Slicer/Slicer

CMake/SlicerDashboardDriverScript.cmake, CMake/SlicerDashboardScript.TEMPLATE.cmake, Extensions/CMake/SlicerExtensionsDashboardScript.TEMPLATE.cmake, Libs/MRML/Core/vtkMRMLParser.h, Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx, Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.h, Libs/vtkITK/vtkITKArchetypeDiffusionTensorImageReaderFile.cxx, Libs/vtkITK/vtkITKArchetypeDiffusionTensorImageReaderFile.h, Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderFile.cxx, Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderFile.h, Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderSeries.cxx, Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderSeries.h, Libs/vtkITK/vtkITKDistanceTransform.cxx, Libs/vtkITK/vtkITKImageToImageFilterUSF.h, Libs/vtkITK/vtkITKIslandMath.cxx, Libs/vtkITK/vtkITKMorphologicalContourInterpolator.cxx, Libs/vtkITK/vtkITKTimeSeriesDatabase.cxx, Libs/vtkITK/vtkITKTimeSeriesDatabase.h, Modules/CLI/CastScalarVolume/CastScalarVolume.cxx, Modules/CLI/ImageLabelCombine/ImageLabelCombine.cxx, Modules/CLI/LabelMapSmoothing/LabelMapSmoothing.cxx, Modules/CLI/MaskScalarVolume/MaskScalarVolume.cxx, Modules/CLI/MergeModels/MergeModels.cxx, Modules/CLI/ModelToLabelMap/ModelToLabelMap.cxx, Modules/CLI/MultiplyScalarVolumes/MultiplyScalarVolumes.cxx, Modules/CLI/ROITest/CLIROITest.cxx, Modules/CLI/ResampleDTIVolume/itkSeparateComponentsOfADiffusionTensorImage.h, Modules/CLI/ResampleDTIVolume/itkSeparateComponentsOfADiffusionTensorImage.txx, Modules/CLI/ThresholdScalarVolume/ThresholdScalarVolume.cxx
Locally tested applying this patch:
```diff
diff --git a/CMake/SlicerDashboardScript.TEMPLATE.cmake b/CMake/SlicerDashboardScript.TEMPLATE.cmake
index df38c564d..2d7443cd5 100644
--- a/CMake/SlicerDashboardScript.TEMPLATE.cmake
+++ b/CMake/SlicerDashboardScript.TEMPLATE.cmake
@@ -56,7 +56,7 @@ set(ADDITIONAL_CMAKECACHE_OPTION "
##########################################
if(NOT DEFINED DRIVER_SCRIPT)
-  set(url https://raw.githubusercontent.com/Slicer/Slicer/master/CMake/SlicerDashboardDriverScript.cmake)
+  set(url https://raw.githubusercontent.com/jcfr/Slicer/finalize-svn-to-github-transition/CMake/SlicerDashboardDriverScript.cmake)
set(dest ${DASHBOARDS_DIR}/${EXTENSION_DASHBOARD_SUBDIR}/${CTEST_SCRIPT_NAME}.driver)
file(DOWNLOAD ${url} ${dest} STATUS status)
if(NOT status MATCHES …
```
=> Finalize svn to GitHub transition

Base/QTCore/qSlicerSlicer2SceneReader.cxx, Base/QTCore/qSlicerXcedeCatalogReader.cxx, Libs/MRML/Core/vtkMRMLScene.cxx, Libs/MRML/Core/vtkMRMLScene.h
```
Building CXX object Libs/MRML/Core/CMakeFiles/MRMLCore.dir/vtkMRMLScene.cxx.o
Slicer/Libs/MRML/Core/vtkMRMLScene.cxx:3510:11: warning: returning address of local temporary object [-Wreturn-stack-address]
return (this->GetErrorMessage().c_str());
^~~~~~~~~~~~~~~~~~~~~~~
```
Resolves: #4729
=> COMP: Remove unused function from Tcl wrapping

Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication.h, Modules/Scripted/DICOM/DICOM.py, Modules/Scripted/DICOMLib/DICOMUtils.py
Adds the urlReceived signal to qSlicerCoreApplication that is emitted when a url beginning with the "slicer://" protocol is processed from the command line.
This also adds handling for "slicer://viewer/..." urls, which will import the specified dataset using DICOMweb.
=> ENH: Add command line url handling and DICOM import from DICOMweb url

CMake/SlicerCPack.cmake
File associations has not been registered since admin access requirement was removed from installer, as a regular user cannot write HKEY_CLASSES_ROOT registry section.
Updated installer so that if installation is done without admin access, file association is saved in HKEY_CURRENT_USER section of registry.
=> BUG: Fix mrml and mrb file association on Windows

SuperBuild/External_python-dicom-requirements.cmake, SuperBuild/External_python-extension-manager-requirements.cmake, SuperBuild/External_python-extension-manager-ssl-requirements.cmake, SuperBuild/External_python-numpy.cmake, SuperBuild/External_python-pip.cmake, SuperBuild/External_python-pythonqt-requirements.cmake, SuperBuild/External_python-requests-requirements.cmake, SuperBuild/External_python-scipy.cmake, SuperBuild/External_python-setuptools.cmake, SuperBuild/External_python-wheel.cmake
Python packages were last updated November 10th, 2019. Outdated python packages were discovered using the below code snippet and then versions, hashes and dependencies were determined and updated.
```powershell
./SlicerPython.exe -m pip list --outdated
```
Tests were run locally on Windows with the same currently failing tests on the dashboard also only being the ones to fail.
@pieper  This includes updating the pydicom version as you indicated you wanted in https://github.com/Slicer/SlicerGitSVNArchive/pull/1254#issuecomment-597660126.
=> Updating Python Packages to latest - March 2020 

Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx
Previously imported segmentations used linearly increasing identifiers when importing (Segment, Segment_1, Segment_2, etc.). Now names are generated using the label value of the segment (Segment_1, Segment_4, Segment_5, etc for label values 1, 4, and 5).
Fixes #4733
=> ENH: Set imported segmentation names from label value

Modules/CLI/CreateDICOMSeries/CreateDICOMSeries.cxx, Modules/Scripted/DICOMLib/DICOMExportScene.py, Modules/Scripted/DICOMPlugins/DICOMSlicerDataBundlePlugin.py
- Slicer Data Bundle exporter can save to user defined path
- Slicer Data Bundle exporter can use custom tags: study description and series description as separate member variables (because they have defaults in the exporter), and an optional tags map to specify any tag
- Allow Slicer Data Bundle exporter to export custom image to the Secondary Capture series
- Add option to Slicer Data Bundle exporter for copying SDB DICOM file to database or not when importing
- Slicer Data Bundle DICOM plugin now sets up subject hierarchy as all other DICOM plugins when importing. Important so that patient/study/series data are stored somewhere in the scene. The series node is the first volume or (non-slice) model or markup
- Allow CreateDICOMSeries module to export Secondary Capture
=> ENH: Improve Slicer Data Bundle DICOM export and import

Modules/Scripted/ScreenCapture/ScreenCapture.py
DCMTK Secondary Capture only supports JPG files, so instead of converting within the application, JPG support has been added to the Screen Capture module
=> ENH: Add JPG support to Screen Capture

Libs/MRML/Core/vtkMRMLStorageNode.cxx
If a model node was empty when the scene was saved then write state of its storage node was set SkippedNoData.
This write state was never updated to Idle, even when later the model was saved successfully.
=> BUG: Fix failed loading of model nodes

Utilities/Templates/Modules/ScriptedCLI/CMakeLists.txt, Utilities/Templates/Modules/ScriptedCLI/TemplateKey.py, Utilities/Templates/Modules/ScriptedCLI/TemplateKey.xml
Python scripted CLI modules are Python scripts that are made possible to run in Slicer simply by providing an XML file that describe the interface.
"Python scripted CLI" module .py file's first line must start with shebang (#!), to distinguish it from a "Python scripted loadable" module.
=> ENH: Added Python scripted CLI module template

Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx
Fixes markup depth peeling by setting the property keys for each internal actor.
Resolves: #4752
=> BUG: Fix depth-peeling for markups

CMake/MIDASCTestUploadURL.cmake
BUG: Generate "midas_ctest_upload_url.url" in Slicer build directory
This commit ensures the URL file generated by different Slicer project
will not be overwritten.
See #4756
=> BUG: Generate "midas_ctest_upload_url.url" in Slicer build directory

CMakeLists.txt, Libs/CMakeLists.txt, Libs/MRML/Core/CMakeLists.txt, Libs/vtkSegmentationCore/CMakeLists.txt, SuperBuild.cmake
Adds the Slicer_USE_SYSTEM_vtkAddon option, which is OFF by default.
This allows extensions with dependencies that rely on vtkAddon to be built in custom apps.
=> ENH: Add option to build Slicer using system vtkAddon

Libs/MRML/Core/CMakeLists.txt, Libs/vtkITK/CMakeLists.txt, SuperBuild.cmake
vtkAddonTargets.cmake is not generated when building Slicer_BUILD_vtkAddon is on.
When built externally, vtkAddonTargets.cmake needs to be included manually, since it is not included in vtkAddonConfig.cmake.
=> COMP: Fix compilation when Slicer_BUILD_vtkAddon is OFF

Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx, Modules/Loadable/VolumeRendering/MRML/vtkMRMLVolumeRenderingDisplayNode.cxx, Modules/Loadable/VolumeRendering/MRML/vtkMRMLVolumeRenderingDisplayNode.h, Modules/Loadable/VolumeRendering/Testing/Cxx/vtkMRMLVolumeRenderingMultiVolumeTest.cxx, Modules/Loadable/VolumeRendering/Widgets/qSlicerVolumeRenderingModuleWidget.cxx
vtkMRMLVolumeRenderingDisplayNode::SetAndObserveVolumeNodeID method was removed, as display node base class already maintains a pointer to the displayed (volume) node.
Updated migration guide (https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer#Volume_rendering).
Fixes #2628.
=> ENH: Remove redundant reference to volume node in volume rendering display node

Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorDrawEffect.py, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractLabelEffect.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractLabelEffect.h
The polydata for the draw effect was rasterized in the world coordinate system.
If the segmentation node was under a transform node, the transform would not be taken into account when modifying the segment.
This commit transforms the rasterized image to the same coordinate system as the segmentation before appending it to the modifier labelmap.
re #4685
=> BUG: Apply segmentation parent transform to draw effect

Libs/MRML/Widgets/Testing/qMRMLSceneTransformModelTest1.cxx
qMRMLSceneTransformModelTest1 crashed on exit because deleted items are attempted to be accessed.
Deleting tree widgets before the application quits solved the issue.
=> BUG: Fix crash in qMRMLSceneTransformModelTest1

Modules/Loadable/Segmentations/EditorEffects/Python/AbstractScriptedSegmentEditorEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorLevelTracingEffect.py, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.h
The position of the mouse in IJK coordinates, as well as the position of the polydata did not previously take into account the parent transform of the segmentation.
re #4685
=> BUG: Apply segmentation parent transform to level-tracing effect

Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorIslandsEffect.py
The position of the mouse in IJK coordinates did not previously take into account the parent transform of the segmentation.
re #4685
=> BUG: Apply segmentation parent transform to island effect

CONTRIBUTING.md
This updates the contributing doc with some additional changes about the usage of the Slicer forum instead of the mailing list, using github issues, and the transition of information about commit messages from the Slicer wiki to a github hosted document.
I don't believe this work has any duplication of work in #4771 as the contributing doc there is just being converted from MD to RST.
=> Various updates to contributing doc

Modules/Loadable/Segmentations/EditorEffects/Python/AbstractScriptedSegmentEditorAutoCompleteEffect.py, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
- Modified events are now blocked during parameter node initialization
- Error message is not displayed if no parameter node is found during updateWidgetFromMRML
- More thorough error checking for parameter and segmentation nodes in autocomplete effect
fixes #4662, #4664
=> BUG: Prevent segment editor error messages on scene close

CONTRIBUTING.md
This avoids the duplication of URL links that are often fairly long in length
Per discussion at https://github.com/Slicer/Slicer/pull/4783#discussion_r400606739.
=> DOC: Add common reference links to bottom of contributing

Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
The choice of layer for the scalar bar in the data probe module was not
exposed in the settings, therefore it was not possible to set or get
this value programmatically, [as discussed in the forum](https://discourse.slicer.org/t/show-scalar-bar-programmatically/9842).
=> ENH: Expose scalar bar layer in DataProbe settings

SuperBuild.cmake
This fixes issue described in https://github.com/Slicer/vtkAddon/pull/5#issuecomment-604486829
=> COMP: Ensure vtkAddons sources are downloaded before Slicer inner build starts

SuperBuild/External_ITK.cmake
```
$ git shortlog v5.1rc01..v5.1rc03 --no-merges
Adam Rankin (1):
COMP: Fixing compilation of ITK/OpenCV video bridge
Antoine Robert (1):
ENH: Add boundary condition getters and setters
Brad King (1):
BUG: Update URL for GitSetup hooks checkout
Brad T. Moore (1):
ENH: Added explicit test of VectorImage with ExpandImageFilter
Bradley Lowekamp (32):
BUG: Use unique_ptr::reset() to delete held pointer
COMP: Remove unused region parameter in default copy constructor
ENH: Update to latest GoogleTest release tag
COMP: Disable GTest using threads
ENH: Enable CircleCI to retrieve ccache on pull requests
BUG: Set ConnectedComponentImageFilter's initial background value to zero.
STYLE: Move constructor to hxx, use inline initialization for ivars
COMP: Fix DCMTK unused CMake …
```
=> ENH: Update ITK version from v5.1rc01 to v5.1rc03

SuperBuild/External_SimpleITK.cmake
This commit fixes regression introduced in 0a8f06c62 (ENH: Update ITK
version from v5.1rc01 to v5.1rc03)
```
$ git shortlog 9fbcf2e9b..7ce1f1867 --no-merges
Boo Irizarry (3):
update workflow contrubiting.md file
update contributing file
update contributing file again
Bradley Lowekamp (69):
Load SimpleITK version used in SimpleITKExamples sub-project
Set SimpleITK version to 2.0.0
Set more restrictive test template globs
Update ITK Superbuild version along the 5.1 development branch
Suppress self assignment warning in Image tests.
For external project add required flags to preprocessor
Update Superbuild ITK version along ITKv5.1 development
Update ITK along 5.1 development
Update ITK along 5.1 development
Update MeanImageFilter wrapping to directly use VectorImage
Add …
```
=> COMP: Update SimpleITK to build error related to ITK version update

Applications/SlicerApp/Testing/Python/AtlasTests.py, Applications/SlicerApp/Testing/Python/DICOMReaders.py, Applications/SlicerApp/Testing/Python/JRC2013Vis.py, Applications/SlicerApp/Testing/Python/RSNA2012ProstateDemo.py, Applications/SlicerApp/Testing/Python/RSNAQuantTutorial.py, Applications/SlicerApp/Testing/Python/RSNAVisTutorial.py, Applications/SlicerApp/Testing/Python/ScenePerformance.py, Applications/SlicerApp/Testing/Python/ShaderProperties.py, Applications/SlicerApp/Testing/Python/SliceLinkLogic.py, Applications/SlicerApp/Testing/Python/Slicer4Minute.py, Applications/SlicerApp/Testing/Python/SlicerRestoreSceneViewCrashIssue3445.py, Applications/SlicerApp/Testing/Python/slicerCloseCrashBug2590.py, Base/Python/slicer/util.py, Extensions/Testing/ScriptedLoadableExtensionTemplate/ScriptedLoadableModuleTemplate/ScriptedLoadableModuleTemplate.py, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest1.py, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py, Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyFoldersTest1.py, Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyGenericSelfTest.py, Modules/Scripted/DataProbe/DataProbe.py, Modules/Scripted/SampleData/SampleData.py
Also improved SampleData.downloadFromSource to not load scenes many times if download or loading fails (by default, download and load is only attempted up to 3 times).
re #4602
=> ENH: Update sample data URLs to use GitHub instead of Midas

CMake/SlicerConfig.cmake.in, CMake/SlicerInitializeBuildType.cmake
This commit conditionally sets CMAKE_DEFAULT_BUILD_TYPE variable to fix
configuration error <s>on Windows</s> using CMake >= 3.17.
This change is required because Slicer build-system introduced the
variable CMAKE_DEFAULT_BUILD_TYPE in Nov 2017 (see c808da1) and it triggers
a configuration error following the introduction of the same variable in
CMake 3.17.
See https://cmake.org/cmake/help/latest/variable/CMAKE_DEFAULT_BUILD_TYPE.html
Error fixed by this commit:
```
CMake Error:
Generator
Visual Studio 15 2017
does not support variable
CMAKE_DEFAULT_BUILD_TYPE
but it has been specified.
```
Custom Slicer application may have to be updated to conditionally set
CMAKE_DEFAULT_BUILD_TYPE based on the value of the GENERATOR_IS_MULTI_CONFIG
global property.
Fixes #4798
=> COMP: Fix configuration with CMake >= 3.17. CMAKE_DEFAULT_BUILD_TYPE can not be specified

Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Some CT images contain multiple acquisitions in the same series, distinguished by Acquisition Number (0020,0012) DICOM tag.
Adding this tag to the list of subseries tags in DICOMScalarVolumePlugin allows loading frames corresponding to specific acquisition numbers.
=> ENH: Allow splitting image subseries using acquisition number tag

Base/QTGUI/Resources/UI/qSlicerModulePanel.ui
Based on the discussion at https://discourse.slicer.org/t/making-the-help-tab-as-the-default-tab-to-open/10944
This PR sets the "Help" tab to be the default instead of the "Acknowledgement" tab. It was set to "Acknowledgement" in https://github.com/Slicer/Slicer/commit/aa4d34d33b2904033a3400ba0ea4a9d525085d9c which added that tab, but it was probably the original intent to maintain "Help" as the default since it is also the first tab.
=> ENH: Set Help tab as the default instead of Acknowledgement

Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
Starting a debug build of Slicer would result in a warning message, since the number of single steps for the slider would exceed the max integer value.
Fixed in two ways, although either would independently remove the warning:
- Increase the minimum resolution of the slider to a value that does not cause the integer overflow (0.000000000001 -> 0.00000001).
- When calculating the offset resolution, the slice bounds are not taken into account if the size of the bounds is zero.
fixes #4807
=> BUG: Reduce startup warnings from qMRMLSliceControllerWidget

Modules/Scripted/DICOMLib/DICOMUtils.py
Only the volume nodes were returned by the DICOMUtils.loadLoadables, which was confusing given the documentation and variable names, and also incorrect because many other types of nodes can be loaded from DICOM (fiducials, segmentations, beams, etc.). This fix allows any non-storage and non-display type node to be included in the returned list.
=> BUG: Return all data nodes loaded by DICOMUtils.loadLoadables

SuperBuild.cmake
$ git shortlog af1d32..ab95838 --no-merges
ENH: Add plane fit functions to vtkAddonMathUtilities
Rafael Palomar (4):
ENH: Enable installation of development files
ENH: Enable installation of python files
ENH: Enable project configuration file for intstall tree
COMP: Fix build of python wrapping as a standalone project
=> ENH: Update to latest vtkAddon

Modules/Loadable/Colors/Logic/vtkSlicerColorLogic.cxx
The "Application Settings" menu is under "Edit", not "View". This directs the user to the right part of the UI.
I do not know when this code runs. I do not know if "Application Settings" menu is _always_ under "Edit". This patch is completely untested. It fails the pre-commit hook (line length).
=> BUG: Change GUI instructions in error message

Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake
This fixes the failing [cmake_slicer_generate_extension_description_test](http://slicer.cdash.org/testDetails.php?test=9961228&build=1881141). The test was failing because of different line endings between the files.
Since the test was passing as of March 10th and then failing as of March 13th, this corresponds exactly with the transition from SVN to Git.  I believe during this transition `extension_description_with_depends.s4ext` and `extension_description_without_depends.s4ext` went from having `LF` line endings with SVN to having `CRLF` line endings with git.
@lassoan This will essentially revert your commit https://github.com/Slicer/Slicer/commit/1c469b3a121fe977755a613a40eb067e5da53d43.  I'm not really sure of the purpose of that commit, but if you would like to maintain it then I …
=> BUG: Fix failing generate extension description test

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
The underlying mesh used for pathfinding wasn't updated when the mesh used in the model node was changed.
Fixed by calling OnSurfaceModelNodeChanged instead of UpdateSurfaceScalarVariables when the ShortestDistanceSurfaceNode, or the underlying mesh is modified.
fixes #4817
=> BUG: Update curve path when mesh is changed

CMake/SlicerExtensionCPack.cmake
This commit fixes warning like the following:
```
-- Checking if extension type is SuperBuild
-- Checking if extension type is SuperBuild - true
-- Extension fixup mode: updating CPACK_INSTALL_CMAKE_PROJECTS with <cpack_bundle_fixup_directory>
CMake Warning (dev) in CMakeLists.txt:
No project() command is present.  The top-level CMakeLists.txt file must
contain a literal, direct call to the project() command.  Add a line of
code such as
project(ProjectName)
near the top of the file, but after cmake_minimum_required().
CMake is pretending there is a "project(Project)" command on the first
line.
```
=> COMP: Fix macOS extension packaging warning

Base/QTCLI/Testing/qSlicerPyCLIModuleTest1.cxx, Modules/Loadable/VolumeRendering/MRML/vtkMRMLVolumePropertyNode.cxx
Now that C++11 is mandatory, remove conditional code
for older language support.
=> STYLE: Remove conditional code for CXX< 201103L

CMake/SlicerCPack.cmake
Fixes #4279 
Adds "ManifestDPIAware true" to CPACK_NSIS_DEFINES.  The variable value
must be as a single string to avoid inserting semicolons into the scripts
Before:
After:
["Before" installer](https://data.kitware.com/#item/5e94a71a2660cbefbab464c2)
["After" installer](https://data.kitware.com/#item/5e94a68c2660cbefbab4625b)
=> ENH: Use ManifestDPIAware to improve the look of the Windows installer

SuperBuild.cmake
Summary:
* BRAINSTools v5.2.0 now uses C++11, and ITKv5.
* This version compiles and passes all Slicer regression tests.
* Several outdated programs have been removed from the build tree.
```
$ git shortlog d87ea8f35..da5d1e9da --no-merges
Ali Ghayoor (1):
BUG: three landmarks are enough for rigid transformation in BRAINSLandmarkInitializer
COMP: Fix build errors with current ITK master
Hans J. Johnson (132):
ENH: ARCHIVE BRAINSDemonWarp as not needed.
COMP: Updated `enum` to `enum class` for c++11
STYLE: Enforce ITK style defined by .clang-format
COMP: ANTs git has was invalid pre-merge value
ENH: ITKv5 changes for ResampleImage.
ENH: Make verbosity of BRAINSFit much less by default
COMP: BRAINSDemonWarp is in the ARCHIVE build
STYLE: Use range-based …
```
=> ENH: Update BRAINSTools to version 5.2.0

SuperBuild/External_ITK.cmake
Fix was contributed in upstream ITK in InsightSoftwareConsortium/ITK#1727
```
$ git shortlog v5.1rc03..35704a458d --no-merges
COMP: Fix -Wstrict-overflow warning in itkImageRegionConstIteratorWithIndex
```
=> COMP: Update ITK to include -Wstrict-overflow warning fix

Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneWidget.h
Describe function overrides using the override
keyword from C++11.
cd ${BLDDIR}
run-clang-tidy.py -extra-arg=-D__clang__ -checks=-*,modernize-use-override  -header-filter=.* -fix
=> STYLE: Use override statements for C++11

CMake/SlicerVersion.cmake
This commit updates SlicerVersion module to fix setting of commit offset variables
and ensures the variable Slicer_MAIN_PROJECT_COMMIT_COUNT defined in
vtkSlicerVersionConfigure.h is correct.
Indeed, if the main application is "Slicer" then we copy Slicer_WC_COMMIT_COUNT_OFFSET
and Slicer_REVISION_TYPE values from Slicer to the main application, so Slicer
values need to be set first.
See https://github.com/Slicer/Slicer/pull/4784#discussion_r400621292
=> COMP: Fix setting of Slicer_MAIN_PROJECT_COMMIT_COUNT in vtkSlicerVersionConfigure.h

Base/QTCore/qSlicerSceneBundleReader.cxx, Libs/MRML/Core/vtkMRMLScene.cxx, Libs/MRML/Core/vtkMRMLScene.h, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Modules/Loadable/Data/qSlicerSceneWriter.cxx
Local build successful and MRB tests pass:
```
$ ctest -R MRB -V
[...]
The following tests passed:
py_SlicerMRBMultipleSaveRestoreLoopTest
py_SlicerMRBMultipleSaveRestoreTest
py_SlicerMRBSaveRestoreCheckPathsTest
100% tests passed, 0 tests failed out of 3
Total Test time (real) =  63.90 sec
```
=> ENH: Update MRML scene API adding support for read/write of MRML bundle

Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx
Adds the needed Start/End SliceNodeInteraction flag to make sure
the zoom change is picked up by SliceLinkLogic
Closes #4720
=> BUG: Mousewheel zoom should be observed by slice link

SuperBuild.cmake, SuperBuild/External_VTK.cmake
This commit fixes a regression introduced in 39054218c3 (ENH: Update
BRAINSTools from v5.0.0 to v5.2.0)
List of BRAINSTools changes:
```
$ git shortlog da5d1e9d..3fe08e96 --no-merges
[backport BRAINSia/BRAINSTools#473] COMP: Fix windows compilation adding missing check_avx_flags function
```
```
$ git shortlog 9853cac9f9..8b29c955d8 --no-merges
[backport MR-6754] COMP: Rename CheckCXXSourceRuns CMake module bundled in VTK
[backport MR-6754] COMP: Rename CHECK_CXX_SOURCE_RUNS to avoid conflict with CMake implementation
```
=> COMP: Update BRAINSTools and VTK to fix windows CMake configuration error

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h
When loading a scene, the parent transform of the model node wasn't used unless it was modified.
Fixed by moving the code for updating the polydata transform to a new function (OnSurfaceModelTransformChanged).
The function is called when a node reference for the surface node is added or modified, which fixes the behavior on scene load.
=> BUG: Fix curve node surface interpolation when loading scene

Libs/MRML/Core/vtkMRMLModelNode.cxx, Libs/MRML/Core/vtkMRMLNode.cxx, Libs/MRML/Core/vtkMRMLNode.h, Libs/MRML/Core/vtkMRMLSegmentationNode.cxx, Libs/MRML/Core/vtkMRMLTextNode.cxx, Libs/MRML/Core/vtkMRMLTransformNode.cxx, Libs/MRML/Core/vtkMRMLVolumeNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx
For example, for transform node, it is not enough to observe vtkCommand::ModifiedEvent.
In that case, the list will contain both vtkCommand::ModifiedEvent
and vtkMRMLTransformableNode::TransformModifiedEvent.
=> ENH: Update MRML node API to allow listing of node content modification events

Base/Python/slicer/tests/compute-checksum.txt, Base/Python/slicer/tests/test_slicer_util_without_modules.py
This fixes the failing [py_nomainwindow_test_slicer_util_without_modules](http://slicer.cdash.org/testDetails.php?test=9961479&build=1881141).  The test was failing due to an invalid expected checksum for the `compute-checksum.txt` file.
Since the test was passing as of March 10th and then failing as of March 13th, this corresponds exactly with the transition from SVN to Git.  I believe during this transition `compute-checksum.txt` went from having `LF` line endings with SVN to having `CRLF` line endings with git.
This is similar to #4814 as it is a fix for a test that started to fail due to a change in a file's line endings.
=> BUG: Fix failing slicer_util_without_modules test

Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx
Closes #4805 
Per the Tuesday discussion, I have replaced the asserts with warnings.  I've also added a check on scene importing when updating add volume render nodes.
Did not need to listen for the end of the scene import to update the volume rendering.  The update is also triggered by OnMRMLNodeModified, so it will occur after the scene import anyway.
=> Fix volume rendering link crash

Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
Previously markup nodes created using vtkMRMLMarkupsDisplayableManager::CreateNewMarkupsNode would use the same name for all nodes.
Now, vtkMRMLScene::GenerateUniqueName is used to give the markups names like: P, P_1, P_2, etc.
=> ENH: Generate unique name for markups created by displayable manager

SuperBuild/python_configure_python_launcher.cmake
Update associated settings to make sure it exits with an error message
indicating PythonSlicer should be used.
Fixes #4843
=> ENH: Mark SlicerPython as obsolete

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx
This commit fixes warning introduced in b39762c4e (BUG: Fixed adjustment
of markups visibility and color in subject hierarchy)
=> COMP: Fix -Wunused-but-set-variable warning in vtkSlicerMarkupsWidgetRepresentation

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx
This commit fixes warning introduced in b39762c4e (BUG: Fixed adjustment
of markups visibility and color in subject hierarchy)
=> COMP: Fix -Wunused-but-set-variable warning in vtkSlicerMarkupsWidgetRepresentation2D

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx
This commit fix warning introduced in ceaddc05b (ENH: Add interaction
handles for transforming markup positions)
=> COMP: Fix -Wunused-variable warning in vtkSlicerMarkupsWidgetRepresentation2D

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
This commit fix warning introduced in ceaddc0 (ENH: Add interaction
handles for transforming markup positions)
=> COMP: Fix -Wunused-parameter warnings in vtkSlicerMarkupsWidget

commit-msg, pre-commit
https://stackoverflow.com/questions/53121208/git-dir-no-longer-set-in-pre-commit-hooks
Using $GIT_DIR, when it has not been explicity set, in pre-commit hooks
did work pre Git 2.18, however this was an unexpected side effect and
not intended behavior.
A change in GIT 2.18 caused this to stop working. In the link a
contributor mentions that the correct way to get the location of the
.git directory in a pre-commit hook (or any hook for that matter) is to
use this git command
```bash
git rev-parse --git-dir
```
=> BUG: Fix git hooks for git 2.18 and greater

Modules/Scripted/DICOMLib/DICOMUtils.py
Sometimes it's useful to store only the instance uid of a slice,
for example with a measurement, but even if you know the
seriesUID for that instance, it doesn't always map to a specific
MRML node, so you may end up loading a full set of nodes
corresponding to different subseries when you only needed
to load the one with this instance.
With this change the loadables are filtered so that only
the highest confidence one containing the instance is
loaded.
=> ENH: add DICOMUtils.loadByInstanceUID method

SuperBuild/External_OpenSSL.cmake
The SDK must be provided in the environment for OpenSSL to compile.
OpenSSL include directory name is 'openssl' all lower case letters.  Use that to avoid 100's of compiler warnings about case mis-match.
=> Fix OpenSSL build issues on Mac 10.15 XCode 11 clean OS

SuperBuild.cmake
Minor compiler warning addressed related to
implicit conversion of vnl_matrix.
=> COMP: Fix BRAINSTools compiler warning of deprecated feature

SuperBuild/External_OpenSSL.cmake, SuperBuild/OpenSSL_resolve_e_os2_symlink.cmake
This commit resolves the symlink to e_os2.h header to address
the following compiler warning:
```
In file included from /Users/johnsonhj/src/Slicer-build/curl/lib/urldata.h:79:
Slicer-build/OpenSSL/include/openssl/pem.h:62:11: warning: non-portable path to file '<OpenSSL/e_os2.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
^~~~~~~~~~~~~~~~~
<OpenSSL/e_os2.h>     <- What Slicer/Superbuild provided
```
See #4875
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
=> COMP: Fix OpenSSL -Wnonportable-include-path warning

Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
This fix loads subseries if there's only one choice and
the there are geometry warnings detected on the full
series.
See: https://github.com/Slicer/Slicer/issues/4872
=> BUG: fix dicom subseries priorities

Base/QTApp/qSlicerMainWindow.cxx, Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication.h, Base/QTGUI/qSlicerApplication.cxx, Base/QTGUI/qSlicerApplication.h, Libs/MRML/Core/vtkMRMLInteractionNode.cxx, Libs/MRML/Core/vtkMRMLInteractionNode.h, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Libs/MRML/Widgets/Resources/UI/qMRMLChartViewControllerWidget.ui, Libs/MRML/Widgets/Resources/UI/qMRMLPlotViewControllerWidget.ui, Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui, Libs/MRML/Widgets/Resources/UI/qMRMLTableViewControllerWidget.ui, Libs/MRML/Widgets/qMRMLLayoutManager.cxx, Libs/MRML/Widgets/qMRMLNodeComboBox.cxx, Libs/MRML/Widgets/qMRMLNodeComboBox.h, Libs/MRML/Widgets/qMRMLNodeComboBox_p.h, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx, Libs/MRML/Widgets/qMRMLSliceWidget.cxx
This pull request makes "Edit current X" menu in MRML node selectors work, without the need for developers to implement a custom event handler.
Now it is enough to enable "editEnabled" property on the node selector to get a working "edit" menu item.
=> ENH: Make qMRMLNodeComboBox node editing easier

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel.cxx
If a null QStandardItem* was passed to updateSubjectHierarchyItemFromItemData, it would cause a crash.
Fixed by adding a null-pointer check and an error message.
=> BUG: Fix crash in qMRMLSubjectHierarchyModel

SuperBuild/External_OpenSSL.cmake
This commit fixes a regression introduced in  ddeb0a33a (COMP: Fix
OpenSSL build on Mac 10.15 XCode 11.4.1 (#4857)) originally intended
to fix issue #4681
Setting the SDKROOT environment variable worked as expected on a regular
developer build but failed on a dashboard build where the invocation of
"make" is wrapped using a "launcher" [1]
This commit addresses the issue by writing a CMake script that will set
the environment and then invoke make.
Last, since  file descriptors expect by the make jobserver are not kept
open by the CMake process, the build script explicitly unset MAKEFLAGS
to avoid "warning: -jN forced in submake: disabling jobserver mode."
For more details, see [2]
[1] https://cmake.org/cmake/help/latest/manual/ctest.1.html#ctest-build-step
[2] …
=> COMP: Fix OpenSSL build on macOS setting SDKROOT in build script

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel.cxx
qMRMLSubjectHierarchyModel::updateSubjectHierarchyItemFromItem could cause a crash if it was called with a nullptr item argument.
Fixed by adding a nullptr check to the start of the function.
=> BUG: Add nullptr check to updateSubjectHierarchyItemFromItem

SuperBuild.cmake
Changes included:
```
$ git shortlog  f4ac832..4e0a9f9
COMP: Fix -Winconsistent-missing-override
Steve Pieper (1):
COMP: return nullptr not false
```
=> COMP: Update SurfaceToolbox to fix build error on MacOS

SuperBuild.cmake
```
$ git shortlog 4e0a9f961..ec6fe416b --no-merges
Jean-Christophe Fillion-Robin (8):
STYLE: Update Simplify.h converting tabs to spaces
COMP: Fix -Wsign-compare warnings in Simplify.h and Decimation.cxx
COMP: Fix -Wunused-* warnings in Simplify.h
COMP: Fix -Wparentheses warning in Simplify.h
STYLE: Remove use of "loopi" macro in Simplify.h
STYLE: Remove use of "loopk" macro in Simplify.h
STYLE: Remove use of "static_cast" in Simplify.h
STYLE: Remove use of "loopj" macro in Simplify.h
```
=> COMP: Update SurfaceToolbox to fix warnings

Modules/Loadable/Colors/Resources/UI/qSlicerColorsModuleWidget.ui, Modules/Scripted/DataProbe/DataProbeLib/Resources/UI/settings.ui
From https://discourse.slicer.org/t/renaming-scalar-bar-to-color-bar/11274
| DataProbe module Before | DataProbe module After |
|------------------------------|----------------------------|
|![dataprobe-module-scalar-bar](https://user-images.githubusercontent.com/15837524/80286687-d9aa8b00-86fa-11ea-959c-c572f06b2016.png)|![dataprobe-module-scalar-bar-2](https://user-images.githubusercontent.com/15837524/80286692-e0390280-86fa-11ea-95a2-f9585c522d57.png)|
| Colors module Before | Colors module After |
|-------------------------|------------------------|
|![color-module-scalar-bar](https://user-images.githubusercontent.com/15837524/80286696-ec24c480-86fa-11ea-82ad-3e86bc404b66.png)|![color-module-scalar-bar-2](https://user-images.githubusercontent.com/15837524/80286700-f050e200-86fa-11ea-8f …
=> STYLE: Rename "ScalarBar" to "Color Scalar Bar" in the GUI

Base/QTGUI/qSlicerSaveDataDialog.cxx, Base/QTGUI/qSlicerSaveDataDialog_p.h
When user typed an invalid filename in save data dialog (such as just a filename base without extension or with an invalid extension) then the validator rejected it and user had to either forced to type the extension or revert to the original value. When user clicked on save after entering an invalid filename (without pressing enter or escape) then the filename was reverted to the original without warning to the user.
It was also not possible to choose a different file extension just by typing a filename with a different extension.
This commit fixes these problems and makes consistent with other software (Notepad, Word, Visual Studio Code, Gimp, Camtasia, Snagit):
- If a known file extension is entered but not the one that is selected in the listbox then the entered filename is used as …
=> ENH: Always use filenames that user typed in save data dialog

Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
Invokes RepresentationModified after derived representations are reconverted in vtkSlicerSegmentationsModuleLogic::SetBinaryLabelmapToSegment(). This ensures that the display manager is kept up-to-date.
Fixes #4895
=> BUG: Fix segment closed surface display after smoothing/margin effect

Modules/Scripted/ScreenCapture/ScreenCapture.py
When creating image series in ScreenCapture module, deleteTemporaryFiles() would always be called at the end of the try: block. This should not be done if "image series" is selected.
=> BUG: ScreenCapture- image series files inadvertently deleted 

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
Due to changes in the input of the curve generator, curve points were being returned in the world coordinate system. Fixed by passing the input points in the local coordinate system.
This also ensures that the output curve transform is up-to-date if the parent transform node changes.
=> BUG: Return GetCurvePoints in the correct coordinate system

Modules/Loadable/Texts/Widgets/Resources/UI/qMRMLTextWidget.ui
Monospaced font for `qMRMLTextEditWidget` as suggested in #4925. This is done by [setting the font family to _Courier_](https://forum.qt.io/topic/35999/solved-qplaintextedit-how-to-change-the-font-to-be-monospaced/5).
**Question:** `QTextEdit` has a property `acceptRichText` which defaults to _true_. Therefore, if you paste formatted text into our widget, the content will have formatting too. Should we set `acceptRichText` to _false_ to make clear that the data is plain text? (The function `void qMRMLTextWidget::updateMRMLFromWidget()` converts content to plain text).
=> ENH: Texts module with monospaced font

Libs/vtkTeem/vtkDiffusionTensorMathematics.cxx
This is related to an issue reported here: https://github.com/SlicerDMRI/SlicerDMRI/issues/128
This affects the calculation of diffusion scalar maps to have nan values, subsequently preventing the calculation of ROI-based statistics using Label Statistics module. 
Simple fix is to remove nan values. 
Regards,
Fan
=> ENH: remove NAN values in DiffusionTensorScalarMaps

SuperBuild/External_VTK.cmake
$ git shortlog --no-merges dd7e051..a81d1af
Andrew J. P. Maclean (1):
[backport MR-6943] Qt 5.15 needs the include file QPainterPath
=> COMP: Update VTK to fix build with Qt 5.15.0

Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
Volume rendering display nodes did not check subject hierarchy visibility if FolderDisplayOverrideAllowed was enabled.
This changes the vtkMRMLVolumeRenderingDisplayableManager to show/hide the volume rendering display node based on subject hierarchy when FolderDisplayOverrideAllowed is true.
=> ENH: Add FolderDisplayOverrideAllowed support for volume rendering

Libs/vtkSegmentationCore/vtkSegmentation.cxx
Calling vtkSegmentation::ApplyLinearTransform() or vtkSegmentation::ApplyNonLinearTransform() would apply the transform to the master representation once for each segment in the segmentation. For shared representations, this would cause the data object to be transformed multiple times.
Fixed by keeping track of which data objects had already been transformed, and only transforming each once.
Fixes: #4944
=> BUG: Fix ApplyXTransform functions to transform each data object once

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx
Curve diameter so far could not be set independently form markup control point diameter, but to use curves to show e.g. intravascular catheter with specific diameter, we need the ability to set the displayed curve diameter to an absolute value.
We also need to keep the ability to specify the size relative to the markups size, because for some other use cases that is the preferable option, so we have similar options for this as for glyph sizing:
- LineThickness (already existed, size relative to glyph)
- LineDiameter (new double value, absolute value in length unit, such as mm)
- CurveLineRadiusMode (enum: UseLineThickness and UseLineDiameter for now, but later we may add more options, such as vary radius according to scalar value associated with control points)
=> ENH: Add absolute way to specify markups curve and line thickness

SuperBuild.cmake
$ git shortlog 8030089..0902230
Kyle Sunderland (8):
BUG: Fix incorrect casting of Dynamic modeler Mirror rule input plane
BUG: Fix incorrect end-cap position
ENH: Move PlaneCut input model to top of inputs
BUG: Preserve surface normals when cutting planes in dynamic modeler
ENH: Manually specify end-cap normals when cutting with planes
ENH: Rename DynamicModeler *Rule classes to *Tool
COMP: Fix warning 'not all control paths return a value'
STYLE: Add additional comments to vtkSlicerDynamicModelerPlaneCutTool
=> ENH: Update SurfaceToolbox

SuperBuild.cmake
```
$ git shortlog 0902230..86827c5
COMP: Fix -Wunused-* warnings
COMP: Fix -Wsign-compare in vtkSlicerDynamicModelerTool
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
```
=> COMP: Fix warnings in SurfaceToolbox

CMake/FindVcvars.cmake
This fixes a configure failure noticed for the SlicerRadiomics extension (see [here](http://slicer.cdash.org/viewConfigure.php?buildid=1927747)) due to the recent upgrade of the compiler used on the factory Windows build machine.
```
-- Setting Vcvars_MSVC_VERSION to '1924' as MSVC_VERSION was `1924`
CMake Error at D:/D/P/Slicer-0/CMake/FindVcvars.cmake:161 (message):
failed to convert msvc_version [1924].  It is not a known version number.
```
=> COMP: Update FindVcvars with newer compiler versions

SuperBuild/External_CTKAppLauncherLib.cmake
```
$ git shortlog --no-merges ec98a50..b1d6dad
COMP: Fix deprecation warning C4996
Jean-Christophe Fillion-Robin (7):
ENH: Reduce launcher executable size on Linux by stripping symbols
.travis: Fix build installing installing latest rvm keys
CTKAppLauncher v0.1.26
Begin post-v0.1.26 development [ci skip]
BUG: Fix stripping of packaged launcher executable on Linux
CTKAppLauncher v0.1.27
Begin post-v0.1.27 development [ci skip]
```
=> COMP: Update CTKAppLauncherLib

Modules/Loadable/Units/Logic/vtkSlicerUnitsLogic.cxx
By default, length values over 100mm were displayed without decimal digits by default (precision=3), which may be insufficient for some medical applications, since measurement of such lengths is no uncommon and image resolution is usually in the magnitude of 0.1mm.
Example: 104.123mm distance was displayed as "104.mm" before this change and it is displayed as "104.2mm" after this change.
=> ENH: Set default display precision of length unit to 4

SuperBuild/External_VTK.cmake
```
$ git shortlog a81d1af082..a44e00db0d --no-merges
COMP: Remove vtk-m submodule
```
To remove vtkm from existing VTK source checkout:
```
git submodule deinit -f -- ThirdParty/vtkm
rm -rf .git/modules/VTK-m/
git rm -rf ThirdParty/vtkm/
```
=> COMP: Update VTK to remove vtk-m dependency

Base/Python/slicer/util.py, Modules/Scripted/DICOMLib/DICOMUtils.py
DICOM databases are sometimes stored in long paths, which are not handled well on Windows, and the result in these cases is files not found.
The new longPath function in slicer.util converts the path string to one that can be safely used on Windows for paths longer than 260 characters.
Probably this won't work like this on Mac and Linux, so if after the discussion we decide to use this, then it will have to be changed to be only used on Windows.
Note that in the PR I moved some functions in slicer.util that were on the bottom of the file in the wrong group (there are groups in util.py like UI, Modules, VTK, etc.) to their corresponding groups.
=> BUG: Make using long paths safe in python !WIP!

Libs/MRML/Widgets/qMRMLTreeView.cxx
This commit fixes a regression introduced in 2f932d8 / r28510 (ENH: Remove
model hierarchy nodes) and ensures visibility of both display and displayable
nodes can be toggled using a qMRMLTreeView associated with a "Displayable"
scene model (qMRMLSceneDisplayableModel)
=> BUG: Update qMRMLTreeView to fix visibility toggle

SuperBuild/External_VTK.cmake
$ git shortlog a843afe3ac..e1be324636 --no-merges
[backport MR-6941] Fix infinite loop in vtkContourTriangulator
=> BUG: Update VTK to fix infinite loop in vtkContourTriangulator

CMakeLists.txt, SuperBuild/External_ITK.cmake
This closes #4866.
There is really no option except for ITK v5.  This can be brought back sometime in the future if there is ever a need to support multiple versions during a ITK v5/v6 transition
Also included minor commit to update version of ITK to find when using system ITK as part of build process.
=> COMP: Remove Slicer_ITK_VERSION_MAJOR configure option

Libs/MRML/Widgets/Testing/qMRMLLayoutManagerTest1.cxx, Libs/MRML/Widgets/Testing/qMRMLLayoutManagerVisibilityTest.cxx, Libs/MRML/Widgets/Testing/qMRMLLayoutManagerWithCustomFactoryTest.cxx
This commit fixes warnings like the following:
```
/path/to/Slicer/Libs/MRML/Widgets/Testing/qMRMLLayoutManagerTestHelper.cxx:13:6: warning: ‘bool {anonymous}::checkViewArrangement(int, qMRMLLayoutManager*, vtkMRMLLayoutNode*, int)’ defined but not used [-Wunused-function]
bool checkViewArrangement(int line, qMRMLLayoutManager* layoutManager,
^
```
=> COMP: Fix -Wunused-function warnings in qMRMLLayoutManager tests

Modules/Loadable/VolumeRendering/Resources/UI/qSlicerVolumeRenderingModuleWidget.ui
Clicking the check box on the SynchronizeScalarDisplayNodeButton now changes the toggle state of the button. Checked causes the button to be toggled "On" and unchecked causes it to be toggled "Off".
Fixes #4717
=> ENH: Control volume rendering synchronize scalar button with check box

Base/QTGUI/qSlicerDarkStyle.cxx
This is part of #4803 specifically addressing color palette values.  There are still some other issues as described in https://github.com/Slicer/Slicer/issues/4803#issuecomment-643808471.  With these changes the dark mode palette feels much much more familiar to other applications with a dark mode.  The current Dark Slicer palette has been very hard on the eyes and a reason I did not use it, but with these changes I would probably actually begin using dark mode.
| Before | After |
|--------|-------|
|![slicer-dark-mode-original](https://user-images.githubusercontent.com/15837524/84601679-1455b780-ae50-11ea-922e-845bcd65da70.png)|![slicer-dark-mode-updated](https://user-images.githubusercontent.com/15837524/84601681-1b7cc580-ae50-11ea-925c-270890cb59f2.png) Link updates| …
=> ENH: Improve Dark Slicer color palette

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
Running undo/redo (from either the button or shortcut) with no segmentation selected would result in a crash.
Fixed by checking if the segmentation node is specified before attempting undo/redo.
=> BUG: Fix undo/redo crash in the Segment Editor widget

SuperBuild/External_VTK.cmake
See https://discourse.slicer.org/t/build-fails-in-vtkexodus-on-linux/12018
```
$ git shortlog e1be324..b4a1815 --no-merges
SET (1):
[Backport] Exodus gcc 10 support
```
Co-authored-by: SET <chir.set@free.fr>
=> COMP: Update VTK to fix build with gcc 10.1 on Arch Linux

CMake/SlicerDashboardScript.TEMPLATE.cmake, CMake/SlicerInitializeOSXVariables.cmake, Docs/user_guide/getting_started.md, Extensions/CMake/SlicerExtensionsDashboardScript.TEMPLATE.cmake
This is for work https://github.com/Slicer/DashboardScripts/pull/27 which updates the factory macOS build to use Qt 5.15.0.
Deployment target >= 10.13 is the one officially supported by Qt 5.15. See [Qt 5.15 supported platforms](https://doc-snapshots.qt.io/qt5-5.15/supported-platforms.html).
This will support the following macOS versions:
- 10.15: Catalina (2019)
- 10.14: Mojave (2018)
- 10.13: High Sierra (2017)
The last forum discussion about updating minimum osx deployment target can be found [here](https://discourse.slicer.org/t/poll-which-version-of-macos-do-you-use-to-run-slicer/6055).
---------------------------
macOS 10.13 High Sierra is compatible with the following hardware ([source](https://support.apple.com/en-us/HT208969)):
- MacBook introduced in late 2009 or later
- MacBook …
=> COMP: Update minimum required CMAKE_OSX_DEPLOYMENT_TARGET to 10.13

Docs/user_guide/getting_started.md
Updates here are motivated by the change in https://github.com/mhalle/slicer4-download/pull/17 to link to https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#system-requirements from the download page.
Please check the OS versions I specified especially for Slicer stable.  I'm not exactly sure what is the lowest known well working version of Slicer stable on a popular linux distro like Ubuntu.
=> Doc computer requirement updates

Base/Python/slicer/ScriptedLoadableModule.py
This commit fixes the following error when using takeScreenshot from a
ScriptedLoadableModuleLogic subclass:
```
File "path\to\slicer\Python\slicer\ScriptedLoadableModule.py", line
344, in takeScreenshot
imageData = vtk.vtkImageData()
NameError: name 'vtk' is not defined
```
=> BUG: Add missing import to ScriptedLoadableModule

SuperBuild/External_curl.cmake
This commit fixes the following error:
error: '/work/Preview/Slicer-0-build/curl-install/lib/libcurl.a', needed by 'bin/libRemoteIO.so', missing and no known rule to make it
It fixes a regression originally introduced in 128fb86dd1 (ENH: Update
curl from 7.34 to 7.70)
See #5000 and #4992
=> COMP: Fix linux build ensuring curl library is install in "lib" directory

CMake/SlicerBlockInstallOpenSSL.cmake, SuperBuild/External_OpenSSL.cmake
Related to #4859 Tested on Ubuntu 18.04 Linux with Qt 5.15.0, and both debug and release builds work now, where previously they segfaulted almost immediately.
=> Update OpenSSL from 1.0.2n  to 1.1.1g

Base/Python/slicer/util.py
There is currently a `pip_install` function in `slicer.util` so there
should also be a `pip_uninstall` counterpart.
This commit adds `pip_uninstall` and a new function
`_executePythonModule` that can be used to run any Python module.
=> ENH: Add pip_uninstall to slicer.util

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
When the shortest distance surface node reference was removed, it caused a crash when trying to access null pointer. Fixed by calling RemoveAllInputs rather than RemoveInputConnection.
=> BUG: Fix vtkMRMLMarkupsCurveNode crash when removing surface reference

Libs/MRML/Core/vtkMRMLTransformNode.cxx, Libs/MRML/Core/vtkMRMLTransformNode.h, Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.cxx, Modules/Loadable/Transforms/qSlicerTransformsModuleWidget.cxx
When inverting a transform by clicking "Invert" button, it is easy to lose track how many times invert was clicked and the user does not know if the transform ends up being the same as the original or inverted.
We change the behavior so that a (-) suffix as appended to or removed from the transform's name each time "Invert" is clicked.
=> ENH: Update transform node name when the transform is inverted

Libs/MRML/Logic/vtkMRMLColorLogic.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialStorageNode.cxx, Modules/Loadable/Models/Logic/vtkSlicerModelsLogic.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.h, Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx, Modules/Loadable/Sequences/Logic/vtkSlicerSequencesLogic.cxx, Modules/Loadable/Transforms/Logic/vtkSlicerTransformLogic.cxx, Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx
When loading filenames, such as segmentation.1.seg.nrrd, the loaded node was named "segmentation" by default (everything after the first "." character was ignored).
Fixes issue reported at https://discourse.slicer.org/t/cannot-rename-markupsfiducial-in-load-data-window/11994/7?u=lassoan
=> BUG: Fix name of node loaded from filename containing multiple dots

Base/QTGUI/qSlicerStyle.cxx
Text on buttons almost touched the border (especially in button boxes), which did not look nice. This commit reverts button margin to the default value.
Before this change (current Slicer Preview Release):
With this proposed change:
=> BUG: Increase button margin for better visual appearance

Modules/Loadable/Markups/MRML/vtkCurveGenerator.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
Removed unnecessary modified events caused by setting the SurfaceCostFunctionType or SurfaceDistanceWeightingFunction to the same value.
Improved speed when calling SetControlPointPositionsWorld by pausing the calculation of measurements until all of the points have been set.
=> ENH: Improve performance for markup nodes

Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationGeometryLogic.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationGeometryDialog.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationGeometryWidget.cxx
When oversampling a segmentation, the oversampling factor would be doubled if the same segmentation node was set as the reference geometry.
While updating the segmentation node, modification events would cause widget to recalculate the output geometry. The specific action that caused the update was setting the segmentation node ReferenceImageGeometry reference.
Fixed by blocking modified events from the segmentation node until the resampling has been applied, and by not changing the ReferenceImageGeometry reference if the same segmentation node is being used as the reference geometry node.
Also fixes memory leak in vtkSlicerSegmentationGeometryLogic.
fixes #5032
=> BUG: Fix invalid oversampling in segmentation geometry dialog

Base/QTCore/qSlicerFileWriter.h, Base/QTCore/qSlicerScriptedFileReader.h, Base/QTCore/qSlicerScriptedFileWriter.h
A qSlicerFileWriter uses the writtenNodes QStringList variable
to indicate which nodes were written when the write method is
invoked.  Prior to this change, a qScriptedFileWriter had no
way to set this variable, so, for example, the Save Data
dialog would always report a failure when saving with a scripted
writer.
This change makes the method virtual in the super class so that
it can be made a wrapped property in the subclass.
This allows usage as in the example below.
class MarkupsFcsvFileWriter:
def __init__(self, parent):
self.parent = parent
def description(self):
return 'Markup points as fcsv'
def fileType(self):
return 'MarkupsFile'
def canWriteObject(self, obj):
return isinstance(obj, slicer.vtkMRMLMarkupsNode)
def extensions(self, obj):
return ['Fiducial csv (*.fcsv)']
def …
=> ENH: add writtenNodes prop to scripted writer

Base/QTCore/qSlicerFileReader.h, Base/QTCore/qSlicerFileWriter.h
Fix build error for overriding non-virtual method.
Fixes issue introduced by https://github.com/Slicer/Slicer/pull/5025
=> COMP: add virtual to file reader declaration

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx
Calling segment editor effects from python without a selected segment ID would cause a crash in qSlicerSegmentEditorAbstractEffect.
Fixed by checking that the segment exists before trying to modify it.
=> BUG: Fix segment editor crash when selected segment is not defined

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx
This adds the view node id to the eventData passed
to a subject hierarchy plugin, allowing them
to use it in the handling actions.
For example, an action may only make sense on threeDViews
and not on sliceViews, or handling the action may require
knowing which camera and renderer to use in handling the action.
=> ENH: Add view id to plugin events

Docs/user_guide/modules/segmenteditor.md, Modules/Loadable/Segmentations/EditorEffects/Python/AbstractScriptedSegmentEditorAutoCompleteEffect.py
Detects if the effective extent of the input segments changes, and re-initializes the auto-complete preview to match the new extent.
fixes #4703
=> ENH: Re-initialize auto-complete editor effects if ROI changes

CMake/SlicerBlockInstallPython.cmake
This change is required to support the installation of python package
like "comtypes" that are not yet completely ported to python3.
See https://pypi.org/project/comtypes/
Fixes #5042
=> BUG: Package python library "lib2to3"

Applications/SlicerApp/Testing/Python/CMakeLists.txt, Applications/SlicerApp/Testing/Python/SlicerScriptedFileReaderWriterTest.py, Base/QTCore/qSlicerCoreIOManager.cxx, Base/QTCore/qSlicerFileReader.h, Base/QTCore/qSlicerScriptedFileReader.cxx, Base/QTCore/qSlicerScriptedFileReader.h
canLoadFile method can be used for inspecting file content before offering a reader for a file.
Also added automated test for scripted file reader and writer.
=> ENH: Allow file readers to override canLoadFile method

SuperBuild/External_OpenSSL.cmake
This fix is based on the assumption that the `configure-zlib` step
should not be executed when `Slicer_USE_SYSTEM_zlib` is `ON`.
This fixes #5056.
=> BUG: Add condition for configure-zlib step

Libs/MRML/Core/vtkMRMLSegmentationNode.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx
Segment editor effects that used ModificationModeSet (Margin, Threshold, AutoComplete, etc.) would adhere to the mask when adding new regions, but would not prevent the deletion of regions within the mask.
Fixed by:
- Not always including the edited segment in the mask, so that we can accurately determine actual mask region
- Adding the regions of the segment labelmap outside of the mask to the modifier labelmap
fixes #4984
=> BUG: Fix segment editor masking for Set-type effects

SuperBuild/External_python-dicom-requirements.cmake, SuperBuild/External_python-extension-manager-requirements.cmake, SuperBuild/External_python-extension-manager-ssl-requirements.cmake, SuperBuild/External_python-numpy.cmake, SuperBuild/External_python-pip.cmake, SuperBuild/External_python-pythonqt-requirements.cmake, SuperBuild/External_python-requests-requirements.cmake, SuperBuild/External_python-scipy.cmake, SuperBuild/External_python-setuptools.cmake
Python packages were last updated March 16th, 2020. Outdated python packages were discovered using the below code snippet and then versions, hashes and dependencies were determined and updated.
As always we'll keep an eye on the dashboard for any potential regressions.  Generally no major changes in any package.
```
PS C:\S5R-nightly\python-install\bin> ./PythonSlicer.exe -m pip list --outdated
Package         Version    Latest    Type
--------------- ---------- --------- -----
certifi         2019.11.28 2020.6.20 wheel
Deprecated      1.2.7      1.2.10    wheel
dicomweb-client 0.21.0     0.41.0    wheel
gitdb           4.0.2      4.0.5     wheel
GitPython       3.1.0      3.1.7     wheel
idna            2.9        2.10      wheel
numpy           1.18.1     1.19.1    wheel
packaging …
```
=> COMP: Update python packages to latest - July 2020

CMakeLists.txt
This feature wasn't presently being used and it led to
multiply defined symbols in CLI builds for some
tests and extensions.
https://discourse.slicer.org/t/the-slicerdmri-extension-is-currently-unavailable/12276/21
https://github.com/pnlbwh/ukftractography/pull/130
Thanks @sjh26 for shared pain and @jcfr for suggesting the fix.
=> COMP: disable parameter serializer by default

Libs/MRML/Core/vtkMRMLDisplayNode.cxx, Libs/MRML/Core/vtkMRMLModelDisplayNode.cxx, Libs/MRML/Core/vtkMRMLModelDisplayNode.h, Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx, Modules/Loadable/Models/Widgets/Resources/UI/qMRMLModelDisplayNodeWidget.ui, Modules/Loadable/Models/Widgets/qMRMLModelDisplayNodeWidget.cxx, Modules/Loadable/Models/Widgets/qMRMLModelDisplayNodeWidget.h
This pull request contains two improvements for model display:
1. Changes default model color to yellow from the old default mid gray. This make default scenes more interesting and model intersections visible over grayscale images.
2. Slightly changes inside (backface) color so that inside/outside surface can be visually distinguished. Change is specified as relative HSV offset (can be changed in Models module GUI).
**Example**
Old:
New:
=> Improved model display

Libs/MRML/Core/vtkMRMLSegmentationNode.cxx, Libs/MRML/Core/vtkMRMLSegmentationNode.h, Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx, Libs/vtkSegmentationCore/vtkSegmentation.cxx, Libs/vtkSegmentationCore/vtkSegmentation.h, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.h, Modules/Loadable/Segmentations/Resources/UI/qSlicerSegmentationsIOOptionsWidget.ui, Modules/Loadable/Segmentations/Resources/UI/qSlicerSegmentationsModule.ui, Modules/Loadable/Segmentations/Widgets/Resources/UI/qMRMLSegmentationFileExportWidget.ui, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationFileExportWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationFileExportWidget.h, Modules/Loadable/Segmentations/qSlicerSegmentationsIOOptionsWidget.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.h, Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx
When importing a segmentation node from file, users can now specify an existing color table node to create the segments with the expected color and name.
The same (or different) node can be used when exporting the segmentation to labelmap to ensure that the label values of the output match the input.
Users can now also export segmentations directly to NRRD/NIFTI from the "Export to files" section of the segmentation module. The same color node can be used to ensure that the correct expected label values are used during export.
re #5044
=> ENH: Utilize color table node for segmentation import/export

SuperBuild/External_python-dicom-requirements.cmake, SuperBuild/External_python-numpy.cmake
This was introduced by 111b131e733b10f2f7fbcb8f5d4284e1281cf96d where Pillow was updated from 7.0.0 to 7.2.0.  The new version now has both a manylinux1 and manylinux2014 option.
This should address @adamrankin 's comment at https://github.com/Slicer/Slicer/commit/111b131e733b10f2f7fbcb8f5d4284e1281cf96d#commitcomment-40980312
=> BUG: Add support for downloading PyPI package linux aarch64

Base/QTGUI/Resources/UI/qSlicerSaveDataDialog.ui, Base/QTGUI/qSlicerSaveDataDialog.cxx, Base/QTGUI/qSlicerSaveDataDialog_p.h, Libs/MRML/Core/CMakeLists.txt, Libs/MRML/Core/vtkMRMLMessageCollection.cxx, Libs/MRML/Core/vtkMRMLMessageCollection.h, Libs/MRML/Core/vtkMRMLStorageNode.cxx, Libs/MRML/Core/vtkMRMLStorageNode.h
This is the code associated with https://github.com/Slicer/Slicer/issues/4968 for collecting the user-friendly messages at the time of saving.  Still to do is presenting the collected messages in the Base/QTGUI/qSlicerSaveDataDialog.cxx.
=> ENH: Display warnings and errors in the Save Data dialog

Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
This commit fixes the following warning:
```
/path/to/Slicer/Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx:1126:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int i = 0; i < exportedSegmentIDs.size(); ++i)
^
```
=> COMP: Fix -Wsign-compare warning in qMRMLSegmentationFileExportWidget

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
This commit fixes the following warnings:
```
/path/to/Slicer/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx:488:10: warning: unused variable ‘foundTransform’ [-Wunused-variable]
bool foundTransform = false;
^
/path/to/Slicer/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx:489:27: warning: unused variable ‘commonTransformNode’ [-Wunused-variable]
vtkMRMLTransformNode* commonTransformNode = nullptr;
^
```
=> COMP: Fix -Wunused-variable warnings in qMRMLSubjectHierarchyTreeView

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationFileExportWidget.cxx
This commit fixes the following warning:
````
/path/to/Slicer/Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationFileExportWidget.cxx:319:72: warning: unused parameter ‘useColorNode’ [-Wunused-parameter]
void qMRMLSegmentationFileExportWidget::setUseLabelsFromColorNode(bool useColorNode)
^
```
=> COMP: Fix -Wunused-parameter warning in qMRMLSegmentationFileExportWidget

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.h
If a plugin was registered later than the tree view created, then the context menus from the new plugin were not available. With this change, the context menu for each tree view is re-generated if a new plugin was registered since the last context menu generation.
Re https://github.com/SlicerMorph/SlicerMorph/issues/71
=> BUG: Make sure subject hierarchy context menu is always up-to-date

Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx
When a TransformModified event was invoked on any node in the scene, all model display pipelines were updated. This caused a noticeable drop in performance when there were a large number of nodes in the scene.
Fixed by not setting UpdateFromMRMLRequested to true when a transform was updated, and instead calling  OnMRMLDisplayableModelNodeModifiedEvent.
The performance of OnMRMLDisplayableModelNodeModifiedEvent was also improved, as it was not necessary to call UpdateClipSlicesFromMRML, and SetUpdateFromMRMLRequested functions when only a display node was modified.
=> ENH: Improve display performance if TransformModifiedEvent is invoked

CMake/SlicerCPackBundleFixup.cmake.in
Other parts of the Qt installation have existing rpath
info in the mach-o file so they require the replacement
form of the install_name_tool command.
But QWebEngineProcess does not have an rpath, so
as described in the man page, this creates an
error condition so the other replacements are not
made.
This change uses the -add_rpath command command instead.
Fixes #5022
Fixes #4999
=> COMP: add rpath to QWebEngineProcess

SuperBuild/External_SlicerExecutionModel.cmake
This commit fixes a regression introduced in 7c60390212 (COMP: disable
parameter serializer by default (#5065))
Fixes #5080
```
$ git shortlog 1788b378e..f19d6e88a --no-merges
Hans Johnson (2):
ENH: Update docker base image to include newer cmake version.
COMP: Protect duplicate definition warnings
COMP: Do not force JsonCpp and ParameterSerializer DIR variables to empty string
Julien Finet (1):
COMP: Do not link ModuleDescriptionParser with entire ITK
```
=> COMP: Update SlicerExecutionModel to fix extension configuration

Extensions/CMake/SlicerBlockBuildPackageAndUploadExtension.cmake
This change is intended to make the Slicer extensions packages
quickly available to the user and independently of the time needed
to run all tests.
=> ENH: Update extension CDash driver script to package then test

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.h, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsDisplayNodeWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.h
Improves the appearance of plane widgets by adding a border around the plane and allowing control of plane fill/border opacity.
fixes #4930
=> ENH: Improve markup plane widget appearance

Docs/developer_guide/build_instructions/index.rst, Docs/developer_guide/build_instructions/linux.md, Docs/developer_guide/build_instructions/macos.md, Docs/developer_guide/build_instructions/overview.md, Docs/developer_guide/build_instructions/windows.md, Docs/index.rst
**This is a work-in-progress branch**
As suggested in the last meeting, I started a documentation section for building Slicer on Linux using different distributions. I welcome comments on structure and contents and appreciate feedback on the following questions:
- I added the section to the `index.rst` file. It seems, however, that the section link does not appear in the left column when visiting some other content (e.g., content in the user guide)?
- The content is inspired on the current Slicer wiki content. There are a few links to other articles (e.g., link to https://www.slicer.org/wiki/Documentation/Nightly/Developers/DevelopmentWithGit). What to to with this type of content: keep external link? open an new section in the readthedocs documentation?
- In the same way, in the Wiki, …
=> Documentation build instructions

Modules/Loadable/Segmentations/EditorEffects/Python/AbstractScriptedSegmentEditorAutoCompleteEffect.py
Check to make sure that the segment labelmap exists before getting the MTime.
If the labelmap does not exist, remove it from the list of MTimes.
fixes #5088
=> BUG: Prevent Traceback from undo/redo in AutoComplete effects

Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx
2D markup plane representations now check outline and fill visibility when determining the color table opacity.
fixes #4930
=> ENH: Add 2D markup plane outline/fill support

SuperBuild/External_VTK.cmake
```
$ git shortlog b4a181566f..9c813fe590 --no-merges
Csaba Pinter (1):
[backport] Add shading to multi-volume rendering
Michael Migliore (1):
[backport] Fix shader error on Mesa and use enum
```
Co-authored-by: Csaba Pinter <pinter.csaba@gmail.com>
=> ENH: Update VTK backporting support for shading with multi-volume rendering

Libs/MRML/Widgets/qMRMLNodeComboBox.cxx
On Windows 10, with Qt-5.15.0, setting the scene in qMRMLNodeComboBox caused warnings such as this:
```
[WARNING][Qt] 11.08.2020 15:44:08 [] (unknown:0) - QAccessibleTable::child: Invalid index at: 0 0
[WARNING][Qt] 11.08.2020 15:44:08 [] (unknown:0) - QAccessibleTable::child: Invalid index at: 0 0
```
It was reproducible by this script:
```
c=slicer.qMRMLNodeComboBox(); c.setMRMLScene(slicer.mrmlScene); c.show()
```
The problem was that during scene setting, when the scene item was placed in the scene model, `setCurrentNode(nullptr)` got called, which triggered a warning in `QAccessibleTable::child(int logicalIndex)` because the item index was invalid.
Fixed the issue by not calling `setCurrentNode(nullptr)` if the current node was already `nullptr`.
fixes #5094
=> BUG: Fix QAccessibleTable::child: Invalid index warning

Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationGeometryLogic.cxx
This commit fixes the following warning:
```
/path/to/Slicer/Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationGeometryLogic.cxx:130:28: warning: unused variable ‘sourceSegmentationNode’ [-Wunused-variable]
vtkMRMLSegmentationNode* sourceSegmentationNode = vtkMRMLSegmentationNode::SafeDownCast(this->SourceGeometryNode);
^
```
=> COMP: Fix -Wunused-variable warning in vtkSlicerSegmentationGeometryLogic

Libs/vtkSegmentationCore/vtkOrientedImageDataResample.cxx
The binary labelmap extent was not transformed to the mask coordinate system when calculating the resampled binary labelmap extent. Fixed by transforming the binary labelmap extent.
=> BUG: Fix extent calculation in IsLabelInMask

Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorThresholdEffect.py
The number of bins used for the selected region histogram was calculated with the following formula:
```max(scalarRangeMax - scalarRangeMin + 1, 1000)```
This worked well for integer type images, but resulted in a low resolution for floating point types.
The number of bins for floating point types is now automatically set to the maximum allowed (1000).
=> ENH: Improve segment threshold histogram for floating point volumes

Base/QTGUI/qSlicerModuleFinderDialog.cxx, Base/QTGUI/qSlicerModuleFinderDialog.h
This commit fixes the following warnings:
```
/path/to/Slicer/Base/QTGUI/qSlicerModuleFinderDialog.cxx: In member function ‘void qSlicerModuleFinderDialogPrivate::init()’:
/path/to/Slicer/Base/QTGUI/qSlicerModuleFinderDialog.cxx:74:40: warning: unused variable ‘factoryManager’ [-Wunused-variable]
qSlicerAbstractModuleFactoryManager* factoryManager = coreApp->moduleManager()->factoryManager();
^
/path/to/Slicer/Base/QTGUI/qSlicerModuleFinderDialog.cxx: At global scope:
/path/to/Slicer/Base/QTGUI/qSlicerModuleFinderDialog.cxx:371:73: warning: unused parameter ‘text’ [-Wunused-parameter]
void qSlicerModuleFinderDialog::setModuleTitleFilterText(const QString& text)
^
```
=> COMP: Fix -Wunused-* warnings in qSlicerModuleFinderDialog

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
Vertical mousewheel+shift on MacOS is mapped to the horizontal, rather than vertical axis.
As a result, using shift+mousewheel to resize the paintbrush was not functional on MacOS.
Fixed by allowing both MouseWheelForward/BackwardEvent and MouseWheelLeft/RightEvent for paint brush resize.
Fixes #4661
=> BUG: Fix paint brush resize using shift+mousewheel on MacOS

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
Observers for horizontal mousewheel events were added to Slice views in 5c04a33, but were not added to 3D views.
Fixed by adding MouseWheelLeftEvent and MouseWheelRightEvent observers to 3D views.
=> BUG: Add horizontal mousewheel event observers to 3D views

Base/QTCLI/vtkSlicerCLIModuleLogic.cxx, Base/QTGUI/qSlicerApplication.cxx, Libs/MRML/Core/vtkMRMLColorTableNode.cxx, Libs/MRML/Core/vtkMRMLScene.cxx, Libs/MRML/Core/vtkMRMLScene.h, Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.cxx, Libs/MRML/Logic/vtkMRMLColorLogic.cxx, Libs/MRML/Widgets/qMRMLSceneFactoryWidget.cxx
When started multiple Slicer instances exactly at the same time, only one log file was created and MRB file loading was failed due to insufficient timestamp (1 second precision) and random number generation with uninitialized seed.
Fixed by adding a 3-digit random counter to log file name and switching to C++ random number generators.
=> BUG: Fix running of multiple Slicer instances

Libs/MRML/DisplayableManager/vtkMRMLModelSliceDisplayableManager.cxx
Loading a scene that used an invalid LUT for the model scalar overlay, would cause a crash.
Fixed by checking that the LUT exists before attempting to access it.
=> BUG: Fix model slice display crash when lookup table node is null

Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx
When loading a segmentation from closed surface, the vtkMRMLSegmentationStorageNode will cause a crash if one of the blocks in the seg.vtm is unable to be loaded. Fixed by checking that the block could be read before trying to access it, and logging an error message if it could not.
I haven't figured out what causes a segmentation to be written missing some blocks, but this fixes the error when it does occur.
=> BUG: Fix crash when loading closed surface segmentations

Base/QTGUI/Resources/UI/qSlicerSaveDataDialog.ui, Base/QTGUI/qSlicerSaveDataDialog.cxx, Base/QTGUI/qSlicerSaveDataDialog_p.h, Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx
Fix the following problems in qSlicerSaveDataDialog:
- when a long directory path was used then the dialog did not fit the screen on some systems and "Save" button was not visible (fixed by using ctkPathLineEdit instead of ctkDirectoryButton)
- fixed lots of widgets appearing and disappearing before save dialog is shown (recent regression introduced by status icon display)
- remove separate "Notes" column for saving status (added icon to filename column instead, where it is much more visible, take less space, and simpler to implement)
- fix deselection of successfully saved items
Also add warning if saving in Analyze format or rotated volume in VTK format - fixes #2443
=> BUG: Fix layout errors in qSlicerSaveDataDialog

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h
Adds the helper function vtkMRMLMarkupsPlaneNode::GetClosestPointOnPlaneWorld().
The function gets the closest position on the plane in world coordinates, and returns the signed distance from the point to the plane.
=> ENH: Add GetClosestPointOnPlaneWorld to plane markup nodes

Modules/Scripted/EditorLib/EditBox.py
The exclusive attribute for QActionGroup was replaced starting in Qt 5.14 with the exclusionPolicy attribute. Using the setExclusive method will set the exclusive or exclusionPolicy attribute depending on the Qt 5 version being used.
Reference: https://github.com/Slicer/Slicer/pull/5127
=> BUG: Fix invalid use of QActionGroup exclusive attribute

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
If filtering by name affected items that were highlighted as reference of the selected item, then a crash may have occurred. It is fixed by checking if the item to be highlighted is actually allowed by the filter (and a valid proxy item exists).
=> BUG: Fix crash when filtering by name in subject hierarchy

Libs/vtkSegmentationCore/vtkClosedSurfaceToBinaryLabelmapConversionRule.cxx, Libs/vtkSegmentationCore/vtkSegmentation.cxx
If the reference geometry conversion parameter had not been set, performing a closed surface to binary labelmap conversion would create the reference geometry if it didn't already exist, setting it to the geometry of the first imported model. This caused all subsequent models to be cropped to the same extent as the first one when exported or saved as labelmap.
Fixed by not setting the reference image geometry from vtkClosedSurfaceToBinaryLabelmapConversionRule, and by calculating extent from the union of segments in vtkSegmentation::DetermineCommonLabelmapGeometry if the reference geometry was not specified, and the extent mode was EXTENT_REFERENCE_GEOMETRY.
fixes #5093
=> BUG: Prevent cropping of segments imported from models

Base/QTGUI/qSlicerStyle.cxx
Using Qt::red was not bright enough for some users, so
increase the luminance a bit.
Not that to experiment with different color options one
can use commands like this:
slicer.app.pythonConsole().errorTextColor = qt.QColor("#ff4444")
=> STYLE: make python errors readable in dark style

Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.cxx
In many functions in the subject hierarchy node if the item was not found for any reason, the same message was logged "Failed to find subject hierarchy item by ID N", and it was impossible to know if it was caused by an internal problem in subject hierarchy, or because of the application that called the function with invalid item ID. This change makes sure that if an invalid item ID is given to these functions, then it's logged explicitly, so the developer can differentiate between application and internal SH bugs.
Also fixed a few copy-paste errors returning wrong values after errors.
=> ENH: Improve error logging in subject hierarchy node

Base/Python/slicer/slicerqt.py
Python INFO, WARNING, and ERROR messages generated by the python logging module created duplicate entries as seen in the Slicer log file and in the Error Log Dialog.  This commit removes python logging messages from showing in the python console as they are already included in the Slicer log and should be viewed there.
When using logging across many scripted modules, this current duplication makes reading the Slicer log and using the Error Log Dialog **much** more difficult to understand.
```
[DEBUG][Qt] 27.08.2020 22:56:22 [] (unknown:0) - Switch to module:  "ScreenCapture"
[INFO][Python] 27.08.2020 22:56:25 [Python] (C:/Users/james/AppData/Local/NA-MIC/Slicer 4.11.0-2020-08-26/bin/../lib/Slicer-4.11/qt-scripted-modules/ScreenCapture.py:805) - Write …
```
=> BUG: Fix duplicate python logging messages in the log

Docs/user_guide/modules/data.md
According to Brad Gilbert (https://meta.stackexchange.com/questions/21233/problems-creating-a-bullet-and-number-list-with-markdown#comment43983_21234), using multiples of 4 spaces makes markdown work better. It improves the way Github renders the markdown. Hopefully the change will work on slicer.readthedocs.io as well
=> DOC: Fix bullet point hierarchy in markdown

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.h, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsDisplayNodeWidget.ui, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsFiducialProjectionPropertyWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.h
By enabling vtkMRMLMarkupsDisplayNode::AlwaysOnTop, the markup widget will be rendered on top of all other objects in the scene.
This option can be toggled on and off from the markups display node ui.
=> ENH: Add option to render markups on top of everything else

Libs/MRML/DisplayableManager/vtkMRMLAbstractWidgetRepresentation.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.h, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.cxx
- Improve organization of actors/mappers in VTK markup widgets
- Mappers, actors, etc. are now grouped together
- Remove UpdateOccludedRelativeCoincidentTopologyOffsets and update UpdateRelativeCoincidentTopologyOffsets to accept two arguments.
- Add explanation for default OccludedRelativeOffset
- Reduce opacity maximum to 0.99 (was 0.99999999) to prevent floating point issues
- Indentation fixes
Fixes issues mentioned in https://github.com/Slicer/Slicer/pull/5128.
=> ENH: Add miscellaneous improvements to markups VTK widgets

Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx
PropertiesLabelVisibility was used to control the visibility of the line representation text actor in 2D, however it had no effect in 3D.
Fixed by checking PropertiesLabelVisibility before setting text actor visibility.
=> BUG: Allow PropertiesLabelVisibility to control line text visibility in 3D

CMake/FindVcvars.cmake
Based on the changes made in https://github.com/scikit-build/cmake-FindVcvars/commit/67b96c3a8dd0db2f4d04c989db12f273a02580af
=> COMP: Update FindVcvars with MSVC 1927 support

SuperBuild.cmake
```
$ git shortlog ab95838..b9a6c16 --no-merges
Hans Johnson (3):
ENH: Use default initialization for ivars.
COMP: Explicitly deleted functions public interface
ENH: Project command should come after minimumn_required
```
=> STYLE: Update vtkAddon to include misc. tweaks

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx
When running the smoothing effect, the current segment could be deleted if the mask was an incorrect datatype.
The mask image was copied from the modifier labelmap, and could be a data type other than unsigned char, which would cause the vtkImageMask filter to fail.
Fixed by setting the mask datatype to VTK_UNSIGNED_CHAR.
See topic here: https://discourse.slicer.org/t/13295
=> BUG: Fix deletion of segments when running smoothing effect

SuperBuild.cmake
This changes is done to prepare the support for VTK <= 8.90
```
$ git shortlog b907c39..8be7d7a --no-merges
Csaba Pinter (1):
STYLE: Remove VTK <= 8 support using override statements for C++11
```
=> COMP: Update MultiVolumeExplorer to remove support for VTK <= 8

Base/QTGUI/qSlicerSaveDataDialog.cxx, Modules/Loadable/Markups/CMakeLists.txt, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialStorageNode.cxx, Modules/Loadable/Markups/qSlicerMarkupsModule.cxx, Modules/Loadable/Markups/qSlicerMarkupsWriter.cxx, Modules/Loadable/Markups/qSlicerMarkupsWriter.h
Added a dedicated markups writer plugin that offers loading both json and fcsv formats for saving any markup node type. This allows easy switching between formats in save dialog:
Default format is now json for all types (as user can easily change in save dialog). If fcsv format is used then a warning icon is displayed about the lossy storage (no popup is displayed, the warning can be dismissed by closing the save dialog by clicking a button or hitting escape or enter key):
=> ENH: Allow switch between json and fcsv format for markups

Modules/Loadable/Markups/MRML/vtkCurveGenerator.h
Makes the static functions vtkCurveGenerator::SortByIndex() and vtkCurveGenerator::SortByMinimumSpanningTreePosition() public.
=> ENH: Expose vtkCurveGenerator::SortByIndex/MinimumSpanningTreePosition

SuperBuild/External_Swig.cmake
Fixes the issue described here: https://github.com/SimpleITK/SimpleITK/issues/1190
=> COMP: avoid JDK warning from Swig on mac

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx
Reduces the total interaction widget size, as well as the individual size of the handles by 50%.
Increases the resolution of the sphere and tube sources.
Appearance before:
Appearance after:
=> ENH: Improve markup interaction handle appearance

Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx
When segment color was changed by calling segment->SetColor then subject hierarchy widget was not updated.
Fixed by calling vtkMRMLSubjectHierarchyNode::SubjectHierarchyItemModifiedEvent when segment is modified.
=> BUG: Fix segment color not updating in subject hierarchy

Extensions/CMake/MIDASAPIUploadExtension.cmake
Despite of having an error like the following reported on CDash, the
package is still available in the extensions manager. This commit updates
the timeout to provide more time to the server for acknowledging the
upload and avoid to report a failure.
Co-authored-by: Sam Horvath <sam.horvath@kitware.com>
=> COMP: Attempt to fix extension package upload updating timeout from 120 to 240

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
This commit ensures the transformation reference point can be retrieved
for both 2D and 3D representations.
=> BUG: Fix crash when scaling markups widget in slice view

CMake/SlicerBlockInstallPython.cmake
Do not exclude wsgi package from Python, as it is required by Jupyter notebook server.
Without this, it is not possible to run Jupyter server in Slicer's Python environment.
Fixes https://github.com/Slicer/SlicerJupyter/issues/39
@pieper
=> BUG: Add wsgi package to Python

Base/QTApp/qSlicerMainWindow.cxx, Docs/user_guide/user_interface.md
Ctrl-O is the standard shortcut for loading data in most other applications, and Slicer already support this shortcut.
Ctrl-A was kept for backward compatibility, but it cause frustration to many users, as it prevented using this shortcut for selecting all items in lists and tables. For example, there was no keyboard shortcut for selecting all markup control points or segments in a list or all cells in a table.
This has been discussed at the last Slicer weekly meeting and everybody agreed on this change.
=> ENH: Remove Ctrl-A shortcut for loading data

Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt, Modules/Loadable/VolumeRendering/Testing/Cxx/vtkMRMLVolumeRenderingDisplayableManagerTest1.cxx
The test was failing because of an error message
from the logic class that the share directory
was not set:
```
ERROR: In D:\D\P\Slicer-0\Modules\Loadable\VolumeRendering\Logic\vtkSlicerVolumeRenderingLogic.cxx, line 1243
vtkSlicerVolumeRenderingLogic (00000222CD51C6D0): Failed to load presets: Share directory *NOT* set !
```
See: http://slicer.cdash.org/testDetails.php?test=10139125&build=2017840
In normal use in the application, this share directory is set
at the Qt level, but that path is not available to this vtk-only
test.
But the path is known to CMake, so here we pass in the path
as a command line argument to the test.
=> BUG: fix failing volume rendering test

Libs/MRML/Core/vtkMRMLSegmentationNode.cxx, Libs/MRML/Core/vtkMRMLSegmentationNode.h
The vtkMRMLSegmentation node functions GetBinaryLabelmapRepresentation or GetClosedSurfaceRepresentation now return True/False depending on if the operation was successful/unsuccessful.
=> ENH: Update segmentation node Get..Representation to return status

Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
Allows markups (and other widgets) to process events when the crosshair position is being changed with shift + mouse move.
This is done by processing ActionSetCrosshairPosition in CanProcessInteractionEvent, rather than ProcessInteractionEvent.
=> ENH: Enable markup preview when holding shift key

CMake/SlicerDashboardDriverScript.cmake
This change is the first one of series intended to make the Slicer
application package quickly available to the user and independently
of the time needed to run all tests.
=> ENH: Update application CDash driver script to package then test

CMake/SlicerBlockInstallQt.cmake
This commit ensures QmlModels introduced in 5.14 is packaged.
See https://github.com/qt/qtdeclarative/commit/325e6305b418ffe1dfb9a36c2516c6a8a3de5733
Notes:
* On linux, installing `libxcb-xinerama0` is required
* Requirement for freetype version changed. See details below
On an older linux system (Ubuntu  15.10), attempt to start Slicer built using latest [build environment](https://github.com/Slicer/SlicerBuildEnvironment/) including Qt 5.15.1 returns the following error:
```
$ export QT_DEBUG_PLUGINS=1
$ ./Slicer
[...] 
Got keys from plugin meta data ("xcb_glx")
QFactoryLoader::QFactoryLoader() checking directory path "/path/to/bin/xcbglintegrations" ...
loaded library "/path/to/lib/QtPlugins/xcbglintegrations/libqxcb-glx-integration.so"
/path/to/bin/SlicerApp-real: symbol lookup error: …
```
=> BUG: Fix application startup when built against Qt 5.15.1

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
- Drag&drop is enabled by default: users have been confused about why drag&drop selects items in some views like DICOM and DICOM export instead of reparenting like in the Data module
- Indentation is set to 8 pixels: there is a wide empty area on the left otherwise
- Selection mode is extended like in the Data module
- Edit triggers like double click and key presses work by default
=> ENH: Adjust subject hierarchy tree defaults to avoid confusion

CMake/SlicerBlockInstallQt.cmake
This commit fixes a regression introduced in 26f1f47a8a (BUG: Fix
application startup when built against Qt 5.15.1 (#5207)) that was intended
to fix Linux packaging.
It ensures the installed Slicer application can successfully start.
On windows the "windeployqt" tool implicitly takes care of copying the
"Qt5QmlModels.dll" by only specifying the "-qml" option.
Fixes #5208
=> BUG: Fix installed Slicer app startup on windows when built against Qt 5.15.1

SuperBuild/External_SimpleITK.cmake
```
$ git shortlog --no-merges v2.0rc3..v2.0.0
Bradley Lowekamp (19):
Add __version__ to Python module for PEP 376 compatibility.
Remove outdated, and disabled download_url field from setup.py
Add project_urls to setup.py for link on  PyPi
Use Readme for long description in setup.py and PyPi
Update ITK version to official 5.1.1 tag
Fix PasteImageFilter doxygen class name
Update IO docs with Python keyword argument usage.
Various improvements to the Sphinx build document.
Update Sphinx for SimpleITK 2.0
Minor tweaks to the Sphinx Getting Started documentation.
Fix unsigned to signed integer comparison warning in generated tests
Fix Sphinx warnings.
Add C++ example for executing filters in place
Add example for processing high dimension images.
Fix Sphinx building docs label syntax
Only add …
```
=> COMP: Update SimpleITK from v2.0rc3 to v2.0.0

SuperBuild/External_SimpleITK.cmake
This commit fixes a regression introduced in 127dfbad28 (COMP: Update
SimpleITK from v2.0rc3 to v2.0.0 (#5212)) and ensures that ITK libraries
are in the PATH when running the command:
```bash
cd /path/to/SimpleITK-build/SimpleITK-build/Wrapping/Python
python setup.py install
```
It addresses the following error:
```python
File "<stdin>", line 1, in <module>
File "/work/Preview/Slicer-0-build/SimpleITK-build/SimpleITK-build/Wrapping/Python/SimpleITK/__init__.py", line 18, in <module>
from SimpleITK.SimpleITK import *
File "/work/Preview/Slicer-0-build/SimpleITK-build/SimpleITK-build/Wrapping/Python/SimpleITK/SimpleITK.py", line 13, in <module>
from . import _SimpleITK
ImportError: libITKIOBruker-5.1.so.1: cannot open shared object file: No such file or …
```
=> COMP: Fix installation of SimpleITK

SuperBuild/External_SimpleITK.cmake
This commit fixes a regression introduced in 127dfbad28 (COMP: Update
SimpleITK from v2.0rc3 to v2.0.0 (#5212)) and ensures that SimpleITK
libraries are also in the PATH when running the command:
cd /path/to/SimpleITK-build/SimpleITK-build/Wrapping/Python
python setup.py install
Adding the SimpleITK libraries is required on windows where
Slicer_USE_SimpleITK_SHARED is enabled.
=> COMP: Fix installation of SimpleITK on windows

CMake/SlicerBlockInstallExternalPythonModules.cmake, CMake/SlicerExtensionCPackBundleFixup.cmake.in, SuperBuild/External_VTK.cmake
Update VTK to ensure "all.py" is packaged
Update install tree launcher settings associated with VTK9
Update install of VTK python modules on macOS
List of VTK9 changes:
$ git shortlog 2f4e011bfc..1ecbd5001e --no-merges
COMP: Associate "all.py" install rule with "python" component
=> COMP: Fix packaging of VTK9 python modules

CMake/SlicerCPackBundleFixup.cmake.in
This commit adds rules for Slicer package.
Note that commit 08789e8 (COMP: Fix packaging of VTK9 python modules)
added similar rules for extension fixup.
=> COMP: Fix macOS package adding fixup rules for VTK9 python modules

CMake/SlicerCPackBundleFixup.cmake.in
This commit is a follow up of d6300056c4 (COMP: Fix macOS package adding
fixup rules for VTK9 python modules)
=> COMP: Fix macOS package setting "path" in VTK9 python modules fixup rules

Libs/MRML/Core/vtkMRMLSegmentationNode.cxx, Libs/MRML/Core/vtkMRMLSegmentationNode.h, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.h, Modules/Loadable/Segmentations/Widgets/Resources/UI/qMRMLSegmentationFileExportWidget.ui, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationFileExportWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationFileExportWidget.h
This commit adds a vtkMRMLVolumeNode selector to the file export dialog, which allows a reference geometry to be specified when exporting a segmentation volume to file.
See discussion here: https://discourse.slicer.org/t/segmentation-alignment/13449/15
=> ENH: Add option to set reference volume when exporting segmentation to file

Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h
This commit removes a 'P' shortcut implemented in the wrong place. It will be reimplemented but the current definition is interfering with customized shortcuts.
From @lassoan:
> I’ve found a ‘P’ key shortcut in qSlicerMarkupsModuleWidget. This is implemented at completely wrong place, so it should be removed.
> Since “P” shortcut would be generally useful, I think it should be handled in vtkSlicerMarkupsWidget, the same way how “Delete”, “Backpace” and “S” keys are handled already. We also plan to make widget GUI to widget event mapping (‘P’ key press -> pick point) customizable by users and modules.”
=> BUG: Remove P shortcut from incorrect location

Libs/MRML/DisplayableManager/vtkMRMLModelSliceDisplayableManager.cxx
The pointer to the lookup table was not set when using a lookup table color node.
Fixed by setting the lut pointer to the correct object.
fixes #5241
=> BUG: Fix crash when selecting a lookup table for slice distance color

SuperBuild/External_VTK.cmake
```
$ git shortlog 1ecbd5001..a889f47304 --no-merges
Ben Boeckel (3):
hdf5: update for H5Tinit.c fix
xdmf2: use the proper preprocessor definition
cmake: fix the library suffix for WrappingPythonCore
Boonthanome Nouanesengsy (1):
Deal with wraparound for PIO Reader, made PIO Reader parallel
Caitlin Ross (1):
edit tag for fides update
Cory Quammen (1):
macos: implement setting of DisplayId
David Thompson (1):
Glyph3D should copy global IDs to its output.
Davide Punzo (1):
ENH: add double click events
Fides Upstream (1):
fides 2020-10-04 (0c29bd4a)
Freetype Upstream (1):
freetype 2020-09-30 (b610a2a4)
HDF Upstream (1):
hdf5 2020-10-05 (7867cd4a)
COMP: Remove vtk-m submodule
COMP: Remove FindTBB and expect VTK to be configured with TBB_DIR …
```
=> ENH: Update VTK

Docs/user_guide/getting_started.md
The recent slicer stable is referring to Slicer-4.11.20200930
=> DOC: Update operating system versions for recent Slicer stable

Docs/user_guide/getting_started.md
This is a follow-up to #5252 for the v4.11 branch.
Documentation is versioned so there is not a need for both Stable and Preview information.
=> DOC: Update operating system versions to reflect state of Slicer-4.11

Libs/MRML/Widgets/qMRMLScalarsDisplayWidget.cxx
qMRMLScalarsDisplayWidget::setMRMLDisplayNode() will cause a crash when called with nullptr.
Fixed by checking if the display node exists before accessing it.
=> BUG: Fix crash in qMRMLScalarsDisplayWidget

Base/QTGUI/qSlicerWebWidget.cxx, Base/QTGUI/qSlicerWebWidget.h
Since WebEngine objects are not exposed in PythonQt, this commit updates
the existing qSlicerWebWidget to support using existing PDF export
functionality built-in WebEngine widget.
For example:
```
url = "file:///home/jcfr/Downloads/index.html"
outputPath = "/tmp/test.pdf"
webWidget = slicer.qSlicerWebWidget()
def loadFinished(ok):
if not ok:
print("failed to load URL %s" % url)
return
webWidget.printToPdf(outputPath);
def pdfPrintingFinished(filePath, success):
print("export completed [%s]: %s" % (success, filePath))
webWidget.connect("loadFinished(bool)", loadFinished)
webWidget.connect("pdfPrintingFinished(QString,bool)", pdfPrintingFinished)
webWidget.setUrl(url)
```
=> ENH: Update qSlicerWebWidget to allow export to PDF

Base/QTApp/Resources/UI/qSlicerErrorReportDialog.ui, Base/QTApp/qSlicerErrorReportDialog.cxx
"Report a bug" dialog had a combobox for selecting logs from previous sessions but users had trouble finding it.
This commit replaces the single-line combobox with a list widget, which is easier to discover and it also easier to browse through the files.
=> ENH: Make logs of previous sessions more easily accessible

CMakeLists.txt
This commit fixes the bundling of extension like SlicerVirtualReality
having external projects setting BUILD_SHARED_LIBS based on the value
of Slicer_BUILD_SHARED.
=> COMP: Fix bundling of extension ensuring Slicer_BUILD_SHARED is set

SuperBuild/External_python-dicom-requirements.cmake, SuperBuild/External_python-extension-manager-requirements.cmake, SuperBuild/External_python-extension-manager-ssl-requirements.cmake, SuperBuild/External_python-numpy.cmake, SuperBuild/External_python-pip.cmake, SuperBuild/External_python-requests-requirements.cmake, SuperBuild/External_python-scipy.cmake, SuperBuild/External_python-setuptools.cmake, SuperBuild/External_python-wheel.cmake
Python packages were last updated July 27th, 2020. Outdated python packages were discovered using the below code snippet and then versions, hashes and dependencies were determined and updated.
@adamrankin The last time python packages were updated Scipy did not have an aarch64 wheel as mentioned in https://github.com/Slicer/Slicer/pull/5064#issuecomment-666611759.  However, the latest Scipy which will now be used does have a wheel for aarch64.
In this PR I'm only updating python packages downloaded from pypi. This means not updating SimpleITK and VTK python packages.
```
PS C:\S5R-nightly\python-install\bin> ./PythonSlicer.exe -m pip list --outdated
Package         Version Latest  Type
--------------- ------- ------- -----
dicomweb-client 0.41.0  0.50.2  wheel
GitPython       3.1.7 …
```
=> COMP: Update python packages to latest

SuperBuild/External_CTK.cmake
```
$ git shortlog 03bf8478..44cb1276 --no-merges
Jean-Christophe Fillion-Robin (3):
COMP: Fix build of CTKVisualizationVTK tests against VTK9
[...]
Tobias Krähling (3):
STYLE: Update CTKVisualizationVTK test requirements to be more specific
BUG: Fix CTKVisualizationVTKWidgets tests updating QSurfaceFormat initialization
ENH: Re-factor code centralizing setting of default surface format
```
=> BUG: Update CTK

Libs/MRML/Core/CMakeLists.txt, Libs/MRML/Core/vtkMRMLMeasurement.cxx, Libs/MRML/Core/vtkMRMLMeasurement.h, Libs/MRML/Core/vtkMRMLMeasurementConstant.cxx, Libs/MRML/Core/vtkMRMLMeasurementConstant.h, Modules/Loadable/Markups/MRML/vtkCurveGenerator.cxx, Modules/Loadable/Markups/MRML/vtkCurveGenerator.h, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.cxx, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest1.cxx, Modules/Loadable/Markups/Testing/Python/MarkupsCurveMeasurementsTest.py, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
- Since for closed curves the two ends meet, instead of setting the end curvature values to zero, we use the adjacent values
- Force measurements to implement Compute function (and thus using the new method for measurement calculation) by making it pure virtual
- Add test for closed curve curvature calculation
=> ENH: Add support for closed curves to curvature calculation

Docs/developer_guide/index.rst, Docs/developer_guide/modules/index.rst, Docs/index.rst
Pull request created to generate preview documentation to facilitate discussion - see https://discourse.slicer.org/t/user-guide-and-developer-guide-cannot-be-clicked-and-linked-as-distinct-url/14042/3
=> DOC: Experimental moving of developer manual into a documentation subsection

Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx
Despite not being intended for visualization in 3D, the Project and ProjectBack control point pipelines were shown in vtkSlicerCurveRepresentation3D::UpdateFromMRML().
Fixed by hiding the "Project" actors in vtkSlicerCurveRepresentation3D using the same method as vtkSlicerMarkupsWidgetRepresentation3D::UpdateAllPointsAndLabelsFromMRML().
Fixes #5276
=> BUG: Remove letter "F" appearing at origin when curve labels are shown

Libs/MRML/Core/vtkObserverManager.cxx
The method gives the option of providing a list of priorities
with one priority per event in two lists.
The check logic was incorrect however, because in the case
where no priorities had been provided (null list pointer) the
'if' condition was triggered and the warning macro would
indirect through the null priorities pointer.
Now the two checks have been separated and each has a custom
warning message so that pointers are only used when they are
known to be non-null.
=> CRASH: fix observer manager events and priorities

Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.cxx, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.cxx, Modules/Loadable/Markups/Testing/Python/MarkupsCurveMeasurementsTest.py
* Curvature mean and max measurements are added to curve markup. These two are disabled by default and get enabled when the user enables curvature calculation for the markup itself.
* They are constant measurements (because these values are calculated in vtkCurveMeasurementsCalculator and it would not make much sense recalculating them in each measurement) and set by vtkCurveMeasurementsCalculator.
* They show up in the description as "curvature mean" and "curvature max"
* Their unit is "kappa" given that this was the only option I could find. We can remove the unit name if this seems incorrect.
=> ENH: Add markups curvature mean and max measurements

SuperBuild/External_VTK.cmake
```
$ git shortlog a889f47304..548df0286b --no-merges
Sankhesh Jhaveri (1):
[backport MR-7407] Shift the Z value of the 2D vertices when in the background
```
Co-authored-by: Sankhesh Jhaveri <sankhesh.jhaveri@kitware.com>
Co-authored-by: Ken Martin <ken.martin@kitware.com>
=> BUG: Update VTK to fix Slicer view rendering with VTK9. Fixes #5220

SuperBuild/External_VTK.cmake
```
$ git shortlog 548df0286..fbfecacef8 --no-merges
Fix crash in vtkOpenGLGPUVolumeRayCastMapper when removing inputs
Andrea Iob (2):
Fix declaration of vtkMakeMappedUnstructuredGridWithIter macro
Fix vtkMakeExportedMappedUnstructuredGridWithIter macro
Ben Boeckel (9):
FindNetCDF: use FPHSA on the pkg-config and cmake-config paths
QVTKInteractorAdapter: prefer QWheelEvent::position
vtkQWidgetWidget: default construct QFlags
vtkQtTreeModelAdapter: use Qt::ForegroundRole
vtkMarkBoundaryFilter: avoid implicit integer promotion
vtkModuleWrap: set policy settings for wrapping APIs
vtkModule: use interface targets to transport private links for kits
Documentation/data: mention `vtk_module_test_data` in the docs
exodusII: update to use C99
Brent Foster …
```
=> ENH: Update VTK9

SuperBuild/External_CTK.cmake
```
$ git shortlog 7210c5bc..18715f18 --no-merges
Jean-Christophe Fillion-Robin (3):
ENH: Improve ctkUtilsCopyDirRecursivelyTest1 to check file existence
BUG: Ensure copyDirRecursively considers hidden directories and files
ENH: Update copyDirRecursively to support skipping copy of hidden files
```
=> BUG: Update CTK to fix installation of extension archive with hidden files

SuperBuild/External_VTK.cmake
BUG: Update VTK to integrate improved fix for #5220
```
$ git shortlog fbfecacef8..9e9746fa49 --no-merges
Revert "[backport MR-7407] Shift the Z value of the 2D vertices when in the background"
Sankhesh Jhaveri (3):
[Backport MR-7413] Ensure depth function is GL_LEQUAL in Qt widgets
[Backport MR-7413] Initialize the opengl state with proper depth function in QVTK widgets
[Backport MR-7407] Fix the 2D mapper foreground/background transform to ignore Z values
```
=> Update VTK to integrate improved fix for #5220

Libs/MRML/Widgets/Testing/CMakeLists.txt, Libs/MRML/Widgets/Testing/qMRMLSegmentSelectorWidgetTest1.cxx, Libs/MRML/Widgets/qMRMLSegmentSelectorWidget.cxx
When populating the list of segments in qMRMLSegmentSelectorWidget, the selected/current segments were cleared when a segment was added/removed.
Fixed by blocking signals on the segment comboboxes before clearing the contents, and restoring the currently selected segment when multiSelection is not enabled.
Fixes #5287
=> BUG: Fix qMRMLSegmentSelectorWidget selection when segment added

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx
The purpose of hidden and excluded nodes is not to show them in the UI. Since subject hierarchy is supposed to have an item to every supported node in the scene, and the hidden/excluded attributes can change, it does not make sense to not add them to subject hierarchy when adding the node or loading a scene containing the node.
=> BUG: Do not skip adding hidden and excluded nodes to subject hierarchy

SuperBuild/External_ITK.cmake, SuperBuild/External_SimpleITK.cmake
Based on desire to update ITK to 5.1.2 in Slicer sooner rather than later (see https://discourse.itk.org/t/patches-for-itk-5-1-2/3635/11), this PR bumps the ITK version to that and SimpleITK also gets a minor update. With SimpleITK v2.0.1 it doesn't need to specify `Module_SimpleITKFilters_GIT_TAG`. This is because https://github.com/SimpleITK/SimpleITK/commit/b71184d1282deff2550026e87e8ce430022e04ea specified that a later ITK version no longer needed the custom SimpleITKFilters remote git tag.  ITK 5.1.2 is even later and meets the criteria to not need the custom SimpleITKFilters remote git tag.
Marking as draft first as I haven't tested the build yet.
=> Minor updates to ITK and SimpleITK version

Docs/developer_guide/python_faq.md
As suggested by @lassoan in https://github.com/Slicer/ExtensionsIndex/issues/1749.
=> DOC: Add FAQ about missing Python modules

Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.cxx, Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.h, Libs/MRML/Widgets/qMRMLSliceView.cxx, Libs/MRML/Widgets/qMRMLSliceView.h, Libs/MRML/Widgets/qMRMLThreeDView.cxx, Libs/MRML/Widgets/qMRMLThreeDView.h, Libs/MRML/Widgets/qMRMLUtils.cxx, Libs/MRML/Widgets/qMRMLUtils.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyVisibilityPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyVisibilityPlugin.h, Modules/Loadable/VolumeRendering/SubjectHierarchyPlugins/CMakeLists.txt, Modules/Loadable/VolumeRendering/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumeRenderingPlugin.cxx, Modules/Loadable/VolumeRendering/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumeRenderingPlugin.h, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin.h, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyLabelMapsPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyLabelMapsPlugin.h, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.h
A node can be shown in a view by drag-and-dropping it from the subject hierarchy into a view.
If a volume is dragged to a 3D view then volume rendering is displayed.
To show a node in a single view only, hide the node (click on the eye icon in subject hierarchy) and then drag-and-drop it into a view.
To restore visibility of a node in all views, choose "Show in all views" in subject hierarchy item visibility.
**Demo video:**
**https://youtu.be/muIlmbUSz3A**
=> ENH: Allow showing nodes by drag-and-dropping into views from subject hierarchy tree

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h
This commit fixes the following warning introduced in 412b65617 (ENH: Add
miscellaneous improvements to markups VTK widgets)
```
In file included from /path/to/Slicer/Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h:45:0,
from /path/to/Slicer/Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h:31,
from /path/to/Slicer/Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx:36:
/path/to/Slicer/Libs/MRML/DisplayableManager/vtkMRMLAbstractWidgetRepresentation.h:148:16: warning: ‘virtual void vtkMRMLAbstractWidgetRepresentation::UpdateRelativeCoincidentTopologyOffsets(vtkMapper*)’ was hidden [-Woverloaded-virtual]
virtual void UpdateRelativeCoincidentTopologyOffsets(vtkMapper* mapper);
^
In file included from …
```
=> COMP: Fix -Woverloaded-virtual in vtkSlicerMarkupsWidgetRepresentation3D

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
(Edited by @jcfr)
Following the revamp of the z-buffer computation and coincident topology
resolution integrated in VTK9 (See [1][2]), the z-buffer values are
now different. This commit accounts for this change by increasing the
world tolerance associated with small spheroid objects (such as glyphs)
and by setting a tiny tolerance for normalized display coordinates.
These tolerances are used to configure vtkSelectVisiblePoints filter
used to determine visibility of markups used to enable/disable
selectability.
[1] update and improve the coincident rendering code
https://github.com/Kitware/VTK/commit/3052137e6621684f9184b293b82c677e976c2f89
[2] Add support for camera based shift scale methods
https://github.com/Kitware/VTK/commit/8f3aef771a25b81d89ae591ef26aca5162c8c6b2
Fixes #5250 …
=> BUG: Fix markup selection with VTK9 updating tolerance

CMake/FindVcvars.cmake
Based on the changes made in https://github.com/scikit-build/cmake-FindVcvars/commit/a4d72a435d39b1adcc717c6202350a5d06056bfc
=> COMP: Update FindVcvars with MSVC 1928 support

Libs/vtkITK/vtkITKImageMargin.cxx, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorMarginEffect.py, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py
- vtkITKImageMargin would not accept labelmaps with scalar types of float or double. Fixed by adding both types to the template macro.
- Shrinking operation was not very accurate when tested on small anisotropic images (eg. TinyPatient). Improved the accuracy of the shrink operation by inverting the labelmap and using positive distance. This is necessary because  itk::SignedMaurerDistanceMapImageFilter calculates the distance of the voxels starting from the interior border voxels (which have a distance of 0.0). By inverting the labelmap the boundary voxels are outside the structure, rather than inside it.
- Add a section testing the Margin effect to SegmentationsModuleTest2. Tests shrink/grow operations on both shared and separated labelmaps of every supported data type.
=> BUG: Add tests and fix issues with Segment Editor margin effect

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyFolderPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyFolderPlugin.h
As an addition to recent work about dropping SH items into views (https://github.com/Slicer/Slicer/pull/5327), this commit adds the ability to drag&drop folders as well. In that case all the child items (recursively) of the folder are shown in the view the folder has been dropped. See alsohttps://github.com/NA-MIC/ProjectWeek/blob/master/PW34_2020_Virtual/Projects/SubjectHierarchyFolders/README.md
=> ENH: Allow dropping SH folders into views

Docs/user_guide/modules/volumerendering.md, Libs/MRML/Core/vtkMRMLViewNode.cxx, Libs/MRML/Core/vtkMRMLViewNode.h, Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx, Modules/Loadable/VolumeRendering/Resources/UI/qSlicerVolumeRenderingModuleWidget.ui, Modules/Loadable/VolumeRendering/Resources/UI/qSlicerVolumeRenderingSettingsPanel.ui, Modules/Loadable/VolumeRendering/Widgets/qSlicerVolumeRenderingModuleWidget.cxx, Modules/Loadable/VolumeRendering/Widgets/qSlicerVolumeRenderingModuleWidget.h, Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingSettingsPanel.cxx, Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingSettingsPanel.h
When rendering large volumes, it may be necessary to unload hidden volume from GPU memory.
See also: https://discourse.slicer.org/t/setting-visibility-to-off-in-volume-rendering-does-not-unload-the-volume-from-texture-memory/15127
Solution: Added "Auto-release resources" checkbox (in Volume Rendering module advanced settings). If it is checked then volume that do not have visible volume rendering are automatically unloaded from GPU memory.
=> ENH: Add option to automatically release resources when volume rendering is hidden

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyFolderPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyFolderPlugin.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx
As discussed in the PR https://github.com/Slicer/Slicer/pull/5350 it may be confusing if only the folders would show their children. Also the plugin handler needs to collect all the shown child items so that the individual plugins have the complete item list to best show the items (e.g. volumes in background and foreground). So instead of the folder plugin managing its children when dropping it, the plugin handler collects and shows all the dropped items and their children, recursively.
=> ENH: Show child items of any dropped SH item in view

Base/Python/slicer/util.py
Minor update to `createProgressDialog` doc string that closes #5351.
=> DOC: Fix incorrect details in createProgressDialog doc string

Docs/developer_guide/build_instructions/macos.md
This cleans up the macOS build instructions document which was full of old OS X version information that is no longer needed in the Slicer latest macOS build instructions page.  Slicer latest has a minimum version of macOS 10.13 and now primarily uses Qt 5.15 as the preferred Qt version.  Old platform information can always be viewed again in older versions of the documentation. The latest documentation should correspond to the current latest code.
Note that many of the "Common Errors" sections have been removed as they were for outdated platforms, or greatly outdated builds including Qt4, or the issue was simply fixed and no longer a "Common Error".
I'm not a regular macOS user, but I know these instructions were incorrect and could use a cleanup. @pieper Your knowledge on building …
=> DOC: Remove outdated macOS build instructions

CMake/SlicerCPack.cmake, CMake/SlicerCPackBundleFixup.cmake.in
For installed versions of Slicer, calling QPrinterInfo::availablePrinterNames() would return an empty list, while built versions would have the list of printers populated as normal.
The lack of available printers made it impossible to set the output of QPrinter to NativeFormat.
By bundling the printsupport plugin with the installer, the available printers can be found.
=> BUG: Fix Qt printer support for Slicer installations

Libs/MRML/Core/vtkMRMLNodePropertyMacros.h
This commit updates the macro to use "std::string" because "vtksys::String"
is not available when building against VTK 9.
It fixes a regression introduced in commit 1e0b70925 (BUG: Fixed MRML
string vector attribute writing)
=> COMP: Update vtkMRMLReadXMLStdStringVectorMacro to fix VTK9 build error

Docs/developer_guide/build_instructions/common_errors.md, Docs/developer_guide/build_instructions/linux.md, Docs/developer_guide/build_instructions/macos.md, Docs/developer_guide/build_instructions/windows.md
This fixes some broken links on GitHub to the Common Errors documentation page. See https://github.com/Slicer/Slicer/blob/bc4a07dc408089328f359436de05c3e440f7a39e/Docs/developer_guide/build_instructions/common_errors from the https://github.com/Slicer/Slicer/blob/bc4a07dc408089328f359436de05c3e440f7a39e/Docs/developer_guide/build_instructions/windows.md page.
Will see if this breaks the ReadTheDocs link with the generated preview from this PR.
=> Fix common Error documentation page links

Docs/conf.py, requirements-docs.txt
Default content:
\          SORRY            /
\                         /
\    This page does     /
]   not exist yet.    [    ,'|
]                     [   /  |
without links to the actual documentation.
notfound.extension displays a much more informative page, with links to the documentation main page and search (see for example https://docs.readthedocs.io/en/latest/thispagedoesnotexist).
=> DOC: Improve notfound page on readthedocs

Modules/Loadable/Models/Logic/vtkSlicerModelsLogic.cxx, Modules/Loadable/Models/Logic/vtkSlicerModelsLogic.h, Modules/Loadable/Models/qSlicerModelsModule.cxx
In this PR some code that seems to be not needed is removed. I found out that the Models has some functionality to keep a copy of the Colors module logic. Similar functionality found in other modules which make use of the logic they hold, however, the Models module does not seem to make any use of it. 
Removing all this functionality does not seem to break anything. There is a small change on the API (set/get functions for colors logic in ModelsLogic are removed). To me, it seems unlikely that any other module would want obtain a pointer to Colors logic through the Models logic; there are much better ways.
=> ENH: Removing unneeded code from Models module

SuperBuild/External_VTK.cmake
```
$ git shortlog 9e9746fa49..491dad3758
Sankhesh Jhaveri (1):
[Backport MR-7413] Simplify coincident topology resolution
```
See #5316 and #5317
=> BUG: Update VTK to include additional fix for coincident topology resolution

Base/QTCore/qSlicerModuleFactoryManager.cxx, Base/QTGUI/qSlicerWidget.cxx, Base/QTGUI/qSlicerWidget.h, Libs/MRML/Logic/Testing/Cxx/vtkMRMLApplicationLogicTest1.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.cxx, Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.h, Modules/Loadable/CropVolume/qSlicerCropVolumeModule.cxx, Modules/Loadable/Data/qSlicerDataModule.cxx, Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx, Modules/Loadable/Markups/Widgets/qSlicerSimpleMarkupsWidget.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.h, Modules/Loadable/Segmentations/qSlicerSegmentationsModule.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.h, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.h, Modules/Loadable/Volumes/qSlicerVolumesModule.cxx
The purpose of this PR is to frame the discussion around improving the exposure of `vtkSlicerModuleLogics` to other Slicer components (e.g., displayable managers) through `vtkMRMLApplicationLogic`. A discussion on this can be found in [https://discourse.slicer.org/t/improving-the-exposure-of-vtkslicermodulelogic-s-to-other-components/15375](https://discourse.slicer.org/t/improving-the-exposure-of-vtkslicermodulelogic-s-to-other-components/15375)
The following changes are proposed:
- Add module logic registration/unregistration methods, as well as query methods in `vtkMRMLApplicationLogic`. Unit testing has been added.
- Use registration/unregistration methods in `qSlicerModuleFactoryManager` for automatic registration of module logics on registration/unregistration of modules.
- …
=> ENH: exposing module logic in vtk mrml application logic

SuperBuild/External_python-pip.cmake
This attempts to fix an issue originally reported at https://discourse.slicer.org/t/build-on-macos-11-fails-in-the-middle-after-building-vtkpython/15570/4.
Updating Pip to version 20.3 should fix the issue as the [release notes](https://pip.pypa.io/en/stable/news/#id15) mention "Add support for MacOS Big Sur compatibility tags." With the changes it appears that macos_10_9 type wheels will be accepted on the Big Sur macOS 11 platform.
It would then be able to pick [numpy-1.19.2-cp36-cp36m-macosx_10_9_x86_64.whl](https://pypi.org/project/numpy/1.19.2/#files) as a matching wheel instead of trying to pull the source zip and then it failing to match the hash since we specifically don't include the source zip since it will require many more dependencies.
cc: @piiq
=> COMP: Update python pip to latest

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx
Interaction handles were incorrectly placed at the origin in local coordinates. Resulted in incorrect handle position if the plane was transformed.
=> BUG: Position interaction handles at plane origin in world coordinates

CMakeLists.txt
This commit ensures that Slicer_VERSION_* variables are not reset
to 0 after calling "find_package(Slicer)" in bundled extensions.
=> COMP: Fix version check in extension bundled in custom applications

SuperBuild.cmake
Previously 4 volumes were laid out in a 3x2 grid with empty
slots at the bottom so space was wasted.
Now 4 volumes are in a 2x2 and 6 volumes are in a 3x2 grid.
https://github.com/pieper/CompareVolumes/pull/11
=> ENH: Update CompareVolumes to improve layouts

Modules/Loadable/Models/Testing/Cxx/qSlicerModelsModuleWidgetTest1.cxx
Functions "data()" and "get()" are equivalent
=> COMP: Update qSlicerModelsModuleWidgetTest1 to fix build with Qt < 5.11

Libs/MRML/Core/vtkMRMLSliceCompositeNode.cxx, Libs/MRML/Core/vtkMRMLSliceCompositeNode.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx
This commit simplifies management of background, foreground and layer
volume references.
=> ENH: Re-factor vtkMRMLSliceCompositeNode to use node references

Modules/Loadable/Cameras/Logic/vtkSlicerCamerasModuleLogic.cxx, Modules/Loadable/Cameras/Logic/vtkSlicerCamerasModuleLogic.h, Modules/Loadable/Cameras/Testing/Cxx/vtkSlicerCamerasModuleLogicCopyImportedCamerasTest.cxx, Modules/Loadable/Data/Resources/UI/qSlicerSceneIOOptionsWidget.ui, Modules/Loadable/Data/qSlicerSceneIOOptionsWidget.cxx, Modules/Loadable/Data/qSlicerSceneReader.cxx
Properties of the scene-to-import camera nodes are always copied into the existing nodes having the same name. This is done when a camera node is about to be added to the scene.
=> ENH: Always copy camera when importing MRML scene

Libs/vtkSegmentationCore/vtkSegmentationConverter.cxx
For some Segmentation conversion methods vtkSegmentationConverterRule::GetConversionInfiniteCost() (10000000) is used to represent a last resort conversion path that should not be used unless it is the only one that can be found.
GetCheapestPath initialized the cheapestPathCost using 10000000. This meant that the cheapest path would never be found if its cost was >= 10000000.
Fixed by initializing cheapestPathCost to VTK_UNSIGNED_INT_MAX.
See SlicerRt/SlicerRT#177
=> BUG: Fix vtkSegmentationConverter::GetCheapestPath if cost >= 10000000

Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx, Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.h, Modules/Loadable/Terminologies/Widgets/qSlicerTerminologySelectorDialog.cxx
Besides clicking Select in the terminology selector dialog, now double-clicking on the type has the same effect. It makes selecting terminology faster in simple cases (when modifiers do not need to be set).
=> ENH: Double click on type selects terminology

Modules/Scripted/DICOM/DICOMExtensions.json
Since the Longitudinal PET/CT extension
is not currently available, remove
it from the suggestion list for now.
Longer term: once the new extension manager
is in place, consider auto-generating
suggestions based on a query of available
extension.  We should also explore adding
tags to s4ext files that could explicitly
declare the data types they are appropriate
for.
Co-authored-by: Sonia Pujol <spujol@bwh.harvard.edu>
=> BUG: remove unavailable extension suggestion

Libs/MRML/Core/vtkMRMLSliceNode.cxx, Libs/MRML/Core/vtkMRMLSliceNode.h, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLinkLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.h
Users were confused by showing reformatted images by default, therefore image display actions are changed to facilitate axis-aligned display.
Slice views are rotated to be aligned with closest image axes if:
- Volume selection is propagated - for example when a volume is loaded or a CLI completes execution. Unless if a view is excluded by setting vtkMRMLSliceCompositeNode::DoPropagateVolumeSelection to false or "show" option is disable in Add data dialog.
- In Data module / Subject hierarchy tree -> eye icon is clicked. Unless "Reset view orientation on show" checkbox (checked by default) is unchecked in context menu of the eye icon.
- Dragging a volume from Data module / Subject hierarchy tree to a view. Unless "Reset view orientation on show" checkbox (checked by default) is unchecked …
=> ENH: Make slice views aligned with image axes by default

Applications/SlicerApp/Testing/Python/SlicerAppTesting.py, Base/Logic/vtkSlicerApplicationLogic.cxx, Base/Logic/vtkSlicerApplicationLogic.h, Base/QTCLI/vtkSlicerCLIModuleLogic.cxx, Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication_p.h, CMake/BundleUtilitiesWithRPath.cmake, CMake/GetPrerequisitesWithRPath.cmake, CMake/SlicerBlockCTKAppLauncherSettings.cmake, CMake/SlicerConfig.cmake.in, CMake/SlicerExtensionCPackBundleFixup.cmake.in, CMake/SlicerMacroBuildApplication.cmake, CMake/vtkSlicerVersionConfigureInternal.h.in, CMakeLists.txt, Libs/MRML/DisplayableManager/vtkMRMLInteractionEventData.h, Libs/MRML/Widgets/qMRMLWidget.cxx, Libs/vtkITK/vtkITKImageMargin.h, Libs/vtkITK/vtkITKIslandMath.h, Utilities/Scripts/SlicerWizard/ExtensionWizard.py, Utilities/Scripts/SlicerWizard/Utilities.py
This includes updates to use macOS term in code comments instead of older Mac OS X name.  There a few additional commits that remove workarounds for old mac versions.
=> STYLE: Use macOS in comments instead of old Mac OS X

CONTRIBUTING.md, Docs/developer_guide/build_instructions/macos.md, Docs/developer_guide/build_instructions/overview.md, Docs/developer_guide/extensions.md, Docs/user_guide/about.md, README.txt
This PR includes various updates to doc files.
- Removes documentation of old `Slicer_USE_PYTHONQT_WITH_TCL` build option.
- Replaces the build instructions link in the README with the Slicer ReadTheDocs build instructions link
- Uses correct name usage of macOS instead of Mac OS or Mac OS X in documentation files
=> Various doc updates removing old TCL build option, build instructions link, and old macOS names

SuperBuild/External_VTK.cmake
```
$ git shortlog 106104086f..d76bf153dd --no-merges
Will Schroeder (1):
[Backport] Fixed NormalizeCoordinates option
```
Fixes #5223
Co-authored-by: Sam Horvath <sam.horvath@kitware.com>
Co-authored-by: Will Schroeder <will.schroeder@kitware.com>
=> BUG: Update VTK 9 to fix surface smoothing of segmentation

Libs/MRML/DisplayableManager/vtkMRMLAbstractDisplayableManager.cxx, Libs/MRML/DisplayableManager/vtkMRMLModelSliceDisplayableManager.cxx, Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager2D.cxx, Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager3D.cxx, Modules/Loadable/Transforms/MRMLDM/vtkMRMLLinearTransformsDisplayableManager3D.cxx, Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformsDisplayableManager2D.cxx, Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformsDisplayableManager3D.cxx, Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
This commit fixes crashes when using the python interactor by improving check for MRML scene validity in ProcessMRMLNodesEvent() and GetSelectionNode()
=> BUG: Avoid crash in DisplayableManager by checking for null scene pointer

CMakeLists.txt, SuperBuild.cmake
This commit sets `vtkAddon_LAUNCH_COMMAND` using `Slicer_LAUNCH_COMMAND` so that
the environment allowing to run vtkAddon tests on Windows is setup.
```
$ git shortlog 5df87dee7..4a50619 --no-merges
BUG: Fix tests execution on windows adding "vtkAddon_LAUNCH_COMMAND" option
Rafael Palomar (2):
COMP: Fix configuration for VTK with external HDF5
ENH: Add installation of vtkAddon CMake files
```
=> BUG: Update vtkAddon and fix execution of associated tests

Libs/MRML/Core/vtkMRMLDiffusionImageVolumeNode.h, Libs/MRML/Core/vtkMRMLVectorVolumeNode.h, Libs/MRML/Core/vtkMRMLVolumeNode.h
In vtkMRMLVolumeNode, vtkMRMLVectorVolumeDisplayNode was used as the class name in vtkMRMLCopyContentMacro, rather than vtkMRMLVolumeNode.
Fixed by updating the macro with the correct class name.
vtkMRMLVectorVolumeNode was missing a vtkMRMLCopyContentDefaultMacro() so HasCopyContent() always returned false.
This prevented vector volume nodes from being displayed in the list of proxy nodes in the Sequences module.
Fixed by adding the missing macro.
=> BUG: Fix incorrect/missing volume node copy content macros

Libs/MRML/DisplayableManager/vtkMRMLSliceViewInteractorStyle.cxx
This commit fixes a crash in `vtkMRMLSliceViewInteractorStyle` reproducible
with the following snippet:
```python
viewWidget = slicer.qMRMLSliceWidget()
viewWidget.show()
```
=> BUG: Fix crash when creating and showing qMRMLSliceWidget using python

Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx, Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.h, Modules/Loadable/Segmentations/qSlicerSegmentationsModule.cxx
The visibility of the segment subject hierarchy visibility was not being updated when segment display properties were modified.
Fixed by adding the slot qSlicerSubjectHierarchySegmentationsPlugin::onDisplayNodeModified() that is invoked when the display node is modified.
This slot updates all segment items from the corresponding display node.
See discussion here: https://discourse.slicer.org/t/visibility-of-segments-from-data-module-vs-segment-editor-segmentations/15888
=> BUG: Fix segment subject hierarchy visibility when display node modified

SuperBuild/External_python.cmake
This fixes a segfault occurring in some linux distributions. Suspected
incompatibility between libffi>=3.4 and Slicer cpython, but not 100% confirmed. The proposed changes seem harmless anyways.
For discussion see [https://discourse.slicer.org/t/cant-start-latest-stable-on-ubuntu-20-04/14029/35](https://discourse.slicer.org/t/cant-start-latest-stable-on-ubuntu-20-04/14029/35)
=> BUG: Enabling builtin ctypes in python

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
Instead of
`self.ui.SubjectHierarchyTreeView.setColumnHidden(self.ui.SubjectHierarchyTreeView.model().idColumn, True)`
we can now use
`self.ui.SubjectHierarchyTreeView.idColumnVisible = False`
Same for color and transform columns.
=> ENH: Add properties for easy visibility setting of SH tree columns

Base/Python/slicer/util.py, Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyGenericSelfTest.py, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
In addition to allowing one attribute name (and value for that attribute) to be filtered, now multiple attributes can be specified that control which items show up in the subject hierarchy trees and comboboxes with more granularity.
- addItemAttributeFilter / addNodeAttributeFilter: add new attribute filter that can filter by attribute name and value, and class name in case of node filter
- removeItemAttributeFilter / removeNodeAttributeFilter: remove certain filters defined by only attribute name or each property
- includeItemAttributeNamesFilter: convenience function to show only items that contain any of the given attributes with this name (removes all previously added include item attribute filters)
- includeNodeAttributeNamesFilter: convenience function to show only items for data …
=> ENH: Extend capabilities of subject hierarchy attribute filtering

Modules/Loadable/VolumeRendering/Testing/Cxx/vtkMRMLVolumeRenderingDisplayableManagerTest1.cxx
Volume rending logic switched from directly instantiating an ROI node to using AddNewNodeByClass.
Fixed test by registering the ROI nodes to the test scene.
=> BUG: Fix vtkMRMLVolumeRenderingDisplayableManagerTest1

Base/QTGUI/qSlicerIOManager.cxx, Libs/MRML/DisplayableManager/vtkMRMLModelSliceDisplayableManager.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Libs/MRML/Widgets/qMRMLLayoutManager.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
These changes make scene loading many times faster if there are hundreds of nodes in the scene.
- Pause rendering during batch processing and data loading for better performance. When the operation is completed, rendering is resumed and any pending rendering requests are processed.
- Make show/hide model slice intersections faster by not removing and re-adding all actors, but only removing/adding those that have changed.
=> ENH: Performance improvements

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
By observing the Modified event of each measurement in the markup nodes, updating the measurements is possible when any of them are e.g. enabled programmatically.
=> ENH: Observe markup measurements to trigger necessary updates

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/MRML/CMakeLists.txt, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIDisplayNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.h, Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx
List of improvements:
- Default fill opacity set to 20%
- Disable fill visibility for volume rendering by default
- Add outline in 3D views
- Remove out of plane ROI outline in 2D
- Increase interaction handle size by 2x in 3D views
- Enable right-click menu for scale handles
- Add interaction handle visibility context menu appear in subject hierarchy widget visibility column
- Hide interaction handles when out of plane
- Enable ROI interaction handles by default
=> ENH: Miscellaneous ROI display improvements

SuperBuild/External_SimpleITK.cmake
On Nov. 30th 2020 I upgraded Slicer to use SimpleITK v2.0.1 and also updated ITK to 5.1.2. SimpleITK v2.0.2 was released later that day, so I just barely missed that update.  No major changes with v2.0.2, but it officially was targeting ITK 5.1.2 as well.
```
$ git shortlog --no-merges v2.0.1..v2.0.2
Bradley Lowekamp (3):
Add missing SWIG mapping for int 64 and void pointer types
Update ITK Superbuild version to 5.1.2
Update release version to 2.0.2
```
=> COMP: Update SimpleITK to v2.0.2

Base/QTGUI/qSlicerApplication.cxx, Modules/Loadable/Units/qSlicerUnitsSettingsPanel.cxx
Units and recent log file paths were stored in the revision-specific application settings, which was not ideal because it generated warning messages when Slicer is launched from a read-only location (and revision-specific settings file is not created in the user profile folder).
see #4966
=> ENH: Move unit and recent log file paths storage to common application settings

Base/QTCore/qSlicerCoreApplication.cxx, Base/QTGUI/qSlicerSettingsModulesPanel.cxx
To ensure that CLI modules, sample data downloads, etc. work it is necessary to have a writable temporary directory.
In some cases the path specified in application settings does not point to a valid, writable location anymore.
To fix this, the application checks at startup that the temporary path is writeable. If the check fails then the path is reset to the default.
see #4652
=> BUG: Ensure temporaryPath is writable

Base/Python/slicer/util.py, Modules/Scripted/DICOM/DICOM.py
Use standard sphinx syntax for exceptions and deprecation.
Remove verbose parameter (always throw exception instead).
Based on feedback from @jcfr - https://github.com/Slicer/Slicer/pull/5451#pullrequestreview-589153421
=> STYLE: Make slicer.util API documentation more consistent

CMake/SlicerMacroBuildScriptedCLI.cmake
This commit ensures the string "Copying ..." is displayed only when
the files are effectively copied.
=> ENH: Update SlicerMacroBuildScriptedCLI to display comment only if needed

Docs/developer_guide/build_instructions/linux.md
A few `cd` commands were missed or duplicated, now commands can be copy-pasted into a terminal one after the other to configure, build, test, and package Slicer.
=> DOC: Improved linux build instructions

Base/QTCLI/CMakeLists.txt, CMake/SlicerMacroBuildModuleLogic.cmake
=> BUG: Fix python wrapping of vtkSlicerCLIModuleLogic using VTK9

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIDisplayNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.h
List of improvements:
- When an ROI is already active and the user clicks place mode, create a new ROI rather than modify the old one.
- Correctly switch between box and bounding box ROI types.
- Enable hover and interaction (right-click) on ROI outline.
- Change box ROI type to place a single fiducial at the center of the ROI.
=> ENH: Improve markup ROI interaction

Base/Python/slicer/util.py
In several places in util.py, statusBar was called as a property, rather than as a method.
This caused an error when setStatusBarVisible was called.
Fixed by changing mw.statusBar -> mw.statusBar()
=> BUG: Fix MainWindow.statusBar() calls in util.py

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
When hitting a key on a subject hierarchy item that did not have an owner, the scene stopped updating.
It was due to starting but not ending a batch processing event when no owner plugin was found for the item.
=> BUG: Fix scene not updating after toggling subject hierarchy item visibility

Libs/MRML/Widgets/qMRMLTableView.cxx
When table view node was not set in a qMRMLTableView but the table node was set correctly, a scene batch update resulted in resetting the table node.
See user report here: https://discourse.slicer.org/t/cant-modify-a-table-in-tables-module-after-using-landmark-registration-module/16069
qMRMLTableView is allowed to be used without a view node, so fixed the problem by ignoring scene batch processing update if view node is not set.
=> BUG: Fix table view losing table node selection after batch processing

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.h
The GetJsonStorageNodeClassNameForMarkupType was supposed to return the default Json storage node "vtkMRMLMarkupsJsonStorageNode" if a specific storage node wasn't registered for the markup type, but it instead returned an empty string.
Fixed by changing default return to the correct value.
=> BUG: Fix default storage node creation in LoadMarkupsFromJson

Libs/MRML/Core/vtkMRMLSliceNode.cxx, Libs/MRML/Core/vtkMRMLSliceNode.h, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx
When "Reset view orientation on show" was enabled then single-slice volumes fully appeared in all view (view normal aligned with slice normal), with different rotations.
This resulted in redundant and slightly confusing views.
Fixed the problem by forcing slice view normal to be aligned with the volume slice normal only if a volume is requested to be shown in a single view.
If a volume is shown in multiple views then each slice view is aligned with the nearest volume axis.
Before the fix:
After the fix:
=> ENH: Improve default axis-aligned display of single-slice volume

Docs/user_guide/modules/markups.md, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIWidget.h
Pressing the shift button while scaling the ROI will adjust the size of the ROI symmetrically, keeping the origin in the same location.
Re #5061
=> ENH: Add Shift shortcut for changing ROI size without moving origin

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx, Modules/Loadable/Markups/Widgets/CMakeLists.txt, Modules/Loadable/Markups/Widgets/DesignerPlugins/CMakeLists.txt, Modules/Loadable/Markups/Widgets/DesignerPlugins/qMRMLMarkupsInteractionHandleWidgetPlugin.cxx, Modules/Loadable/Markups/Widgets/DesignerPlugins/qMRMLMarkupsInteractionHandleWidgetPlugin.h, Modules/Loadable/Markups/Widgets/DesignerPlugins/qSlicerMarkupsModuleWidgetsPlugin.h, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsDisplayNodeWidget.ui, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsInteractionHandleWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsInteractionHandleWidget.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsInteractionHandleWidget.h
Markup display nodes now have the option to show/hide interaction handle types separately (Translation, Rotation, Scale).
All interaction handle types are shown by default if interaction visibility is enabled. For ROI display nodes, translation and rotation handles are hidden by default.
Visibility of handle types can be controlled from the markup display node widget, or through the subject hierarchy context menu.
This commit also reduces the thickness of the translation arrows by 25%.
Re #5061
=> ENH: Add separate node attributes for interaction handle visibility

Base/Python/slicer/util.py, Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication.h
macOS started to manage application temporary and cache folders more actively, i.e., remove them after certain time period (or at system restart or application exit) to improve security.
Cache folder by default was initialized to be a subfolder of temporary folder. However, when the system removed the temporary folder, the cache folder has become invalid.
To fix this, implemented an automatic mechanism to check the cache folder at startup and reset it to a system-recommended location if the folder is not writable.
See related user error report: https://discourse.slicer.org/t/slicer-4-11-on-m1-not-loading-mrb-file/16228/7
The pull request also contains an unrelated commit with a trivial fix of missing imports in slicer.util.
=> ENH: Ensure that remote cache folder is writable

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect.cxx
If Segment Editor Paint effect was interrupted by hitting Escape then next time it was used again, a stray stroke was added because IsPainting state variable was not reset.
See user error report at https://discourse.slicer.org/t/issue-with-brush-or-eraser/16270
=> BUG: Fix paint effect drawing extra strokes after interrupted

Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx
Previously, creating a vtkMRMLMarkupsLineNode with 2 control points and then removing one or both would leave a line in the 3D view.
This commit hides the line actor if there aren't 2 defined control points.
=> ENH: Hide markup line in 3D view if the number of control points != 2

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
While hovering over interaction handles, the mouse was constantly flickering between interactive and non-interactive modes due to missing MouseMoveEvent/Move3DEvent event translations.
=> BUG: Fix mouse flicker when hovering over interaction handles

SuperBuild/External_VTK.cmake
To ensure the Slicer can run on system where only libGL is available,
this commit updates VTK to make sure setting OpenGL_GL_PREFERENCE
to LEGACY works as expected. For reference, setting to LEGACY value
was originally introduced in Slicer@23d8144 (BUG: Fix linux package
removing dependency to GLVND libraries).
```
$ git shortlog d76bf153dd..60b13991d3
COMP: Remove custom FindOpenGL to ensure OpenGL_GL_PREFERENCE is considered
```
Fixes #5228
Fixes #5286
=> BUG: Fix linux package ensuring OpenGL_GL_PREFERENCE is considered with VTK9

Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx
- 2D ROI
- CanInteractROI threshold is now based on display, rather than world coordinates. Improves behavior at high zoom levels.
- 2D plane
- CanInteractWithPlane now works for both the outline and slice intersection.
- 3D plane
- Fixed picking of 3D plane representation by moving the outline to a separate actor.
- CanInteractWithPlane function now checks to see if the users is hovering over the plane outline, rather than the plane fill.
All representations should be made faster by keeping a reference the cell locator.
=> ENH: Improve Markups Plane and ROI interaction

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h
The implementation of GetRASBounds and GetBounds implemented by vtkMRMLMarkupsNode only took the control point positions into account.
For ROI bounds, we now compute the bounds based on the location of the corner points of the ROI.
Re #5061
=> ENH: Add Markups ROI GetRASBounds and GetBounds functions

Base/QTCore/qSlicerCoreApplication.cxx
Without this `#include <QTemporaryFile>` I got compilation error telling me that `QTemporaryFile` is undefined. With this little change I could compile on Windows 10 MSVC2019, Qt 5.15.2
=> COMP: Undefined class "QTemporaryFile" when building using SlicerCAT

Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx, Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.h
See user request:
https://discourse.slicer.org/t/i-want-to-boot-up-with-my-very-own-color-map-and-a-black-background/16383/10?u=lassoan
=> ENH: Add custom volume rendering presets to the top of the preset list by default

SuperBuild/External_DCMTK.cmake
re #5510 and https://github.com/QIICR/dcmqi/issues/341#issuecomment-707053566
Update to official 3.6.6 release plus an extra backported patch:
https://git.dcmtk.org/?p=dcmtk.git;a=commit;h=b665e2ec2d5ce435e28da6c938736dcfa84d0da6
```
$ git shortlog DCMTK-3.6.5..patched-DCMTK-3.6.6_20210115 --no-merges
Jan Schlamelcher (4):
Updated version information for 3.6.5+ development.
Fixed various typos and whitespace errors.
Allow overriding support library search behaviour.
Harmonized documentation of calcElementLength().
Joerg Riesmeier (120):
Fixed typos and other minor issues.
Enhanced performance of inserting sequence items.
Enhanced performance of getting a sequence item.
Updated data dictionary for DICOM 2019d.
Updated code definitions for DICOM 2019d.
Updated Context Group …
```
=> ENH: update DCMTK to version 3.6.6

Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx
This commit hides the line actor if all of the points on the markup curve are outside of the slice by 0.5 * slice thickness.
Re #5480
=> ENH: Hide markups in slice views when they do not intersect the slice

SuperBuild/External_VTK.cmake
```
$ git shortlog e88e47c967..1076d8bc00 --no-merges
Andras Lasso (2):
[Backport] Prevent vtkDebugLeaks from polluting process output if no leaks are found
[Backport] Fix crash in vtkOpenGLFramebufferObject::GetMultiSamples()
```
=> BUG: Update VTK to fix crash and avoid process output polluting by debug leaks

CMake/SlicerCPackBundleFixup.cmake.in, CMake/SlicerExtensionCPackBundleFixup.cmake.in
This commit ensures vtk modules that do not start with "vtk" prefix (e.g SplineDrivenImageSlicer)
are also fixed up.
It is a follow up of these commits:
* 08789e8: COMP: Fix packaging of VTK9 python modules
* d630005: COMP: Fix macOS package adding fixup rules for VTK9 python modules
* 0b15603: COMP: Fix macOS package setting "path" in VTK9 python modules fixup rules
Fixes #5285
Fixes #5521
=> COMP: Ensure all vtk python modules are fixed up on macOS

CMake/SlicerBlockInstallPython.cmake
This commit fixes "ELF load command address/offset not properly aligned" runtime
error reported when attempting to import some python modules.
Instead of systematically stripping all libraries, this commit updates the
packaging rules Strip symbols of selected libraries for which ones
(1) stripping has a significant impact
and (2)  stripping does not prevent the successful import of the module.
Example of error reported:
```
$ ./bin/PythonSlicer -c "from scipy.special import _ufuncs as u; from pprint import pprint as pp; pp(dir(u))"
[...]
ELF load command address/offset not properly aligned
```
Fixes #5474
=> BUG: Fix import of python modules on Linux selectively stripping libraries

Libs/vtkITK/vtkITKDistanceTransform.cxx, SuperBuild.cmake, SuperBuild/External_ITK.cmake, SuperBuild/External_SimpleITK.cmake
This PR updates ITK to recent latest in preparation for ITK v5.2.0 release. This includes https://github.com/InsightSoftwareConsortium/ITK/commit/7cebc26dfae73d90dbf4702aa1ccc544e9b70a37 which helped solve an ITK build error that was happening when I was building latest Slicer using Visual Studio 16.9 (recently released).
Slicer vtkITKDistanceTransform.cxx updates were made based on changes introduced in https://github.com/InsightSoftwareConsortium/ITK/commit/076e990904fea748c4f139d1bb69c45ec6669220. Thanks to @dzenanz for helping out on these fixes.
All tests were run on Windows with only 1 test failing which appears to have already been failing on the Windows platform.
```
1>
1>99% tests passed, 1 tests failed out of 680
..
1>The following tests FAILED:
1>	318 - …
```
=> COMP: Update ITK to post-v5.2rc03 with matching SimpleITK and BRAINSTools

Modules/Scripted/SampleData/SampleData.py
The current three-column box layout resizes the module panel if it was narrower than what could fit three thumbnails, which was an inconvenience especially on smaller monitors or smaller window sizes, because the user had to manually resize the panel after switching to another module if they wanted to see the viewers in the usual size.
By using flow layout the thumbnails naturally fit the available horizontal space.
https://user-images.githubusercontent.com/1325980/111494297-40cb9680-8736-11eb-988c-18a8ead0e61e.mp4
=> ENH: Use flow layout in Sample Data module

Base/QTCore/qSlicerCoreApplication.cxx
Untested
SlicerJupyter is using this function to determine the Slicer Launcher file path and it is failing for a custom app name.
=> BUG: launcher executable now using app name to compose the filepath

Libs/MRML/Core/vtkMRMLMeasurement.cxx, Libs/MRML/Core/vtkMRMLMeasurement.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx
The custom modified event InputDataModifiedEvent has been introduced in vtkMRMLMeasurement that is invoked only when such members are modified that should trigger update of the measurement. By observing this event for updating the measurements, circular calls are prevented.
A concrete effect is that curvature computation and scalar display update is fast again.
Fixes https://github.com/Slicer/Slicer/issues/5486
=> BUG: Fix circular markups measurement update calls

Base/QTGUI/Resources/UI/qSlicerSettingsViewsPanel.ui, Base/QTGUI/qSlicerSettingsViewsPanel.cxx, Base/QTGUI/qSlicerSettingsViewsPanel.h, Libs/MRML/Core/Testing/vtkMRMLSliceNodeTest1.cxx, Libs/MRML/Core/vtkMRMLSliceNode.cxx, Libs/MRML/Core/vtkMRMLSliceNode.h, Libs/MRML/Widgets/Testing/qMRMLSliceControllerWidgetTest.cxx, Modules/Loadable/ViewControllers/Logic/vtkSlicerViewControllersLogic.cxx, Modules/Loadable/ViewControllers/qSlicerViewControllersModule.cxx, Modules/Loadable/ViewControllers/qSlicerViewControllersModule.h
User can choose between radiology and neurology view directions (patient left/right on screen right).
=> ENH: Make default slice view orientations configurable

Base/Logic/vtkSlicerApplicationLogic.cxx, Base/Logic/vtkSlicerApplicationLogic.h, Base/QTCLI/qSlicerCLIModuleFactoryHelper.cxx, Base/QTCore/Testing/Cxx/qSlicerUtilsTest1.cxx, Base/QTCore/qSlicerLoadableModuleFactory.cxx, Base/QTCore/qSlicerUtils.cxx, Base/QTCore/qSlicerUtils.h, Base/QTGUI/qSlicerScriptedLoadableModuleFactory.cxx
Modules in Extensions-<revision> folder must be always classified as not built-in, even if that folder is within the application folder.
Previously Extensions-<revision> folder only contained extension modules on macOS, but now since applications are fully portable, this folder contains extension modules on all operating systems.
=> BUG: Fix logic that determines if a module is built-in

Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.cxx, Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.h, Modules/Loadable/CropVolume/MRML/vtkMRMLCropVolumeParametersNode.cxx, Modules/Loadable/CropVolume/MRML/vtkMRMLCropVolumeParametersNode.h, Modules/Loadable/CropVolume/Resources/UI/qSlicerCropVolumeModuleWidget.ui, Modules/Loadable/CropVolume/qSlicerCropVolumeModuleWidget.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIWidget.cxx
This pull request makes Crop volume work with the new markups ROI. Markups ROI node has many advantages over Annotation ROI, for example that it can be rotated without applying a transform.
=> Make Crop volume module compatible with Markups ROI node

Libs/MRML/Widgets/qMRMLSegmentSelectorWidget.cxx, Libs/MRML/Widgets/qMRMLSegmentSelectorWidget.h, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
Segment selector widget in qMRMLSliceControllerWidget made segments hidden when the segmentation display node was updated earlier than the segmentation node.
The problem was that qMRMLSliceControllerWidget made all segments that were not in the segment selector widget hidden, and segments were not yet in the segment selector widget when they have just been added but node modified event was not yet invoked.
Fixed by not modifying visibility of those segments that are not yet in the segment selector widget.
Fixes #5533
=> BUG: Fix new segments appearing as hidden

Modules/Loadable/CropVolume/Resources/UI/qSlicerCropVolumeModuleWidget.ui, Modules/Loadable/CropVolume/qSlicerCropVolumeModuleWidget.cxx
Crop volume requires the output volume node type to be the same as the input volume node type.
There was no option to create vector volume, therefore it was not possible to pre-create the output volume for vector volumes.
The error only appeared in the log.
Fixed by adding display of the error message in the module widget and added the option of creating vector volume output.
Addresses the problem reported by a user: https://discourse.slicer.org/t/crop-volume-reports-error-when-input-is-a-color-volume/16857
=> BUG: Make cropping of vector volumes more intuitive

SuperBuild.cmake
List of `MultiVolumeImporter` changes:
```
$ git shortlog --no-merges b701ca1..04afeb1
Fix VTK9 incompatibility
```
List of `MultiVolumeExplorer` changes:
```
$ git shortlog --no-merges 8be7d7a..5e69562
Fix VTK9 incompatibility
```
Fixes #5560
=> BUG: Update MultiVolumeImporter/MultiVolumeExplorer to support VTK9

Libs/MRML/Core/vtkMRMLNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
Prevent updating the internal vtkPoints structure, interaction handles, and measurements from control points between StartModify/EndModify calls.
These are performed automatically in EndModify().
This makes point insertion fast, even if points are added one by one (but between StartModify/EndModify calls).
fixes #5564 (slow fcsv loading)
=> ENH: Optimize markups batch update speed

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/Testing/Python/CMakeLists.txt, Modules/Loadable/Markups/Testing/Python/MarkupsCurveCoordinateFrameTest.py, SuperBuild.cmake
Previously, "consistent" variant of Frenet-Serret method (in SplineDrivenImageSlicer VTK remote package) was used in GetCurvePointToWorldTransformAtPointIndex to get coordinate frame along the curve. However, this implementation had random initial normal direction and it was not robust when points were too close to each other.
This commit switches to a parallel transport method, which is more robust and predictable. Initial direction is set so that +X direction is preferred as normal direction (if curve tangent is exactly +X then +Y direction is preferred as binormal direction).
Fixes #5559
=> ENH: Use parallel transport for more robust curve coordinate system computation

Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCorePythonManager.cxx, Base/QTCore/qSlicerExtensionsManagerModel.cxx
Path environment variables could grow over 32k when installing a few extensions.
There were some checks trying to prevent adding duplicate paths, but they had logic flaws and some checks were missed.
I've discovered this because Elastix failed to launch because the environment was huge, with lots of duplicate entries in path, pythonpath, and librarypath. Hopefully this will fix the issue (I could not reproduce the massive amount of duplication in a debug-mode local build that occurred in a release build, with installing and updating many extensions).
=> BUG: Prevent duplicate paths added to environment variables

SuperBuild/External_ITK.cmake, SuperBuild/External_SimpleITK.cmake
This PR updates ITK to v5.2.0 and updates SimpleITK to a commit (https://github.com/SimpleITK/SimpleITK/commit/1062acf7705dd53f0cf01789b7c4a3b4a1bf15a0) where SimpleITK also updated to use ITK v5.2.0.
All Tests passed on the Windows platform
```
1>
1>100% tests passed, 0 tests failed out of 681
1>
```
Changelog:
```
ITK:
$ git shortlog --topo-order --no-merges 2b34388..v5.2.0
Bradley Lowekamp (2):
BUG: Initialize member variables
STYLE: Prefer in class initialization
Dženan Zukić (10):
COMP: fix CMake Deprecation Warning (Compatibility with CMake < 2.8.12)
ENH: update remote modules
ENH: add Ultrasound remote module
STYLE: mark ultrasound remote module enablement as advanced variable
DOC: improve description of LBFGSERR_ROUNDING_ERROR stopping condition
STYLE: use ReadImage and WriteImage …
```
=> COMP: Update ITK to v5.2.0 and update SimpleITK

Modules/Scripted/DICOMLib/DICOMUtils.py
This commit avoids reporting error on system where no original database
was created.
=> BUG: Fix closeTemporaryDatabase to re-open original database only if it exists

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.h
Undo/Redo buttons were enabled before having done anything in the module. A new function has been added that does both types of checks that are needed to decide enabled state for these buttons, and this function is called both from updateWidgetFromMRML and onSegmentationHistoryChanged.
=> BUG: Fix Segment Editor Undo/Redo button states

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/qSlicerMarkupsModule.cxx
Change default to enable shadow and bold. Fix bug in saving/restoring shadow properties. Allow saving all markups display properties.
See discussion here: https://discourse.slicer.org/t/improve-markups-label-visibility/17022/10
=> Improve markups label visibility

Applications/SlicerApp/Testing/Python/CLIEventTest.py, Applications/SlicerApp/Testing/Python/Charting.py, Applications/SlicerApp/Testing/Python/FiducialLayoutSwitchBug1914.py, Applications/SlicerApp/Testing/Python/JRC2013Vis.py, Applications/SlicerApp/Testing/Python/RSNAQuantTutorial.py, Applications/SlicerApp/Testing/Python/RSNAVisTutorial.py, Applications/SlicerApp/Testing/Python/SlicerMRBSaveRestoreCheckPathsTest.py, Applications/SlicerApp/Testing/Python/TwoCLIsInARowTest.py, Applications/SlicerApp/Testing/Python/TwoCLIsInParallelTest.py, Applications/SlicerApp/Testing/Python/WebEngine.py, Libs/MRML/Widgets/Testing/qMRMLChartViewTest.py, Libs/vtkITK/Testing/vtkITKArchetypeDiffusionTensorReaderFile.py, Libs/vtkITK/Testing/vtkITKArchetypeScalarReaderFile.py, Modules/Loadable/Annotations/SubjectHierarchyPlugins/AnnotationsSubjectHierarchyPlugin.py, Modules/Loadable/Plots/Testing/Python/PlotsSelfTest.py, Modules/Loadable/Segmentations/EditorEffects/Python/AbstractScriptedSegmentEditorAutoCompleteEffect.py, Modules/Loadable/Tables/Testing/Python/TablesSelfTest.py, Modules/Scripted/DataProbe/DataProbe.py, Modules/Scripted/EditorLib/EditUtil.py, Modules/Scripted/EditorLib/PaintEffect.py, Modules/Scripted/EditorLib/WatershedFromMarkerEffect.py, Modules/Scripted/LabelStatistics/LabelStatistics.py, Modules/Scripted/PerformanceTests/PerformanceTests.py, Modules/Scripted/SampleData/SampleData.py, Modules/Scripted/ScreenCapture/ScreenCapture.py, Utilities/Scripts/ExtensionWizard.py, Utilities/Scripts/SlicerWizard/TemplateManager.py
I noticed an instance of a trailing semicolon being used in some python code. I used the following script to find other similar uses and then removed the trailing semicolon after manually reviewing each instance. Some were part of some embedded logic that wasn't python getting passed elsewhere or were some C++ examples in comments of a python file.
```python
import os
search_directory = os.path.join(os.getenv('UserProfile'), "Documents", "GitHub", "Slicer")
for root, dirs, files in os.walk(search_directory):
for filename in files:
if filename.endswith(".py"):
filepath = os.path.join(root, filename)
with open(filepath, "r") as open_file:
lines = open_file.readlines()
for index, line in enumerate(lines):
if line.endswith(";\n"):
print(filepath)
print(f"LINE: {index+1}:" + line)
```
=> STYLE: Remove unnecessary trailing semicolon in python code

Libs/vtkSegmentationCore/vtkSegmentationModifier.cxx, Libs/vtkSegmentationCore/vtkSegmentationModifier.h
Improve the segmentation erase effect performances by only processing the modified brush extent instead of the whole volume.
=> ENH: Improve segmentation erase effect performances

Libs/MRML/Core/vtkMRMLPETProceduralColorNode.cxx, Libs/MRML/Core/vtkMRMLPETProceduralColorNode.h
See discussion at:
https://discourse.slicer.org/t/custom-color-maps-disappearing-on-mac-big-sur/16904/5
=> ENH: Added new color nodes for PET image display: PET-Rainbow2, PET-DICOM, and PET-HotMetalBlue

Modules/Loadable/Markups/Testing/Cxx/vtkSlicerMarkupsLogicTest4.cxx
Error was:
"c:\d\S4R\Slicer-build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\d\S4R\Slicer-build\Modules\Loadable\Markups\Testing\Cxx\qSlicerMarkupsModuleCxxTests.vcxproj" (default target) (520) ->
(ClCompile target) ->
C:\d\Slicer\Modules\Loadable\Markups\Testing\Cxx\vtkSlicerMarkupsLogicTest4.cxx(124,98): error C2666: 'operator !=': 5 overloads have similar conversions [C:
\d\S4R\Slicer-build\Modules\Loadable\Markups\Testing\Cxx\qSlicerMarkupsModuleCxxTests.vcxproj]
C:\d\Slicer\Modules\Loadable\Markups\Testing\Cxx\vtkSlicerMarkupsLogicTest4.cxx(129,96): error C2666: 'operator !=': 5 overloads have similar conversions [C:
\d\S4R\Slicer-build\Modules\Loadable\Markups\Testing\Cxx\qSlicerMarkupsModuleCxxTests.vcxproj]
C:\d\Slicer\Modules\Loadable\Markups\Testing\Cxx\vtkSlicerMarkupsLogicT …
=> COMP: Fix Windows build error in vtkSlicerMarkupsLogicTest4

Base/Logic/vtkImageRectangularSource.cxx, Libs/vtkSegmentationCore/vtkOrientedImageDataResample.h
Adding `<cmath>` header.
In:
- vtkImageRectangularSource.cxx
- vtkOrientedImageDataResample.h
=> BUG: Fix 'fabs' was not declared

Applications/SlicerApp/Testing/Python/FiducialLayoutSwitchBug1914.py, Applications/SlicerApp/Testing/Python/RSNAQuantTutorial.py, Applications/SlicerApp/Testing/Python/RSNAVisTutorial.py, Base/Python/slicer/ScriptedLoadableModule.py, Extensions/Testing/ScriptedLoadableExtensionTemplate/ScriptedLoadableModuleTemplate/ScriptedLoadableModuleTemplate.py, Modules/Loadable/Markups/Testing/Python/MarkupsInCompareViewersSelfTest.py, Modules/Loadable/Markups/Testing/Python/MarkupsInViewsSelfTest.py, Modules/Loadable/Markups/Testing/Python/NeurosurgicalPlanningTutorialMarkupsSelfTest.py, Modules/Loadable/Markups/Testing/Python/PluggableMarkupsSelfTest.py, Modules/Loadable/SceneViews/Testing/Python/AddStorableDataAfterSceneViewTest.py, Modules/Loadable/VolumeRendering/Testing/Python/VolumeRenderingSceneClose.py, SuperBuild.cmake
As I found out in https://github.com/Slicer/Slicer/pull/5582#issuecomment-818070072 there are some methods in ScriptedLoadableModuleLogic class that is intended for testing purposes only. Therefore the work (originally mentioned in https://github.com/Slicer/Slicer/pull/5582#issuecomment-818758575) in this PR moves these methods to the ScriptedLoadableModuleTest class and update a few tests that were using the testing methods from the logic class. 
Part of this is enforcing the removal of some deprecated methods in the ScriptedLoadableModuleLogic class. `delayDisplay` usage in ScriptedLoadableModuleLogic has been deprecated since Dec 10th 2014 and `clickAndDrag` usage since Dec 6th 2016.
=> ENH: Move testing methods in scripted logic class to test class

Base/QTGUI/Testing/Cxx/qSlicerMouseModeToolBarTest1.cxx, Modules/Loadable/Markups/Widgets/Resources/UI/qSlicerMarkupsPlaceWidget.ui, Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx
This closes #5608.
MarkupsMouse... became "MarkupsFiducialMouse... for naming consistency in 6082a9bf488431ab0d14748c577f82c1dcf29e17
```python
widget = slicer.qSlicerMarkupsPlaceWidget()
widget.show()
```
|![image](https://user-images.githubusercontent.com/15837524/115563728-d7372e80-a285-11eb-83b6-a9f56903d437.png) |![image](https://user-images.githubusercontent.com/15837524/115587830-1a9c9780-a29c-11eb-9b21-117720bc4622.png)|
=> BUG: Fix missing markups place button icon

Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.h
Fixes for @lassoan 's comments in https://github.com/Slicer/Slicer/pull/5594 that I forgot to push. Sorry for the mixup.
=> STYLE: Improve naming and order of markup terminology view menu

Applications/SlicerApp/Testing/Python/FiducialLayoutSwitchBug1914.py
This fixes failing test `py_FiducialLayoutSwitchBug1914` as observed on the CDash for all platforms. As part of this I simplified the widget class down as you can the reload and test to rerun things. Those specific widgets weren't needed and is now based on some other tests that specifies a widget class that just use the base class ScriptedLoadableModuleWidget.
Failing test:
https://slicer.cdash.org/test/17315997
Introduced by changes made in 71f236bfacffec1d6c01036840dfc8d89be0563c.
=> BUG: Fix failing FiducialLayoutSwitchBug1914 test case

Utilities/Scripts/qrcc.py
This commit replaces usage of base64.encodestring for base64.encodebytes
that was deprecated in python 3.1 and removed in 3.9.
See https://bugs.python.org/issue39351
=> BUG: Fix use of qrcc when building against Python3.9

Modules/Loadable/Markups/Widgets/Testing/Cxx/CMakeLists.txt
This commit fixes a regression introduced in 0242927e3 (ENH: Add unit tests
for markups factory)
This pull request fixes the following error:
```
CMake Error at CMake/SlicerMacroSimpleTest.cmake:61 (message):
error: Target 'qSlicerMarkupsModuleWidgetsCxxTests' is not defined !
Modules/Loadable/Markups/Widgets/Testing/Cxx/CMakeLists.txt:46 (simple_test)
```
=> COMP: Fix configruation of qSlicerSimpleMarkupsWidgetTest1 with QtTesting OFF

SuperBuild/External_CTK.cmake
A recent change in CTK converted four hard-coded multi-instance display fields (i.e. they concern more than a single instance such as series/study/patient), and fixed the last study date role, which sometimes failed to calculate the date on newly added datasets.
=> ENH: Update CTK to include multi-instance DICOM display roles

SuperBuild.cmake
This closes #5626.
No build issues. Tests were run locally and the tests that failed were the same as the ones already failing prior to these changes.
```
1>Total Test time (real) = 2212.64 sec
1>
1>The following tests FAILED:
1>	332 - vtkMRMLAnnotationLinesNodeTest1 (Failed)
1>	334 - vtkMRMLAnnotationLinesStorageNodeTest1 (Failed)
1>Errors while running CTest
```
```
MultiVolumeExplorer:
$ git shortlog --topo-order --no-merges 5e69562..36102fd
STYLE: Upgrade python syntax to 3.6 and newer (# 50)
MultiVolumeImporter:
$ git shortlog --topo-order --no-merges dbae430..db80594
STYLE: Upgrade python syntax to 3.6 and newer
SlicerSimpleFilters:
$ git shortlog --topo-order --no-merges 8686bf5..92e8db0
Improve progress reporting
James Butler …
```
=> COMP: Update remote modules

Modules/Loadable/Data/Resources/UI/qSlicerDataModuleWidget.ui, Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyGenericSelfTest.py, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel_p.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
1. Introduce None item in subject hierarchy
- If enabled, an "extra item" (similarly to the same concept in qMRMLNodeComboBox) is added as the top item under the scene. This item has the name defined in the noneItemText property, and is selectable but no drag&drop is enabled. When selecting it, the current item will have the ID 0 (= INVALID_ITEM_ID)
- This enables having empty selections in comboboxes after having made a valid selection
2. Add flag in subject hierarchy combobox for showing parents in title
- Sometimes it is undesired to see the name of each parent after selecting an item in the combobox (it looks like "[ParentName] / [ParentName] / [SelectedItemName]"). If disabled, only the name of the selected item is shown ("[SelectedItemName]")
- On by default not to change the …
=> Sh combobox improvements

Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx
The commit 5ae5564362b40e43730a289e1fa0531feee8ca73 on 2020.03.17 changed all the terminology category codes in the default terminology contexts. As a result, if a scene saved before this date containing terminology information is loaded in a version newer than that, lots of errors are reported about the category not found in the specified terminology category.
The errors logged are pairs of entries looking like this:
"GetCategoryInTerminology: Failed to find category 'Anatomical Structure' in terminology 'Segmentation category and type - 3D Slicer General Anatomy list'
DeserializeTerminologyEntry: Failed to get terminology category"
=> BUG: Prevent flood of terminology errors in the log if using an older scene

Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIDisplayNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h, Modules/Loadable/Markups/Testing/Cxx/CMakeLists.txt, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest4.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest5.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIWidget.cxx, Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx, Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
- Renamed "ROI"/"Plane" space to "Object".
- Renamed "Local" space to "Node".
- Improved handling of ROI ObjectToWorld matrix.
- ObjectToWorld is a matrix generated from ObjectToNode and NodeToWorld transforms that will always represent the transform from the axis-aligned "Object" space, to world space, ensuring that the ROI axes remain orthogonal.
- Moved scale handle indices from vtkMRMLMarkupsROINode to vtkMRMLMarkupsROIDisplayNode.
- Add DLL export to interaction handle pipelines so that they can be inherited by subclasses in other extensions.
- Add vtkMRMLMarkupsROINode::IsPointInROI() and IsPointInROIWorld() functions.
- Added vtkMRMLMarkupsNodeTest5 to test ROI functions, applying transforms, and transform hardening.
=> ENH: Improve handling of internal transforms for ROI and plane markups

Docs/developer_guide/build_instructions/linux.md
Make sure that the package lists are updated before installing to avoid
errors on fresh installs (e.g. a fresh VM on a gcp's Ubuntu image
will not have updated packages by default).
=> DOC: add an apt update step to linux build lines

Libs/MRML/Core/vtkMRMLMeasurement.cxx, Libs/MRML/Core/vtkMRMLMeasurement.h
Errors like this occurred when compiling vtkMRMLMeasurement on Windows (using VTK8):
C:\d\Slicer\Libs\MRML\Core\vtkMRMLMeasurement.h(158,3): error C2666: 'vtkOStreamWrapper::operator <<': 5 overloads have similar conversions [C:\d\S4D\Slicer-build\Libs\MRML\Core\MRMLCore.vcxproj] [C:\d\S4D\Slicer.vcxproj]
They were due to using vtkGetObjectMacro for vtkSmartPointer objects.
=> COMP: Fix build error on Windows

Docs/developer_guide/build_instructions/windows.md
Just like it was asked [here](https://discourse.slicer.org/t/building-slicer-from-source/17823/2). 
I made a pull request to set up the lines I used to build Slicer and correct the old cmake line that appears on the developer build tutorial for Windows.
I didn't test all the modules after executing the compiled Slicer, just that the sliceViews and the 3D view worked. I did't build debug version, only release
=> COMP: correct CMake parameters (generator name, code folder)

pre-commit
Expands the regex so that files with multiple extensions can still match the regex if the tail of the string contains an excluded extension, instead of requiring a complete match.
=> ENH: Allow multiple extensions to be excluded from line length check

SuperBuild/External_ITK.cmake
Hi, I'm working on a [ANTs extension](https://github.com/simonoxen/SlicerANTs) and adding these modules to ITK build allows me to build ANTs against Slicer's ITK. They are used in [ANTs ITK Super Build](https://github.com/ANTsX/ANTs/blob/master/SuperBuild/External_ITKv5.cmake).
Would it be possible to include?
=> COMP: use ITK to build ANTs

Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx, Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.h
It is quite frequently needed and not easy for users to find how to create closed surface representation for a segmentation node.
This commit adds "create" and "remove" actions for "closed surface" and "binary labelmap" representations.
Only the non-master representation is offered to be created or deleted, therefore typically only one action appears in the menu.
For example, if binary labelmap is the master representation then either "Create closed surface representation"
or "Remove closed surface representation" action is shown.
=> ENH: Add create/remove representation options to segmentations subject hierarchy menu

Modules/Loadable/Markups/VTKWidgets/CMakeLists.txt, Modules/Loadable/Markups/VTKWidgets/vtkFastSelectVisiblePoints.cxx, Modules/Loadable/Markups/VTKWidgets/vtkFastSelectVisiblePoints.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h
This PR contains 2 improvements to the performance of rendering markups fiducials and visibility detection of control points.
- Improve 3D markups fiducial performance with vtkGlyph3DMapper
- vtkGlyph3D has a higher overhead when used for a large number of points, since it duplicates the glyph polydata once for each point, and then uploads the duplicated polydata to the mapper.
- vtkGlyph3DMapper has a higher performance as it uploads the glyph once, and renders the same polydata multiple times on the GPU.
- Improve performance of markups visibility detection 
- Previously, each ControlPointsPipeline3D had its own vtkSelectVisiblePoints filter to determine if the markups were occluded by opaque geometry in the render window. The filters would all download the ZBuffer data separately, …
=> ENH: Improve markups rendering performance

Base/QTCLI/qSlicerCLIProgressBar.cxx, Docs/developer_guide/python_faq.md, Docs/developer_guide/script_repository/subjecthierarchy.md, Libs/MRML/Core/vtkMRMLInteractionNode.cxx, Libs/MRML/Core/vtkMRMLInteractionNode.h, Libs/MRML/DisplayableManager/vtkMRMLCameraDisplayableManager.cxx, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.h, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/Testing/Python/AddManyMarkupsFiducialTest.py, Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyCorePluginsSelfTest.py, Modules/Loadable/SubjectHierarchy/Widgets/CMakeLists.txt, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyCloneNodePlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyFolderPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyModuleWidgetsPythonQtDecorators.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.h, Modules/Scripted/DICOMLib/SubjectHierarchyPlugins/qSlicerSubjectHierarchyDICOMPlugin.cxx
Currently, the only actions in the view context menu (when clicking on empty area) then only interaction mode can be changed.
More actions can be added later.
Let me know if there are other actions that you would like to see in this menu.
=> ENH: Add context menu when right-clicking in slice or 3D view

CMakeLists.txt
`Qt5X11Extras` is a Qt componnent required to build the Superbuild `VTK` in
the current configuration, however, this component is not required when
configuring Slicer. In abscence of installed `Qt5X11Extras` the build will
fail on `VTK`.
his commit adds Qt5X11Extras as a required component for Linux systems
and closes Slicer/Slicer#5695
=> COMP: Check for Qt5X11Extras on Linux

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/MRML/CMakeLists.txt, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneJsonStorageNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneJsonStorageNode_Private.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementArea.cxx, Modules/Loadable/Markups/Resources/Schema/markups-schema-v1.0.2.json, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx
Adds missing attributes to markups plane node XML Read/Write/Copy/Print, as well as the new vtkMRMLMarkupsPlaneJsonStorageNode class that can save additional plane data in the json file.
PlaneBounds (renamed to Size), and AutoSizeScalingFactor attributes in vtkMRMLMarkupsPlaneNode were not included in WriteXML/ReadXMLAttributes/CopyContent/PrintSelf functions. This commit adds the relevant attributes to the functions.
=> ENH: Add additional saved parameters to vtkMRMLMarkupsPlaneNode

Libs/MRML/Core/vtkMRMLScalarVolumeNode.cxx, Libs/MRML/Core/vtkMRMLScalarVolumeNode.h, Libs/MRML/Core/vtkMRMLSequenceNode.cxx, Libs/MRML/Core/vtkMRMLStorableNode.cxx, Libs/MRML/Core/vtkMRMLStorableNode.h, Libs/MRML/Core/vtkMRMLTransformNode.cxx, Libs/MRML/Core/vtkMRMLTransformNode.h
Currently, it is not possible in a module to add a default SequenceStorageNode for a data node class in the Slicer core.
This commit adds an interface so that Extensions can now add default sequence storage node classes for specific data types by registering the data node/storage node in the default sequence node.
Example of use:
````
defaultSequenceNode = slicer.mrmlScene.CreateNodeByClass("vtkMRMLSequenceNode")
defaultSequenceNode.RegisterAdditionalStorageNode("vtkMRMLStreamingVolumeNode", "vtkMRMLStreamingVolumeSequenceStorageNode")
slicer.mrmlScene.AddDefaultNode(defaultSequenceNode)
defaultSequenceNode.UnRegister(None)
````
=> ENH: Add interface to register default sequence storage nodes

Libs/MRML/DisplayableManager/vtkMRMLScriptedDisplayableManager.cxx
vtkMRMLScriptedDisplayableManager::SetPythonSource evaluates
a python code string to load a the source file.
The code used execfile, which worked in python2 but does not
exist in python3.
This changes the code to use exec, open, and read in order
to emulate the execfile behavior.
=> BUG: use exec not execfile for scripted MRMLDM

Base/QTGUI/Resources/UI/qSlicerSaveDataDialog.ui, Base/QTGUI/qSlicerFileDialog.cxx, Modules/Scripted/LabelStatistics/LabelStatistics.py, SuperBuild/External_CTK.cmake
This aims to improve directory selection by using the native dialog instead of Qt's own widget-based dialog design.
See 3D Slicer forum discussion of how users have been doing other methods to avoid using widgets that use Qt's widget-based dialog.
https://discourse.slicer.org/t/using-native-file-dialog-for-selecting-files-and-folders/17926
| Qt widget-based dialog | Native dialog (on Windows)|
|-------------------------|--------------------------------|
|![image](https://user-images.githubusercontent.com/15837524/120825251-3051dd80-c527-11eb-83a4-1a0c2c03971c.png)|![image](https://user-images.githubusercontent.com/15837524/120825677-9e96a000-c527-11eb-8200-2c2a4cecc8ae.png)|
This PR currently contains changes to update the main Slicer Load dialog to choose directories and files using a …
=> ENH: Improve directory and file selection by using native dialogs

Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.cxx, Libs/MRML/Widgets/Resources/UI/qMRMLVolumeThresholdWidget.ui, Libs/MRML/Widgets/Resources/UI/qMRMLWindowLevelWidget.ui, Libs/MRML/Widgets/Testing/qMRMLVolumeThresholdWidgetEventTranslatorPlayerTest1.xml, Libs/MRML/Widgets/Testing/qMRMLWindowLevelWidgetEventTranslatorPlayerTest1.xml, Libs/MRML/Widgets/qMRMLVolumeThresholdWidget.cxx, Libs/MRML/Widgets/qMRMLVolumeThresholdWidget.h, Libs/MRML/Widgets/qMRMLVolumeWidget.cxx, Libs/MRML/Widgets/qMRMLVolumeWidget_p.h, Libs/MRML/Widgets/qMRMLWindowLevelWidget.cxx, Libs/MRML/Widgets/qMRMLWindowLevelWidget.h
This PR aims to improve range bounds behavior for widgets that use qMRMLVolumeWidget including the Window Level and Threshold widgets. See https://discourse.slicer.org/t/improving-qmrmlvolumewidget-range-bounds/17821 for full discussion about this work.
I have added a "..." toolbutton next to the sliders in the window/level and threshold UI files that is similar in nature to what is used in the Slicer qMRMLRangeWidget. 
Shown in the image below is what things look like now. Pressing the "..." toolbutton will show/hide the popup widget contain widgets for setting the bounds of the main slider widget. The previous hover action that would trigger the popup widget was very frustrating to users as in most cases they were looking to change bounds. This toolbutton now makes changing bounds a …
=> Improving qMRMLVolumeWidget range bounds functionality

Docs/developer_guide/script_repository/subjecthierarchy.md
Methods were renamed as part of recent work in 598dea0b5f2acadffde161111bc071eff0dc8b25.
`setDisplayedViewMenuActionNames` and `availableViewMenuActionNames` were originally added as part of 62fe31fb179e5c904f5d8157739483dee6669a44 which was included in Slicer v4.11.20200930 and v4.11.20210226.
=> DOC: Update plugin logic example based on recent renames

Libs/MRML/Widgets/qMRMLVolumeThresholdWidget.h, Libs/MRML/Widgets/qMRMLWindowLevelWidget.cxx
`BUG: Fix Window Level mode not reflecting ManualMinMax set state` closes #5651.
```python
nodeToClone = SampleData.SampleDataLogic().downloadMRHead()
widget = slicer.qMRMLWindowLevelWidget()
widget.setMRMLVolumeNode(nodeToClone)
widget.setAutoWindowLevel(slicer.qMRMLWindowLevelWidget.ManualMinMax)
widget.show()
```
I've also added a second commit that exposes the similar control mode type enums, but for the Volume Threshold widget. This allows for setting the auto threshold using the control mode enum.
```python
nodeToClone = SampleData.SampleDataLogic().downloadMRHead()
widget = slicer.qMRMLVolumeThresholdWidget()
widget.setMRMLVolumeNode(nodeToClone)
widget.setAutoThreshold(slicer.qMRMLVolumeThresholdWidget.Manual)
widget.show()
```
=> WindowLevel widget mode fixes and Threshold mode improvements

SuperBuild/External_CTK.cmake
This commit updates PythonQt to add support for `isatty` to `PythonQtStdInRedirect`.
```
$ git shortlog 9f128617..e485a3fc --no-merges
BUG: Update PythonQt to fix installation of light-the-torch in Slicer
```
Fixes #5705
Co-authored-by: Fernando Perez-Garcia <fernando.perezgarcia.17@ucl.ac.uk>
=> BUG: Update CTK and PythonQt to fix installation of light-the-torch

SuperBuild/External_VTK.cmake
VTK modules can be built in the following scenarios:
1. Module sources and generated buildsystem are respectively in VTK source and build trees (aka built-in case)
2. Module sources are external and module generated buildsystem is in VTK build tree (aka built-in case for a VTK remote module)
3. Module sources and module generated buildsystem are both external
4. Module sources are in VTK source tree and module generated buildsystem is external
This commit updates VTK to include logic ensuring files are not generated
in VTK source for case (3) and (4).
```
$ git shortlog f3c1a72fbf..fe57670c3e --no-merges
[Backport MR-8123] Do not generate files in source tree when building module externally
```
=> COMP: Update VTK to improve support for extension bundling VTK modules

SuperBuild/External_VTK.cmake
This commit is a follow up of 5270e2f32 (COMP: Update VTK to improve support for extension
bundling VTK modules), it updates VTK to include changes contributed while reviewed VTK MR-8123
```
$ git shortlog fe57670c3e..a0125fe2b0 --no-merges
[Backport MR-8123] vtk_module_build: Update CMake function fixing use of quotes and indentation
[Backport MR-8123] vtk_module_build: Ensure external modules build directory are not overwritten
```
=> COMP: Update VTK

Docs/developer_guide/modules/segmenteditor.md, Docs/user_guide/modules/segmenteditor.md, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorSmoothingEffect.py
Added a new checkbox and logic that enables serial smoothing of all visible segments currently open in the Segment Editor. If no segments are visible there is a logging message. The last selected segment gets restored.
The progress is shown as a statusmessage.
=> ENH: "Apply to all segments" checkbox added in Segment Editor "Smoothing" effect

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyDefaultPlugin.cxx, Modules/Scripted/DICOMLib/SubjectHierarchyPlugins/qSlicerSubjectHierarchyDICOMPlugin.cxx
Update content of SH help pupup to reflect changes in the application. Fix style where inconsistent.
Before:
After:
=> DOC: Fix popup help content for Subject Hierarchy usage in Data module

Libs/MRML/DisplayableManager/vtkMRMLAbstractWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLAbstractWidget.h, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLInteractionEventData.cxx, Libs/MRML/DisplayableManager/vtkMRMLInteractionEventData.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceViewInteractorStyle.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceViewInteractorStyle.h, Libs/MRML/DisplayableManager/vtkMRMLThreeDViewInteractorStyle.cxx, Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.h, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
For a long time, markup control points were placed on mouse button press. A week ago we changed the implementation to place a point on click (no mouse move between button press and release), which several users did not like because it required the users to pause while placing points (instead of keep placing points while moving the mouse). See more details here: https://discourse.slicer.org/t/feedback-requested-requirements-to-place-a-fiducial/18407
The only difference is that now point position is finalized on button release (instead of button press) to be consistent with drawing behavior of other software (Microsoft Office, Inkscape, Gimp, etc.).
fixes #5713
=> BUG: Revert to previous markups placement behavior

Docs/developer_guide/modules/segmenteditor.md, Docs/user_guide/modules/segmenteditor.md, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorHollowEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorMarginEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorSmoothingEffect.py, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx
Added new checkboxes and logic that enables serial hollowing as well as growing and shrinking (Margin) of all visible segments currently open in the Segment Editor. If no segments are visible there is a logging message. The last segment selection gets restored.
The progress is shown as a status message.
User Documentation Hollow not yet found. 
This pull request contains 5 changed files, but only two are needed (SegmentEditorHollowEffect and SegmentEditorMarginEffect). Sorry for this
=> ENH: "Apply to all segments" checkboxes added in Segment Editor "Hollow" and "Margin" effect

Modules/Loadable/Segmentations/EditorEffects/Python/AbstractScriptedSegmentEditorAutoCompleteEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorFillBetweenSlicesEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorGrowFromSeedsEffect.py
On a large (400x400x1500) volume with 20 seed segments, Grow from seeds completed in about 50 second, but segment updates added about 30 seconds. There also seemed to be multiple updates for a single user action.
To avoid multiple updates, added previewComputationInProgress flag.
To reduce update time, preview segmentation is filled using ImportLabelmapToSegmentationNode method.
With the changes, initial update takes about 55 seconds, subsequent updates take about 11 seconds.
Remaining problems:
- It would be better to avoid temporary labelmap creation (if we keep this, then before importing we probably need to set the segmentation's parent transform to the labelmap).
- Final update is still slow.
=> BUG: Improve performance of Grow from seeds Segment Editor effect

Docs/developer_guide/script_repository/plots.md, Libs/MRML/Widgets/Resources/UI/qMRMLPlotViewControllerWidget.ui, Libs/MRML/Widgets/qMRMLPlotView.cxx, Libs/MRML/Widgets/qMRMLPlotView.h, Libs/MRML/Widgets/qMRMLPlotViewControllerWidget.cxx, Libs/MRML/Widgets/qMRMLPlotViewControllerWidget.h
Filename was not computed correctly.
Use "Export" instead of "Save" because it is a lossy operation (we do not save the plot, just the appearance).
=> BUG: Fix plot export to svg

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
When the parent transform node reference for the curve node was changed, the transform from the surface model to the curve was not updated. Fixed by updating the transform when the parent transform node reference is changed.
Re #5661
=> BUG: Fix markups curve constrain if parent transform node is changed

Libs/vtkITK/itkLevelTracingImageFilter.txx, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorLevelTracingEffect.py
LevelTracing is implemented in 2D and should work on the first and last slicer; however, there is a check that doesn't allow this for when only one slice is available (drag and drop of one dicom file)
For context see: https://discourse.slicer.org/t/level-tracing-on-a-single-slice-from-a-3d-volume/16693/4
=> BUG: Fix the check for 3D while tool logic is 2D in levelTracing tool

Docs/developer_guide/script_repository/subjecthierarchy.md, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx
List of allowed view context menu actions was reset whenever the menu was rebuilt.
Fixed by introducing a string list that stores the allowed action names.
https://discourse.slicer.org/t/customization-of-right-click-context-menu-is-being-reset-to-default-unexpectedly/18603/7
=> BUG: Fix customization of view context menu

Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication.h, Base/QTCore/qSlicerSceneBundleReader.cxx, Base/QTGUI/qSlicerApplication.cxx, Base/QTGUI/qSlicerApplication.h, Base/QTGUI/qSlicerIOManager.cxx, Base/QTGUI/qSlicerIOManager.h
When "Open with..." function was used on macOS (or the filename was specified as a command-line argument), then the application did not report any loading errors.
=> BUG: Show error popup if loading via command-line has failed

SuperBuild/External_CTK.cmake
This is part of #5739 work. It is unclear if this will completely resolve the issue or only some of the issue. Choosing a file to import into the DICOM database, even when using Windows, should not crash anymore upon selecting "import" which closes the native file dialog.
```
$ git shortlog --no-merges e485a3f..a964dcc
BUG: Fix crash upon selecting files with DICOM browser import dialog
```
=> COMP: Update CTK

Libs/MRML/Widgets/qMRMLVolumeThresholdWidget.cxx, Libs/MRML/Widgets/qMRMLVolumeThresholdWidget.h, Libs/MRML/Widgets/qMRMLVolumeWidget.cxx, Libs/MRML/Widgets/qMRMLVolumeWidget_p.h, Libs/MRML/Widgets/qMRMLWindowLevelWidget.cxx, Libs/MRML/Widgets/qMRMLWindowLevelWidget.h, Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.cxx
If you select a volume in the Volumes module and the volume's current Window/Level was outside of the bounds, then using the qMRMLWindowLevelWidget would change the current window level to the special Window/Level range bounds. 
Current Slicer `master`
```python
volumeNode = SampleData.SampleDataLogic().downloadMRHead()
volumeNode.GetDisplayNode().AutoWindowLevelOff()
volumeNode.GetDisplayNode().SetWindowLevelMinMax(-2000,2000)
print(volumeNode.GetDisplayNode().GetWindowLevelMin())  # -2000
print(volumeNode.GetDisplayNode().GetWindowLevelMax())  # 2000
slicer.util.selectModule("Volumes")  # triggers setting a volume to the qMRMLWindowLevelWidget
print(volumeNode.GetDisplayNode().GetWindowLevelMin())  # -600
print(volumeNode.GetDisplayNode().GetWindowLevelMax())  # 600 …
```
=> BUG: Fix Window Level widget setting bounds inside current values

Libs/MRML/Core/vtkMRMLFolderDisplayNode.cxx, Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
Problem is that on scene close in certain cases, when the new SH node is created, the Markups displayable manager requests render on the node added event of the SH node, then there is an endless loop in the Folder plugin's GetHierarchyVisibility because SH item parent is 0 (i.e. invalid ID) and never reaches the scene.
=> BUG: Fix hang when closing scene

Docs/user_guide/data_loading_and_saving.md
I just noticed this and figured I would go ahead and submit a change.
I removed a link that was linking to the Slicer Wiki DICOM module page (https://www.slicer.org/wiki/Documentation/Nightly/Modules/DICOM) since that page is now telling users to go to the DICOM module ReadTheDocs page (https://slicer.readthedocs.io/en/latest/user_guide/modules/dicom.html) and that is already linked to users in a sentence a few lines down.
=> DOC: Remove duplicate linking to DICOM module documentation

Docs/user_guide/user_interface.md, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.h
Problem:  
Rotating 3D models in 3D view with the mouse may cause tumbling effects and often leads to the impression of inaccuracy. Apart from this, permanent corrections are exhausting. 
Solution:  
Pressing the "a" on the keyboard now toggles between "limited rotation mode" (Azimuth only) and "full rotation mode" (all axes). The result is a smooth and reproducible rotation "on demand".  
Keys:  
"a" -> toggle 3D stabilizer
To do:
Indication to the user that stabilizer is active ? pls suggest where
If accepted-> documentation
=> ENH: Implementation of a 3D stablizer in 3D view

Libs/MRML/Widgets/qMRMLVolumeThresholdWidget.cxx, Libs/MRML/Widgets/qMRMLVolumeThresholdWidget.h, Libs/MRML/Widgets/qMRMLWindowLevelWidget.cxx, Libs/MRML/Widgets/qMRMLWindowLevelWidget.h
This is a small change to add some public methods for convenience to manipulate the bounds of Volume Threshold and WindowLevel widgets through code rather than just through the GUI.
=> ENH: Add public method to change threshold and WindowLevel bounds

Base/QTGUI/qSlicerSaveDataDialog.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
Filenames starting or ending with spaces may be hard to manage. Therefore, we remove leading and trailing whitespace characters when generating filename from node name (in Save data dialog and in segmentation export).
fixes #4523
=> ENH: Trim whitespaces from node names when generating filenames from them

Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx
When loading a segmentation from a regular nrrd (rather than seg.nrrd), the reference image geometry of the original image was not saved.
Due to the missing geometry conversion parameter, exporting/saving the segmentation would cause the segmentation to be exported/saved at minimum extent. Fixed by setting the reference image geometry conversion parameter to the size of the imported nrrd.
Re #5323
=> BUG: Save segmentation imported from plain nrrd using original geometry

Libs/MRML/Widgets/qMRMLVolumeWidget.h, Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.h
I found exposing to the python interface getting the volume node of some volume widgets helpful. Some other widgets have it exposed from the python interface using calls such as `currentNode()` and now that is possible with these widgets using their already named methods of `mrmlVolumeNode()` and `volumeNode()`. 
It would be nice if getting the node for the associated qMRML/qSlicer widgets had a more consistent naming scheme, but I'll leave that for a more comprehensive future change.
=> ENH: Get node from volume display widgets using Python interface

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
Previously, interaction handles (translate/rotate/scale) did not take right-click events and so the view context menu was shown, so it was hard to turn off interaction handles.
re #5734
=> ENH: Show context menu if clicking on markups interaction handle

Modules/Loadable/Segmentations/EditorEffects/Python/AbstractScriptedSegmentEditorAutoCompleteEffect.py
Due to a previous optimization that set the labelmap representation of the preview segments directly, the 3D preview closed surface was no longer automatically updating. To fix this, we remove the existing closed surface so that it will be reconverted after the segmentation is updated.
When the functions for setting multiple segments are added, we will no longer need this call as the closed surface update will be handled by the segmentation logic.
Re #5757
=> BUG: Force update of grow from seeds 3D closed surface preview

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx
When modifying a segment the list of segments that need to be overwritten does not normally include segments that are on the same layer (since they will be overwritten by default). This list was populated before the selected segment is modified. This causes segments on the same layer to not be overwritten if the selected segment is separated to a new layer.
Fixed by populating the list of segments to overwrite after the selected segment has been modified (and potentially moved to a new layer).
Re #5338
=> BUG: Fix invalid overlap when splitting segments

Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h
The useful FitSliceToAll function in ApplicationLogic may change the slice view orientation. User may want to keep the current orientation and simply adjust the FOV.
=> ENH: Allow FOV adjustment without slice view reorientation

Libs/MRML/Widgets/qMRMLCheckableNodeComboBox.cxx, Libs/MRML/Widgets/qMRMLPlotViewControllerWidget.cxx, Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx, Modules/Scripted/DICOMLib/DICOMUtils.py
The code to delete the database was commented out several years ago (before the large DICOM database refactoring). The temporary database files can now be deleted properly.
=> BUG: Remove temporary database files when the database is closed

Modules/Loadable/Data/qSlicerSceneReader.cxx
This commit fixes a regression introduced in 4c8b2803f (ENH: Report more
scene loading errors)
Co-authored-by: Rafael Palomar <rafael.palomar@rr-research.no>
=> COMP: Update qSlicerSceneReader to fix compilation using Qt < 5.14

SuperBuild/External_SimpleITK.cmake
This updates SimpleITK to a tagged release. Should be tested across the platforms to confirm none of these final updates from the pre-release version to the tagged release cause issues.
```
$ git shortlog --topo-order --no-merges 1062acf..v2.1.0
Bradley Lowekamp (25):
Use https://simpleitk.org
CircleCI fix typo in anchor name
Wrap the ComposeScaleSkewVersor3DTransform
Document ComposeScaleSkewVersorTransform in Sphinx overviews
Add ComposeScaleSkewVersor3DTransform header to wrapping interface
Add another baseline image for the SLICImageFilter "default" case
Release tolerance for SLICImageFilter.default measurement
Add alternative baseline for ImageRegistrationMethodDisplacement1
Add Image GetBufferAsNativePointer and GetBufferAsBuffer methods
Ignore constant Image::GetBufferAs.. methods …
```
=> COMP: Update SimpleITK to v2.1.0

Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.cxx, Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.h, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.h, Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx, Libs/vtkSegmentationCore/vtkSegmentation.cxx, Libs/vtkSegmentationCore/vtkSegmentation.h
VTK interactors have a number of keyboard shortcuts for various low-level operations, such as change rendering style of all actors to wireframe or change rendering mode to stereo.
These interfere with rendering settings set by displayable managers, therefore it is better to disable them.
The only useful keyboard shortcut ('r' key for camera reset) is now handled by the vtkCameraWidget.
fixes #5772
Also bundled an unrelated commit in the pull request, to add methods that return std::vector<std::string>. These string vectors are now wrapped in Python and they are much more convenient to use than vtkStringArray.
=> Disable default vtk keyboard shortcuts

Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.h
When exporting binary labelmaps to file, the color table was not being taken into account.
Fixed by adding an argument for labelmap values to vtkSlicerSegmentationsModuleLogic::GenerateMergedLabelmapForAllSegments().
Also added additional documentation to vtkSlicerSegmentationsModuleLogic.h.
=> BUG: Fix binary labelmap file export using color table

Base/QTGUI/qSlicerWebWidget.cxx, Base/QTGUI/qSlicerWebWidget.h, Base/QTGUI/qSlicerWebWidget_p.h
The purpose of this changes is to help identify issues within `qSlicerWebWidget` by inspecting the Slicer log file.
=> ENH: qSlicerWebWidget: Log javascript message if developer mode is enabled

Base/QTCore/qSlicerExtensionsManagerModel.cxx
This commit ensures the slicer revision is properly associated with
extension manager model by converting the server specific metadata key
"meta.app_revision" to the one used internally "slicer_revision".
It avoids false positive associated with the function
"qSlicerExtensionsManagerModelPrivate::isExtensionCompatible" and also avoids
message like "Incompatible with Slicer rNNNNN [built for r]" from being reported
Fixes #5786
=> BUG: Fix loading of extension installed using "Girder_v1" serverAPI

Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake
This ensures that the upload to Girder_v1 server will always happen.
=> COMP: Report Midas_v1 extension package upload failures as warnings

Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake
This commit generalizes to all metadata the change originally introduced
in 23e8fb730f (COMP: Fix upload of extension with semi-colon in description
metadata) and intended to fix a regression previously introduced in
8f33d93e8c (ENH: Ensure dependency metadata is published with extension
packages)
It fixes issue reported in https://github.com/KitwareMedical/slicer-extensions-webapp/issues/44
=> COMP: Fix Girder_v1 upload of extension with semi-colon in any metadata

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
Some methods in vtkMRMLMarkupsNode returned double* but did not contain a size hint. As a result the wrapped methods were not usable in python. Fixed by adding VTK_SIZEHINT to the following methods:
- GetNthControlPointPosition
- GetNthControlPointOrientationMatrix
- GetNthControlPointNormal
=> BUG: Fix wrapping for methods in vtkMRMLMarkupsNode

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx
The plane node interaction handle to world matrix was not updated when the transform was hardened.
Fixed by updating the matrix in vtkMRMLMarkupNode::OnTransformNodeReferenceChanged.
Also prevents the plane position from "flickering" by pausing modified events while vtkMRMLNode::ApplyTransform is being called.
Fix #5539
=> BUG: Update interaction handle orientation when transform is hardened

Base/QTGUI/qSlicerExtensionsManagerWidget.cxx
This commit ensures the search box text is properly reset when
using Girder_v1 server API integration.
In that case, the value associated with "q" query parameter should
be retrieved.
=> BUG: ExtensionsManager: Fix searchBox update after switching tab

Docs/developer_guide/build_instructions/linux.md, Docs/developer_guide/build_instructions/windows.md, Docs/developer_guide/debugging/codelitecpp.md, Docs/developer_guide/debugging/index.md, Docs/developer_guide/debugging/linuxcpp.md, Docs/developer_guide/debugging/macoscpp.md, Docs/developer_guide/debugging/overview.md, Docs/developer_guide/debugging/qtcreatorcpp.md, Docs/developer_guide/debugging/vscodecpp.md, Docs/developer_guide/debugging/windowscpp.md, Docs/developer_guide/index.md
Moved from Slicer wiki - https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/Debug_Instructions and related pages.
=> DOC: Add debug instructions

CMakeLists.txt
Official builds and tests are performed with Qt-5.15 on all platforms,
but since it is not easy to get latest Qt versions on Linux, the version
requirement is relaxed on Linux so that it builds on Ubuntu-20.04.
See https://github.com/Slicer/Slicer/issues/5804 for more details.
=> BUG: Relax Qt version requirements

Libs/vtkSegmentationCore/vtkSegmentationModifier.cxx, Libs/vtkSegmentationCore/vtkSegmentationModifier.h
If the modifier labelmap and resampled segmentation labelmaps do not overlap, then GetExtentIntersection will generate an invalid extent. Passing this extent to vtkImageThreshold::UpdateExtent will cause a crash.
Fixed by not applying the segment mask to the modifier if the extent is invalid. This should not cause any issues since if there is no overlap between the modifier/segment labelmaps, nothing should need to be erased.
Fix: #5812
=> BUG: Fix crash when erasing regions outside segmentation

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx
When "Erase all segments" was enabled, only the active segment was erased because minimumOfAllSegments was not enabled. In addition, labelmaps on other layers were not modified. Fixed by setting minimumOfAllSegments to True and marking all segment IDs to be overwritable when erasing all segments.
Fix #5584
=> BUG: Fix Erase effect "Erase all segments" options

Base/QTApp/qSlicerMainWindow.cxx
Originally discussed at today's hangout with @pieper @lassoan 
Note that this is somewhat related to #5820 which is also improving the defaults to value module panel vertical space more. That PR achieves more space given back to the module panel by moving the application logo to a new spot. That PR has quite the conversation going on as it relates to the logo so I wasn't going to add the changes in this PR there to avoid multiple conversations going on at once especially if this proposed change is as controversial.
Since the module panel is typically not a majority of the width dimension, this means the python interactor in the bottom widget area still has a wide aspect ratio. From my time using the python interactor I find that of typical screen size (1920x1080 at 100 to 125% scale) and …
=> ENH: Left/Right dock widgets given ownership to bottom corner areas

Libs/MRML/Widgets/qMRMLSceneModel.cxx
Weak pointer doesn't automatically resolve to pointer in Q_ASSERT.
See discussion here:
https://github.com/Slicer/Slicer/issues/5823
=> COMP: fix vtkWeakPointer in Q_ASSERT

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx
In Subject Hierarchy combobox when the user started a drag, a crash occurred. Since comboboxes are intended only for selection of items and not reorganizing them, and even if we want to drag&drop it is quite inconvenient and hard to control, it makes sense to simply disable the drag&drop feature.
=> BUG: Fix crash by disabling drag&drop in SH combobox

Modules/Scripted/DICOMLib/DICOMProcesses.py
Add self.indexer.waitForImportFinished() before calling os.remove() to make a DICOM retrieval followed by emptying the "incoming" directory more failsafe.  
There may be a possible interaction with self.indexer as a background process
=> ENH: Update DICOMListener with waitForImportFinished()

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx
The current region previously always added the current segment to the editable area if we were using one of the "EditAllowedInside*Segment*" masking modes.
This commit changes the behavior to only remove the current segment from the mask when:
1) The masking setting is set to inside a single segment
2) Modification mode is ModificationModeRemove
In this circumstance, we add the "Mask" segment to the current segment.
Re #5831
=> BUG: Ensure that masking settings are fully observed for most effects

CMake/SlicerExtensionCPack.cmake
This commit updates the heuristic checking if packaging should be skipped.
In case of extension bundled within another extension, checking if Slicer_DIR
is defined is not sufficient.
=> COMP: Skip packaging of extension bundled in other extension

CMakeLists.txt
Slicer Preview Releases are built with VTK9 and there are no major issues, therefore we update the default VTK version to 9.
=> ENH: Set default VTK version to 9

Modules/Scripted/DICOMPlugins/DICOMVolumeSequencePlugin.py
These modifications allow for the DICOM export of a 4D Volume Sequence
- Invalid syntax when parsing the time string 'tm' in function datetimeFromDicom
Change from 'string.split' to 'str.split'
- Added missing tags in export function for 'Patient Birth Date' and 'Patient Sex' required by the class DICOMExportScalarVolume
See issue: https://discourse.slicer.org/t/exporting-sequences-as-dicoms-does-not-work/18935
=> BUG: DICOMVolumeSequencePlugin.py  -Export Volume Sequences

Base/QTGUI/qSlicerExtensionsInstallWidget.cxx
This commit fixes the following error reported when building against Qt > 5.10
and introduced by 98af6f222d (ENH: ExtensionsManager: Ensure theme of
extension catalog webpage is updated):
```
Base/QTGUI/qSlicerExtensionsInstallWidget.cxx:161:39: error: invalid use of incomplete type ‘class QStyle’
```
=> COMP: Fix qSlicerExtensionsInstallWidget build error adding  missing include

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/Testing/Cxx/CMakeLists.txt, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest6.cxx
Previously the memory layout used to store for control point orientation in memory was: [x0, x1, x2, y0, y1, y2, z0, z1, z2], which was different from the implementation of vtkMatrix3x3. This commit changes the memory orientationto the one used in VTK: [x0, y0, z0, x1, y1, z1, x2, y2, z2].
The method vtkMRMLMarkupsNode::SetNthControlPointOrientationMatrixWorld previously did not actually set the orientation in world coordinates, it simply used the orientation matrix in world coordinates to directly update the OrientationMatrix. This commit transforms the orientation matrix from world to node coordinate system, and also adds a GetNthControlPointOrientationMatrixWorld function.
This commit also adds a test to check the orientation of each control point before and after applying linear and …
=> ENH: Improve handling of markups control point orientation

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
This commit fixes a warning originally introduced in ecc32d495 (ENH: Improve
handling of markups control point orientation).
```
/path/to/Slicer/Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx: In member function ‘double* vtkMRMLMarkupsNode::GetNthControlPointNormal(int, double*)’:
/path/to/Slicer/Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx:1252:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
```
=> COMP: Fix -Wreturn-type in vtkMRMLMarkupsNode::GetNthControlPointNormal

Base/QTApp/qSlicerApplicationHelper.cxx, Base/QTGUI/Resources/UI/qSlicerSettingsModulesPanel.ui, Base/QTGUI/qSlicerApplication.cxx, Base/QTGUI/qSlicerApplication.h, Base/QTGUI/qSlicerSettingsModulesPanel.cxx, Docs/user_guide/settings.md
Always prefer executable CLIs. While launching a process and transfer data via files may take slightly longer than passing a memory pointer and calling a DLL function, running CLI modules in separate process have several important advantages:
- the file transfer is more robust (the MRMLIDIO infrastructure was fragile and took a lot of effort to maintain)
- CLI modules can be stopped at any time (while a thread within the process may be requested to stop, there is no way to force it to stop cleanly)
- CLI module errors cannot crash the application
- application startup time and memory usage is slightly reduced by avoiding loading all CLI modules into the main process.
For now, CLI modules that only available as DLLs are still loaded, in the future this option will be removed completely. …
=> ENH: Always prefer executable CLIs

Modules/Scripted/Endoscopy/Endoscopy.py
The user can more easily adjust size and appearance (scaling, projection, occluded visibility, etc.) more flexibly than a model node.
In the module logic class, developers can choose between using a model or a markups fiducial.
=> ENH: Use markups fiducial point as cursor in Endoscopy module

Libs/MRML/Core/vtkMRMLDiffusionTensorVolumeDisplayNode.cxx, Libs/MRML/Core/vtkMRMLDiffusionTensorVolumeDisplayNode.h, Libs/MRML/Logic/vtkMRMLSliceLayerLogic.cxx
The color-by-orientation slice rendering mode
should take into account the measurement frame
of the tensor acquistion.
This information is stored in the
vtkMRMLDiffusionTensorVolumeNode
and needs to be copied to the
vtkMRMLDiffusionTensorVolumeNode.
=> ENH: use measurment frame to color dti slices

Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
If a user wants to edit custom corner annotation texts, having disabled the sliceViewAnnotationWidget of slicer, there is still an empty text that interfere with the user edition.
If sliceViewAnnotationWidget is turned off, we should remove observers and do not create other.
=> Slice annotation disabled

Modules/Loadable/Segmentations/Widgets/Resources/UI/qMRMLSegmentEditorWidget.ui, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
This moves the Undo and Redo buttons in the Segment Editor module to be under the effects groupbox. This is motivated by the desire for these buttons to not move when different segment editor effects are selected.
See https://discourse.slicer.org/t/new-segment-editor-layout-vertical-effect-toolbar/19649/9?u=jamesobutler for more details about this development.
|![image](https://user-images.githubusercontent.com/15837524/133895687-bbf355b0-63a4-4e8f-8139-4832499b87d5.png)|![image](https://user-images.githubusercontent.com/15837524/133895637-9b5d8e05-0de0-4f1d-9e9a-28bbd744d613.png)|
=> ENH: Undo Redo segment editor buttons stay in same position

SuperBuild/External_VTK.cmake
* [Backport 8371] Fix expansion of stl template args in wrapping
See #5752 (Improve markups rendering performance)
Co-authored-by: Connor Bowley <connor.bowley@kitware.com>
=> PERF: Update VTK with backported fix improving renderer and viewport perf

CMake/SlicerBlockInstallPython.cmake, CMake/SlicerFunctionInstallLibrary.cmake
This commits make sure directories like these ones are not packaged:
```
./lib/python3.6/test/
./lib/python3.6/site-packages/scipy/io/tests/
./lib/python3.6/site-packages/scipy/signal/tests/
./lib/python3.6/site-packages/numpy/linalg/tests/
./lib/python3.6/site-packages/numpy/random/tests/
```
=> Fix python install rules ensuring "excluded" files are not packaged and exclude `/tests/`

Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx
An object name facilitates unambiguous access for the widget.
The name "CenterButton_Header" was chosen in order to differ from the "CenterButton" in the popup of the same toolbar.
=> ENH: Add object name to center button in 3D view header

Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserPlayWidget.cxx, Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserPlayWidget.h
Implement this [discussion](https://discourse.slicer.org/t/disable-snapshot-and-record-push-buttons-in-sequencebrowserplaywidget-while-recordning/19711/7)
=> ENH: Add a property to disable Record and Snapshot button

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.h
The popup was hidden both when selection was changed and when selected item was modified. Now it is not hidden when the item is modified, because it prevented selection when streaming data into Slicer. In that case if the proxy node was selected and it was modified because of the new data item appearing in the corresponding sequence, the popup was collapsed, and if the stream was fast, it could disappear in a fraction of a second.
=> BUG: Do not hide SH combobox popup when selected item is modified

Base/QTGUI/qSlicerMouseModeToolBar.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/Widgets/Resources/UI/qSlicerMarkupsPlaceWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx
This commit fixes a bug causing the fixed point number property to not be read while loading a markup node from file. This bug is documented in issue #5889
=> BUG: Corrects fixed point number property on loading markups

CMakeLists.txt
This ensures that running Slicer from a read-only location will load the
byte-compiled modules.
=> COMP: Ensure stdlib and site-packages python modules are always byte-compiled

Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserPlayWidget.cxx
This commit fixes a regression introduced in 85e6328aa0 (ENH: Add a property
to hide Record and Snapshot buttons in qMRMLSequenceBrowserPlayWidget)
See #5878
=> COMP: Fix qMRMLSequenceBrowserPlayWidget build error

Modules/Loadable/Annotations/Resources/UI/qSlicerAnnotationModuleWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx
This fixes a build error I ran into. I was building Slicer latest (cfc69c5fcd8e119dcf3060561c999c8a9baebd93).
> 33>C:\Slicer\Modules\Loadable\Markups\Widgets\qMRMLMarkupsToolBar.cxx(30,10): fatal error C1083: Cannot open include file: 'QTest': No such file or directory
I also noticed some incorrect tooltips when placing Annotation ruler and Annotation ROI node. 
Also have made slight layout improvement so annotations place buttons are compressed together.
|![image](https://user-images.githubusercontent.com/15837524/134786880-bb69b5b6-32b1-4222-ba3d-fe440d4d7efd.png)|![image](https://user-images.githubusercontent.com/15837524/134786886-ec64d11e-e50a-462b-93d8-4861f1feaae8.png)|
cc: @lassoan, @smrolfe
=> Markups Toolbar build error and Annotations place fixes

CMake/FindVcvars.cmake
Based on https://github.com/scikit-build/cmake-FindVcvars/pull/1
Required to successfully build an extension such as SlicerRadiomics with latest version of Visual Studio.
=> COMP: Update FindVcvars with MSVC 1929 support

Modules/Scripted/DICOM/DICOM.py
Using a slicelet with a custom DICOM browser and closing the app with this DICOM browser open triggers a python error caused by the dicom listener stopped as it does not have any DICOMInstance.
This simple check fix this error.
=> ENH: check DICOM instance before stopping listener

Base/QTGUI/qSlicerMouseModeToolBar.cxx, Docs/user_guide/modules/markups.md, Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsDisplayNodeTest1.cxx, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsDisplayNodeWidget.ui, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsFiducialProjectionPropertyWidget.ui, Modules/Loadable/Markups/Widgets/Resources/UI/qSlicerMarkupsPlaceWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx, Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h, Modules/Loadable/Tables/Widgets/Resources/UI/qSlicerTableColumnPropertiesWidget.ui
This addresses https://github.com/Slicer/Slicer/issues/5889#issuecomment-927207824.  For usability reasons, items should be consistently referred to with the same name in the UI and in the documentation. This allows for easier learning when users can connect that "this term over here" matches and is for "this same term over there". When different terminology is used it is natural to assume they are different objects and that can lead to confusion when they are not different. My goal here is to make Slicer more user-friendly for users to understand what is a Markup vs a Control Point across various places in the UI. At times advanced users can get a little lazy with using specific and clear terminology and that can be confusing to users trying to learn.
"Control Point" is the clear and …
=> Consistent markup control point terminology

Base/Python/slicer/util.py
This commit adds a context a manager that calls slicer.app.pauseRender() on enter and slicer.app.resumeRender() on exit.
Previously this would be written as:
```
try:
slicer.app.pauseRender()
finally:
slicer.app.resumeRender()
```
Now can be written as:
```
with slicer.util.RenderBlocker():
```
=> ENH: Add RenderBlocker context manager to call pauseRender/resumeRender

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIWidget.cxx
The GetBoundsROI function was confusingly named and did not do what users expected (returning the bounds of the ROI in node coordinates).
This commit removes the GetBoundsROI function, and adds additional documentation to explain which functions can be used to determine the ROI axis-aligned bounding box and orientated bounding box. Since the function was only used in one location, it should be safe to remove.
=> ENH: Remove vtkMRMLMarkupsROINode::GetBoundsROI() and add documentation

Docs/user_guide/modules/markups.md, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
Double-click is used in many software (PowerPoint, Inkscape, Gimp, ...) to finish point editing. It also makes double-click a more useful action during point placement (previously, a double-click resulted in placing a control point and maximizing/restoring the view).
See discussion here: https://discourse.slicer.org/t/new-feature-maximize-view/19581
=> ENH: Add mouse gesture to finish markup point placement by double-click

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialStorageNode.cxx
Calling vtkMRMLMarkupsFiducialStorageNode::SetPointFromString() with an index beyond the maximum number of control points would result in a crash. To reproduce, place a line and then copy+paste a control point using the Markups module widget.
Fixed by checking that the specified index is under the maximum, and that the control point exists before attempting to access it.
=> BUG: Fix crash in Markups storage node if setting point beyond maximum

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
The setter slots for the attribute properties in the Subject Hierarchy tree view were protected by mistake, which caused a build error when setting any of them in Qt designer, and in general not usable for the tree view.
=> BUG: Make property slots public in SH tree view

Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/Widgets/Resources/UI/qSlicerMarkupsPlaceWidget.ui, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
Originally from discussion starting at https://discourse.slicer.org/t/changes-to-the-markups-module/19871/3?u=jamesobutler
"Clear" is chosen over "Unset" since it is less technical. Action order is based on the cycle order when click in the position status column of the markups control point table.
| ![image](https://user-images.githubusercontent.com/15837524/135353453-fecd3318-5cf7-40e8-a6e8-c34011e5dec3.png)| ![image](https://user-images.githubusercontent.com/15837524/135353330-bf9ee5cd-2885-494b-96a0-3936350a31b0.png)|
|![image](https://user-images.githubusercontent.com/15837524/135351384-e9c090ea-6880-4e68-a7c7-d7951b08aa5a.png)|![image](https://user-images.githubusercontent.com/15837524/135353255-f23b08b8-8708-4186-a9b1-b19ba1ab57c5.png)| …
=> ENH: Reorder and rename control point position status options for clarity

SuperBuild/External_CTK.cmake
(This PR originates from [this discussion](https://github.com/Slicer/Slicer/pull/5909))
Support for the QtMultimedia component has been recently [added to CTK](https://github.com/commontk/CTK/pull/992).
This PR simply forward this support to Slicer.
=> COMP: add QtMultimedia Python wrapper from CTK

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsStorageNodeTest2.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
Fixes a bug introduced by the fix in 1b21b7208594f3b6c1ed387ae648c3e9d757f1d0.
Pasting a control point from the Markups module widget would be prevented in markups nodes that had MaximumNumberOfControlPoints of 0.
Fixed by also checking that MaximumNumberOfControlPoints is greater than 0 before returning.
=> BUG: Fix control point copy paste with 0 maximum control points

SuperBuild/External_SimpleITK.cmake, SuperBuild/External_python-dicom-requirements.cmake, SuperBuild/External_python-extension-manager-requirements.cmake, SuperBuild/External_python-extension-manager-ssl-requirements.cmake, SuperBuild/External_python-pip.cmake, SuperBuild/External_python-pythonqt-requirements.cmake, SuperBuild/External_python-requests-requirements.cmake, SuperBuild/External_python-setuptools.cmake, SuperBuild/External_python-wheel.cmake, Utilities/Scripts/SlicerWizard/Utilities.py
Python packages were last updated June 15th, 2021. Outdated python packages were discovered and updated using the python_package_updater.py script in the Slicer repo and then dependencies new/conflicting were manually reviewed.
```
PS C:\Users\JamesButler\AppData\Local\NA-MIC\Slicer 4.13.0-2021-09-27\bin> ./PythonSlicer "C:\Users\JamesButler\Documents\GitHub\Slicer\Utilities\Scripts\python_package_updater.py"
WARNING: You are using pip version 21.1.2; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\JamesButler\AppData\Local\NA-MIC\Slicer 4.13.0-2021-09-27\bin\python-real.exe -m pip install --upgrade pip' command.
Package           Version  Latest   Type
----------------- -------- -------- -----
Deprecated        1.2.12   1.2.13   wheel
dicomweb-client …
```
=> Update python packages to latest Sept 2021

Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionRepresentation2D.cxx
When no intersection point was detected, return the center of slice view.
But the index was wrong before
=> BUG: Fix slice intersection representation point default case

Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsROIWidget.ui
This commit removes uses of `PlaceholderText` in UI file that was
originally introduced in 294e142189 (ENH: Refactor markups module widgets)
It fixes the following error:
```
error: ‘PlaceholderText’ is not a member of ‘QPalette’
```
`QPalette::PlaceholderText` was introduced in Qt 5.12.
See https://github.com/qt/qtbase/commit/ebd3a13b807c6af2684b42d3912549caf7ef82aa
=> COMP: Fix qMRMLMarkupsROIWidget build error against Qt 5.10

SuperBuild.cmake
This commit fixes a regression introduced in a15cbacbb9 (ENH: Add "Select
by points" tool to Dynamic Modeler module)
List of SlicerSurfaceToolbox changes:
```
$ git shortlog 8dd9ce053..df684ae --no-merges
Jean-Christophe Fillion-Robin (20):
COMP: Simplify setting of position independent flag for MeshGeodesics target
COMP: Fix -Wunknown-pragmas in DynamicModeler/Logic/FastMarching
COMP: Fix -Wunused-parameter in DynamicModeler/Logic/FastMarching
COMP: Fix -Wreorder in DynamicModeler/Logic/FastMarching
BUG: Fix GW_Face::GetEdgeNumber to return -1 if edge is not found
COMP: Fix -Wunused-variable in GW_Mesh::BuildCurvatureData
COMP: Fix -Wsign-compare in GW_VectorStatic.h
COMP: Fix -Woverloaded-virtual in DynamicModeler/Logic/FastMarching
COMP: Fix -Wdelete-non-virtual-dtor in …
```
=> COMP: Fix macOS build error updating SlicerSurfaceToolbox

Modules/Loadable/Markups/MRML/vtkProjectMarkupsCurvePointsFilter.cxx, SuperBuild.cmake
List of SlicerSurfaceToolbox changes:
```
$ git shortlog df684ae..c7cf164 --no-merges
COMP: Update DynamicModeler/Logic/FastMarching to support VTK8
```
This commit fixes the following errors:
```
/path/to/S-r/VTK/Common/Core/vtkNew.h:62:21: error: incomplete type 'vtkGenericCell' named in nested name specifier
vtkNew() : Object(T::New())
^~~
/path/to/S/Modules/Loadable/Markups/MRML/vtkProjectMarkupsCurvePointsFilter.cxx:186:29: note: in instantiation of member function 'vtkNew<vtkGenericCell>::vtkNew' requested
here
vtkNew <vtkGenericCell> cell;
^
/path/to/S-r/SurfaceToolbox/DynamicModeler/Logic/FastMarching/vtkPolygonalSurfaceContourLineInterpolator2.cxx:148:11: error: no member named 'SetInput' in
'vtkDijkstraGraphGeodesicPath'
dggp->SetInput( …
```
=> COMP: Update Markups module and SurfaceToolbox project to support VTK8 build

Base/QTCore/Testing/Cxx/CMakeLists.txt, Modules/Loadable/Data/Testing/Cxx/CMakeLists.txt, Modules/Loadable/Models/Testing/Cxx/CMakeLists.txt
This commit fixes warning like the following:
```
CMake Warning (dev) at /path/to/S-r/CTK/CMake/ctkFunctionAddExecutableUtf8.cmake:18 (add_executable):
Policy CMP0115 is not set: Source file extensions must be explicit.  Run
"cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
File:
/path/to/S/Base/QTCore/Testing/Cxx/qSlicerAbstractCoreModuleTest1.cxx
Base/QTCore/Testing/Cxx/CMakeLists.txt:114 (ctk_add_executable_utf8)
```
=> COMP: Fix CMake CMP0115 warning specifying extensions with "add_executable"

SuperBuild/External_CTK.cmake
Summary:
* Fix python autocomplete
* Add DICOM browser select API
* Fix misc build warnings
* Add ctk::qStringListToQSet and ctk::qSetToQStringList
```
$ git shortlog ec9fcee532..19c36e25 --no-merges
Andras Lasso (3):
BUG: Fix autocomplete in Python console
ENH: Improve Python autocomplete list ordering
ENH: Add API to select items in the DICOM browser
Jean-Christophe Fillion-Robin (7):
COMP: Fix -Wreorder in ctkDICOMDatabasePrivate class
COMP: Fix -Wunused-parameter in ctkDICOMDisplayedFieldGenerator classes
COMP: Fix -Wsign-compare and -Wunused-variable in ctkDICOMItem class
COMP: Fix -Wdeprecated-declarations related to Qt::KeyboardModifiers
COMP: Fix -Winconsistent-missing-override in ctkCheckablePushButton
ENH: Add ctk::qStringListToQSet
ENH: Add …
```
=> ENH: Update CTK to fix python autocomplete and add DICOM browser select API

Base/QTApp/qSlicerApplicationHelper.txx, Modules/Loadable/Data/qSlicerSceneReader.cxx
This commit fixes warning like the following reported when
building against Qt >= 5.14.
* `fromSet` deprecation warning:
```
/path/to/S/Base/QTApp/qSlicerApplicationHelper.txx:169:64: warning: 'fromSet' is deprecated: Use QList<T>(set.begin(), set.end()) instead. [-Wdeprecated-declarations]
QStringList failedToBeInstantiatedModuleNames = QStringList::fromSet(
^
/path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qlist.h:410:5: note: 'fromSet' has been explicitly marked deprecated here
QT_DEPRECATED_VERSION_X_5_14("Use QList<T>(set.begin(), set.end()) instead.")
^
/path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qglobal.h:366:45: note: expanded from macro 'QT_DEPRECATED_VERSION_X_5_14'
^
/path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qglobal.h: …
```
=> COMP: Fix QList::to/fromSet deprecation warnings

SuperBuild/External_CTK.cmake
This commit also fixes the build by ensuring the`ctk::endl` function
required by previous commit da61c65a59 (`COMP: Fix endl deprecation warning
in qMRMLLabelComboBox`) is available.
```
$ git shortlog 19c36e250..03575a03 --no-merges
COMP: Consistently export global and namespace symbols
ENH: Add ctk::flush and ctk::endl to fix deprecation warnings with Qt >= 5.14
COMP: Fix endl deprecation warning using ctk::end
COMP: Fix qt5_get_moc_flags/qt5_create_moc_command deprecation CMake warnings
```
=> COMP: Update to fix both endl and CMake qt5_*_moc deprecation warnings

SuperBuild/External_CTK.cmake
```
$ git shortlog 03575a032..27f89406 --no-merges
Jean-Christophe Fillion-Robin (5):
COMP: Fix QFlags deprecation warnings related to Qt::ColorDialogOptions
COMP: Fix QAtomicInt::load() deprecation warning in ctkErrorLogQtMessageHandler
COMP: Fix QTime::start(), QTime::elasped() deprecation warnings
COMP: Fix QFlags deprecation warnings related to ctkColorPickerButton::ColorDialogOptions
COMP: Fix QPixmapCache::find deprecation warnings in ctkPixmapIconEngine
```
=> COMP: Update CTK to fix deprecation warnings

Base/QTApp/Resources/UI/qSlicerMainWindow.ui
The Edit Box class was removed when the legacy "Editor" module was removed from Slicer in https://github.com/Slicer/Slicer/commit/39283db420baf502fa99865c9d5d58d0e5295a6e.
The Edit Box action was visible in Help->Keyboard Shortcuts and is now removed with this PR.
=> ENH: Remove Edit Box action

Extensions/CMake/Testing/CMakeLists.txt
By default, non-existing github repositories using https will prompt for authentication under https (e.g., `Username for 'https://github.com':`). Some of the underlying extension tests rely on testing non-existing repositories, which trigger authentication prompts.
This disables the authentication prompts by setting the
`GIT_TERMINAL_PROMPT` variable to `0` during testing of relevant tests.
The authentication prompt triggered on the following tests:
- Test   7: py_cmake_slicer_extensions_index_build_without_upload
- Test   8: py_cmake_slicer_extensions_index_build_with_upload
- Test   9: py_cmake_slicer_extensions_index_build_with_upload_using_ctest
- Test  10: py_cmake_slicer_extensions_index_build_without_upload_using_ctest
=> ENH: Disable prompt for non-existing git repos

CMake/SlicerCPackBundleFixup.cmake.in
After inspecting the history of Slicer/DashboardScripts project (see [1]),
the regression was likely introduced when transitioning from Qt 5.10 to
5.15.0 in June 2020.
[1] https://github.com/Slicer/DashboardScripts/commits/master/factory-south-macos-slicer_preview_nightly.cmake
Issue was identified following this process:
(1) Copy relevant code from the configured "SlicerCPackBundleFixup.cmake"
into a CMake script where calls to "file(COPY ..." and "execute_process"
were changed to be no-op by using "message()" statements.
(2) Copy first command into a bash script and attempt to execute in a
standalone way.
Doing so led to the following command and error message:
```
install_name_tool \
-rpath "@executable_path/Frameworks" "@loader_path/../../../../" \
-change \ …
```
=> COMP: Attempt to fix launching of designer in macOS package

Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionRepresentation2D.cxx
when computing rotation center among slice intersection lines, if
two lines intersect under 3 degrees, they are considered to be
parallel and their intersection point is not counted.
Refs:
https://discourse.slicer.org/t/rotation-center-moves-in-ctrl-alt-drag/19986
and
https://github.com/Slicer/Slicer/issues/5936
=> PERF: two slice intersection lines under 3 degrees are not counted

Modules/Loadable/Markups/Widgets/Testing/Python/MarkupsWidgetsSelfTest.py, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx, Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx, Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.h
This closes #5917.
Having unset control point position options visible in the place widget by default can lead to weird situations such as the functionality enabled for the SurfaceCut effect. This effect doesn't have a set number of control points and would not benefit from unsetting points. Having unset points not visible by default will maintain previous behavior prior to 09d12ae.
The options is turned on only for the Markups toolbar.
```python
place_widget =slicer.qSlicerMarkupsPlaceWidget()
place_widget.setMRMLScene(slicer.mrmlScene)
place_widget.setCurrentNode(slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode"))
place_widget.show()
```
Place a point and then you will see the default place widget does not have unset options shown by default.
Markups ToolBar has the unset …
=> BUG: Fix unset control point position options visible in default place widget

Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx
This closes #5914.
The Place control point QToolButton was changed in https://github.com/Slicer/Slicer/commit/09d12ae6f7598fe8490b691d17a35dcca5bd344a (specifically [here](https://github.com/Slicer/Slicer/commit/09d12ae6f7598fe8490b691d17a35dcca5bd344a#diff-b15fee96f47b8f3a2987141a9caae794d55d9a578a07a32a1febafac506d523eR53-R55)) to use the `QToolButton::MenuButtonPopup` type for [ToolButtonPopupMode](https://doc.qt.io/qt-5/qtoolbutton.html#ToolButtonPopupMode-enum). Previously it was the default `QToolButton::DelayedPopup`. DelayedPopup would automatically hide the menu arrow when there was no menu, however the `QToolButton::MenuButtonPopup` option always shows the button even when there is no menu.
To avoid showing a menu button with no menu, we can switch to the …
=> BUG: Fix place control point button menu button always visible

Modules/Loadable/Annotations/qSlicerAnnotationsModule.cxx
Annotations module has been replaced by the Markups module. This moves the Annotations module to the legacy category to make it clear that any remaining objects are legacy and will be removed in the future.
Deprecating of the Annotations module is mentioned in the [Slicer roadmap](https://github.com/Slicer/Slicer/wiki/Roadmap). Moving it to the Legacy category does not hide the module from users, but does put it into a more appropriate category rather than being the first "main" module in the module selector menu.
|![image](https://user-images.githubusercontent.com/15837524/141374683-120fe743-aa00-4bc5-828a-ad98173c29d3.png)|![image](https://user-images.githubusercontent.com/15837524/141374708-1d7dd181-346a-4f80-b9c9-a44fd3ebdbc7.png)|
=> ENH: Move Annotations module to Legacy category

Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
std::regex was causing a bad alloc error with the updated gcc compiler.
To fix the error, the regex used for format string validation is switched from std::regex to kwsys.
Re: #6011
=> BUG: Fix bad alloc error from sequence string validation on Linux

Libs/MRML/Core/vtkMRMLScalarVolumeNode.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLWindowLevelWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLWindowLevelWidget.h, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/SubjectHierarchy/Widgets/CMakeLists.txt, Modules/Loadable/Volumes/Logic/CMakeLists.txt, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.h, Modules/Loadable/Volumes/Resources/Schema/volumes-display-presets-schema-v1.0.0.json, Modules/Loadable/Volumes/Resources/VolumeDisplayPresets.json, Modules/Loadable/Volumes/SubjectHierarchyPlugins/CMakeLists.txt, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.h, Modules/Loadable/Volumes/Widgets/CMakeLists.txt, Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.cxx
Add functionality to display volume presets from the slice view right-click menu.  
Do not display the preset menu in 3D view.   
Let it only display if a scalarvolume is displayed in slice view.   
Make the presets checkable and setcheck(true) them upon selection  
Make this work even if several scalar volumes are loaded.  
Set the presets by a function call to  [Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx](https://github.com/Slicer/Slicer/compare/master...rbumm:master#diff-e66332c76fe962dd310d54e008ed379b062f3fec8a74f0969d4706d96b362ad4) 
To do:
find a way to define a default window/level preset that the user can define by special action and that be used as default upon every start of Slicer.  
Limitations:
*   qSlicerScalarVolumeDisplayWidget has still its hard coded …
=> ENH: Add intuitive volume presets

CMake/SlicerGenerateSlicerConfig.cmake
When an extension was configured, VTK printed the warning message: "The `VTK_USE_FILE` is no longer used starting with 8.90."
This is due to that in VTK9 defines VTK_USE_FILE variable (so Slicer attempts to use it), but the variable just points to a file (vtk-use-file-deprecated.cmake) that prints the message that the file is deprecated.
Fixed by explicitly disabling usage of VTK_USE_FILE for VTK9.
=> COMP: Fix VTK_USE_FILE warning when building extensions

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsFiducialNodeTest1.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsFiducialStorageNodeTest2.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsFiducialStorageNodeTest3.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMarkupsAnnotationSceneTest.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkSlicerMarkupsLogicTest3.cxx, Modules/Loadable/Markups/Testing/Python/MarkupsSceneViewRestoreTestManyLists.py
This closes #5990 by providing warnings of deprecated methods. Developers are alerted of the deprecation at runtime which is a lot more helpful than only documented in the source code.
Deprecation with runtime warnings is like what is already done for `SetSliceIntersectionVisibility`.
https://github.com/Slicer/Slicer/blob/6582c1f0b0ec5772776564e5c2704e78b82ea261/Libs/MRML/Core/vtkMRMLDisplayNode.cxx#L932-L935
=> ENH: Add deprecation warnings to deprecated Markups API methods

Libs/MRML/Core/vtkMRMLSegmentationNode.cxx, Libs/MRML/Core/vtkMRMLSegmentationNode.h, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsModel.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsTableView.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsTableView.h
When vtkMRMLSegmentationNode were copied from recorded sequences, no events were emitted that would cause the table to update. This commit adds SegmentationChangedEvent to vtkMRMLSegmentationNode, which is triggered whenever the vtkSegmentation object is changed. If the event is observed by qMRMLSegmentsModel, it will trigger a reset of the model.
This commit also makes some changes to qMRMLSegmentsTableView and qMRMLSegmentEditorWidget to ensure that the widget states are consistent during Segmentation node Sequence replay.
Fixes #5953
=> BUG: Fix Segment table update for Segmentation replay in Sequences

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
This closes #5599.
When there was an active segment editor effect cursor icon and then the interaction mode was changed away from ViewTransform, it would set the new interaction mode icon and then set the active segment editor effect to None where setting the null effect arrow cursor icon would overwrite the newly set interaction mode icon.
=> BUG: Fix null segment editor effect cursor icon overwriting mouse mode icon

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsModel.cxx
If no Segmentation node was set, endResetModel() was not called. This left the table signals blocked, since qMRMLSegmentsTableView::modelReset() was not triggered.
=> BUG: Unblock segment table signals when no Segmentation node is set

Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLCrosshairDisplayableManager.cxx, Libs/MRML/DisplayableManager/vtkMRMLCrosshairDisplayableManager3D.cxx, Libs/MRML/DisplayableManager/vtkMRMLInteractionEventData.cxx, Libs/MRML/DisplayableManager/vtkMRMLInteractionEventData.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLWindowLevelWidget.cxx, Libs/MRML/Widgets/qMRMLScreenShotDialog.cxx, Modules/Loadable/Annotations/VTKWidgets/vtkAnnotationROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h
Added fast `WorldToDisplay` to `vtkMRMLInteractionEventData` which will cache the Composite Projection Transform matrix from the camera on first use.
This seems to increase the FPS of scenes with high amounts of fiducial markups by 1-2 FPS. Therefore I do not think this solves the whole of the performance problem mentioned in https://github.com/Slicer/Slicer/issues/5752, but is a marginal improvement towards it.
=> Improve markups rendering performance

Docs/developer_guide/script_repository/gui.md
This script was built to install Slicer with BoneTextureExtension in a container. See https://github.com/DCBIA-OrthoLab/SlicerCMF-docker/pull/2. I've included the same script here, with some modifications.
The added script `slicer-download.sh` downloads and extracts Slicer to a target directory. It accepts parameters to select slicer version and pre-installed extensions; I've documented these in a comment at the top of the script, however I don't have any `--help` text or similar set up. The script depends on `rsync`, `curl`, and `jq`; I'm not sure the best place to document this.
It can also be used to install extensions into an existing installation of Slicer by setting `-d dest` to the Slicer root directory.
The script only supports the Linux `.tar.gz` binaries. It may be possible to …
=> DOC: Add programmatic installation section to developer guide 

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx
When all control points were removed from the ROI node, the ROI would remain visible. In addition, attempting to re-place the ROI would only allow one point to be placed.
Fixed visibility issues by disabling the ROI actors if there are no control points.
Fixed the re-placement issue by changing the maximum number of control points from -1 to 2 for "Box" type ROI when all control points were removed.
Fixes #5898
=> BUG: Fix Markups ROI visibility when all control points are removed

Libs/MRML/Widgets/qMRMLNodeComboBox.cxx, Libs/MRML/Widgets/qMRMLSceneCategoryModel.cxx, Libs/MRML/Widgets/qMRMLSceneModel.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel.cxx, SuperBuild/External_CTK.cmake
```
$ git shortlog 27f89406..04a3fd3b --no-merges
COMP: Fix QModelIndex::child() deprecation warnings
```
This commit introduces `ctk::modelChildIndex()` function so that the
same code compiles without deprecation warnings pre and post Qt 5.8.
It fixes warnings like the following:
```
/path/to/S-r/CTK/Libs/DICOM/Core/ctkDICOMModel.cpp:745:32: warning: 'child' is deprecated: Use QAbstractItemModel::index [-Wdeprecated-declarations]
this->setChildData(index.child(i,0), value, role);
^
/path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h:71:5: note: 'child' has been explicitly marked deprecated here
QT_DEPRECATED_X("Use QAbstractItemModel::index") inline QModelIndex child(int row, int column) const;
^ …
```
=> COMP: Update CTK to fix QModelIndex::child() deprecation warnings

Base/QTApp/qSlicerMainWindow.cxx, Base/QTApp/qSlicerMainWindow.h, Base/QTApp/qSlicerMainWindow_p.h
This is useful when writing custom applications overriding the default
application close behavior.
See https://www.slicer.org/wiki/Documentation/Nightly/ScriptRepository#Override_application_close_behavior
=> ENH: Add restoreGUIState/saveGUIState to qSlicerMainWindow public API

Docs/developer_guide/script_repository/volumes.md, Docs/user_guide/modules/data.md, Docs/user_guide/modules/editor.md, Docs/user_guide/modules/index.md, Docs/user_guide/modules/segmentations.md, Docs/user_guide/modules/segmenteditor.md
re #5664
The Editor module was removed in https://github.com/Slicer/Slicer/commit/39283db420baf502fa99865c9d5d58d0e5295a6e. The Segment Editor module was the replacement.
=> DOC: Remove Editor module documentation

Extensions/CMake/SlicerExtensionDescriptionSpec.cmake, Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake, Extensions/CMake/Testing/extension_description_with_depends.s4ext, Extensions/CMake/Testing/extension_description_without_depends.s4ext
This commit fixes the following tests:
* `cmake_slicer_extension_description_spec_defaults_test`
* `cmake_slicer_generate_extension_description_test`
by implementing the following changes:
* Fix regression introduced in d1a182641 (STYLE: Trim trailing whitespace)
by specifying a status value for both "with" and "without" depends tests
* Update s4ext baseline to use "https" instead of "git". This fixes
a regression introduced in 99578c69e (COMP: Use https protocol for
git by default) and fb404815f (ENH: Replace git:// by https://)
* Update expected metadata count in description spec test. This fixes
a regression introduced in 7f533d3d0 (STYLE: Remove svn references
from extension description file).
=> COMP: Fix CMake extension description tests

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIDisplayNode.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIWidget.cxx
In the same way that ROI corner handles can be used to change the size of an ROI in the 3D view, this commit adds handles to the ROI edges that can be used in Slice views.
Re #5061
=> ENH: Add ROI edge handles to slice views

Libs/MRML/Logic/vtkImageLabelOutline.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py
Segment editor effects that use "ModificationModeSet" restore the existing segment outside of the masking region. The mask was not being applied, and so the entire segment was restored. Fixed by only restoring the segment outside the mask area.
This commit also adds tests for intensity masking with island effects, and fixes issues that caused the test to fail when run with a main window. (Uninitialized labelmaps + unhandled VTK_SIGNED_CHAR data type in vtkImageLabelOutline).
Fixes #6043
=> BUG: Fix intensity masking for Islands effect

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h
Currently the Markups rotation handle "hangs" as a single arc around the rotation axis, which looks strange if the translation handles are hidden. This commit connects the arc with a right angle so that it forms an enclosed shape.
Before:
After:
Re #5061
=> ENH: Improve Markups rotation handle appearance

SuperBuild/External_python.cmake, SuperBuild/python_configure_python_launcher.cmake
This commit updates the configuration of the launcher to ensure the settings
needed to lookup the user revision settings are set.
The user revision settings contain the extension settings like Paths,
LibraryPaths and EnvironmentVariables.
See https://discourse.slicer.org/t/slicer-no-main-window-python-script-in-windows-command-prompt-not-working/6481/26
Fixes #4603
=> BUG: Ensure PythonSlicer loads extension settings

Base/Python/slicer/ScriptedLoadableModule.py, Base/Python/slicer/util.py, Modules/Scripted/DICOMLib/DICOMSendDialog.py, Modules/Scripted/DICOMPatcher/DICOMPatcher.py, Modules/Scripted/SegmentStatistics/SegmentStatistics.py, Utilities/Templates/Modules/Scripted/TemplateKey.py
These are some potentially useful utils coming from https://github.com/fepegar/SlicerParcellation/blob/master/lib/GeneralUtils.py.
@lassoan's comments were:
> There is indeed some repeating code pattern with the waitcursor and printing of exception messages which would be nice to simplify. Please send a pull request to Slicer core with the content of GeneralUtils.py to start a discussion. Initial comment: the overridecursor has to be restored when an exception occurs ("finally" is too late because the popup window is displayed in "except" and it is not nice if the waitcursor is still shown when the user gets the error popup). messageContextManager: It seems that it is intended for progress reporting, but for thatyou can already use the statusbar or delaydisplay. A context manager for …
=> ENH: Add context managers to show while waiting

Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.h, Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui, Libs/MRML/Widgets/Resources/UI/qMRMLThreeDViewControllerWidget.ui, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.h
Using the right-click menu is a convenient way to interact with the Slicer views. The top 'center view' icon is probably the one most used in Slicer, but the icon itself is small and a small but significant amount of time is needed to focus the mouse on this spot. The tilt-lock key combination is a little hard to grab and the status of the tilt-lock is not displayed. So this PR is about:       
*   Add 'Fit View' menu entry in scalar volume view
*   Add 'Center 3D view' menu entry  in 3D view
*   Add a checkable 'Tilt lock' menu entry in 3D view and connect it to the camera widget
Tested for several days, works well.
=> ENH: Enhance the right-click menu in Slicer views

Modules/Scripted/DataProbe/DataProbe.py
By setting the the horizontal size policy of the data probe widget to "Ignored", the widget will use as much space as is provided horizontally, but will never cause the module panel to change size.
The widget can still expand vertically, allowing strings that are too long to be displayed in a single line to be wrapped and not truncated.
=> BUG: Prevent data probe from expanding horizontally

Modules/CLI/ResampleScalarVectorDWIVolume/ResampleScalarVectorDWIVolume.xml
Saw this minor issue when looking through some documentation.
The generated documentation was creating a hyperlink to the webpage "Transforms.it".
=> DOC: Fix unintended link in ResampleScalarVectorDWIVolme documentation

.github/actions/slicer-build/entrypoint.sh, .github/workflows/ci.yml
This commit copies the package to `GITHUB_WORKSPACE` instead of `RUNNER_TEMP`. This
is required to workaround issue discussed in actions/runner#965 (Incorrect context
paths in container)
It also adds a step for uploading the generated Slicer package as an
artifact with a retention time of 1 day.
=> COMP: Improve "CI" GitHub Action workflow uploading package as artifact

Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h
This matches changes other recent changes to consistent usage of "control point" instead of "fiducial". "Control point" is already appropriately used in the Markups toolbar, but was not in the Markups module widget.
| ![image](https://user-images.githubusercontent.com/15837524/144277279-d08e019f-1a96-48f3-b0f8-871597ce7852.png)| ![image](https://user-images.githubusercontent.com/15837524/144279399-f714b5e6-cbdf-4d82-983a-21a4b5b4c2e8.png)|
=> ENH: Clean up qSlicerMarkupsModuleWidget to use appropriate Control Point terminology

Modules/Loadable/Markups/Resources/Schema/markups-schema-v1.0.3.json
Attempted to modify the description of the "size" item so that it more clearly distinguished between characterizing the size of a markups object as a radius from a center point vs a diameter across a center point.  Schema change was suggested here: https://discourse.slicer.org/t/explanation-needed-for-json-files-created-by-markup/20842/7
=> DOC: Clarify "size" description in markups JSON schema

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
A custom markup "GridSurface" did not specify a `GetMarkupTypeDisplayName`, so in Slicer it was shown as "Markup" in the Markups module. This isn't helpful so it should fallback to use the internal markup type name of "GridSurface" even though it should have a `GetMarkupTypeDisplayName` method that defines it as "Grid Surface" (see https://github.com/cpinter/SlicerSurfaceMarkup/pull/3).
|![image](https://user-images.githubusercontent.com/15837524/144295645-3adf5fc5-e643-42ba-ba8e-bce18253a76a.png)|![image](https://user-images.githubusercontent.com/15837524/144297410-8e5539ba-32bb-40a8-bd7e-693d9447d8e9.png)|
=> ENH: Use markup type internal name when display name not specified

SuperBuild.cmake
```
$ git shortlog --topo-order --no-merges 290d481..551cee5
Update test data download URL
James Butler (2):
ENH: Use non-deprecated markups API
ENH: Use point terminology instead of fiducial
```
=> COMP: Update Landmark Registration

CMake/FindVcvars.cmake
This is based on FindVcvars.cmake as of https://github.com/scikit-build/cmake-FindVcvars/commit/a57b8b9df60ba1bd650a81f7f28c8b9ea4f96beb.
=> ENH: Update FindVcvars for future MSVC versions

Libs/MRML/Core/vtkArchive.cxx, Libs/MRML/Core/vtkCacheManager.cxx, Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx
This commit addresses build issues related to the KWSys updates related
to return result of function like SystemTools::MakeDirectory introduced in
commit Kitware/VTK@8cb5e736a (Merge branch 'upstream-KWSys' into HEAD).
=> COMP: Update SystemTools use anticipating update from VTK 9.0 to 9.1

Base/QTCore/qSlicerCoreIOManager.cxx, Base/QTCore/qSlicerCoreIOManager.h, Base/QTGUI/CMakeLists.txt, Base/QTGUI/Resources/UI/qSlicerExportNodeDialog.ui, Base/QTGUI/qSlicerExportNodeDialog.cxx, Base/QTGUI/qSlicerExportNodeDialog.h, Base/QTGUI/qSlicerExportNodeDialog_p.h, Base/QTGUI/qSlicerNodeWriter.h, Base/QTGUI/qSlicerSaveDataDialog.cxx, Base/QTGUI/qSlicerSaveDataDialog_p.h, Libs/MRML/Core/vtkMRMLMeasurement.cxx, Libs/MRML/Core/vtkMRMLStorageNode.cxx, Libs/MRML/Core/vtkMRMLStorageNode.h, Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx, Modules/Loadable/Data/qSlicerDataModule.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsNodeWriter.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsNodeWriter.h, Modules/Loadable/Segmentations/qSlicerSegmentationsNodeWriterOptionsWidget.cxx, Modules/Loadable/SubjectHierarchy/Widgets/CMakeLists.txt, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyExportPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyExportPlugin.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx
This is my second go at addressing #4989. Related links:
- [first try](https://github.com/Slicer/Slicer/pull/5805)
- [my comment](https://github.com/Slicer/Slicer/issues/4989#issuecomment-904779802) that followed discussion about the first PR
- [related SlicerMorph issue](https://github.com/SlicerMorph/SlicerMorph/issues/72)
This time the export module is a loadable module written in C++, and it gets its own `qSlicerFileDialog` that is opened via `qSlicerApplication::application()->ioManager()->openDialog`.
@lassoan @pieper @cpinter @smrolfe  @sjh26  
Right click on an item in the subject hierarchy view, and there will be an "Export" action available if it is a storable node. This brings up a simple export dialog.
I will squash all "WIP" commits into one "ENH" commit if this becomes ready …
=> Export individual nodes

Docs/user_guide/modules/markups.md, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/Resources/Schema/markups-schema-v1.0.3.json, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsInteractionHandleWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsInteractionHandleWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModule.cxx
Previously the size of the interaction handles was controlled using the vtkMRMLMarkupsDisplayNode::GlyphScale/GlyphSize properties.
This commit adds the vtkMRMLMarkupsDisplayNode::InteractionHandleScale property, which behaves in the same way as GlyphScale except only affects the interaction handle. The interaction handles are no longer affected by Glyph properties.
Also cleans up the constants used to define the size of the interaction widget.
Re #5061
=> ENH: Add vtkMRMLMarkupsDisplayNode interaction handle scale property

Docs/user_guide/modules/markups.md, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h, Modules/Loadable/Markups/Resources/Schema/markups-schema-v1.0.3.json, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsROIWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsROIWidget.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsROIWidget.h
The inside out function can be used to invert the ROI so that points inside the ROI are considered outside, and vice versa. This state is reflected in GetPlanes()/GetPlanesWorld() and IsPointInROI()/IsPointInROIWorld().
This commit also adds implicit functions to the ROI node that can be used by other nodes, and that will invert their sign based on the InsideOut state.
Re #5061
=> ENH: Add Markups ROI InsideOut flag

Base/QTApp/qSlicerMainWindow.cxx
To center "Save before exit?" window on main window even if the main window is not maximized.
=> ENH: Center "Save before exit?" window on main window

SuperBuild.cmake
$ git shortlog c7cf164..ba4a56c
ENH: Set more user-friendly name for boundary cut tool
BUG: Fix error linking vtkSlicerDynamicModelerModuleLogic in extensions
=> BUG: Update SurfaceToolbox to fix linking Dynamic Modeler logic

CONTRIBUTING.md, Docs/developer_guide/extensions.md, Docs/user_guide/getting_started.md, Utilities/Doxygen/SlicerMainPage.dox
This is a followup commit to [62e4d85](https://github.com/Slicer/Slicer/commit/62e4d8544f2a6f30b707a87288a5e1b9fc5a5a86). That commit should've been titled `ENH: Rename CDash project name from "Slicer4" to "SlicerStable"` instead of `ENH: Rename CDash project name from "Slicer4" to "SlicerPreview"`.
Also added a commit to update extensions catalog link from outdated midas link. This extensions catalog link is located on the User Guide Getting Started doc page.
=> DOC: Update link to Slicer Stable CDash

Libs/MRML/Core/vtkMRMLNode.h, Libs/MRML/Core/vtkMRMLScene.cxx, Libs/MRML/Core/vtkMRMLScene.h, Libs/MRML/Widgets/qMRMLNodeComboBox.cxx, Libs/MRML/Widgets/qMRMLNodeComboBox_p.h, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsClosedCurveNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest1.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest2.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkSlicerMarkupsLogicTest2.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Utilities/Templates/Modules/LoadableCustomMarkups/MRML/vtkMRMLMarkupsTestLineNode.h
The markups toolbar node selector was not getting a specific nodeTypeLabel from GetTagByClassName so it was just using the fallback "node" term.
|----------|----------|
| ![image](https://user-images.githubusercontent.com/15837524/142306753-193a54f0-bd83-4802-b715-0b126687e628.png)| ![image](https://user-images.githubusercontent.com/15837524/142306621-aa19ea64-6929-4e8e-a84f-f1bbc2f32fa5.png)|
It is weird that `GetTagByClassName("vtkMRMLMarkupsNode")` is returning an empty string during startup which is why it was proceeding to the end of `qMRMLNodeComboBox::nodeTypeLabel()` to then get the "node" term. I would have expected it to get the node tag name of "Markups" (as seen below). I'm assuming it has something to do with the creation of the Markups ToolBar prior to …
=> BUG: Fix markups toolbar node selector not using specific node label

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx
Whenever a Markups closed curve node is modified the displayable manager calls vtkMRMLMarkupsNode::GetCenterPositionWorld. This logs a warning due to the use of the deprecated GetCenterPositionVector method.
Fixed by using the non-deprecated GetCenterPosition.
=> BUG: Fix vtkMRMLMarkupsNode::GetCenterPositionWorld deprecation warning

Docs/user_guide/modules/markups.md, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.h, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar_p.h, Modules/Loadable/Markups/qSlicerMarkupsModule.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
Fixes bug causing custom markup types to not appear in the Markups toolbar or module after registration. Addresses issue https://github.com/Slicer/Slicer/issues/5918
=> BUG: Fix registration of custom markups

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
Without `PointAboutToBeRemovedEvent` it used to be impossible to get
info about removed point (name, description).
`PointAboutToBeRemovedEvent` solves this issue.
`PointAboutToBeAddedEvent` is introduced mostly for the symmetry.
=> ENH: Added `PointAboutToBe/Added/Removed/Event`s.

Modules/Loadable/Segmentations/EditorEffects/Python/CMakeLists.txt, Modules/Loadable/SubjectHierarchy/Widgets/Python/CMakeLists.txt
scripted modules were getting a subfolder with duplicated content on final windows build.
=> BUG: duplicated subfolder on scripted modules

Modules/Scripted/DICOMLib/DICOMUtils.py
It is possible to encounter a non-empty NumberOfFrames with the value of "1".
Currently, this would result in a warning that DICOM is multiframe, which can
be confusing.
=> ENH: check if NumberOfFrames is 1

Docs/developer_guide/api.md, Docs/developer_guide/script_repository/markups.md, Docs/developer_guide/script_repository/models.md, Docs/developer_guide/script_repository/volumes.md, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest1.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkSlicerMarkupsLogicTest1.cxx, Modules/Loadable/Markups/Widgets/Testing/Python/MarkupsWidgetsSelfTest.py, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx, Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx, Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.h, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
I did this work of additional markups API cleanup after noticing the Markups module documentation beginning at the top with an example of how to add a control point and it doing `slicer.modules.markups.logic().AddFiducial()` instead of something like `slicer.modules.markups.logic().AddControlPoint()`.
Ran all tests on Windows and only the currently failing tests are still failing.
```
Deprecate all method names for that either of these applies:
- use old terms: fiducial or markup (instead of control point)
```
=> ENH: Clean up markups API further

Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx
When using a qSlicerMarkupsPlaceWidget, the place button would be disabled unless placement for the active place node was valid (vtkMRMLSelectionNode::GetActivePlaceNodePlacementValid). This could cause the place button to be disabled even when placement for the widget's current Markups node was valid.
Fixed by checking place mode validity for the current markups node in the widget, rather than the active node.
=> BUG: Fix Markups place widget not enabled when active node is not set

Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx, Libs/vtkSegmentationCore/vtkSegmentation.cxx, Libs/vtkSegmentationCore/vtkSegmentation.h, Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.cxx
Previously, saving a Segmentation with "Crop to minimum extent" disabled, the segmentation would be cropped to exactly the reference geometry extent. This could result in the segment being truncated if the reference geometry was smaller than the effective extent of the segmentation.
Fixed by saving the segmentation using an extent that contains both the reference and effective extents.
The same behavior is fixed when exporting segments to labelmap nodes.
Fix #6102
See discussion: https://discourse.slicer.org/t/editing-segmentation-of-model-and-saving-it/21338
=> BUG: Fix truncation of Segmentations when saving at reference geometry

Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx
@pieper ,
Please consider this tiny patch.
It fixes Slicer crashing when showing a Volume Rendering markups ROI, in self built Slicer on Arch Linux. Report referenced [here](https://discourse.slicer.org/t/volume-rendering-displaying-roi-leads-to-a-crash-on-self-built-slicer/21389?u=chir.set).
Thank you.
=> Fix missing return statement in Volume Rendering logic.

Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication.h, Base/QTCore/qSlicerCoreApplication_p.h, Base/QTGUI/qSlicerSettingsGeneralPanel.cxx, CMake/SlicerDirectories.cmake, CMake/SlicerMacroBuildApplication.cmake, CMake/SlicerMacroBuildBaseQtLibrary.cmake, CMake/SlicerMacroBuildLoadableModule.cmake, CMake/SlicerMacroBuildModuleWidgets.cmake, CMake/SlicerMacroTranslation.cmake, CMakeLists.txt, Libs/MRML/Widgets/CMakeLists.txt, SuperBuild/External_CTK.cmake
Build Slicer with i18n enabled by default.
It is marked as draft because first need to merge this CTK language box improvement (https://github.com/commontk/CTK/pull/1019), but otherwise it is fully ready for review.
It should get into today's nightly build so that it can be shown at the project presentations tomorrow.
=> Enable i18n

Libs/MRML/Widgets/qMRMLVolumeInfoWidget.cxx
IJK matrix is not reset when selecting an empty volume node
=> ENH: reset IJK matrix in volume information

Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx
**Steps to reproduce**
Load Volume
keep control + mouse wheel backward in a 2D view
**Expected result:**
Image becomes bigger during movement, in order to be consistent with other zooms (wheel backward in volume rendering view) 
**Actual result:**
Image becomes smaller during movement
=> BUG: Inverse zoom when ctrl+wheel is used

CMakeLists.txt, SuperBuild/External_LibFFI.cmake, SuperBuild/External_python-dicom-requirements.cmake, SuperBuild/External_python-numpy.cmake, SuperBuild/External_python-pip.cmake, SuperBuild/External_python-scipy.cmake, SuperBuild/External_python-setuptools.cmake, SuperBuild/External_python.cmake, SuperBuild/python_configure_python_launcher.cmake
Most part of the work was done on project python-cmake-buildsystem. I've opened a [PR](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/282) over there as well. This current PR is linking to the commit on the tip of the branch over there. I've based my work on a branch by colleagues including @jcfr @dbrnz Dan Dees. Thank you. 
Updating to 3.9 was preferred to 3.10 as discussed on #5014 
Summary of changes:
1. Added libffi as a dependency to build python and use it as an external lib. We need to check if it works on other environments as well. It should, because I've only configured to set the include dirs and lib variables. It is hosted on my personal github for now. I don't mind keeping it there forever, but if you think we should move to anywhere else feel free …
=> Update Slicer python to 3.9.9

SuperBuild/External_LibFFI.cmake
This commit fixes a regression introduced in 34e48e8ae (ENH: Upgrade
from python 3.6.7 to 3.9.10)
List of LibFFI changes:
```
$ git shortlog cb4a78e..e8599d9 --no-merges
cmake: Fix HAVE_AS_X86_PCREL test on macOS ensuring linking is disabled
```
=> COMP: Update LibFFI to fix macOS link error related to HAVE_AS_X86_PCREL test

SuperBuild/External_SimpleITK.cmake
This commit fixes a regression introduced in 34e48e8ae (ENH: Upgrade
from python 3.6.7 to 3.9.10) by integrating a fix originally contributed
in the pull request Slicer#6026 (Update Slicer python to 3.9.10).
It ensures the "LibraryPaths" env. variables read by "slicer_dll_directories.add()"
is set in the file "SimpleITK_Env.cmake" included from "SimpleITK_install_step.cmake"
=> COMP: Fix windows build updating SimpleITK install step

Modules/Loadable/Segmentations/Logic/vtkImageGrowCutSegment.cxx
GCC 11 requires implicit inclusion of limits (for reference
https://gcc.gnu.org/gcc-11/porting_to.html). This adds the header in
`vtkImageGrowCutSegment.cxx`. This is loosely connected to Slicer/Slicer#6100
=> COMP: Fix explicit inclusion of <limits>

Modules/Loadable/Annotations/Testing/Python/AnnotationsTestingAddManyFiducials.py, Modules/Loadable/Annotations/Testing/Python/AnnotationsTestingAddManyROIs.py, Modules/Loadable/Annotations/Testing/Python/AnnotationsTestingAddManyRulers.py, Modules/Loadable/Markups/Testing/Python/AddManyMarkupsFiducialTest.py
This closes #6136.
`time.clock()` became unavailable in Slicer due to the recent upgrade of Python 3.6.7 to Python 3.9.10 in https://github.com/Slicer/Slicer/commit/34e48e8aef5dad19ec8a955d6f48a1940846e3f3.
From https://docs.python.org/3.7/library/time.html#time.clock:
> Deprecated since version 3.3, will be removed in version 3.8: The behaviour of this function depends on the platform: use perf_counter() or process_time() instead, depending on your requirements, to have a well defined behaviour.
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
=> BUG: Fix use of removed `time.clock()` method

Base/QTGUI/qSlicerViewersToolBar.cxx, Base/QTGUI/qSlicerViewersToolBar_p.h, Libs/MRML/Core/CMakeLists.txt, Libs/MRML/Core/vtkMRMLScene.cxx, Libs/MRML/Core/vtkMRMLSliceCompositeNode.cxx, Libs/MRML/Core/vtkMRMLSliceCompositeNode.h, Libs/MRML/Core/vtkMRMLSliceDisplayNode.cxx, Libs/MRML/Core/vtkMRMLSliceDisplayNode.h, Libs/MRML/DisplayableManager/CMakeLists.txt, Libs/MRML/DisplayableManager/vtkMRMLCrosshairDisplayableManager.cxx, Libs/MRML/DisplayableManager/vtkMRMLCrosshairDisplayableManager.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentationHelper.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentationHelper.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionRepresentation2D.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.h, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Libs/MRML/Widgets/qMRMLLayoutManager.cxx, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h, Modules/Loadable/Markups/Testing/Cxx/vtkSlicerMarkupsLogicTest1.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.h
If "Interaction" flag is enabled then slice intersections can be drag-and-dropped in slice views.
Re #5544
Co-authored-by: Csaba Pinter <pinter.csaba@gmail.com>
Continuation of https://github.com/Slicer/Slicer/pull/6008
=> ENH: Add interactive slice intersections widget

Base/QTCore/qSlicerCoreIOManager.cxx, Base/QTCore/qSlicerCoreIOManager.h, Base/QTGUI/Resources/UI/qSlicerExportNodeDialog.ui, Base/QTGUI/qSlicerExportNodeDialog.cxx, Base/QTGUI/qSlicerExportNodeDialog.h, Base/QTGUI/qSlicerExportNodeDialog_p.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyExportPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyExportPlugin.h
This PR addresses #6074 and extends the export functionality from #5876 by allowing multiple nodes to be exported in one batch. If you right click a a subject hierarchy item that has children, then "Export to file..." will allow you export the storable nodes that occur in the subtree rooted at your selection. You can choose to include children recursively, or to just include direct children. Multi-select is not supported here; only selecting a single subject hierarchy item with children can lead to the multiple-node-export functionality.
Each node _type_ occurring within the set of nodes slated for export will have its own options widget and its own export format dropdown box. 
The example in these screenshots does not show the "include children" or "recursively include children" …
=> ENH: Exporting multiple nodes

Docs/developer_guide/script_repository/gui.md
Update snippet to turn on slice intersections. This update is needed since the visibility of the slice intersections is not handled anymore from the _vtkMRMLSliceCompositeNode_. Instead, a new node type is used for that: _vtkMRMLSliceDisplayNode_.
More info regarding these changes: [here](https://github.com/Slicer/Slicer/pull/6124).
=> DOC: Update snippet to turn on slice intersections

Libs/MRML/Core/vtkMRMLDisplayNode.cxx, Libs/MRML/Core/vtkMRMLDisplayNode.h, Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx, Libs/MRML/Widgets/qMRMLDisplayNodeWidget.cxx, Modules/Loadable/Models/Widgets/Resources/UI/qMRMLModelDisplayNodeWidget.ui, Modules/Loadable/Models/Widgets/qMRMLModelDisplayNodeWidget.cxx, Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager3D.cxx, Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformsDisplayableManager3D.cxx, SuperBuild/External_CTK.cmake
In Models module, Display / 3D Display / Advanced section, Interpolation can be set to PBR (physically based rendering).
When PBR interpolation mode is selected then the user can edit diffuse, metallic, and roughness material parameters.
PBR is useful for building models that will be exported in glTF or other software that only supports PBR interpolation.
It also allows leveraging many more rendering features in VTK, including image-based lighting, various textures (base, normal, occlusion, emission, etc.), coats, etc. described in:
https://www.kitware.com/vtk-pbr/
https://www.kitware.com/pbrj1/
https://www.kitware.com/pbr-journey-part-3-clear-coat-model-with-vtk/
Updated CTK to latest master version to get the updated material editor that supports PBR parameter settings.
=> ENH: Add PBR rendering mode to models, segmentations, transforms display

Docs/developer_guide/advanced_topics.md, Docs/developer_guide/index.md
This transfers the [memory management info from the wiki](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MemoryManagement) into readthedocs.
See related discussions at #4205 and #6099.
We should later remember to update the wiki page to redirect to the readthedocs page.
Any suggestions about where this page should go? Here I've included it as its own page directly under "Developer Guide," but perhaps that's too high up for this small page.
=> DOC: Transfer memory management guide from wiki

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h
This commit adds event translations that will jump to the position of an interaction handle when it is left-clicked. This is the same behavior as with control points.
Re #5061
=> ENH: Jump slices when markups interaction handle is clicked

Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication.h, Base/QTCore/qSlicerCoreApplication_p.h, Docs/developer_guide/advanced_topics.md, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
The current working directory can be changed by any module at any time (for example, because some algorithms or executables use the current working directory for their inputs or outputs).
Therefore, modules that wanted to use the current working directory to interpret command-line arguments, or the Slicer Jupyter kernel that relies on knowing the working directory could not reliably get it.
A new property `startupWorkingPath` was added to qSlicerCoreApplication. This property is initialized from the current working directory at startup and cannot be changed later, therefore it is a reliable way of getting the original working directory.
The name is derived from "current working directory", with "current" replaced by "startup" (similarly to `startupEnvironment` property) and "directory" …
=> ENH: Add startupWorkingPath property to qSlicerCoreApplication

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h, Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx, Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.h, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar_p.h, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
This commit addresses issue: https://github.com/Slicer/Slicer/issues/5912
The color assigned to a ROI created using the single node placement buttons in the Markups module and Markups Toolbar are varied to be consistent with the varying color of nodes created using continuous placement mode.
The colormap used for the ROIs is changed from the vtkMRMLColorTableNodeRandom to MediumChartColors, which are more distinguishable.
=> BUG: Adds varying colors to ROIs added as a single node

Libs/vtkSegmentationCore/vtkOrientedImageDataResample.cxx, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py
Due to limitations in casting VTK_LONG_MAX from double to long on Linux, it is not possible to erase from VTK_LONG segments in the Segment Editor. This issue comes up when trying to fill outside a segment with VTK_LONG_MAX using vtkImageThreshold (see https://github.com/Slicer/Slicer/blob/3edd84ddba681786be9e916124126fc858592598/Libs/vtkSegmentationCore/vtkSegmentationModifier.cxx#L370-L376).
Since VTK_LONG Segmentation are not likely to be used anyway, it makes sense to remove them rather than to find a workaround.
This commit removes VTK(_UNSIGNED)_LONG from SegmentationsModuleTest2, and removes the scalar type from vtkOrientedImageDataResample::CastImageForValue so that long type labelmaps won't be created.
Closes #5427
=> BUG: Fix Segmentation test failing on Linux due with long scalar type

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
**Steps to reproduce**
- Create a subject hierarchy combo box
- Select a node
- Remove this node
- Node is still selected in the hierarchy combo box
- Call clearSelection()
**Expected results**
subject hierarchy combo box is cleared and set to None
**Actual results**
no effect, node is still selected in the hierarchy combo box
=> Fix clear selection in subject hierarchy combo box

Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.h
Added context menu option for control points in 2d/3d view to focus camera on clicked-on point. Functionally equivalent to same menu option in control point list.
=> ENH: Add focus camera to control point right-click menu

Base/Python/slicer/util.py
The message box utility functions such as `slicer.util.confirmOkCancelDisplay` are used in some extensions in such a way that tests can end up timing out and failing; this is due to the expectation of user interaction.
[SlicerAuto3dgm example that started this discussion](https://github.com/ToothAndClaw/SlicerAuto3dgm/issues/6)
[SlicerMorph example](https://slicer.cdash.org/test/21233619)
This commit addresses the issue by having message box functions such as `slicer.util.confirmOkCancelDisplay` behave differently in a testing situation: they can skip the dialog and return a default result.
I tested my changes by running the tests for SlicerAuto3dgm and SlicerMorph and seeing that they indeed skip the message boxes, while still raising those message boxes outside of a testing situation. …
=> ENH: Skip message boxes when testing

Base/Python/slicer/util.py
This is a v4.11 patch mirroring #6162:
> The message box utility functions such as slicer.util.confirmOkCancelDisplay are used in some extensions in such a way that tests can end up timing out and failing; this is due to the expectation of user interaction.
> This commit addresses the issue by having message box functions such as slicer.util.confirmOkCancelDisplay behave differently in a testing situation: they can skip the dialog and return a default result.
I just cherry-picked 95819c1a69bd162cf33adee08304143a2b2d147d which is a more minimal change that the full #6162, then I made a small modification to the docstrings.
[See here](https://github.com/ToothAndClaw/SlicerAuto3dgm/issues/6#issuecomment-1034036421) the discussion about introducing this patch.
Please let me know if it's …
=> ENH: (v4.11 patch) Skip message boxes when testing

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIDisplayNode.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.h, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsDisplayNodeWidget.ui, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsInteractionHandleWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsInteractionHandleWidget.cxx
Previously, all of the interaction handles could only be enabled/disabled with others of the same type (rotation, translation, scaling).
This commit adds options for enabling disabling the individual XYZ axes for each of the handle types, as well has the handles that allow free transformation.
ROI nodes now display translation handles by default, but only display the free translation point in the center of the ROI.
Closes #5558
Re #5061
=> ENH: Add options to toggle individual markups interaction handle axes

Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx
The tooltip "Create new ClosedCurve" is now "Create new Closed Curve".
|![image](https://user-images.githubusercontent.com/15837524/153914728-f3b51505-0010-4af4-85cd-abbbcfe2add0.png)|![image](https://user-images.githubusercontent.com/15837524/153914753-550bb70a-a683-42c3-8a27-942d38700975.png)|
=> BUG: Fix Markups toolbar not using display names

SuperBuild/External_LibArchive.cmake
This commit fixes the following error reported when LibArchive
external project is compiled gcc-11.2.0 in Gentoo Linux:
```
FAILED: libarchive/CMakeFiles/archive_static.dir/archive_read_support_format_warc.c.o
[...]
/home/rafael/src/Slicer/Slicer-master/build/LibArchive/libarchive/archive_read_support_format_warc.c:610:25: error: argument 1 of type ‘const char *’ declared as a pointer [-Werror=array-parameter=]
610 | _warc_rdver(const char *buf, size_t bsz)
|             ~~~~~~~~~~~~^~~
/home/rafael/src/Slicer/Slicer-master/build/LibArchive/libarchive/archive_read_support_format_warc.c:130:44: note: previously declared as an array ‘const char[10]’
130 | static unsigned int _warc_rdver(const char buf[10], size_t bsz);
|                                 ~~~~~~~~~~~^~~~~~~
```
The specific …
=> COMP: Update LibArchive from 3.4.3 to 3.5.2 to support GCC v11

Docs/developer_guide/debugging/codelitecpp.md, Docs/developer_guide/debugging/overview.md, Docs/developer_guide/debugging/qtcreatorcpp.md, Docs/developer_guide/debugging/vscodecpp.md, Docs/developer_guide/debugging/windowscpp.md, Docs/developer_guide/extensions.md, Docs/developer_guide/python_faq.md, Docs/user_guide/modules/retiredmodules.md
Found this broken link to the registration documentation page. Published readthedocs pages are html unless there is seemingly an index to pick the markdown name.
=> DOC: Fix internal link in retired modules list

Base/QTCore/qSlicerCoreIOManager.cxx, Base/QTGUI/Resources/UI/qSlicerExportNodeDialog.ui, Base/QTGUI/qSlicerExportNodeDialog.cxx, Base/QTGUI/qSlicerExportNodeDialog.h, Base/QTGUI/qSlicerExportNodeDialog_p.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyExportPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyExportPlugin.h, SuperBuild/External_CTK.cmake
This closes #6180 
I could use some help with testing this feature on windows. I don't have a windows machine, and I don't know how platform-robust all my directory string manipulation is. 
- dialog was getting broken in certain nested folder situations if the user unchecked and checked certain boxes
- "apply transform" option was not getting displayed in some rare-ish situations
=> ENH: Improve Export 

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementArea.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementVolume.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneWidget.cxx
Previously the plane and ROI Markups did not account for parent transform scaling when calculating the volume/area. Fixed by using GetSizeWorld methods.
The measurements now also automatically update if the parent transform node is changed.
Also fixes the position of plane scale handles when scaled by a parent transform.
Re #5061
=> BUG: Fix plane/ROI measurements to account for parent transform scaling

Docs/developer_guide/extensions.md, SuperBuild/External_DCMTK.cmake
This updates some extension documentation and a DCMTK comment about C++ standard usage. The C++ standard was updated to C++14 in Slicer and had a minimum Visual Studio version updated in https://github.com/Slicer/Slicer/commit/bc2b3f4049ef32486cf43ad16903820fc8767f27.
=> DOC: C++14 language features are allowed in extensions

Libs/MRML/Logic/Testing/Cxx/vtkMRMLColorLogicTest1.cxx, Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
This PR prevents empty colors with "(none)" label from displaying in color legend. Part of the issue #6111.
"Hide empty Colors" check box controls the behavior.
Left: Empty colors are shown; Right: Empty colors are hidden.
=> ENH: Skip empty colors with (none) label in color legend

SuperBuild/External_ITK.cmake
This commit is a follow up of b1c235939e (COMP: Update ITK to post-5.3rc03
and SimpleITK to post-2.2rc2).
It reverts NIFTI-Imaging/nifti_clib@3bd6afc7f (fix issues with
config/targets files) integrated in ITK through
InsightSoftwareConsortium/ITK@faa754cbc (Merge branch 'upstream-nifti'
into nifticlib3.0)
```
$ git shortlog be81e62232..027fd5ce0c --no-merges
BUG: Fix install of libITK(znz|niftiio) libraries specifying component
```
See #6202
=> COMP: Update ITK to fix packaging of libITKznz and libITKniftiio libraries

SuperBuild/External_LibArchive.cmake
This commit fixes a regression introduced in e5c5ad780 (COMP: Update
LibArchive from 3.4.3 to 3.5.2 to support GCC v11), it addresses the
following error by updating the interface number hard-coded in the library
path used in the "fix_rpath" external project step specific to macOS.
Error:
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool:
can't open file: /path/to/S-0-build/LibArchive-install/lib/libarchive.17.dylib (No such file or directory)
```
See #6219
=> COMP: Fix LibArchive external project install step on macOS

SuperBuild/External_ITK.cmake
This commit is a follow-up of 7da002489 (COMP: Update ITK to fix
packaging of libITKznz and libITKniftiio libraries) where the ITK
SHA is effectively updated to address #6202.
```
$ git shortlog be81e62232..027fd5ce0c --no-merges
BUG: Fix install of libITK(znz|niftiio) libraries specifying component
```
=> COMP: Effectively update ITK version to fix ITKznz & ITKniftiio packaging

Docs/developer_guide/build_instructions/macos.md, SuperBuild/External_LibArchive.cmake
STYLE: Simplify LibArchive external project consolidating options
This commit removes obsolete comment from 2012 originally introduced
in c463d49680 (COMP: switch to newer LibArchive (3.0.4))
Option ENABLE_OPENSSL became redundant following 1f0f6f9b5 (COMP: Explicitly
set LibArchive options to avoid implicit finding of libraries)
Conditional passing of BUILD_TESTING was first introduced in
b50007add3 (COMP: On unix: use LibArchive 2.7.1 patched, on windows:
use LibArchive 2.8.4) and became irrelevant with c463d49680 (COMP:
switch to newer LibArchive (3.0.4))
-----
DOC: Update macOS build instructions removing obsolete LibArchive workaround
Considering that (1) the build instruction section "LibArchive pointing to
a nonexistent path" was added on Feb 2021 by 5dd8e7f71 (DOC: Update macOS …
=> Simplify LibArchive external project and improve associated documentation

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx
Fixes a small issue introduced on #6204
=> BUG: scissors shapeDrawCenteredCheckBox disabling when using rectangle

CMake/SlicerMacroConfigureModuleCxxTestDriver.cmake, SuperBuild/External_VTK.cmake
Addresses issue #5956 
Current:
* [Slicer/VTK@slicer-v9.1.20220125-efbe2afc2](https://github.com/Slicer/VTK/tree/slicer-v9.1.20220125-efbe2afc2) 
Previously associated with this pull request:
* [Slicer/VTK@slicer-v9.1.20211022-1172cdd2e](https://github.com/Slicer/VTK/tree/slicer-v9.1.20211022-1172cdd2e)
* `CMake/SlicerMacroConfigureModuleCxxTestDriver.cmake:` Included `vtkVersionsMacro.h` header in the generated tests to correctly resolve the `VTK_MAJOR_VERSION` and `VTK_MINOR_VERSION` macros. Needs further investigation to determine why it was not required before.
* https://github.com/Slicer/Slicer/pull/6059
* `Libs/MRML/Core/vtkArchive.cxx`: Earlier, call to `vtksys::SystemTools::ChangeDirectory()` returned `int(0)` for success, same as the system call `chdir()`. New changes to VTK now …
=> ENH: Update VTK9 from 9.0.20201111 to 9.1.20220125

Base/QTGUI/qSlicerExportNodeDialog.cxx
It was not possible to focus on the directory ctkPathLineEdit via mouse click.
=> BUG: Fix export directory line edit focus

CMake/SlicerBlockCTKAppLauncherSettings.cmake, CMake/SlicerBlockFindQtAndCheckVersion.cmake
This commit fixes the test and ensures that python modules compiled
on windows and depending on Qt (e.g `vtkRenderingQt`) can be imported
using PythonSlicer when executed from a Slicer build tree.
See #6228
It sets `QT_LIBRARY_DIR` variable and updates the `LibraryPaths`
launcher settings to append `QT_LIBRARY_DIR` on Unix and `QT_BINARY_DIR`
on Windows.
Running these commands on windows now work as expected:
```
cd C:\D\S4R
python-install\bin\PythonSlicer.exe -c "import slicer"
cd C:\D\S4R\Slicer-build
ctest.exe -C Release -R py_standalonepython_import_slicer
```
When configured against Qt4, the variables `QT_PLUGINS_DIR`, `QT_BINARY_DIR`
and `QT_LIBRARY_DIR` were set by the `FindQt4` CMake module.
Considering these variables are not set by the Qt5 modules, following
commit e88cb6649 …
=> BUG: Fix py_standalonepython_import_slicer test on windows

SuperBuild/External_VTK.cmake
This commit is similar to c1a94fc83 that was fixing the same issue
for VTK 9.0.
To ensure the Slicer can run on system where only libGL is available,
this commit updates VTK to make sure setting `OpenGL_GL_PREFERENCE`
to LEGACY works as expected.
For reference, setting to LEGACY value was originally introduced
in 23d8144 (BUG: Fix linux package removing dependency to GLVND
libraries).
```
$ git shortlog  e0d1851e22..fc49db9756 --no-merges
COMP: Remove custom FindOpenGL to ensure OpenGL_GL_PREFERENCE is considered
[Backport MR-8945] COMP: Ensure project depending on VTK link against correct OpenGL libraries
```
=> BUG: Fix linux package ensuring OpenGL_GL_PREFERENCE is considered with VTK9.1

SuperBuild/External_python-dicom-requirements.cmake, SuperBuild/External_python-extension-manager-requirements.cmake, SuperBuild/External_python-extension-manager-ssl-requirements.cmake, SuperBuild/External_python-numpy.cmake, SuperBuild/External_python-pip.cmake, SuperBuild/External_python-requests-requirements.cmake, SuperBuild/External_python-scipy.cmake, SuperBuild/External_python-setuptools.cmake, Utilities/Scripts/python_package_updater.py
This updates python packages to their latest versions. PyGitHub is able to be updated to 1.55, unlike previous times because new dependency PyNaCl has available whl files for the specified release version. Following this update there are no more outdated python packages. I built on Windows and it was successful and ran through full testing with already factory build failing tests being the ones still failing.
```powershell
PS C:\Users\JamesButler\AppData\Local\NA-MIC\Slicer 4.13.0-2022-02-28\bin> ./PythonSlicer.exe "C:\Users\JamesButler\Documents\GitHub\Slicer\Utilities\Scripts\python_package_updater.py"
WARNING: You are using pip version 21.3.1; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Users\JamesButler\AppData\Local\NA-MIC\Slicer …
```
=> Update Python packages to latest March 2022

SuperBuild/External_python.cmake, SuperBuild/External_xz.cmake
This replaces the lzma repository by xz which includes lzma and it is
better maintained.
=> ENH: Replacing lzma v5.2.2 by xz v5.2.5

Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
When the interpolation was different for the previous and new (background or foreground) volume in the slice views when changing, the previous volume display node was set the interpolation value of the new volume display node. It was because of a signal that was emitted when setting the interpolation on the checkbox in the slice view controller, which triggered setting that interpolation value. By adding blockSignals calls this issue is fixed.
Fixes https://github.com/Slicer/Slicer/issues/6240
=> BUG: Fix interpolation reset issue in slice views

Base/Python/slicer/__init__.py
This is related to https://github.com/Slicer/Slicer/commit/542f53c5ba9bf650119707f990e36d74a6c8d36a.
I attempted `import scipy` in the latest Slicer preview 4.13.0-2022-02-28 and the Slicer application would then just hang. This is on my Windows 11 machine so I attempted the same type workaround as https://github.com/Slicer/Slicer/commit/542f53c5ba9bf650119707f990e36d74a6c8d36a and it no longer would cause the application to hang.
An unfortunate side-effect of this workaround is that there is no auto-complete for available methods. `numpy` has nothing show up on `numpy.[tab]` in the python interactor and `scipy` only has `scipy.test()` as an option. If I manually type out some known thing like `scipy.__version__` then it does appropriately print out:
```
>>> scipy.__version__
'1.7.3'
```
=> BUG: Workaround for Slicer hang on scipy import on Windows 11

Docs/developer_guide/build_instructions/windows.md
The factory build machine has been using Visual Studio 2022 and the v143 toolset for the past month as of https://github.com/Slicer/DashboardScripts/commit/7cd961df84997f22bb684d7d2a185a610f23d6a1.
This PR is updating the documentation based on the comment at https://github.com/Slicer/Slicer/pull/6012#issuecomment-983050373 to update it once the factory machines were using VS2022 and the v143 toolset.
=> DOC: Update build instructions to specify using Visual Studio 2022

Base/Python/slicer/ScriptedLoadableModule.py
Missing calls to `super().__init__()` in the `ScriptedLoadableModule` classes break multiple inheritance. The init method is skipped in any derived classes that come after the ScriptedLoadableModule class in the MRO.
Adding super calls to each of the ScriptedLoadableModule classes fixes this issue and correctly supports multiple inheritance.
- `ScriptedLoadableModule.__init__`
- `ScriptedLoadableModuleWidget.__init__`
- `ScriptedLoadableModuleLogic.__init__`
---
For example, this class fails to initialize VTKObservationMixin:
```python
class MyModuleLogic(ScriptedLoadableModuleLogic, VTKObservationMixin):
def __init__(self):
super().__init__()
self.addObserver(...)  # AttributeError on self.Observations
```
_In this case_, swapping the base class order avoids the error as …
=> BUG: Fix broken multiple inheritance in ScriptedLoadableModule classes

SuperBuild/External_LibFFI.cmake
This commit updates the LibFFI external project originally introduced
in 34e48e8aef (ENH: Upgrade from python 3.6.7 to 3.9.10) to also check
if the variables `LibFFI_INCLUDE_DIR` and `LibFFI_LIBRARY` are set.
=> COMP: Update LibFFI external project to accept INCLUDE_DIR and LIBRARY vars

SuperBuild/External_LZMA.cmake, SuperBuild/External_python.cmake
This commit partially reverts d4e7c2fcc (ENH: Replacing lzma v5.2.2 by
xz v5.2.5) to use the name `LZMA` instead of `xz`.
This ensures the project can be configured specifying external built
LZMA library by specifying `LZMA_INCLUDE_DIR` and `LZMA_LIBRARY` variables.
=> COMP: Rename xz external project back to LZMA

SuperBuild/External_VTK.cmake
* Improve build-system support for externally built modules
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8123
* vtk-config: Add find_package hints for OpenVR
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8977
```
$ git shortlog 6a92c520f..0ba7af6306 --no-merges
[Backport MR-8977] vtkInstallCMakePackageHelpers: add find_package hints for OpenVR
[Backport MR-8123] Do not generate files in source tree when building module externally
[Backport MR-8123] vtk_module_build: Update CMake function fixing use of quotes and indentation
[Backport MR-8123] vtk_module_build: Ensure external modules build directory are not overwritten
```
=> COMP: Update VTK to improve support for externally build VTK modules

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsCurveSettingsWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsCurveSettingsWidget.cxx
This pull request removes the surface constraint options from the Markups Resample menu. The surface constraint function has been moved to the Curve Settings menu and was no longer functional from the Resample menu. The issue was discussed in [this thread](https://discourse.slicer.org/t/unexpected-behavior-of-curve-resampling/22188/2).
=> BUG: Remove redundant surface constraint from markups resampling

Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationGeometryLogic.cxx
It will prevent a crash in CalculateOutputGeometryFromBounds if the source geometry is not set.
=> ENH: Improve robustness check in vtkSlicerSegmentationGeometryLogic

Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
In DICOMScalarVolumePluginClass::sliceCornersFromDICOM, the DICOM.instanceUIDs attribute will be empty in this case.
=> BUG: Fix attribute bad access when using a sequence node

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialStorageNode.cxx
This allows `vtkMRMLMarkupsFiducialStorageNode` to be used by markups
defined in external modules (pluggable markups)
=> ENH:Make vtkMRMLMarkupsFiducialStorageNode generic

Docs/user_guide/modules/colors.md, Modules/Loadable/Colors/Logic/vtkSlicerColorLogic.h, Modules/Loadable/Volumes/SubjectHierarchyPlugins/CMakeLists.txt, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.h
The item is visible if slice view has a volume on it, and volume has valid color node and primary display node. Part of the #6111 issue.
Example of the context menu item.
=> ENH: Added a color legend item to the slice view context menu for volumes

Base/QTGUI/qSlicerApplication.cxx
Previous implementation worked only when when mainwindow is deleted after app.
If mainwindow is deleted before app then we get seg fault in destructor.
I.e. we are trying to set parent to destroyed SettingsDialog.
This used to happen with SlicerCAT.
QPointer helps to track the lifetime of a pointer.
So we always know if it is alive.
Steps to reproduce:
1) launch SlicerCAT from command line
1) open `Application settings`
2) close it
3) close application
4) see output to command line
=> BUG: segfault invoked by SettingsDialog deletion

Modules/Scripted/DataProbe/DataProbe.py
The DataProbe magnifier currently has an odd behavior when the mouse approach the corners of the slice views:
This PR uses a 2D canvas with a fixed size and draws the crop imagedata on it at the right position.
=> ENH: improve dataprobe magnifier borders

Libs/MRML/Core/vtkMRMLSegmentationNode.cxx, Libs/MRML/Core/vtkMRMLSegmentationNode.h, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx, Modules/Loadable/Segmentations/MRML/vtkMRMLSegmentEditorNode.cxx, Modules/Loadable/Segmentations/MRML/vtkMRMLSegmentEditorNode.h, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
There were two sets of enums for the same purpose, the set in vtkMRMLSegmentEditorNode marked as deprecated. Now it is removed, and the enums in vtkMRMLSegmentationNode are used everywhere.
=> ENH: Consolidate segmentation masking options

Libs/MRML/Core/vtkMRMLStreamingVolumeNode.cxx
When calling CopyContent, the target ImageConnection was used as the source. This caused problems when adding un-encoded vtkMRMLStreamingVolumeNode to sequences.
=> BUG: Fix imageData content copying in vtkMRMLStreamingVolumeNode

.pre-commit-config.yaml
This commit follows up configuration originally introduced in
pull request #6262 (Update GitHub Actions to leverage pre-commit
hook framework and integrate flake8 hook)
=> COMP: Fix linting by pinning flake8-bugbear used in pre-commit-config

Utilities/Scripts/python_package_updater.py
This commit adds a new option called `--from-installed-packages` allowing
to systematically update all external project independently of their current
status.
Assuming the external project files of a SuperBuild extension include the
relevant `[<package_name>]` hints, they may be updated by:
1. installing the extension specific packages in a dedicated prefix
2. running "python_package_updater" script setting `PYTHONPATH` to account for the custom prefix
For example:
```
SLICER_SOURCE_DIR=~/Projects/Slicer
SLICER_DIR=~/Projects/Slicer-Release/Slicer-build
PYTHONSLICER_EXECUTABLE=${SLICER_DIR}/../python-install/bin/PythonSlicer
EXTENSION_SOURCE_DIR=/home/jcfr/Projects/ShapeVariationAnalyzer
EXTENSION_BINARY_DIR=/home/jcfr/Projects/ShapeVariationAnalyzer-Release
```
``` …
```
=> Improve python_package_updater to support updating extension external project

.git-blame-ignore-revs
This adds some recent commits to the git blame ignore list to help skip over bulk change commits. Let me know if all of these commits are valid for this file, or only if was 100.0% STYLE changes (a few instances include changes to some logic).
=> STYLE: Ignore more bulk changes for git blame

Libs/MRML/Core/vtkMRMLModelStorageNode.h, Modules/Loadable/Segmentations/Resources/UI/qSlicerSegmentationsModule.ui, Modules/Loadable/Segmentations/Widgets/CMakeLists.txt, Modules/Loadable/Segmentations/Widgets/DesignerPlugins/CMakeLists.txt, Modules/Loadable/Segmentations/Widgets/DesignerPlugins/qMRMLSegmentationShow3DButtonPlugin.cxx, Modules/Loadable/Segmentations/Widgets/DesignerPlugins/qMRMLSegmentationShow3DButtonPlugin.h, Modules/Loadable/Segmentations/Widgets/DesignerPlugins/qSlicerSegmentationsModuleWidgetsPlugin.h, Modules/Loadable/Segmentations/Widgets/Resources/UI/qMRMLSegmentEditorWidget.ui, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.h, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationShow3DButton.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationShow3DButton.h, Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.h, Modules/Scripted/SegmentStatistics/SegmentStatistics.py
Display "Show 3D" button in Segmentations module similarly to Segment Editor module.
When a segmentation was loaded and the user did not want to edit the segmentation, only show it in 3D it was not intuitive that the user had to go to Segment Editor module (or click on Create button of Closed surface representation).
Implemented by creating a qMRMLSegmentationShow3DButton widget for showing/hiding the segmentation in 3D.
It is used now in both Segmentations and Segment Editor module and can be used in custom modules, too.
Segmentations (new):
Segment Editor (for reference):
=> Show3d button in segmentations module

Modules/Loadable/Segmentations/Widgets/Resources/UI/qMRMLSegmentEditorWidget.ui, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
- When the new selected segment ID is the same as the old one, the necessary updates were sometimes not called, because the SetSelectedSegmentID method did not trigger updateWidgetFromMRML on the segment editor widget
- Fixed widget base class in ui file to prevent Qt Designer warning
=> BUG: Fix stuck disable state in Segment Editor effect list

Modules/Loadable/Models/Widgets/Resources/UI/qMRMLModelDisplayNodeWidget.ui
Can maybe also delete 
`````
<property name="SingleStep" stdset="0">
<double>0.050000000000000</double>
`````
as duplication.
=> ENH: harmonising slider step sizes in Model module.

Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx, Libs/vtkTeem/vtkTeemNRRDWriter.cxx, Libs/vtkTeem/vtkTeemNRRDWriter.h, Modules/Loadable/Sequences/Testing/Cxx/CMakeLists.txt, Modules/Loadable/Sequences/Testing/Cxx/vtkMRMLSequenceStorageNodeTest1.cxx
When trying to save a volume sequence with a single frame, vtkTeemNRRDWriter raises the following error:
```
[nrrd] nrrdSave:
[nrrd] nrrdWrite: trouble
[nrrd] _nrrdWrite:
[nrrd] nrrdCheck: trouble
[nrrd] _nrrdCheck: trouble with space field
[nrrd] _nrrdFieldCheck_space: trouble
[nrrd] _nrrdFieldCheckSpaceInfo: axis[0] has a direction vector, and so can't have min, max, spacing, or units set
```
This is because the range dimension is omitted by the writer when the size of the first dimension is 1. This results in an error when units are instead assigned to the first spatial dimension.
Fixed by adding an option (vtkTeemNRRDWriter::ForceRangeAxis) to force the writer to include a range axis, even when the size of the first dimension is 1. This option remains disabled by default, and is only …
=> BUG: Fix saving of scalar volume sequence with only one frame

SuperBuild/External_ITK.cmake
This commit updates ITK to avoid false positive like the following
reported when building extension like `SlicerITKUltrasound` bundling
ITK standalone modules like `ITKHigherOrderAccurateGradient` or
`ITKUltrasound`:
```
CMake Warning at D:/D/P/S-0-build/ITK/CMake/ITKModuleExternal.cmake:12 (message):
-- This is needed to allow proper setting of CMAKE_MSVC_RUNTIME_LIBRARY.
-- Do not be surprised if you run into link errors of the style:
CUSTOMBUILD : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_Static' doesn't match value 'MDd_Dynamic' in module.obj [D:\D\P\S-0-E-b\SlicerITKUltrasound-build\ITKHigherOrderAccurateGradient.vcxproj]
cmake_minimum_required must be at least 3.16.3
CMakeLists.txt:7 (include)
```
``` …
```
=> COMP: Update ITK to fix CTest false positive when building ITK standalone module

CMake/SlicerCPack.cmake
=> COMP: Define Slicer icon for package and installed details

SuperBuild/External_curl.cmake
Remove the text saying
```    
the curl cmake build system is poorly maintained. Be aware
```
List of curl changes:
```
$ git shortlog ca5fe8e63..d73e360a7 --no-merges
Daniel Stenberg (1):
[Backport] cmake: remove scary warning
```
=> COMP: Update curl to remove CMake warning related to poorly maintained build-system

Modules/Loadable/Sequences/Testing/Cxx/vtkMRMLSequenceStorageNodeTest1.cxx
Because the remote cache directory was not specified for the scene in vtkMRMLSequenceStorageNodeTest1, attempting to unzip and read the seq.mrb would fail on Linux and Mac as the application would not have permission to write to the directory.
Fixed by setting the remote cache directory to the temporary testing directory.
=> BUG: Fix remote cache directory in vtkMRMLSequenceStorageNodeTest1

Docs/user_guide/modules/index.md, Docs/user_guide/modules/retiredmodules.md, SuperBuild.cmake
In March 2020, the Slicer community decided [^1] to retire the DataStore module and instead store the corresponding data files as GitHub release assets into the Slicer/SlicerDataStore [^2] GitHub project.
In September 2021, the Slicer legacy extensions catalog has been updated[^3] to include the `/midas3/slicerdatastore` and `/midas3/slicerdatastore/user/login` endpoints displaying instructions referencing the GitHub release assets.
Finally, in April 2022, the module was completely removed.
[^1]: https://github.com/Slicer/Slicer/issues/4602
[^2]: https://github.com/Slicer/SlicerDataStore
[^3]: https://github.com/Slicer/Slicer/issues/5845
=> BUG: Retire DataStore module

Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx
Slicer would crash when following this example in the Slicer developer guide documentation.
https://github.com/Slicer/Slicer/blob/a61c805427e9af8cef631ce6e5ff2e297c3a3325/Docs/developer_guide/api.md?plain=1#L49-L56
This was not caught by the Markups widget test because a node is already set to the widget upon customizing the delete all control points action.
https://github.com/Slicer/Slicer/blob/a61c805427e9af8cef631ce6e5ff2e297c3a3325/Modules/Loadable/Markups/Widgets/Testing/Python/MarkupsWidgetsSelfTest.py#L162-L176
=> BUG: Fix Slicer crash upon hiding delete all control points option

Docs/developer_guide/script_repository/gui.md
Based on https://discourse.slicer.org/t/previous-turning-on-individual-slice-intersection-not-working/23183/4.
This updates the example for updating slice intersecting visibility with the currently required force update to see the change. This is to document the current situation until #6338 can be completed.
=> DOC: Include workaround to force visual update of intersecting slices

Base/Python/slicer/util.py, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.h
I noticed this mismatch in the suggestion versus what was actually being used while I was updating some old code to use newer API.
This mismatch of the recommendation versus what is actually used was introduced in https://github.com/Slicer/Slicer/commit/e667de230fb41aca7efa576ebcdeb2621f300aa5.
=> BUG: Fix deprecation warning suggesting method not actually used

Applications/SlicerApp/Testing/Python/CMakeLists.txt, Base/Python/slicer/tests/test_slicer_util_chdir.py, Base/Python/slicer/util.py
This commit implements a non thread-safe context manager to change
the current working directory.
Available in Python 3.11 as ``contextlib.chdir`` and adapted from
https://github.com/python/cpython/pull/28271.
=> ENH: Add slicer.util.chdir context manager

CMakeLists.txt
This commit ensures that re-configuring the inner build accounts for the
`ExternalData_OBJECT_STORES` value stored in the CMake cache.
=> COMP: Ensure ExternalData_OBJECT_STORES cache variable is read

CMakeLists.txt, Utilities/Scripts/SlicerWizard/__version__.py
* Ensure revision displayed during configuration is always correct
This commit is a follow-up of https://github.com/Slicer/Slicer/commit/3814f1af649d63a1737005304b0924a03393446a (`ENH: Use commit count as working copy revision`). It ensures the commit count offset and the revision type are set before displaying revision information during top-level configuration.
|                | Before | After | Command                                 |
|----------------|--------|-------|-----------------------------------------|
| Initial config | 27775  | 30812 |`cmake -U Slicer_WC_COMMIT_COUNT_OFFSET .` |
| Re-config      | 30812  | 30812 |`cmake  .`                                 |
* Generalize logic for specifying additional commit count offsets 
* Begin 5.1.0 development and allocate 250 …
=> Begin 5.1.0 development

CMakeLists.txt
This commit ensures the variable `Slicer_USE_VTK_DEBUG_LEAKS` is propagated to the inner build. 
Doing so ensures `VTK_DEBUG_LEAKS` is properly set and avoids including test like `MRMLCreateNodeByClassWithoutSetReferenceCount` expected to be executed only when `VTK_DEBUG_LEAKS` is `ON`.
=> COMP: Ensure VTK_DEBUG_LEAKS CMake variable is properly set in inner build

Base/QTGUI/qSlicerApplication.cxx
This commit applies a fix similar to acc618074 (BUG: Segfault at application
exit due to SettingsDialog deletion) and fixes a regression likely introduced
in abd2544d4 (BUG: Fixed application window not clickable when popup is
displayed) where the extension manager instance is associated with the
parent window.
See https://discourse.slicer.org/t/help-for-package-testing-on-macos-monterrey-or-bigsur-system/23249
=> BUG: Fix on exit Segfault ensuring ExtensionsManagerDialog is deleted once

Libs/MRML/Core/vtkMRMLLabelMapVolumeNode.cxx, Libs/MRML/Core/vtkMRMLLabelMapVolumeNode.h, Libs/MRML/Core/vtkMRMLVolumeNode.cxx, Libs/MRML/Core/vtkMRMLVolumeNode.h
Hardening a non-linear transform on a labelmap results in a linear interpolation of the labels which is undesired.
Relative to [issue discussed on the forums](https://discourse.slicer.org/t/landmark-registration-transform-resampling/23243)
=> ENH: add nearest neighbor interpolation mode to labelmapvolume

Libs/MRML/Core/vtkMRMLTransformNode.cxx
When loading a scene that contains markups transformed by singleton transform nodes it is possible to enter an infinite loop calling vtkMRMLTransformNode::GetTransformBetweenNodes(). This can happen if a circular loop is created between the transform nodes as their references are being updated.
Fixed by not processing TransformModifiedEvent events in vtkMRMLMarkupsNode during scene import.
=> BUG: Fix infinite loop loading markups node under singleton transforms

Libs/MRML/Core/vtkMRMLColorTableNode.cxx, Libs/MRML/Core/vtkMRMLColorTableNode.h, Libs/MRML/Core/vtkMRMLColorTableStorageNode.cxx
File loading performance is fixed by implementing bulk setting of color values.
Increased maximum number of accepted entries to 1 million as requested in #6354.
Loading of a file with 1 million as the maximum ID takes only a few seconds.
Colors module performance is not great with such huge tables. It takes about 20 seconds
to display a color table with 1 million entries.
fixes #6354
=> ENH: Increase maximum number of colors loaded from colortable files

Modules/Scripted/Endoscopy/Endoscopy.py
the bug was introduced in a258951f473d74f24a93cff95673ea6163a7b5e1, and it's fixed here
corresponding to the Issue:
https://github.com/Slicer/Slicer/issues/6360
=> BUG: vtk_to_numpy function missing in Endoscopy

CMake/FindGit.cmake, CMake/SlicerMacroExtractRepositoryInfo.cmake, Docs/developer_guide/extensions.md
Developers often complained that their extension build failed for some
unknown reason and frequently the issue was that they did not store the
source code in a git repository.
It is good to encourage developers to use best practices, such as version
control, but making the build fail if they build from a non-version-controlled
repository was unnecessarily strong measure.
This commit changes the behavior so that if an extension is built from a
non-git folder then the build succeeds, just a warning is displayed during
project configuration step and `NA` is used as the extension's WC revision.
=> COMP: Do not require building extension from git repository (alternative approach)

SuperBuild/External_VTK.cmake
```
$ git shortlog 684e8a602..efbbf9c02e --no-merges
Ben Boeckel (1):
[Backport] vtkSphericalPointIterator: include `<memory>` for `std::unique_ptr`
```
Rational:
Some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. As such, C++ programs that used standard library components without including the right headers will no longer compile.
The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 11:
(for std::numeric_limits)
(for std::unique_ptr, std::shared_ptr etc.)
(for std::pair, std::tuple_size, std::index_sequence etc.)
(for members of namespace std::this_thread.)
Source: https://gcc.gnu.org/gcc-11/porting_to.html
=> COMP: Update VTK backporting fix for vtkSphericalPointIterator gcc build error

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode_Private.h, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx
Add header `<memory>` for `std::unique_ptr`, see also gcc guide: https://gcc.gnu.org/gcc-11/porting_to.html.
Related https://github.com/Slicer/Slicer/issues/6367 and https://github.com/Slicer/Slicer/pull/6383.
=> COMP: fix building error with gcc 11

Base/Python/slicer/util.py
This commit is a follow up of c47d816c7 (ENH: Skip message boxes when testing)
and 70bb3b2ce (ENH: Refactor message box utility functions)
=> BUG: Improve slicer.util.messageBox() to avoid blocking in testing mode

Libs/MRML/Core/Testing/vtkMRMLCameraNodeTest1.cxx, Libs/MRML/Core/vtkMRMLCameraNode.cxx
This commit is a follow up of e78f557cd (ENH: Simplify view widgets
initialization from view nodes) that originally introduced the
`vtkMRMLCameraNode::GetLayoutName/SetLayoutName`.
It makes sure that the layout name associated with a given camera node
can be set to a different value after it had already been set once.
=> BUG: Ensure vtkMRMLCameraNode layout name can be updated

Modules/Loadable/Colors/qSlicerColorsModuleWidget.cxx, SuperBuild/External_CTK.cmake
Possible fix of the first bug in #6111.
CommonTK PR [#1032](https://github.com/commontk/CTK/pull/1032) must be applied as well.
Drawback: Colour transfer function thumbnail icon and widget representation (ColorNode) isn't updated on the fly. Only if you hover a mouse arrow above it.
Read only for build-in CTF nodes (not editable)
Node is editable after being copied.
=> BUG: Make built-in procedural color nodes (such as PET-DICOM) read only

Base/QTCore/Testing/Cxx/qSlicerUtilsTest1.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h, Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h
When Markups module's control point table was visible it was very slow to add new points after a few hundred points had been added.
Fixes https://github.com/Slicer/Slicer/issues/6379
=> Improve markups control point adding speed

SuperBuild/External_LibArchive.cmake
This commit updates libarchive to fix a macOS build error specific to
debug builds.
For reference, commit libarchive/libarchive@a4c3c90bb (Remove the unused variable detected_bytes) fixes the following build error:
```
/opt/s/LibArchive/libarchive/archive_read_support_format_mtree.c:695:10: error: variable 'detected_bytes' set but not used [-Werror,-Wunused-but-set-variable]
ssize_t detected_bytes = 0, len, nl;
^
1 error generated.
```
```
$ git shortlog 1b2c437b9..6c3301111 --no-merges
AdamKorcz (1):
Add CIFuzz
Alex Richardson (2):
Reduce test_write_format_7zip_large_lzma1 buffer size
Avoid millions of rand() calls() when running tests
Alex Xu (1):
libarchive.3: update archive format list
Alexey Pelykh (1):
Include android_lf.h only for libarchive sources
Brad King (1): …
```
=> Fix macOS build error updating libarchive from 3.5.2 to 3.6.1

Base/QTGUI/qSlicerWebWidget.cxx
Since the script injection associated with `qSlicerWebWidget` was done globally
and only once at the profile level, instantiating first `qSlicerWebWidget`
and then `qSlicerExtensionsInstallWidget` was preventing the customization
done in `qSlicerExtensionsInstallWidget::initializeWebChannelTransport()`
from being effective.
This commit addresses this by injecting the `qwebchannel_appended.js` script
on per page basis. Doing so ensures each `qSlicerWebWidget` (and derived
object like `qSlicerExtensionsInstallWidget`) will inject the expected script.
It follows up on da201359b (ENH: WIP - WebEngine support for
extension manager).
=> Allow multiple qSlicerWebWidget instance by injecting scripts into page

Base/QTGUI/qSlicerWebWidget.cxx
This commit fixes a regression introduced in 9c0ae2ad8 (BUG: Allow multiple
`qSlicerWebWidget` instance injecting scripts into page) where the observation
of the profile `downloadRequested()` signal was done multiple time.
Since the download request is emitted by the default profile observed by
all web widget instances, this change ignores the request if it does not
originate from the page associated with this web widget instance.
=> BUG: Ensure download request are handled by web widget triggering the request

Docs/developer_guide/script_repository/gui.md, Libs/MRML/DisplayableManager/vtkMRMLAbstractWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLAbstractWidget.h, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
Custom event translation can now be specified to make click or click-and-drag set the crosshair position.
=> ENH: Enable new custom mouse gestures for moving crosshair

Base/Python/slicer/ScriptedLoadableModule.py, Base/Python/slicer/tests/test_slicer_util_VTKObservationMixin.py
See my comment here: https://github.com/Slicer/Slicer/pull/6243#issuecomment-1061800718
> > ScriptedLoadableModuleTest cannot be fixed because its base class, unittest.TestCase, [does not have a super call](https://github.com/python/cpython/blob/3.10/Lib/unittest/case.py#L357-L387). For such cases it would still be necessary to explicitly call the mixin initializer.
> 
> > https://docs.python.org/3/library/functions.html#super
> 
> Reading through that documentation more carefully, it seems it _is_ possible to fix the behavior for `ScriptedLoadableModuleTest` as well. @jcfr thanks for posting the link! It helps to read things even if you already know the bulk of it, I learned something new!
> 
> > The object-or-type determines the [method resolution …
=> BUG: Fix broken multiple inheritance in ScriptedLoadableModuleTest 

CMake/SlicerBlockInstallPython.cmake, SuperBuild/python_configure_python_launcher.cmake
This closes #4849, a Slicer 5.1 milestone issue.
In July 2018, PythonSlicer replaced SlicerPython as the primary python executable in https://github.com/Slicer/Slicer/commit/f63a450ba3d4390e422ab9b8902e5d6784d70603 with SlicerPython kept for backwards compatibility.
In April 2020, SlicerPython was marked as obsolete in https://github.com/Slicer/Slicer/commit/d9c5ba6cf5641cdac7289d37b7238d2c1fd741d4 and scheduled for removal.
This commits executes on the removal of SlicerPython.
=> ENH: Remove SlicerPython launcher

CMake/SlicerBlockInstallExternalPythonModules.cmake
This commit updates "SlicerBlockInstallExternalPythonModules"
CMake module fixing the following regression introduced
in b9ac6ed61 (COMP: Remove support for VTK8)
```
CMake Error at CMake/SlicerBlockInstallExternalPythonModules.cmake:16 (endif):
Flow control statements are not properly nested.
CMake/SlicerCPack.cmake:172 (include)
CMake/LastConfigureStep/CMakeLists.txt:44 (include)
```
=> COMP: Fix inner project config removing invalid CMake statement

CMakeLists.txt
Visual Studio 2019 16.11 now has the /std:c++20 switch
https://devblogs.microsoft.com/cppblog/msvc-cpp20-and-the-std-cpp20-switch/
This PR allows the standard to be set to C++20 as an option for testing. C++20 built Slicer on Windows 10 using Visual Studio 2022 with v143 toolset failed in some dependencies such as ITK as C++20 has removed some syntax options that were deprecated in earlier C++ versions. However, this PR allows to begin testing and finding areas where there are incompatibilities.
=> COMP: Allow building with C++20

Docs/developer_guide/build_instructions/linux.md, Docs/user_guide/getting_started.md
Slicer built on CentOS 7 will be available for many Linux distros.
At the time of this commit, Slicer was successfully build, packaged
and ran on:
* Debian 10.12
* Debian 11.3
* Ubuntu 18.04
* Ubuntu 20.04
* Ubuntu 22.04
* Fedora 34
To support running on Debian 10.12, the "Getting Started" section
is also updated to document tricks needed to solve `xinerama` issue.
See https://discourse.slicer.org/t/build-and-package-slicercat-on-manylinux/23443/3
=> DOC: Update build instructions to include CentOS 7

Libs/vtkSegmentationCore/vtkSegmentation.cxx, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py
The segment ID list was called early in vtkSegmentation::RemoveAllSegments, and the segments were thus not properly removed. Besides the memory leak, this caused bugs related to expecting the SegmentRemoved event, such as that the segments were not removed from Subject Hierarchy when using said function.
Fixing segmentation automated test by setting selected segment explicitly, which selection was lost due to now properly removing the segments.
=> BUG: Fix RemoveAllSegments function to actually remove the segments

Base/QTApp/qSlicerApplicationHelper.txx, Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication.h, Base/QTGUI/qSlicerApplication.cxx
This commit ensures that the code path expected to be executed when testing
is enabled is done so when the AA_EnableTesting attribute is set and not
only when the command line parameter "--testing-enabled" is passed.
This allows to programmatically enable testing in test without having to
explicitly pass the argument.
=> ENH: Improve robustness of condition check if testing is enabled

Docs/developer_guide/build_instructions/linux.md
This commit is a follow up of 192af076d3 (DOC: Update build
instructions to include CentOS 7).
There were two lines having a similar meaning.
=> DOC: Improve Centos 7 build instructions

Base/QTCore/Testing/Cxx/qSlicerExtensionsManagerModelTest.cxx, Base/QTCore/qSlicerExtensionsManagerModel.cxx, Base/QTCore/qSlicerExtensionsManagerModel.h
QSignalSpy is intended for testing, therefore use qRestAPI's synchronous query instead to get extensions metadata from the server.
To simplify the implementation of synchronous query, extension metadata is now always downloaded using a single query (by specifying `limit=0` query parameter).
see #6437
=> ENH: Do not use QSignalSpy in qSlicerExtensionsManagerModel

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx
Previous versions of Slicer used the previous "master" branch name to identify the schema.
After rename, old files no longer matched the regex since the branch name was changed, and the urls were no longer lower case.
Fixed by allowing either branch name in the regex and forcing the comparison to be done in lower case.
=> BUG: Fix loading of markups json from previous versions of Slicer

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx
Prior to recent changes, Slicer expected a specific schema url, which is different from the one that is currently used.
- Slicer <= 5.0.2:
https://raw.githubusercontent.com/slicer/slicer/master/Modules/Loadable/Markups/Resources/Schema/markups-schema-v1.0.3.json#"
- Current version of Slicer:
https://raw.githubusercontent.com/slicer/slicer/main/modules/loadable/markups/resources/schema/markups-schema-v1.0.3.json#
Fixed compatibility issues by using the old url. In the future, we will update the schema url to reflect the current version of Slicer.
This commit also relaxes the regex url validation to only check the filename and ignore the rest of the url.
=> BUG: Fix compatibility of Markups JSON with Slicer < 5.1

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIWidget.cxx
In some camera positions the behaviour of the interaction handles is incorrect.
Fixed by ensuring that the reference position is not specified when calculating the last world position using vtkPointPlacer::ComputeWorldPosition.
Re #6459
=> BUG: Fix issue with invalid markup handle interaction

Utilities/Scripts/SlicerWizard/__version__.py.in
This commit ensures that configuring the project doesn't introduce
local changes by accounting for style change introduced
in 9390be6bf (STYLE: Update python code with indentation fixes)
=> COMP: Update SlicerWizard version template to ensure indent is consistent

requirements-docs.txt
This commit workarounds backward incompatible change introduced in
Markdown 3.4 through Python-Markdown/markdown@659a43659 (Update th/td
to use style attribute)
It addresses error like the following:
```
Extension error (sphinx_markdown_tables):
Handler <function process_tables at 0x7f12fd69dc20> for event 'source-read' threw an exception (exception: __init__() missing 1 required positional argument: 'config')
```
See https://github.com/ryanfox/sphinx-markdown-tables/issues/36
and https://python-markdown.github.io/change_log/release-3.4/
The current approach depends on a change associated with branch called `markdown-patch` and available in a fork maintained by @Dzordzu at https://github.com/Dzordzu/sphinx-markdown-tables/tree/markdown-patch and contributed through …
=> COMP: Fix sphinx documentation build due to breaking change in markdown

CODE_OF_CONDUCT.md
While reviewing project metrics for a grant application we realized that although we have a common agreement about how to conduct operations in the Slicer community, we do not have a formalized document to describe it.
The Contributor Covenant is a short and clear description that captures well how we operate, so we propose to adopt this as code of conduct document.
The only customization that is made is the contact information: "...reported to the community leaders listed
[here](https://github.com/Slicer/Slicer/blob/master/CONTRIBUTING.md#benevolent-dictators-for-life)
via private message on the [Slicer forum](https://discourse.slicer.org)."
=> ENH: Add code of conduct document

Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx, Modules/Loadable/VolumeRendering/Widgets/qSlicerVolumeRenderingModuleWidget.cxx
Multi-volume rendering quality was always quite low because always "adaptive" rendering mode was used (regardless of what was set in the GUI) and the sampling distance was not computed correctly.
fixes #5238
fixes #5312
=> BUG: Fix sampling distance computation for multi-volume rendering

Base/QTCore/qSlicerCoreIOManager.cxx, Libs/MRML/Core/vtkArchive.cxx
When a zip file was attempted to be written into a read-only folder then Slicer crashed.
Some errors were not captured when writing zip files.
Fixed by adding more checks during zip archive writing.
fixes #6470
=> Make zip file saving more robust

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
Signal currentItemChanged was emitted by qMRMLSubjectHierarchyComboBox even if
the same item was selected.
=> BUG: Fix wrong signal emitted by SubjectHierarchy if same item is selected

Base/QTCLI/qSlicerCLIModuleUIHelper.cxx, Libs/MRML/Core/vtkMRMLSequenceNode.cxx, Libs/MRML/Core/vtkMRMLSequenceNode.h, Modules/CLI/ExecutionModelTour/ExecutionModelTour.xml
If an input `image` parameter's `type` is set to "dynamic-contrast-enhanced", "signal", or "multichannel" then the generated node selector allows selection of `vtkMRMLSequenceNode` node that contains `vtkMRMLScalarVolume` nodes in it.
This is useful for allowing running CLI modules such as [PkModeling](https://github.com/QIICR/PkModeling/blob/master/CLI/PkModeling.xml) on volume sequences.
=> ENH: Allow selecting volume sequence nodes as CLI module input

CITATION.cff
This add visibility to how to cite Slicer from the GitHub repository by the addition of a CITATION.cff file. This would be in addition to what is stated at https://slicer.readthedocs.io/en/latest/user_guide/about.html#how-to-cite.
Resources about CITATION.cff
- https://github.blog/2021-08-19-enhanced-support-citations-github/
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
- https://citation-file-format.github.io/
- https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionsreferenceend
I've added the file to my default branch at https://github.com/jamesobutler/Slicer so you can see how it looks.
=> DOC: Add citation

Modules/Loadable/Segmentations/Widgets/Resources/UI/qMRMLSegmentEditorWidget.ui
This commit fixes a regression introduced in 1b94b0d53 (ENH: Improve Segment Editor widget layout)
It restores the object name from `Form` to `SegmentsTableResizableFrame`.
Using an explicit widget name is relevant in the context of prototyping and/or custom application development.
Additionally, it adds the missing `customwidget` definition associated with the `ctkMenuButton` custom widget. Sew https://doc.qt.io/qt-5/designer-creating-custom-widgets.html
=> Restore widget name in qMRMLSegmentEditorWidget

.git-blame-ignore-revs
Similar to #6498, but with the appropriate git hashes for the commits on the `5.0` branch.
=> STYLE: Add recent python formatting to ignored list for git blame (5.0)

.git-blame-ignore-revs
This adds a few of the recent python formatting commits to the git blame ignore list.
=> STYLE: Add recent python formatting to ignored list for git blame

Docs/conf.py
This commit adds a javascript redirect to handle the redirection of page
like https://slicer.readthedocs.io/en/v5.0 to https://slicer.readthedocs.io/en/v5.0/
and workaround limitation documented in https://github.com/readthedocs/readthedocs.org/issues/9507
Indeed, despite of adding the following "Exact Redirect" to the readthedocs
configuration:
```
/en/v5.0 -> /en/5.0
/en/v5.0/$rest -> /en/5.0/
```
, specifying https://slicer.readthedocs.io/en/v5.0 doesn't redirect to
https://slicer.readthedocs.io/en/5.0
=> BUG: Update sphinx custom 404 page to handle redirect of vX.Y URL without slash

Libs/vtkSegmentationCore/CMakeLists.txt, Libs/vtkSegmentationCore/Testing/vtkSegmentationConverterTest1.cxx, Libs/vtkSegmentationCore/vtkBinaryLabelmapToClosedSurfaceConversionRule.cxx, Libs/vtkSegmentationCore/vtkClosedSurfaceToBinaryLabelmapConversionRule.cxx, Libs/vtkSegmentationCore/vtkFractionalLabelmapToClosedSurfaceConversionRule.cxx, Libs/vtkSegmentationCore/vtkSegmentation.cxx, Libs/vtkSegmentationCore/vtkSegmentation.h, Libs/vtkSegmentationCore/vtkSegmentationConversionParameters.cxx, Libs/vtkSegmentationCore/vtkSegmentationConversionParameters.h, Libs/vtkSegmentationCore/vtkSegmentationConversionPath.cxx, Libs/vtkSegmentationCore/vtkSegmentationConversionPath.h, Libs/vtkSegmentationCore/vtkSegmentationConverter.cxx, Libs/vtkSegmentationCore/vtkSegmentationConverter.h, Libs/vtkSegmentationCore/vtkSegmentationConverterRule.cxx, Libs/vtkSegmentationCore/vtkSegmentationConverterRule.h, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest1.py, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationConversionParametersWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationConversionParametersWidget.h, Modules/Loadable/Volumes/qSlicerVolumesReader.cxx
Previously, complex STL containers were used that were not Python-wrappable. Now conversion paths and parameters are all VTK objects.
This allows converting segmentations using a custom path, when there are multiple conversion paths are available.
For example, multiple conversion paths are available after installing SlicerRT extension, which provides additional segment representations and conversion rules.
=> ENH: Expose segment conversion paths in Python

Base/QTApp/qSlicerMainWindow.cxx, Base/QTApp/qSlicerMainWindow.h, Base/QTApp/qSlicerMainWindow_p.h, Base/QTGUI/Resources/UI/qSlicerSettingsModulesPanel.ui, Base/QTGUI/qSlicerApplication.cxx, Base/QTGUI/qSlicerModuleFactoryFilterModel.cxx, Base/QTGUI/qSlicerSettingsModulesPanel.cxx, Base/QTGUI/qSlicerSettingsModulesPanel.h
Favorite modules (in Application settings / Modules) can now be reordered by drag-and-drop.
When a module is drag-and-dropped into the favorite list, the drop position is used (instead of adding the module to the end of the list).
Adding/removing/reordering a module shortcut takes effect immediately (no need to restart the application).
fixes #6511
fixes #6510
=> ENH: Reorder favorite modules by drag-and-drop

Base/Logic/vtkSlicerApplicationLogicRequests.h, Libs/MRML/CLI/vtkMRMLCommandLineModuleNode.cxx, Libs/MRML/Core/Testing/vtkMRMLVolumeNodeTest1.cxx, Libs/MRML/Core/vtkArchive.cxx, Libs/MRML/Core/vtkDataFileFormatHelper.cxx, Libs/MRML/Core/vtkMRMLNRRDStorageNode.cxx, Libs/MRML/Core/vtkMRMLSubjectHierarchyLegacyNode.cxx, Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx, Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx, Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx, Libs/MRML/IDImageIO/itkMRMLIDImageIO.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Widgets/qMRMLPlotViewControllerWidget.cxx, Libs/vtkTeem/vtkTeemNRRDWriter.cxx, Modules/CLI/OrientScalarVolume/OrientScalarVolume.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Plots/Widgets/qMRMLPlotChartPropertiesWidget.cxx, Modules/Loadable/Sequences/qSlicerSequencesModuleWidget.cxx, Modules/Loadable/ViewControllers/qSlicerViewControllersModuleWidget.cxx, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx
Simplified code by using the arrow operator, instead of using
parentheses, asterisk and dot operators.
Did so by replacing the regular expression `\(\*(\w+)\)\.` with `->`,
followed by a few manual fixes.
```
find . \( -iname "*.cxx" -or -iname "*.hxx" -or -iname "*.h" \) -exec perl -pi -w -e 's/\(\*(\w+)\)\./->/g' {} \;
```
=> STYLE: Replace (*p).member with p->member

Base/QTGUI/qSlicerApplication.cxx, Base/QTGUI/qSlicerExtensionsLocalWidget.cxx, Base/QTGUI/qSlicerExtensionsManagerDialog.cxx, Base/QTGUI/qSlicerExtensionsManagerDialog.h, Base/QTGUI/qSlicerExtensionsManagerWidget.cxx, Base/QTGUI/qSlicerExtensionsManagerWidget.h
When an extension update is available then a link is added to the extension description to list all the changes between the installed and current version (if the repository is hosted on github and version information is available).
When the user clicks the link then the change log is displayed in the default browser:
=> ENH: Display git diff when extension update is available

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx
Previously GetRASBounds did not take the scaled "world" size of the ROI into account when calculating axis-aligned RAS bounds. Fixed by using the GetSizeWorld method to get the size of the ROI in world coordinates.
Fix #6523
=> BUG: Fix vtkMRMLMarkupsROINode::GetRASBounds not accounting for scaling

Docs/user_guide/modules/segmenteditor.md, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorHollowEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorMarginEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorSmoothingEffect.py, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx
The "Apply to all segments" label was misleading, since enabling it caused the scissors effect to only apply on all visible segments.
Changed label from "Apply to all segments" to "Apply to visible segments".
See: https://discourse.slicer.org/t/erase-using-a-segment-as-only-editable-area/20519/13
=> ENH: Update scissors "Apply to visible segments" label

Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManagerHelper.cxx
In some cases, when the creation of the markups widget triggers modified event on the markups node, in a recursive call of vtkMRMLMarkupsDisplayableManagerHelper::AddDisplayNode, a second representation is created, which then will be orphaned, because the map MarkupsDisplayNodesToWidgets will point only to the first one. This causes problems in the form of duplicate, stuck actors. Solved by not allowing modified events to be handled until the creation of the widget is finished.
=> BUG: Prevent creation of duplicate markup representations

SuperBuild/External_ITK.cmake, SuperBuild/External_SimpleITK.cmake
It has been almost 5 months since the base version of ITK that Slicer uses has been updated. This PR updates to use a recent ITK version to help test prior to ITK officially tagging version 5.3.0 (cc: @dzenanz). 
The Slicer fork of ITK has maintained one custom commit in https://github.com/Slicer/ITK/commit/027fd5ce0c7044c33eb56bf7530466488109390b to fix an issue on the Linux platform. @dzenanz can you take a look to see if this commit is valid as an upstream fix or if a different handling of the issue is better than the revert made in the Slicer commit? 
The most recent SimpleITK release candidate is also being used here for compatibility with latest ITK (cc: @blowekamp).
From my testing on the Windows platform, there were no build errors or testing errors introduced with this update to …
=> COMP: Update ITK to post-v5.3rc04 version and SimpleITK to post-v2.2.0 

Base/QTApp/qSlicerMainWindow.cxx, Base/QTApp/qSlicerMainWindow_p.h
qSlicerMainWindow destructor crashed when a custom widget was used as CentralWidget (not the layout manager).
fixes #6522
=> BUG: Make main window destruction more robust

Modules/Scripted/WebServer/CMakeLists.txt, Modules/Scripted/WebServer/Resources/docroot/db.html, Modules/Scripted/WebServer/Resources/docroot/index.html, Modules/Scripted/WebServer/Resources/docroot/package.json, Modules/Scripted/WebServer/WebServer.py, Modules/Scripted/WebServer/WebServerLib/DICOMRequestHandler.py
Fixed incorrect reading of logging flags from settings (logging was always enabled). Fixed study list loading for cases when optional DICOM fields were not present.
Added OHIF viewer to Web Server API examples.
=> BUG: Make Web Server module DICOMweb endpoint more robust

.github/workflows/ci.yml, .github/workflows/lint.yml
The `master` branch was renamed to `main` on June 23rd 2022. https://discourse.slicer.org/t/slicer-to-use-more-inclusive-language-in-code/23972/4
=> COMP: Fix workflows not running on pushed commits on main branch

SuperBuild/External_ITK.cmake
Nifti with different spacing in sform and qform are now allowed. Qform is used.
git shortlog 05adf2d..62eb5ca
Bradley Lowekamp (1):
Merge branch 'upstream-GoogleTest'
Dave Chen (1):
DOC: Fixed Midas Journal link to use HTTPS
Dženan Zukić (4):
COMP: Fix build with ITK_USE_SYSTEM_HDF5=ON
Merge pull request 3615 from blowekamp/UpdateGoogleTest
ENH: Add a test for different spacing in NIFTI's qform and sform
STYLE: Make NIFTI test CMakeLists.txt more readable
GoogleTest Upstream (1):
GoogleTest 2022-06-27 (58d77fa8)
Jon Haitz Legarreta Gorroño (37):
BUG: Fix Superclass name in RTTI macro
STYLE: Use the superclass name in itkTypeMacro
COMP: Remove duplicate include file
STYLE: Conform to ITK style in variable naming in tests
STYLE: Prefer using exception checking macros in tests
ENH: Add …
=> ENH: Update ITK to allow opening a wider range of NIFTI files

Base/QTApp/qSlicerAboutDialog.cxx, Base/QTCore/qSlicerApplicationUpdateManager.cxx, Modules/Loadable/SlicerWelcome/Resources/UI/qSlicerWelcomeModuleWidget.ui
If application update is found then display the available version number and link to the download page. If no application update is found then do not display link to download page.
Clarify partially checked meaning in "automatic" update check button.
See discussion: https://discourse.slicer.org/t/stable-update-notification/23655/22
=> ENH: Display available application version in "About" box

Libs/MRML/Widgets/qMRMLViewControllerBar.cxx, Libs/MRML/Widgets/qMRMLViewControllerBar.h, Libs/MRML/Widgets/qMRMLViewControllerBar_p.h
In custom apps usually it is easy to simply find unwanted toolbar elements by object name and hide it. However, in the case of the maximize view button, it is automatically shown if the view can be maximized, which makes it reappear in the custom apps. It is possible to remove it from the layout but it does not work properly in all cases. By adding such an option it is possible to hide it appropriately.
=> ENH: Add option to hide the maximize view button

requirements-docs.txt
Fix was integrated into the official release (https://github.com/ryanfox/sphinx-markdown-tables/issues/36), use that instead of a private patch version (which is no longer available).
=> DOC: Remove sphinx-markdown-tables workaround

Modules/Loadable/Markups/qSlicerMarkupsWriter.cxx
qSlicerMarkupsWriter was explicitly setting the markups storage node to use vtkMRMLMarkupsJsonStorageNode for writing markups to json. Since some markup types used other storage nodes (ex. vtkMRMLMarkupsROIJsonStorageNode), this caused an issue when trying to save those node types.
See: https://discourse.slicer.org/t/markups-roi-cannot-be-loaded-from-json-file/25430
=> BUG: Ensure default JSON storage node is used in qSlicerMarkupsWriter

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx
When the size of the plane was changed, the area measurement was not updated. Fixed by calling UpdateAllMeasurements() when SetSize or SetPlaneBounds is called.
=> BUG: Fix plane area measurement not updating

Docs/developer_guide/script_repository/gui.md, Libs/MRML/Core/vtkMRMLViewNode.cxx, Libs/MRML/Core/vtkMRMLViewNode.h, Libs/MRML/DisplayableManager/vtkMRMLViewDisplayableManager.cxx, Libs/MRML/Logic/vtkMRMLViewLinkLogic.cxx, Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx, Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.h
Box in 3D view is an actor controlled by vtkMRMLViewDisplayableManager.
This manager also controls the renderer background color as well.
Thus it was pretty easy to introduce this feature in the same way.
`vtkMRMLViewNode` now have attribute `double BoxColor[3]`.
User is able to modify box color through vtkMRMLViewNode::SetBoxColor().
Probably it would be good to add the example to [Slicer script repository](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#change-3d-view-background-color):
```python
viewNode = slicer.app.layoutManager().threeDWidget(0).mrmlViewNode()
viewNode.SetBoxColor(1,0,0)
```
=> ENH: customizable Box Color in 3D view

Modules/Scripted/VectorToScalarVolume/CMakeLists.txt, Modules/Scripted/VectorToScalarVolume/Resources/Icons/VectorToScalarVolume.svg, Modules/Scripted/VectorToScalarVolume/Resources/UI/VectorToScalarVolume.ui, Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py
When scene was closed or the module was reloaded then the module threw exceptions. Fixed by updating the module to use the latest scripted module template.
Average computation was not correct for integer volumes. For example for a volume containing 30, 50, 100 in 3 channels the average is 60 but it was computed to be 59 (due to casting to int). Fixed by rounding of the average computation result instead of just casting the floating-point value.
fixes #6478
=> BUG: Minor VectorToScalarVolume module improvements

Docs/developer_guide/script_repository/gui.md, Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx
Color legend is to be shown in 3D view for volumes that are shown in slice views, that are visible in the 3D view. Part of #6111 issue.
Single color bar in 3D.
Multiple color bars in 3D.
=> ENH: Color legend is to be shown for slice view, visible in the 3D view

Modules/Loadable/Annotations/MRMLDM/vtkMRMLAnnotationDisplayableManagerHelper.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.h, SuperBuild.cmake, SuperBuild/External_CTK.cmake, SuperBuild/External_VTK.cmake
To minimize changes prior to Slicer 5.2 release, this pull request attempts to backport the minimum set of VTK commits allowing to integrate OpenXR and OpenXRRemoting update.
=> Update VTK, vtkAdon and CTK to backport OpenXR and OpenXRRemoting updates 

SuperBuild.cmake
This commit fixes a regression introduced in previous commit by updating `vtkSlicerDynamicModelerSelectByPointsTool` to use updated `vtkThreshold` API.
List of SlicerSurfaceToolbox changes:
```
$ git shortlog 3515c3cca..74af7b5ab --no-merges
Jean-Christophe Fillion-Robin (3):
COMP: Fix -Wdeprecated-copy in Simplify.h reported with gcc 9.x
DOC: Add module documentation
COMP: Remove use of deprecated vtkThreshold API
```
=> COMP: Update SlicerSurfaceToolbox to fix build error introduced by VTK update

SuperBuild/External_SimpleITK.cmake
This commit fixes a regression introduced in 4d1c98ef8 (COMP: Update ITK to post-v5.3rc04 version and SimpleITK to post-v2.2.0) where SimpleITK installation method was changed to use "pip install" instead of "setup.py".
See discussion at https://discourse.slicer.org/t/windows-nightly-build-error-pip-install-of-simpleitk-build-failing/25629
Since by default the project "python-ensurepip" leads to the installation of pip 21.2.4, SimpleITK was installed using a version of pip older than 21.3 and didn't have the "in-tree-build" feature enabled by default.
To address the problem, this commit adds the dependency to the python-pip project and ensures that pip >= 21.3 is used.
=> COMP: Fix SimpleITK installation ensuring its uses newer version of pip

Libs/ITKFactoryRegistration/itkFactoryRegistration.h, Libs/vtkITK/vtkITK.h, Libs/vtkITK/vtkITKArchetypeDiffusionTensorImageReaderFile.cxx, Libs/vtkITK/vtkITKArchetypeDiffusionTensorImageReaderFile.h, Libs/vtkITK/vtkITKArchetypeImageSeriesScalarReader.cxx, Libs/vtkITK/vtkITKArchetypeImageSeriesScalarReader.h, Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderFile.cxx, Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderFile.h, Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderSeries.cxx, Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderSeries.h, SuperBuild/External_ITK.cmake, SuperBuild/External_SimpleITK.cmake
* `metroplex` (linux) :heavy_check_mark:
* `computron` (macOS) :hourglass_flowing_sand:
* _The clang compiled has been failing with segfault. Factory has been restarted and build re-triggered_
* `factory-south-macos` (macOS) :heavy_check_mark: : 
* `overload` (Windows) :heavy_check_mark: 
* `metroplex` (linux) :hourglass_flowing_sand:
* `computron` (macOS) :hourglass_flowing_sand:
* `factory-south-macos` (macOS) :hourglass_flowing_sand:
* `overload` (Windows)
_To avoid modifying the local Slicer environment, ITK wheels can be installed in a dedicated prefix_
```bash
itk_wheels_install_prefix=/home/jcfr/Downloads/itk-wheels-installed
echo "itk_wheels_install_prefix [${itk_wheels_install_prefix}]"
mkdir -p $itk_wheels_install_prefix
config=RelWithDebInfo …
```
=> Support itk python module switching to custom itk namespace

Modules/Loadable/Markups/Widgets/qMRMLMarkupsCurveSettingsWidget.cxx
The number of segments when resampling a curve was "number of given points - 1", which is fine for open curves, but for closed curves it has to be just the number of given points. Added a simple fix in the widget function.
=> BUG: Fix bug in closed curve resampling

Base/QTGUI/qSlicerMouseModeToolBar.cxx
It can be assumed that when the user wants to change the mode of the window/level mouse mode, they also want to use it right afterwards. Thus, it makes sense to activate it along with setting the mode, to save extra clicks and possible confusion.
=> ENH: When setting window/level mode also activate it

SuperBuild/External_bzip2.cmake
* Fix `-Wmaybe-uninitialized` warnings
* Fix handling of large (> 4GB) files on Windows.
* Fix undefined behavior in the macros `SET_BH`, `CLEAR_BH`, & `ISSET_BH`
* Make sure nSelectors is not out of range ([CVE-2019-12900](https://nvd.nist.gov/vuln/detail/cve-2019-12900))
* Accept as many selectors as the file format allows. This relaxes the fix for [CVE-2019-12900](https://nvd.nist.gov/vuln/detail/cve-2019-12900) from 1.0.7 so that bzip2 allows decompression of bz2 files that use (too) many selectors again.
=> ENH: Update bzip2 from version 1.0.6 (Sept 2010) to 1.0.8 (July 2019)

SuperBuild/External_SimpleITK.cmake
This commit is a follow-up of 8f67453b0b (ENH: Add support for importing "itk" from python wheels installed from PyPI)
List of SimpleITK changes:
```
$ git shortlog c7f15141..48cddfb0 --no-merges
COMP: Simplify and fix handling of custom "itk" namespace
```
=> COMP: Update SimpleITK to simplify handling of custom itk namespace

Base/QTGUI/qSlicerActionsDialog.cxx, Base/QTGUI/qSlicerModuleFinderDialog.cxx, CMake/SlicerBlockCTKAppLauncherSettings.cmake, Docs/user_guide/extensions_manager.md, Docs/user_guide/getting_started.md, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.cxx
In the [3D Slicer in My Language](https://chanzuckerberg.com/eoss/proposals/3d-slicer-in-my-language-internationalization-and-usability-improvements/) project, we use the _QT **lupdate** tool_ to extract traductible strings. However, when we run that tool on the [current source code](https://github.com/Slicer/Slicer), we note the presence of some warnings that may affect the translation quality. 
This commit fixes the `cannot invoke tr() like this` warning that is related to _tr function calls_ on private classes. 
More details in this issue can be found [here](https://github.com/mhdiop/Sliceriml/issues/1).
CC: @lassoan @pieper
=> Fix lupdate warnings related to tr function calls on private classes

SuperBuild/External_ITK.cmake
GrowCut remote module in ITK has recently been updated to mirror Slicer's improvements. This PR contains pre-requisites to removing this code from Slicer and refactoring it to use the version coming from ITK.
I have not begun the Slicer refactoring, and I would prefer if somebody else did that. I could support them by making changes inside `ITKGrowCut`.
=> Enable GrowCut remote module in ITK

SuperBuild/External_VTK.cmake
See https://github.com/KitwareMedical/SlicerVirtualReality/issues/91
Copied from "Fix projection matrix computation in VR" commit:
> Fix all mappers that use the VCDC matrix, e.g. GPUVolume, PointGaussian;
>
> The VCDC matrix must be transposed before being sent to the GPU.
> Also make sure that GetKeyMatrices is idempotent, and remove useless calls
> to it.
$ git shortlog 73ca81bb4..97a187572 --no-merges
Lucas Gandel (1):
[Backport MR-9620] Fix projection matrix computation in VR
Co-authored-by: Lucas Gandel <lucas.gandel@kitware.com>
=> BUG: Update VTK to include OpenVR/OpenXR volume rendering fix

CMake/SlicerDashboardDriverScript.cmake
This commit includes a new check based on the `run_ctest_submit` variable when submitting `PARTS build`. Without this fix, you could try to disable submission to dashboard but the build information will still appear submitted.
This commit modifies the logic of the script to decouple the building of the Slicer package and its upload. This is to support cases where the Slicer package needs to be built, but won't be uploaded. Not having this in place forces the generated package to be uploaded.
=> ENH: Fix use of run_ctest_ variables

Base/Python/slicer/slicerqt.py, Base/QTGUI/Resources/UI/qSlicerSettingsPythonPanel.ui, Base/QTGUI/qSlicerApplication.cxx, Base/QTGUI/qSlicerApplication.h, Base/QTGUI/qSlicerSettingsPythonPanel.cxx, Base/QTGUI/qSlicerSettingsPythonPanel.h
The motivation of this change is to improve user experience when viewing the Error Log Dialog and the slicer log as seen in the Report A Bug Dialog.  When there are, for example, 3 errors and 3 warnings, the user will see 3 errors and 3 warnings.  This is instead of 6 errors and 6 warnings where half were indicated from python and the other half were indicated from the stream.
This proposed change only shows python logging output in the console stream while in Developer Mode. For regular users not in developer mode they will no longer see double python logging (one from python and one from the stream).  
Developers will still have the double logging, but this appears to be desired behavior as they want knowledge of everything from the console stream in addition to everything from the …
=> BUG: Fix duplicate python logging messages in the log for regular users

Base/QTGUI/qSlicerExtensionsLocalWidget.cxx, Modules/Loadable/Colors/Widgets/qMRMLColorLegendDisplayNodeWidget.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyOpacityPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyRegisterPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx, Modules/Loadable/VolumeRendering/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumeRenderingPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx
In the [3D Slicer in My Language](https://chanzuckerberg.com/eoss/proposals/3d-slicer-in-my-language-internationalization-and-usability-improvements/) project, we use the QT _lupdate_ tool to extract traductible strings. However, when we run that tool on the [current source code](https://github.com/Slicer/Slicer), we note the presence of some warnings that may affect the translation quality.
This commit fixes the `Class 'SomeClassName' lacks Q_OBJECT macro` warning that is related to tr function calls on classes with no Q_OBJET macro declaration.
More details in this issue can be found [here](https://github.com/mhdiop/Sliceriml/issues/1).
@lassoan As discussed during the meeting, the Q_OBJECT macro introduced in `Base/QTGUI/qSlicerExtensionsLocalWidget.cxx` is still causing a compilation …
=> BUG: Fix lupdate warnings related to missing Q_OBJECT macro

Base/QTGUI/qSlicerSettingsGeneralPanel.cxx
This appears to have been a typo introduced in https://github.com/Slicer/Slicer/commit/3ce46788cde6d74167cd5bb7639855dc1e59401e
I ran into this issue while testing https://github.com/KitwareMedical/SlicerCustomAppTemplate/pull/43 where I had `Slicer_BUILD_APPLICATIONUPDATE_SUPPORT` set to `OFF` and `Slicer_BUILD_I18N_SUPPORT` set to `ON`.
=> COMP: Fix build error for Application Update off and I18N on

.github/workflows/lint.yml
This fixes some warnings observed in GitHub actions runs such as the one observed in https://github.com/Slicer/Slicer/actions/runs/3274861579.
=> Update GitHub actions to avoid deprecations

Applications/SlicerApp/Testing/Python/CLISerializationTest.py, Base/Python/slicer/ScriptedLoadableModule.py, Base/Python/slicer/util.py, Modules/Scripted/DICOMPlugins/DICOMEnhancedUSVolumePlugin.py, Modules/Scripted/DataProbe/DataProbe.py, Modules/Scripted/ImportItkSnapLabel/ImportItkSnapLabel.py, Modules/Scripted/WebServer/WebServer.py, Modules/Scripted/WebServer/WebServerLib/DICOMRequestHandler.py, Modules/Scripted/WebServer/WebServerLib/SlicerRequestHandler.py, Modules/Scripted/WebServer/WebServerLib/StaticPagesRequestHandler.py, Utilities/Scripts/genqrc.py
<s>This continually enforces changes made in https://github.com/Slicer/Slicer/commit/4483cc0e6f288b0816b6329f1829d9ef8c5aa81a and https://github.com/Slicer/Slicer/commit/1a85ebabd543907072c72c34247aae849489d33b.
Changes were applied automatically by running:
pre_commit run --all-files</s>
---------
**EDIT**
Similarly to 1a85eba (introduced through PR #6132) and 4483cc0 (introduced through PR #5625), this PR uses [`pyupgrade`](https://github.com/asottile/pyupgrade) to also automatically upgrade python syntax.
- Install: `PythonSlicer -m pip install pyupgrade`
- Running:
- On 1 file: `PythonSlicer -m pyupgrade --py39-plus MyPythonFile.py`
- On multiple files, there are few options:
- on unix system:
```
PythonSlicer -m pyupgrade --py39-plus $(find . -type f -name "*.py")
```
- on any …
=> Upgrade python syntax to 3.9 and newer

Base/QTCore/Testing/Cxx/qSlicerSslTest.cxx, Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreApplication.h, Libs/MRML/Logic/vtkMRMLRemoteIOLogic.cxx, Libs/MRML/Logic/vtkMRMLRemoteIOLogic.h, Libs/RemoteIO/vtkHTTPHandler.cxx, Libs/RemoteIO/vtkHTTPHandler.h
It allows referring to files hosted on https servers in the MRML scene.
May be useful to distribute scene files with remote data - see https://discourse.slicer.org/t/embedding-uri-in-a-mrml-scene-file-for-viewing-the-mrml-scene-on-a-remote-slicer-application/25373/9
=> ENH: Add https support to vtkHTTPHandler

.github/workflows/commit-message.yml, Docs/developer_guide/style_guide.md
This replaces the usage of https://github.com/marketplace/commitcheck which has been unreliable at times and also difficult to see what is required to pass a failing check. I had to find https://discourse.slicer.org/t/commit-message-prefix/10921 to see the previously used regex. The unreliable can be observed in recent PR #6601 where the installed CommitCheck app is not responding and the https://www.commitcheck.com/ site is unresponsive.
This check is based on content at https://slicer.readthedocs.io/en/latest/developer_guide/style_guide.html#commits.
=> ENH: Add commit message github actions workflow

.pre-commit-config.yaml
By adding `pyupgrade` to the pre-commit configuration, it enables the following:
* GitHub Action report: Suggested changes are reported in the error log associated with the pre-commit GitHub Action workflow.
* Consolidated local pre-commit checks and updates by running:
```
PythonSlicer -m pip install pyupgrade
PythonSlicer -m pre_commit run --all-files
```
As described in a4ea79909 (STYLE: Upgrade python syntax to 3.9 and newer), note that:
1. Running the command twice may be needed to ensure that strings associated with `logging` package are updated to use f-string.
2. Revisiting some of the changes automatically proposed may be required.
=> ENH: Update pre-commit config to include pyupgrade

SuperBuild/External_SimpleITK.cmake
See https://discourse.slicer.org/t/sitkutils-pullvolumefromslicer-does-not-create-sitk-image-in-slicer-5-1/25669
This commit fixes a regression introduced by Slicer@8f67453b0 (ENH: Add support for importing "itk" from python wheels installed from PyPI)
It ensures the type checks associated with "sitk.SetImageFromArray()" and "sitk.GetMemoryViewFromImage()" functions do not report errors like the following:
```
File "<console>", line 1, in <module>
File "/path/to/lib/Python/Lib/site-packages/SimpleITK/extra.py", line 269, in GetArrayFromImage
array_view = GetArrayViewFromImage(image)
File "/path/to/lib/Python/Lib/site-packages/SimpleITK/extra.py", line 255, in GetArrayViewFromImage
image_memory_view = _GetMemoryViewFromImage(image)
TypeError: in method …
```
=> BUG: Update SimpleITK to fix test_sitkUtils

Libs/MRML/Core/Testing/vtkMRMLDisplayableNodeTest1.cxx
This commit updates the test to account for change introduced in abe976107 (BUG: Make sure ProcessMRMLEvents is called all the way to the base node class).
Considering that...
* the spy is associated with `displayableNode`
* `displayableNode` has a reference to `displayNode1`
* the modified event associated with `displayNode1` is triggered
* the fix abe976107 ensures events associated with references are processed in vtkMRMLNode::ProcessMRMLEvents
... updating the test to expect "DisplayModifiedEvent" and "ReferencedNodeModifiedEvent" is sensible.
=> BUG: Fix vtkMRMLDisplayableNodeTest1-TestDisplayModifiedEvent

Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx
Exporting visible segments to model nodes could cause a crash when exporting using the action on the virtual "Segment" items, but wouldn't crash when exporting from the "Segmentation" item. When exporting from segment, the segment parent (the segmentation node) was used as the parent of the folder node. This seems to cause an invalid SH item parent, and could cause a crash later when the model is updated.
Fixed by using the parent of the Segmentation node for the export folder parent.
Fixes #6570
=> BUG: Fix crash when exporting segment model node

.github/ISSUE_TEMPLATE/patch-release.md, .github/ISSUE_TEMPLATE/release.md
A dedicate wiki page has also been added. See https://github.com/Slicer/Slicer/wiki/Release-Process
Remaining:
=> DOC: Add "release" issue template

Docs/user_guide/user_interface.md, SuperBuild/External_CTK.cmake
These commits are added:
-----
Revision: commontk/CTK@65a0555120de6681959b43f9154a77fd7ccf1d47
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date: 2022-05-05 1:56:00 AM
Message:
ENH: Update ctkVTKRenderView::lookFromAxis API
This commit is a follow up of d620ad966 (BUG: Fix unexpected camera position change in ctkVTKRenderView::lookFromAxis) removing the use of the "fov" parameter originally introduced in fbb33cdfa (Add ctkVTKRenderView::lookFromAxis(axis, fov))
It was not a good idea to force changing the camera distance from the focal point when the user only requested a view direction change.
-----
Revision: commontk/CTK@2e78ec70d30c7a4dca6affb0c3a342d338e34044
Author: Jean-Christophe Fillion-Robin …
=> ENH: Update CTK to improve Python console

Docs/user_guide/user_interface.md, SuperBuild/External_CTK.cmake
See https://discourse.slicer.org/t/load-python-script-from-harddisk-in-slicers-s-python-interactor/17399/10
```
$ git shortlog 65a055512..95d735d1d --no-merges
Andras Lasso (3):
COMP: Fix build error introduced in previous commit
ENH: Change run file keyboard shortcut in Python console
BUG: Fix unnecessary warning in ctkVTKHistogram::resetRange()
```
=> COMP: Update CTK to fix build error and update python console shortcut

Docs/conf.py, Docs/developer_guide/api.md, Docs/developer_guide/mrml.md, Docs/developer_guide/slicer.md, Docs/developer_guide/vtk.md.dis, Docs/developer_guide/vtkAddon.md, Docs/developer_guide/vtkITK.md, Docs/developer_guide/vtkTeem.md
Re-introduces the documentation of the slicer python packages originally added using ``automodule`` in b82b68f43 (ENH: Add automatically generated CLI module documentation) and removed in dc149534a (DOC: Add a few missing module documentation).
To avoid having a long list of documented functions listed on the main "api" documentation page, the `maxdepth` is changed from 4 to 2.
To ensure the documentation can be generated without having the "real" compiled python modules available, it set the `autodoc_mock_imports`[^1] setting.
The setting `autodoc_mock_imports` addresses warning like the following:
```
WARNING: autodoc: failed to import module 'ScriptedLoadableModule' from module 'slicer'; the following exception was raised:
No module named 'ctk'
```
[^1]: …
=> Document slicer python api

Docs/user_guide/user_interface.md, Libs/MRML/DisplayableManager/vtkMRMLWindowLevelWidget.cxx
Fixes #6592 by changing the window/level reset opation to be control-left-doubleclick so that it doesn't interfere with the default view operation of maximizing/restoring view size using left-double-click.
=> ENH: separate slice doubleclick operations

Base/Python/slicer/ScriptedLoadableModule.py, Base/Python/slicer/util.py
In addition of few docstring fixes, this pull request streamline referencing of resources during them module `setup()`, this function adds the function `resourcePath` to `ScriptedLoadableModule` similar to the one already available in `ScriptedLoadableModuleWidget`.
=> Add resourcepath helper to scripted module

Base/QTGUI/qSlicerMouseModeToolBar.cxx
When changing mouse modes, the cursor is not updated for views that are not mapped in the current layout. This causes an incorrect cursor to be displayed in views that are not part of the layout when the mouse mode is changed.
Example:
- Start in four-up layout
- Change to window/level mouse mode
- Maximize red slice view
- Change to view transform mouse mode
- Restore view layout
- Mouse cursor still shows window/level cursor in all views except the red slice == *Error*
Fixed by updating view cursors even when the view is not mapped in the current layout.
=> BUG: Fix mouse cursor not being changed for views not mapped in layout

CMakeLists.txt
When building with Slicer_BUILD_APPLICATIONUPDATE_SUPPORT the commontk/qRestApi is used. The qRestApi depends on the Script module of Qt. This commit expresses that dependency and allows Slicer to be built with extension manager support off and application update support on.
=> COMP: Fix Qt dependencies for application update

Docs/user_guide/modules/vectortoscalarvolume.md
This commit adds the documentation historically maintained on the Slicer wiki at https://www.slicer.org/wiki/Documentation/Nightly/Modules/VectorToScalarVolume
=> DOC: Add "Vector to Scalar Volume" module documentation

Docs/user_guide/modules/extensionwizard.md
This commit adds the documentation historically maintained on the Slicer wiki at https://www.slicer.org/wiki/Documentation/Nightly/Modules/ExtensionWizard
=> DOC: Add "Extension Wizard" module documentation

Libs/MRML/Widgets/qMRMLThreeDView.cxx, Libs/MRML/Widgets/qMRMLThreeDView.h, Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx, Modules/Scripted/WebServer/WebServerLib/SlicerRequestHandler.py
This fixes the following warning which began to be displayed with the CTK update in https://github.com/Slicer/Slicer/commit/2e02a3581f25db91edd23a82a59cc91833512dcd
"This function is deprecated. Use lookFromAxis(const ctkAxesWidget::Axis& axis) instead"
The above deprecation can be seen when using latest Slicer preview and running
`slicer.app.layoutManager().threeDWidget(0).threeDController().lookFromAxis(ctk.ctkAxesWidget.Anterior)`.
=> ENH: Replace deprecated lookFromAxis usage

SuperBuild/External_CTK.cmake
-----
commit commontk/CTK@2c89539632e503e7cf9b7c53adccd8f1f71b2ead
Date:   Tue Nov 1 20:09:08 2022 -0400
BUG: Fix cursor position during auto-complete
When error messages were printed during auto-complete, the error messages got mixed up with the entered command.
Fixed by inserting text into the correct position (this->textCursor()  was called twice in ctkConsolePrivate::printString() and so the movePosition() call had no effect); also changed the code to use this->textCursor() consistently to get the cursor (sometimes the equivalent `QTextCursor c(this->document())` call was used)
Also fixed output printing: always print pending messages before displaying the prompt.
See https://github.com/Slicer/Slicer/issues/6630
-----
=> BUG: Update CTK to fix cursor position during auto-complete

Base/QTCore/qSlicerCoreApplication.cxx, Libs/MRML/DisplayableManager/vtkMRMLAbstractWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLAbstractWidgetRepresentation.cxx, Libs/MRML/DisplayableManager/vtkMRMLAbstractWidgetRepresentation.h, Libs/MRML/DisplayableManager/vtkMRMLRulerDisplayableManager.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentationHelper.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionRepresentation2D.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
VTK's default font file does not support Chinese characters. This commit allows setting a custom font file (such as Google's Noto font - https://fonts.google.com/noto/fonts?noto.continent=Asia&noto.region=CN&noto.script=Hant) in application settings. Since these font files are relatively large (about 5MB for each font family) and it is not clear yet which formats will work the best, the fonts are not yet bundled with the application but for now it will be installed by LanguagePacks extension.
=> ENH: Make viewer font file configurable

SuperBuild/External_ITK.cmake
This commit fixes a regression introduced in InsightSoftwareConsortium/ITK@5b09d5466 (COMP: Allow install lib directory name changes) through 4d1c98ef8 (COMP: Update ITK to post-v5.3rc04 version and SimpleITK to post-v2.2.0).
It backports the changes introduced in upstream ITK through https://github.com/InsightSoftwareConsortium/ITK/pull/3722
```
$ git shortlog 69e52f05c4..be914a8b57 --no-merges
[Backport PR-3722] COMP: Ensure client project can find externally build ITK module
```
* https://github.com/Slicer/Slicer/issues/6587
* https://github.com/Slicer/Slicer/pull/6454
* https://github.com/InsightSoftwareConsortium/ITK/pull/3722
=> COMP: Update ITK to fix superbuild of extensions with ITK modules

Modules/Scripted/DICOMLib/DICOMUtils.py, Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Image acquisition geometry regularization has proven to work well over the past several years (it allows loading unusual image geometries correctly and does not seem to result in extra complications), therefore it makes sense to enable it by default.
See the most recent related discussion at https://discourse.slicer.org/t/distorted-malaligned-volumes-after-loading-dicom-sets/26088/8
It is probably safe to include this in Slicer-5.2 stable, but waiting until Slicer-5.3 preview should not be a problem either (then we could integrate it along with a fix for https://github.com/Slicer/Slicer/issues/6648).
=> ENH: Regularize acquisition geometry by default for DICOM image loading

Base/QTApp/Resources/UI/qSlicerErrorReportDialog.ui, Base/QTApp/qSlicerErrorReportDialog.cxx, Base/QTApp/qSlicerErrorReportDialog.h
The main motivation behind this is that adding the ability to open file log locations makes it far easier for slicer users to send entire log files to the developers that make various slicer apps/extensions/modules. This PR updates the 'report a bug' dialog by replacing the `Copy log message to clipboard` button with a `Open log file location` button. I could have opted to add another button, however for the sake of space I decided to simply replace the former button.
=> ENH: Add ability to quickly open to log file location

Libs/MRML/Core/vtkMRMLScriptedModuleNode.cxx
vtkMRMLScriptedModuleNode copies parameters from the other node not through the SetParameter function, so it needs to properly call Modified if anything changes.
=> BUG: CopyContent should call Modified

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
The FixedNumberOfControlPoints flag was not copied and at node export a copy of the node is exported.
Also made FixedNumberOfControlPoints and MaximumNumberOfControlPoints properties completely independent. Modifying MaximumNumberOfControlPoints when FixedNumberOfControlPoints flag was changed was unnecessary and had very complicated side effects.
Fixes error reported at https://discourse.slicer.org/t/export-file-as-bug-for-markup-control-points/26188
=> BUG: Fix fixedNumberOfControlPoints property value in exported markup nodes

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.h
Originally discussed in https://discourse.slicer.org/t/optimizing-performance-of-events-when-clearing-nodes/23588/5. A `masterVolumeNodeChanged` call in SegmentEditor was 25% of the time when clearing a set of volume nodes from the scene in some custom code that I have.
For example when removing volume nodes, this can trigger a change of the current Master Volume node specification in the Segment Editor module if the current volume node is removed from the scene. When this happens over and over during batch processing there was frequent updating of the master volume node for SegmentEditor logic which can be an expensive operation, especially the masterVolumeNodeChanged call for SegmentEditorThresholdEffect.
=> ENH: Optimize processing Segment Editor updates during Batch Processing

Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
Originally mentioned in https://discourse.slicer.org/t/unable-to-clear-all-control-points-at-once-goes-by-threes/26203.
An incorrect selected item increment was using the number of total columns to skip when finding the next selected row and this was incorrect when columns were hidden. Selected Items only include the visible selections so each row would only have 6 selected items when coordinates were hidden instead of 9 items when coordinates were shown.
=> BUG: Fix control point state not updated with hidden coordinates

Docs/user_guide/modules/cropvolume.md
This commit adds the documentation historically maintained on the Slicer wiki at https://www.slicer.org/wiki/Documentation/Nightly/Modules/CropVolume
=> DOC: Add Crop Volume module documentation

Docs/user_guide/modules/surfacetoolbox.md
This commit adds the documentation based on 
1. markdown document contributed through https://github.com/Slicer/SlicerSurfaceToolbox/pull/53
2. tooltip text associated with tool button contributed through https://github.com/Slicer/SlicerSurfaceToolbox/pull/41
3. text originally historically maintained on the Slicer wiki at https://www.slicer.org/wiki/Documentation/Nightly/Modules/SurfaceToolbox.
In a follow-up pull-request addressing https://github.com/Slicer/Slicer/issues/6090, we will likely revisit the duplication of the documentation and instead have the markdown files fetched from https://github.com/Slicer/SlicerSurfaceToolbox/tree/master/Docs/user_guide/modules.
=> DOC: Add Surface Toolbox module documentation

Modules/Scripted/PerformanceTests/PerformanceTests.py
This commit fixes a regression introduced in 96ad8dfc0b (BUG: Update PerformanceTests module removing obsolete "webview" test cases)
Error fixed:
```
test_widgetRepresentation (qSlicerPerformanceTestsModuleGenericTest.qSlicerPerformanceTestsModuleGenericTest) ... Traceback (most recent call last):
File "/work/Preview/Slicer-0-build/Slicer-build/lib/Slicer-5.1/qt-scripted-modules/PerformanceTests.py", line 38, in setup
('Web View Test', self.webViewTest),
AttributeError: 'PerformanceTestsWidget' object has no attribute 'webViewTest'
ok
```
See https://slicer.cdash.org/test/23424820
=> BUG: Fix PerformanceTests removing invalid reference to web tests

Docs/user_guide/modules/selftests.md
This commit adds the documentation historically maintained on the Slicer wiki at https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/SelfTestModule
=> DOC: Add Self Tests module documentation

Docs/developer_guide/extensions.md, Docs/developer_guide/index.md, Docs/developer_guide/module_overview.md, Docs/developer_guide/mrml_overview.md
* Add `Module Overview` documentation (historically maintained on the Slicer wiki at https://www.slicer.org/wiki/Documentation/Nightly/Developers/Modules)
* Update `Module Overview` documentation adding `Remote Module` section (historically maintained on the Slicer wiki at https://www.slicer.org/wiki/Documentation/Nightly/Developers/Build_system/Remote_Module)
=> Add module overview documentation

Docs/developer_guide/module_overview.md
_Related to #6189_
* Update "rational" and "getting started" wording and use sphinx directives to highlight them.
* Remove ambiguous description: Considering the purpose of implementing a loadable module (either C++ or scripted) is to have a custom and tailored user experience that can not be obtained using the automatically generated UI associated with CLI modules, this commit removes the sentence.
* Remove link to obsolete "Loadable module" tutorial last updated in August 2016.
=> DOC: Improve Module Overview highlighting "rational" and "getting started"

Applications/SlicerApp/Testing/Python/ScriptedModuleDiscoveryTest/ModuleA.py, Applications/SlicerApp/Testing/Python/ScriptedModuleDiscoveryTest/Resources/resource.txt, Base/Python/slicer/ScriptedLoadableModule.py
This commit is a follow-up of 3c1b69de4 (ENH: Add convenient ScriptedLoadableModule.resourcePath() function)
It ensures the function can be called from the module constructor. Prior to this commit it was failing because the `slicer.modules` was updated only after the module was fully instantiated and after it was loaded (see function `setSlicerModules` in `slicerqt.py`).
=> BUG: Ensure ScriptedLoadableModule.resourcePath() works in __init__()

Base/Python/slicer/tests/test_slicer_util_VTKObservationMixin.py, Base/Python/slicer/util.py
If an observer is attached to an object through `VTKObservationMixin`, and if a reference to the object is not kept in Python, then the observer was automatically garbage collected from the `WeakKeyDictionary` even if the VTK object still exists. This means the observer cannot be removed with `removeObserver()`/`removeObservers()`.
This commit partially reverts 1e6d068 (BUG: Fix VTKObservationMixin preventing observed nodes from being released) by removing the use of `WeakKeyDictionary`.
It also marks `test_releaseNodes` as expected to fail and `test_removeObserver_issue6610` as expected to pass.
=> Fix VTKObservationMixin so that observers are removed if object reference is not kept in Python

CMake/SlicerCPackBundleFixup.cmake.in
This commit fix the following `codesign` error reported when attempting to sign a Slicer application package build with `Slicer_BUILD_WEBENGINE_SUPPORT` set to `OFF`.
For reference, the regression was introduced in 100f8268d (`BUG: Update macOS fixup script to package QtWebEngineProcess.app`) and exerted following the updated of the macOS signing server to macOS 12.
Error:
```
$ ./slicer-macos-codesign-scripts/sign.bash \
${identifier} ${version} \
[...]
--   Signing App
/Volumes/tmp.9dkIOBNj/Slicer.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /Volumes/tmp.9dkIOBNj/Slicer.app/Contents/Frameworks/QtWebEngineCore.framework
```
=> COMP: Fix macOS signing with webengine support disabled
