Slicer/Slicer

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, SuperBuild/External_VTK.cmake
Requires merge and backport of VTK enhancement https://gitlab.kitware.com/vtk/vtk/-/merge_requests/6586
=> BUG: Make markups 3D glyphs always face the camera

Modules/Scripted/ScreenCapture/ScreenCapture.py
This new feature allows creating a single large image that contains all the captured images in a table layout.
Implements basic solution for https://github.com/Slicer/Slicer/issues/4749
=> ENH: Add lighbox image creation option to ScreenCapture module

Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
The range of the slice offset slider in qMRMLSliceControllerWidget is set using the depth dimension of the slice bounds.
For thin volumes (such as ultrasound), the bounds could be slightly smaller than the spacing due to floating point errors. In these cases, trying to set the step size of the slider to the spacing would result in a warning message since the step size would be greater than the maximum value.
Fixed by setting the step size to the smaller of the either the slice offset or the slice bounds depth.
=> BUG: Fix warning messages logged by slice offset slider

Libs/MRML/Core/vtkMRMLInteractionNode.cxx
https://github.com/Slicer/Slicer/issues/4766
=> fix for misuse of vtkMRMLInteractionNode::EndPlacementEvent

Base/QTGUI/qSlicerApplication.cxx, Base/QTGUI/qSlicerSingletonViewFactory.cxx, Libs/MRML/Core/Testing/vtkMRMLTableStorageNodeTest1.cxx, Libs/MRML/Core/vtkMRMLTableStorageNode.cxx, Libs/MRML/Logic/vtkImageLabelOutline.cxx, Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx, Modules/CLI/ACPCTransform/ACPCTransform.cxx, Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DFSAffineTransform.txx, Modules/Loadable/Markups/MRML/vtkCurveGenerator.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneWidget.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/VolumeRendering/MRML/vtkMRMLGPURayCastVolumeRenderingDisplayNode.cxx, SuperBuild.cmake
An additional warning is being fixed in ITK (see https://github.com/InsightSoftwareConsortium/ITK/pull/1727) and will be backported after the PR is integrated upstream.
=> Fix miscallenous warnings

Base/Python/slicer/util.py, Base/QTCore/qSlicerCoreIOManager.cxx, Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.cxx, Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.h, Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx, Libs/MRML/Widgets/Testing/qMRMLSceneModelTest1.cxx, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.cxx, Modules/Scripted/SampleData/SampleData.py
This is a small collection of minor fixes, which were found while working on Sequences module migration to Slicer core.
=> Small fixes (no functional change)

Libs/FreeSurfer/vtkFSSurfaceReader.h, Libs/MRML/Core/vtkDataFileFormatHelper.h, Libs/MRML/Core/vtkMRMLFiducialListNode.h, Libs/MRML/Core/vtkMRMLTableStorageNode.h
<s>Find and remove redundant void argument lists.</s>
=> STYLE: Avoid typedef of anonymous structure

Base/Python/slicer/util.py
Helpful to trigger renders.
E.g. used here:
https://gist.github.com/pieper/f9da3e0a73c70981b48d0747132526d5
=> ENH: adds a helper for making numpy changes to scalars

SuperBuild/External_CTK.cmake
```
$ git shortlog 27bc11d..8ec9136
COMP: Fix Qt4 build adding fallback implementation for qUtf8Printable() (commontk/CTK#909)
ENH: Add checkBoxControlsButtonToggleState property to ctkCheckablePushButton (commontk/CTK#908)
```
=> ENH: Update CTK to improve ctkCheckablePushButton behavior

Libs/MRML/Core/Testing/vtkMRMLModelStorageNodeTest1.cxx, Libs/MRML/Core/vtkMRMLModelStorageNode.cxx, Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx, Modules/CLI/ProbeVolumeWithModel/CMakeLists.txt, Modules/CLI/ProbeVolumeWithModel/ProbeVolumeWithModel.cxx
Various fixes related to unstructured grid loading, display, and probing.
=> Unstructured grid probe fixes

SuperBuild/External_python.cmake
This commit checks if the lsb_release python script contains the "-Es"
option. If it is the case, we are sure that the script will not attempt
to find package in the Slicer python installation.
See https://bugs.launchpad.net/ubuntu/+source/lsb/+bug/938869/comments/28
See https://github.com/Slicer/Slicer/pull/4879#issuecomment-619089055
Co-authored-by: Hans Johnson <hans-johnson@uiowa.edu>
=> COMP: Skip generation of lsb_wrapper launcher if not required

Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui
=> ENH: Add tooltip to plane markup button

Base/QTCLI/qSlicerCLIModuleFactoryHelper.cxx
=> STYLE: Remove Q_ASSERT from qSlicerCLIModuleFactoryHelper::modulePaths()

Docs/conf.py, Docs/developer_guide/slicer.rst, Docs/global.rst.in, Docs/user_guide/module_segmentations.md, Docs/user_guide/module_segmenteditor.rst
Fix markdown usage with recent Sphynx, add markdown table support, add Segmentations module documentation.
=> Improve markdown support

Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager2D.cxx
vtkContourTriangulator is simpler and more robust than vtkStripper+vtkCleanPolyData+vtkTriangleFilter.
However, it is considerably slower.
Fixes #4959
=> ENH: Simplify segmentation filled slice view

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.h
Fixes https://github.com/Slicer/Slicer/issues/4987
=> ENH: make SH plugin handler currentItems python friendly

Docs/user_guide/about.md
This section matches the content found the corresponding Slicer Wiki
section.
See https://www.slicer.org/w/index.php?title=CommercialUse&oldid=49340
| readthedocs | mediawiki |
|------------------|---------------|
| ![image](https://user-images.githubusercontent.com/219043/85755922-5f878a00-b6dc-11ea-8a68-6b7abc0d06d6.png) |   ![image](https://user-images.githubusercontent.com/219043/85756105-847bfd00-b6dc-11ea-8739-8699d69a280f.png) |
=> DOC: Update "Commercial Use" section

Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake
=> BUG: Upload additional metadata when using extension manager client

Base/QTGUI/qSlicerApplication.cxx
Changed the exception message to make it more understandable by
users with less technical background.
Additional system-specific suggestion on adding RAM is given only
when std::bad_alloc is captured.
Fixes #5011 
Throw bad_alloc on Linux:
Throw std::exception
=> ENH: Make exception message more user-friendly

Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Fixes issue of localizer image messing up loading of a series - see https://discourse.slicer.org/t/why-does-my-xa-type-image-appear-as-a-series-and-not-a-single-2d-image/12711/4
=> Dicom scalar plugin remove localizer image

Modules/Scripted/SegmentStatistics/SegmentStatistics.py
In order to ensure that the segment statistics are calculated in world coordinates, the segmentation is duplicated to a temporary segmentation node and the transform is hardened.
fixes #4942
=> BUG: Fix Segment statistics ignores parent transform

SuperBuild.cmake
$ git shortlog ff51ea0..cbbecd7
ENH: Clean BoundaryCut and CurveCut input
=> ENH: Update SurfaceToolbox to latest version

Libs/MRML/Core/vtkMRMLMessageCollection.cxx
Fixes warning for comparison of signed and unsigned integer.
=> COMP: fix signed/unsigned comparison introduced by pull request 5045.

Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx, Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
Slicer often crashed when manipulated display nodes, for example switched between CPU/GPU rendering mode or added/removed volume rendering display nodes from scripts.
The problem was that volume rendering displayable manager used simple pointers to display nodes and volume nodes, which could become invalid, while the nodes were removed from the scene.
=> BUG: Fix crash when chaning volume rendering display nodes

SuperBuild/External_VTK.cmake
$ git shortlog 9c813fe590..8b86723b9d
[backport MR-7151] Add support for horizontal mouse scroll events
=> ENH: Update VTK backporting support for horizontal mouse wheel events

Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx
Segmentation reader now uses the model storage node to read
Closes: #5097
=> BUG: STL coordinate system read incorrectly when loaded as segmentation

Docs/developer_guide/modules/index.rst, Docs/developer_guide/modules/markups.md, Docs/developer_guide/modules/volumerendering.md, Docs/index.rst, Docs/user_guide/modules/volumerendering.md
Moved from https://www.slicer.org/wiki/Documentation/Nightly/Modules/VolumeRendering
=> DOC: Add volume rendering documentation

Base/Python/slicer/slicerqt.py
This reverts commit 4ccf136921f6ecb22e546115bc8f56ea6b6ba8be.
See https://github.com/Slicer/Slicer/pull/5147
=> BUG: Revert "Fix duplicate python logging messages in the log"

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
Markups were still interactive if they were behind an actor that was added after the markup actor. Markup that were added later were correctly occluded by previously added nodes.
Fixed by disconnecting SelectVisiblePoints from the label pipeline and only manually calling it at the start of RenderOverlay().
fixes #5150
=> BUG: Fix interactability of occluded markup control points

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsDisplayNodeWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.h
Adds additional options to the vtkMRMLMarkupsDisplayNode to customize text display:
- TextFontFamily
- TextFontFamily;
- TextBold;
- TextItalic;
- TextShadow;
- TextBackgroundColor
- TextBackgroundVisibility;
- TextBackgroundOpacity
=> ENH: Add customization of markup text font and background appearance

Docs/user_guide/modules/segmentations.md
Describe how to oversample segmentation of an imported model.
=> DOC: Update segmentations.md

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorEraseEffect.cxx
=> STYLE: fix typo in Erase effect help text

SuperBuild.cmake
Mainly addresses: https://github.com/pieper/CompareVolumes/commit/381f9eb134b006b6c13b97a15a8c5ef111dedcf0
=> COMP: CompareVolumes fix int division add features

Modules/Scripted/DICOMPlugins/CMakeLists.txt, Modules/Scripted/DICOMPlugins/DICOMImageSequencePlugin.py, Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
DICOMScalarVolumePlugin is updated to allow loading of color images.
DICOMImageSequencePlugin can read 2D X-ray angiography and ultrasound image sequences.
Fixes #3168.
=> ENH: Allow loading color images and 2D+t XA and US images

Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.cxx
GetItemByDataNode was slow because it had to search the whole tree for an item that has a specific MRML node associated with it.
Made it faster by adding a vtkMRMLNode* to vtkSubjectHierarchyItem* cache.
=> ENH: Improve subject hierarchy performance

Utilities/SetupForDevelopment.sh
See https://github.com/Slicer/Slicer/issues/5259#issuecomment-717907044
=> ENH: Exclude md extension from git hook line lengths check

Applications/SlicerApp/qSlicerAppMainWindow.cxx, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorGrowFromSeedsEffect.py
See https://discourse.slicer.org/t/issues-with-website-links-and-webmaster-email-address/12848
=> BUG: Replace broken SPL publication links

Libs/MRML/Core/vtkMRMLMeasurement.cxx, Libs/MRML/Core/vtkMRMLMeasurement.h, Libs/MRML/Core/vtkMRMLMeasurementConstant.cxx, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementAngle.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementLength.cxx, Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h
Video about how it works:
https://1drv.ms/u/s!Ao_a-dPPX98ZhOIJ0heKpXafNKKRgg?e=Ribmlh
I have rebased to the upstream master and if it turns out fine I'll update the PR.
=> Markups measurement handling

Libs/MRML/Core/vtkMRMLStreamingVolumeNode.cxx
Copying a vtkMRMLStreamingVolumeNode would cause the frame to be decoded, leading to to poor performance when copying entire sequences.
Fixed by preventing decoding during node copy.
=> BUG: Fix performance issue when copying vtkMRMLStreamingVolumeNode

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
Previous implementation of interaction handle translation/rotation tried to align the position of the handle to the current mouse position, which had the issue that the markup handle would "jump" if the user didn't click exactly on the center of the handle.
This is fixed by transforming the markup handles based on the difference between the current and previous mouse positions.
fixes #5257
=> BUG: Fix markup position jumping when using interaction handles

Libs/MRML/Core/vtkMRMLMeasurement.cxx, Libs/MRML/Core/vtkMRMLMeasurement.h, Libs/MRML/Core/vtkMRMLMeasurementConstant.cxx, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
Two commits: a bugfix and the storage feature.
=> Markups measurement storage

Docs/user_guide/modules/markups.md, Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui
- Sections about scalars and measurements added in Markups user documentation
- Measurements section collapsed by default
=> STYLE: Add doc for markups measurements and scalar display

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/Resources/Schema/markups-schema-v1.0.0.json, Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsSettingsPanel.ui, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx, Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsDisplayNodeWidget.ui, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.h, Modules/Loadable/Markups/qSlicerMarkupsModule.cxx, Modules/Loadable/Markups/qSlicerMarkupsSettingsPanel.cxx, Modules/Loadable/Markups/qSlicerMarkupsSettingsPanel.h
Allows the color shown when the user hovers over a markup component to be changed.
=> ENH: Add ActiveColor property for markup display

SuperBuild.cmake
$ git shortlog cb1259b..e4b2bdf
BUG: Fix surface normals in hollowed models
BUG: Fix plane cut cap orientation for negative side
=> ENH: Update SurfaceToolbox - Fixes normals in Hollow and Plane Cut

CMake/SlicerMacroExtractRepositoryInfo.cmake, Extensions/CMake/CMakeLists.txt, Extensions/CMake/SlicerBlockBuildPackageAndUploadExtensions.cmake, Extensions/CMake/SlicerExtensionsDashboardDriverScript.cmake, Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake, Extensions/CMake/Testing/CMakeLists.txt, Extensions/CMake/Testing/SlicerExtensionBuildSystemTest.py
Make extension description comparison insensitive to line ending.
Make SVN optional.
Fix expected order of build artifacts submission.
=> Fix extensions tests

Libs/MRML/Core/vtkMRMLMeasurement.cxx, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.cxx, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h
See discussion here https://discourse.slicer.org/t/perpendicular-cross-sectional-area-along-centerline/15556/103
=> ENH: Always interpolate control point measurements in markups

Docs/user_guide/getting_started.md
Based on information here:
https://discourse.slicer.org/t/could-not-load-dicom-data/14211/3
=> Add ArchLinux installation information

SuperBuild.cmake
Improves size of grid transform exported from thin plate spline
https://github.com/Slicer/LandmarkRegistration/commit/7cad2c1796c267899fc3bde02e299c608726a52a
=> ENH: update LandmarkRegistration tag

SuperBuild/External_CTK.cmake
see discussion here: https://discourse.slicer.org/t/crash-with-ctkrangewidget/15299/4
=> BUG: Update CTK to fix a crash in ctkRangeWidget::SetRange in Debug mode

Libs/MRML/Core/Testing/vtkMRMLSceneTest2.cxx, Libs/MRML/Core/vtkMRMLCameraNode.cxx, Libs/MRML/Core/vtkMRMLCoreTestingUtilities.cxx, Libs/MRML/Core/vtkMRMLCoreTestingUtilities.h, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx, Libs/MRML/Widgets/qMRMLSliceControllerWidget.h, Libs/MRML/Widgets/qMRMLSliceWidget.cxx
Changes implemented while working on https://github.com/Slicer/Slicer/pull/5410
=> Misc tweaks

Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
The recommended colors for are shown as a color square for each type in the terminology navigator widget.
=> ENH: Show colors in terminology selector

Modules/Loadable/Cameras/Testing/Cxx/vtkSlicerCamerasModuleLogicCopyImportedCamerasTest.cxx
Related to https://github.com/Slicer/Slicer/pull/5410
=> COMP: Fix build error in cameras test

Base/QTCore/qSlicerCoreIOManager.cxx, Base/QTCore/qSlicerSceneBundleReader.cxx, Base/QTGUI/qSlicerDataDialog.cxx, Base/QTGUI/qSlicerIOManager.cxx, Base/QTGUI/qSlicerIOManager.h, Base/QTGUI/qSlicerSaveDataDialog.cxx, Libs/MRML/Core/Testing/vtkMRMLStorageNodeTest1.cxx, Libs/MRML/Core/vtkMRMLLayoutNode.cxx, Libs/MRML/Core/vtkMRMLMessageCollection.cxx, Libs/MRML/Core/vtkMRMLMessageCollection.h, Libs/MRML/Core/vtkMRMLModelStorageNode.cxx, Libs/MRML/Core/vtkMRMLScene.cxx, Libs/MRML/Core/vtkMRMLSequenceStorageNode.cxx, Libs/MRML/Core/vtkMRMLStorableNode.cxx, Libs/MRML/Core/vtkMRMLStorageNode.cxx, Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveWidget.cxx, Modules/Loadable/Models/Logic/vtkSlicerModelsLogic.cxx, Modules/Loadable/Models/Logic/vtkSlicerModelsLogic.h, Modules/Loadable/Models/Testing/Cxx/vtkSlicerModelsLogicAddFileTest.cxx, Modules/Loadable/Models/qSlicerModelsReader.cxx, Modules/Loadable/Sequences/Logic/vtkSlicerSequencesLogic.cxx, Modules/Loadable/Sequences/Logic/vtkSlicerSequencesLogic.h, Modules/Loadable/Sequences/qSlicerSequencesReader.cxx
Implement error reporting for loading data (similarly how it was recently implemented for *saving* data) and a two other minor fixes.
=> Report data loading errors

Base/Python/slicer/util.py
Add function to return module logic.
Improve module widget function to return the actual Python class instead of the C++ wrapper.
Use exceptions for error handling (instead of just printing error message) to make sure that the error is noticed and the most relevant error message is displayed.
Add missing function documentation.
=> ENH: Improve module access scripts in slicer.util

Base/QTGUI/qSlicerExtensionsRestoreWidget.cxx, Libs/MRML/Core/vtkMRMLMessageCollection.cxx, Libs/MRML/Core/vtkMRMLMessageCollection.h, Libs/MRML/Core/vtkMRMLModelNode.cxx, Libs/MRML/Core/vtkMRMLNodePropertyMacros.h
A few trivial improvements.
(Previously I committed such trivial changes directly into the main branch, but to follow the Slicer development process more consistently, I now push all changes via code reviews.)
=> Minor improvements

Base/QTCore/qSlicerCoreApplication.cxx
See discussion here:
https://github.com/Slicer/Slicer/commit/d518c36aca64583d003b3a405f2308aceedf65db#commitcomment-47154875
=> BUG: fix tmp file path calculation

Base/QTGUI/qSlicerApplication.cxx, Modules/Scripted/DICOMLib/DICOMExportScalarVolume.py, Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Small fixes for errors found while investigating failing DICOM export into folders that have special characters in their names.
=> Improve dicom export robustness

Modules/Scripted/DICOMLib/DICOMPluginSelector.py
A temperate solution of a #5114 issue.
=> ENH: DICOM plugins layout is placed into a scroll area widget

Docs/user_guide/modules/acpctransform.md, Docs/user_guide/modules/index.rst, Modules/CLI/ACPCTransform/ACPCTransform.cxx, Modules/CLI/ACPCTransform/ACPCTransform.xml
Documentation is co-authored by https://discourse.slicer.org/u/shebaelena
=> ENH: Add Center volume option and documentation to ACPC Transform module

Docs/user_guide/modules/dicom.md, Modules/Scripted/DICOM/DICOM.py, Modules/Scripted/DICOM/Resources/UI/DICOM.ui, Modules/Scripted/DICOMLib/DICOMBrowser.py
Another solution for an issue #5114
=> ENH: DICOM plugins layout is moved from browser to module panel

Libs/MRML/Core/vtkMRMLMeasurement.cxx, Libs/MRML/Core/vtkMRMLMeasurement.h, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode_Private.h, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementAngle.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementArea.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementLength.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementVolume.cxx, Modules/Loadable/Markups/Resources/Schema/markups-schema-v1.0.1.json, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.h, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsStorageNodeTest2.cxx, Modules/Loadable/Markups/Testing/Python/CMakeLists.txt, Modules/Loadable/Markups/Testing/Python/MarkupsCurveMeasurementsTest.py, Modules/Loadable/Markups/Testing/Python/MarkupsMeasurementsTest.py, Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx, Modules/Loadable/Markups/qSlicerMarkupsReader.cxx
Also improve saving of units into markups measurements and make error message display during loading.
see https://github.com/Slicer/Slicer/issues/5261
=> ENH: Save coordinate system unit to markups json files

Base/QTCore/qSlicerCoreApplication.h, Base/QTGUI/qSlicerIOManager.cxx, Libs/MRML/Core/vtkMRMLCrosshairNode.cxx, Libs/MRML/Core/vtkMRMLCrosshairNode.h, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Modules/CLI/ExecutionModelTour/ExecutionModelTour.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest1.py, Modules/Loadable/Sequences/qSlicerSequencesModule.cxx, SuperBuild.cmake
This is a collection of unrelated small fixes bundled together in one pull request for joint review.
=> Fixing tests and other small errors

Base/QTCLI/vtkSlicerCLIModuleLogic.cxx
Support for scripted CLI has been revamped and is now achieved through
the use of `SlicerMacroBuildScriptedCLI` CMake macro.
This commit removes obsolete, untested and unmaintained support for writing
scripted CLIs there were only valid for Slicer 3. For reference, this approach
was documented here:
https://www.slicer.org/wiki/Documentation/Nightly/Developers/SlicerExecutionModel/Python
=> STYLE: Remove obsolete "PythonModule" support from vtkSlicerCLIModuleLogic

Base/QTGUI/qSlicerSettingsGeneralPanel.cxx, Libs/MRML/Core/vtkMRMLModelStorageNode.cxx, Modules/CLI/ModelMaker/ModelMaker.cxx, Modules/CLI/ProbeVolumeWithModel/ProbeVolumeWithModel.cxx, Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx, Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.h, Modules/Scripted/SegmentEditor/SegmentEditor.py, SuperBuild/External_VTK.cmake
This pull request contains 4 unrelated fixes, lumped together to reduce overhead in creating and reviewing the pull request.
=> Several small fixes

Docs/user_guide/extensions_manager.md
Add note on installation requirement on macOS.
=> DOC: Improve Extensions manager page

Base/QTCore/Testing/Cxx/qSlicerUtilsTest1.cxx, Base/QTCore/qSlicerCoreApplication.cxx, CMake/SlicerCPack.cmake, Modules/Scripted/DICOM/DICOM.py, Modules/Scripted/DICOMLib/DICOMUtils.py, Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
=> Small fixes 20210405

Modules/Scripted/DICOMLib/DICOMBrowser.py, Modules/Scripted/DICOMLib/DICOMExportScalarVolume.py, Modules/Scripted/DICOMLib/DICOMPlugin.py, Modules/Scripted/DICOMLib/DICOMRecentActivityWidget.py, Modules/Scripted/DICOMLib/DICOMUtils.py, Modules/Scripted/DICOMPlugins/DICOMSlicerDataBundlePlugin.py, SuperBuild.cmake, SuperBuild/External_CTK.cmake
If only first file of a series is needed then retrieve only that.
Update git hashes of MultiVolumeImporter and CTK to include related API and performance improvements.
=> ENH: Improve DICOM examine and load performance

Libs/MRML/DisplayableManager/vtkMRMLViewDisplayableManager.cxx
When zooming in on a very small object, the axis labels of the purple box were drifting very far away.
How to reproduce: load MRHead, set volume spacing to 1000x smaller (`getNode('MRHead').SetSpacing(0.001, 0.001, 0.0013`), fit to slice views, center 3D view, hit "R" key in 3D view to zoom to fit.
The fix was to center the text in the text actor's coordinate system.
Before the fix:
After the fix:
=> BUG: Fixed label positions in zoomed in view

Libs/MRML/Core/vtkMRMLModelNode.cxx, Libs/MRML/Core/vtkMRMLModelNode.h, Libs/MRML/Core/vtkMRMLModelStorageNode.cxx, Libs/vtkTeem/vtkTeemNRRDReader.cxx, Libs/vtkTeem/vtkTeemNRRDReader.h, Modules/CLI/ProbeVolumeWithModel/ProbeVolumeWithModel.cxx, Modules/CLI/ProbeVolumeWithModel/ProbeVolumeWithModel.xml, Modules/Loadable/Models/Logic/vtkSlicerModelsLogic.cxx, Modules/Loadable/Models/Testing/Cxx/vtkSlicerModelsLogicAddFileTest.cxx, Modules/Loadable/Models/qSlicerModelsReader.cxx, Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserToolBar.cxx, Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserToolBar.h, Modules/Loadable/Sequences/qSlicerSequencesModule.cxx
- Improve model loading (display scalars, center in 3D view)
- Improve sequence loading (show sequence toolbar if sequence is loaded as part of a scene; show toolbar in separate row)
- Add output array name option to Probe volume with model module
These are quite independent commits, do not squash when merging.
=> Improve model and sequence loading defaults

Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/ScalarVolumeSegmentStatisticsPlugin.py
I am making a child class of ScalarVolumeSegmentStatisticsPlugin outside of Slicer core, and I would like to make use of the code that already exists for aligning the segment to the volume image data and creating a vtkStencil. This refactor adds a method getStencilForVolume to ScalarVolumeSegmentStatisticsPlugin which returns a vtkStencil.
An example child class would be:
```
class ThresholdedStatsPlugin(ScalarVolumeSegmentStatisticsPlugin):
...
def computeStatistics(self, segmentID):
segmentationNode = slicer.mrmlScene.GetNodeByID(self.getParameterNode().GetParameter("Segmentation"))
grayscaleNode = slicer.mrmlScene.GetNodeByID(self.getParameterNode().GetParameter("ScalarVolume"))
stencil = self.getStencilForVolume(segmentationNode, segmentID, grayscaleNode)
threshold_lower, …
```
=> ENH: ScalarSegmentStatsPlugin has method to get vtkStencil from segment

Base/QTCore/Testing/Cxx/qSlicerExtensionsManagerModelTest.cxx, Base/QTCore/qSlicerExtensionsManagerModel.cxx, Base/QTCore/qSlicerExtensionsManagerModel.h, Base/QTGUI/qSlicerExtensionsInstallWidget.cxx, SuperBuild/External_qRestAPI.cmake
This first set of changes does not introduce new changes and is expected to be fully backward compatible. 
It is being integrated anticipating the future integration of #5629
=> Refactor extensions manager support

CMake/SlicerPackageAndUploadTarget.cmake, Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake
This PR was incorrectly labelled,  it has been renamed and updated.
Changes related to the support for the new extension frontend and backend are published in https://github.com/Slicer/Slicer/pull/5637
=> Add support for uploading application package to Girder based server

Base/QTCore/qSlicerSlicer2SceneReader.cxx, Docs/developer_guide/build_instructions/macos.md, Docs/developer_guide/modules/dicom.md, Docs/user_guide/getting_started.md, Libs/MRML/Core/vtkMRMLMeasurement.cxx, Libs/MRML/Core/vtkMRMLMeasurement.h, Modules/CLI/ExecutionModelTour/ExecutionModelTour.xml, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.cxx, Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsClosedCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsClosedCurveNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementAngle.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementArea.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementLength.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMeasurementVolume.cxx, Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest1.cxx, Modules/Loadable/Markups/Testing/Python/MarkupsCurveMeasurementsTest.py, Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx, Modules/Loadable/Units/Logic/vtkSlicerUnitsLogic.cxx, Modules/Loadable/Units/Logic/vtkSlicerUnitsLogic.h, Modules/Loadable/Units/qSlicerUnitsSettingsPanel.cxx, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.h
Related to #5356.
@lassoan, I have added only the installation instructions, for now. Do you think the developer part is necessary? If yes, where should it go? I didn't find an obvious home for it in the Developer section.
=> DOC: Add macOS Homebrew installation instructions

Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h, Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h
New "Export/import table" section is added to Markups module.
=> ENH: Add export/import of markups to/from table node

Docs/developer_guide/mrml_overview.md
=> DOC: Add "Layout" section to "Developer Guide / MRML Overview / Advanced topics"

Modules/Scripted/DICOMLib/DICOMProcesses.py, Modules/Scripted/DICOMLib/DICOMSendDialog.py
AE title is currently hard-coded, add a text edit in the dicom export dialog.
=> ENH: Add AE title option to DIMSE export

Base/QTGUI/qSlicerApplication.cxx, Base/QTGUI/qSlicerApplication.h, Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx, Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.h, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.h
Fixes https://discourse.slicer.org/t/crash-on-selecting-point-properties-after-using-surface-cut/18234/2
=> Fix markups edit properties

Base/QTCore/qSlicerExtensionsManagerModel.cxx, Base/QTCore/qSlicerExtensionsManagerModel.h, Base/QTGUI/Resources/UI/qSlicerSettingsExtensionsPanel.ui, Base/QTGUI/qSlicerExtensionsInstallWidget.cxx, Base/QTGUI/qSlicerExtensionsManageWidget.cxx, Base/QTGUI/qSlicerExtensionsManagerWidget.cxx, Base/QTGUI/qSlicerSettingsExtensionsPanel.cxx, Base/QTGUI/qSlicerSettingsExtensionsPanel.h, Docs/user_guide/settings.md
Re-factor extensions manager integration anticipating support for new server.
* Update ExtensionsManagerModel API adding frontendServerUrl
* Support setting extensions server URLs using env. vars
* Update ExtensionsManager to support serverAPI selection
=> Update extensions manager to support server api selection and frontend backend configuration

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyParseLocalDataPlugin.h
See discussion here: https://discourse.slicer.org/t/python-called-qslicersubjecthierarchyparselocaldataplugin-function/18600
=> ENH: Make parse local data function accessible

Docs/developer_guide/script_repository.md
As suggested in this thread: https://discourse.slicer.org/t/model-hiearchy-visibility-returns-an-exception/18344/10
=> DOC: Add links and comments to script repository

SuperBuild/External_CTK.cmake
https://github.com/commontk/CTK/pull/983
Closes #5739
=> BUG: fix dicom import dialog box hang #5739

CMake/SlicerPackageAndUploadTarget.cmake
This commit removes support to upload to the deprecated midas based
server and makes the upload to the Girder based server required ensuring
it reports an error in case of upload failure.
=> COMP: Simplify application package upload logic removing midas support

Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.cxx
Within vtkMRMLScalarVolumeDisplayNode, scalar values are mapped using window/level to a unsigned char scalar range of 0 to 255.
While most color nodes in the scene use a range of 0 to 255, some nodes use different ranges (ex. RedGreenBlue uses -6.0 to 6.0).
In order to make full use of all colors in the table, we now copy the color node lookup table, and map it to the expected 0 to 255 scalar range from vtkImageMapToWindowLevelColors.
This commit also adds support for using the scalar range flag of UseDirectMapping to map the values of the image directly onto the scalar range of the table, bypassing the window/level.
=> ENH: Update scalar volume display to use full color node scalar range

Base/QTGUI/qSlicerWebWidget.cxx, Base/QTGUI/qSlicerWebWidget.h
Allows to print PDFs with custom margins
=> ENH: add QPageLayout argument to printToPdf method

CMakeLists.txt, Docs/developer_guide/build_instructions/linux.md, Docs/developer_guide/build_instructions/macos.md, Docs/developer_guide/build_instructions/windows.md
Updating to match factory build. This is a minimum recommended
version. Actual minimum usable version be less.
Update to Qt 5.15.0 after consultation with @sjh26 and @jcfr
=> COMP: Update Qt minimum required version

Modules/Scripted/DICOMLib/DICOMProcesses.py
in the incoming directory after DICOM network retrieval
=> ENH: DICOM - Added deletion of files

SuperBuild/External_ITK.cmake
=> ENH: Update ITK to 5.2.1

Docs/user_guide/about.md
=> DOC: Add text about licensing context

CMake/SlicerBlockInstallPython.cmake
=> BUG: Add missing Python3.dll to the install package

Base/QTCore/qSlicerExtensionsManagerModel.cxx
Fixes a regression introduced in e2ea8afa6 (BUG: Ensure extensions installed using "Girder_v1" serverAPI are enabled)
_Original  issue title and description edited by @jcfr_
=> Fix support for installing extensions from file 

Base/QTCore/Resources/Certs/Slicer.crt
This pull-request was auto-generated by the [update-slicer-certificate-bundle][1] GitHub action workflow.
[1]: https://github.com/Slicer/Slicer/blob/8a23e7aa76681025f54f1d7643f5977094b8a411/.github/workflows/update-slicer-certificate-bundle.yml
=> Update Slicer.crt CA bundle

Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserPlayWidget.h
=> DOC: Tweak qMRMLSequenceBrowserPlayWidget::recordingControlsVisible docstring

Base/QTCore/Resources/Certs/make-ca.sh, CMake/SlicerBlockInstallQt.cmake, CMake/vtkSlicerConfigure.h.in, CMakeLists.txt, SuperBuild/External_CTK.cmake
```
$ git shortlog 34a390a4..ec9fcee5 --no-merges
Sylvain Bernhardt (1):
ENH: Add Python wrapping for Qt multimedia component (PR-992)
```
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
=> ENH: Update CTK to include QtMultimedia Python wrappers

CMake/SlicerBlockPlatformCheck.cmake
I've updated some platform checks to latest requirements. These checks were very very out of date.
=> COMP: Update platform check based on latest requirements

Base/QTGUI/Testing/Cxx/qSlicerMouseModeToolBarTest1.cxx, Base/QTGUI/qSlicerMouseModeToolBar.cxx
This commit addresses issue [#5915](https://github.com/Slicer/Slicer/issues/5915). Cursor shape is now set from the selection node active place node class instead of the mouse mode toolbar actions removed in  09d12ae6f7598fe8490b691d17a35dcca5bd344a. qSlicerMouseModeToolBarTest1 is updated to remove tests of interaction between the selection node and removed mouse mode toolbar actions.
=> BUG: Restores mouse mode cursor shape

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode_Private.h
=> BUG: Fix memory leak related to JSON reading in vtkMRMLMarkupsJsonStorageNode

Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
=> COMP: Fix unknown escape sequence in vtkMRMLSequenceBrowserNode

Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx, Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py
Erasing a single segment would "add-back" the mask segment. When the selected segment and mask segment were the same, this would result in nothing changing. Fixed by only adding the mask segment back if it is not the selected segment.
See discussion: https://discourse.slicer.org/t/erase-using-a-segment-as-only-editable-area/20519
Also adds tests to SegmentationsModuleTest2.py to detect future regressions in masking behavior.
=> BUG: Fix erase when using the selected segment as mask

Modules/Loadable/Segmentations/Logic/CMakeLists.txt, Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationGeometryLogic.cxx, Modules/Loadable/Segmentations/Widgets/Resources/UI/qMRMLSegmentationGeometryWidget.ui, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationGeometryWidget.cxx
=> ENH: Allow using markups ROI for specifying segment geometry

Docs/developer_guide/script_repository/gui.md
Added a line of code that enables crosshair visibility
=> Updating script repository with a command to enable crosshair visibility

Modules/Scripted/DataProbe/DataProbeLib/Resources/UI/settings.ui, Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
The vtkPVScalarBarActor is left untouched.
It might be merged later with vtkSlicerScalarBarActor from Colors module.
=> ENH: ColorScalarBar is removed from DataProbe module as a part of Issue #6111

Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
This commit corrects a discrepancy in the jump mode indexes. This fixes a bug that [disabled the jump slices function from the markups table](https://discourse.slicer.org/t/markups-jump-slices-functionality-is-broken-on-preview/21602) and a bug that [prevented jumping to locked points](https://discourse.slicer.org/t/syncing-markups-edit-state-with-control-point-lock/21606/2?u=smrolfe).
=> BUG: Fixes broken control point table jump slice function

Modules/Scripted/DICOM/Resources/UI/DICOM.ui
existing label name		->	Updated label name
----------------------------------------------------------
label_5	->	labelLoadedData
label	->	labelPullDataFromRemoteServer
label_6	->	labelStorageListener
labe_7	->	labelStartStorageListenerOnStartup
label_8	->	labelDatabaseLocation
label_9	->	labelAutoHideBrowserWindow
label_10	->	labelMaintenance
For discussion please visit [https://discourse.slicer.org/t/how-to-access-dicom-widget-components/21844](https://discourse.slicer.org/t/how-to-access-dicom-widget-components/21844)
=> ENH: given meaningful names to labels

Libs/vtkITK/itkLevelTracingImageFilter.txx, Libs/vtkTeem/vtkTeemNRRDWriter.cxx, Modules/CLI/ExpertAutomatedRegistration/ITKRegistrationHelper/itkAnisotropicSimilarity3DTransform.h, Modules/CLI/ExpertAutomatedRegistration/ITKRegistrationHelper/itkAnisotropicSimilarity3DTransform.txx, Modules/CLI/ExpertAutomatedRegistration/ITKRegistrationHelper/itkAnisotropicSimilarityLandmarkBasedTransformInitializer.h, Modules/CLI/ExpertAutomatedRegistration/ITKRegistrationHelper/itkImageToImageRegistrationMethod.h, Modules/CLI/ExpertAutomatedRegistration/itkAnisotropicSimilarity3DTransformTest.cxx, Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DAbsCorrection.h, Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DNearestCorrection.h, Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DZeroCorrection.h, Modules/CLI/RobustStatisticsSegmenter/SFLSRobustStatSegmentor3DLabelMap_single.txx, Modules/CLI/RobustStatisticsSegmenter/SFLSSegmentor3D.txx
This applies a set of standard scripts that were created to update many ITK packages to make them consistent
with modern programming recommendations.
=> Default cleanups with scripts used to modernize ITK

Docs/developer_guide/modules/segmenteditor.md, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.h
=> ENH: added draw circle by border on scissors segmentation effect

SuperBuild.cmake
$ git shortlog ba4a56c..1059169
BUG: Fix Dynamic Modeler boundary cut with plane
=> BUG: Update SurfaceToolbox to fix Dynamic Modeler boundary cut

Base/QTApp/Resources/UI/qSlicerMainWindow.ui
Looking back to Slicer 4.0.0 I haven't been able to find when it was last working. If anyone has insights I can add it to the commit message.
=> ENH: Remove unused New Fiducial List action

Docs/user_guide/getting_started.md
After my own experience I felt this needed to be documented in the Getting Started page.
=> Fedora section in prerequisites

Docs/user_guide/getting_started.md
=> Add Fedora information

Base/QTGUI/qSlicerNodeWriter.cxx, Base/QTGUI/qSlicerSaveDataDialog.cxx
I came across some typos in some comments. I'm sure there are other typos around, but figured I'd submit these changes now.
=> DOC: Fix typos in some comments

Base/QTCore/Testing/Cxx/CMakeLists.txt, Base/QTCore/Testing/Cxx/Resources/qSlicerBaseQTCoreTesting.qrc, Base/QTCore/Testing/Cxx/qSlicerExtensionsManagerModelTest.cxx, Base/QTCore/Testing/Data/Input/30338_slicerheart_win_amd64_1db3627.json, Base/QTCore/qSlicerExtensionsManagerModel.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Modules/Loadable/Annotations/Testing/Cxx/CMakeLists.txt, Modules/Scripted/DICOMPlugins/DICOMGeAbusPlugin.py
3 steps closer to a green dashboard.
=> Fix qSlicerExtensionsManagerModelTest test, disable failing annotation tests

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationDisplayNodeWidget.cxx
Re https://discourse.slicer.org/t/bug-segmentation-opacity-not-updated-in-panel/22771
=> BUG: Fix update of overall opacity slider in Segmentations module

Docs/user_guide/extensions_manager.md, Docs/user_guide/getting_started.md
See discussion at https://discourse.slicer.org/t/extension-manager-in-linux-empty/22343/6 and issue #6293 for more details.
=> DOC: Describe solution for empty blank extensions manager on ArchLinux

Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx
This commit solves 2 issues:
- When loading scenes with a plane of area 0.0mm, the scale handle points were not fully initialized, which could cause a crash. Fixed by always initializing the points, and instead hiding the scale handles during UpdateHandleVisibility for planes with area 0.0mm.
- Scale handles were not displayed at the incorrect locations in 3D while the plane was being moved. Fixed by calling Superclass::UpdateInteractionPipeline() before updating the scale handle, ensuring that the HandleToWorldTransform was updated before calculating scale handle position.
=> BUG: Fix issues with Markups plane interaction scale handles

Docs/developer_guide/script_repository/gui.md
| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/166809385-a690ee57-2fb0-41ca-b834-587a9160f0c5.png) | ![image](https://user-images.githubusercontent.com/219043/166809743-d1e0ab0e-06a3-4669-905d-735a225a14d4.png) |
=> DOC: Fix heading associated with script repository "Gui" entries

Docs/developer_guide/debugging/linuxcpp.md
I figure this could be of help since it is a simple solution
=> Add debugging by following the forked process

Modules/Scripted/WebServer/WebServer.py, Modules/Scripted/WebServer/WebServerLib/DICOMRequestHandler.py, Modules/Scripted/WebServer/WebServerLib/SlicerRequestHandler.py, Modules/Scripted/WebServer/WebServerLib/StaticPagesRequestHandler.py
See https://github.com/Slicer/Slicer/runs/6398682294?check_suite_focus=true
=> Fix python lint issues in WebServer module

Docs/user_guide/modules/index.md, Docs/user_guide/modules/webserver.md
* Add "Panels and their use" section and remove "Current Features"
* Highlight security risks using "warning" directive
* Re-organize endpoint sections
=> DOC: Improve Webserver module documentation

Base/Python/slicer/tests/test_slicer_util_VTKObservationMixin.py, Base/Python/slicer/util.py
Fixes #6406.
This change modifies the implementation of `VTKObservationMixin` to use a `weakref.WeakKeyDictionary` rather than a flat list of registered observations. This allows observed vtkObjects to be garbage collected if all other references have been lost.
The registered events are stored in a nested dictionary structure to acheive constant-time access for `removeObserver`, `hasObserver`, etc. This also guarantees no observations are duplicated.
```
{obj: {event: {method: (group, tag, priority)}}}
```
The dictionary is stored in the attribute `__observations` (mangled to `__VTKObservationMixin_observations`). The property `Observations` is added as a list view of that dictionary, for backwards compatibility.
=> BUG: Fix VTKObservationMixin preventing observed nodes from being released

Base/QTCore/qSlicerExtensionsManagerModel.cxx
This commit fixes a regression introduced in ...
=> BUG: Fix installation of extension

Modules/Scripted/WebServer/WebServer.py
I discovered that the WebServer module fails to load if Slicer is built with the `Slicer_BUILD_DICOM_SUPPORT` option turned off because DICOMRequestHandler.py (part of WebServerLib) is imported at initialization which includes a top level import of `pydicom`. The `pydicom` module is part of the python-dicom-requirement superbuild project which is only included if `Slicer_BUILD_DICOM_SUPPORT` is turned on.
|With DICOM Support| This PR with no DICOM support|
|-----------------------|------------------------------------|
|![image](https://user-images.githubusercontent.com/15837524/171748879-237fc489-bc64-4315-bd78-e506836e95a4.png)|![image](https://user-images.githubusercontent.com/15837524/171748821-32ccc7ae-2efe-484d-8ab7-d20016a40617.png)|
=> BUG: Fix WebServer failing to load when Slicer built without DICOM support

Libs/MRML/Core/vtkMRMLSequenceNode.cxx
=> BUG: Fix copying of trimmed sequences

Base/Python/slicer/util.py, Base/QTGUI/qSlicerExportNodeDialog.cxx, Base/QTGUI/qSlicerIOManager.cxx, Base/QTGUI/qSlicerNodeWriter.cxx, Base/QTGUI/qSlicerSaveDataDialog.cxx, Libs/MRML/Core/vtkMRMLModelStorageNode.cxx
=> ENH: Log error details if slicer.util file read/write operation fails

Docs/index.md
(cherry picked from commit 1eee06cad5)
=> DOC: Remove "work in progress" disclaimer (#6479) [5.0 backport]

.codespellignore, .github/workflows/codespell.yml, Base/QTGUI/qSlicerExportNodeDialog.cxx, Libs/MRML/Widgets/qMRMLSliceView.cxx
Typo in `typeDisplayNameCollison` should be `typeDisplayNameCollision`
=> Fix source typo 

Base/QTCore/qSlicerExtensionsManagerModel.cxx, Base/QTGUI/qSlicerExtensionsLocalWidget.cxx, Libs/MRML/Logic/vtkMRMLAbstractLogic.cxx, Modules/Loadable/SlicerWelcome/Resources/UI/qSlicerWelcomeModuleWidget.ui, Modules/Loadable/SlicerWelcome/qSlicerWelcomeModuleWidget.cxx, Modules/Loadable/SlicerWelcome/qSlicerWelcomeModuleWidget.h
Enable automatic extension update check by deafult for new Slicer.ini files.
See discussion at https://discourse.slicer.org/t/enable-automatic-extension-update-check/25062
=> Auto update check

Docs/developer_guide/script_repository/dicom.md
Interface of CTK class `ctk.ctkDICOMQuery()` for retreiving queried InstanceUIDs has changed from `ctk.ctkDICOMQuery().studyInstanceUIDQueried` to `ctk.ctkDICOMQuery().studyAndSeriesInstanceUIDQueried`.
Cf. https://github.com/commontk/CTK/commit/34a390a49bc8e41e2ff8a6fe72382974c0787ad7
=> Adapt documentation to CTK interface change

Modules/Scripted/DICOM/DICOM.py, Modules/Scripted/DICOMLib/DICOMUtils.py, Modules/Scripted/WebServer/WebServerLib/DICOMRequestHandler.py
This allows retrieving images using the DICOMwebBrowser extension from a remote Slicer application.
=> ENH: Implement instance retrieval in DICOMweb request handler

Docs/developer_guide/script_repository/gui.md, Libs/MRML/Core/vtkMRMLCrosshairNode.h, Libs/MRML/DisplayableManager/vtkMRMLCrosshairDisplayableManager.cxx, Libs/MRML/DisplayableManager/vtkMRMLCrosshairDisplayableManager3D.cxx
This closes Slicer/Slicer#6439
=> ENH: Add functionality to change crosshair color

.pre-commit-config.yaml, Applications/SlicerApp/Testing/Python/DWMRIMultishellIOTests.py, Applications/SlicerApp/Testing/Python/ScriptedModuleCleanupTest.py, Applications/SlicerApp/Testing/Python/SlicerStartupCompletedTest.py, Modules/Loadable/Markups/Testing/Python/MarkupsInViewsSelfTest.py, Modules/Scripted/DICOMLib/DICOMPlugin.py, Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py, Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py
This is a manual trigger to autoupdate the pre-commit lint package versions and fixing the newly identified warnings. 
`python -m pre_commit autoupdate`.
This updating of the packages can be automated if the repository is externally linked to https://pre-commit.ci/. It would generated commits like https://github.com/Project-MONAI/MONAILabel/commit/e9745729a4263ac6c4f65c5c2211a4243b03cc78 and automatically issue a PR. A custom github actions workflow can also be created to schedule the autoupdate running and issuing of a PR just like https://pre-commit.ci/.
=> Update pre-commit lint packages to latest and fix identified warnings

Docs/user_guide/modules/dmriinstall.md, Modules/Scripted/DMRIInstall/DMRIInstall.py
Fixes #6593 by updating api and adding a .md doc.
=> BUG: fix/doc DMRIInstall

Modules/Scripted/WebServer/WebServerLib/DICOMRequestHandler.py
If a single instance was missing or had DICOM non-conformances then it could make an entire request fail. Fixed the issue by just logging any issues and skipping problematic items.
=> ENH: Make DICOM request handler in WebServer more robust

Docs/user_guide/modules/dynamicmodeler.md
=> DOC: Add user guide for Dynamic Modeler module

Docs/user_guide/modules/markups.md
=> DOC: Update Markups user guide

Docs/user_guide/modules/multivolumeexplorer.md, Docs/user_guide/modules/multivolumeimporter.md, Docs/user_guide/modules/simplefilters.md
=> DOC: Add documentation for MultiVolumeImporter and MultiVolumeExplorer modules

Docs/user_guide/modules/surfacetoolbox.md, SuperBuild.cmake
Describe "uniform remeshing" tool added in https://github.com/Slicer/SlicerSurfaceToolbox/commit/94957ef2c87438e6d21f6071a036232eb8119717 and integrated in Slicer through https://github.com/Slicer/Slicer/commit/c0b92b4359c3d4a3b449307741e1d7a2be99aedb
=> DOC: Update SurfaceToolbox documentation to include "uniform remeshing"

Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyLabelMapsPlugin.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx, Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.cxx, Modules/Loadable/Volumes/qSlicerVolumesModule.cxx, Modules/Loadable/Volumes/qSlicerVolumesReader.cxx
(cherry picked from commit 6cde2e3cbbb02ac34ae5fa8f3922c642e9e72c32)
Originally introduced through https://github.com/Slicer/Slicer/pull/6655
=> [5.2.1] STYLE: Mark translatable strings in Volumes module

Applications/SlicerApp/Testing/Python/CMakeLists.txt, Base/Python/slicer/parameterNodeWrapper/serializers.py, Base/Python/slicer/parameterNodeWrapper/validators.py, Base/Python/slicer/parameterNodeWrapper/wrapper.py, Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py, Libs/MRML/Core/vtkMRMLScriptedModuleNode.cxx
Fixes a few small bugs (and one tabbing inconsistency) in the parameter node wrapper.
=> Parameter node bugfixes

.github/workflows/commit-message.yml
See:
https://github.com/Slicer/Slicer/pull/6729
and
https://github.com/Slicer/Slicer/issues/6692
=> DOC: Improve error message for commit check

Docs/developer_guide/python_faq.md
This should help with questions like this: https://discourse.slicer.org/t/customizing-python-after-extension-wizard/26751/3
=> DOC: Add Qt connection documentation to Python FAQ

Docs/developer_guide/modules/volumerendering.md
follow-up from https://github.com/Slicer/Slicer/pull/6762
=> DOC: Describe how to add a volume rendering preset Slicer core

Base/QTCore/qSlicerAbstractCoreModule.cxx, Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreCommandOptions.cxx, Base/QTCore/qSlicerCoreIOManager.cxx, Base/QTCore/qSlicerExtensionsManagerModel.cxx, Base/QTCore/qSlicerSceneBundleReader.cxx, Base/QTGUI/qSlicerExtensionsManagerWidget.cxx
See https://github.com/Slicer/SlicerLanguagePacks/issues/12
=> STYLE: Mark translatable strings in Base/QTCore

CMake/SlicerConfig.cmake.in, CMake/SlicerFunctionAddPythonQtResources.cmake, CMakeLists.txt
This commit introduces `Slicer_QRCC_SCRIPT` variable to support using `slicerFunctionAddPythonQtResources()` from within Slicer extension.
=> COMP: Support using slicerFunctionAddPythonQtResources() in extension

SuperBuild/External_VTK.cmake
Backport changes associated with these two PRs:
* https://github.com/Slicer/Slicer/pull/6779
* https://github.com/Slicer/Slicer/pull/6780
=> [5.2] backport vtk updates

SuperBuild/External_VTK.cmake
References:
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/109
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/91
```
$ git shortlog 465e9dff6a..6efd97c519 --no-merges
[Backport MR-9892] ENH: Re-introduce support for custom logic handling VR complex gesture
```
=> BUG: Update VTK to restore support for complex gesture in SlicerVirtualReality

Base/Python/slicer/parameterNodeWrapper/guiConnectors.py, Base/Python/slicer/parameterNodeWrapper/parameterPack.py, Base/Python/slicer/parameterNodeWrapper/serializers.py, Base/Python/slicer/parameterNodeWrapper/wrapper.py, Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
Fixes a couple bugs that were found. Adds more testing.
=> Parameter node wrapper bugfixes

Base/QTGUI/qSlicerModuleFinderDialog.cxx, Base/QTGUI/qSlicerNodeWriter.cxx, Libs/MRML/Widgets/qMRMLTransformSliders.h, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Scripted/DICOMLib/SubjectHierarchyPlugins/qSlicerSubjectHierarchyDICOMPlugin.cxx
Minor fixes to remove false warning, improve translations, and Python wrapping.
=> Fixes of warnings and user messages

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
When a curve markup is copied using CopyContent the vtkMRMLMarkupsNode::RemoveAllMeasurements removes all measurements but the observations of the special curve measurements (calculated by vtkCurveMeasurementsCalculator) are not re-added. This commit adds these observations on CopyContent.
=> BUG: Fix issue with copying curve with CopyContent

Base/QTApp/qSlicerAboutDialog.cxx, Base/QTApp/qSlicerMainWindow.cxx
See https://github.com/Slicer/SlicerLanguagePacks/issues/12
=> STYLE: Mark translatable strings in Base/QTApp

Base/Python/slicer/parameterNodeWrapper/default.py, Base/Python/slicer/parameterNodeWrapper/guiConnectors.py, Base/Python/slicer/parameterNodeWrapper/parameterPack.py, Base/Python/slicer/parameterNodeWrapper/wrapper.py, Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py, Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py, Base/Python/slicer/tests/test_slicer_parameter_pack.py, Utilities/Templates/Modules/Scripted/Resources/UI/TemplateKey.ui, Utilities/Templates/Modules/Scripted/TemplateKey.py
Updates the TemplateKey to use the parameterNodeWrapper, including its gui connection capabilities.
Makes a few other small parameterNodeWrapper related updates.
=> Parameter node wrapper template key update

Applications/SlicerApp/Testing/Python/CMakeLists.txt, Base/Python/CMakeLists.txt, Base/Python/slicer/parameterNodeWrapper/__init__.py, Base/Python/slicer/parameterNodeWrapper/guiConnectors.py, Base/Python/slicer/parameterNodeWrapper/guiCreation.py, Base/Python/slicer/parameterNodeWrapper/wrapper.py, Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_gui_creation.py
Implements a GUI creation infrastructure that builds on the existing parameter node wrapper and its GUI connection infrastructure
=> Parameter node wrapper gui creation

Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMExportDialog.cxx
Previously only one plugin was stored within the QMap for a given mean confidence value. This commit changes the QMap to a QMultiMap so that multiple plugins with the same confidence can be displayed.
See discussion here: https://discourse.slicer.org/t/exporting-segmentation-as-dcm/28168
=> BUG: Allow multiple DICOM plugins for export with same mean confidence

Base/Python/CMakeLists.txt, Base/Python/slicer/parameterNodeWrapper/__init__.py, Base/Python/slicer/parameterNodeWrapper/guiConnectors.py, Base/Python/slicer/parameterNodeWrapper/guiCreation.py, Base/Python/slicer/parameterNodeWrapper/parameterPack.py, Base/Python/slicer/parameterNodeWrapper/types.py, Base/Python/slicer/parameterNodeWrapper/validators.py, Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_gui_creation.py, Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py, Base/Python/slicer/tests/test_slicer_parameter_pack.py, Docs/developer_guide/parameter_nodes/supported_types.md
Adds the ability to enforce invariants on parameterPacks.
Adds tests and documentation for enforcing said invariants.
Adds a `FloatRange` class to be used with `ctkRangeWidget`.
=> Parameter pack invariants + FloatRange

Base/Python/slicer/parameterNodeWrapper/__init__.py, Base/Python/slicer/parameterNodeWrapper/guiConnectors.py, Base/Python/slicer/parameterNodeWrapper/guiCreation.py, Base/Python/slicer/parameterNodeWrapper/parameterPack.py, Base/Python/slicer/parameterNodeWrapper/serializers.py, Base/Python/slicer/parameterNodeWrapper/validators.py, Base/Python/slicer/parameterNodeWrapper/wrapper.py, Docs/developer_guide/mrml_overview.md, Docs/developer_guide/parameter_nodes/overview.md
Relates https://github.com/Slicer/Slicer/issues/6870
=> DOC: Update parameter node documentation

Docs/user_guide/user_interface.md, Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.h
Small improvements to allow view manipulation during markup point placement.
=> View manipulation during markup point placement

Base/Python/CMakeLists.txt, Base/Python/slicer/i18n.py, Modules/Scripted/DICOM/DICOM.py, Modules/Scripted/SampleData/SampleData.py, Utilities/Scripts/update_translations.py
see Slicer/SlicerLanguagePacks#8
=> ENH: Add translation function for python scripted modules

Docs/index.md
=> DOC: update wording of old documentation link

Docs/index.md
Cherry picked from commit 7d0388b90 integrated through https://github.com/Slicer/Slicer/pull/6927
=> [5.2] DOC: Update wording of old documentation link

SuperBuild.cmake
Includes a single fix:
Revision: 3b556d10307c5c9ee9fd8da1ea873ddc1d48acf3
Date: 2022-11-26 3:34:57 PM
Message:
BUG: Fix DynamicModeler button layout
Sometimes buttons were shifted by one row.
=> BUG: Update SurfaceToolbox to fix Dynamic Modeler module layout

Modules/Scripted/DICOMPatcher/DICOMPatcher.py
DICOM patcher can now specify the character set if it was not set in the original DICOM file. (for example, if strings are stored using CP1251 code page then we can now read the strings from the DICOM file correctly and then save properly with UTF8 encoding).
A rule is added to fix non-integer XRayTubeCurrent value stored in IS value representation (http://dclunie.blogspot.com/2008/11/dicom-exposure-attribute-fiasco.html).
See discussion at https://discourse.slicer.org/t/patientname-and-rus-language-trouble/28870/4?u=lassoan
=> ENH: Add character set and exposure fix DICOM patcher rules

Modules/Scripted/DICOM/DICOM.py, Modules/Scripted/DICOMLib/DICOMBrowser.py, Modules/Scripted/DICOMPlugins/DICOMEnhancedUSVolumePlugin.py, Modules/Scripted/DICOMPlugins/DICOMGeAbusPlugin.py, Modules/Scripted/DICOMPlugins/DICOMImageSequencePlugin.py, Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py, Modules/Scripted/DICOMPlugins/DICOMSlicerDataBundlePlugin.py, Modules/Scripted/DICOMPlugins/DICOMVolumeSequencePlugin.py, Utilities/Scripts/update_translations.py
The previous commit had to go in without lint/spellchecker fixes to meet the nightly build deadline. This commit fixes up that commit.
=> BUG: Fix lint and spellchecker errors

Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentsPlugin.cxx, Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentsPlugin.h
https://user-images.githubusercontent.com/1325980/230777122-254432bc-54ce-4e13-8913-e2fb3d6c678d.mp4
=> ENH: Add option from subject hierarchy to set segment opacity

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx
I was not sure about the commit prefix so let me know if it should be STYLE or something else.
=> ENH: Avoid superfluous error message

Modules/Loadable/Data/qSlicerDataModule.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorEraseEffect.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect.cxx, Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx, Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx, Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentsPlugin.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationConversionParametersWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationDisplayNodeWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationFileExportWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationGeometryDialog.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationGeometryWidget.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationRepresentationsListView.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsModel.cxx, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsTableView.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsModule.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsNodeWriterOptionsWidget.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsSettingsPanel.cxx
See Slicer/SlicerLanguagePacks#12
=> BUG: Mark translatable strings in Segmentations module

Modules/Scripted/SegmentStatistics/SegmentStatistics.py, Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/ClosedSurfaceSegmentStatisticsPlugin.py, Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/LabelmapSegmentStatisticsPlugin.py, Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/ScalarVolumeSegmentStatisticsPlugin.py, Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/SegmentStatisticsPluginBase.py, Modules/Scripted/SegmentStatistics/SubjectHierarchyPlugins/SegmentStatisticsSubjectHierarchyPlugin.py
See Slicer/SlicerLanguagePacks#21
=> BUG: Mark translatable strings in SegmentStatistics module

Modules/Scripted/DataProbe/DataProbe.py
See Slicer/SlicerLanguagePacks#21
=> BUG: Mark translatable strings in DataProbe module

Base/Logic/vtkSlicerApplicationLogicRequests.h, Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCoreCommandOptions.cxx, Base/QTCore/qSlicerCoreCommandOptions.h, Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.cxx, Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h, Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx, Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserSeekWidget.cxx, Modules/Loadable/Sequences/Widgets/qMRMLSequenceEditWidget.cxx, Modules/Loadable/VolumeRendering/Widgets/qSlicerCPURayCastVolumeRenderingPropertiesWidget.cxx, Modules/Loadable/VolumeRendering/Widgets/qSlicerGPURayCastVolumeRenderingPropertiesWidget.cxx, Modules/Loadable/VolumeRendering/Widgets/qSlicerMultiVolumeRenderingPropertiesWidget.cxx, Modules/Loadable/VolumeRendering/qSlicerShaderPropertyReader.cxx, Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingModule.cxx, Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingReader.cxx, Modules/Scripted/ExtensionWizard/ExtensionWizardLib/ModuleInfo.py
See Slicer/SlicerLanguagePacks#12
=> BUG:marking string of volume rendering module in loadable

Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx, Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx, Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx, Modules/Loadable/Markups/qSlicerAnnotationsReader.cxx, Modules/Loadable/Markups/qSlicerMarkupsModule.cxx, Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx, Modules/Loadable/Markups/qSlicerMarkupsReader.cxx
=> Mark markups module

Applications/SlicerApp/Main.cxx, Applications/SlicerApp/qSlicerAppMainWindow.cxx, Base/QTApp/qSlicerApplicationHelper.cxx, Base/QTApp/qSlicerApplicationHelper.txx, Base/QTCore/qSlicerApplicationUpdateManager.cxx, Base/QTGUI/qSlicerAbstractModule.h, Base/QTGUI/qSlicerActionsDialog.cxx, Base/QTGUI/qSlicerApplication.cxx, CMakeLists.txt, Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneJsonStorageNode.cxx, Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROIJsonStorageNode.cxx, Modules/Loadable/SlicerWelcome/qSlicerWelcomeModuleWidget.cxx
CMAKE_LINK_DEPENDS_NO_SHARED ON avoids useless linking.
=> COMP: Speed up incremental build on Linux

Modules/CLI/AddScalarVolumes/AddScalarVolumes.xml
Add more information to "Add Scalar Volume" module's "Interpolation order" parameter documentation.
=> DOC: Improve "Interpolation order" parameter documentation

Base/Python/slicer/__init__.py, Docs/developer_guide/python_faq.md, Docs/developer_guide/slicer.md
This pull request adds the following entries:
* What is the Slicer Python Environment?
* What is the PythonSlicer executable?
* What is the Python Console?
* How to access Slicers Python API via an external program while Slicer is running?
Additionally, it update the Slicer API to document the following:
* `slicer.app`
* `slicer.mrmlScene`
* `slicer.modules`
* `slicer.moduleNames`
Summary of this pull request also posted on discourse at https://discourse.slicer.org/t/updated-python-faq-slicer-api-documentation/29967
<details><summary>Click here for preview screenshots</summary>
| | |
|--|--|
| Slicer API | ![image](https://github.com/Slicer/Slicer/assets/219043/312a9b3e-7e9c-4dd9-a5ac-7c71f858587d) |
| Python FAQ | ![image](https://github.com/Slicer/Slicer/assets/219043/9909a772-1c5d-4ad3- …
=> Improve Python FAQ

Docs/user_guide/modules/webserver.md, Modules/Scripted/WebServer/WebServerLib/DICOMRequestHandler.py
Add PatientID to params parsed
=> ENH: Add Parsed Parameters in DICOMRequestHandler

CMake/SlicerBlockInstallTBB.cmake, Libs/MRML/Core/vtkMRMLDiffusionWeightedVolumeDisplayNode.h, Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.h, Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx, Libs/MRML/DisplayableManager/vtkMRMLOrientationMarkerDisplayableManager.cxx, Libs/MRML/Logic/vtkMRMLRemoteIOLogic.h
Fixed some non user interfacing typos
=> STYLE: Fix various typos

Base/QTCore/qSlicerCoreApplication.cxx
The applicationLocale was always set to the default language (en-us).
=> BUG: Fix the application's applicationLocale object

Libs/MRML/Widgets/qMRMLLayoutManager.cxx, Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx
Possible fix for issue #6827. Some minor bugs can be still present.
=> BUG: Fix color legend visibility on non-standard slice views

Docs/developer_guide/build_instructions/linux.md, Docs/developer_guide/build_instructions/windows.md, Docs/developer_guide/debugging/windowscpp.md, Docs/developer_guide/extensions.md
Update build instructions as suggested by @jcfr in https://github.com/NousNav/NousNav/issues/355#issuecomment-1601495014
=> DOC: Update build instructions in windows.md

Base/Python/slicer/util.py, Base/QTApp/Resources/UI/qSlicerMainWindow.ui, Base/QTApp/qSlicerMainWindow.cxx, Base/QTApp/qSlicerMainWindow.h, Base/QTApp/qSlicerMainWindow_p.h, SuperBuild/External_CTK.cmake
ref https://discourse.slicer.org/t/log-window-cannot-be-hidden-in-enviroments-with-no-windows-manager/29633
@pieper @lassoan @jamesobutler can you please review? thanks!
=> ENH: Make ctk ErrorLogWidget dockable

Base/Python/slicer/ScriptedLoadableModule.py, Base/QTGUI/qSlicerSettingsGeneralPanel.cxx, Docs/developer_guide/python_faq.md
Follow-up from https://github.com/Slicer/Slicer/pull/7074
=> STYLE: Fix wording in comments

Modules/Loadable/Colors/qSlicerColorsReader.cxx, Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.cxx, Modules/Loadable/Markups/qSlicerMarkupsReader.cxx, Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx, Modules/Loadable/Sequences/qSlicerSequencesReader.cxx, Modules/Loadable/Terminologies/qSlicerTerminologiesReader.cxx, Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx
Fixes for small errors uncovered by linting.
=> Lint fixes

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx
=> BUG: Fix "Restore view layout" view context menu action

Utilities/Scripts/update_translations.py
update_translations.py can now create source translation file (MyExtension_en-US.ts) for any extension. The process of making an extension translatable is described at https://github.com/Slicer/SlicerLanguagePacks/blob/main/DevelopersManual.md#how-to-make-an-extension-translatable
see https://github.com/Slicer/SlicerLanguagePacks/issues/29
=> ENH: Allow update_translations.py to create new translation components

SuperBuild/External_CTK.cmake
Follow up to https://github.com/commontk/CTK/pull/1126 to incorporate that change into Slicer
```
List of CTK Changes:
$ git shortlog 1feb498..2b16f9d
James Butler (2):
STYLE: Trim whitespace
BUG: Fix inability to customize ctkRangeSlider filled color
```
=> COMP: Update CTK to fix styling of ctkRangeSlider

SuperBuild/External_CTK.cmake
```
$ git shortlog 2b16f9dff..ee5508d6e --no-merges
James Butler (2):
COMP: Update C++ source files removing code specific to Qt 4
ENH: Remove custom CTK Dialog options
COMP: Revert removal of custom CTK Dialog options
```
=> COMP: Update CTK removing code specific to Qt 4

Docs/developer_guide/mrml_overview.md
Make a few grammatical and syntactical changes, but no change in information.
=> DOC: Copy edits to mrml_overview.md

Docs/developer_guide/script_repository/gui.md, Docs/developer_guide/script_repository/models.md, Docs/developer_guide/script_repository/plots.md
This pull request was created while reviewing:
* https://github.com/Slicer/Slicer/pull/6913
=> DOC: Consistently reference slicer.util.pip_install usage example

Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
This pull request was created while working on this issue:
* https://github.com/Slicer/Slicer/issues/7092
=> ENH: Support saving and restoring SliceViewAnnotations display level

.github/workflows/ci.yml, .github/workflows/lint.yml
|Before | After |
|---|---|
| ![image](https://github.com/Slicer/Slicer/assets/219043/d0fc53e4-96bd-4cf6-883f-8439d82752f2) | ![image](https://github.com/Slicer/Slicer/assets/219043/987b9f83-e257-4f1b-a05f-6998dfa91dba) | 
| ![image](https://github.com/Slicer/Slicer/assets/219043/aa46d2ba-6598-43d9-a55d-21df6d9c4e7a) | ![image](https://github.com/Slicer/Slicer/assets/219043/ab220ed7-0532-456c-be2e-b7fa20645600) |
=> STYLE: Disambiguate CI workflow names adding "(Build)" and "(Lint)" suffix

.github/workflows/scorecard.yml
See https://github.com/ossf/scorecard-action#authentication-with-fine-grained-pat-optional
=> ENH: Update OSSF scorecard workflow to support running Branch-Protection check

README.md
Add build CI badge to `README`.
=> ENH: Add build CI badge to `README`

Libs/vtkSegmentationCore/vtkSegmentation.cxx
When a segment that is in the same layer as other segments is removed from a vtkSegmentation, it causes the shared labelmap to be modified. This triggered a SourceRepresentationModified on the remaining segments, which invalidated non-source representations. Fixed by calling SetSourceRepresentationModifiedEnabled(false) before editing the labelmap, and restoring the original value after.
Fixes #7220
=> BUG: Fix closed surface disappearing when segment is removed

Extensions/Testing/ScriptedLoadableExtensionTemplate/ScriptedLoadableModuleTemplate/ScriptedLoadableModuleTemplate.py, Extensions/Testing/ScriptedSegmentEditorEffectExtensionTemplate/ScriptedSegmentEditorEffectModuleTemplate/SegmentEditorScriptedSegmentEditorEffectModuleTemplate.py, Modules/Loadable/Models/qSlicerModelsModule.cxx, Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingModule.cxx, Modules/Scripted/CropVolumeSequence/CropVolumeSequence.py, Modules/Scripted/DMRIInstall/DMRIInstall.py, Modules/Scripted/Endoscopy/Endoscopy.py, Modules/Scripted/ImportItkSnapLabel/ImportItkSnapLabel.py, Modules/Scripted/SampleData/SampleData.py, Modules/Scripted/ScreenCapture/ScreenCapture.py, Modules/Scripted/SegmentEditor/SegmentEditor.py, Modules/Scripted/SelfTests/SelfTests.py, Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py, Utilities/Templates/Modules/Scripted/TemplateKey.py, Utilities/Templates/Modules/ScriptedSegmentEditorEffect/SegmentEditorTemplateKey.py
Marked strings that were found to be non-translatable in https://github.com/Slicer/SlicerLanguagePacks/issues/41
=> BUG: Make more strings translatable

Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.cxx, Libs/vtkITK/vtkITKArchetypeImageSeriesReader.cxx
This pull request contains fixes for two independent problems that caused Slicer crashes.
=> Fix crashes in subject hierarchy and DICOM reading

Libs/vtkSegmentationCore/vtkSegmentationHistory.cxx
During undo/redo, representations could be added or removed from the segment, however the "Show 3D" would not be updated. Fixed by invoking ContainedRepresentationNamesModified on the segmentation if the current and restored representation lists are different.
Fix #7246
=> BUG: Fix "Show 3D" button not updating during undo/redo

Libs/MRML/Core/vtkMRMLSliceDisplayNode.h, Libs/MRML/Core/vtkMRMLSliceNode.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.h, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionRepresentation2D.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.h, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Libs/MRML/Logic/vtkMRMLSliceLinkLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx, Libs/MRML/Widgets/qMRMLSliceControllerWidget.h, Libs/MRML/Widgets/qMRMLSliceControllerWidget_p.h, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.h
Related issue:
* #7083
This pull request updates the Slice Interaction widget for adjusting the thickness of the slab for Thick Slab Reconsturction (TSR).
=> Update Intersection Widget to Display Slab Thickness

Base/Python/slicer/parameterNodeWrapper/guiConnectors.py, Docs/developer_guide/parameter_nodes/gui_connection.md, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Scripted/DICOMLib/DICOMUtils.py
=> BUG: Small fixes 20231005

Base/Python/slicer/parameterNodeWrapper/guiConnectors.py, Docs/developer_guide/parameter_nodes/gui_connection.md, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Scripted/DICOMLib/DICOMUtils.py
Following discussion in https://github.com/Slicer/Slicer/pull/7262#issuecomment-1749625461, the integration of https://github.com/Slicer/Slicer/pull/7262 into `main` was reverted by force-pushing so that it be re-integrated though `Merge & Rebase`.
This allows us to keep a more descriptive history.
=> BUG: Small fixes 20231005 (for rebase & merge)

Libs/MRML/DisplayableManager/vtkMRMLThreeDViewInteractorStyle.cxx
Instead of relying on the CurrentRenderer ivar internally updated by the "vtkInteractorStyle::FindPokedRenderer()", we explicitly retrieve and use the poked renderer with "vtkRenderWindowInteractor::FindPokedRenderer()"
=> ENH: Update MRML interactor style to explicitly use the poked renderer

Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
- return statement was called after `StartModify` but before `EndModify`
Replace instances of:
```cpp
int wasModified = this->StartModify();
...
this->EndModzfy(wasModified);
```
with:
```cpp
MRMLNodeModifyBlocker blocker(this);
```
Supercedes: https://github.com/Slicer/Slicer/pull/7327
=> BUG: AddSynchronizedSequenceNodeID caused browser to stop operating correctly

Docs/user_guide/modules/sceneviews.md
Facilitate visual parsing of the raw markdown files replacing literal "\n" with actual newlines.
=> DOC: Update sceneviews.md replacing literal \n with newline

Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/AbstractScriptedSegmentEditorEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/AbstractScriptedSegmentEditorLabelEffect.py, Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/AbstractScriptedSegmentEditorPaintEffect.py
These were identified while working on a larger set of improvements for:
* enforcing docstring style
* adding generation of module specific API
Here is a preview of the module specific API that will be integrated as part of a different pull request:
=> DOC: Improve layout of AbstractScriptedSegmentEditorEffect docstrings

Docs/developer_guide/build_instructions/linux.md
add instruction for lunar lobster
=> DOC: Add instructions for setting up development environment on Ubuntu 23.04

Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.cxx, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.h, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
Re https://discourse.slicer.org/t/problems-filtering-subject-hierarchy-tree/32435/5
=> Improve documentation of obsolete filtering API in SH proxy model

Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx, Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationControlPointsNode.h, Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationControlPointsStorageNode.cxx, Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationFiducialNode.h, Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationLinesNode.h, Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationLinesStorageNode.cxx, Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationNode.h, Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationRulerStorageNode.cxx, Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationStorageNode.cxx
Fix miscellaneous grammar and typos.
=> STYLE: Fix miscellaneous grammar and typos

Modules/Scripted/Endoscopy/Endoscopy.py
Changes include:
- BUG: Lazily rebuild flythrough if input curve is modified
- BUG: Stop a modification to the input curve from triggering a second modification event
- BUG: Allow the user to specify the name of the model to be created
- BUG: Correct names of vtk.vtkMath functions
- DOC: Use "flythrough" as noun; "fly through" as verb
- DOC: Remove use of degree symbol
- STYLE: Remove explicit set of widget as not collapsed.
- STYLE: Don't instantiate \_\_del\_\_ when it defaults appropriately
- STYLE: Use `p` instead of `ctr` for center position of plane
=> BUG: Fix rebuild of Endoscopy flythrough when modifying the input curv

Modules/Scripted/Endoscopy/Endoscopy.py
The logic for when to loadCameraOrientations and recompute EndoscopyLogic fields was not working in all cases.  The lazy approach to loading and recomputing could have been modified to fix this, but we did not pursue this approach because the lazy approach has a flaw: the user interface (e.g. number of frames available) should be available immediately, not lazily (e.g. only once the user starts a flythrough).
=> BUG: Recompute EndoscopyLogic fields immediately instead of lazily

Modules/Loadable/SubjectHierarchy/Widgets/Python/CMakeLists.txt, Modules/Loadable/SubjectHierarchy/Widgets/Python/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py, Modules/Loadable/SubjectHierarchy/Widgets/Python/SubjectHierarchyPlugins/__init__.py, Modules/Scripted/SegmentEditor/SubjectHierarchyPlugins/__init__.py, Modules/Scripted/SegmentStatistics/SubjectHierarchyPlugins/__init__.py
* Slicer/SlicerLanguagePacks#52
* Slicer/SlicerLanguagePacks#21
=> BUG: Fix context change at runtime in DICOM module

Modules/Loadable/Sequences/Widgets/qMRMLSequenceEditWidget.cxx
In Sequences module's Edit tab, data node candidate node list ("Add/remove data nodes") sometimes remained empty. Fixed the issue by more robustly checking if the list needs to be updated.
Also fixed a minor issue in auto-advance not working when adding the first data node to the sequence.
=> BUG: Fix empty candidate node list in Sequences module

Docs/user_guide/coordinate_systems.md
Minor rewording for clarity and grammatical correctness, hopefully not changing the meaning.
=> DOC: Minor rewording of coordinate_systems.md

Modules/Scripted/SampleData/SampleData.py
Previously, `VolumeFile` type was used by default if type was not explicitly specified for a sample data item. Since readers can now provide confidence value, the default type is most often correct and it is no longer necessary to specify file type.
=> ENH: Do not require file type in sample data specification

Docs/user_guide/data_loading_and_saving.md
follow up on https://github.com/QIICR/QuantitativeReporting/pull/274#issuecomment-1897812838
=> update the list of supported formats

SuperBuild/External_CTK.cmake
The update includes two commits to improve the visual DICOM browser
Revision: 888cdd92b7d5d465ed7e6b378deb99e10a801588
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-01-18 10:06:25 AM
Message:
ENH: Add ctkDICOMJobListWidget for logging jobs activity in the UI
The commit also includes these fixes and improvements:
- fix updates in the series widget when the update signal is from ctkDICOMStoregeListener (i.e. CMOVE)
- fix folder selector in ctkDICOMVisualBrowser, save folder selection to QSettings
- remove unnecessary re-rendering of the thumbnails
Revision: 8d358c696e3cc53bd56dfbdb248174def9889b0f
Author: Davide Punzo <punzodavide@hotmail.it>
Date: 2024-01-22 11:05:50 AM
Message:
PERF: Remove unnecessary logging information from ctkDICOMDatabase class
=> ENH: Update CTK to latest

Base/QTApp/qSlicerApplicationHelper.txx
Follow-up of edfbdb492 (ENH: Allow dragging of splashwindow), this commit further improves the `DraggableWidgetEventFilter` to support dragging the Splashwindow without having to release the mouse button and re-pressing it.
Since just after the mouse button is pressed and before it is released, mouse events are associated with a "QWidgetWindow" instance named after "<objectname>Window" if the widget object name is set or after "<classname>ClassWindow" if the object name is empty (See `QWidgetWindow::updateObjectName`[^1]).
To ensure events from either are being filtered, the event filter should be installed at the application level.
Change locally tested on Linux and macOS
[^1]: https://github.com/qt/qtbase/blob/v5.15.2/src/widgets/kernel/qwidgetwindow.cpp#L1151-L1158
=> ENH: Support dragging of the splashwindow just after clicking on it

Docs/developer_guide/script_repository/segmentations.md
Add an example script to documentation of Slicer-5.6 stable.
=> [5.6] DOC: Add example script for resampling segmentation to higher resolution

Libs/MRML/Widgets/qMRMLNodeComboBox.cxx, Libs/MRML/Widgets/qMRMLNodeComboBox.h
Fixes #6002
Additional minor improvements
=> BUG: Fixed issue with adding new node after rename cancelation

Modules/Scripted/DICOMPatcher/DICOMPatcher.py, Modules/Scripted/DICOMPlugins/DICOMImageSequencePlugin.py
Add DICOM patcher rule to split ultrasound series and read pixel spacing for single-region ultrasound images.
@ungi
=> ENH: Improve ultrasound reading

Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx, Utilities/Scripts/update_translations.py
* Slicer/SlicerLanguagePacks#43
=> ENH: Add translation for VolumeDisplayPresets.json

Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyGenericSelfTest.py, Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
The old behavior cause "currentItemChanged" signal to be emitted event if at the end of this method call the selected items stay the same.
=> BUG: SHTree setCurrentItems do not deselect items before selecting them again

Modules/Scripted/DICOMPatcher/DICOMPatcher.py
Previously DICOM patcher's rule that modified a character set only changed those files that did not have any encoding set. However, files emerged that contained incorrectly set "ISO_IR 100" encoding value. So, the rule is now set to force setting the requested encoding for all files, except if the encoding is already UTF8.
See https://discourse.slicer.org/t/patientname-and-rus-language-trouble/28870/4 for details.
=> ENH: Make characterset modifier DICOM patcher rule stronger

Docs/developer_guide/script_repository/gui.md
I stumbled upon this problem and couldn't find it in the forum or in the script repository (I also created a [post](https://discourse.slicer.org/t/how-to-show-a-fiducial-in-only-specified-views/35682/2) on discourse)
=> DOC: Update gui.md with example on how to display a node in only some views

Libs/MRML/Core/Testing/vtkMRMLVolumeArchetypeStorageNodeTest1.cxx, Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt, Libs/vtkSegmentationCore/Testing/vtkSegmentationTest2.cxx
Fixed vtkMRMLVolumeArchetypeStorageNodeTest1 and MRMLDisplayableManagerCxxTests test failures.
=> Fix test failures

Libs/MRML/Widgets/Testing/qMRMLThreeDWidgetTest1.cxx, SuperBuild.cmake
Two minor updates - see details in commit comments
=> Update surface toolbox and improve a test

Libs/MRML/Core/vtkMRMLVolumeNode.cxx
Reading of tensor images (such as DTIBrain sample data set) crashed Slicer. The root cause was that the image used a left-handed coordinate system, the recently added image orientation normalization function tried to flip the image, but the underlying vtkImageReslice filter crashes if the scalar point data in the input image is nullptr (which is the case for tensor images, where the tensor point data is valid but scalar point data is invalid).
Fixed by setting the array that contains the data to the scalar array for the time of running vtkImageReslice.
Fixes py_CompareVolumes test failure.
=> BUG: Fix tensor image reading

Docs/user_guide/user_interface.md
#7770 Adding documentation for existing Ctrl + left-click + drag feature
=> add documentation for ctrl + left-click + drag

SuperBuild.cmake, SuperBuild/External_CTK.cmake, SuperBuild/External_ITK.cmake, SuperBuild/External_SimpleITK.cmake, SuperBuild/External_SlicerExecutionModel.cmake
Pending merge of the following PRs:
I will set the correct upstreams instead of my forks.
=> ENH: Update ITK to 5.4.0

SECURITY.md
Added high-level security guidelines - inspired by the discussion at https://discourse.slicer.org/t/cybersecurity-questions/36946
=> DOC: Add notes to SECURITY.md

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsTableView.h
This is needed to use the SegmentationVerification extension
=> ENH: Make SegmentsTableView functions available from Python

CMake/SlicerBlockPlatformCheck.cmake, SuperBuild/External_tbb.cmake
See https://discourse.slicer.org/t/tbb-dll-problem-with-new-version-of-visual-studio/36936
=> COMP: Update acceptable VS2022 MSVC version for TBB install

SuperBuild/External_ITK.cmake
```
$ git shortlog --group=author --group=trailer:co-authored-by aacaefd63..e18566d53 --no-merges
Matt McCormick (2):
[Backport] BUG: Update HDF5 name mangled symbols
[Backport] DOC: Improve itk_hdf5_mangle.h.in instructions
```
See https://github.com/Slicer/ITK/compare/aacaefd63...e18566d53
This is expected to address errors like the following reported when importing itk python package from a Linux Preview build of Slicer:
```
Thread 1 "SlicerApp-real" received signal SIGSEGV, Segmentation fault.
0x00007f34d7a3d58f in H5::Exception::~Exception() ()
from /path/to/Slicer-5.7.0-2024-06-04-linux-amd64/bin/../lib/Slicer-5.7/libitkhdf5_cpp-shared-5.4.so.1
(gdb) where
#0  0x00007f34d7a3d58f in H5::Exception::~Exception() ()
from …
```
=> BUG: Update ITK to fix HDF5 symbol clash when import itk wheel

Docs/developer_guide/script_repository/webserver.md
Add missing `:::` for note section
=> DOC: Fix WebServer script repository formatting

Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsInteractionWidgetRepresentation.cxx
Interaction handles for Markups nodes would not take ViewNodeIDs, folder visibility, and 2D/3D visibility flags into account when determining visibility. Fixed by checking the visibility options in IsDisplayable.
Fix #7865
=> BUG: Fix markups interaction handles not respecting visibility options

Libs/MRML/Core/vtkMRMLSliceCompositeNode.cxx, Libs/MRML/Core/vtkMRMLSliceCompositeNode.h, Libs/MRML/Logic/vtkMRMLSliceLinkLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx, Libs/MRML/Widgets/qMRMLSliceControllerWidget.h, SuperBuild/External_VTK.cmake
=> ENH: Allow disabling layers blend clipping to background in slice views

Libs/MRML/DisplayableManager/vtkMRMLWindowLevelWidget.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Modules/Loadable/Sequences/Resources/UI/qSlicerSequencesModuleWidget.ui, Modules/Loadable/Sequences/qSlicerSequencesReader.cxx
Allow loading sequences created by dcm2niix and few small fixes.
=> Improve sequence detection

Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
This fixes the parsing of window level/center from DICOM when the values are (pair) arrays.
=> BUG: Fix reading of multiple window/level presets in DICOMScalarVolumePlugin

Docs/developer_guide/script_repository/dicom.md, Modules/Scripted/DICOMLib/DICOMBrowser.py, SuperBuild/External_CTK.cmake
New PR for visual DICOM browser enhancements. This is a work in progress.
Depends on:
https://github.com/commontk/CTK/pull/1217
=> Visual dicom browser enhs

Base/Python/slicer/parameterNodeWrapper/guiConnectors.py, Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py, Docs/developer_guide/parameter_nodes/gui_connection.md
Supersedes https://github.com/Slicer/Slicer/pull/7499
=> Add parameter node GUI wrappings for certain CTK and other classes

Base/Python/slicer/util.py
=> DOC: Improve slicer.util.pip_install documentation

SuperBuild/External_CTK.cmake
Revision: 2d99b4ee14537748f2237a3586f5c700960627e8
Author: Davide Punzo <punzodavide@hotmail.it>
Date: Thu Sep 26 11:49:45 2024 +0200
Message:
BUG: Fix error log filtering in ctkErrorLogWidget
https://github.com/commontk/CTK/pull/1221
@lassoan
=> BUG: Update to latest CTK

Docs/user_guide/data_loading_and_saving.md, Modules/Loadable/Sequences/qSlicerSequencesReader.cxx, Modules/Loadable/Transforms/qSlicerTransformsReader.cxx, Modules/Loadable/Transforms/qSlicerTransformsReader.h
Improves automatic detection of segmentation and NIFTI transform files.
=> Improve file format detection

Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
Fix regression reported in
https://github.com/Slicer/Slicer/issues/7984
@jamesobutler @lassoan
=> BUG: Fix fit slice view if no background volume is selected

Base/QTCLI/vtkSlicerCLIModuleLogic.cxx
This commit resolves errors when writing Markup nodes set as CLI output of type `point` to `.fcsv` files. It reintroduces support for the `.fcsv` format, ensuring compatibility similar to the fix in commit 889d98ebda ("BUG: Fix writing markups input for CLI modules", 2021-02-01).
Example error:
```
[VTK] vtkMRMLMarkupsJsonStorageNode::ReadDataInternal: Error: Error parsing the file '/tmp/Slicer-jcfr/BJDHB_vtkMRMLMarkupsFiducialNodeB.fcsv'
[VTK] vtkMRMLStorageNode::ReadData: Failed to read node F (vtkMRMLMarkupsFiducialNode1) from filename='/tmp/Slicer-jcfr/BJDHB_vtkMRMLMarkupsFiducialNodeB.fcsv'
```
Reported-by: @dzenanz
=> BUG: Restore support for writing CLI output as .fcsv files

Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h
Per https://discourse.slicer.org/t/unexpected-interactions-of-roi-objects-with-code/40053/3
=> DOC: Clarify doc of vtkMRMLMarkupsROINode::GetObjectToWorldMatrix

Applications/SlicerApp/Testing/Python/SliceLinkLogic.py, Base/Python/slicer/util.py, Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx, Libs/MRML/Logic/vtkMRMLApplicationLogic.h, Libs/MRML/Logic/vtkMRMLSliceLinkLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h, Libs/MRML/Widgets/qMRMLLayoutManager.h, Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx, Modules/Loadable/Markups/Testing/Python/MarkupsInCompareViewersSelfTest.py, Modules/Loadable/Markups/Testing/Python/NeurosurgicalPlanningTutorialMarkupsSelfTest.py, Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx, Modules/Loadable/Sequences/qSlicerSequencesReader.cxx, Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx, Modules/Loadable/Volumes/qSlicerVolumesReader.cxx, Modules/Scripted/DICOMPlugins/DICOMImageSequencePlugin.py, Modules/Scripted/WebServer/WebServerLib/SlicerRequestHandler.py
Fixed and fit slice to volume and made it work consistently for both when background clipping is enabled (default) or disabled.
=> Fix fit slice to volume

Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.cxx
When right clicking in a view to call "toggleInteractionBox()", the current subject hierarchy ID was sometimes invalid, causing nothing to happen. Fixed by getting the transform node from "getTransformNodeForAction()", which works in both SH widgets and in views.
Also ensures that all context menu widgets are updated in "showViewContextMenuActionsForItem()".
=> BUG: Fix interaction handle enable/disable not working in views

Libs/MRML/Logic/vtkMRMLSliceLogic.cxx, Libs/MRML/Logic/vtkMRMLSliceLogic.h
See discussion here: https://discourse.slicer.org/t/slicer-preview-crashes-on-slicer-util-resetsliceviews/40488/4
=> BUG: Check for null pointer before fitting volume

Modules/Scripted/ScreenCapture/ScreenCapture.py
Reported via weblate: https://hosted.weblate.org/translate/3d-slicer/3d-slicer/en/?checksum=906c3eb816def890#comments
=> BUG: Fix typo in message

Docs/developer_guide/build_instructions/windows.md
- Qt 5.15.2 installation requires additional steps in the universal installer
=> windows.md: update qt5 install instructions

Libs/MRML/Core/vtkMRMLScene.cxx
When a scene mrb file had space before the file extension, for example "myscene .mrb" then on Windows the scene failed to save and load. The issue is due to the folder inside the .mrb file ended with a space ("myscene /"), which kwsys did not handle correctly (due to some Windows file API not supporting it).
This commit fixes saving by removing the trailing space from the internal folder name. It also fixes loading of corrupted scenes created by earlier Slicer versions, by returning with a warning (because the internal folder cannot be deleted) instead of bailing out with an error.
=> BUG: Fix loading and saving .mrb files with trailing space in filename

Libs/MRML/Core/vtkEventBroker.cxx
=> STYLE: Remove unused variable

Docs/user_guide/user_interface.md
=> DOC: Add documentation for help menu

Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorGrowFromSeedsEffect.py
I corrected a simple spelling mistake in the helpText function.
=> Corrected typo SegmentEditorGrowFromSeedsEffect.py

Base/Logic/vtkSlicerApplicationLogic.cxx, Base/Logic/vtkSlicerApplicationLogic.h, Base/QTCLI/vtkSlicerCLIModuleLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx, Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h
After #8105, #8193, and this PR are integrated, I believe the only remaining obstacle to turning `ITK_LEGACY_REMOVE` on is another update of `BRAINSTools` (after it gets updated to compile with `ITK_LEGACY_REMOVE` on).
Fixes warnings like the following:
```
/path/to/Slicer/Base/Logic/vtkSlicerApplicationLogic.cxx: In destructor ‘virtual vtkSlicerApplicationLogic::~vtkSlicerApplicationLogic()’:
/path/to/Slicer/Base/Logic/vtkSlicerApplicationLogic.cxx:99:73: warning: ‘void slicer_itk::PlatformMultiThreader::TerminateThread(slicer_itk::ThreadIdType)’ is deprecated [-Wdeprecated-declarations]
99 |     this->ProcessingThreader->TerminateThread( this->ProcessingThreadId );
|                                                                         ^ …
```
=> COMP: Use std::thread instead of deprecated ITK threading functions

SuperBuild.cmake
```
$ git shortlog 3f317421d..8c43b66ed --no-merges
AlexyPellegrini (1):
ENH: Replace WIN32 with _WIN32 to fix build with Ninja (#51)
Ebrahim Ebrahim (1):
BUG: Fix matrix comparisons for exact equality (#54)
```
=> ENH: Update vtkAddon

Libs/MRML/Core/vtkMRMLVolumeNode.cxx
Print a warning when tryng to get a volume node to observe a vtkImageData that has a non-identity affine (i.e. origin isn't (0,0.0), or spacing isn't (1,1,1), or direction matrix isn't identity)
Closes #6911
=> ENH: Warn when setting volume node with invalid vtkImageData

Docs/user_guide/user_interface.md
Backport from #8169
---
Closes #7634
(cherry picked from commit 40c77ef9cfd5ef095a25abd3ec261d2c35ed62d3)
=> [5.8] DOC: Add documentation for help menu

Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
This PR refactors `vtkMRMLSliceLogic::UpdatePipeline()` to fully utilize the **Nth Layer API**.  
- Instead of handling background, foreground, and label layers separately, iterate over all defined layers dynamically.
- Replace explicit volume retrieval (`GetBackgroundVolumeID()`, etc.) with `GetNthLayerVolume(layerIndex)`.
- Replace hardcoded layer logic updates with `SetNthLayerVolumeNode(layerIndex, volumeNode)`.
- Remove redundant variable assignments for `backgroundImagePort`, `foregroundImagePort`, and `labelImagePort`.
- Pass `GetNthLayerImageDataConnection(layerIndex)` directly into `Pipeline->AddLayers()` and `PipelineUVW->AddLayers()`.
> [!NOTE]
> This PR is part of a broader effort to generalize and expand Slicer's multi-layer rendering capabilities.
> Future work includes:
>
> …
=> ENH: Refactor vtkMRMLSliceLogic::UpdatePipeline to use "Nth Layer" API

Modules/Loadable/Transforms/Testing/Cxx/qSlicerTransformsModuleWidgetTest.cxx
The Transforms module widget now uses a Subject Hierarchy tree widget, which requires initialization of the subject hierarchy module. This was missing from the test, therefore the Transforms module widget test failed. Fixed by adding subject hierarchy module initialization to the test.
=> BUG: Fix qSlicerTransformsModuleWidgetTest

SuperBuild/External_VTK.cmake
=> ENH: Update VTK (vtkMultiVolume bounds computation fix)

Libs/MRML/Core/vtkMRMLTransformNode.cxx
If parent transform(s) got hardened on an inverted composite transform then the resulting transform was incorrect.
The problem was that the hardened transform components were concatenated to the inverted transform and when Update()
was called on that transform then it was updated from the original (non-inverse) transform, removing all concatenations.
Fixed the problem by creating a new composite transform when a transform is hardened on an inverted composite transform.
fixes https://github.com/Slicer/Slicer/issues/8355
@che85
=> Fix hardening of inverted composite transform

Libs/MRML/Widgets/Resources/UI/qMRMLScreenShotDialog.ui, Modules/Loadable/SceneViews/GUI/qSlicerSceneViewsModuleDialog.cxx, Modules/Loadable/SceneViews/GUI/qSlicerSceneViewsModuleDialog.h, Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx, Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.h
This commit adds UpdateNthSceneView functions to update the contents of an existing scene view. These functions can be used to update individual nodes, or replace the content of scene views with the state of the current scene.
=> ENH: Add functions to update the contents of existing scene views

SuperBuild.cmake
Update the hash for [LandmarkRegistration](https://github.com/Slicer/LandmarkRegistration)
```
$ git shortlog aa23730..a205287 --no-merges
Sébastien Goll (2):
ENH: Add dialog selector for transformed volume and transform
BUG: Fix the reveal cursor not untoggling
```
=> COMP: Update LandmarkRegistration module to latest

Applications/SlicerApp/Testing/Python/JRC2013Vis.py, Applications/SlicerApp/Testing/Python/RSNAQuantTutorial.py, Applications/SlicerApp/Testing/Python/RSNAVisTutorial.py
This PR is a collection of fixes after reviewing tracebacks in automated testing output.
=> A collection of traceback fixes in automated tests

Utilities/SetupForDevelopment.sh
This change updates the maximum allowed line length in the git pre-commit hook from 160 to 180 characters in anticipation of adopting `clang-format`, where the `ColumnLimit` will be set to 180.
The new limit strikes a reasonable balance between maintaining readability and supporting formatting automation across the codebase.
This aligns with prior work in commit 78b5306058 ("ENH: Update maximum line length from 160 to 180", 2025-07-10).
For reference, here is a distribution of line lengths collected across the repository:
```
$ /path/to/line_length_histogram.sh 180
Line Length Histogram:
0-  9: 200244
10- 19: 40583
20- 29: 44773
30- 39: 52417
40- 49: 46224
50- 59: 40752
60- 69: 42380
70- 79: 45884
80- 89: 24880
90- 99: 11373
100-109: 7368
110-119: 4941
120-129: 3078
130-139: 1816
140-149: …
```
=> ENH: Increase git hook maximum line length from 160 to 180

Base/QTCore/qSlicerCoreApplication.cxx, Base/QTCore/qSlicerCorePythonManager.cxx
Fixes regression introduced in:
- 7a26aa1b87 ("ENH: Update Python initialization for compatibility with isolated mode")
- 3bace0b4b6 ("ENH: Update Python initialization to use PyConfig API")
These changes inadvertently introduced multiple and inconsistent Python initializations by removing the use of deprecated symbols (`PySys_SetArgvEx`, `Py_NoUserSiteDirectory`) without fully replicating their intended behavior. As a result, over 100 tests failed (e.g., `AttributeError: module 'qt' has no attribute 'QTimer'` on Ubuntu) due to Python being initialized both too late and with conflicting settings.
This commit restores correct initialization behavior by:
1. Initializing Python early in `qSlicerCorePythonManager` using the `PyConfig` API. Rather than explicitly setting `config.isolated = 0`, …
=> BUG: Fix improper Python initialization causing inconsistent interpreter state

Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorThresholdEffect.py
Rendering the Segment Editor effect threshold preview in slice views that are no longer visible or have no volume in the foreground or background layer is unnecessary. A warning had been spamming the log about this situation, but this commit replaces it by handling creation and deletion of preview pipelines as the layout manager state changes.
To replicate the spammy log message I was observing, copy the following into a new session of Slicer:
```python
slicer.mrmlScene.Clear()
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutThreeOverThreeView)
slicer.app.processEvents()
volumeNode = SampleData.SampleDataLogic().downloadMRHead()
slicer.util.selectModule("SegmentEditor")
slicer.modules.SegmentEditorWidget.editor.findChild(qt.QPushButton, …
```
=> ENH: Remove unnecessary threshold preview pipeline in unused views

Docs/user_guide/modules/index.md, Docs/user_guide/modules/lineprofile.md, Modules/Scripted/CMakeLists.txt, Modules/Scripted/LineProfile/CMakeLists.txt, Modules/Scripted/LineProfile/LineProfile.py, Modules/Scripted/LineProfile/Resources/Icons/LineProfile.svg, Modules/Scripted/LineProfile/Resources/UI/LineProfile.ui, Modules/Scripted/LineProfile/Testing/CMakeLists.txt, Modules/Scripted/LineProfile/Testing/Python/CMakeLists.txt
As specified in the conversation https://github.com/PerkLab/SlicerSandbox/pull/36
This PR adds the Line Profile module into Slicer core.
=> ENH: Add line profile module

Libs/vtkITK/vtkITKImageSequenceReader.cxx, Libs/vtkITK/vtkITKImageSequenceReader.h, Libs/vtkITK/vtkITKImageSequenceWriter.cxx
Fixes linux build errors introduced in recent commit (11df881b46c907c92947ae89d1ffb3ef9cd95142).
=> COMP: Fix linux build errors

Libs/MRML/Core/vtkMRMLScene.cxx
Sequences that don't need data nodes can be saved as `.seq.mrml` files since the recent commit "PERF: Improve sequence node storage performance for simple nodes" (cd151177ac8e27ae61e619b657e5bcc992fa9070). However, these `.mrml` files can be mistaken for the main scene file when loading a scene from an `.mrb` file, causing the scene loading to silently fail (loading only a single sequence instead of all the nodes).
This commit makes finding the main scene `.mrml` file more robust: the `.mrml` file that is the closest to the root of the zip archive will be used as the main scene file.
Thanks to @che85 for reporting the issue.
=> BUG: Make mrb file loading more robust

Applications/SlicerApp/Testing/Python/CMakeLists.txt, Base/Python/slicer/tests/test_slicer_util_childWidgetVariables.py, Base/Python/slicer/util.py
=> BUG: childwidgetvariables do not return an object with an empty attribute
