- .github/ISSUE_TEMPLATE/release.md
- Docs/conf.py
This reverts commit a3b7544ec (`BUG: Update sphinx custom 404 page to handle redirect of vX.Y URL without slash`) and instead update the readthedoc configuration setting up the redirect:
```
/en/v5.0$rest -> /en/5.0
```
instead of
```
/en/v5.0/$rest -> /en/5.0/
```
Related issues and pull requests:
* https://github.com/readthedocs/readthedocs.org/issues/9507#issuecomment-1322888048
* https://github.com/Slicer/Slicer/pull/6504
> BUG: Remove custom handling for redirect of vX.Y URL without slash

- Base/Python/slicer/util.py
Without this fix there can be situation in which when `columnNames` are provided, but no `title`, the name of the created series is not affected. I would expect that column names would be used as `seriesNode` names.
I tested this fix in my Slicer installation and it worked.
Fixes #6671
> ENH: Use column name for plot title when none specified

- .gitignore
- Base/QTCLI/qSlicerCLIModule.cxx
- Base/QTCLI/qSlicerCLIModule.h
- Base/QTCLI/qSlicerCLIModuleUIHelper.cxx
- Base/QTCLI/qSlicerCLIModuleWidget.cxx
- Base/QTCLI/qSlicerCLIModuleWidget.h
- Docs/_extracli/DWIConvert.xml
- Libs/MRML/CLI/vtkMRMLCommandLineModuleNode.cxx
- Utilities/Scripts/update_translations.py
From CLI .xml files _generate_translation_header_from_cli_xml() (in update_translations.py) creates .h files that Qt lupdate tool recognizes. For example: Modules\CLI\ACPCTransform\ACPCTransform_tr.h is created with this content:
// Generated automatically by update_translations.py from ACPCTransform.xml
QT_TRANSLATE_NOOP("qSlicerAbstractCoreModule", "Registration")
QT_TRANSLATE_NOOP("qSlicerAbstractCoreModule", "Specialized")
QT_TRANSLATE_NOOP("CLI_ACPCTransform", "ACPC Transform")
...
QT_TRANSLATE_NOOP("CLI_ACPCTransform", "Input landmarks")
QT_TRANSLATE_NOOP("CLI_ACPCTransform", "Anatomical landmarks that will be used for computing the ACPC transform.")
qSlicerCLIModule* classes use `CLI_<modulename>` context to retrieve translations.
The *_tr.h files are placed into the source tree to …
> ENH: Make all text in built-in CLI modules translatable

- .github/ISSUE_TEMPLATE/release.md
Integrates changes collected while working on the 5.2.0 release.
In **Installers Release** checklist:
* Add posting of "Announce release is in progress" on discourse
* Move "Disable regular nightly builds" after finalizing extensions fixes
* Move "Create maintenance branch" earlier and remove redundant entry
* Remove hard-coded `5.0` values. Since the developer is expected to replace the occurrences of `X.Y`, the created issue will be self-explanatory.
In **Post Release** checklist:
* Remove "Create release" step already done in "Installers Release" checklist
* Add dedicated wiki section for copying packages. See https://github.com/Slicer/Slicer/wiki/Release-Process#copy-draft-application--extension-packages-into-the-new-release-folder
> DOC: Tweak "release" issue template

- .github/ISSUE_TEMPLATE/patch-release.md
- .github/ISSUE_TEMPLATE/release.md
Integrates changes collected while working on the `5.2.1` patch release.
Split **Patch Release** into **Installers Release** and **Post Release** to mirror the [release](https://github.com/Slicer/Slicer/blob/main/.github/ISSUE_TEMPLATE/release.md) issue template.
-------------
In **Installers Release** checklist:
* Add update of `Release in progress` post See https://github.com/Slicer/Slicer/wiki/Release-Process#update-release-in-progress-post
* Add "Disable regular nightly builds"
* Remove the update of the Slicer version information for the development. This is irrelevant in the context of patch releases since the commit are directly added to the X.Y maintenance branch.
* Move update of "Release Details" into this section.
-------------
In **Post Release** checklist:
* Add "Re-enable of …
> DOC: Tweak "patch-release" issue template

- .flake8
- .pre-commit-config.yaml
- Base/Python/slicer/util.py
Base/Python/slicer/util.py:3481: [F401] 'logging' imported but unused
Introduced in https://github.com/Slicer/Slicer/commit/f9dcc53b560a5f1d3f933a81c514175aed65a127
`ENH: Update pre--commit hook versions to latest` manually updates the hooks. An automated method of updating these has not been completed and is work captured in #6599.
> STYLE: Fix python linting issue

- .github/ISSUE_TEMPLATE/patch-release.md
- .github/ISSUE_TEMPLATE/release.md
* Add lines to visually separate each sections.
* Update submitting instructions to include `YYYY-MM-DD`
* Split "Update readthedocs" across multiple lines
* Add dedicated wiki section for "Upload signed release packages".
See https://github.com/Slicer/Slicer/wiki/Release-Process#upload-signed-release-packages
* Fix punctuation of checklist entries.
See https://www.instructionalsolutions.com/blog/bulleted-list-punctuation
This commit updates the process to leverage download server improvement ensuring that packages marked as "pre release" are not offered for download.
It updates the process by:
- moving "Create release" before initiating the packages generation.
- removing the need for copying application & extension packages from `draft` into the new release.
- adding a step for updating …
> Improve "release" and "patch-release" issue templates

- Libs/MRML/Core/vtkMRMLParser.cxx
For module names that contain multiple "Node" substrings, For example: vtkMRMLROS2NodeNode, the previous implementation using .find() would be restrictive. Considering that the logic is to check whether the className ends with "Node" from the end ( using .rfind() ) is better.
> BUG: Update vtkMRMLParser to support custom type ending with "Node" string

- .flake8
- Applications/SlicerApp/Testing/Python/CMakeLists.txt
- Base/Python/CMakeLists.txt
- Base/Python/slicer/parameterNodeWrapper/__init__.py
- Base/Python/slicer/parameterNodeWrapper/default.py
- Base/Python/slicer/parameterNodeWrapper/serializers.py
- Base/Python/slicer/parameterNodeWrapper/util.py
- Base/Python/slicer/parameterNodeWrapper/validators.py
- Base/Python/slicer/parameterNodeWrapper/wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Docs/developer_guide/index.md
- Docs/developer_guide/mrml_overview.md
- Docs/developer_guide/parameter_nodes.md
- Libs/MRML/Core/vtkMRMLScriptedModuleNode.cxx
- Libs/MRML/Core/vtkMRMLScriptedModuleNode.h
- Modules/Scripted/VectorToScalarVolume/CMakeLists.txt
- Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py
Adds a Python parameter node wrapper that offers access to typed properties instead of going through strings and manually serializing/deserializing to string manually.
Adds tests for the wrapper.
Updates VectorToScalarVolume to use new parameter node as an example of use (the tests also serve as example).
I have added a `parameter_nodes.md` file documenting purpose, usage, and extensibility, but would like recommendations on where would be good to link to it from.
Closes https://github.com/Slicer/Slicer/issues/6665
> Parameter node wrapper

- Base/QTCLI/qSlicerCLIProgressBar.cxx
- Base/QTCLI/vtkSlicerCLIModuleLogic.cxx
- Base/QTCLI/vtkSlicerCLIModuleLogic.h
- Libs/MRML/CLI/vtkMRMLCommandLineModuleNode.cxx
- Libs/MRML/CLI/vtkMRMLCommandLineModuleNode.h
Previously, CLI output was only displayed when execution completed.
Now, if StartContinuousOutputUpdate() is called on the CLI module node then the CLI module logic will keep updating the output in the node (until EndContinuousOutputUpdate() is called). Multiple components can call Start/EndContinuousOutputUpdate - the continuous update will remain effect until all EndContinuousOutputUpdate is called for each StartContinuousOutputUpdate.
This is used in every CLI module's GUI (progress detail double-arrow button) and it can be used for monitoring the output in Python scripts (for example, update a transform in real-time based on transform parameters that the module prints on its output - as discussed in https://discourse.slicer.org/t/question-about-registration/26507/7).
> ENH: Allow getting process output during CLI execution

- Utilities/Templates/Modules/Scripted/TemplateKey.py
Whenever the user leaves the template module, the parameter node observers are removed. If the module is entering after that, setParameterNode() will attempt to remove the observer again, and throw a warning message.
Fixed by checking if the observer exists before removing in setParameterNode().
See: https://discourse.slicer.org/t/warning-of-observer-from-scripted-module-in-slicer-5-0-3/
> BUG: Fix scripted module template observer warning

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Libs/MRML/Logic/vtkMRMLSliceLogic.h
- Libs/MRML/Widgets/CMakeLists.txt
- Libs/MRML/Widgets/DesignerPlugins/CMakeLists.txt
- Libs/MRML/Widgets/DesignerPlugins/qMRMLSliceVerticalControllerWidgetPlugin.cxx
- Libs/MRML/Widgets/DesignerPlugins/qMRMLSliceVerticalControllerWidgetPlugin.h
- Libs/MRML/Widgets/DesignerPlugins/qMRMLWidgetsPlugin.h
- Libs/MRML/Widgets/Resources/UI/qMRMLSliceVerticalControllerWidget.ui
- Libs/MRML/Widgets/Resources/UI/qMRMLSliceWidget.ui
- Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLSliceControllerWidget.h
- Libs/MRML/Widgets/qMRMLSliceControllerWidget_p.h
- Libs/MRML/Widgets/qMRMLSliceVerticalControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLSliceVerticalControllerWidget.h
- Libs/MRML/Widgets/qMRMLSliceWidget.cxx
- Libs/MRML/Widgets/qMRMLSliceWidget.h
- Libs/MRML/Widgets/qMRMLSliceWidget_p.h
- Libs/MRML/Widgets/qMRMLSliderWidget.cxx
- Libs/MRML/Widgets/qMRMLSliderWidget.h
This adds a vertical slice controller slider to slice widgets.
In default it is not visible, and it can be shown with:
`slicer.app.layoutManager().sliceWidget("Red").setShowSliceVerticalOffsetSlider(True)`
The horizontal slide selector (or the whole slice controller) can then be hidden:
`slicer.app.layoutManager().sliceWidget("Red").sliceController().hide()`
> ENH: add simple vertical slice controller widget

- Modules/Scripted/SampleData/SampleData.py
Fixes the issue of clipped labels in Sample Data module by using the default icon size as a basis, which is more robust than computing it relative to window size.
Before the fix:
After the fix:
Tested on both large desktop and small laptop screens.
> BUG: Fix sample data set labels not appearing on large desktop monitors

- Base/Python/slicer/parameterNodeWrapper/default.py
- Base/Python/slicer/parameterNodeWrapper/serializers.py
- Base/Python/slicer/parameterNodeWrapper/util.py
- Base/Python/slicer/parameterNodeWrapper/validators.py
- Base/Python/slicer/parameterNodeWrapper/wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Docs/developer_guide/parameter_nodes.md
Adds support for `tuple[type1, type2, type3, ...]` and `dict[keyType, valueType]`.
Adds an `ObservedDict` similar to the `ObservedList`. I did not think an `ObservedTuple` was  needed due to the immutability of `tuple`s.
> Parameter node wrapper support for tuple and dict

- Base/Python/slicer/util.py
Issue: https://github.com/Slicer/Slicer/issues/6741
Topic: https://discourse.slicer.org/t/bug-slicer-util-loadvolume-crashes-when-given-a-pathlib-path-instead-of-a-string/26820
> ENH: Use objects with __str__ as a filename

- CMake/SlicerBlockCTKAppLauncherSettings.cmake
This commit is a follow-up of 7960e2d28 (BUG: Fix blank Extensions manager on Linux due to Chromium sandboxing).
It ensures that the launcher settings associated with the generated package also set the QTWEBENGINE_DISABLE_SANDBOX environment variable.
Fixes #6577
> BUG: Fix blank Extensions manager for Linux package due to Chromium sandboxing

- Base/QTCore/qSlicerCoreApplication.cxx
Fix compilation with `Slicer_USE_PYTHONQT_WITH_OPENSSL` set to `OFF` by addressing a regression introduced in ea2e6f0fc (ENH: Add https support to vtkHTTPHandler).
> COMP: Fix build with OpenSSL support disabled

- Modules/Loadable/Markups/qSlicerMarkupsModule.cxx
Fixes issue reported at https://discourse.slicer.org/t/markups-save-to-defaults-colors-misremembered/26732
> BUG: Fix reading of default markup active color

- Modules/Scripted/WebServer/WebServerLib/SlicerRequestHandler.py
When Slicer web API was used for loading nodes but the reader did not return any node ID then the API call returned with error.
> BUG: Fix SlicerRequestHandler return value when reader does not return any node ID

- Libs/MRML/Widgets/Resources/UI/qMRMLSliceWidget.ui
- Libs/MRML/Widgets/qMRMLSliceWidget.cxx
- Modules/Loadable/Data/qSlicerSceneReader.cxx
Fixes the two failing tests. Both tests were due to subtle errors introduced by the recently added vertical slice offset slider feature (https://github.com/Slicer/Slicer/commit/2ed9451921d937f2a73d846bd1bf19b956478492).
Also fixed a extension list difference reporting when an incompatible scene is loaded.
> Fix 2 failing tests

- Docs/user_guide/modules/volumes.md
- Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.cxx
- Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.h
- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Libs/MRML/Widgets/Resources/UI/qMRMLWindowLevelWidget.ui
- Modules/Loadable/Volumes/Widgets/Resources/UI/qSlicerScalarVolumeDisplayWidget.ui
- Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.cxx
- Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.h
| Slicer 5.2.1 | This PR |
|--------|---------|
|![image](https://user-images.githubusercontent.com/15837524/210019102-b270a764-cab7-4cfe-9ab4-b71ba66761c9.png)|![image](https://user-images.githubusercontent.com/15837524/210019156-a5aa166c-d4dc-413f-ac80-9dddad8115e6.png)|
- Display presets now have a group section which is titled to indicate they are presets. The section is moved to the top as the presets change multiple display settings below (window/level/colormap)
- Window/Level locked state removed
- Window/Level widget reorganized with familiarity of Threshold widget
- Window/Level and Threshold widgets contained in a groupbox for improved clarification about which objects are for W/L vs objects for Threshold.
- Additional tooltips added to widgets in the Display section so users …
> Volumes module Display options improvements and fixes

- Libs/MRML/Widgets/qMRMLTransformSliders.cxx
This closes #6735.
Changing spinbox values of sliders was adding duplicate references into the ActiveSliders QStack.
The expected behavior from the documentation is mentioned below and it was previously not being respected.
https://slicer.readthedocs.io/en/latest/user_guide/modules/transforms.html#edit
> "Note: Linear transform edit sliders only show relative translation and rotation because a transformation can be achieved using many different series of transforms. To make this clear to users, only one transform slider can be non-zero at a time (all previously modified sliders are reset to 0 when a slider is moved). The only exception is translation sliders in “translate first” mode (i.e., when translation in global/local coordinate system button is not depressed): in this case there is …
> BUG: Fix more than one rotation slider can be non-zero

- Libs/MRML/Core/vtkMRMLAbstractViewNode.h
- Libs/MRML/Core/vtkMRMLCameraNode.h
- Libs/MRML/Core/vtkMRMLDiffusionWeightedVolumeNode.h
- Libs/MRML/Core/vtkMRMLModelDisplayNode.h
- Libs/MRML/DisplayableManager/vtkMRMLAbstractWidgetRepresentation.h
- Libs/MRML/DisplayableManager/vtkMRMLInteractionEventData.h
- Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.h
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.h
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionRepresentation2D.h
- Libs/MRML/Logic/vtkMRMLSliceLogic.h
- Libs/vtkSegmentationCore/vtkPolyDataToFractionalLabelmapFilter.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.h
VTK Python wrapper requires a size hint in the header file (such as "VTK_SIZEHINT(3)") to be able to return a double* pointer as a float vector. This commit adds the missing size hints.
Example:
print(slicer.mrmlScene.GetFirstNodeByClass('vtkMRMLCameraNode').GetPosition())
Returns a raw pointer without size hint:
_00000272e44bc7b0_p_void
Returns a vector if a size hint is added to the method declaration:
(0.0, 500.0, 0.0)
> ENH: Add missing array size hints for better Python wrapping

- Base/Python/slicer/parameterNodeWrapper/serializers.py
- Base/Python/slicer/parameterNodeWrapper/validators.py
- Base/Python/slicer/parameterNodeWrapper/wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_pack.py
- Docs/developer_guide/parameter_nodes.md
Adds support for `typing.Union`.
Uses better suited exception types.
Minor cleanup.
> Parameter node wrapper support for typing.Union

- Docs/user_guide/about.md
- Due to ceasing its operations, Pixel Medical is removed from the commercial partners list
- Add some details to the Ebatinca commercial partner
> DOC: Remove Pixel Medical from commercial partners

- SuperBuild/External_VTK.cmake
This commit re-introduces the API removed in kitware/VTK@9bd64d666 (Cleanup and rework of the VRInteractorStyle and subclasses).
This OpenVR specific API allows SlicerVirtualReality extension to query the state of trackers.
```
$ git shortlog 97a187572d..c333750383 --no-merges
[SlicerVirtualReality] ENH: Re-introduce OpenVR API for retrieving last OpenVR pose
```
This should help address issue reported in https://github.com/KitwareMedical/SlicerVirtualReality/issues/91
> BUG: Update VTK to reintroduce OpenVR API for retrieving last pose

- SuperBuild/External_VTK.cmake
Backport of https://github.com/Slicer/Slicer/pull/6754
----
This commit re-introduces the API removed in kitware/VTK@9bd64d666 (Cleanup and rework of the VRInteractorStyle and subclasses).
This OpenVR specific API allows SlicerVirtualReality extension to query the state of trackers.
```
$ git shortlog 97a187572d..c333750383 --no-merges
[SlicerVirtualReality] ENH: Re-introduce OpenVR API for retrieving last OpenVR pose
```
> [5.2] BUG: Update VTK to reintroduce OpenVR API for retrieving last pose

- Base/Python/slicer/parameterNodeWrapper/serializers.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Docs/developer_guide/parameter_nodes.md
- Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py
Add an `EnumSerializer` which stores enums by their name and enforces that only valid instances of that enum may be serialized.
This grants static analysis support to certain existing uses of `Option` validator or `Union` type. Serializing by name also enables attaching metadata to particular enum values.
---
Updated _Vector to Scalar Volume_ module to use `Enum` for its conversion method parameter.
Note the new enum and parameter node definitions:
https://github.com/allemangD/Slicer/blob/9ea61e53281631e9177ce1f34faa8eb53bf0be4e/Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py#L83-L103
And populating the `methodSelectorComboBox` using the enum metadata:
https://github.com/allemangD/Slicer/blob/9ea61e53281631e9177ce1f34faa8eb53bf0be4e/Modules/Scripted/VectorToScalarVolume/Vecto …
> Add Enum support to parameterNodeWrapper

- Base/QTGUI/qSlicerExtensionsLocalWidget.cxx
Without this change I get this build error on my linux build:
```
[ 40%] Building CXX object Base/QTGUI/CMakeFiles/qSlicerBaseQTGUI.dir/qSlicerExtensionsLocalWidget.cxx.o
/home/pieper/slicer4/latest/Slicer/Base/QTGUI/qSlicerExtensionsLocalWidget.cxx: In member function ‘void {anonymous}::qSlicerExtensionsDescriptionLabel::labelText(const QString&)’:
/home/pieper/slicer4/latest/Slicer/Base/QTGUI/qSlicerExtensionsLocalWidget.cxx:423:10: error: ‘QLatin1Literal’ {aka ‘class QLatin1String’} has no member named ‘arg’
423 |         .arg(this->WarningColor)
|          ^~~
/home/pieper/slicer4/latest/Slicer/Base/QTGUI/qSlicerExtensionsLocalWidget.cxx:431:10: error: ‘QLatin1Literal’ {aka ‘class QLatin1String’} has no member named ‘arg’
431 |         .arg(this->WarningColor)
|          ^~~
make[2]: …
```
> COMP: put literal after string format for translation

- SuperBuild/External_VTK.cmake
This commit is a follow up of 294ef47edb (BUG: Update VTK to reintroduce OpenVR API for retrieving last pose)
```
$ git shortlog c333750383..b74591f27e --no-merges
[SlicerVirtualReality] BUG: Ensure a valid OpenVR pose is returned
```
> BUG: Update VTK to ensure a valid OpenVR pose is returned

- SuperBuild/External_VTK.cmake
```
$ git shortlog b74591f27e..465e9dff6a --no-merges
Alexy Pellegrini (6):
[Backport] Fix typo in action name for nextcamerapose
[Backport] Remove squeeze force from VTK OpenXR Actions
[Backport] Rename handposehandgrip and bind action for it. Remove it for HTC Vive
[Backport] Remove "thickcropstart" and "thickcropdirection" actions
[Backport] Prevent memory leak in vtkOpenXRRemotingRenderWindow
[Backport] Add lock around vtkOpenXRRemotingRenderWindow::CopyResultFrame
Mathieu Westphal (1):
[Backport] Fix XR/VR related warnings
```
> ENH: Update VTK to backport OpenXR and OpenXRRemoting changes

- Docs/user_guide/user_interface.md
- Libs/MRML/Core/vtkMRMLAbstractViewNode.cxx
- Libs/MRML/Core/vtkMRMLAbstractViewNode.h
- Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLSliceControllerWidget_p.h
Sagittal plane offset direction label "R" was incorrect: moving the slider to the right did not move the slice in "R" direction (while for axial and coronal slices, moving the slider to the right moved the slice according to the direction specified in the label).
Instead of changing the incorrect "R" label to "L", this commit removes the hardcoded labels and instead computes the correct label dynamically. If the slice normal direction is not aligned with an axis then the label contains a combination of directions. The order of axes reflects the dominance of the axis. For example, if the plane normal points to anterior and slightly left then the label is AL.
fixes #6778
> BUG: Fix computation of offset direction label in slicer view controller

- Base/Python/slicer/util.py
Qt doesn't offer users any way to resize a message box, even when the detailedText field is displayed with lots of text. I didn't find a good way to resize programmatically either.
This is a problem with something like a python stack trace is displayed and the word wrapping makes it hard to read.
This workraound makes the title artificially bigger so that the message box size is wider than normal.
> ENH: make error report box bigger

- Libs/MRML/Core/vtkMRMLTableStorageNode.cxx
- Modules/Loadable/Tables/Logic/vtkSlicerTablesLogic.cxx
- Modules/Loadable/Tables/Logic/vtkSlicerTablesLogic.h
- Modules/Loadable/Tables/qSlicerTablesReader.cxx
A table schema specifies metadata about each column of a table. It may also have a special row `<default>`. Unlike other rows, the default row does not correspond to a column of the table, instead representing the default properties of the table's columns.
`vtkMRMLTableStorageNode` was not taking this into account when reading a table from file, so I added a check which skips the `<default>` row when loading a table's columns.
Steps to reproduce:
- Create new table
- Under "New Column Defaults", set "Data type" to another type such as "Double"
- Add values to the table
- Save table
- Load table from file
> BUG: Load table with default column type

- Libs/MRML/Core/vtkITKTransformConverter.h
- Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx
When ITK reads a vector field from NIFTI image, it changes the index to physical to IJKToLPS, but it does not reorient the vectors from RAS to LPS. This commit handles the special case when reading a vector field from NIFTI format.
Future ITK versions might reorient the vectors - in that case this special case handling should be removed from here.
This will allow reading displacement fields in NIFTI file format, for example, created by VoxelMorph. Currently, VoxelMorph writes an invalid NIFTI file, but it should be fixed soon (see https://github.com/voxelmorph/voxelmorph/issues/438).
> BUG: Fix reading of vector fields from NIFTI files

- Base/QTCore/qSlicerAbstractCoreModule.cxx
- Base/QTCore/qSlicerExtensionsManagerModel.cxx
This fixes regressions introduced in https://github.com/Slicer/Slicer/commit/1031050a0a677381ff40030a218702cd45fda668 (BUG: Mark translatable strings in Base/QTCore).
To catch issue like the one associated with the return type, we are also looking into marking `-Wreturn-type` as an error so that the CI effectively fails.
> Fix i18n qt base regressions

- Applications/SlicerApp/Testing/Python/CMakeLists.txt
- Base/Python/CMakeLists.txt
- Base/Python/slicer/parameterNodeWrapper/__init__.py
- Base/Python/slicer/parameterNodeWrapper/guiConnectors.py
- Base/Python/slicer/parameterNodeWrapper/parameterInfo.py
- Base/Python/slicer/parameterNodeWrapper/parameterPack.py
- Base/Python/slicer/parameterNodeWrapper/util.py
- Base/Python/slicer/parameterNodeWrapper/wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py
- Base/Python/slicer/tests/test_slicer_parameter_pack.py
- Docs/developer_guide/parameter_nodes.md
Essentially adds the functionality from `updateParameterNodeFromGui` and `updateGuiFromParameterNode` into the parameter node wrapper.
The parameterNodeWrapper is given a `connectGui` method that can take the `self.ui` of a module widget and connect to the widgets in the UI. The widgets that should connect to the parameter node should have a "SlicerParameterName" property added to them (this can be done in the Qt Designer). Alternatively, an explicit map from parameter name to widget can be used.
Again, I will update the TemplateKey for Scripted modules to use the parameterNodeWrapper at some point, and when I do it will use this automatic connection functionality.
The way the connections work is to define classes that know how to convert widgets to datatypes (int, str, float, etc). I …
> Parameter node wrapper gui connection

- Modules/Loadable/Colors/VTKWidgets/vtkSlicerScalarBarActor.cxx
- Modules/Loadable/Colors/VTKWidgets/vtkSlicerScalarBarActor.h
If a string specifier followed by a float specifier were added to the label format string, the SNPRINTF call would crash when interpreting the double as a string pointer. Fixed by only printing the value to the first specifier, and by validating that the specifier defines a floating point type.
Fix #3802
> BUG: Fix crash when adding %s specifier to color legend label

- Libs/MRML/Widgets/Testing/qMRMLLayoutManagerVisibilityTest.cxx
This commit fixes the test failing on some system (e.g Ubuntu 20.04):
```
Line 201 - Problem with widget visibility associated with node vtkMRMLViewNode1
widgetVisibility: 0
expectedWidgetVisibility: 1
```
> BUG: Fix qMRMLLayoutManagerVisibilityTest

- CMake/SlicerBlockInstallQt.cmake
- CMake/SlicerMacroBuildApplication.cmake
Bundle lconvert, lrelease, lupdate tools with the application to allow Slicer modules to update and process translation (.ts) files without requiring Qt installation.
Required for https://github.com/Slicer/SlicerLanguagePacks/issues/1
> ENH: Bundle Qt language tools

- Base/QTGUI/qSlicerMouseModeToolBar.cxx
This change allows for calling to removeAction(ToolBarAction) to remove the markups toolbar connection and have it remain disconnected. Previously it would always add the action back, overwriting the customization. Now the action is always in the set of mouse mode actions, but selectively shown/hidden
This doesn't introduce a change in functionality of how things are currently. It changes from removing/adding actions to showing/hiding actions in the Mouse mode toolbar. In the case of my custom app where we don't use the markups toolbar (reducing functionality on purpose), this PR allows for me to remove the toggle markups toolbar action from the Mouse Mode toolbar and have the place widget action still show/hide, but not reshow the toggle markups button in my custom app.
> ENH: Support disconnecting markups toolbar from mouse mode toolbar

- Libs/MRML/Core/vtkITKTransformConverter.h
- Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx
- Modules/Loadable/Transforms/Logic/vtkSlicerTransformLogic.cxx
- Modules/Loadable/Transforms/Logic/vtkSlicerTransformLogic.h
- Modules/Loadable/Transforms/qSlicerTransformsReader.cxx
- SuperBuild/External_ITK.cmake
This commit is a follow-up of 898959159 (BUG: Fix reading of vector fields from NIFTI files)
NIFTI image containing displacement field (`intent = 1006`) was incorrectly read as scalar volume (all 3 vector components were set to the same value).
Fixed by reading NIFTI displacement vector files similarly to general-purpose vector images. For displacement vector files, vector components are converted between NIFTI file's `RAS` coordinate system and ITK's `LPS` coordinate system, unless this conversion is explicitly disabled by setting `ConvertRASDisplacementVectors` to false.
An ITK vector image can be written as NIFTI displacement vector file by setting "intent_code"="1006" in the metadata dictionary of the image.
```
$ git shortlog be914a8b57..eeb7f43c49 --no-merges …
```
> BUG: Update ITK to fix read/write of displacement field in NIFTI file format

- Base/QTGUI/Testing/Cxx/qSlicerMouseModeToolBarTest1.cxx
- Base/QTGUI/qSlicerMouseModeToolBar.cxx
The change in order of the actions made in https://github.com/Slicer/Slicer/commit/0ad10f0cb406d25c8d2ea62058b31dcc33173bdf caused the hardcoded index used to find the place widget action in the test to fail.
Failing qSlicerMouseModeToolBarTest1 - https://slicer.cdash.org/test/23951100
> BUG: Fix failing qSlicerMouseModeToolBarTest1

- .github/workflows/codespell.yml
- CMake/NSIS.template.in
- CMake/SlicerCPack.cmake
On the Windows platform, running a Slicer installer would create Start Menu shortcuts but did not create a desktop shortcut which is pretty common. This PR will create a desktop shortcut as part of the install process.
Note: The Start Menu folder MUI Page has a "Do not create shortcuts" option which will skip start menu and desktop shortcut creation
> ENH: Create Windows Desktop shortcut during install

- Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx
- Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h
- Modules/Loadable/Markups/qSlicerMarkupsReader.cxx
Fixed loadAnnotationRuler function. It now returns a valid markups line node. ruler_node = slicer.util.loadAnnotationRuler(".../M_1.acsv")
Annotation fiducials, lines, ROIs can be loaded from .acsv files using "Add data" (drag-and-dropping the file to the application window).
fixes #6813
> BUG: Make loading of legacy annotation fiducial, line, ROI nodes more robust

- Modules/Loadable/Markups/Testing/Python/MarkupsCurveMeasurementsTest.py
The test has been failing due to recent work about torsion measurement. Torsion is computed using the tangent and binormal vectors provided by CurveCoordinateSystemGeneratorWorld (vtkParallelTransportFrame) filter, and adds three scalar arrays to the point data (PedigreeIDs + Tangents, Normals, Binormals). The test failed because of these additional arrays.
> BUG: Fix markups curve measurements test

- Base/QTCLI/qSlicerCLIExecutableModuleFactory.cxx
- Base/QTCLI/qSlicerCLILoadableModuleFactory.cxx
- Base/QTCLI/qSlicerCLIModuleUIHelper.cxx
Some user-visible strings were not marked as translatable.
see https://github.com/Slicer/SlicerLanguagePacks/issues/12
> BUG: Mark translatable strings in Base/QTCli

- Modules/Scripted/DICOMLib/DICOMProcesses.py
Since the return argument of the defaultProgressCallback() is None, the send() function of the DICOMSender raises a UserWarning:
```python
if not self.progressCallback(f"Sending {file} to {self.destinationUrl.toString()} using {self.protocol}"):
raise UserWarning("Sending was cancelled, upload is incomplete.")
```
This minimal PR prevents the user warning by returning True instead.
> BUG: Fixes default progress callback raises user warning in send() function

- Base/Python/slicer/parameterNodeWrapper/serializers.py
- Base/Python/slicer/parameterNodeWrapper/wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_pack.py
Adds a new serializer for `typing.Any`
Fixes a couple bugs.
> Parameter node wrapper any serializer

- Modules/Scripted/WebServer/WebServer.py
If the request included `processEvents()` or otherwise triggered the event loop the notifier could be
freed before the slot was finished, causing memory corruption.
Fixes #6823
> BUG: Free notifier after request handling

- Modules/Loadable/Markups/Testing/Cxx/CMakeLists.txt
This is a follow-up of d4723511c effectively fixing the build by ensuring the SceneViews module logic library is not linked against the Markups tests.
This further improve change initially integrated in:
* https://github.com/Slicer/Slicer/pull/6790
> COMP: Fix vtkMarkupsAnnotationSceneTest build with SceneViews module disabled (part2)

- Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
Previously ImportLabelmapToSegmentationNode would only import segments if the specified list of segment IDs matched pre-existing segments, and ignore other segments. This commit will insert new segments that don't match an existing segment ID.
See https://discourse.slicer.org/t/slicer-modules-segmentations-logic-importlabelmaptosegmentationnode-not-workign-with-given-segmentids/27998.
> BUG: Create non-existing segments in ImportLabelmapToSegmentationNode

- SuperBuild.cmake
The class module names (cls.__module__) for classes wrapped with this wrapping were incorrect. For example, vtkAddonMathUtilities.__module__ returns "vtkAddon", while the actual python package is "vtkAddonPython".
This updates module names to have the Python suffix. See Slicer/vtkAddon#34
```
$ git shortlog fb7edc86f..0bcff82 --no-merges
Connor Bowley (1):
BUG: Fix Python module names
David Allemang (2):
COMP: Report error on wrapping empty KIT_SRCS
STYLE: Update CMakeLists.txt sorting values in vtkAddon_SRCS list
COMP: vtkMacroKitPythonWrap: Remove obsolete use of PYTHON_INCLUDE_PATH
```
> BUG: Update vtkAddon to include python module name

- Base/QTGUI/qSlicerModuleFactoryFilterModel.cxx
- Base/QTGUI/qSlicerModuleFactoryFilterModel.h
- Base/QTGUI/qSlicerModuleFinderDialog.cxx
- Base/QTGUI/qSlicerModulesListView.cxx
Do not allow selecting a testing module in module finder when not in developer mode.
Also fix a small programming style mistake.
> Improve module finder filtering

- Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx
Previously, the line/arc in line and angle Markups was forced to be hidden if the visibility of any of the control points was disabled. This commit removes the GetAllControlPointsVisible() requirement so that line/angle markups can be displayed even when some of the control points are hidden.
> ENH: Allow line/angle Markups line visibility if control points hidden

- Docs/developer_guide/modules/segmenteditor.md
- Docs/user_guide/modules/segmenteditor.md
- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorMaskVolumeEffect.py
This reduces edge artifacts on the resulting masked image.
Original behavior (no soft edge):
Soft edge (less edge artifacts):
Soft edge (very wide edge, even less edge artifacts but the transition zone somewhat eats into the image):
> ENH: Add Soft edge option for Mask volume Segment Editor effect

- Applications/SlicerApp/Testing/Python/CMakeLists.txt
- Base/Python/slicer/parameterNodeWrapper/guiConnectors.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py
- Base/Python/slicer/tests/test_slicer_parameter_pack.py
- Base/QTCore/qSlicerLoadableModuleFactory.cxx
- Base/QTCore/qSlicerScriptedUtils.cxx
- Base/QTCore/qSlicerScriptedUtils_p.h
- Base/QTGUI/qSlicerLoadableModule.cxx
- Docs/developer_guide/parameter_nodes/supported_types.md
- Utilities/Templates/Modules/Scripted/TemplateKey.py
This commit ensures that python wrapped C++ classes implemented by loadable module (Logic, MRML, MRMLDisplayableManager, VTKWidgets, PythonQt) are imported and associated with the "slicer" package during module instantiation.
This ensures that classes that are both provided by other modules and referenced in python script associated with scripted loadable module can be successfully resolved.
Note that since wrapped C++ VTK modules explicitly import other wrapped C++ VTK modules they depend one (using `vtkPythonUtil::ImportModule`), calling `qSlicerScriptedUtils::importModulePythonExtensions` during module instantiation done independently of the module dependency graph is not a problem.
```
$ ctest -R test_slicer_parameter 
Test project /home/jcfr/Projects/Slicer-Release/Slicer-build
Start …
```
> Support import type annotation from slicer during module load

- CMakeLists.txt
Due to a regression introduced in CMake 3.25 that will be fixed in CMake 3.25.3, this commit ensures an error message is reported.
The regression was preventing the successful build and installation of the PythonQt external project integrated through CTK.
References:
* https://gitlab.kitware.com/cmake/cmake/-/issues/24567
* https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7655
* https://discourse.slicer.org/t/slicer-custom-app-build-error/28026/8
> COMP: Report error if unsupported CMake version 3.25.(0|1|2) is used

- Docs/developer_guide/script_repository/sequences.md
I saw this outdated Sequence Browser module usage (`slicer.modules.sequencebrowser`) in the sequences documentation so I figured I would go ahead and issue a minor change for it.
> DOC: Fix outdated sequence browser example usage

- Libs/MRML/Core/Testing/vtkMRMLTableNodeTest1.cxx
- Libs/MRML/Core/vtkMRMLTableNode.cxx
- Libs/MRML/Core/vtkMRMLTableNode.h
- Libs/MRML/Core/vtkMRMLTableStorageNode.cxx
Fix non-string table cells initialized with random values.
When a null value for a non-string type column was not specified,
new cells were filled with arbitrary values.
Removed __int64 type, as it is no longer supported in tables.
Added tests for all types.
Fix non-str cols always loaded before string columns.
When editing a table, string columns with no extra metadata were not
included in the schema. When the schema file is written, these missing
columns are appended to the schema.
This commit makes the columns in the table node match the order in the table file.
This pull request replaces https://github.com/Slicer/Slicer/pull/6801, which solved the same issues but it had some limitations (unnecessarily removed vtkIdType support, no tests were added; column order in table node still did …
> Table column type issues 2

- Base/Python/slicer/parameterNodeWrapper/parameterPack.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py
- Base/Python/slicer/tests/test_slicer_parameter_pack.py
When using nested parameterPacks, the setValue would change the parameterPack, but not the underlying parameterNode.
> BUG: Fix lost setValue with nested parameterPacks

- Applications/SlicerApp/Testing/Python/CMakeLists.txt
- Base/Python/slicer/parameterNodeWrapper/__init__.py
- Base/Python/slicer/parameterNodeWrapper/guiConnectors.py
- Base/Python/slicer/parameterNodeWrapper/util.py
- Modules/Loadable/SubjectHierarchy/Widgets/Python/CMakeLists.txt
- Modules/Loadable/SubjectHierarchy/Widgets/Python/__init__.py
- Modules/Loadable/SubjectHierarchy/Widgets/Python/parameterNodeWrapper/__init__.py
- Modules/Loadable/SubjectHierarchy/Widgets/Python/parameterNodeWrapper/guiConnectors.py
This commit fixes the following tests by ensuring parameterNodeWrapper guiConnectors specific to modules (e.g SubjectHierarchy) are registered in the corresponding modules.
```
py_nowarning_mainwindow_noloadableTest
py_nowarning_mainwindow_nocli_noloadableTest
py_nowarning_nomainwindow_noloadableTest
py_nowarning_nomainwindow_nocli_noloadableTest
py_nomainwindow_SlicerOptionModulesToIgnoreTest
```
Note that since the test associated with `qMRMLSubjectHierarchyTreeViewToNodeConnector` is still implemented in `py_nomainwindow_test_slicer_parameter_node_wrapper_guis`, it is required to have the `SubjectHierarchy` python classes imported by removing the `--disable-scripted-loadable-modules` argument.
> BUG: Register parameterNodeWrapper plugins in corresponding module

- Base/QTGUI/qSlicerMouseModeToolBar.cxx
- Base/QTGUI/qSlicerMouseModeToolBar_p.h
This closes #6830.
This fixes the following error which was introduced by https://github.com/Slicer/Slicer/commit/32675b18cb60123a7a873889f8c7383549e3ad27: [Qt] QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'PlaceWidgetMenuWindow'
History about the changes that were previously made and the reasoning about the changes made here: https://github.com/Slicer/Slicer/issues/6830#issuecomment-1432061086
> BUG: Fix missing toggle markups action in Markups Place button menu

- Base/Python/slicer/parameterNodeWrapper/parameterPack.py
- Base/Python/slicer/parameterNodeWrapper/wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_pack.py
- Docs/developer_guide/parameter_nodes/advanced/custom_classes.md
- Docs/developer_guide/parameter_nodes/defaults.md
- Docs/developer_guide/parameter_nodes/supported_types.md
- Docs/developer_guide/parameter_nodes/validators.md
- Utilities/Templates/Modules/Scripted/TemplateKey.py
Update to allow parameterPacks and parameterNodeWrappers to specify default values via assignment instead of the Default annotation. The assignment syntax is simpler and easier to read.
> ENH: ParameterNodeWrapper default by assignment

- Base/QTGUI/qSlicerIOManager.cxx
- Docs/developer_guide/extensions.md
- Docs/user_guide/settings.md
- Modules/Scripted/ExtensionWizard/ExtensionWizard.py
- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/LoadModulesDialog.py
- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/ModuleInfo.py
Python scripted modules folders can now be added to "Additional module paths" by drag-and-dropping module .py files or folders to the application window.
> ENH: Add additional module paths by drag-and-drop to application

- Modules/Scripted/DICOMLib/DICOMPlugin.py
- Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
- Modules/Scripted/DICOMPlugins/DICOMVolumeSequencePlugin.py
- Utilities/Scripts/update_translations.py
In addition to series modality and series number, also read these fields from DICOM into metadata in the scene: seriesDescription, seriesDate, seriesTime, contentDate, contentTime, manufacturer, model.
This allows preserving more information when importing and then exporting DICOM images.
Also changed default series number to 301 (from 1) because values <100 are typically used for primary acquisitions, while higher numbers are used for processed data.
> Import more series information from DICOM images

- .gitignore
- .readthedocs.yaml
Migrate Read the Docs settings to file and switch from python 3.7 to 3.9
This commit ensures the python version used to build the documentation matches the one available in Slicer.
References:
* https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface
* https://docs.readthedocs.io/en/stable/config-file/index.html
This should help move forward with the following pull-request:
* https://github.com/Slicer/Slicer/pull/6876
> Migrate Read the Docs settings to file and switch from python 3.7 to 3.9

- Base/QTCore/qSlicerCoreApplication.cxx
One of the changes introduced in Slicer/Slicer#6864 produces a compilation error (missing QSslConfiguration header) in some GNU/Linux distributions, more specifically on Gentoo, which deploys Qt 5.15.8-r3. In some versions of Qt, this might have been indirecly included in some other Qt headers, thus not producing the error.
This commit solves the issue by including `QSslConfiguration` explicitly. This change should work across operating systems.
> COMP: Fix missing QSslConfiguration include

- CMake/SlicerMacroBuildApplication.cmake
This commit adds an explicit check ensuring that the regression fixed by 17dccc679c (BUG: Change organization name and domain to slicer.org from Slicer) is not re-introduced.
To avoid conflict between the revision specific settings folder name and the application name, this commit adds a check ensuring that both are different.
Note that while the name conflict is specific to Linux and happens only if `Slicer_STORE_SETTINGS_IN_APPLICATION_HOME_DIR` is `ON` (the default), the check is done unconditionally of the platform and build option.
References:
* https://github.com/Slicer/Slicer/issues/6878
* https://discourse.slicer.org/t/install-extensions-is-not-working-on-latest-preview-release/28316/7
> COMP: Update slicerMacroBuildApplication to check for valid application name

- SuperBuild/External_CTK.cmake
List of CTK updates:
```
$ git shortlog ef3d86b3b..a203172b6 --no-merges
STYLE: Use consistent indentation in qt/__init__.py.in
BUG: Avoid segfault if importing qt & ctk python package in standalone python
```
> BUG: Update CTK to fix crash when importing ctk or qt from standalone python

- Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.cxx
- Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h
- Modules/Loadable/Markups/Testing/Python/MarkupsCurveMeasurementsTest.py
When a custom measurement was added to a closed curve that contained control point values then the "Failed to add ... measurement array to curve" error was displayed and the measurement did not show up on the GUI.
The problem was that the pedigree IDs for the last curve segment points were considered out of range.
Fixed by accepting up to one more control point index when interpolating values on a closed curve. Values after the last control point index refer to points after the last control point that connect the curve to the first control point.
> BUG: Fix static control point measurements for closed curves

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/update-slicer-certificate-bundle.yml
To avoid the need to manually update GitHub actions such as https://github.com/Slicer/Slicer/commit/a9b93e531c525546fce3936ea49826b03570bf95, this utilizes Dependabot to automatically issue PRs with updates.
With `COMP: Pin GitHub actions to full length commit SHA`, Dependabot will update with a pinned hash and will also [update the semver comment](https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/).
Once integrated Dependabot will run and create PRs to update actions/upload-artifact and peter-evans/create-pull-request to the latest tagged version.
> COMP: Add Dependabot workflow to update GitHub actions

- CMake/SlicerDirectories.cmake
- CMakeLists.txt
~~This commit modifies `SlicerDirectories.cmake` to add a new CMake variable called `Slicer_LIB_PREFIX`. This variable allows users to specify the directory prefix for installation of 3D Slicer llibraries (e.g., lib or lib64). By default, the value of this variable is set to `lib`, which preserves the previous hard-coded value.~~
This commit modifies `SlicerDirectories.cmake` to replace the hardcoded `lib` part of the library installation path by `CMAKE_INSTALL_LIBDIR`. The use of `CMAKE_INSTALL_LIBDIR` is documented in the following
references:
- https://cmake.org/cmake/help/latest/command/install.html?highlight=cmake_install_libdire#installing-directories
- https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs
This is useful when building/installing slicer …
> ENH: Replace `lib` by `CMAKE_INSTALL_LIBDIR`

- .github/workflows/codespell.yml
- .github/workflows/commit-message.yml
- .github/workflows/lint.yml
This is a followup to https://github.com/Slicer/Slicer/commit/73f549c1e698a087c550c193e849e7a03645113f.
GitHub's security hardening guide recommends this mitigation method. https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
> COMP: Pin more GitHub actions to full length commit SHA

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Libs/MRML/Logic/vtkMRMLSliceLogic.h
This fixes an issue that would always log the following warning when changing Window/Level with the mouse mode. This issue was introduced in my commit https://github.com/Slicer/Slicer/commit/2896452063e2bcd5526934cd032f68603fd572ff where I removed the Window/Level locked state for a given volume. This logic was there to previously check if the volume in the slice viewer had an unlocked Window/Level state.
```
[VTK] Warning: In D:\D\P\S-0\Libs\MRML\Logic\vtkMRMLSliceLogic.cxx, line 2457
[VTK] vtkMRMLSliceLogic (00000246B7D8E270): vtkMRMLSliceLogic::VolumeWindowLevelEditable method is deprecated. Volume window level can always be set programmatically.
```
> BUG: Fix warning when changing window/level with mouse mode

- SuperBuild/External_VTK.cmake
This commit fixes a regression introduced in 396c8e5d0a (BUG: Fix crash in vtkPolyData::BuildCells() and add .pyi generator) where the feature for generation pyi files was inadvertently integrated.
The Windows build is fixed by removing `vtkpythonmodules_pyi` from the default target (the "ALL" parameter was commented out) in the associated custom target.
Until this is addressed, this should ensure the build succeeds.
```
Creating .pyi files for vtkpythonmodules
File "C:\path\to\S-0-build\python-install\Lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\path\to\S-0-build\python-install\Lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File …
```
> COMP: Update VTK to fix Windows build error related to .pyi files generation

- CMake/SlicerBlockInstallQt.cmake
- CMake/SlicerBlockInstallQtTools.cmake
- CMake/SlicerCPack.cmake
This commit is a follow-up of 0a00473ea (ENH: Bundle Qt language tools).
It factors out the logic for installing the tools into a CMake module included on all platforms.
Notes:
* The module `SlicerBlockInstallQtTools.cmake` was designed to eventually support installing other Qt tools.
* Since the bundling of Qt designer is implemented in two files `SlicerCPack.cmake` and `SlicerCPackBundleFixup.cmake.in` included at either build or packaging time, the refactoring the associated installation code is a more involved task that does not belong to this pull request.
> COMP: Ensure Qt language tools are bundled on macOS

- SuperBuild/External_VTK.cmake
This commit is a follow of fa749969c (COMP: Update VTK to fix Windows build error related to .pyi files generation) introduced through:
* https://github.com/Slicer/Slicer/pull/6903 
The packaging error copied below is resolved by commenting the rules attempting to install non-existent pyi files.
Packaging error:
```
CMake Error at VTK-build/cmake_install.cmake:3570 (file): file INSTALL cannot find
"/.../Slicer-0-build/VTK-build/lib/python3.9/site-packages/vtkmodules/vtkCommonCore.pyi": No such file or directory.
```
```
$ git shortlog 3ecff39979..f6bcc9d3e3 --no-merges
COMP: Fix packaging removing install rules associated with non-existent pyi files
```
> COMP: Update VTK to fix packaging error due to non-existent .pyi files

- CMake/SlicerBlockInstallQtTools.cmake
This commit fixes a regression introduced in 4c91fd052 (COMP: Ensure Qt language tools are bundled on macOS) through the pull-request:
* https://github.com/Slicer/Slicer/pull/6904
... that was originally intended to fix issue:
* https://github.com/Slicer/Slicer/issues/6896
It sets the variable `qt_root_dir` and adds the relevant checks to report an error at configuration time.
> COMP: Fix packaging of Qt tools

- SuperBuild/External_CTK.cmake
This commit fixes a regression introduced in 2e4cfbd9a2 (BUG: Update CTK to make DICOM browser translatable)
It ensures the build works on case-sensitive file-system by consistently including Qt headers.
```
$ git shortlog c819ae737..04618a43f --no-merges
COMP: Fix DICOM/Core build ensuring Qt headers can always be included
```
Related issues and pull-requests:
* https://github.com/commontk/CTK/pull/1068
* https://github.com/commontk/CTK/pull/1074
> COMP: Update CTK to fix build of CTK DICOM Core library

- Docs/conf.py
- Docs/developer_guide/build_instructions/linux.md
- Docs/user_guide/getting_started.md
(1) Switch from
```
:::{note} Warning
:class: warning
```
to
```
:::{warning}
```
(2) Update the type of admonition:
* ArchLinux uses a rolling-release: warning -> cautious
* Build on any Distribution: warning -> important
* `Qt5_DIR` need to be set using the full path: warning -> hint
* recommended to avoid use of spaces: warning -> tip
> DOC: Fix use of admonition directives in "getting started" and "build instructions"

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
When the slice viewer only had a foreground volume populated, the user was unable to change the window level with the mouse mode.
This was introduced by https://github.com/Slicer/Slicer/commit/4a73c3a7599324fdf66a0cf154bb2f85e7eb63d3
> BUG: Fix unable to change foreground volume window level with mouse mode

- SuperBuild/External_CTK.cmake
More strings are now marked as translatable in CTK, particularly in the DICOM module.
Change log:
Revision: 83a570aacc2ef745b595c92ff475ef314be884ff
Date: 2023-04-05 12:33:30 PM
Message:
BUG: Make DICOM database table view headings translatable
Revision: c5141054fd398d9945d2c8812ed19cda08859497
Date: 2023-04-05 10:24:59 AM
Message:
STYLE: Removed translation from log messages
Log messages should not be translated (it is not intended for users and would make it harder for developers to interpret the logs).
Revision: e9aa74a504513ab2f77d020476f7cefc9b9f0609
Date: 2023-04-05 10:22:22 AM
Message:
STYLE: Removed commented out code
The comments happened to start with colon, …
> ENH: Update CTK to latest version to improve translations

- Docs/user_guide/getting_started.md
I just did the test of running SlicerCAT on Debian 10.12. To solve `QT_QPA_PLATFORM` error I needed to create symlink. But this time I needed to create it to `libxcb-util.so.0.0.0`. As I there was no `libxcb-util.so`.
Most likely the correct library is always `libxcb-util.so.0.0.0`. But I'm not sure.
We could leave these two options so the user could check his system.
This solution also comes from the link above.
> DOC: updated run solution for Debian 10.12

- SuperBuild/External_VTK.cmake
```
$ git shortlog f6bcc9d3e3..7a000d76cb --no-merges
[Backport MR-10122] RenderingOpenXRRemoting: Fix support for externally building the module
```
> COMP: Update VTK to support external build of RenderingOpenXRRemoting module

- Libs/MRML/Core/vtkMRMLAbstractViewNode.cxx
- Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.h
- Modules/Loadable/Sequences/Resources/UI/qSlicerSequencesModuleWidget.ui
- Modules/Loadable/Sequences/Widgets/CMakeLists.txt
- Modules/Loadable/Sequences/Widgets/DesignerPlugins/CMakeLists.txt
- Modules/Loadable/Sequences/Widgets/DesignerPlugins/qMRMLSequenceEditWidgetPlugin.cxx
- Modules/Loadable/Sequences/Widgets/DesignerPlugins/qMRMLSequenceEditWidgetPlugin.h
- Modules/Loadable/Sequences/Widgets/DesignerPlugins/qSlicerSequencesModuleWidgetsPlugin.h
- Modules/Loadable/Sequences/Widgets/Resources/UI/qMRMLSequenceEditWidget.ui
- Modules/Loadable/Sequences/Widgets/Testing/Cxx/CMakeLists.txt
- Modules/Loadable/Sequences/Widgets/Testing/Cxx/qMRMLSequenceBrowserWidgetsTest1.cxx
- Modules/Loadable/Sequences/Widgets/Testing/Cxx/qMRMLSequenceEditWidgetTest1.cxx
- Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserSeekWidget.cxx
- Modules/Loadable/Sequences/Widgets/qMRMLSequenceEditWidget.cxx
- Modules/Loadable/Sequences/Widgets/qMRMLSequenceEditWidget.h
- Modules/Loadable/Sequences/qSlicerSequencesModuleWidget.cxx
- Modules/Loadable/Sequences/qSlicerSequencesModuleWidget.h
In Sequences module's Edit section, multiple candidate nodes can be selected and added to the sequence at once, and multiple data nodes can be removed from the sequence at once.
Added an option to use the candidate node name as index value if index type is text.
Factored out sequence editing into a separate widget (qMRMLSequenceEditWidget). This simplifies the code and provides sequence editing GUI for other modules.
This implements the feature that was mentioned in this discussion:
https://discourse.slicer.org/t/volume-rendering-property-lock/28761/12?u=lassoan
> Sequence editing improvements and fixes

- Base/QTCLI/vtkSlicerCLIModuleLogic.h
- Libs/MRML/CLI/vtkMRMLCommandLineModuleNode.h
- Libs/MRML/Core/vtkMRMLClipModelsNode.h
- Libs/MRML/Core/vtkMRMLDisplayNode.h
- Libs/MRML/Core/vtkMRMLModelNode.h
`typedef enum {value1, value2, ...} someTypeName;` is not supported by VTK's Python wrapper (the method that uses such enums are not Python-wrapped). Need to use `enum someTypeName {value1, value2, ...};` syntax instead.
Fixes issue reported here: https://discourse.slicer.org/t/how-to-set-clipping-method-of-vtkmrmlclipmodelsnode/28816
> BUG: Fix Python wrapping of methods using enum arguments

- SuperBuild/External_CTK.cmake
git log:
Revision: cd194fff1360e2da114b6b55ce963f089c6f46f2
Date: 2023-04-11 10:30:38 PM
Message:
BUG: Fix localization and inconsistent state in ctkModalityWidget
There were several issues with the imaging modality selector widget (ctkModalityWidget):
- when imaging modality abbreviations (CT, MRI, XA, ...) were localized then the widget did not work at all, because the checkbox text was used to identify the checkboxes
- widget state was stored redundantly in SelectedModalities and VisibleModalities variables and the checkbox properties; and these were often inconsistent
Fixed by using Qt object names to identify checkboxes; and removing SelectedModalities and VisibleModalities variables (store widget state in the checkbox properties).
Revision: …
> BUG: Update CTK to latest version to get a few minor fixes

- Modules/Scripted/DICOMPatcher/DICOMPatcher.py
This commit fixes a regression that prevented instantiation of some rules. The regression was introduced a few days ago when a new rule was added that takes an additional rule parameter.
> BUG: Fix DICOM patcher regression

- Modules/Loadable/Sequences/Resources/UI/qSlicerSequencesModuleWidget.ui
The horizontalHeaderVisible for tableWidget_SynchronizedSequenceNodes was set to "false". Changed horizontalHeaderVisible back to "true".
> BUG: Restore synchronized sequence table header visibility

- Libs/MRML/Core/Testing/vtkMRMLNodeTest1.cxx
- Libs/MRML/Core/vtkMRMLNode.cxx
- Libs/MRML/Core/vtkMRMLNode.h
- Libs/MRML/Core/vtkMRMLTransformDisplayNode.cxx
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformsDisplayableManager2D.cxx
Transform displayable managers rely on node reference to get notified about input "glyph points" node changes. Glyph points node designates where to draw glyphs. User can select it in Transforms module / Display / Advanced / Source points.
When points of a markup node change then the markup node does not invoke a Modified event, but a custom PointModified event. However, the vtkMRMLTransformDisplayNode (in MRML core) does not know about markup node custom events (in Markups module).
A solution could have been to move markups nodes into MRML core, but moving all node types into MRML core is not a sustainable strategy.
Instead, MRML node reference infrastructure was enhanced with a new feature: instead of just specifying an event list, it is now also possible to request observing …
> BUG: Fix dynamic update of transform visualization

- Libs/MRML/Widgets/CMakeLists.txt
- Libs/MRML/Widgets/qMRMLAbstractViewWidget.cxx
- Libs/MRML/Widgets/qMRMLAbstractViewWidget.h
- Libs/MRML/Widgets/qMRMLLayoutManager.cxx
- Libs/MRML/Widgets/qMRMLLayoutManager.h
- Libs/MRML/Widgets/qMRMLLayoutManager_p.h
- Libs/MRML/Widgets/qMRMLLayoutViewFactory.cxx
- Libs/MRML/Widgets/qMRMLPlotWidget.cxx
- Libs/MRML/Widgets/qMRMLPlotWidget.h
- Libs/MRML/Widgets/qMRMLSliceWidget.cxx
- Libs/MRML/Widgets/qMRMLSliceWidget.h
- Libs/MRML/Widgets/qMRMLTableWidget.cxx
- Libs/MRML/Widgets/qMRMLTableWidget.h
- Libs/MRML/Widgets/qMRMLThreeDWidget.cxx
- Libs/MRML/Widgets/qMRMLThreeDWidget.h
Previously, newly created views were initialized with the default pause render state of 0. This caused warning messages if the layout was changed between pauseRender/resumeRender calls as the render state of newly created views would not match the existing ones.
This commit tracks the global pauseRender count, and uses it to initialize the pauseRender state of newly created views. This removes most instances of the warning message:
> [Qt] int __cdecl ctkVTKAbstractView::resumeRender(void) Cannot resume rendering, pause render count is already 0!
> ENH: Initialize global pause render state for newly created views

- SuperBuild/External_VTK.cmake
This is a first toward addressing:
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/112
This will allow to update `SlicerVirtualReality` (and `SlicerMixedReality`) to make use of the new `vtkVRRenderWindowInteractor::Set/GetActionManifestDirectory`.
```
$ git shortlog 7a000d76c..213951843 --no-merges
Ben Boeckel (4):
[Backport] vtkVRRenderWindow: remove unnecessary `void*` casts
[Backport] clang-tidy: fix `modernize-use-nullptr` lints
[Backport] shaders: do not export shader symbols
[Backport] vtkOpenXRInteractorStyle: remove excess semicolon
Bernhard Froehler (1):
[Backport] OpenVR: Never ignore VREvent_Quit
Mathieu Westphal (1):
[Backport] Improve OpenVR/OpenXR module and test and enable OpenXR in CI
```
> ENH: Update VTK to backport "Rendering(VR|OpenVR|OpenXR)" changes

- SuperBuild.cmake
Update Surface toolbox to include a single fix that allows performing Uniform remeshing on models that contain triangle strips.
---
Revision: 25999cefa2554b5fa4698b847716f75837070e33
Author: Ben Zwick <benzwick@gmail.com>
Date: 2023-05-15 11:44:23 PM
Message:
ENH: Uniform remesh models with triangle strips (#58)
Uniform remesh using PyACVD failed if the model contained triangle strips (e.g., created by Model Maker module). Fixed by converting triangle strips to triangles using vtkTriangleFilter.
> BUG: Make Uniform remeshing in Surface toolbox work for triangle strips

- Base/Logic/vtkSlicerApplicationLogic.cxx
- Base/QTCore/Testing/Cxx/qSlicerUtilsTest1.cxx
This commit is a follow-up of 008f8b957 (ENH: Make Slicer application fully
portable) and f7edf41e7 (BUG: Fix logic that determines if a module is built-in).
It ensures that in the context of extension installed from file when running the application from a build tree, the function `qSlicerAbstractCoreModule::isInstalled()` returns the expected value.
> BUG: Fix IsPluginInstalled() when plugin installed in application build tree

- Docs/developer_guide/advanced_topics.md
- Libs/MRML/Core/vtkMRMLMeasurement.h
- Libs/MRML/Core/vtkMRMLStaticMeasurement.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonElement.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMeasurementAngle.h
- Modules/Loadable/Markups/MRML/vtkMRMLMeasurementArea.h
- Modules/Loadable/Markups/MRML/vtkMRMLMeasurementLength.h
- Modules/Loadable/Markups/MRML/vtkMRMLMeasurementVolume.h
Getting the ROI box as polydata is useful for example for creating a model or segment from an ROI node.
> ENH: Add utility function to get ROI box as vtkPolyData

- Modules/Scripted/WebServer/CMakeLists.txt
- Modules/Scripted/WebServer/Resources/docroot/ServerTests/modelviewer.html
- Modules/Scripted/WebServer/Resources/docroot/ServerTests/threejs.css
- Modules/Scripted/WebServer/Resources/docroot/ServerTests/threejs.html
- Modules/Scripted/WebServer/Resources/docroot/index.html
- Modules/Scripted/WebServer/WebServerLib/SlicerRequestHandler.py
This adds a threeDGraphics rest endpoint that returns a glTF json of the threeD view contents.
The demos show how to use this endpoint with common web graphics tools.
There is also a stub for a segmentations endpoint that could be fleshed out later.
> ENH: Web server examples (threejs and modelviewer)

- Applications/SlicerApp/Testing/Python/CMakeLists.txt
- Applications/SlicerApp/Testing/Python/ScriptedModuleDiscoveryTest.py
- Applications/SlicerApp/Testing/Python/ScriptedModuleDiscoveryTest/ModuleD_WithFileDialog_WithoutWidget.py
- Applications/SlicerApp/Testing/Python/ScriptedModuleDiscoveryTest/ModuleF_WithFileReader_WithoutWidget.py
- Base/QTCore/qSlicerCoreIOManager.cxx
- Base/QTCore/qSlicerCoreIOManager.h
- Base/QTGUI/qSlicerIOManager.cxx
- Base/QTGUI/qSlicerIOManager.h
- CMake/SlicerMacroPythonTesting.cmake
This pull-request aims to integrate fixes & changes implemented while working toward finalizing:
* https://github.com/Slicer/Slicer/pull/6953
* Add support for checking that scripted IOs are registered
* Add support for checking that scripted file dialogs are registered
* Ensure python exceptions in `ScriptedModuleDiscoveryTest` are considered
* Improve comments in `ScriptedModuleDiscoveryTest.py`
* Fix setting of extension module paths when `slicer_add_python` testing macros
* Fix setting module paths associated with `slicer_add_python` testing macros
* Ensures that arguments like "--disable-modules" and "--disable-*-modules" are respected when adding tests using the slicer_add_python testing macros.
Workaround the fact using PASS_REGULAR_EXPRESSION ignores return code by checking for …
> Misc scripted module fixes

- Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.h
Fixes an issue where interaction handles were not updated correctly when scrolling through Slices in 2D viewers. Ensures that interaction handles are updated after all other components. The UpdateFromMRMLInternal method replaces the UpdateFromMRML method in all representation subclasses, and is called by UpdateFromMRML in the base class. UpdateFromMRML also updates the interaction pipeline after UpdateFromMRMLInternal has been called.
Also fixes an issue where the ROI box is not visible in slices that are parallel to and intersecting with one of the ROI faces.
Fixes #6922
Co-authored by: Mathieu Albi <albi@certis-therapeutics.com>
> BUG: Fix interaction handle visibility when changing displayed slice

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
Some volumes may have an extent min/max of 0/0 and the converted ijkPos could be a very close to 0 value, but not exactly 0.
Attached is a zipped MRB where adjusting window/level of foreground volume with mouse mode would not work:
[ForegroundWLData.zip](https://github.com/Slicer/Slicer/files/11619074/ForegroundWLData.zip)
In this sample data, the 3rd dimension min/max extent was 0/0, however the `ijkPos[i]` value was 7.10543e-15. This made it seem that it was outside the bounds of the max since it was >0. This resulted in the background volume Window/Level being adjusted instead of the foreground volume.
> BUG: Fix unable to change foreground W/L with mouse mode

- Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.cxx
Pickable is a new segment display property, so when loading existing segmentations it will be missing from the display node. In this case the default true value needs to be specified, otherwise no segments will be pickable (i.e. no fiducials or other points can be placed on them).
This commit also fixes saving of the Pickable property. Now it is saved and loaded as a boolean property, as "true" or "false" instead of 0 or 1.
> BUG: Set segment Pickable display property to true if not specified

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Libs/MRML/Logic/vtkMRMLSliceLogic.h
- the Add/Subtract pipeline now respects the opacity slider used for alpha blend
- The opacity slider is used to determine the fraction of the foreground image added to the background
Alpha Blend Behavior:
| Old Add Behavior | New Add Behavior |
|--|--|
| ![OldAddPipeline_mid](https://github.com/Slicer/Slicer/assets/25040869/b346fd83-acfd-43c1-9a0b-3d7ef764a732) | ![NewAddPipeline](https://github.com/Slicer/Slicer/assets/25040869/5ce80d4c-ddcd-4058-8fb5-81f15ed5b137) |
> ENH: Add fractional addition to Add/Subtract Slice Composting pipeline

- Base/Python/slicer/tests/test_slicer_util_save.py
- Base/Python/slicer/util.py
- Base/QTCore/qSlicerCoreIOManager.cxx
- Base/QTCore/qSlicerCoreIOManager.h
- Base/QTCore/qSlicerFileReader.cxx
- Base/QTCore/qSlicerFileReader.h
- Base/QTCore/qSlicerFileWriter.cxx
- Base/QTCore/qSlicerFileWriter.h
- Base/QTCore/qSlicerScriptedFileReader.cxx
- Base/QTCore/qSlicerScriptedFileReader.h
- Base/QTCore/qSlicerScriptedFileWriter.cxx
- Base/QTCore/qSlicerScriptedFileWriter.h
- Base/QTGUI/qSlicerFileDialog.cxx
- Base/QTGUI/qSlicerNodeWriter.cxx
- Base/QTGUI/qSlicerNodeWriter.h
- Modules/Loadable/Colors/qSlicerColorsReader.cxx
- Modules/Loadable/Colors/qSlicerColorsReader.h
- Modules/Loadable/Markups/qSlicerMarkupsReader.cxx
- Modules/Loadable/Markups/qSlicerMarkupsReader.h
- Modules/Loadable/Segmentations/qSlicerSegmentationsNodeWriter.cxx
- Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx
- Modules/Loadable/Segmentations/qSlicerSegmentationsReader.h
- Modules/Loadable/Sequences/qSlicerSequencesReader.cxx
- Modules/Loadable/Sequences/qSlicerSequencesReader.h
- Modules/Loadable/Tables/qSlicerTablesReader.cxx
- Modules/Loadable/Tables/qSlicerTablesReader.h
- Modules/Loadable/Terminologies/qSlicerTerminologiesReader.cxx
- Modules/Loadable/Terminologies/qSlicerTerminologiesReader.h
Until now, reader and writer plugins could only return a Boolean value indicating if they can read or write a certain file. For file reading, composite file extensions (.seg.nrrd instad of just .nrrd) were used to find the most suitable plugin, but this did not work when a file was saved with a generic file extension (nrrd, json, txt, ...). It also caused an issue when a more specific reader plugin was registered before a generic plugin (e.g., segmentation reader was registered before volume reader). Finally, there was no way to prioritize writer plugins.
This commit introduces a new `canLoadFileConfidence` method to readers and writers. This allows a plugin to indicate its confidence that it is the most suitable plugin for reading/writing a file. Reader plugins are updated to determine …
> Choose file reader writer based on confidence

- SuperBuild/External_ITK.cmake
This updates the version in `ITKTubeTK` Remote module to use a valid tag and has no impact on the default `Slicer/ITK` build.
Fixes RafaelPalomar/Slicer-Flatpak#5
```
$ git shortlog 07216c9a5..c927a320a --no-merges
Rafael Palomar (1):
[Slicer] COMP: Fix incorrect tag for ITKTubeTK Remote module
```
> COMP: Update ITK to fix Flatpack dependency analysis

- Base/Python/slicer/tests/test_slicer_util_save.py
This fix is a follow of these commits:
* 37416c2e5 (ENH: Use inclusive language for segmentation source representation)
* 5204e7a31 (ENH: Improve default description selection in Add data window)
> BUG: Update test_slicer_util_save to use non-deprecated method

- Libs/MRML/DisplayableManager/vtkMRMLCameraWidget.cxx
Undo states were being added to the stack when the camera was modified, even if undo was not enabled for the camera.
> BUG: Skip camera undo when undo is not enabled on vtkMRMLCameraNode

- Base/Logic/Testing/vtkSlicerVersionConfigureTest1.cxx
- Base/QTCore/Testing/Cxx/qSlicerApplicationUpdateManagerTest.cxx
- Base/QTCore/Testing/Cxx/qSlicerExtensionsManagerModelTest.cxx
- Base/QTCore/qSlicerExtensionsManagerModel.cxx
- CMake/vtkSlicerVersionConfigure.h.in
- CMake/vtkSlicerVersionConfigureMinimal.h.in
- CMakeLists.txt
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialStorageNode.cxx
- Utilities/Doxygen/Doxyfile.txt.in
vtkSlicerVersionConfigureInternal.h is renamed vtkSlicerVersionConfigureMinimal.h.
#include "vtkSlicerVersionConfigure.h" is replaced by #include "vtkSlicerVersionConfigureMinimal.h" when it is possible, therefore no compilation is required if git commit is changed.
> COMP: Speed up incremental build

- Base/QTApp/qSlicerApplicationHelper.txx
The CTKAppLauncher creates an initial splash screen with the Qt::WindowStaysOnTopHint flag that closes with a specified delay time to close. The Slicer application initializes a second splash screen at startup that did not have the Qt::WindowStaysOnTopHint resulting in the CTKAppLauncher splash screen displaying on top of it and obscuring the loading text.
CTKAppLauncher code that specifies that launcher's SplashScreen with `Qt::WindowStaysOnTopHint`.
https://github.com/commontk/AppLauncher/blob/8109ffb2f1ae3038bb5a955bff1a5f07dd1400d2/Base/ctkAppLauncher.cpp#L743-L744
Now with this change the Slicer splash screen becomes shown on top of the CTKAppLauncher splash screen therefore showing the loading text as soon as it is available. Previously you would only see the loading text if the …
> BUG: Fix splash screen loading text hidden

- Base/QTCore/qSlicerAbstractCoreModule.h
- Base/QTCore/qSlicerAbstractModuleRepresentation.h
It was not clear what methods needs to be overwritten to allow a module to be associated with a node.
> DOC: Improve documentation of module/node association

- Base/Logic/vtkSlicerScriptedLoadableModuleLogic.cxx
- Base/QTCore/Testing/Cxx/qSlicerScriptedUtilsTest1.cxx
- Base/QTCore/qSlicerScriptedFileReader.cxx
- Base/QTCore/qSlicerScriptedFileWriter.cxx
- Base/QTGUI/qSlicerScriptedLoadableModuleWidget.cxx
- Libs/MRML/Core/vtkMRMLAbstractViewNode.cxx
- Libs/MRML/DisplayableManager/vtkMRMLScriptedDisplayableManager.cxx
- Libs/vtkSegmentationCore/vtkPolyDataToFractionalLabelmapFilter.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedLabelEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedPaintEffect.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyScriptedPlugin.cxx
- SuperBuild/External_VTK.cmake
Update `vtkPolyDataToFractionalLabelmapFilter` to account for vtkPolyDataToImageStencil::PolyDataSelector() API update introduced in kitware/VTK@3b0b72a74 (Make vtkPolyDatToImageStencil thread-safe)
List of Slicer specific changes:
```
$ git shortlog 1ff325c54a..6c02c9b376 --no-merges
Jean-Christophe Fillion-Robin (13):
[Slicer] COMP: Remove custom FindOpenGL to ensure OpenGL_GL_PREFERENCE is considered
[Slicer] BUG: Update vtkPythonUtil to disable relative import causing crash for Slicer modules
[Slicer] COMP: Remove FindTBB and expect VTK to be configured with TBB_DIR
[SlicerSMTK] COMP: Add support for specifying vtk-m library install components
[SlicerSMTK] vtkm: Use github.com/KitwareMedical/vtk-m: Update diy install rules, support TBB_DIR
[Backport MR-9892] ENH: Re-introduce support …
```
> ENH: Update VTK from 9.1.20220125 to 9.2.20230607

- SuperBuild.cmake
This commit fixes potential out of bound issue in `vtkCurveGenerator::SortByMinimumSpanningTreePosition`
Fixes #6866
> BUG: Update vtkAddon to fix potential out of bound issue in vtkCurveGenerator

- Libs/MRML/Core/vtkMRMLAbstractViewNode.cxx
- Libs/MRML/Core/vtkMRMLModelStorageNode.cxx
- Libs/MRML/DisplayableManager/Testing/Cxx/vtkMRMLCameraDisplayableManagerTest1.cxx
- Libs/MRML/Widgets/qMRMLTableModel.cxx
- Modules/Loadable/Annotations/Logic/vtkSlicerAnnotationModuleLogic.cxx
- Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationNode.cxx
- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx
- Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager2D.cxx
- Modules/Loadable/Tables/Logic/vtkSlicerTablesLogic.cxx
- Modules/Loadable/Tables/Testing/Cxx/vtkSlicerTablesLogicAddFileTest.cxx
- Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx
- Modules/Loadable/Volumes/Testing/Cxx/vtkSlicerVolumesLogicTest2.cxx
- Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMLoadable.cxx
- SuperBuild.cmake
This commit fixes warnings like the following:
```
/path/to/Slicer/Modules/Loadable/Volumes/Testing/Cxx/vtkSlicerVolumesLogicTest2.cxx:126:88: warning: ‘vtkStdString::operator const char*()’ is deprecated: Call `.c_str()` explicitly [-Wdeprecated-declarations]
126 |       logic->AddArchetypeVolume(fileNameList->GetValue(0), "rgbVolume", 0, fileNameList));
|                                                                                        ^
```
```
$ git shortlog 800a0fb33..87e5df9ac --no-merges
COMP: Fix deprecation warnings by explicitly calling vtkStdString::c_str()
```
This pull request is a follow-up of:
* https://github.com/Slicer/Slicer/pull/7010
> COMP: Fix deprecation warnings by explicitly calling vtkStdString::c_str()

- SuperBuild/External_CTK.cmake
Highlighted fixes:
* Ensure ctk::copyDirRecursively skips hidden file by default. See commontk/CTK@97cc44525
* Fix regression in ctkDateRangeWidget. See commontk/CTK@ac4c0d755
* Remove obsolete error message in ctkDateRangeWidget::displayTime. See commontk/CTK@a17882bbd
```
$ Jean-Christophe Fillion-Robin (60):
COMP: Fix -Wint-in-bool-context in ctkWorkflow
COMP: Fix -Wcatch-value warnings in DICOM libraries, tests and apps
COMP: Fix -Wunused-* warnings
COMP: Fix -Wreorder warning in ctkExampleHostControlWidget
COMP: Fix -Wcomment in ctkDICOMApplicationTest1
COMP: Fix CMake warning CMP0115 in org.commontk.plugingenerator.core
COMP: Fix QFlags deprecation warnings related to ctkPlugin::Start/StopOptions
COMP: Fix -Wunused-function warnings in ctkErrorLogModelTestHelper …
```
> ENH: Update CTK to fix warnings and misc issues

- CMake/SlicerBlockInstallCMakeProjects.cmake
- CMakeLists.txt
- SuperBuild/External_ITK.cmake
Since official ITK wheels can be installed in the Slicer Python environment[^1], this commit removes the options Slicer_BUILD_ITKPython and Slicer_INSTALL_ITKPython.
[^1]: https://discourse.slicer.org/t/installing-itk-python-package-in-slicer-5-1-and-above/25636
> Remove support for building ITK Python and prefer ITK Python wheels

- Docs/developer_guide/build_instructions/linux.md
Slicer is not compatible with CMake 3.25.1 that ships with Debian 12 (bookworm).
> DOC: Update linux.md to add note about Debian 12 CMake

- Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
Selecting "No type modifier" for a terminology when modifiers exist causes the the default invalid color to be displayed, even if a non-modified color has been specified in the terminology JSON. 
This commit corrects the function terminologyRecommendedColor() to return the non-modified color if the type has modifiers and a non-modified color exists. This bug fix is related to the issue: https://github.com/Slicer/Slicer/issues/6972 and was discussed in the Slicer discourse post: https://discourse.slicer.org/t/terminologies-questions/27384.
> BUG: Fix handling of non-modified terminology types

- License.txt
This fixes a small typo on the `License.txt` file. This closes Slicer/Slicer#7056
> DOC: Fix typo in `License.txt`

- Libs/MRML/Core/vtkMRMLNodePropertyMacros.h
- Libs/MRML/Core/vtkMRMLSliceNode.cxx
- Libs/MRML/Core/vtkMRMLSliceNode.h
`vtkMRMLSliceNode`'s read and write XML did not use macros. As I was updating the XML attributes as part of #7021, we decided to update all XML attributes before adding the new items.
> Update vtkMRMLSliceNode to use MRML helper macros

- Modules/Loadable/Transforms/Documentation/Transforms.dox
s/spacial/spatial/
Edit: it could also be 'special' but in context seemed like the former
> DOC: Fix typo in `Transforms.dox`

- .github/workflows/ci.yml
This allows for a job such as "Build Slicer" to report successful even if the changed files are in the list of ones to ignore. A skipped job will report its status as "Success". See the following link for more details:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks
From https://github.com/Slicer/Slicer/pull/7053#issuecomment-1613335912
> - Had a change to a .cxx file and also DOC and github workflow changes - https://github.com/Slicer/Slicer/actions/runs/5413682866/jobs/9839616035?pr=7053
> - Only DOC and github workflow changes - https://github.com/Slicer/Slicer/actions/runs/5413703493/jobs/9839670031?pr=7053
> ENH: Skip steps in required job rather than skipping workflow

- CMakeLists.txt
- Docs/developer_guide/build_instructions/windows.md
The issue with CMake 3.25.0 was resolved in CMake 3.25.1 (https://github.com/Kitware/CMake/commit/80fc564dd7cbebc374a18fb57c71472dac5de6c1).
The build instructions were saying that CMake <3.25.0 had to be used, but I have built recent Slicer successfully using CMake 3.26.4. Therefore I'm updating the instructions to make note that specifically 3.25.0 is one of a few versions to avoid.
> DOC: Update build instructions that newer CMake can be used

- .github/workflows/ci.yml
This commit is a follow-up of 2d6d136e94 (ENH: Skip steps in required job rather than skipping workflow) that should ensure the "dorny/paths-filter" action works in the context of push event.
See https://github.com/dorny/paths-filter/issues/88#issuecomment-847003742
> BUG: Fix "Build Slicer" CI workflow in the context of push event

- Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
This commit just hides the volume and logs a message if a non-linearly transformed volume is attempted to be displayed using volume rendering.
This is a partial fix, as it would be better if the user was warned on the GUI in advance that the volume will not be displayed; and it would be even better to allow correct display of the volume regardless of what transform it is under. Still, this fix is useful as it prevents a volume from appearing in incorrect position.
see #6648
> BUG: Do not display volume rendering if volume is under non-linear transform

- Base/QTCore/qSlicerIOOptions_p.h
- Base/QTCore/qSlicerScriptedUtils_p.h
- Base/QTGUI/qSlicerExtensionsServerWidget_p.h
- Base/QTGUI/qSlicerSettingsUserInformationPanel.h
- Libs/MRML/Core/vtkMRMLTableSQLiteStorageNode.h
- Libs/MRML/DisplayableManager/vtkMRMLAbstractWidgetRepresentation.h
- Libs/vtkITK/vtkITKImageToImageFilterUSF.h
- Modules/Loadable/Annotations/MRMLDM/vtkMRMLAnnotationDisplayableManagerHelper.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonElement.h
- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManagerHelper.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h
- Modules/Loadable/Markups/Widgets/Testing/Cxx/qMRMLMarkupsMalformedWidget.h
- Modules/Loadable/Markups/Widgets/qMRMLMarkupsCurveSettingsWidget.h
- Modules/Loadable/Markups/Widgets/qMRMLMarkupsOptionsWidgetsFactory.h
- Modules/Loadable/Markups/qSlicerMarkupsReader.h
- Modules/Loadable/Plots/qSlicerPlotsModuleWidget.h
- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.h
- Modules/Loadable/Segmentations/Logic/vtkImageGrowCutSegment.h
- Modules/Loadable/Sequences/Widgets/DesignerPlugins/qSlicerSequencesModuleWidgetsAbstractPlugin.h
- Modules/Loadable/Sequences/Widgets/DesignerPlugins/qSlicerSequencesModuleWidgetsPlugin.h
- Modules/Loadable/Tables/qSlicerTablesModuleWidget.h
- Modules/Loadable/Tables/qSlicerTablesReader.h
- Modules/Loadable/Texts/Widgets/DesignerPlugins/qSlicerTextsModuleWidgetsPlugin.h
- Modules/Loadable/Units/Widgets/DesignerPlugins/qSlicerUnitsModuleWidgetsAbstractPlugin.h
- Utilities/Templates/Modules/LoadableCustomMarkups/Logic/vtkSlicerTemplateKeyLogic.h
- Utilities/Templates/Modules/LoadableCustomMarkups/MRML/vtkMRMLMarkupsTestLineNode.h
- Utilities/Templates/Modules/LoadableCustomMarkups/VTKWidgets/vtkSlicerTestLineRepresentation2D.h
- Utilities/Templates/Modules/LoadableCustomMarkups/VTKWidgets/vtkSlicerTestLineRepresentation3D.h
- Utilities/Templates/Modules/LoadableCustomMarkups/VTKWidgets/vtkSlicerTestLineWidget.h
- Utilities/Templates/Modules/LoadableCustomMarkups/Widgets/qMRMLMarkupsTestLineWidget.h
This commit updates the files to match any of these:
```
<stem>_h   (*)
__<stem>_h
__<STEM>_H
```
(*) Note that this is the preferred way because of the clang -Wreserved-id-macro
warning. See https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier
The following one-liner was used to identify the files:
```
for file in $(\
fd \
-e h \
-E "Modules/CLI/ExtractSkeleton/SkelGraph.h" \
-E "Modules/CLI/ExtractSkeleton/coordTypes.h" \
-E "Modules/CLI/ExtractSkeleton/misc.h" \
); do
filename=$(basename $file);
guard=${filename/./_};
cat $file | ack -i "define \_?\_?$guard" > /dev/null || echo "$file";
done
```
> COMP: Consistently define include guards to match filename

- Libs/MRML/DisplayableManager/vtkMRMLThreeDViewInteractorStyle.cxx
Following discussions on #6910, here is a new proposal for the addition of a virtual cursor in 3DSlicer.
The new approach consists in a model node being updated on CursorPositionModifiedEvent events.
As discussed with @lassoan, this MR:
1. applies the required changes to the 3D view interactor style for the cursor position to be updated in the 3D view too.
2. provides a small python script to test how the feature would behave once fully integrated: [TrackCursor.zip](https://github.com/Slicer/Slicer/files/11201330/TrackCursor.zip)
The goal is to confirm that such feature could be integrated in its own menu, and identify what would be the options that are exposed to users in terms of rendering properties, cursor models, Slice visibility... 
A few notes regarding the status of the example …
> Update crosshair cursor position on 3D view mouse move events

- Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx
- Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx
- Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.h
- Modules/Loadable/Markups/Widgets/qSlicerSimpleMarkupsWidget.cxx
- Modules/Loadable/Markups/Widgets/qSlicerSimpleMarkupsWidget.h
- Modules/Loadable/Plots/Widgets/qMRMLPlotChartPropertiesWidget.cxx
- Modules/Loadable/Plots/Widgets/qMRMLPlotChartPropertiesWidget.h
- Modules/Loadable/Plots/Widgets/qMRMLPlotSeriesPropertiesWidget.cxx
- Modules/Loadable/Plots/Widgets/qMRMLPlotSeriesPropertiesWidget.h
- Modules/Loadable/Tables/Widgets/qSlicerTableColumnPropertiesWidget.cxx
- Modules/Loadable/Tables/Widgets/qSlicerTableColumnPropertiesWidget.h
- Modules/Loadable/Texts/Widgets/qMRMLTextWidget.cxx
- Modules/Loadable/Texts/Widgets/qMRMLTextWidget.h
~~This adds the installation of the `ui_*.h` files as development files (headers) in `SlicerMacroBuildModuleQtLibrary`~~ This remove the inclusion of `ui_*.h` files (private) into `*.h` (public) headers. (see discussion below)
This is needed for modules building on install trees (of other modules or Slicer).
> ENH: Remove exposure of `ui_*.h` files from public `.h` files 

- Base/Python/slicer/ScriptedLoadableModule.py
- Base/QTGUI/Resources/UI/qSlicerSettingsPythonPanel.ui
- Base/QTGUI/qSlicerSettingsGeneralPanel.cxx
- Base/QTGUI/qSlicerSettingsPythonPanel.cxx
- Base/QTGUI/qSlicerSettingsPythonPanel.h
- Docs/developer_guide/python_faq.md
- Modules/Scripted/ScreenCapture/ScreenCapture.py
When "Developer mode" is enabled in Application Settings, "Edit" button opens the module .py file in the default program associated with .py files.
This is most commonly an editor, but some users associate .py files with a Python launcher (such as "c:/windows/py.exe"). In these cases, the module .py file is attempted to be launched instead of edited.
This commit adds a new "Editor for .py files" option Application settings / Python. If a text editor is specified there then that program will be launched to edit .py files.
If user holds down Shift key while clicking on "Edit" button then an editor is not launched but instead the full path is copied to the clipboard to allow the user to open it in an editor manually.
Also changed icon of opening of .sliccerrc.py file (file open button …
> ENH: Allow setting custom editor for .py files

- Base/QTCore/qSlicerScriptedFileReader.cxx
- Docs/user_guide/modules/dicom.md
- Modules/Scripted/DICOM/DICOM.py
Drag-and-dropping a DICOM file made Slicer use ITK DICOM reader, which often did not load the data correctly.
This commit adds a new "DICOM import" reader type, which is selected by default for DICOM files. This reader imports the files into the Slicer DICOM database and switches to the DICOM module.
The workaround of interpreting all files as DICOM by default while in DICOM module has now been removed. "Add data" window is brought up when loading a file, regardless of what is the active module. The workaround surprised users when they could not load non-DICOM data while they were in DICOM module.
If a user wants to read the DICOM file using ITK reader, it is possible by changing "Description" in the "Add data" module to "Volume".
fixes #5726
> ENH: Load DICOM files using DICOM module by default

- Docs/user_guide/modules/reformat.md
- Modules/Loadable/Reformat/Logic/vtkSlicerReformatLogic.cxx
- Modules/Loadable/Reformat/Logic/vtkSlicerReformatLogic.h
- Modules/Loadable/Reformat/Resources/UI/qSlicerReformatModuleWidget.ui
- Modules/Loadable/Reformat/qSlicerReformatModuleWidget.cxx
- Modules/Loadable/Reformat/qSlicerReformatModuleWidget.h
Users quite often ask about how to flip or rotate slice views. Slicers in Reformat module were suitable for this but were not very convenient or intuitive.
This commit adds "Flip H", "Flip V", "Rotate CW", "Rotate CCW" buttons to the Orientation section of the Reformat module. Internally they just rotate the slice view by 90 or 180 degrees around various slice axes. "Rotate to volume plane" button is also added for completeness.
Normal direction setting buttons and slice orientation sliders were renamed according to their actual function (normal vector is set to LR, PA, IS anatomical directions - not X, Y, Z; rotation happens around horizontal, vertical, normal slice axes - not around LR, PA, IS anatomical directions).
> ENH: Add flip and rotate buttons to Reformat module

- SuperBuild/External_VTK.cmake
This ensures that reading an empty "vtkPolyData" reports a warning instead of an error message.
```
$ git shortlog 6c02c9b376..8e0f1f9af7 --no-merges
[Backport MR-10295] Allow const std::vector<vtkSmartPointer<T>> in Python (part 2)
Steve Pieper (1):
[Backport MR-9648] BUG: error for non-fatal xml issue
```
> BUG: Update VTK to fix regression preventing from loading older vtp files

- Applications/SlicerApp/Testing/Python/SlicerOrientationSelectorTest.py
This commit is a follow-up of e75785816 (ENH: Add flip and rotate buttons to Reformat module (#7078)) accounting for the slide widget rename introduced in:
* https://github.com/Slicer/Slicer/pull/7078
> BUG: Fix SlicerOrientationSelectorTestTest to account for widget rename

- SuperBuild/External_qRestAPI.cmake
This commit is a follow-up of ea25fa65a (COMP: Replace deprecated Qt Script usage)
Follow-up of:
* https://github.com/Slicer/Slicer/pull/6710
> COMP: Update qRestAPI external project to use the correct GitHub organization

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorDrawEffect.py
- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorIslandsEffect.py
- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorLevelTracingEffect.py
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx
- Utilities/Templates/Modules/ScriptedSegmentEditorEffect/SegmentEditorTemplateKeyLib/SegmentEditorEffect.py
When the user starts a segment editing operation on an invisible segment a popup is displayed to confirm that it is intentional (usually not). This popup left some effects in inconsistent state (3D view rotation is initiated, some feedback actors were not cleaned up). This commit avoids these inconsistent states.
fixes #6748
> BUG: Fix behavior after invisible segment confirmation popup

- Libs/vtkITK/CMakeLists.txt
- Libs/vtkITK/vtkITKGrowCut.cxx
- Libs/vtkITK/vtkITKGrowCut.h
- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorGrowFromSeedsEffect.py
- Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py
This commit adds a new VTK filter vtkITKGrowCut, which uses the itk::FastGrowCut implementation.
The new filter is used in the "Grow from seeds" segment editor effect.
SegmentationsModuleTest2 now includes a Grow from seeds test.
> ENH: Add vtkITKGrowCut filter

- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
This change adds two menu actions in the subject hierachy tree view context menu to hide or show the selected items.
This is similar to the existing "Toggle visibility" menu action.
> ENH: Add menu actions to hide or show selected items in subject tree

- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
This commit adds a new function that allows unlocked markup points to move using the markup interaction handles. Currently, the interaction handles are disabled when any point is locked. This commit also fixes a bug where any points with an undefined position status are reset on using a markup's interaction handles. To support the new functionality, the interaction handle center of rotation is updated to ignore locked and undefined points. This commit is a product of the PW 39 2023 projects: https://projectweek.na-mic.org/PW39_2023_Montreal/Projects/TranslationRotationOfSelectPointsInAList/
and https://projectweek.na-mic.org/PW39_2023_Montreal/Projects/SlicerLiver/.
> ENH: Translation/rotation of unlocked points in a list

- Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Without this change the vtkITK code complained that a series of color dicom data could not be loaded.
It appears that when the check for grayscale was added it was only tested on single instance files, not on series in multiple files.
This change invokes the correct reader based on whether it's a single file or not.
> BUG: support color DICOM data series

- CMake/SlicerCPack.cmake
Introduced by https://github.com/Slicer/Slicer/commit/43dd44e85c210fc09375997bd435da61adbe136b
I was using this along with `mark_as_superbuild(Slicer_CPACK_NSIS_INSTALL_SUBDIRECTORY "${Slicer_ORGANIZATION_NAME}")` in the CMakeLists.txt of my Slicer custom app to change the default system level install location from "C:/Program Files/{ApplicationName}" to "C:/Program Files/{OrganizationName}/{ApplicationName}
> BUG: Fix CPACK_NSIS_INSTALL_SUBDIRECTORY being overwritten

- SuperBuild/External_VTK.cmake
This commit updates VTK to include an empty commit working around the fact CTest incorrectly flag the external project update output as an error.
It fixes a regression introduced in e3aadb552 (BUG: Update VTK to fix regression preventing from loading older vtp files)
To illustrate, it flags the following output as an error on Linux and Windows:
```
Cloning into 'VTK'...
HEAD is now at 8e0f1f9af7 [Backport MR-9648] BUG: error for non-fatal xml issue
Submodule 'VTK-m' (https://github.com/KitwareMedical/vtk-m.git) registered for path 'ThirdParty/vtkm/vtkvtkm/vtk-m'
Cloning into '/.../Slicer-0-build/VTK/ThirdParty/vtkm/vtkvtkm/vtk-m'...
[...]
```
This happens despite of having "HEAD is now" being listed in `CTEST_CUSTOM_WARNING_EXCEPTION` in `CMake/CTestCustom.cmake.in`. …
> COMP: Update VTK to workaround external project output flagged as error

- SuperBuild/External_CTK.cmake
This update does not integrate any functional changes.
See https://github.com/commontk/CTK/compare/491614f12...9856b3fcf
Note that within the span of this update, commit commontk/CTK@9856b3fcf [^1] reverts the effect of commit commontk/CTK@7bb0d9fdb [2].
[^1]: commontk/CTK@9856b3fcf (`BUG: Fix ctkDICOMIndexer reverting back to functor signal/slot`)
[^2]: commontk/CTK@7bb0d9fdb (`COMP: Fix Qt4/C++98 ctkDICOMIndexerPrivate build using literal signal/slot`)
```
$ git shortlog 491614f12..9856b3fcf --no-merges
Jean-Christophe Fillion-Robin (50):
COMP: Update ctkCompilerDetections_p.h to include CTK_OVERRIDE
COMP: Fix Qt4/C++98 build updating Widget & DICOM libraries to use CTK_OVERRIDE
COMP: Fix Qt4/C++98 build using '> >' instead of '>>' in nested templates
COMP: Update …
```
> STYLE: Update CTK

- Modules/Loadable/CropVolume/qSlicerCropVolumeModuleWidget.cxx
- SuperBuild/External_CTK.cmake
This fixes a regression introduced in commontk/CTK@e66324212 (COMP: Fix deprecated warning related to QWidget::getContentsMargins()).
Since functions `QWidget::contentsRect()` and `QWidget::contentsMargins()` are not equivalent, the logic associated with `ctkFlowLayout::minimumSize()` and `ctkFlowLayout::sizeHint()` was incorrect.
For future reference, modules using `ctkFlowLayout` are the following:
* CLIs (`Base/QTCLI/qSlicerCLIModuleUIHelper.cxx`)
* Loadable:
- Segmentations (`qSlicerSegmentationsIOOptionsWidget.cxx`)
- Volumes (`qSlicerVolumesIOOptionsWidget.cxx`)
- Data (`qSlicerSceneIOOptionsWidget.cxx`)
* Scripted
- SampleData (`SampleData.py`)
Additionally, it updates `CropVolumeModuleWidget` removing unused `ctkFlowLayout` include. Following 4cacc07bd (`ENH: Improved Crop Volume …
> BUG: Update CTK to fix initial sizing of modules using ctkFlowLayout

- SuperBuild/External_python-extension-manager-ssl-requirements.cmake
This commit fixes a regression introduced in 7d58308e2 (`COMP: Update python packages to latest) by explicitly specifying "[crypto]"`).
It addresses the following error reported on macOS, Linux and Windows when doing a clean build:
```
${SLICER_BUILD_DIR}/python-install/bin/PythonSlicer \
-m pip install \
--require-hashes \
-r ${SLICER_BUILD_DIR}/python-extension-manager-ssl-requirements-requirements.txt
[...]
Collecting pyjwt[crypto]>=2.4.0 (from PyGithub==1.59.0->-r <SLICER_BUILD_DIR>/python-extension-manager-ssl-requirements-requirements.txt (line 85))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
pyjwt[crypto]>=2.4.0 from https://files.pythonhosted.org/packages/2b/4f/e04a8067c7c96c364cef7ef73906504e2f40d690811c021e1a1901473a19/ …
```
> COMP: Fix python-extension-manager-ssl-requirements build specifying "[crypto]"

- Libs/MRML/DisplayableManager/vtkMRMLModelSliceDisplayableManager.cxx
- Libs/vtkSegmentationCore/vtkBinaryLabelmapToClosedSurfaceConversionRule.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.h
- Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager2D.cxx
With the current VTK a `vtkCompositeDataGeometryFilter` cannot be used with a `vtkPolyData` so we use a `vtkGeometryFilter` instead.
Fixes:
* #7101
> Fix "Model",  "plane markups" and "segmentation closed surface" slice intersections display

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
This pull request fixes a regression introduced in 530b8fcdc (ENH: Update Slicer Controller adding Thick Slab Reconstruction (#7021)) and fixes these tests:
- `qMRMLSliceWidgetTest1_vol_and_cube.mrml`
- `qMRMLVolumeThresholdWidgetTest2_vol_and_cube.mrml`
The problem was that in the context of these tests the call to `vtkMRMLSliceLayerLogic::SetSliceNode` happens after `UpdateSliceCompositeNode`
For reference the sequence of calls lead to the segfault for test `qMRMLSliceWidgetTest1_vol_and_cube` was the following:
```
#20 main(int, char**) (ac=<optimized out>, av=<optimized out>)
#19 qMRMLSliceWidgetTest1(int, char**)
#18 qMRMLSliceWidget::setMRMLSliceNode(vtkMRMLSliceNode*)
#17 qMRMLSliceControllerWidget::setMRMLSliceNode(vtkMRMLSliceNode*) (this=
#16 …
```
> BUG: Fix potential segfault during initialization of qMRMLSliceWidget

- Docs/developer_guide/style_guide.md
- Docs/user_guide/extensions_manager.md
- Docs/user_guide/modules/cropvolume.md
- Docs/user_guide/modules/dicom.md
- Docs/user_guide/settings.md
Fix miscellaneous typos across documentation markdown files. Specifically:
- Remove duplicate `the` article in consecutive appearances.
- Use lowercase in `millimeter`.
> DOC: Fix miscellaneous typos in the documentation

- Modules/Loadable/Models/qSlicerModelsReader.cxx
- Modules/Loadable/Models/qSlicerModelsReader.h
.vtk files tried to be loaded as Model node by default. Loading failed when attempted to load an image file without manually setting Description to Volume in "Add data" window.
This commit makes .vtk image file loaded as image by default, avoiding user questions such as this one: https://discourse.slicer.org/t/error-exporting-and-importing-vtk/30733/2
> ENH: Make it easier to load of .vtk image files

- Base/Python/slicer/ScriptedLoadableModule.py
Some modules don't behave well under Reload which means that Reload & Test cannot be used.
This adds a Test button to the UI of ScriptedLoadableModule and enables access to the unit tests
> ENH: Add "Test" Button to ScriptedLoadableModule UI

- Base/QTGUI/qSlicerSaveDataDialog.cxx
Set a stylesheet that sets the unchecked background to alternate base for QCheckBox in options column and QAbstractItemView in filename column.
fixes #5185
References:
* https://doc.qt.io/qt-5/stylesheet-reference.html#paletterole
* https://doc.qt.io/qt-5/stylesheet-reference.html#list-of-stylable-widgets
> BUG: Fix rendering of SaveDataDialog checkboxes in Dark Mode

- Modules/Loadable/Markups/MRML/vtkCurveMeasurementsCalculator.cxx
Torsion computation may contain a NaN value when extracting. A similar error was reported for VMTK (https://discourse.slicer.org/t/error-exporting-and-importing-vtk/30733/6) and the same may have occurred in Slicer core, too.
> BUG: Fix potential NaN in torsion computation results

- Docs/developer_guide/extensions.md
Fix developer guide extensions section extension build tip box bash snippet syntax: enclose the bash code snippet with triple backticks. Remove the double colon at the end of the accompanying text.
Explicitly state the highlight to correspond to bash code.
Take advantage of the commit to fix a typo in the accompanying text.
> DOC: Fix developer guide extensions section bash snippet syntax

- SuperBuild/External_CTK.cmake
This pull request supersedes:
* https://github.com/Slicer/Slicer/pull/6165
It ensures CTK only requires the Qt components it uses.
```
$ git shortlog ee5508d6..c0c8e41db --no-merges
COMP: Update ctk_list_to_string to use CMake join implentation if available
ENH: Display Qt version and Qt components used to configure CTK
ENH: Simplify setting of CTK_QT5_COMPONENTS ensuring all CTK variables are set
ENH: Improve setting of CTK_QT5_COMPONENTS based on actual requirements
```
_Output based of Slicer/Slicer@77f1e2d06c after manually checking out commontk/CTK#1132 and re-configuring CTK_
Before:
```
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Xml, XmlPatterns, Concurrent, Sql, Test, Multimedia, Widgets, OpenGL, UiTools)
```
After:
```
-- …
```
> COMP: Update CTK to ensure only used Qt components are expected

- SuperBuild/External_CTK.cmake
This commit is a following up of the previous commit introduced through this pull request:
*https://github.com/Slicer/Slicer/pull/7129
It ensures that CTK QtTesting library is also properly linked.
Before (both https://github.com/Slicer/Slicer/pull/7129 and this pull request):
```
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Xml, XmlPatterns, Concurrent, Sql, Test, Multimedia, Widgets, OpenGL, UiTools)
```
After:
```
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Xml, XmlPatterns, Sql, Multimedia, Widgets, OpenGL, UiTools, Designer)
```
```diff
Core
Xml
XmlPatterns
- Concurrent
Sql
- Test
Multimedia
Widgets
OpenGL
UiTools
+ Designer
```
```
$ git shortlog c0c8e41d..dc0d7eb5 --no-merges
COMP: Fix CTK QtTesting …
```
> COMP: Update CTK to ensure only used Qt components are expected (part 2)

- CMake/SlicerLinkerAsNeededFlagCheck/CMakeLists.txt
Call cmake minimum required prior to top-level project.
Fixes:
```
CMake Warning (dev) at
Slicer/CMake/SlicerLinkerAsNeededFlagCheck/CMakeLists.txt:1 (project):
cmake_minimum_required() should be called prior to this top-level project()
call.  Please see the cmake-commands(7) manual for usage documentation of
both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
Visible, for example, in:
https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5685861171/job/15411625384#step:6:39
> COMP: Call cmake minimum required prior to top-level project

- CMake/ExternalProjectDependency.cmake
- SuperBuild/External_CTK.cmake
- SuperBuild/External_Swig.cmake
- SuperBuild/External_python.cmake
This fixes `DOWNLOAD_EXTRACT_TIMESTAMP` warnings related to `CMP0135`[^1] introduced in CMake >= 3.24.
[^1]: https://cmake.org/cmake/help/latest/policy/CMP0135.html
* Updates `ExternalProjectDependency` CMake module based on the latest version provided by https://github.com/commontk/artichoke
* Updates `CTK` so that its bundled version of `ExternalProjectDependency` is also the most recent
* Updates `Swig` and `python` external projects to explicitly set `DOWNLOAD_EXTRACT_TIMESTAMP` to `1` if using  CMake >= 3.24. This is needed because these projects are directly using `ExternalProject_Add` (without relying on `ExternalProject_Include_Dependencies`)
This will avoid warnings like the following:
```
CMake Warning (dev) at /path/to/cmake-3.26.4-linux-x86_64/share/cmake-3.26/Modules/ExternalP …
```
> Fix external project download extract timestamp warnings

- SuperBuild/External_VTK.cmake
This fixes a regression introduced in Kitware/VTK@926ec960d (`Fixed ASan buffer under-read in FiltersCorePython-cutLoop test`) through https://github.com/Slicer/Slicer/pull/7010
```
$ git shortlog a3ab617b0f..4341e48252 --no-merges
Sean McBride (1):
[Backport MR-10360] Restored correct wrapping in vtkSelectPolyData::IsBoundaryEdge
```
> BUG: Update VTK to fix regression in Dynamic modeler Curve cut

- Applications/SlicerApp/Testing/Python/SlicerScriptedFileReaderWriterTest.py
- Base/QTCore/qSlicerFileReader.h
- Modules/Scripted/ImportItkSnapLabel/ImportItkSnapLabel.py
In scripted file readers, file extension was not checked when determining if a file can be loaded. This can result in unnecessary checks when inspecting any file before loading.
see https://github.com/PerkLab/SlicerSandbox/issues/18
> ENH: Check file extension file readers before inspecting content

- SuperBuild.cmake
Time sequence of volumes can be loaded as multivolume (vtkMRMLMultiVolumeNode) or volume sequence (vtkMRMLSequenceNode). Volume sequence is a more generic representation and many more modules use it than the old multivolume representation.
This commit changes the default so that when a user loads a 4D volume from DICOM then it is loaded into a volume sequence by default.
Users can revert to the old behavior by selecting in Application settings / DICOM / Preferred multi-volume import format -> multi-volume. For loading a single image using non-default settings, enable "Advanced" option in DICOM module, click Examine, and choose the appropriate loadable (loadables are offered for both multivolme and volume sequence representation, application settings specify which is selected by default).
> ENH: Update MultiVolumeImporter to load as volume sequence by default

- Base/Python/slicer/util.py
This was created based of changes originally contributed through:
* https://github.com/Slicer/Slicer/pull/6733
> ENH: Update slicer.util.updateVolumeFromArray to support 1D NumPy array

- Applications/SlicerApp/Testing/Python/SlicerScriptedFileReaderWriterTest.py
This is a follow-up of 8381ef3e6 (BUG: Improve error reporting in file loading)
It was created based of changes originally contributed through:
* https://github.com/Slicer/Slicer/pull/6733
> ENH: Improve error reporting in ScriptedFileReaderWriterTest

- Base/QTCore/qSlicerExtensionsManagerModel.cxx
- Base/QTCore/qSlicerExtensionsManagerModel.h
By default, the extension and its dependencies are installed and the application restarted also after asking the user to confirm each.
If testing mode is enabled, the extension and its dependencies are installed without asking for confirmation. In this the application is not restarted.
> ENH: Add extension model API for downloading and installing an extension

- Base/QTGUI/qSlicerExtensionsLocalWidget.cxx
This commit fixes a regression introduced in c904ea00b (STYLE: Mark translatable strings in Base/QTGUI) through:
* https://github.com/Slicer/Slicer/pull/6704
It addresses warnings like the following:
```
QString::arg: Argument missing: Incompatible with Slicer r#bd8530 [built for r31917], 31916
```
References:
* https://github.com/Slicer/SlicerLanguagePacks/issues/12
> BUG: Fix setting of color in qSlicerExtensionsLocalWidget status messages

- Modules/Scripted/DICOMLib/DICOMBrowser.py
The key word Warning: was appearing twince in the concatenation of warning messages.
> BUG: Remove redundant "Warning:" prefix in DICOM popup 

- Base/QTGUI/qSlicerApplication.cxx
This closes #7154.
This removes the "Ctrl+H" shortcut defined for the ctkConsole so that it does not conflict with the "Ctrl+H" shortcut to go to the Slicer "Home" module.
Currently when the python console is visible "Ctrl+H" does not work for either of the defined slots and the following error is reported: [Qt] QAction::event: Ambiguous shortcut overload: Ctrl+H
> BUG: Fix home shortcut not working when python console visible

- SuperBuild/External_ITK.cmake
These changes are specific to the ITK Python wheels and are not directly used in Slicer.
They are backported for consistency sake anticipating the integration of the python utility functions supporting ITK image <-> volume node conversion:
* https://github.com/Slicer/Slicer/pull/7094
```
$ git shortlog c927a320a7..37c5991ee5 --no-merges
Dženan Zukić (1):
[Backport] ENH: Better support for multi-component images in image_from_vtk_image
[Backport] ENH: Ensure 3D multi-components conversion in image_from_vtk_image is tested
```
> STYLE: Update ITK to minimize confusion related to image_from_vtk_image support

- Base/Python/slicer/util.py
<s>This was adapted from https://github.com/KitwareMedical/SlicerITKUltrasound/blob/6d7ea98bc329fc52e9c9bfddccc807cf76806fc2/ITKUltrasoundCommon/ITKUltrasoundCommon.py#L98-L204</s>
**Update:** This was adapted from https://discourse.slicer.org/t/installing-itk-python-package-in-slicer-5-1-and-above/25636
> Add Python utility functions: ITK image <-> volume node

- Docs/developer_guide/python_faq.md
Fix the following warning introduced in 44a5f634d (ENH: Allow setting custom editor for .py files (#7074)):
```
/path/to/Slicer/Docs/developer_guide/python_faq.md:306:
WARNING: Pygments lexer name 'txt' is not known
```
> COMP: Fix sphinx build warning in Python FAQ related to unknown "txt" lexer

- Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
Create a consolidated `DEFAULTS` dictionary to centralize default values. This guarantees consistent utilization of these values during both UI initialization and after clicking on the "Restore Defaults" button.
Fix a regression introduced in 2e8238c3e (`ENH: Added orientation marker to slice view annotations.`) where the values set during UI initialization and after the "Restore Defaults" action became different.
----
This pull request was created while working on this issue:
* https://github.com/Slicer/Slicer/issues/7092
> BUG: Sync DataProbe UI initialization and "Restore Defaults" action

- Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
Ensure that the visibility of the corner annotation displaying the thickness is automatically toggled without requiring the user to explicitly do so in the DataProbe module.
If the visibility of the corner annotation was enabled by "forcing", it will not be saved in the settings.
Fixes #7092
> ENH: Ensure slab reconstruction thickness is visible in slice view corner

- CMakeLists.txt
Ensure that `Slicer_WC_COMMIT_COUNT_OFFSET` cache value used to compute `Slicer_REVISION` when revision type is "CommitCount" is also updated for existing build.
It ensures the value is always current by switching the cache variable type to `INTERNAL` implying that the value is always forced.
Before:
```
-- Configuring Slicer revision [31939]
```
After:
```
-- Configuring Slicer revision [32139]
```
> COMP: Ensure revision of type CommitCount is always re-computed based on offset

- CMake/SlicerExtensionCPack.cmake
Since the output of `otool -L` reports paths with synthetic firmlinks resolved (see `GetPrerequisitesWithRPath`), we are using the `REAL_PATH` file command to also resolve `Slicer_SUPERBUILD_DIR` and ensure that the test in `SlicerExtensionCPackBundleFixup.cmake.in` checking if `${key}_ITEM` is a library built in Slicer itself work as expected.
To illustrate, copied below is the content of the ImageMaker extension package before/after implementing the fix.
```
$ pwd
/D/P/S-0-E-b/ImageMaker-build/_CPack_Packages/Darwin/TGZ/32140-macosx-amd64-ImageMaker-git6293f99-2017-07-03/Slicer.app/Contents
```
Before:
```
$ find .
.
./Extensions-32140
./Extensions-32140/ImageMaker
./Extensions-32140/ImageMaker/lib
./Extensions-32140/ImageMaker/lib/Slicer-5.5 …
```
> COMP: Fix extension packaging on macOS accounting for synthetic firmlink

- CMake/SlicerExtensionCPack.cmake
Backport of 858c19515f5e4eb69145f0b8c38aa8525b56521f originally introduced through:
* https://github.com/Slicer/Slicer/pull/7181
> [5.4] COMP: Fix extension packaging on macOS accounting for synthetic firmlink

- SuperBuild.cmake
Wrong button for tooltip:
https://github.com/pieper/CompareVolumes/commit/cb755dda78f726cf9262aa4e1f75122c72a0df2f
> COMP: Update CompareVolumes tag to fix typo

- SuperBuild/External_VTK.cmake
```
$ git shortlog 4341e48252..abbbb1bc3a --no-merges
[Backport MR-10449] OpenXRRemoting: Streamline integration as plugin
```
> ENH: Update VTK to support distribution of OpenXRRemoting in extension

- Extensions/CMake/SlicerBlockAdditionalLauncherSettings.cmake
Ensure that the placeholder `<CMAKE_CFG_INTDIR>` is also expanded when used in custom extension launcher settings specified in external project.
This is a follow-up of ee90f2b15 (`ENH: Support custom additional launcher settings in extension external proj`)
> COMP: Expand <CMAKE_CFG_INTDIR> in extension additional launcher settings

- SuperBuild/External_VTK.cmake
```
$ git shortlog abbbb1bc3..5c3135299 --no-merges
[Backport MR-10450] OpenXR: Improve XrCheckOutput API fixing constness of level parameter
[Backport MR-10450] OpenXRRemoting: Fix windows build using XrCheckOutput instead of XrCheckError
Mathieu Westphal (2):
[Backport MR-10450] OpenXR: Generalize XrCheck* into a single method
[Backport MR-10450] OpenXR: Downgrade action suggestions to debug output
```
> ENH: Update VTK to backport OpenXR error handling improvements

- SuperBuild/External_VTK.cmake
```
$ git shortlog 5c313529..b261e0c1 --no-merges
Alexy Pellegrini (1):
[Backport] Prevent widgets and floor from being clipped using interactive crop in VR
[Backport MR-10452] OpenXR: Consistently name manifest install sub-directory
Mathieu Westphal (1):
[Backport] VR: Fix ground movement
Thomas Galland (1):
[Backport] Update obsolete VR documentation
Tom Birdsong (1):
[Backport] DOC: Add `OpenVR`, `OpenXR`, and `OpenXRRemoting` README
```
> ENH: Update VTK backporting RenderingVR and RenderingOpenXR fixes

- .github/workflows/scorecard.yml
- README.md
This adds the OSSF scorecard action (https://github.com/ossf/scorecard-action) to display open-source health. 
Some security engineering groups have requested that open-source repositories should display their OSSF score. Adding this GitHub action will help fulfill their request. [`numpy`](https://github.com/numpy/numpy#readme) is a major open source repo that has adopted the OSSF score and present the badge on their readme. `numpy`'s full scorecard https://securityscorecards.dev/viewer/?uri=github.com/numpy/numpy reports a 7.5 score.
As of right now the Slicer OSSF score is a 5.4 for my fork specifically (this will be slightly different for the Slicer upstream as there are protected branches in the upstream which will give a higher score). You may be able to see the score reported on my …
> ENH: Add OSSF scorecard action to quantify open-source health

- Docs/conf.py
Explicitly setting the theme is required following the release of ReadTheDocs 10.1.0:
> Build: do not set sphinx_rtd_theme theme automatically
See https://docs.readthedocs.io/en/stable/changelog.html#version-10-1-0
For reference, the approach used in Slicer was officially removed from sphinx_rtd_theme in readthedocs/sphinx_rtd_theme@dc9d3d732 (`Readme: remove outdated text about building on rtd`)
| Before | After |
|--|--|
| ![image](https://github.com/Slicer/Slicer/assets/219043/5137199d-c74b-494a-933a-ef415a25555c) | ![image](https://github.com/Slicer/Slicer/assets/219043/93fff06c-56af-49af-a29c-544be5537258) |
> DOC: Ensure published documentation uses "sphinx_rtd_theme"

- Applications/SlicerApp/slicer-application-properties.cmake
- CMake/SlicerGenerateSlicerConfig.cmake
Fix regression introduced in 2fe5bdee41 (DOC: Convert README to markdown for adding of badges) through https://github.com/Slicer/Slicer/pull/7197
> COMP: Fix configuration referencing README.md

- Base/QTCLI/qSlicerCLIProgressBar.cxx
- Base/QTCore/qSlicerCoreApplication.cxx
- Libs/MRML/CLI/vtkMRMLCommandLineModuleNode.cxx
- Libs/MRML/CLI/vtkMRMLCommandLineModuleNode.h
- Libs/MRML/Core/CMakeLists.txt
- Libs/MRML/Core/Testing/CMakeLists.txt
- Libs/MRML/Core/Testing/vtkMRMLI18NTest1.cxx
- Libs/MRML/Core/vtkMRMLColorTableStorageNode.cxx
- Libs/MRML/Core/vtkMRMLI18N.cxx
- Libs/MRML/Core/vtkMRMLI18N.h
- Libs/MRML/Core/vtkMRMLLinearTransformSequenceStorageNode.cxx
- Libs/MRML/Core/vtkMRMLModelStorageNode.cxx
- Libs/MRML/Core/vtkMRMLProceduralColorStorageNode.cxx
- Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx
- Libs/MRML/Core/vtkMRMLSequenceStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTableSQLiteStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTableStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTextStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTranslator.h
- Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialStorageNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonStorageNode.cxx
- Modules/Loadable/VolumeRendering/MRML/vtkMRMLShaderPropertyStorageNode.cxx
- Modules/Loadable/VolumeRendering/MRML/vtkMRMLVolumePropertyStorageNode.cxx
Allows using Qt translation infrastructure in MRML to translate text, without directly depending on Qt.
Fixes https://github.com/Slicer/Slicer/issues/6647
> Make text in MRML library translatable

- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
Fix a bug where the closing segment (from the last control point to the first control point) in a closed curve is not incorporated into a `vtkMRMLMarkupsCurveNode::GetCurveLength` computation in all cases that it should be.  Specifically, a computation where
```c++
startCurvePointIndex <= lastCurvePointIndex &&
startCurvePointIndex + numberOfCurvePoints - 1 > lastCurvePointIndex
```
should include the closing segment's length even when the requested `numberOfCurvePoints` is not strictly greater than the number of control points.
> BUG: Include closing segment of closed curve when appropriate.

- SECURITY.md
This pull request follows up https://github.com/Slicer/Slicer/pull/7197 and is expected to address the `Security Policy` warning[^1] reported on our scorecard (as of https://github.com/Slicer/Slicer/commit/9ceb5d25e634ce7bf6438e4c907959e497e9c1b3).
Language was adapted from https://github.com/microsoft/vscode/blob/main/SECURITY.md
[^1]: https://github.com/ossf/scorecard/blob/v4.12.0/docs/checks.md#security-policy
In this pull request, it assumes we create a private discourse category called `Security` associated with the email `slicer+security@discoursemail.com`
Alternatively, as illustrated below, we could also enable the built-in `private vulnerability reporting`[^2] feature available in GitHub.
[^2]: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and- …
> DOC: Add security policy document

- SuperBuild/External_VTK.cmake
`vtkTransformPolyDataFilter` is often used in pipelines where it is completely valid to have empty input.
For example, when slicing through a mesh with a plane, the output may be empty if the plane does not happen to intersect any part of the mesh. Logging an error pollutes the error log and if performed too frequently then it may slow down an application.
```
$ git shortlog b261e0c1b..b142c0d08 --no-merges
[Backport] Remove unnecessary "No input data" error message in vtkTransformPolyDataFilter
```
> BUG: Update VTK to remove unnecessary messages in vtkTransformPolyDataFilter

- Libs/MRML/Widgets/qMRMLPlotViewControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLViewControllerBar.cxx
If restyling ToolButtons as a whole through QSS with a fixed vertical size set, but a variable width allowed, the fixed size specification in qMRMLViewControllerBar was still forcing these buttons to be 15px wide.
| `main` | This PR |
|--------|----------|
|![image](https://github.com/Slicer/Slicer/assets/15837524/37f1351e-a30d-4c19-a063-52df2a026466)|![image](https://github.com/Slicer/Slicer/assets/15837524/a113dd03-010a-4bb2-83ff-81f32ed4454a)|
Now these buttons are sized based on their contents which in this case is their icon. This results in a slightly different spacing and sizing as previously the FixedSize call was actually cutting off part of the ToolButton's normal margin/padding. However I think the end result is near identical and functionally acts the same. This change …
> ENH: Remove fixed size buttons in view controller for better restyling

- Docs/user_guide/modules/comparevolumes.md
- Docs/user_guide/modules/index.md
Refers to images that have already been added to the release assets.
Migrates documentation from this post:
https://discourse.slicer.org/t/link-views-in-three-over-three-configuration/24564/5
> DOC: Add docs for CompareVolumes module

- Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentsPlugin.cxx
Many times it would have come in handy to be able to see the segment ID for certain segments in a segmentation in the subject hierarchy tooltip. This commits adds this information.
> ENH: Show segment ID in tooltip for segments in subject hierarchy

- Modules/Loadable/SubjectHierarchy/Widgets/CMakeLists.txt
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyExpandToDepthPlugin.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyExpandToDepthPlugin.h
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyFolderPlugin.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyFolderPlugin.h
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.h
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx
- Modules/Scripted/DICOMLib/SubjectHierarchyPlugins/qSlicerSubjectHierarchyDICOMPlugin.cxx
- The SH tree view saves the "current tree view" pointer in the SH plugin handler
- When the user creates a new folder, the folder plugin enables showing empty folders in the sort filter proxy model of the current tree view, and stores the tree view pointer in a list
- Right-clicking on scene or any item, the folder plugin shows a new "Show empty folders" action if the user has created a new folder from that tree view (i.e. the current tree view is in the list)
- The DICOM plugin (providing the Subject and Study hierarchy items) behaves the same way as the Folder plugin
- New plugin created for the Expand to depth feature (used to be a core SH tree view feature)
> Empty folder SH visibility

- Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLViewControllerBar.cxx
This is work for #7233.
https://github.com/Slicer/Slicer/commit/8e70f763b0b351db00d8851871e68f11469d1a2e introduced this issue of light text being used for the slice offset text when in Slicer dark mode. Dark text was correctly being used in Slicer light mode. This change uses dark text regardless of current Slicer style.
|`main` | This PR |
|--------|---------|
|![image](https://github.com/Slicer/Slicer/assets/15837524/2c02fa42-c177-44ed-93ed-fd9b2c19834f)|![image](https://github.com/Slicer/Slicer/assets/15837524/8aa9675a-0798-4025-8934-d96af67239df)|
> BUG: Fix difficult to see slice offset text in Slicer dark mode

- Base/QTApp/Resources/UI/qSlicerErrorReportDialog.ui
- Base/QTApp/qSlicerErrorReportDialog.cxx
- Base/QTGUI/qSlicerApplication.cxx
Making the log file display more human-readable would contribute to the improvement of the error reporting workflow.  This would allow users to more easily determine which log file(s) are related to their error.
This PR changes the displayed text of the log entries in the error dialog while preserving the original function and tooltip. 
|---------|----------|
|![image](https://github.com/Slicer/Slicer/assets/88200986/18a0ec1a-0566-44fa-b21e-689d93086a49)|![image](https://github.com/Slicer/Slicer/assets/88200986/f4db6592-586e-40f0-aefc-47721a3aceef)|
> ENH: Make datetime string in error dialog more readable

- Base/QTApp/qSlicerErrorReportDialog.cxx
- Base/QTGUI/qSlicerApplication.cxx
Introduced in https://github.com/Slicer/Slicer/pull/7225#issuecomment-1729384982
This PR uses the log filename to get app version and revision number to report in the error report dialog:
`ENH: Report custom application revision in log filename` uses the custom-app revision number rather than the slicer revision number. This won't change anything from the slicer side, but could be beneficial for custom applications. (needs to be tested)
> BUG: Use log filename to get app version and revision

- CMake/SlicerMacroBuildApplication.cmake
- CMake/SlicerPackageAndUploadTarget.cmake
- CMakeLists.txt
- Extensions/CMake/SlicerBlockUploadExtension.cmake
- Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake
- SuperBuild/External_JsonCpp.cmake
- SuperBuild/External_OpenSSL.cmake
Starting with CMake 3.21, use of CMAKE_CFG_INTDIR has been deprecated.
> Remove use of deprecated ${CMAKE_CFG_INTDIR} variable

- .github/actions/slicer-build/entrypoint.sh
- .github/workflows/ci.yml
Set the step id to `slicer-build` to ensure the use of `${{ steps.slicer-build.outputs.package }}` in the _Upload Slicer package_ step effectively lookup the package.
Follow up of these pull requests:
* https://github.com/Slicer/Slicer/pull/6051
* https://github.com/Slicer/Slicer/pull/6053
Also fix the following warning:
> The `set-output` command is deprecated and will be disabled soon.
> Please upgrade to using Environment Files.
> For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Temporarily including the following patch to the pull-request allowed to test the changes:
```diff
diff --git a/.github/actions/slicer-build/entrypoint.sh b/.github/actions/slicer-build/entrypoint.sh
index 2caf49c7f02..50e709c8579 …
```
> COMP: Fix "ci" GitHub workflow ensuring Slicer package is uploaded

- Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
Also simplify setting of checkbox state in SliceViewAnnotations
----
This pull request was created while working on this issue:
* https://github.com/Slicer/Slicer/issues/7092
> ENH: Support restoring SliceViewAnnotations enabled state

- Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx
When removing a vtkMRMLSegmentationNode using the SubjectHierarchy tree, all of the virtual children would be removing before the segmentation. This caused a large number of updates in various segmentation widgets as all of the widgets were regenerated when each of the segments were removed from the segmentation node.
This commit improves performance by blocking modification events on the segmentation node (or any other node with virtual children), until all of the children have been removed. Rendering is also blocked during the item removal to prevent unnecessary updates of the views.
> PERF: Improve performance when removing segmentation from SH tree

- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.cxx
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionRepresentation2D.cxx
In vtkMRMLSliceIntersectionInteractionRepresentation:
* `SetHandlesVisibility` -> `SetIntersectionHandlesVisibility`
* `GetVisibility` -> `GetIntersectionVisibility`
In vtkMRMLSliceIntersectionRepresentation2D:
* `GetVisibility` -> `GetIntersectionVisibility`
* `SetVisibility` -> `SetIntersectionVisibility`
This change is done anticipating the integration of:
* https://github.com/Slicer/Slicer/pull/7093
> STYLE: Improve naming of internal SliceIntersection representation API

- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.cxx
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.h
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentationHelper.cxx
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentationHelper.h
Follow-up of https://github.com/Slicer/Slicer/commit/bc5d5b45fcb1949a2545ee1c2e2c1f35976698ac (`ENH: Add interactive slice intersections widget`) integrated through:
* https://github.com/Slicer/Slicer/pull/6124
Simplify and fix the `SliceIntersectionInteractionRepresentationHelper` class
This change is done anticipating the integration of:
* https://github.com/Slicer/Slicer/pull/7093
> Fix intersection interaction representation helper

- Docs/user_guide/modules/markups.md
Current behavior was not well documented - see https://discourse.slicer.org/t/markup-renaming-error-loses-numbering/31971/4
> DOC: Clarify markup renaming behavior

- Modules/CLI/FiducialRegistration/FiducialRegistration.cxx
- Modules/CLI/FiducialRegistration/FiducialRegistration.xml
When Rigid transform type was selected in Fiducial Registration module, the resulting transform included scaling (scale factor != 1.0) as reported at https://discourse.slicer.org/t/rigid-transformation-is-scaling/31953
The problem occurred because ITK landmark initializer has been improved so that it can now compute scaling. Fixed this by using more specific transform types (rigid/similarity).
Since ITK now also supports "affine" transform initialization, this option is now exposed in the module as well.
> BUG: Fix Fiducial Registration module rigid transform changing scale

- Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
- Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.h
- Modules/Loadable/Segmentations/Resources/UI/qSlicerSegmentationsSettingsPanel.ui
- Modules/Loadable/Segmentations/qSlicerSegmentationsSettingsPanel.cxx
- Modules/Loadable/Segmentations/qSlicerSegmentationsSettingsPanel.h
Hi @lassoan ,
Following this [feature request](https://discourse.slicer.org/t/consider-a-non-destructive-default-in-segment-editor-masking-options/30631/4), can you check this PR ?
It adds a combobox in settings for Segmentations, fills it with possible values, and fails to save/restore the chosen option.
When an option is selected, the Segment editor does use it by default. Once Slicer is closed, the chosen preferred option is not restored on restart.
Thank you for any input to get it working.
> ENH: Add a setting for the overwrite mode masking option of the segment editor

- Modules/Loadable/Segmentations/qSlicerSegmentationsSettingsPanel.cxx
- Modules/Scripted/DataProbe/DataProbe.py
This PR contains small fixes, see details in the commits. Do not squash merge.
<del>Add masked median filter needed for RGBA volume generation - see https://github.com/Slicer/VTK/pull/43.</del> _moved masked median filter to VTK (Merge https://github.com/Slicer/VTK/pull/44)_
> Two small fixes

- CMake/SlicerMacroBuildApplication.cmake
This ensures that the custom application version number is used to the macOS 'Quick Look' feature
Follow on fix to: https://github.com/Slicer/Slicer/commit/d004e4e394bba81d92df506b70b4b263656c094d for another version string that was missed in the initial fix.
Example of the bug:
> BUG: Use main project version for macOS short version string in bundle

- SuperBuild/External_VTK.cmake
---
Revision: 3e45140d5ed4c38ff93bbfd4af033216f9fc820c
Author: Steve Pieper <pieper@isomics.com>
Date: 2023-10-10 1:58:01 PM
Message:
BUG: use alpha to calculate RGBA lighting (#43)
Implements the feature and fixes discussed in this thread: https://discourse.slicer.org/t/volume-rendering-colorized-with-segmentation/26689/6
Basically allows RGBA volumes to be shaded according to their alpha component so that something like a CT or microCT can define an rgb value at spatial regions, while getting opacity and gradient information from the alpha channel (e.g. the Hounsfield unit).
Also always uses the 0 channel for defining the lighting parameters. This part is WIP since it may be more appropriate to set the alpha channel lighting parameters in this scenario.  Currently, …
> BUG: Update VTK to fix RGBA volume rendering

- Utilities/Scripts/update_translations.py
SlicerIGT translation files were found by Slicer component. Translations were only extracted from CLI module XMLs for Slicer but not for other components.
> ENH: Make translation update script more robust

- Modules/Loadable/Segmentations/qSlicerSegmentationsSettingsPanel.cxx
There is no signal called setDefaultOverwriteMode in the qSlicerSigmentationSettingPanel.
Qt emits a warning during the Slicer execution process.
> BUG: Fix a typo in qSlicerSigmentationSettingsPanel signal/slot connection

- SuperBuild/External_VTK.cmake
Follow-up of Slicer/VTK@3e45140d5 (BUG: use alpha to calculate RGBA lighting)
introduced through 57b8434f4 (BUG: Update VTK to fix RGBA volume rendering).
It removes the use of regex leading to segfault in binary compiled using gcc 7.3.1 and introduces an ivar called lightingComponent set based on the value of "independentComponents"
See https://github.com/Slicer/Slicer/issues/7281
```
$ git shortlog 3e45140d5..97965bba9 --no-merges
BUG: Fix generation of volume rendering shader
```
References:
* https://discourse.slicer.org/t/vtk-multivolume-cinematic-volume-rendering/31981/44?u=jcfr
* https://github.com/Slicer/VTK/pull/45
> BUG: Update VTK to fix segfault when enabling volume rendering

- Modules/Scripted/SampleData/SampleData.py
Restore the passing of the following tests addressing regressions introduced in d3f49ed35 (BUG: Make more strings translatable) introduced through:
* https://github.com/Slicer/Slicer/pull/7243
Tests fixed:
* `py_Slicer4Minute`
* `py_ShaderProperties`
* `py_RSNA2012ProstateDemo`
* `py_VolumeRenderingSceneClose`
* `py_SubjectHierarchyGenericSelfTest`
* `py_SampleData`
* `py_SlicerRestoreSceneViewCrashIssue3445`
* `py_RSNAVisTutorial`
* `py_JRC2013Vis`
* `py_AtlasTests`
Tested on a local build generated on Ubuntu 20.04
> Fix SampleData module

- Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyGenericSelfTest.py
- The test assumed incorrect shown item count including the empty folder (which flag is enabled by default), expected item counts has been fixed
- Add test for the showEmptyHierarchyItems flag, which has not been tested until now
Re #7288
> BUG: Fix SubjectHierarchyGenericSelfTest

- Docs/developer_guide/modules/dicom.md
- Docs/developer_guide/script_repository/dicom.md
- Modules/Scripted/DICOMLib/DICOMProcesses.py
- Modules/Scripted/DICOMLib/DICOMSendDialog.py
- Modules/Scripted/DICOMLib/DICOMUtils.py
These changes aim to expose authentication parameters in Python utilities
to aid in DICOM networking while avoiding implementation-specific
changes to the Slicer user interface. Generic methods such as a
user/password combination, OAuth token, or other application-specific
token can now (theoretically) be used in DICOMweb utility methods.
- A username/password combination can be persisted as a global setting
with the `DICOMWEBUSER` and `DICOMWEBPWD` keys.
- A generic `requests.auth.AuthBase` object can be passed into Slicer
utility methods for use in retrieving and stowing DICOM objects.
- DICOMSender is refactored for clarity. The DICOMSender public interface is
limited to initialization and the `send` method. A DICOMweb
authentication parameter is exposed, otherwise no functional …
> ENH: Expose authentication parameters for DICOMweb networking

- Libs/vtkSegmentationCore/vtkBinaryLabelmapToClosedSurfaceConversionRule.cxx
- Libs/vtkSegmentationCore/vtkBinaryLabelmapToClosedSurfaceConversionRule.h
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationShow3DButton.cxx
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationShow3DButton.h
Provides users with the ability to enable 3D rendering of segmentations using the vtkSurfaceNets3D filter. This includes the option to apply built-in smoothing during surface generation.
To access this functionality, users can now select "Use Surface Nets (fast)" within the newly introduced "Experimental" menu found under the "Show 3D" button.
Furthermore, the menu now includes the "Use Surface Nets Smoothing (faster)" option to enable the vtkSurfaceNets3D filter's built-in smoothing functionality, implemented with `vtkConstrainedSmoothingFilter`.
Using the Surface Nets approach provide a more efficient alternative:
* With the currently used smoothing method, rendering is ~7x faster than using flying edges.
* With the built-in smoothing, rendering is ~16x faster than flying edges with the …
> Support 3D rendering of segmentation using Surface Nets

- Base/QTCore/qSlicerCoreApplication.cxx
This update ensures that any pending messages logged from Python scripts are properly reported and written to log files before the application exits.
This issue was uncovered while working on https://github.com/Slicer/Slicer/pull/7299
To illustrate:
* :white_check_mark: **With** explicit call to `slicer.app.processEvents()`:
```
rm /tmp/Slicer-jcfr/*.log && \
./Slicer --python-code "import logging; logging.debug('EXPECTED DEBUG OUTPUT'); slicer.app.processEvents()" \
--exit-after-startup 2>&1 > /dev/null && \
(echo "Slicer exited without error" && cat $(ls -1 /tmp/Slicer-jcfr/*.log) | grep "EXPECTED DEBUG OUTPUT")
[DEBUG][Python] 23.10.2023 17:35:16 [Python] (<string>:1) - EXPECTED DEBUG OUTPUT
```
* :x: **Without** explicit call to `slicer.app.processEvents()`:
```
rm …
```
> BUG: Ensure remaining application events are processed before exiting

- Modules/Scripted/DICOMLib/DICOMProcesses.py
Resolve `py_nomainwindow_DCMTKPrivateDictTest` failure caused by a regression introduced in commit adb997269 (`COMP: Refactor DICOMProcess and DICOMCommand`).
The issue stemmed from the refactoring commit, which guaranteed that the `start()` function of the base class was consistently invoked. This resulted in the connection of the "onStateChanged()" signal and the immediate reading of standard output and error.
Subsequently, any further calls to `self.process.readAllStandardOutput()` were returning an empty string. This fix restores the expected behavior.
_Command below executed on local build done on Ubuntu 20.04_
```
ctest -R "(py_nomainwindow_qSlicerDICOMModuleGenericTest|py_nomainwindow_qSlicerDICOMPatcherModuleGenericTest|py_DICOMPatcher|CreateDICOMSeriesTest|py_DICOMReaders|py_nomai …
```
> BUG: Ensure DICOMCommand.start() returns process output 

- CMakeLists.txt
- SuperBuild/External_tbb.cmake
Follow-up de4a89a1b4 (ENH: Support 3D rendering of segmentation using Surface Nets) integrated through PR-7224 and ensure similar performance increase an all platforms including Linux and macOS.
With TBB enabled:
- Flying Edges with Standard Smoothing is ~ x2 faster
- Surface Nets with Standard Smoothing is ~ x4 faster
- Surface Nets with Internal Smoothing is ~ x4 faster
Related pull requests and issues:
* https://github.com/Slicer/Slicer/pull/7224#issuecomment-1774327464
* https://github.com/Slicer/Slicer/pull/6405
* https://github.com/Slicer/Slicer/pull/6404
* https://github.com/Slicer/Slicer/pull/5965
* https://github.com/Slicer/Slicer/pull/5903
Before integrating, test build and packaging:
[^1]: https://github.com/Slicer/SlicerBuildEnvironment#docker-based-environments
> ENH: Enable TBB as default VTK SMP implementation on all platforms

- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/ModuleInfo.py
Python file detection plugin (that detects if Python files are drag-and-dropped to the application window) logged an error when MRML nodes were drag-and-dropped within the application.
> BUG: Fix error message when drag-and-dropping nodes

- SuperBuild.cmake
- SuperBuild/External_VTK.cmake
The updated VTK branch has been cleaned up to remove the update to `vtkImageLabelDilate3D` and backport changes already integrated in upstream VTK or being contributed through merge requests.
Instead of using the modified `vtkImageMedian3D` filter, the extension has been updated to use the `vtkImageLabelDilate3D` provided through the vtkAddon project.
The `vtkImageLabelDilate3D` is used when coloring a scalar volume using segmentation and we want to make sure that labels cover the underlying structure and a bit further (to color also the transition of the masked voxels).
For reference:
* integration of `vtkImageLabelDilate3D` into upstream VTK is discussed at https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10588
* updates originally introduced through 57b8434f4 (BUG: Update VTK to fix …
> ENH: Update VTK and vtkAddon for ColorizeVolume module in Sandbox extension

- SuperBuild.cmake
Follow-up of 1aeac28119 (ENH: Update VTK and vtkAddon for ColorizeVolume module in Sandbox extension)
List of vkAddon changes:
```
$ git shortlog 03f7dfdd3..960c2e3c8 --no-merges
COMP: Update vtkImageLabelDilate3D adding includes for used STL containers
```
> COMP: Update vtkAddon to fix vtkImageLabelDilate3D build on recent compiler

- SuperBuild/External_CTK.cmake
When deleting many patients (or studies or series) it can occur that the confirmation dialog that is created with all the deleted object names is taller than the screen height, so the buttons are cut off and not available.
This ensures that the said dialog cannot be higher than the DICOM browser.
```
$ git shortlog 5657c58a7..b9ef9b8a --no-merges
Csaba Pinter (1):
BUG: Make sure the delete DICOM object dialog is not too tall
```
> BUG: Update CTK to adjust the size of the delete DICOM object dialog

- SuperBuild/External_CTK.cmake
See https://github.com/commontk/CTK/compare/b9ef9b8aa...4888deb1d
```
$ git shortlog b9ef9b8aa..4888deb1d --no-merges
COMP: Fix CTK PluginFramework library build
COMP: Fix configuration without explicitly setting CTK_QT_VERSION
COMP: Fix CMake 3.26 warning in ctkLinkerAsNeededFlagCheck project
COMP: Add install rules for PluginFramework CMake modules
```
> COMP: Update CTK to include build-system fixes

- Libs/MRML/DisplayableManager/vtkMRMLAbstractDisplayableManager.cxx
- Libs/MRML/DisplayableManager/vtkMRMLAbstractDisplayableManager.h
The `InteractorStyleAbort` API was originally introduced in 8ded9a0bb (`ENH: eliminated conflict between crosshair navigation and window level`).
Then, it was superseded by the `InteractorAbort` API in 0b9b33983 (`BUG: #2629.  Window level controls conflicted with crosshair navigation`)
Ultimately, the last uses of either the `InteractorStyleAbort` or `InteractorAbort` API were removed in dc2c09580 (`ENH: Improved crosshair usability, added display in 3D view`)
> ENH: Remove unused API to set/get displayable manager interactor abort flags

- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.h
- Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
- Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.h
Following changes introduced in https://github.com/Slicer/Slicer/commit/abff04f36a7394b4378d7dd852989356ff8193a5 (`ENH: Reimplement volume rendering displayable manager`), the event handling mechanisms was restructured. As a result, the invocation of "UpdatePipelineTransforms()" within the "OnInteractorStyleEvent" function became obsolete.
Furthermore, note that the call to the "OnInteractorStyleEvent" function stopped working following the alterations made in https://github.com/Slicer/Slicer/commit/a0ad2a32824dee03c15182c00d71391b11dc80c2 (`ENH: Handle 3D events in MRML interactor style and markups VTK widgets`). This change removed the installation of the interactor style observer from "SetAndObserveInteractorStyle()".
Also removes empty …
> Remove obsolete OnInteractorStyleEvent

- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx
Instead of relying on the "CurrentRenderer" indirectly set by "vtkInteractorStyle::FindPokedRenderer", directly retrieve the render window from the interactor.
> ENH: Simplify vtkMRMLViewInteractorStyle::SetMouseCursor

- Libs/MRML/Widgets/qMRMLSliceView.cxx
- Libs/MRML/Widgets/qMRMLSliceView.h
- Libs/MRML/Widgets/qMRMLSliceView_p.h
- Libs/MRML/Widgets/qMRMLThreeDView.cxx
- Libs/MRML/Widgets/qMRMLThreeDView.h
- Libs/MRML/Widgets/qMRMLThreeDView_p.h
- SuperBuild/External_CTK.cmake
The CTK update adds protected constructor to `ctkVTKRenderView` and `ctkVTKSliceView` for associating a derived pimpl.
This is required to have the complete virtual function chain executed when virtual function are called in the `qMRMLThreeDViewPrivate::init()` or `qMRMLSliceViewPrivate::init()` function.
> ENH: Allow virtual func to be called during MRML(ThreeD|Slice)View pimpl init

- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx
- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.h
Follow-up of 364ff7b6d (`ENH: Use common interactor style for slice and 3D views`) in which these variables became obsolete.
> STYLE: Remove unused ivars from vtkMRMLViewInteractorStyle

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/AbstractScriptedSegmentEditorAutoCompleteEffect.py
- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorGrowFromSeedsEffect.py
Grow from seeds effect requires at least 2 visible segments as input if no editable region is specified, and at least 1 visible segment if editable region is specified. When the requirement was not fulfilled then the user did not know what was wrong, because there was no visible notification on the GUI (only in the application log), see for example https://discourse.slicer.org/t/grow-from-seeds-does-not-work-if-painting-only-one-segment/32452/6
This commit adds display of the error in a popup window if there are not enough input segments. A notification on the status bar is added if segmentation is canceled due to removal of an input segment.
> ENH: Make Grow from seeds effect input requirements more clear

- Modules/Scripted/DICOMLib/DICOMUtils.py
Would be great to have the progressbar option of `loadSeriesByUID` also for the higher level functions.
> ENH: Propagate args / kwargs to loadLoadables

- Modules/Scripted/DICOMLib/DICOMUtils.py
_Originally posted by @lassoan in https://github.com/Slicer/Slicer/pull/7270#pullrequestreview-1680877095_
> [...] I agree that it can be useful to expose `messages` and `progressCallback` arguments at higher-level functions, too. I would prefer to explicitly specify these arguments, as it would make the API more clear (and 2 extra arguments are not too many and I don't expect that `loadLoadables` will have many new options in the future).
cc: @marcus-wirtz-snkeos 
---
This pull request was created to include the changes originally included through this pull-requests:
* https://github.com/Slicer/Slicer/pull/7270
For the sake of having a clean history and considering the updated `main` branch has not been referenced externally, `main` was forced push to …
> ENH: Update DICOMUtils loadPatient API to handle messages and progressCallback

- .github/ISSUE_TEMPLATE/bug_report.md
Removed expected behavior section, as it is normally described in the "Steps to reproduce" section (what you did + what you expected to happen + what happened instead).
> DOC: Simplify bug report template

- .github/ISSUE_TEMPLATE/bug_report.md
Since the pull request updating the issue template was created and approved before 1886057da4 (ENH: Update pre-commit config to include "trailing-whitespace"), trailing whitespaces were inadvertently introduced.
* https://github.com/Slicer/Slicer/pull/7332
> STYLE: Trim trailing whitespaces in issue template

- Modules/Loadable/Models/qSlicerModelsReader.cxx
Option to read FreeSurfer files is not handled in Slicer core, and was exported to the SlicerFreeSurfer extension.
> ENH: Remove FreeSurfer file extensions from qSlicerModelsReader

- Modules/Scripted/DICOMLib/DICOMUtils.py
Before:
Images are not equally spaced (a difference of -0.476013 vs 1.90399 in spacings was detected).
After:
Image slices are not equally spaced (1.90399 spacing was expected, 1.42798 spacing was found between .../I6000001 and .../I6100000).
> ENH: Make DICOM variable spacing warning more informative

- .git-blame-ignore-revs
This adds recent formatting commits to the git blame ignore list.
For convenience, here is the list of commit added to the `.git-blame-ignore-revs` file. While reviewing this pull request, consider unchecking if any of these should be removed or commenting if I missed any.
> STYLE: Add recent formatting changes to ignored list for git blame

- Modules/Scripted/ExtensionWizard/ExtensionWizard.py
This commit addresses a regression introduced in 34651fbbb (`BUG: Fix error message when drag-and-dropping nodes`) through the following pull request:
* https://github.com/Slicer/Slicer/pull/7303
The problem stemmed from the `errorDisplay()` function, which expects the argument to be provided as `text, windowTitle=None, parent=None, standardButtons=None, **kwargs`.
Specifying `parent` as a keyword argument is then required to avoid the following error:
```
File "/path/to/Slicer-Release/Slicer-build/lib/Slicer-5.5/qt-scripted-modules/ExtensionWizard.py", line 518, in dropEvent
ExtensionWizardWidget.loadModules(modules=self.foundModules)
File "/path/to/Slicer-Release/Slicer-build/lib/Slicer-5.5/qt-scripted-modules/ExtensionWizard.py", line 407, in …
```
> BUG: Fix ExtensionWizard error message reporting when drag-and-dropping script

- Base/Logic/vtkSlicerScriptedLoadableModuleLogic.cxx
- Base/Logic/vtkSlicerScriptedLoadableModuleLogic.h
- Base/QTCore/qSlicerScriptedFileReader.cxx
- Base/QTCore/qSlicerScriptedFileReader.h
- Base/QTCore/qSlicerScriptedFileWriter.cxx
- Base/QTCore/qSlicerScriptedFileWriter.h
- Base/QTCore/qSlicerScriptedUtils.cxx
- Base/QTCore/qSlicerScriptedUtils_p.h
- Base/QTGUI/qSlicerScriptedFileDialog.cxx
- Base/QTGUI/qSlicerScriptedFileDialog.h
- Base/QTGUI/qSlicerScriptedLoadableModule.cxx
- Base/QTGUI/qSlicerScriptedLoadableModule.h
- Base/QTGUI/qSlicerScriptedLoadableModuleWidget.cxx
- Base/QTGUI/qSlicerScriptedLoadableModuleWidget.h
- Libs/MRML/DisplayableManager/vtkMRMLScriptedDisplayableManager.cxx
- Libs/MRML/DisplayableManager/vtkMRMLScriptedDisplayableManager.h
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedLabelEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedLabelEffect.h
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedPaintEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedPaintEffect.h
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyScriptedPlugin.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyScriptedPlugin.h
_Changes implemented following the comment of @pieper in https://github.com/Slicer/Slicer/pull/7351#discussion_r1383991595._
---
This more accurately conveys the variable's purpose, avoiding any ambiguity between "python code" and "python script".
* Improve `setPythonSource` API readability renaming parameter from `newPythonSource` to `filePath`
* Improve code readability renaming scripted class internal variable from `PythonSource` to `PythonSourceFilePath`
> Improve scripted classes readability renaming setPythonSource parameter and associated internal variable

- SuperBuild/External_python-extension-manager-ssl-requirements.cmake
Fix the error reported below ensuring "python-dateutil" dependency "six" is explicitly specified within its external project, ensuring it is not installed as side effect of an unrelated external project.
```
$ cat /path/to/python-extension-manager-ssl-requirements-install-err.log
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
six>=1.5 from https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from python-dateutil==2.8.2->-r /Users/svc-dashboard/D/P/A/python-extension-manager-ssl-requirements-requirements.txt (line 87))
WARNING: There was an error checking the latest version of pip.
```
> COMP: Fix parallel build error adding missing PyPI dependency for python-dateutil

- SuperBuild/External_python-dicom-requirements.cmake
- SuperBuild/External_python-ensurepip.cmake
- SuperBuild/External_python-extension-manager-requirements.cmake
- SuperBuild/External_python-extension-manager-ssl-requirements.cmake
- SuperBuild/External_python-numpy.cmake
- SuperBuild/External_python-pip.cmake
- SuperBuild/External_python-pythonqt-requirements.cmake
- SuperBuild/External_python-requests-requirements.cmake
- SuperBuild/External_python-scipy.cmake
- SuperBuild/External_python-setuptools.cmake
- SuperBuild/External_python-wheel.cmake
This commit addresses warnings related to description generation for Python external projects and fixes a regression introduced in commit f348d6f5b (COMP: Install python packages using PyPI wheels), which updated external projects to install wheels instead of installing packages from source.
It avoids the following warnings that occur when the function `ExternalProject_GenerateProjectDescription_Step` attempts to extract version and license information from an external project's source tree.
```
Generate version-python-pip.txt and license-python-pip.txt
No configure step for 'python-pip'
fatal: not a git repository (or any of the parent directories): .git
CMake Warning (dev) at /path/to/Slicer-Release/CMakeFiles/python-pip-generate-project-description.cmake:69 (message):
python-pip: Could …
```
> COMP: Fix description generation warnings for Python external projects

- Libs/MRML/Core/vtkMRMLSequenceNode.cxx
- Libs/MRML/Core/vtkMRMLSequenceNode.h
- Modules/Loadable/Sequences/Testing/Cxx/vtkMRMLSequenceNodeTest1.cxx
When SetDataNodeAtValue is called, the new data node is deep-copied into the internal sequence scene, and replaces the old node in the index list if one exists. The old node however is not removed from the scene, causing the number of nodes to grow larger every time SetDataNodeAtValue was called for a value with an existing data node.
Fixed by removing the old node from the scene if one already exists for the specified value. This commit also changes the node pointer in IndexEntryType to a vtkWeakPointer.
Fixes #7328
> BUG: Fix nodes not getting removed in vtkMRMLSequenceNode::SetDataNodeAtValue

- .github/workflows/update-slicer-certificate-bundle.yml
This commit applies a fix similar to c410ead7b (`COMP: Fix "ci" GitHub workflow removing deprecated use of "::set-output"`) to the "update-slicer-certificate-bundle" GitHub Actions workflow.
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> COMP: Update GitHub workflow to remove deprecated use of "::set-output"

- .readthedocs.yaml
When a command exits with code 183, Read the Docs will cancel the build immediately.
> COMP: Skip ReadTheDocs build for "hooks" branch

- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx
Issue is only visible in debug mode as `assert` is not in release build
In debug mode the assertion fails preventing slicer from starting up
> BUG: Fix crash for debug build due to invalid assert in MRMLViewInteractorStyle

- Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Following-up of f0b2690c3 (ENH: Add support for ctkDICOMDatabase tag precaching) where the original use of "__contains__" was introduced.
See https://docs.python.org/3/reference/expressions.html#in
> STYLE: Simplify list membership test in DICOMScalarVolumePlugin

- Docs/user_guide/modules/dicom.md
- Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
this PR adds:
- Grouping frames by orientation with a 10^-6 tolerance in examineFiles in DICOM module.
- Add harden transform option in the DICOM settings for load in DICOMScalarVolumePlugin.
> ENH: Support regularization transform hardening in DICOM Scalar plugin 

- .git-blame-ignore-revs
This commit includes historical style changes to be ignored by git blame. The adjustments cover various aspects such as changing indentation styles, addressing white space issues, and ensuring adherence to modern C++ and Python standards.
Notable C++ updates involve replacing (ITK|VTK)_OVERRIDE with 'override', substituting ITK_NULLPTR, 0, and NULL with 'nullptr', and using "= default" for trivial implementations.
-----
For convenience, here is the list of commit added to the `.git-blame-ignore-revs` file. While reviewing this pull request, consider unchecking the ones that should be removed.
> STYLE: Add historical formatting changes to git blame ignore list

- Base/QTGUI/Testing/Cxx/qSlicerMouseModeToolBarTest1.cxx
- Libs/MRML/Core/vtkMRMLPlotChartNode.cxx
To identify all location if a `break;` statement following `return;`, the entire codebase was inspected using a command like the following:
```
$ ack --ignore-dir=CLI  "break\;" -C2 | ack "return"
```
> STYLE: Remove unreachable "break" statement after "return" outside of "switch"

- Libs/MRML/DisplayableManager/vtkMRMLCameraDisplayableManager.cxx
Mark parameter as not used unconditionally.
Fixes:
```
Libs/MRML/DisplayableManager/vtkMRMLCameraDisplayableManager.cxx:
In member function
‘virtual void vtkMRMLCameraDisplayableManager::OnMRMLNodeModified(vtkMRMLNode*)’:
Libs/MRML/DisplayableManager/vtkMRMLCameraDisplayableManager.cxx:206:15:
warning: unused parameter ‘node’ [-Wunused-parameter]
206 |  vtkMRMLNode* node)
|  ~~~~~~~~~~~~~^~~~
```
raised when building 3D Slicer.
> COMP: Mark parameter as not used unconditionally

- Base/Python/slicer/parameterNodeWrapper/wrapper.py
Whenever a parameter node wrapper was instantiated, it attached a ModifiedEvent observer for each cached attribute in the node, however these observers were never removed.
This commit adds a RemoveObserver call to the `__del__ `method to ensure that the observer is removed when the wrapper object is deleted. This commit also ensures that the object can be deleted by using a weak reference in the AddObserver callback.
**Before:**
```
parameterNode.AddObserver(vtk.vtkCommand.ModifiedEvent, self._onModified)
```
Using this approach the python reference count is increased and kept by VTK for as long as the observer is attached to the self._onModified method.
**After**
````
_selfWeakRef = weakref.ref(self)
self._observerTag: int = parameterNode.AddObserver(vtk.vtkCommand.ModifiedEvent, lambda …
```
> BUG: Fix parameter node wrapper observers not being removed

- Docs/developer_guide/build_instructions/windows.md
This clarifies instructions describing how to use Qt universal installer.
> DOC: Clarify steps for installing Qt in windows build instructions

- .ruff.toml
- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/AbstractScriptedSegmentEditorAutoCompleteEffect.py
This commit rectifies the linter error concerning the `__del__` method in the AutoComplete segment editor effect. The specific issue was that the `__del__` method expects one parameter, but two were given. To resolve this, the call to the superclass `__del__` has been removed, as it is not implemented.
Note that while this correction resolves the immediate warning, there may still be issues with proper garbage collection for some effects.
A proposal to address the root cause is documented in:
* Slicer#7392
It also updates the Ruff configuration, re-enabling the PLE0302 rule to ensure that `__del__` functions are called with the expected number of parameters.
> BUG: Resolve del method override issue in AutoComplete segment editor effect

- .ruff.toml
- Base/Python/slicer/util.py
- Utilities/Scripts/SEMToMediaWiki.py
- Utilities/Scripts/SlicerWizard/ExtensionProject.py
- Utilities/Scripts/SlicerWizard/ExtensionWizard.py
- Utilities/Scripts/SlicerWizard/TemplateManager.py
- Utilities/Scripts/SlicerWizard/__init__.py
Fix scripts and update Ruff configuration checking if docstrings require raw string prefix
For reference:
> In Python, backslashes are typically used to escape characters in strings. In raw strings (those prefixed with an r), however, backslashes are treated as literal characters.
>
> PEP 257 recommends the use of raw strings (i.e., r"""raw triple double quotes""") for docstrings that include backslashes. The use of a raw string ensures that any backslashes are treated as literal characters, and not as escape sequences, which avoids confusion.
Copied from https://docs.astral.sh/ruff/rules/escape-sequence-in-docstring/
| Context | Illustration |
|--|--|
| Before| ![image](https://github.com/Slicer/Slicer/assets/219043/d698002d-bbf6-4ff2-98f9-b8b00c413537) | 
| …
> Docstring fix escape sequence issues

- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx
Replace GetNumberOfMarkups with GetNumberOfControlPoints. This prevents warning messages when using plane fit.
> BUG: Remove use of deprecated GetNumberOfMarkups in vtkMRMLMarkupsPlaneNode

- Docs/user_guide/modules/transforms.md
I saw this while reading some Transforms module documentation. Very minor, but I figured I would go ahead and contribute before I forget.
> DOC: Fix misspelling of transforms

- Base/QTApp/qSlicerApplicationHelper.txx
Workaround the reporting of -Wunused-function warnings when using
GCC <= 7.3 to build translation units not making use of the
"qSlicerApplicationHelper::postInitializeApplication" function.
This was verified with the following self-contained example
compiled using the "https://godbolt.org/" platform specifying the
-Wunused-function flag and toggling between "x86-64 gcc 7.3" and
"x86-64 gcc 7.4".
```
#include <iostream>
namespace
{
void setEnableQtTesting()
{
std::cout << "setEnableQtTesting" << std::endl;
}
} // end of anonymous namespace
template<typename SlicerMainWindowType>
void postInitializeApplication()
{
setEnableQtTesting();
}
int main(int, char*[])
{
std::cout << "Hello" << std::endl;
return 0;
}
```
Fixes:
```
In file included from …
```
> COMP: Fix reporting of -Wunused-function related to qSlicerApplicationHelper

- Libs/MRML/Widgets/Testing/qMRMLLayoutManagerTest1.cxx
This commit re-introduces the marking of "checkViewArrangement" as unused that was inadvertently removed as part of 3ce46788 (`ENH: Add check for available application updates`) and originally introduced in 53fea52c1 (`COMP: Fix -Wunused-function warnings in qMRMLLayoutManager tests`)
It fixes the following warning:
```
/path/to/Slicer/Libs/MRML/Widgets/Testing/qMRMLLayoutManagerTestHelper.cxx:13:6: warning: ‘bool {anonymous}::checkViewArrangement(int, qMRMLLayoutManager*, vtkMRMLLayoutNode*, int)’ defined but not used [-Wunused-function]
bool checkViewArrangement(int line, qMRMLLayoutManager* layoutManager,
^~~~~~~~~~~~~~~~~~~~
```
This warning may be reproduced using the following self-contained example compiled using the "https://godbolt.org/" platform specifying the …
> COMP: Fix -Wunused-function warning in qMRMLLayoutManagerTest1

- Base/Python/mrml.py
- Base/Python/slicer/__init__.py
- Base/Python/slicer/logic.py
- Base/Python/slicer/slicerqt.py
- Base/Python/vtkAddon.py
- Base/Python/vtkITK.py
- Base/Python/vtkSegmentationCore.py
- Base/Python/vtkTeem.py
This commit addresses an issue where the creation of VTK-based objects in script executed through the PythonSlicer executable was dependent on the order of module imports. The update ensures consistent and successful instantiation of associated objects, such as `vtkMRMLScene`, regardless of the import order.
For instance, the following code is now supported:
```py
import slicer
import vtk
object = slicer.vtkMRMLScene()
assert isinstance(object, vtk.vtkObject)
```
It doesn't require the developer to always import `vtk` before `slicer`.
The problem stemmed from the wrapping of MRML or Slicer VTK-based C++ classes through `vtkMacroKitPythonWrap` (from vtkAddon). The generated `vtk*PythonInitImpl.cxx` files do not include the names of dependent VTK modules in the list used with …
> BUG: Fix VTK-based object creation in PythonSlicer regardless of import order

- Docs/user_guide/modules/screencapture.md
- Modules/Scripted/ScreenCapture/ScreenCapture.py
Instead of having an obscure "single" button next to the "number of frames" selector, add a "none" animation mode and make it the default. Options that are not relevant are not just disabled but hidden, to make it easier for the user to find the relevant options.
| Before | After |
|--|--|
| ![image](https://github.com/Slicer/Slicer/assets/307929/34548d95-af41-40ba-a56b-efa82de30eb5) | ![image](https://github.com/Slicer/Slicer/assets/307929/bae4a8a6-950f-4199-aff7-6fca185ded26) |
> ENH: Simplify single-image capture in ScreenCapture module

- Modules/Loadable/Sequences/Logic/vtkSlicerSequencesLogic.cxx
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.h
- Modules/Loadable/Sequences/Testing/Cxx/CMakeLists.txt
- Modules/Loadable/Sequences/Testing/Cxx/vtkSlicerSequencesLogicTest1.cxx
It is now possible to represent non-existing items in a sequence as an empty node. It is also possible to enable saving of modifications while avoid creating missing items during sequence browsing.
Additional small fixes and improvements:
- added a test for Sequences module logic and added a few fixes in sequence node observations (so that proxy node is automatically updated if a sequence node is changed)
- added convenience API to browser node to allow selecting item by index value
- i18n: allow translation of sequence node name suffix
> ENH: Make sequence item creating strategy configurable

- Libs/MRML/Core/vtkMRMLCoreTestingMacros.h
Call `c_str()` to get `const char*` types for object property comparison tests.
Fixes:
```
Slicer/Libs/MRML/Core/Testing/vtkMRMLSceneViewNodeTest1.cxx:
In function ‘int vtkMRMLSceneViewNodeTest1(int, char**)’:
Slicer/Libs/MRML/Core/vtkMRMLCoreTestingMacros.h:328:62:
warning: ‘vtkStdString::operator const char*()’ is deprecated: Call `.c_str()` explicitly [-Wdeprecated-declarations]
const char * originalStringPointer = object->Get##variable(); \
```
and similar errors.
raised for example in:
https://github.com/Slicer/Slicer/actions/runs/6885650499/job/18730113110#step:4:3460
> COMP: Call c_str() to get const char* for property comparison tests

- Docs/developer_guide/script_repository/gui.md
- Libs/MRML/DisplayableManager/Testing/Cxx/vtkMRMLCameraDisplayableManagerTest1.cxx
- Libs/MRML/DisplayableManager/Testing/Cxx/vtkMRMLCameraWidgetTest1.cxx
- Libs/MRML/DisplayableManager/Testing/Cxx/vtkMRMLDisplayableManagerFactoriesTest1.cxx
- Libs/MRML/DisplayableManager/Testing/Cxx/vtkMRMLThreeDReformatDisplayableManagerTest1.cxx
- Libs/MRML/DisplayableManager/Testing/Cxx/vtkMRMLThreeDViewDisplayableManagerFactoryTest1.cxx
- Libs/MRML/DisplayableManager/vtkMRMLThreeDViewInteractorStyle.cxx
- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx
- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.h
- Libs/MRML/Widgets/qMRMLSliceView.cxx
- Libs/MRML/Widgets/qMRMLSliceView.h
- Libs/MRML/Widgets/qMRMLSliceView_p.h
- Libs/MRML/Widgets/qMRMLSliceWidget.cxx
- Libs/MRML/Widgets/qMRMLThreeDView.cxx
- Libs/MRML/Widgets/qMRMLThreeDView.h
- Libs/MRML/Widgets/qMRMLThreeDView_p.h
This pull request is aimed at streamlining the review process and testing by consolidating several independent changes, each of which will be contributed separately.
The primary focus for review in this pull request is the last commit, titled `ENH: Improve Event Delegation in qMRMLThreeDView and qMRMLSliceView`.
In this commit, we've refactored `vtkMRMLThreeDViewInteractorStyle` and `vtkMRMLSliceViewInteractorStyle` to inherit from `vtkObject` and have implemented event delegation to MRML displayable managers and their associated widgets by observing the interactor style.
This enhancement allows for the association of specialized interactor styles, such as `vtkOpenXRInteractorStyle` or `vtkOpenVRInteractorStyle`, with the render window while still maintaining MRML-specific event …
> Improve Event Delegation in qMRMLThreeDView and qMRMLSliceView

- Base/QTApp/qSlicerErrorReportDialog.cxx
Use `Qt::SkipEmptyParts` instead of deprecated `QString::SkipEmptyParts`
applying fix similar to 94f644676
Note that the version check test for Qt 5.14 because the Qt enum was effectively introduced in Qt 5.14. See https://github.com/qt/qtbase/commit/26a0db4b441a74cb65410635c3e8608a6360c793
Fixes:
```
slicer/Base/QTApp/qSlicerErrorReportDialog.cxx:84:44:
warning: ‘QStringList QString::split(const QString&, QString::SplitBehavior, Qt::CaseSensitivity) const’ is deprecated:
Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
84 |     QStringList stringList = fileName.split("_", QString::SkipEmptyParts);
|                              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sdks/qt/5.15.2/gcc_64/include/QtCore/qstring.h:609:17: note: declared here
609 |     QStringList …
```
> COMP: Use `Qt::SkipEmptyParts` instead of deprecated `QString::SkipEmptyParts`

- Libs/MRML/Core/Testing/vtkMRMLI18NTest1.cxx
Fix unused parameter warnings in `vtkMRMLI18NTest1.cxx`
Fixes:
```
/usr/src/Slicer/Libs/MRML/Core/Testing/vtkMRMLI18NTest1.cxx:
In member function ‘virtual std::string {anonymous}::vtkTestTranslator::Translate(const char*, const char*, const char*, int)’:
/usr/src/Slicer/Libs/MRML/Core/Testing/vtkMRMLI18NTest1.cxx:31:101:
warning: unused parameter ‘disambiguation’ [-Wunused-parameter]
std::string Translate(const char* context, const char* sourceText, const char* disambiguation = nullptr, int n = -1) override
^~~~~~~
/usr/src/Slicer/Libs/MRML/Core/Testing/vtkMRMLI18NTest1.cxx:31:119:
warning: unused parameter ‘n’ [-Wunused-parameter]
std::string Translate(const char* context, const char* sourceText, const char* disambiguation = nullptr, int n = -1) override
^
```
Raised for example at: …
> COMP: Fix unused parameter warnings in `vtkMRMLI18NTest1.cxx`

- Base/QTGUI/qSlicerStyle.cxx
Fixes:
```
slicer/Base/QTGUI/qSlicerStyle.cxx:
In member function ‘virtual QRect qSlicerStyle::subControlRect(QStyle::ComplexControl, const QStyleOptionComplex*, QStyle::SubControl, const QWidget*) const’:
slicer/Base/QTGUI/qSlicerStyle.cxx:180:11:
warning: this statement may fall through [-Wimplicit-fallthrough=]
180 |           }
|           ^
slicer/Base/QTGUI/qSlicerStyle.cxx:183:5: note: here
183 |     default:
|     ^~~~~~~
```
and
```
slicer/Base/QTGUI/qSlicerStyle.cxx:
In member function ‘virtual int qSlicerStyle::styleHint(QStyle::StyleHint, const QStyleOption*, const QWidget*, QStyleHintReturn*) const’:
slicer/Base/QTGUI/qSlicerStyle.cxx:287:7:
warning: this statement may fall through [-Wimplicit-fallthrough=]
287 |       if (widget && …
```
> COMP: Fix `-Wimplicit-fallthrough` warnings in qSlicerStyle

- Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationControlPointsStorageNode.cxx
- Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationLinesStorageNode.cxx
- Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationRulerStorageNode.cxx
Fix null pointer property query warnings.
Fixes:
```
slicer/Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationControlPointsStorageNode.cxx:
In member function ‘int vtkMRMLAnnotationControlPointsStorageNode::ReadAnnotation(vtkMRMLAnnotationControlPointsNode*)’:
slicer/Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationControlPointsStorageNode.cxx:241:83:
warning: ‘this’ pointer is null [-Wnonnull]
241 |       vtkErrorMacro("ReadAnnotation: unable to cast input node " << refNode->GetID() << " to a annotation node");
|                                                                     ~~~~~~~~~~~~~~^~
licer/Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationLinesStorageNode.cxx:
In member function ‘int vtkMRMLAnnotationLinesStorageNode::ReadAnnotation(vtkMRMLAnnotationLinesNode*)’: …
```
> COMP: Fix -Wnonnull warnings in MRML Annotation nodes

- Libs/MRML/Core/vtkMRMLCoreTestingMacros.h
This reverts commit e9772b1b1 (COMP: Call `c_str()` to get `const char*` for property comparison tests) introduced through https://github.com/Slicer/Slicer/pull/7411 originally intended to fix warnings like the following:
```
Slicer/Libs/MRML/Core/Testing/vtkMRMLSceneViewNodeTest1.cxx:
In function ‘int vtkMRMLSceneViewNodeTest1(int, char**)’:
Slicer/Libs/MRML/Core/vtkMRMLCoreTestingMacros.h:328:62:
warning: ‘vtkStdString::operator const char*()’ is deprecated: Call `.c_str()` explicitly [-Wdeprecated-declarations]
const char * originalStringPointer = object->Get##variable(); \
```
Initializing a std::string object with a null string is not valid.
cc: @jhlegarreta
> BUG: Revert invalid `-Wdeprecated-declarations` fix in TEST_SET_GET_STRING

- Libs/MRML/Core/vtkMRMLROIListNode.cxx
Fixes:
```
In function ‘char* strncpy(char*, const char*, size_t)’,
inlined from ‘virtual void vtkMRMLROIListNode::ReadXMLAttributes(const char**)’ at slicer/Libs/MRML/Core/vtkMRMLROIListNode.cxx:199:26:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output truncated before terminating nul copying 1 byte from a string of the same length [-Wstringop-truncation]
95 |   return __builtin___strncpy_chk (__dest, __src, __len,
|          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
96 |                                   __glibc_objsize (__dest));
|                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
```
raised when compiling on an Ubuntu 22.04 machine with gcc-11.
> COMP: Fix `-Wstringop-truncation` GCC warning in vtkMRMLROIListNode 

- Base/Python/slicer/util.py
- Base/QTGUI/qSlicerScriptedLoadableModuleWidget.cxx
- Base/QTGUI/qSlicerScriptedLoadableModuleWidget.h
When a scripted loadable module was reloaded using slicer.util.reloadScriptedModule, pythonSource was not changed in qSlicerScriptedLoadableModuleWidget. As a result, the previous enter/exit methods continued to be used by the scripted module.
Fixed by making setPythonSource accessible in Python, and using it to instantiate the new widget object.
Fix #7211
> BUG: Fix incorrect enter/exit called after scripted module reload

- SuperBuild/External_SimpleITK.cmake
```
$ git shortlog 1c0cf5de..v2.2.1 --no-merges
Bradley Lowekamp (17):
Fix numpy character dtype conversion warning
Update ITK Superbuild version
UpdateLabelOverlapMeasures with ITK 5.3 changes
Use ITK GTest already defined
Use system python executable
Update AZP Mac package utility python version to 3.9
Fix GHA trigger for Package workflows
Preserve SWIG PCRE file timestamps
CircleCI install "file" executable depedency
Correct DOWNLOAD_EXTRACT_TIMESTAMP value
Update ITK to 5.3.0 tagged release
Fix CircleCI Python 3.8 build
Update actions to fix warning
Make Image valid after move
Add testing for valid image after move
Adding cp311 to GHA Package workflow
Update version to 2.2.1
```
> ENH: Update SimpleITK from 2.2.0rc2 to 2.2.1 to support TotalSegmentator v2

- Docs/user_guide/modules/endoscopy.md
- Modules/Scripted/Endoscopy/Endoscopy.py
The Endoscopy module currently supports a fly though, where the user can specify points on a path, and the module interpolates the points with splines and _computes_ a camera orientation at each point of interpolation.
The goal with this pull request is to allow the user to _specify_ a camera orientation (and possibly a camera translation too) at specified points.  These user-specified transformations will be interpolated to the same set of points on a spline so that the fly though will use the user-specified transformations (and their interpolations) instead of the currently implemented, module-computed orientations.
> ENH: Endoscopy fly through with user's camera transforms

- Modules/Scripted/Endoscopy/Endoscopy.py
This is a follow-up of commit 717fd6f2b (ENH: Add support for managing orientation keyframe in Endoscopy) introduced through https://github.com/Slicer/Slicer/pull/7165
The set of commits aims to simplify the Endoscopy API (removing <s>~60</s> ~30 lines):
- Simplifies math helper functions API supporting only "return by value": Supporting both "return by value" and "pass mutable object as argument" API is error-prone.
- Removes unnecessary wrapping of relative orientation functions.
- Directly utilizes `vtkMRMLMarkupsNode::SetNthControlPointOrientation`.
- <s>Directly employs VTK's math functions for converting between matrices and quaternions.</s>
- <s>Streamlines interpolation by eliminating unnecessary functions: `orientationToQuaternion` and `quaternionToOrientation` are converting …
> Simplify Endoscopy API relelated to quaternion

- Base/Python/slicer/util.py
- Base/QTGUI/qSlicerApplication.cxx
- Modules/Scripted/DICOMLib/DICOMUtils.py
- Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMExportDialog.cxx
qt.QDateTime().currentDateTime().toString(...) may use Arabic numerals on an operating system set to Arabic language. Always specify en-US locale when using when using date in file/folder names to avoid having to work with paths that may contain unicode characters.
Fixes problem originally reported at:
https://discourse.slicer.org/t/i-tried-everything-to-run-totalsegmentator-pls-help/33023/3
> BUG: Fix temporary folder containing special characters

- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
- Modules/Loadable/Sequences/Testing/CMakeLists.txt
- Modules/Loadable/Sequences/Testing/Python/CMakeLists.txt
- Modules/Loadable/Sequences/Testing/Python/SequencesSelfTest.py
When a sequence was saved into a scene and then that scene was loaded then browsing did not work. The problem was caused by a typo that set missingItemMode to invalid and thereby disabling copying of sequence content into the proxy node.
Fixed the typo, made setting of missingItemMode more robust (if invalid string is found then the mode is not changed just a warning is logged), and added automated tests to capture similar errors in the future.
fixes #7440
> BUG: Fix loading of sequence nodes

- Base/QTCore/qSlicerLoadableModuleFactory.cxx
- Base/QTGUI/qSlicerLoadableModule.cxx
- Base/QTGUI/qSlicerScriptedLoadableModule.cxx
- Base/QTGUI/qSlicerScriptedLoadableModuleFactory.cxx
- Modules/Scripted/Endoscopy/Endoscopy.py
1. Fixes Endoscopy module dependency by adding "Markups"
2. Ensure scripted modules can always import wrapped C++ classes even if loading of loadable module is disabled. It fixes the tests `py_nowarning_[no]mainwindow_[nocli_]noloadableTest`.
3. De-duplicate code in loadable module factory by reusing qSlicerScriptedUtils.
> Fix scripted loadable module importing wrapped classes

- Base/QTCore/qSlicerCoreApplication.cxx
Fix a regression introduced in db1d60134 (`BUG: Enable language translation in MRML classes`) through https://github.com/Slicer/Slicer/pull/7210 ensuring the `vtkQtTranslator` instance is deleted in `quickExit()`.
> BUG: Fix vtkQtTranslator leak on quick exit

- SuperBuild/External_python-pip.cmake
This commit addresses the quarterly update cycle of python packages bundled into Slicer. To mitigate unnecessary console clutter caused by the pip version check, the variable `PIP_DISABLE_PIP_VERSION_CHECK` is set, suppressing warnings such as:
```bash
$ PythonSlicer -m pip list
[...]
[notice] A new release of pip is available: X.Y.Z -> Z'.Y'.Z'
[notice] To update, run: pip install --upgrade pip
```
To ensure that `the PIP_DISABLE_PIP_VERSION_CHECK` environment variable is undefined when Slicer is built against a system or external Python installation, this variable is set only in the pip external project.
This also addresses an issue introduced in 028fb31 (COMP: Update python packages to latest) where the pip version was updated from `23.1.2` to `23.3`. This resulted in the following …
> ENH: Disable pip version check

- Docs/user_guide/modules/endoscopy.md
- Modules/Scripted/Endoscopy/Endoscopy.py
Selecting the curve is now sufficient to work with the associated flythrough path. Also listen to the more specific `PointEndInteractionEvent` to only update the curve after user is done updating the curve.
Instantiate one EndoscopyLogic and simplify its API 
... introducing:
* `updateCameraFromOrientationAtIndex()`
* `getNumberOfControlPoints()`
* `saveOrientationAtIndex()`
* `removeOrientationAtIndex()`
* `createTransformFromInputCurve()` / `getTransformFromInputCurve()` / `setInputCurveTransform()`
* `createCursorFromInputCurve()` / `getCursorFromInputCurve()` / `setInputCurveCursor()`
... renaming:
* `setControlPoints` to `setControlPointsByResamplingAndInterpolationFromInputCurve`
* `interpolateOrientations` to `interpolateOrientationsForControlPoints`
* `loadCameraOrientations()` to …
> Streamline Endoscopy UX removing "Use this curve" button

- Base/QTApp/qSlicerApplicationHelper.txx
- Base/QTCore/qSlicerAbstractModuleFactoryManager.cxx
- Base/QTCore/qSlicerAbstractModuleFactoryManager.h
Module instantiation may take a long time if a module inappropriately performs lengthy operations in its main scope (e.g., pip_install or large import). It has been difficult to determine which modules misbehaved, because the splashscreen only showed the message "Instantiating modules..." but not individual module names.
This commit makes the name of the module that is being instantiated visible in the splashscreen. This way it becomes very clear which module takes disproportionately long time to instantiate.
> ENH: Display instantiated module name in splashscreen

- Base/Python/slicer/__init__.py
The GPA and QuickAlign modules in the SlicerMorph extension were causing the Slicer application to hang during module instantiation on Windows 11. This issue mirrors the previous errors encountered during the import of `numpy` and `scipy`, both of which were addressed in commits 542f53c5b and ad5d20d1a, respectively.
This commit adds `scipy.linalg` to the list of pre-imported packages, preventing the hang during the application start.
> BUG: Workaround for Slicer hang on scipy.linalg import on Windows 11

- SuperBuild/External_VTK.cmake
This addresses a crash related to the static initialization order 'fiasco' in `vtkSMPToolsAPI`. It ensures proper deletion of the `vtkSMPToolsAPI` singleton once the last translation unit referencing it has been unloaded.
This update ensures that the SMP backend is cleaned up at the appropriate time, fixing the following macOS tests that started to fail following commit 28dca75dc (ENH: Enable TBB as the default VTK SMP implementation on all platforms):
* `py_nomainwindow_SegmentationWidgetsTest1`
* `py_sceneImport2428`
* `py_SegmentStatistics`
* `py_UtilTest`
```
$ git shortlog  4bfb0f049a..d1727b8ce6 --no-merges Jean-Christophe Fillion-Robin (2):
[Backport MR-10751] BUG: Resolve crash by fixing vtkSMPToolsAPI static initialization order issue
[Backport MR-10751] ENH: …
```
> BUG: Update VTK to to fix vtkSMPToolsAPI static initialization order issue

- .github/actions/slicer-build/Dockerfile
- .github/workflows/ci.yml
* Update slicer-build GitHub action to use `5.6` docker image
* Update CI GitHub workflow to test `5.6` branch instead of `main`
The `slicer-base` image was manually tagged and published on the `metroplex` factory using the following commands:
```
docker tag slicer/slicer-base:latest slicer/slicer-base:5.6
docker push slicer/slicer-base:5.6
```
Since it is based on the `latest` version, it includes external project specific changes associated with this pull-request:
* https://github.com/Slicer/Slicer/pull/7451
* https://github.com/Slicer/Slicer/pull/7453
> [5.6] Update GitHub CI workflow to be release specific

- SuperBuild/External_VTK.cmake
* https://github.com/Slicer/Slicer/pull/7453
----------
This addresses a crash related to the static initialization order 'fiasco' in vtkSMPToolsAPI. It ensures proper deletion of the vtkSMPToolsAPI singleton once the last translation unit referencing it has been unloaded.
It also ensures backend-specific statics are properly initialized. when the first translation unit is loaded.
This update ensures that the SMP backend is cleaned up at the appropriate time, fixing the following macOS tests that started to fail following commit 28dca75dc (ENH: Enable TBB as the default VTK SMP implementation on all platforms):
* `py_nomainwindow_SegmentationWidgetsTest1`
* `py_sceneImport2428`
* `py_SegmentStatistics` …
> [5.6] BUG: Update VTK to to fix vtkSMPToolsAPI static initialization order issue

- SuperBuild/External_python-pip.cmake
* https://github.com/Slicer/Slicer/pull/7451
---------------
This commit addresses the quarterly update cycle of python packages bundled into Slicer. To mitigate unnecessary console clutter caused by the pip version check, the variable `PIP_DISABLE_PIP_VERSION_CHECK` is set, suppressing warnings such as:
```bash
$ PythonSlicer -m pip list
[...]
[notice] A new release of pip is available: X.Y.Z -> Z'.Y'.Z'
[notice] To update, run: pip install --upgrade pip
```
To ensure that `the PIP_DISABLE_PIP_VERSION_CHECK` environment variable is undefined when Slicer is built against a system or external Python installation, this variable is set only in the pip external project.
This also addresses an issue …
> [5.6] ENH: Disable pip version check

- Docs/developer_guide/mrml_overview.md
- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx
- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.h
* https://github.com/Slicer/Slicer/pull/7442
> [5.6] BUG: Restore maximization of view on double click event

- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
- Modules/Loadable/Sequences/Testing/CMakeLists.txt
- Modules/Loadable/Sequences/Testing/Python/CMakeLists.txt
- Modules/Loadable/Sequences/Testing/Python/SequencesSelfTest.py
* https://github.com/Slicer/Slicer/pull/7441
-----
When a sequence was saved into a scene and then that scene was loaded then browsing did not work. The problem was caused by a typo that set missingItemMode to invalid and thereby disabling copying of sequence content into the proxy node.
Fixed the typo, made setting of missingItemMode more robust (if invalid string is found then the mode is not changed just a warning is logged), and added automated tests to capture similar errors in the future.
fixes #7440
(cherry picked from commit 140d58aa18a4c293634a5cbfafd121254fc9e7f9)
> [5.6] BUG: Fix loading of sequence nodes

- Docs/user_guide/modules/endoscopy.md
- Modules/Scripted/Endoscopy/Endoscopy.py
- https://github.com/Slicer/Slicer/pull/7435
- https://github.com/Slicer/Slicer/pull/7431
- https://github.com/Slicer/Slicer/pull/7433
- https://github.com/Slicer/Slicer/pull/7436
- https://github.com/Slicer/Slicer/pull/7437
- https://github.com/Slicer/Slicer/pull/7439
Verified that the `Endoscopy.py` file associated with the `5.6` branch includes all changes from the one of the `main` branch (as of https://github.com/Slicer/Slicer/commit/7bd7cd0f596a73dce4201d05cb6aa9836f5b51bd) expect the one introduced through https://github.com/Slicer/Slicer/pull/7446
> [5.6] Streamline Endoscopy UX removing "Use this curve" button

- Base/QTCore/qSlicerCoreApplication.cxx
* https://github.com/Slicer/Slicer/pull/7447
-----------
Fix a regression introduced in db1d60134 (BUG: Enable language translation in MRML classes) ensuring the vtkQtTranslator instance is deleted in quickExit
(cherry picked from commit 3f0e381b67893e957ef7854c7642af0c19f12032)
> [5.6] BUG: Fix vtkQtTranslator leak on quick exit

- Base/QTCore/qSlicerLoadableModuleFactory.cxx
- Base/QTGUI/qSlicerLoadableModule.cxx
- Base/QTGUI/qSlicerScriptedLoadableModule.cxx
- Base/QTGUI/qSlicerScriptedLoadableModuleFactory.cxx
- Modules/Scripted/Endoscopy/Endoscopy.py
* https://github.com/Slicer/Slicer/pull/7446
> [5.6] Fix scripted loadable module importing wrapped classes

- Base/Python/slicer/util.py
- Base/QTGUI/qSlicerApplication.cxx
- Modules/Scripted/DICOMLib/DICOMUtils.py
- Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMExportDialog.cxx
* https://github.com/Slicer/Slicer/pull/7430
---------
qt.QDateTime().currentDateTime().toString(...) may use Arabic numerals on an operating system set to Arabic language. Always specify en-US locale when using when using date in file/folder names to avoid having to work with paths that may contain unicode characters (such paths may cause problems on certain file systems and it may not be always possible to pass them as command-line arguments).
Fixes problem originally reported at:
https://discourse.slicer.org/t/i-tried-everything-to-run-totalsegmentator-pls-help/33023/3
(cherry picked from commit eccb98ce1f58b19d0a429981cc8e3cf131bcf3d5)
> [5.6] BUG: Fix temporary folder containing special characters

- Base/QTGUI/qSlicerApplication.cxx
- Libs/MRML/Core/vtkMRMLTableNode.cxx
- Libs/MRML/Core/vtkMRMLTableNode.h
- Libs/MRML/Core/vtkMRMLTableStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTableStorageNode.h
- Libs/MRML/Widgets/qMRMLTableModel.cxx
- Libs/MRML/Widgets/qMRMLTableView.cxx
- Libs/MRML/Widgets/qMRMLTableViewControllerWidget.cxx
- Modules/Loadable/Plots/qSlicerPlotsModuleWidget.cxx
- Modules/Loadable/Tables/Testing/Python/TablesSelfTest.py
- Modules/Loadable/Tables/Widgets/Resources/UI/qSlicerTableColumnPropertiesWidget.ui
- Modules/Loadable/Tables/Widgets/Testing/Cxx/qSlicerTableColumnPropertiesWidgetTest1.cxx
- Modules/Loadable/Tables/Widgets/qSlicerTableColumnPropertiesWidget.cxx
- Modules/Loadable/Tables/qSlicerTablesModule.cxx
- Modules/Loadable/Tables/qSlicerTablesModuleWidget.cxx
- Modules/Scripted/SegmentStatistics/SegmentStatistics.py
- Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/ClosedSurfaceSegmentStatisticsPlugin.py
- Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/LabelmapSegmentStatisticsPlugin.py
- Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/ScalarVolumeSegmentStatisticsPlugin.py
- Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/SegmentStatisticsPluginBase.py
* https://github.com/Slicer/Slicer/pull/7283
> [5.6] ENH: Make Tables module translatable (SlicerLanguagePacks#12)

- Base/Python/slicer/__init__.py
* https://github.com/Slicer/Slicer/pull/7455
----
The GPA and QuickAlign modules in the SlicerMorph extension were causing the Slicer application to hang during module instantiation on Windows 11. This issue mirrors the previous errors encountered during the import of numpy and scipy, both of which were addressed in commits 542f53c5b and ad5d20d1a, respectively.
This commit adds scipy.linalg to the list of pre-imported packages, preventing the hang during the application start.
(cherry picked from commit d22925b4f3d33fbf55a605fd7d093818c4cee8ed)
> [5/6] BUG: Workaround for Slicer hang on scipy.linalg import on Windows 11 (#7455)

- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.h
- Modules/Loadable/Sequences/Testing/Cxx/vtkMRMLSequenceBrowserNodeTest1.cxx
- Modules/Loadable/Sequences/Testing/Python/SequencesSelfTest.py
- Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserSeekWidget.cxx
Two small fixes in keeping selected item number in sequence browser valid when browsing/adding/deleting items in the master sequence node.
These are not critical fixes, not required to be included in 5.6.1 patch release.
> Ensure selected item number in Sequence browser remains valid

- SuperBuild/External_CTK.cmake
The `ctkDICOMDatabase` update allows handling DICOM files with both file paths and URLs. The SQLite database schema now includes a `URL` field. Entries in the `Images` table can have a `URL`, a `fileName`, or both. The schema version is updated from `0.7.0` to `0.8.0`.
The `ctkDICOMTagCache` is also improved to store tags as uppercase hex, ensuring consistency and optimizing storage and performance.
For more details, refer to https://github.com/commontk/CTK/pull/1154
```
$ git shortlog f53820a4e..841877133 --no-merges 
Steve Pieper (1):
ENH: Update DICOM Database with URL Support and Tag Cache Optimization
```
> ENH: Update CTK DICOM Database version from 0.7.0 to 0.8.0

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorSmoothingEffect.py
When "Apply to visible segments" option was enabled in Segment Editor's Smoothing effect, then the processing failed with an error. The problem was that the string formatting was reworked for i18n and the named placeholder was not specified in the format function.
fixes #7482
> BUG: Fix smoothing effect for all visible segments

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorMaskVolumeEffect.py
Fix regression introduced in 238eeb1f6 (`ENH: Add node reference convenience functions to segment editor effects`)
> BUG: Fix Mask volume effect node selector

- Extensions/CMake/SlicerBlockAdditionalLauncherSettings.cmake
This commit addresses two issues:
The use of the `string(REPLACE ...)` command introduced in commits e9f28d6c8  and b1efab8a6 led caused input variable representing a list to be concatenated as a single string. This commit addresses this by transitioning to the `TRANSFORM` action allowing to replace values individually within a list.
Also addresses the missing replacement of `<CMAKE_CFG_INTDIR>` associated with the `PYTHONPATH_LAUNCHER_BUILD` settings.
| Before & After |
|---|
| ![image](https://github.com/Slicer/Slicer/assets/219043/f844319a-b5b9-4aba-a88e-4422198d915e) |
Fixes the regular expression used for replacing `$(Configuration)` with `${CMAKE_CFG_INTDIR}` so that the placeholder variable is ultimately replaced through the execution of the custom command associated with the …
> COMP: Fix generation of additional launcher settings for list-based settings

- Extensions/CMake/SlicerBlockAdditionalLauncherSettings.cmake
This commit ensures that the custom command responsible for generating `AdditionalLauncherSettings.ini` is rerun whenever the project is re-configured with different options. This is important to account for changes in the set of paths associated with the launcher settings.
> COMP: Re-generate additional launcher settings if settings are updated

- Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
- Modules/Scripted/ImportItkSnapLabel/ImportItkSnapLabel.py
Fixes regressions introduced in the these commits
- 60c659f33 (`ENH: Add transformation step before strings extraction`) for `DICOMScalarVolumePlugin`
- d3f49ed35 (`BUG: Make more strings translatable`) for `ImportItkSnapLabel`
> BUG: Fix error string format in `DICOMScalarVolumePlugin` and `ImportItkSnapLabel`

- SuperBuild/External_VTK.cmake
This includes a workaround to recognize OpenVR gesture where buttons are pressed consecutively.
Corresponding changes have been contributed to upstream VTK as [MR-10771][1] and [MR-10778][2]
[1]: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10771
[2]: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10778
```
$ git shortlog d5d688b47..08161371c2 --no-merges
[Backport MR-10771] BUG: Add missing Elevation3DEvent to vtkCommand::EventHasData()
[Backport MR-10778] BUG: Recognize OpenVR gesture where buttons are pressed consecutively
```
> BUG: Update VTK backporting fix for OpenVR gesture recognition

- SuperBuild/External_VTK.cmake
Fixes a regression introduced through commit
Slicer/VTK@b4fa8ba5d2 (`[Backport] ReadPixels: Check for errors only when VTK is configured to report errors`)
```
$ git shortlog 08161371c..c69cf77a6 --no-merges
Jaswant Panchumarti (1):
OpenGL2: Use #ifdef instead of #if to fix compiler error
```
> COMP: Update VTK to fix preprocessor expression in vtkOpenGLRenderWindow

- SuperBuild/External_VTK.cmake
This addresses proper rendering, particularly by `vtkOpenGLGPUVolumeRaycastMapper`, when the head-mounted display (HMD) is positioned inside the volume. The issue is resolved by ensuring correct computation of the plane frustum when the camera is tracking the HMD and is positioned inside the volume.
The changes listed below impact the following VTK modules:
* `Rendering/VR`
* `Rendering/OpenVR`
* `Rendering/OpenXR`
Fixes:
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/125
For more details:
* https://github.com/Slicer/VTK/pull/48
* [VTK issue 19123](https://gitlab.kitware.com/vtk/vtk/-/issues/19123): `OpenXR: Fix near plane clipping with camera inside volume`
* [VTK merge request #10783](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10783): `VR: Accommodate separate …
> BUG: Update VTK backporting OpenVR rendering fix when HMD inside the volume

- SuperBuild/External_VTK.cmake
This follows up on commit a0d5883544 ([Backport MR-10783] VR: Deprecate vtkVRRenderWindow::TrackHMD) adding missing deprecation macro required to successfully build. 
Related:
* https://github.com/Slicer/Slicer/pull/7507
```
$ git shortlog 7767cabe4..573f18292 --no-merges
willdunklin (1):
[Backport] vtkDeprecation: add VTK_DEPRECATED_IN_9_4_0 macro
```
> COMP: Update VTK backporting deprecation macro update

- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.h
This commit updates the documentation based on the updated behavior introduced in 1cc3b2c62 (`ENH: Improve Event Delegation in qMRMLThreeDView and qMRMLSliceView`)
> DOC: Improve docstring of vtkMRMLViewInteractorStyle processing functions

- Libs/MRML/DisplayableManager/vtkMRMLSliceViewInteractorStyle.cxx
- Libs/MRML/DisplayableManager/vtkMRMLThreeDViewInteractorStyle.cxx
- Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx
Within the `DelegateInteractionEventToDisplayableManagers` function:
- Introduce a check for `pokedRenderer`, mirroring the one initially incorporated in `vtkMRMLThreeDViewInteractorStyle` via commit 364ff7b6d (ENH: Use common interactor style for slice and 3D views).
- Introduce (or relocate) a check for `inputEventData` at the beginning of the `Delegate` function for consistency with the update to `vtkMRMLSliceViewInteractorStyle` in commit 731be146e (BUG: Fix crash when creating and showing qMRMLSliceWidget using Python). This adjustment also prevents the invocation of `FindPokedRenderer` when there is no `inputEventData`.
> ENH: Improve handling of invalid input in MRMLViewInteractorStyle classes

- SuperBuild/External_VTK.cmake
Updates VTK to support the integration of multiple runtime into the SlicerVirtualReality extension.
The following merge requests, including the backported commits referenced below, have been submitted to upstream VTK for reference
* `VR: Update interactor style API adding GetMappedAction()`.
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10784
* `VR: Declare AddAction() functions as virtual`.
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10785
* `VR: Update vtkVRRenderWindowInteractor marking ComplexGesture recognition functions as public`.
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10786
* `VR: Add SetInteractionState() API to VR interactor style`.
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10789
```
$ git shortlog …
```
> ENH: Update VTK to backporting VR, OpenVR and OpenXR improvements

- SuperBuild/External_VTK.cmake
Updates VTK to support integration of the OpenXR runtime into the SlicerVirtualReality extension.
The following merge requests, including the backported commits referenced below, have been submitted to upstream VTK for reference
* `VR: Declare AddAction() functions as virtual` See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10785
* `VR: Resolve "Not rendered" warnings after XR RenderWindow Initialization` See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10794
Additionally this commit also adds the OpenXR bindings for the oculus touch controller copied from kitware/paraview@ec4111e7c. See `Plugins/XRInterface/Plugin/pv_openxr_binding_oculus_touch_controller.json`.
```
$ git shortlog 2f050efc8..b9aae674d --no-merges
Jean-Christophe Fillion-Robin (5): …
```
> ENH: Update VTK backporting VR and OpenXR improvements

- Libs/MRML/Logic/vtkMRMLSliceLayerLogic.cxx
Follow-up to #4982. 32-bit integer data types can fit losslessly into the 53-bit mantissa of a 64-bit `double`, and this fix has been working fine for us for the last few months.
> BUG: Allow reslicing of 32-bit integer images

- Base/QTGUI/qSlicerModulesMenu.cxx
In one of the language translations, "Segmentation" module category name was translated with the same word as "Segmentations" module name, which caused Slicer to crash. Added a check to log a warning if such name conflict occurs and put the module in the top-level category.
fixes #7523
> BUG: Fix crash when module category name matches a module name

- Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx
In private implementation class, the public class's `tr` method must be used for translation (to avoid the private class name show up as translation context).
> BUG: Fix translation in qMRMLThreeDViewControllerWidget

- SuperBuild/External_VTK.cmake
Updates VTK to support finding OpenXR-SDK using the `OpenXRConfig.cmake` file provided in the OpenXR-SDK project itself.
```
$ git shortlog b9aae674d..211f2b71a --no-merges
Sankhesh Jhaveri (1):
[Backport MR-10792] OpenXR: Use the OpenXRConfig.cmake files provided by OpenXR-SDK
Software Solution Team (1):
[Backport] improve FindOpenXR.cmake for windows platform
```
> ENH: Update VTK backporting OpenXR-SDK improvements to streamline integration

- SuperBuild/External_VTK.cmake
This will allow to build SlicerVirtualReality extension against the latest version of `Microsoft.Holographic.Remoting.OpenXr` matching the version of the "Holographic Remoting Player" directly available in the Microsoft store.
```
$ git shortlog 211f2b71a..a7235af9d --no-merges
[Backport MR-10814] OpenXRRemoting: Support building against Holographic.Remoting.OpenXr >= 2.9.3
```
> ENH: Update VTK backporting support for Holographic.Remoting.OpenXr >= 2.9.3

- CMake/SlicerExtensionCPackBundleFixup.cmake.in
This updates Slicer extension fix-up rules adapting a similar fix done for Slicer core in 0b1560371 (`COMP: Fix macOS package setting "path" in VTK9 python modules fixup rules`)
> COMP: Fix macOS extension packaging updating VTK9 python modules fixup rules

- CMake/UseSlicer.cmake.in
- CMakeLists.txt
Follow-up of 52b238d0ec (`COMP: Ensure full path ID for macOS libraries installed for fix-up`) reverting the systematic clearing of `CMAKE_INSTALL_NAME_TOOL`.
Due to the possibility of external projects (e.g., LibFFI) enabling languages (e.g., ASM) that necessitate `install_name_tool` via the "CMakeFindBinUtils" module, we opt to clear `CMAKE_INSTALL_NAME_TOOL` on a per-project basis.
Related:
* https://github.com/Slicer/Slicer/pull/7537
> COMP: Prefer clearing CMAKE_INSTALL_NAME_TOOL on a per-project basis

- SuperBuild/External_CTK.cmake
This updates removes Python 2.x support, streamline test execution setting launch environment and fixes tests while addressing minor issues.
Highlights:
* Convert `ctkDoubleRangeSlider::setRange` to a slot to expose to Python
* Fix `applySettings()` to emit `settingChanged()` only if needed
* Fix segfault in `ctkFileDialog::selectionMode()` with native dialogs
```
$ git shortlog 841877133..b83ff7a54 --group=author --group=trailer:co-authored-by --no-merges
BUG: Fix connection with "dicomserver.co.uk" server using port 104 as default
Davide Punzo (4):
BUG: Fix connection with "dicomserver.co.uk" server using port 104 as default
BUG: Fix segfault in ctkDICOMAppWidget support use of native file dialog
BUG: Fix support of interactive mode in …
```
> ENH: Update CTK

- SuperBuild/External_CTK.cmake
This updates adds the signals `patientRemoved(QString)`, `studyRemoved(QString)` and `seriesRemoved(QString)` to the DICOM database (see `ctkDICOMDatabase`).
It also improves the CTK continuous integration and DICOM testing infrastructure.
Highlights:
* Add removePatient/Series/Study signals to DICOM database
* Fix and update DICOM tests to support running all of them in ~7s
* Update pre-commit config to include "end-of-file-fixer" and "mixed-line-ending"
```
$ git shortlog b83ff7a54..45f33c81 --group=author --group=trailer:co-authored-by --no-merges
ENH: Add removePatient/Series/Study signals to DICOM database
Davide Punzo (4):
ENH: Refine order of ctkErrorLogLevel enum values
ENH: Update ctkLogger adding support for log level
BUG: Fix argument …
```
> ENH: Update CTK adding removePatient/Series/Study signals to DICOM database

- Modules/Scripted/DICOM/DICOM.py
- Modules/Scripted/DICOM/Resources/UI/DICOM.ui
- Modules/Scripted/DICOMLib/DICOMBrowser.py
- SuperBuild/External_CTK.cmake
**:zap: Updated[^1] Description: :zap:**
[^1]: _The description has been updated by @jcfr on 2024.01.19 based on the consolidated list of commits integrating the CTK changes merged through https://github.com/commontk/CTK/pull/1165_
This enhancement includes an update to CTK and introduces the `ctkDICOMVisualBrowserWidget` to augment DICOM exploration, query, and retrieval capabilities within the DICOM module. The widget is seamlessly integrated into the Slicer DICOM module and is labeled as experimental.
For a comprehensive overview and future plans, refer to the roadmap at:
* https://github.com/commontk/CTK/issues/1162.
By default, the widget is disabled, and users can access the familiar `ctkDICOMBrowser` when opening the `DICOM` module. To enable the experimental feature, users can …
> ENH: Add experimental visual DICOM browser

- Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx
- Modules/CLI/ResampleDTIVolume/Testing/itkDifferenceDiffusionTensor3DImageFilter.txx
- Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DInterpolateImageFunctionReimplementation.txx
- Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DRead.txx
- Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DWrite.txx
- Modules/CLI/ResampleScalarVectorDWIVolume/ResampleScalarVectorDWIVolume.cxx
Fix ITK's threading-related method name deprecation warnings.
Fixes:
```
Slicer/Modules/CLI/ResampleDTIVolume/Testing/itkDifferenceDiffusionTensor3DImageFilter.txx:135:7:
warning: ‘slicer_itk::ThreadIdType slicer_itk::ProcessObject::GetNumberOfThreads() const’ is deprecated [-Wdeprecated-declarations]
int numberOfThreads = this->GetNumberOfThreads();
^~~~~~~~~~~~~~~
In file included from /usr/src/Slicer-build/ITK/Modules/Core/Common/include/itkLightObject.h:21:0,
from /usr/src/Slicer-build/ITK/Modules/Core/Common/include/itkObject.h:31,
from /usr/src/Slicer-build/ITK/Modules/Core/Common/include/itkMultiThreaderBase.h:31,
from /usr/src/Slicer-build/ITK/Modules/Compatibility/Deprecated/include/itkMultiThreader.h:23,
from /usr/src/Slicer/Modules/CLI/ResampleDTIVolume/Testing/itkTestMainExtend …
```
> COMP: Fix ITK's threading-related method name deprecation warnings

- Base/QTCore/qSlicerIO.h
To ensure correct lookup of the return type of the `fileType` function registered with the meta-object system (MOC), this commit updates the function signature. Previously, it was registered as "IOFileType," and this caused issues with PythonQt, which expected "qSlicerIO::IOFileType" for proper identification.
This change eliminates the need to separately register the unqualified and potentially conflicting shorter version:
```cpp
qRegisterMetaType<qSlicerIO::IOFileType>("IOFileType");
```
It also fixes the following error:
```python
reader = slicer.qSlicerSceneBundleReader()
reader.fileType()
File "<console>", line 1, in <module>
ValueError: Called fileType() -> IOFileType, return type 'IOFileType' is ignored because it is unknown to PythonQt. Probably …
```
> BUG: Fix meta-object system registration of qSlicerIO::fileType return type

- Base/QTCore/qSlicerCoreIOManager.cxx
This ensures the `IOFileType` type associated with the `fileType` parameter of the functions used to check if a particular reader or writer is registered as a metatype without having any `qSlicerIO` instance already created.
The relevant `qSlicerCoreIOManager` functions are the following:
```
int registeredFileReaderCount(const qSlicerIO::IOFileType& fileType) const;
int registeredFileWriterCount(const qSlicerIO::IOFileType& fileType) const;
```
For example, this addresses the following error where executing python code through the `-c` option (equivalent to passing `--disable-modules`):
```bash
./Slicer -c "import slicer;print(slicer.app.ioManager().registeredFileReaderCount('VolumeFile'));slicer.app.quit()"
File "<string>", line 1, in <module> …
```
> BUG: Support checking if IO registration from python without registered IOs

- Applications/SlicerApp/Testing/Python/CMakeLists.txt
- Base/Python/slicer/tests/test_slicer_util_load_data.py
- Base/Python/slicer/util.py
- ENH: Check for extension and registered reader for fiber bundle data
- ENH: Add test for the `slicer.util.loadFiberBundle` method
> ENH: Add test for the `slicer.util.loadFiberBundle` method

- SuperBuild/External_CTK.cmake
* https://github.com/commontk/CTK/pull/1189
* https://github.com/commontk/CTK/pull/1188
```
$ git shortlog 888cdd92b..4aba4e20 --group=author --group=trailer:co-authored-by --no-merges
ENH: Update PythonQt backporting recent changes from MeVisLab/pythonqt
ENH: Update PythonQt backporting recent changes from MeVisLab/pythonqt
ENH: Always compile python scripts as legacy .pyc files
```
> ENH: Update CTK to backport PythonQt fixes & restore script compilation to pyc

- CMake/SlicerBlockInstallQt.cmake
This commit focuses on updating the Qt install rules to ensure the packaging of the latest version of `d3dcompiler_47.dll`. The proper functioning of "Microsoft.Holographic.Remoting.OpenXr" within the SlicerVirtualReality extension with OpenXR remoting enabled relies on this update for successful scene rendering.
By setting the `WindowsSdkDir` environment variable, the "windeployqt" tool is instructed to look up and deploy the library available on the system. This action prevents the deployment of an older version that may be installed alongside Qt 5.15.2 libraries when Qt is installed using the installer.
For future reference, here are links related to the `windeployqt` tool
* For Qt 5.15.2 (source managed in the `qttools` project)
* …
> BUG: Ensure packaging of the latest d3dcompiler_47.dll for SlicerVirtualReality

- Modules/Loadable/Sequences/Logic/vtkSlicerSequencesLogic.cxx
- Modules/Loadable/Sequences/Testing/Cxx/vtkMRMLSequenceBrowserNodeTest1.cxx
When "save changes" was enabled for a sequence then it was not possible to delete the last time point.
> BUG: Fix deletion of last time point in a sequence

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorThresholdEffect.py
When a single vtkMRMLSegmentEditorNode was used by multiple qSlicerSegmentEditorWidget instances then after using Threshold effect, the current segment disappeared from slice views.
The reason was that Threshold effects in every segment editor widgets get activated (via sharing the segment editor node) and they all started preview, saved original segment opacity, and then on "Apply" restored the original segment opacity. However, the segment opacity that was restored by second, third, etc. effects were not the original anymore, but it was already the opacity that was set to 0 (it has to be set to 0 to prevent the current segment occluding the preview).
The solution could have been to store the original opacity in a shared location (e.g., in the segment editor node), but that would not …
> BUG: Fix segment disappearing when sharing segment editor node between widgets

- Modules/Scripted/DICOMPlugins/DICOMImageSequencePlugin.py
Adds Multi-frame Grayscale Byte Secondary Capture Image Storage (SOP Class UID: 1.2.840.10008.5.1.4.1.1.7.2) to DICOMImageSequencePlugin.py.
> ENH: Add DICOM support for Multi-frame Grayscale Byte Secondary Capture Image

- Base/QTGUI/Resources/UI/qSlicerSettingsViewsPanel.ui
Shadows feature is not yet mature enough to be enabled by default. It may make rendering darker, not compatible with MIP, and the shader fails to compile if shading (normal computation) is disabled.
See #7560 for MIP incompatibility
See discussion about darkened look at https://discourse.slicer.org/t/are-shadows-enabled-by-default-for-volume-rendering-in-new-previews/34219
> ENH: Disable shadows in 3D views by default

- Base/QTCore/qSlicerExtensionsManagerModel.cxx
This is an attempt to fix #7579 by adding loadable module paths of extensions to `PYTHONPATH` section of `Slicer-NNN.ini`.
For example, before this fix, `PYTHONPATH` section of `Slicer-NNN.ini` was this:
```
[PYTHONPATH]
size=2
1\path=slicer.org/Extensions-30987/SlicerVMTK/lib/Slicer-5.7/qt-scripted-modules
2\path=slicer.org/Extensions-30987/SlicerVMTK/lib/Slicer-5.7/qt-loadable-modules/Python
```
After this fix:
```
[PYTHONPATH]
size=4
1\path=slicer.org/Extensions-30987/SlicerVMTK/lib/Slicer-5.7/qt-scripted-modules
2\path=slicer.org/Extensions-30987/SlicerVMTK/lib/Slicer-5.7/qt-loadable-modules
3\path=slicer.org/Extensions-30987/SlicerVMTK/lib/Slicer-5.7/qt-loadable-modules/Python
4\path=slicer.org/Extensions-30987/ExtraMarkups/lib/Slicer-5.7/qt-loadable-modules
```
The added …
> BUG: Fix loading of modules that depend on another extension

- Libs/MRML/Widgets/Resources/UI/qMRMLNodeAttributeTableView.ui
- Libs/MRML/Widgets/Resources/UI/qMRMLNodeAttributeTableWidget.ui
- Libs/MRML/Widgets/qMRMLNodeAttributeTableView.cxx
- Libs/MRML/Widgets/qMRMLNodeAttributeTableView.h
- Libs/MRML/Widgets/qMRMLNodeAttributeTableWidget.cxx
In Data module, "MRML node information" section had a "Node information" section and an untitled node attributes section. The node attributes section displayed messages (e.g., attribute name already exists) above the table. This all looked quite confusing.
Updated the GUI to have a "Properties" and "Attributes" section under "MRML node information". Also replaced the label above the table by a tooltip for showing "attribute name already exists" message.
> ENH: Improve appearance of node information section in Data module

- Base/QTCore/Testing/Cxx/qSlicerExtensionsManagerModelTest.cxx
Update test based on change introduced in 9c87503363 (`"BUG: Fix loading of modules that depend on another extension", 2024-02-09`) through https://github.com/Slicer/Slicer/pull/7580
> BUG: Fix qSlicerExtensionsManagerModelTest

- Libs/MRML/Core/vtkMRMLTransformDisplayNode.cxx
- Libs/MRML/Core/vtkMRMLTransformDisplayNode.h
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLLinearTransformsDisplayableManager2D.cxx
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLLinearTransformsDisplayableManager3D.cxx
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformHandleWidgetRepresentation.cxx
- Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.cxx
- Modules/Loadable/Transforms/Widgets/Resources/UI/qMRMLTransformDisplayNodeWidget.ui
- Modules/Loadable/Transforms/Widgets/qMRMLTransformDisplayNodeWidget.cxx
- Modules/Loadable/Transforms/Widgets/qMRMLTransformDisplayNodeWidget.h
The visibility of individual interaction axes can now be controlled separately for transform nodes.
- Translation: X, Y, Z, View
- Rotation: X, Y, Z
- Scaling: None
- Translation: View
- Rotation: View
- Scaling: None
- EditorVisibility3D and EditorSliceIntersectionVisibility control the visibility in their respective views, while EditorVisibility controls visibility in both.
- Editor{XYZ}Enabled now only works for 3D while Editor{XYZ}SliceEnabled has been added to control 2D view visibility.
- {XYZ}HandleComponentVisibility3D allows individual axes to be enabled disabled in 3D, while {XYZ}HandleComponentVisibilitySlice does the same in 2D.
- "Interaction in 3D view" is now "Interaction", and controls visibility in both views.
Re #7570
> ENH: Add finer control of 2D interaction handle axis display

- SuperBuild/External_python.cmake
- SuperBuild/python_configure_python_launcher.cmake
This commit addresses an issue where launcher scripts installed from wheels were not correctly added to the PATH. Specifically, it updates the PATH for both "Slicer" and "PythonSlicer" launcher settings in the build and install tree. This adjustment ensures that convenience executables created after installing wheels with specified entry-points such as "project.scripts" or "project.gui-scripts" can be easily located and accessed within the project environment.
> BUG: Ensure launcher scripts installed from wheels are accessible

- Modules/Scripted/WebServer/Resources/docroot/ServerTests/WebXR-controller/index.html
- Modules/Scripted/WebServer/Resources/docroot/index.html
- Modules/Scripted/WebServer/WebServer.py
HTTPS support updated to support both the .pem file and .key file. This allows the server to be configured to support https if the .pem file is shared with a client (note - for Android phones the .pem file may need to be converted to .der format).  Adding a way to help generate and configure these files without editing the code can be addressed in future work.
HTTPS is required to use the WebXR interface on the mobile phone due to security concerns (WebXR uses cameras and other tracking data that is considered a potential privacy issue, so https is required).
The WebXR demo allows the user to manage a MRML linear transform node based on the position and orientation of the phone.  See this page for an example video and more information: …
> ENH: Update https support and add WebXR demo as transform controller

- Libs/MRML/Widgets/qMRMLTransformSliders.cxx
- Libs/MRML/Widgets/qMRMLTransformSliders.h
This is a fix for the transformation matrix editing glitch that @RafaelPalomar demonstrated during the weekly developer meeting.
In transforms module, when linear transformation matrix values were edited using spinboxes and then by directly editing the matrix, the value that was previously edited in the spinbox got overwritten by the new value.
The issue was that a single slot was used for all signals coming from all sliders and in the slot implementation the active focus was used to determine which axis should be updated. Fixed by using a separate slot for each axis. This way we don't rely on the GUI widget focus, which may go through complex transitions during transform editing using various widgets.
> BUG: Fix unrelated matrix elements overwritten in transform editor

- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidget.cxx
- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidget.h
- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidgetRepresentation.h
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformHandleWidget.cxx
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformHandleWidget.h
This commit enables the jump to handle action when left-clicking on an interaction handle.
For Transform nodes:
- Jump is only available when clicking on the center of transformation.
For Markups nodes:
- Jump is available for any handle type.
Re #7570
> ENH: Add jump to handle action for interaction handles

- .git-blame-ignore-revs
Update the list referencing 2762f0c9f3 (`STYLE: Convert C++ source files from old-style "Whitesmiths" to "Allman" style`, 2024-02-20)
> STYLE: Add brace indentation style update to ignored list for git blame 

- Base/QTCore/qSlicerCoreApplication.cxx
- Base/QTGUI/qSlicerWebWidget.cxx
- Libs/MRML/Core/vtkMRMLAbstractViewNode.cxx
- Libs/MRML/Core/vtkMRMLModelNode.h
- Libs/MRML/Core/vtkMRMLNode.cxx
- Libs/MRML/Core/vtkMRMLProceduralColorNode.h
- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLSliceNode.h
- Libs/MRML/Core/vtkMRMLStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTransformDisplayNode.cxx
- Libs/vtkITK/vtkITKImageThresholdCalculator.h
- Libs/vtkITK/vtkITKImageWriter.h
- Modules/Loadable/Annotations/Logic/vtkSlicerAnnotationModuleLogic.cxx
- Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationSnapshotNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx
- Modules/Loadable/Markups/Widgets/qSlicerSimpleMarkupsWidget.cxx
- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx
- Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
- Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMExportDialog.cxx
These changes are done anticipating the integration of "clang-format" for automated formatting of source files.
Changes were identified using the following one-liners:
```
cd Slicer
ack -i "^[\s\/]*(ctk|itk|slicer|vtk)\s*[0-9a-zA-Z]+\([\,a-zA-Z0-9\s]+\)$"
ack "Q_UNUSED\([\,a-zA-Z0-9\s]+\)$"
ack "Q_[^P][A-Za-z0-9]+\([\,a-zA-Z0-9\s]+\)$" # To identify use of "Q_*" macros excluding "Q_PROPERTY"
```
> STYLE: Add missing semicolon after statement macros

- Docs/developer_guide/script_repository/segmentations.md
- Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationGeometryLogic.cxx
- Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationGeometryLogic.h
- Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest1.py
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationGeometryWidget.cxx
Added `SetReferenceImageGeometryInSegmentationNode` function to `vtkSlicerSegmentationGeometryLogic`. This feature was only available in the segmentation geometry widget, which was not convenient for scripting.
> ENH: Add SegmentationGeometryLogic API to set reference image geometry

- Libs/MRML/Core/vtkMRMLTransformNode.cxx
- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidget.cxx
- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidget.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsInteractionWidget.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsInteractionWidget.h
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformHandleWidget.cxx
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLTransformHandleWidget.h
This commit adds a cancel action when translating/rotating/scaling using interaction handles. Users can press "Escape" or right-click to cancel the current action and restore the Transform or Markups node back to its original state.
Re #7570
> ENH: Add cancel action for interaction handles

- Docs/developer_guide/modules/segmentations.md
- Libs/MRML/Core/Testing/CMakeLists.txt
- Libs/MRML/Core/Testing/vtkMRMLSegmentationStorageNodeTest1.cxx
- Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx
NRRD file cannot be created without voxel data, so an 1x1x1 array was used as image data. However, when the empty segmentation was loaded then this single-voxel geometry was treated as a valid geometry. Fixed by detecting this special case of a single voxel in the segmentation, and considering the geometry invalid in this case.
fixes #7576
> BUG: Fix loading of empty segmentation

- Base/Python/slicer/i18n.py
If a Python string with placeholders (e.g., Loading {filename}) is translated incorrectly so that the placeholder is not in the translated string (e.g., Carga {nombre de archivo}) then currently an exception is raised and execution of the Python code stops.
Fixed by only using the translated string if the placeholders match. Otherwise a warning is logged and the translation is not used.
fixes #7235
> ENH: Make translations in Python scripts more robust

- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManagerHelper.cxx
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLLinearTransformsDisplayableManager.cxx
The interaction renderer instantiated in vtkMRMLMarkupsDisplayableManager::Create() is not supported in VR.
Follow-up of Slicer/Slicer@4efda83181 (`ENH: Add interaction handle visualization for linear transform nodes (#7562)`, 2024-02-02) introduced in https://github.com/Slicer/Slicer/pull/7562
This addresses the following error reported when initializing an OpenVR or OpenXR connection:
```
[...]
Initializing "OpenXR" XR backend (1/1)
vtkOpenXRRenderWindow::AddRenderer: Failed to add renderer of type vtkOpenGLRenderer: A vtkOpenXRRenderer is expected
vtkOpenXRRenderWindow::AddRenderer: Failed to add renderer of type vtkOpenGLRenderer: A vtkOpenXRRenderer is expected
[...]
```
> BUG: Skip creation of markups interaction widget in VR windows

- Modules/Loadable/VolumeRendering/Logic/Testing/Cxx/vtkSlicerVolumeRenderingLogicTest.cxx
- Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx
- Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.h
When a volume rendering preset was added to the preset scene, the input preset node was moved to that scene, thereby making the scene that contained the input preset node unusable. Fixed by making a copy of the input preset node instead of moving it.
> BUG: Make volume rendering preset registration more robust

- Docs/developer_guide/script_repository/gui.md
**Background**: Enhance script documentation by fixing comment formatting, updating variable names for improved readability, and resolving a missing closing bracket issue in the 'Change file type for saving for existing nodes' section. These changes specifically improve clarity when setting the default segmentation storage to not compress by default.
> DOC: Fix comment format, update variable names, and add missing closing bracket in script repository

- SuperBuild/External_CTK.cmake
```
$ git shortlog 51c9f4a5a..5a5c9f62a --no-merges
STYLE: Convert C++ source files from old-style "Whitesmiths" to "Allman" style (#1193)
```
> STYLE: Update CTK with source files converted to "Allman" indentation style

- Base/QTGUI/qSlicerWebPythonProxy.cxx
- Base/QTGUI/qSlicerWebPythonProxy.h
- SuperBuild/External_CTK.cmake
Update `qSlicerWebPythonProxy` to allow specifying `EvalInput` as mode and ensure a result is returned as `QVariant`.
For example:
```js
await slicerPython.evalPython("40+2")
""
await slicerPython.evalPython("40+2", slicerPython.EvalPythonMode.EvalInput)
"42"
```
Note that the associated CTK changes are not strictly required to support passing the evalPython mode parameter.
```
$ git shortlog 5a5c9f62a..a0ea618f1 --no-merges
ENH: Support using ctkAbstractPythonManager::ExecuteStringMode from Python
```
> ENH: Support returning the result when executing Python from qSlicerWebWidget

- Base/QTGUI/qSlicerWebWidget.cxx
- Base/QTGUI/qSlicerWebWidget.h
This commit updates `qSlicerWebWidget` to remove obsolete code related to Webkit integration. The removal of this code prevents the display of a warning message that occurs when loading a page after opening the extension manager or explicitly instantiating a `qSlicerWebWidget` and setting its URL property.
The warning message was:
```
"JQuery not loaded - Failed to trigger webkitvisibilitychange"
```
This integration was initially introduced in commit 8d7f94e4ee ("BUG: Prevent extensions from being loaded twice when 'Install' tab initially hidden", 2013-02-04), but the support for Webkit was later removed in commits:
* 6bd2db52ef ("COMP: Remove support for building against Qt WebKit module", 2019-03-08)
* f3edc8f609 ("STYLE: Remove obsolete code supporting use of Qt WebKit module", …
> BUG: Remove obsolete Webkit-specific integration code from qSlicerWebWidget

- Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
- Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx
- Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentsPlugin.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
When closing the scene, qSlicerMarkupsModuleWidget::updateWidgetFromMRML() would access the subjectHierarchyNode without first checking if it exists, causing a crash.
Fixed by adding a nullptr check.
See: https://discourse.slicer.org/t/weird-trouble-with-markups/34872/
> BUG: Fix crash in Markups widget when closing scene

- .gitignore
Also remove unneeded entry related to `.circleci` directory that was removed in 991cd64b9a ("COMP: Add "CI" GitHub action workflow to replace CircleCI", 2021-11-30)
> COMP: Update .gitignore ensuring changes to .github files are reported

- Libs/MRML/Core/vtkMRMLTransformNode.cxx
- Libs/MRML/Core/vtkMRMLTransformNode.h
- Libs/MRML/Widgets/qMRMLLinearTransformSlider.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsInteractionWidgetRepresentation.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLLinearTransformsDisplayableManager.cxx
- Modules/Loadable/Transforms/Resources/UI/qSlicerTransformsModuleWidget.ui
- Modules/Loadable/Transforms/SubjectHierarchyPlugins/CMakeLists.txt
- Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.cxx
- Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.h
- Modules/Loadable/Transforms/Widgets/Resources/UI/qMRMLTransformDisplayNodeWidget.ui
- Modules/Loadable/Transforms/Widgets/qMRMLTransformDisplayNodeWidget.cxx
- Modules/Loadable/Transforms/Widgets/qMRMLTransformDisplayNodeWidget.h
- Modules/Loadable/Transforms/qSlicerTransformsModuleWidget.cxx
- Modules/Loadable/Transforms/qSlicerTransformsModuleWidget.h
New SH actions for resetting the center of transformation for a transform:
- Reset to local origin
- Reset to world origin
- Reset to center of bounds for all transformed nodes
- Reset to center of bounds for a single transformed node
Transforms module widget:
- New widget for live display and editing of center of transformation
- New slider for changing scale of interaction widget
Bug fixes:
- Use correct scale for markups interaction handles
- Fix both 2D and 3D visibility being controlled by GetEditorSliceIntersectionVisibility
Re #7570
> ENH: Improve interaction options in Transforms SH plugin and module widget

- Libs/vtkSegmentationCore/vtkBinaryLabelmapToClosedSurfaceConversionRule.cxx
- SuperBuild/External_VTK.cmake
Surface low-pass filter did not use an optimal window function, which sometimes resulted in small (<1%) scale difference in smoothed output.
The issue was fixed in VTK by implementing Nuttall window function and use it by default. We also slightly increment the number of iterations at stronger smoothing settings, as the default 20 iterations is only enough for moderate smoothing factors.
More information:
- https://discourse.slicer.org/t/accuracy-of-segmentation-smoothing/34723
- https://discourse.vtk.org/t/slight-offset-in-vtkwindowedsincpolydatafilter-if-normalization-is-enabled/7676
VTK is updated to include these commits:
* Slicer/VTK@9f48d797ada1069e5717116e3e62e1d6d37ddc4c:
```
Revision: 9f48d797ada1069e5717116e3e62e1d6d37ddc4c
Date: …
```
> BUG: Improve surface smoothing accuracy in segmentations

- SuperBuild/External_CTK.cmake
Reference PR: https://github.com/commontk/CTK/pull/1191
@lassoan 
BUG: Fix issue with proxy server attribute in ctkDICOMServerNodeWidget2.
Resolved a bug where the proxy server attribute in the servers settings UI was being cleared at startup.
The fix ensures that the proxy server option is now correctly retained during initialization.
BUG: Fix sorting of Study Widgets in the Visual DICOM Browser.
Addressed a bug related to the sorting of study widgets in the visual DICOM browser.
Previously, the sorting mechanism was compromised when studies shared the same date,
leading to incorrect layout additions and missing study widgets. This issue has been fixed,
ensuring proper sorting even when studies have identical dates.
BUG: Fix ctkJobScheduler crash when stopping jobs …
> ENH: Update CTK with visual DICOM browser improvements

- Modules/Scripted/DICOMPatcher/DICOMPatcher.py
Photometric intepretation field of compressed ultrasound images was ambiguous before DICOM CP156 (https://dicom.nema.org/medical/dicom/Final/cp156_ft.pdf) and there are DICOM images in the wild that contain photometric interpretation value (RGB) that is inconsistent with the compressed transfer syntax (JPEG). See https://groups.google.com/g/comp.protocols.dicom/c/EPkbFOMBOhE for more details.
The new DICOM patcher rule modifies RGB photometric interpretation to YBR_FULL_422 if the transfer syntax of the image is JPEG, because JPEG compression is practically always used with YBR_FULL_422.
> ENH: Add DICOM patcher rule to fix compressed ultrasound discolorization

- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidgetRepresentation.cxx
- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManagerHelper.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
- Modules/Loadable/Transforms/MRMLDM/vtkMRMLLinearTransformsDisplayableManager.cxx
Improve and re-enable visibility of transform interaction widgets in VR.
Visualization of interaction widgets works for both absolute and relative widget size. Interacting with the widgets is not implemented yet, though the handles hand can be highlighted using the controllers.
Re #7570
- ### Adaptive scale:
https://github.com/Slicer/Slicer/assets/9222709/9e79d6ed-68df-4435-ad7f-9b1837177b79
- ### Absolute size:
https://github.com/Slicer/Slicer/assets/9222709/f9e757a5-2ff1-4483-9d80-149d8d73db20
> ENH: Re-enable display of interaction handles in VR

- Modules/Scripted/WebServer/WebServerLib/SlicerRequestHandler.py
The NRRD definition lists various aliases
to specify the for the "short" datatype in
the "type" nrrd header field (see
https://teem.sourceforge.net/nrrd/format.html#type).
Pynnrd as a widely used nnrd library
e.g. creates NRRD headers with short
datatypes identified as "int16" and
does not allow to override this.
Consequently, a POST request to the
slicer/volume endpoint will always fail
with data from pynnrrd.
This commit relaxes the type check to
also allow aliases of "short" to pass.
> ENH: Allow aliases for NRRD "type" header in postNRRD

- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
Addresses issue introduced in 580e1875b1c0fa20d1db123d5feeb6487fca2c2d which caused markups handle scale to not update. The original fix was meant to prevent a crash when starting VR with Markups in the scene, however it disabled scale update in all situations. Fixed by checking GetNeverRendered() instead of GetGenericContext(), before calling GetScreenSize(). Once the window has been rendered at least once, it is safe to call GetScreenSize().
Related issues and pull requests:
* https://github.com/Slicer/Slicer/issues/7570
* https://github.com/Slicer/Slicer/pull/7630
> BUG: Fix markups handle scale not updating

- SuperBuild/External_VTK.cmake
This commit updates the external project to explicitly reference the VTK version that was manually checked out within the Slicer release-specific build tree to support building the SlicerVirtualReality extension.
* https://github.com/Slicer/VTK/pull/47
* https://github.com/Slicer/VTK/pull/49
* https://github.com/Slicer/VTK/pull/50
* https://github.com/Slicer/VTK/pull/52
* https://github.com/Slicer/VTK/pull/54
```
$ git shortlog 46201478c..d4be5ea25 --no-merges
Alexy Pellegrini (6):
[Backport] Enable switching from remoting XR runtime to default XR runtime dynamically
[Backport] Add a utility function to query OpenXR instance version
[Backport] OpenXR: Add missing EndInitialize in QueryInstanceVersion
[Backport] VR: enable interaction methods to …
```
> [5.6] ENH: Update VTK backporting SlicerVirtualReality extension specific changes

- Docs/user_guide/coordinate_systems.md
Backport of https://github.com/Slicer/Slicer/pull/7548
---------
This commit corresponds to minor rewording in the coordinate_systems.md file to improve clarity and ensure grammatical correctness.
(cherry picked from commit e3eae6e67d9f033029c14c60204677242e1fa1bf)
> [5.6] DOC: Refine Language in coordinate_systems.md

- Libs/MRML/Widgets/qMRMLTransformSliders.cxx
- Libs/MRML/Widgets/qMRMLTransformSliders.h
Backport of https://github.com/Slicer/Slicer/pull/7594
------------
In transforms module, when linear transformation matrix values were edited using spinboxes and then by directly editing the matrix, the value that was previously edited in the spinbox got overwritten by the new value.
The issue was that a single slot was used for all signals coming from all sliders and in the slot implementation the active focus was used to determine which axis should be updated. Fixed by using a separate slot for each axis. This way we don't rely on the GUI widget focus, which may go through complex transitions during transform editing using various widgets.
(cherry picked from commit 325fdbd4c380c1c30f18ded37acdc6c1270e9f1a)
> [5.6] BUG: Fix unrelated matrix elements overwritten in transform editor

- Libs/vtkSegmentationCore/vtkBinaryLabelmapToClosedSurfaceConversionRule.cxx
- SuperBuild/External_VTK.cmake
Backport of https://github.com/Slicer/Slicer/pull/7643
-----------
Surface low-pass filter did not use an optimal window function, which sometimes resulted in small (<1%) scale difference in smoothed output.
The issue was fixed in VTK by implementing Nuttall window function and use it by default. We also slightly increment the number of iterations at stronger smoothing settings, as the default 20 iterations is only enough for moderate smoothing factors.
More information:
- https://discourse.slicer.org/t/accuracy-of-segmentation-smoothing/34723
- https://discourse.vtk.org/t/slight-offset-in-vtkwindowedsincpolydatafilter-if-normalization-is-enabled/7676
```
$ git shortlog d4be5ea25..4c46b5221 --no-merges
Andras Lasso (2):
[Backport] Improve accuracy of …
```
> [5.6] BUG: Improve surface smoothing accuracy in segmentations

- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidgetRepresentation.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx
- Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx
- Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.cxx
- Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.h
Adds the subject hierarchy menu "Interaction options" for enabling/disabling transform handle types (Rotation/Translation/Scaling), and adds all of the interaction options to the view context menu. This commit also fixes an issue where markups interaction handles could not be enabled/disabled correctly, and scale handles could be shown for unsupported markups types.
Re #7570
> ENH: Add SH options to control transform interaction handle type visibility

- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.h
Terminology logic only offered access to anatomical regions and their modifiers using C++ API (due to CodeIdentifier type is not accessible in Python). This commit adds helper functions that allow developers to iterate through all anatomical regions and their modifiers.
> ENH: Add Python-wrappable methods for accessing anatomical regions

- .github/workflows/pre-commit-autoupdate.yml
Update workflow introduced in 0f047b65c3 ("COMP: Add Github workflow for keeping pre-commit configuration up-to-date", 2024-03-17) ensuring the compare links referenced in the pull request description are correct.
* https://github.com/Slicer/Slicer/pull/7636
Raw:
```
- [pre-commit/pre-commit-hooks: v4.5.0 -> v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.5.0...v4.6.0)
- [astral-sh/ruff-pre-commit: v0.3.3 -> v0.3.6](https://github.com/astral-sh/ruff-pre-commit/compare/v0.3.3...v0.3.6)
- [asottile/pyupgrade: v3.15.1 -> v3.15.2](https://github.com/asottile/pyupgrade/compare/v3.15.1...v3.15.2)
```
Rendered:
- [pre-commit/pre-commit-hooks: v4.5.0 -> v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.5.0...v4.6.0)
- …
> COMP: Fix pull request description generated by pre-commit-autoupdate workflow

- Docs/developer_guide/build_instructions/linux.md
With these prerequisites I could build from scratch on a freshly booted 22.04 machine running on Jetstream2.
> DOC: Add ubuntu 22.04 build instructions

- Docs/developer_guide/build_instructions/linux.md
This is a follow-up to https://github.com/Slicer/Slicer/pull/7689, by trying to organize the required dev tools to be in a similar order between the different Ubuntu versions. This to hopefully better manage updates to required packages in the future.
> DOC: Reorganize Ubuntu console example of required dev tools

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorThresholdEffect.py
Use case:
- Avoid users changing upper and lower limit threshold values by accidentally clicking on the 2D views
Example:
```
segmentEditorWidget = mainWindow().findChildren('qMRMLSegmentEditorWidget')[0]
segmentEditorWidget.setActiveEffectByName("Threshold")
thresholdEffect = segmentEditorWidget.activeEffect()
thresholdEffect.self().enableViewInteractions = False
```
Thanks
> ENH: Allow disabling histogram (2D views) interactions of ThresholdEffect

- Libs/vtkTeem/vtkTeemNRRDReader.cxx
When some required fields in the NRRD file were missing, the user just got a generic error message. This commit logs detailed information about why Teem library could not load the NRRD file.
see https://discourse.slicer.org/t/slicer-rejects-modified-header/35549
> ENH: Log more information when NRRD reading fails

- Extensions/CLIExtensionTemplate.json
- Extensions/LoadableExtensionTemplate.json
- Extensions/ScriptedLoadableExtensionTemplate.json
- Extensions/ScriptedSegmentEditorEffectExtensionTemplate.json
- Extensions/SuperBuildExtensionTemplate.json
- Schemas/slicer-extension-catalog-entry-schema-v1.0.0.json
This is a follow-up of 1de721fd2b ("ENH: Add extension catalog entry file schema", 2024-03-19) in which the rename of the schema was partially applied.
Related pull request:
* #7709
> BUG: Fix extension schema id

- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.h
- Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
When the type selector was populated, all the type IDs were retrieved first, and then the type objects were looked up based on these IDs. This lookup is very slow if there are tens of thousands of types in the terminology.
Improved performance by returning not just all the type IDs but also all the corresponding type objects, therefore avoiding the costly lookup for each type.
see https://discourse.slicer.org/t/exporting-a-segmentation-paired-to-a-custom-colortable/35719/15
> ENH: Improve terminology selector speed

- Modules/Scripted/DICOM/DICOM.py
- Modules/Scripted/DICOMLib/DICOMBrowser.py
- SuperBuild/External_CTK.cmake
BUG: Fix import of DICOM files for the visual dicom browser
BUG: Fix update of DatabaseDirectory when is changed either in the dicom browser or the visual one
this requires https://github.com/commontk/CTK/pull/1201
> Fixes for the visual dicom browser

- Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserPlayWidget.cxx
- Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserPlayWidget.h
- Modules/Loadable/Sequences/Widgets/qMRMLSequenceBrowserToolBar.cxx
This makes the shortcuts for the qMRMLSequenceBrowserPlayWidget able to be customized from python. I have used this when showing multiple qMRMLSequenceBrowserPlayWidget objects and needing unique shortcuts for each.
> ENH: Make qMRMLSequenceBrowserPlayWidget shortcuts accessible from python

- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect_p.h
Currently the diameter of the tool could be changed in 3 different ways - by SpinBox, Slider, and a set of buttons. This change simplifies the options to be more concise by only have a slider and spinbox along with the button to toggle between absolute and relative sizing. The design is based on the existing Markups module glyph size widget options.
| `main` | This PR |
|--------|----------|
|![image](https://github.com/Slicer/Slicer/assets/15837524/2db8d69a-37c6-4a73-b6a7-6f3574aad564)|![image](https://github.com/Slicer/Slicer/assets/15837524/1d0771a5-f6dd-4d5b-babe-eadffad8c906)|
|![image](https://github.com/Slicer/Slicer/assets/15837524/34827e75-8fd0-416a-9dd1-fd5db36b5fad)|![image](https://github.com/Slicer/Slicer/assets/15837524/0500efd9-c649-41e8-9773-b3f5aec42dd8)|
Markups module …
> ENH: Simplify paint/erase diameter options for more concise UI

- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsInteractionWidgetRepresentation.cxx
Add nullptr check to vtkSlicerMarkupsInteractionWidgetRepresentation::UpdateHandleToWorldTransform.
See discussion: https://discourse.slicer.org/t/reproducible-slicer-crash-deleting-markupsroinodes-from-subject-hierarchy/36007
> BUG: Fix crash when deleting multiple markups in subject hierarchy

- Libs/vtkITK/vtkITKMorphologicalContourInterpolator.cxx
This removes duplicated code initially introduced in d0782fa233 (`ENH: Added contour interpolation`, 2016-10-04)
> COMP: Remove redundant call in vtkITKMorphologicalContourInterpolator

- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
In some situations (such as between Start/EndModify calls on vtkMRMLMarkupsCurveNode), it is possible that the output curve polydata will be in a state it has no points.
If TransformedCurvePolyLocator had been previously initialized and FindClosestPoint is called when the curve polydata has no points, then it will cause a crash. This is due to the vtkPointLocator HashTable not being reset correctly. See related MR fixing the issue in VTK here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11114
This commit fixes the crash by returning if there are no points without checking the vtkPointLocator. This change also serves as an minor optimization.
> BUG: Fix crash in vtkPointLocator when markups curve polydata is empty

- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.h
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologyType.cxx
Often the segment category&type and anatomic region codes are available in multiple contexts. This commit adds FindTerminologyNames and FindAnatomicContextNames methods to the terminology logic that allows getting a list of contexts where the codes are listed in.
The methods can also return the terminology objects, which makes it very easy to get properties (such as name and color) from codes.
> ENH: Add API for finding terminology from codes

- Libs/MRML/Core/vtkMRMLAbstractViewNode.cxx
- Libs/MRML/Core/vtkMRMLAbstractViewNode.h
- Libs/MRML/DisplayableManager/vtkMRMLAbstractWidgetRepresentation.cxx
- Libs/MRML/DisplayableManager/vtkMRMLAbstractWidgetRepresentation.h
- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidgetRepresentation.cxx
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h
- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation3D.cxx
Size of markup control points glyphs and text can be adjusted globally for a view by modifying the view node's ScreenScaleFactor property. This is useful for compensating different physical screen sizes and resolutions or for taking high-resolution screenshots. This scaling factor has already existed but it was hardcoded and now it is exposed in the view node.
Example use:
getNode('vtkMRMLViewNode1').SetScreenScaleFactor(0.1)
getNode('vtkMRMLSliceNodeRed').SetScreenScaleFactor(0.1)
Most likely users would not want to save this factor in the scene but they would set it for their computer, therefore the value is not written into the scene file.
> ENH: Add API to change screen scale factor

- Libs/MRML/Core/Testing/vtkMRMLVolumeArchetypeStorageNodeTest1.cxx
- Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx
- Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.h
- Libs/MRML/Core/vtkMRMLVolumeNode.cxx
- Libs/MRML/Core/vtkMRMLVolumeNode.h
- Modules/CLI/OrientScalarVolume/OrientScalarVolume.xml
Fix regression introduced in https://github.com/Slicer/Slicer/pull/7627 that image origin is not computed correctly when flipping K axis of an image to make it right-handed.
Fixes issue discussed in https://discourse.slicer.org/t/geometry-all-messed-up-in-latest-5-7-0-pre-release/36072/12
> Fix reading of images that have left-handed IJK coordinate system

- Base/QTCore/qSlicerExtensionsManagerModel.cxx
- Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake
- Extensions/CMake/SlicerFunctionExtractExtensionDescription.cmake
- Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake
These changes are ready to be reviewed & integrated.
* Ensure ExtractExtensionDescriptionFromJson sets empty output variable: This ensures that output variables are defined in the parent scope event if they are empty.
* Remove obsolete requirements from `SlicerExtensionPackageAndUploadTarget`
- Follow-up of 437e338 (`ENH: Switch extension index entry format from
"s4ext" to "json"`, 2024-03-13).
- It removes setting of `EXTENSION_CATEGORY` and `EXTENSION_ENABLED` into the `SCRIPT_ARGS_FILE`. These variables are now extracted from the ".json" file copied into the extension build directory.
* Improve error reporting in `slicer_generate_extension_description_test`: Since using "cmake -E compare_files" does not report any details, this commit explicitly report that the …
> Misc extensions tweaks

- SuperBuild/External_CTK.cmake
Contains these CTK fixes and improvements:
Revision: acfc526a2a7f646dd9cd27d2a35625825302ee4a
Author: Davide Punzo <punzodavide@hotmail.it>
Date: Fri May 17 06:07:02 2024 +0200
Message:
BUG: Ensure all studies metadata are queried before filtering
Revision: 4ac8f132bb2fbff0023f898d323b82a97de3192b
Author: Davide Punzo <punzodavide@hotmail.it>
Date: Thu May 16 15:15:12 2024 +0200
Message:
BUG: Update dicom-qr-schema.sql to version 0.8.1
Revision: 9eda3b8baa9d7f9ea109770e5c348f086a735e88
Author: Davide Punzo <punzodavide@hotmail.it>
Date: Wed May 15 19:57:28 2024 +0200
Message:
BUG: Conceal empty patient and study widgets during filtering
Revision: 890e51bfc02f9d9c028300423752af255c85027c
Author: Davide Punzo <punzodavide@hotmail.it>
Date: Tue May 14 15:16:48 2024 +0200
Message:
BUG: Match …
> BUG: Update CTK to fix Visual DICOM Browser

- Libs/MRML/Core/vtkMRMLModelDisplayNode.cxx
- Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx
Fixes warnings during rendering such as:
> Algorithm vtkPassThrough (00000223357FFBC0) returned failure for request: vtkInformation (000002233CEA6520)
Fixed by enabling AllowNullInput on the vtkPassThrough in vtkMRMLModelDisplayNode.
This commit also fixes an issue where the views would not be immediately rendered when vtkMRMLModelNode::SetAndObserveMesh(nullptr) was called for a model node that previously had a mesh. Fixed by requesting a render in vtkMRMLModelDisplayableManager whenever an actor that was previously visible is no longer displayable.
> BUG: Fix warnings when vtkMRMLModelNode has no mesh data

- Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx
- Libs/MRML/Core/vtkMRMLSegmentationStorageNode.h
- Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx
Make the segmentation storage node read .seg.nrrd files that are created outside of Slicer (e.g., using slicerio Python package).
They may use different order of fields (therefore the file detection heuristics had to be tuned), some fields may be missing, and there could be minor syntax differences (e.g., Slicer always terminates a list with separator character, but other software may just use separators between components).
> Improve segmentation (.seg.nrrd) file reader robustness

- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsClosedCurveNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsClosedCurveNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h
- Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx
- Modules/Loadable/Markups/Widgets/qMRMLMarkupsCurveSettingsWidget.cxx
- Modules/Loadable/Markups/Widgets/qMRMLMarkupsPlaneWidget.cxx
- Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx
- Modules/Loadable/Markups/Widgets/qSlicerMarkupsPlaceWidget.cxx
- Modules/Loadable/Markups/Widgets/qSlicerSimpleMarkupsWidget.cxx
- Modules/Loadable/Markups/qSlicerMarkupsModule.cxx
Mark some remaining translatable strings in Markups module
* Slicer/SlicerLanguagePacks#12
> BUG: Mark translatable strings in Markups module

- .github/workflows/pre-commit-autoupdate.yml
Add support for versions specified without the "v" prefix.
This fixes the description generated in pull request like the following:
* https://github.com/Slicer/Slicer/pull/7754
> COMP: Fix version extraction in pre-commit-autoupdate workflow

- .codespellignore
- Docs/user_guide/modules/screencapture.md
- Modules/CLI/N4ITKBiasFieldCorrection/N4ITKBiasFieldCorrection.cxx
- Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx
This is required because the `codespell-project/actions-codespell` does not pin the version of `codespell` and a new version was just released. 
| https://github.com/codespell-project/actions-codespell/blob/master/requirements.txt |https://pypi.org/project/codespell/#history |
| --- | -- |
| ![image](https://github.com/Slicer/Slicer/assets/219043/651e76d3-336e-4752-b5f3-fb2ccae83a37) | ![image](https://github.com/Slicer/Slicer/assets/219043/81f62cfc-3558-46e3-b4f5-f71e1a21de33) |
> COMP: Add support for codespell 2.3.0 and fix identified typos

- Docs/user_guide/modules/dynamicmodeler.md
Make the documentation match the updated interface and add an explanation that the boolean operations combine the negative sides of multiple planes to make the negative side of the output.  See https://github.com/Slicer/SlicerSurfaceToolbox/pull/62.
> DOC: Match updated interface in SlicerSurfaceToolbox Dynamic Modeler

- Modules/Loadable/Terminologies/qSlicerTerminologiesModule.cxx
- Modules/Loadable/Terminologies/qSlicerTerminologiesReader.cxx
- Modules/Scripted/ExtensionWizard/ExtensionWizard.py
- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/CreateComponentDialog.py
- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/DirectoryListWidget.py
- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/EditExtensionMetadataDialog.py
- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/EditableTreeWidget.py
- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/LoadModulesDialog.py
- Modules/Scripted/ExtensionWizard/ExtensionWizardLib/SettingsPanel.py
@lassoan  can you please look at this.
> BUG: Mark translatable strings in module ExtensionWizard

- Modules/Loadable/Reformat/Resources/UI/qSlicerReformatModuleWidget.ui
This was copy-paste error made in https://github.com/Slicer/Slicer/commit/e7578581612779b3d83ba976d35328427d398b97.
> BUG: Fix incorrect tooltip for rotate to volume reformat button

- Docs/user_guide/getting_started.md
I have tested the Slicer-5.6.2 binaries in different containers and updated the Linux instructions (mostly adding new packages needed to run the application). This was suggested by @lassoan in [https://discourse.slicer.org/t/cant-start-latest-stable-on-ubuntu-20-04/14029/51](https://discourse.slicer.org/t/cant-start-latest-stable-on-ubuntu-20-04/14029/51)
> DOC: Update Linux documentation

- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.h
Adds vtkSlicerTerminologiesModuleLogic::AreSegmentTerminologyEntriesEqual/AreTerminologyEntriesEqual/AreCodedEntriesEqual methods to check if two terminologies are equivalent.
> ENH: Add methods for comparing terminologies

- SuperBuild/External_SimpleITK.cmake
Update remaining use of `itk::simple` introduced after Slicer/SimpleITK@f95590f7 and omitted when updating SimpleITK in the context of Slicer/Slicer@acf3dd47 (ENH: Update ITK to 5.4.0)
List of SimpleITK changes:
```
$ git shortlog 4328a91a..441c59aa --no-merges
COMP: Update remaining Swig interface files to use "slicer_itk" namespace
COMP: Revert namespace changes in "sitkPathType.i" to fix build issues
```
-----------
Ensure SimpleITK is built using the Slicer Python environment by fixing the configuration to account for changes introduced in SimpleITK/SimpleITK@1b7d670b2, which uses the new CMake FindPython module.
This commit addresses the following warning:
```
CMake Warning at /path/to/SimpleITK/CMake/sitkLanguageOptions.cmake:110 (message):
Use …
```
> BUG: Update SimpleITK to fix import adding missing use of custom namespace

- Modules/Scripted/DICOMLib/DICOMBrowser.py
- SuperBuild/External_CTK.cmake
**Fix minor bug:**
Prevent DICOM Browser popups on initial module entry
**Update CTK:**
Refs: 
1) https://github.com/commontk/CTK/pull/1206
2) https://github.com/commontk/CTK/issues/1162
Revision: db10ff2b7067e82f29fc375def8a62051a01a2c3
Author: Davide Punzo <punzodavide@hotmail.it>
Date: Thu Jun 6 21:16:40 2024 +0200
Message:
BUG: Fix thumbnail scaling for high DPI displays.
Revision: 065f4df702e81f8f35f31f500c94295e487cbf7a
Author: Davide Punzo <punzodavide@hotmail.it>
Date: Thu Jun 6 18:05:06 2024 +0200
Message:
PERF: Implement thumbnail storage to disk to avoid re-rendering after series widget destruction.
PERF: Disable SEG rendering in thumbnails due to limited support and potential performance issues. Replace with a blank thumbnail featuring a document SVG.
BUG: Resolve issue …
> Visual dicom browser

- Base/Python/slicer/i18n.py
- Docs/developer_guide/debugging/python.md
- Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/ClosedSurfaceSegmentStatisticsPlugin.py
- Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/LabelmapSegmentStatisticsPlugin.py
- Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/ScalarVolumeSegmentStatisticsPlugin.py
This has performance implications where runtime is faster if English is the desired language for the application because the source code is in English.
Segmentation file to extract and put into User Downloads location (or modify script below)
[Segmentation.seg.zip](https://github.com/user-attachments/files/15920920/Segmentation.seg.zip)
```python
import os
import cProfile
cp=cProfile.Profile()
cp.enable()
sampleDataLogic = SampleData.SampleDataLogic()
mrHead = sampleDataLogic.downloadMRHead()
slicer.util.loadSegmentation(os.path.join(os.path.expanduser('~'), 'downloads', 'Segmentation.seg.nrrd'))
segmentationNode = getNode("Segmentation")
import SegmentStatistics
segStatLogic = SegmentStatistics.SegmentStatisticsLogic() …
```
> ENH: Only translate python strings when necessary

- SuperBuild/External_VTK.cmake
```
[Backport MR-11192] Make SSAO intensity configurable
Lucas Gandel (1):
[Backport MR-11192] Make SSAO intensity configurable
```
```
$ git shortlog --group=author --group=trailer:co-authored-by 9f48d797ada1069e5717116e3e62e1d6d37ddc4c..1923c43205ef6041f21e112807874ec9ae045b52
```
> BUG: Update VTK to backport vtkSSAOPass intensity adjustment feature

- Base/QTGUI/Resources/UI/qSlicerSettingsViewsPanel.ui
- Base/QTGUI/qSlicerSettingsViewsPanel.cxx
- Libs/MRML/Core/vtkMRMLViewNode.cxx
- Libs/MRML/Core/vtkMRMLViewNode.h
- Libs/MRML/Logic/vtkMRMLViewLinkLogic.cxx
- Libs/MRML/Widgets/qMRMLThreeDView.cxx
- Libs/MRML/Widgets/qMRMLThreeDView.h
- Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.h
- Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget_p.h
- Modules/Loadable/ViewControllers/qSlicerViewControllersModule.cxx
Shadows intensity can be linearly adjusted by shift and scale sliders in the 3D view controller.
This can be used to make ambient shadows appear darker (by increasing scale), without making the entire 3D scene darker (by increasing shift).
Example: see shadow of the rib casted on the kidney behind it. Left- no shadows. Center - default shadows (100%/0%). Right - strong shadows (200%/20%):
> ENH: Allow setting ambient shadows intensity

- SuperBuild/External_tbb.cmake
This is a follow-up to https://github.com/Slicer/Slicer/pull/7833#issuecomment-2204049639.
When building the `tbb` external project with MSVC 1940 (not with https://github.com/Slicer/Slicer/commit/aa313b88e79fd5f3d279a7a7c2fc01f8639c1cc7) there is a build error such as the following:
```
2>CMake Error at SuperBuild/External_tbb.cmake:85 (message):
2>  TBB does not support your Visual Studio compiler.  [MSVC_VERSION: 1940]
```
> COMP: Fix fatal error not reported for MSVC + TBB compatibility

- Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.cxx
For line/curve markup types, the lines are hidden whenever they don't intersect with the current slice, however the current behavior for angle markups is that they continue to be visible even when they no longer intersect. This commit updates the behavior of angle lines to be consistent with that of the other markup types.
See discussion: https://discourse.slicer.org/t/visibility-of-markups-angle-in-2d-slice-views-is-unlike-other-markups/37091
> ENH: Hide angle markups when the line doesn't intersect with the slice

- Docs/user_guide/modules/transforms.md
- Docs/user_guide/user_interface.md
- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidget.cxx
This commit adds AltModifier to the interaction handle event translations for WidgetEventMouseMove.
Adds information to the documentation pertaining to the new interaction options, including instructions on how to create, display, change the center of rotation, and how to interact with the handles.
> BUG: Fix translation handle flickering when holding ALT and update Transforms module documentation to include interaction info

- Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.cxx
- Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.h
Within the vtkMRMLSegmentationDisplayNode::UpdateSegmentList, there is an option to not remove unused display properties, however this argument is never used or exposed. This commit adds the RemoveUnusedDisplayProperties parameter to vtkMRMLSegmentationDisplayNode that allows display properties to be preserved when the segments are removed.
The default behavior is still to remove unused display properties.
> ENH: Add RemoveUnusedDisplayProperties to vtkMRMLSegmentationDisplayNode

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorIslandsEffect.py
Changing the island effect done message from info to debug. No other effect logs activity at this level, and it pollutes log when using algorithmically.
> ENH: Change log level in islands effect

- Libs/MRML/Core/vtkMRMLSegmentationNode.cxx
- Libs/vtkSegmentationCore/CMakeLists.txt
- Libs/vtkSegmentationCore/Testing/vtkSegmentationTest1.cxx
- Libs/vtkSegmentationCore/vtkSegmentation.cxx
- Libs/vtkSegmentationCore/vtkSegmentation.h
- Libs/vtkSegmentationCore/vtkSegmentationCoreConfigure.h.in
- Modules/Loadable/Segmentations/Testing/Python/SegmentationWidgetsTest1.py
- Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest1.py
- Modules/Loadable/Segmentations/Testing/Python/SegmentationsModuleTest2.py
- Modules/Scripted/SegmentStatistics/SegmentStatistics.py
Previously adding new segments to a segmentation would generate segment IDs of the format Segment_N unless another segment ID was specified. This commit changes the automatically generated segment IDs to use the format S_XYZ where XYZ is a unique random 16 character alphanumeric string.
This makes segment IDs more meaningful as a unique identifier since previously most segmentations would always contain the same IDs (Segment_1, Segment_1, etc.), now they will be unique across segmentations.
> ENH: Generate unique segment IDs using random identifier

- Libs/MRML/Core/vtkMRMLVolumeNode.cxx
- Libs/MRML/Core/vtkMRMLVolumeNode.h
- Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Automatically flip left handed volumes when loading into 3D Slicer from DICOM to make them compatible with all algorithms. Fixes flipped normals in segmentation node for left handed volumes.
Renamed FlipIJKCoordinateSystemHandedness method to ReverseSliceOrder to make it explicit that flipping of handedness is achieved by reversing slice order. The method was introduced recently (no Slicer Stable Release has been created since then), therefore the old name was not deprecated but removed.
See related commit that applies this regularization when the image is read using volume storage node: https://github.com/Slicer/Slicer/commit/3802d812b1a5d855399d8a19cea0bd1705715d52
See discussion at https://discourse.slicer.org/t/dentalsegmentator-result-mesh-is-inverted/37408/9
> BUG: Force loading images from DICOM using right-handed coordinate system

- Base/QTCore/qSlicerCoreApplication.cxx
- Base/QTCore/qSlicerCoreApplication.h
- CMake/vtkSlicerConfigure.h.in
- CMakeLists.txt
The new qSlicerCoreApplication::logUsageEvent can be called by modules in Slicer core and extensions to indicate that certain software feature is used. The application itself does not process the event, just emits a 'usageEventLogged' signal, which can be connected to slots in external modules.
This API can be used for example for implementing an extension that collects usage data and computes usage statistics of various features. If no extensions are installed that processes software usage data then calling qSlicerCoreApplication::logUsageEvent has no effect.
How to test:
```
slicer.app.connect("usageEventLogged(QString,QString)", lambda component, event: print(f"{component} -> {event}"))
slicer.app.logUsageEvent("TotalSegmentator", "segmentation/ct/total")
```
See related discussions at …
> ENH: Add API to log software usage events

- Modules/CLI/AddScalarVolumes/AddScalarVolumes.cxx
- Modules/CLI/CastScalarVolume/CastScalarVolume.cxx
- Modules/CLI/CheckerBoardFilter/CheckerBoardFilter.cxx
- Modules/CLI/CurvatureAnisotropicDiffusion/CurvatureAnisotropicDiffusion.cxx
- Modules/CLI/GaussianBlurImageFilter/GaussianBlurImageFilter.cxx
- Modules/CLI/GradientAnisotropicDiffusion/GradientAnisotropicDiffusion.cxx
- Modules/CLI/GrayscaleFillHoleImageFilter/GrayscaleFillHoleImageFilter.cxx
- Modules/CLI/GrayscaleGrindPeakImageFilter/GrayscaleGrindPeakImageFilter.cxx
- Modules/CLI/HistogramMatching/HistogramMatching.cxx
- Modules/CLI/ImageLabelCombine/ImageLabelCombine.cxx
- Modules/CLI/LabelMapSmoothing/LabelMapSmoothing.cxx
- Modules/CLI/MaskScalarVolume/MaskScalarVolume.cxx
- Modules/CLI/MedianImageFilter/MedianImageFilter.cxx
- Modules/CLI/MultiplyScalarVolumes/MultiplyScalarVolumes.cxx
- Modules/CLI/N4ITKBiasFieldCorrection/N4ITKBiasFieldCorrection.cxx
- Modules/CLI/OrientScalarVolume/OrientScalarVolume.cxx
- Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DWrite.txx
- Modules/CLI/ResampleScalarVectorDWIVolume/ResampleScalarVectorDWIVolume.cxx
- Modules/CLI/ResampleScalarVolume/ResampleScalarVolume.cxx
- Modules/CLI/SimpleRegionGrowingSegmentation/SimpleRegionGrowingSegmentation.cxx
- Modules/CLI/SubtractScalarVolumes/SubtractScalarVolumes.cxx
- Modules/CLI/ThresholdScalarVolume/ThresholdScalarVolume.cxx
- Modules/CLI/VotingBinaryHoleFillingImageFilter/VotingBinaryHoleFillingImageFilter.cxx
CLI modules are primarily used for processing and the output file is just used for temporary storage. Therefore, usually compression has no benefits, but it slows down the execution time.
If it turns out in the future that some modules would benefit from having compressed output, those modules could get an optional "--useCompression" flag, similarly to CreateDICOMSeries module.
See discussion at https://discourse.slicer.org/t/crop-volume-resample-scalar-slowness-for-large-image/34985/6
> ENH: Disable compression for CLI output files

- .github/workflows/commit-message.yml
Follow-up of bf50210585 ("COMP: Support reuse of "commit-message" GitHub workflow", 2024-08-19)
This ensures the "gsactions/commit-message-checker" internally using GraphQL along with the equivalent of the "Get a Pull Request" REST endpoint is granted with the expected permissions:
* "Pull requests" repository permissions (read)
* "Contents" repository permissions (read)
See https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request
> BUG: Update "pre-commit" workflow to support reuse from private project

- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLScene.h
When saving a scene that includes sequence nodes, it is easy to go over the max path length on windows. This is due to saving the mrb scenes for the sequences inside the temp directory of the full scene. This means that the path will include the same bundle temporary directory string twice in the sequence mrb path.
This commit results in a ~55% length decrease in the bundle directory path.
Previously scene temporary directories were of the format:
```__BundleSaveTemp-2024-08-20_115507_655``` (38 characters)
Now the bundle directory format is:
```20240820115507655``` (17 characters)
> ENH: Reduce bundle temp directory length when saving scene mrb

- Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx
- Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.h
- Libs/vtkITK/vtkITKArchetypeDiffusionTensorImageReaderFile.cxx
- Libs/vtkITK/vtkITKArchetypeImageSeriesReader.cxx
- Libs/vtkITK/vtkITKArchetypeImageSeriesReader.h
- Libs/vtkITK/vtkITKArchetypeImageSeriesScalarReader.cxx
- Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderFile.cxx
- Libs/vtkITK/vtkITKImageWriter.cxx
- Libs/vtkITK/vtkITKImageWriter.h
- Consolidate functions ConvertVoxelVectorTypeMRMLToVTKITK and ConvertVoxelVectorTypeVTKITKToMRML
- The type of the enum in the functions was mixed up
- These functions will be used in a later PR from another class (vtkMRMLVolumeSequenceStorageNode), and this paves the way to use the one function
- Remove the vtkFlip step from vtkITKImageWriter as it has no effect (not part of the pipeline)
- Minor style changes
> ENH: Minor fixes made during the 5D nrrd IO development

- Modules/Loadable/Data/Resources/UI/qSlicerDataModuleWidget.ui
In dark mode, the style sheet on the HelpButton was overriding the tooltip stylesheet, making it difficult to read. Fixed by changing the HelpButton style sheet so that the changes only affected the button, and not the tooltip.
Before:
After:
> BUG: Fix subject hierarchy help button tooltip's appearance in dark mode

- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidgetRepresentation.cxx
@Sunderlandkyl @lassoan 
This fixes two issues:
1) handle glyphs vtk rendering warning [lines](https://github.com/Slicer/Slicer/pull/7903/files#diff-eb8c3eb226772bfbd7f81c26ca0c10239a7c7260688123bcc49d09a895780964R977)
2) handles failing the rendering when unzomming a slice view. [lines](https://github.com/Slicer/Slicer/pull/7903/files#diff-eb8c3eb226772bfbd7f81c26ca0c10239a7c7260688123bcc49d09a895780964L1906-L1913)
For issue (2), adding the translation: `this->Pipeline->WorldToSliceTransform->Translate(0.0, 0.0, -slicePlanePosition[2] - 10*this->WidgetScale)` causes the interaction handles to disappear when WidgetScale is greater than 100. This might have been intentional to avoid rendering handles when unzooming a slice view beyond a certain scale. However, this introduces two problems: …
> BUG: Resolve interaction handles rendering issues

- Base/Python/slicer/i18n.py
Context was determined incorrectly due to a recent optimization of translation speed.
fixes https://github.com/Slicer/SlicerLanguagePacks/issues/78 fixes https://github.com/Slicer/SlicerLanguagePacks/issues/79
> BUG: Fix translation of Python modules

- .github/workflows/commit-message.yml
This pull request updates the commit message check workflow to use the newly created reusable composite action, now maintained at https://github.com/Slicer/slicer-check-commit-message-action
This change was discussed during the developer meeting on September 3, 2024. For reference, the relevant [meeting notes](https://discourse.slicer.org/t/2024-09-03-weekly-meeting/38169/5#p-115880-slicer-reusable-github-actions-and-workflows-5) are also copied below:
>  - Following Slicer [PR#7900](https://github.com/Slicer/Slicer/pull/7900), the GitHub workflow [`commit-message.yml`](https://github.com/Slicer/Slicer/blob/main/.github/workflows/commit-message.yml) is now re-usable.
>  - Maintaining this workflow within the `Slicer/Slicer` project prevents Dependabot from effectively tracking updates …
> ENH: Update "commit-message" workflow to use dedicated GitHub action

- Docs/developer_guide/script_repository.md
- Docs/developer_guide/script_repository/registration.md
- Docs/user_guide/modules/index.md
I realized there were no examples of (image) registration in the script repository, so I thought it would be helpful to create a section and add examples of scripting registrations.
> DOC: Add scriptedregistration.md with an example rigid registration

- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsJsonElement.cxx
- Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx
When markup point position was defined as an integer (0) instead of float (0.0) the markup reader rejected the position value. The problem was that the code only accepted double type. Fixed by accepting any numeric type.
Fixes issue reported at https://discourse.slicer.org/t/one-control-point-out-of-many-is-read-incorrectly-into-slicer/38369
> BUG: Fix reading of markup point position from integer value

- Docs/developer_guide/script_repository/segmentations.md
DOC: Remove outdated examples and link slicer documentation.
This refers to this (slicerio issue)[https://github.com/lassoan/slicerio/issues/10]. 
Here is an updated version of the corresponding section of the script repository. 
Fixes #7919
> DOC: Remove outdated example and link slicerio documentation .

- Applications/SlicerApp/Main.cxx
- Base/QTCore/qSlicerCoreApplication.cxx
- Base/QTCore/qSlicerCoreApplication.h
- Base/QTCore/qSlicerCoreApplication_p.h
Introduces two enhancements to streamline and customize how URI arguments are handled in custom Slicer applications:
* Add `qSlicerCoreApplication::handleURIArguments`.
* Add the ability to enable or disable post-startup URI argument handling.
> ENH: Improve and Customize URI Argument Handling for Custom Applications

- Base/QTCore/qSlicerCoreApplication.cxx
Unparsed arguments may be processed after the application startup (e.g., in scripts or custom applications). Always displaying the list of ignored arguments introduces unnecessary noise in the logs.
Related issues and pull requests:
* https://github.com/Slicer/Slicer/pull/7938
* https://github.com/Slicer/Slicer/issues/7936
> BUG: Remove unneeded display of ignored arguments 

- Libs/MRML/Widgets/qMRMLTransformSliders.cxx
- SuperBuild/External_CTK.cmake
In Transforms module, when rotate-first mode was enabled and edited translation components and the number of digits changed, the value that was being edited was reset. The problem was that when number of digits change then sibling widgets get a notification and they update their number of digits, too, which results in value change, which leads to resetting of all values (including the one that is being edited). Fixed by preventing resetting of the slider+spinbox for the axis that is being edited using the spinbox.
fixes #7574
---
<del>Draft pull request because it requires merging of https://github.com/commontk/CTK/pull/1219</del>
required CTK update was merged and git hash is updated in this pull request
> BUG: Fix editing of transform component values in spinbox

- Base/Python/sitkUtils.py
- Base/Python/tests/test_sitkUtils.py
A fallback mechanism was implemented to keep sitkUtils functional when Slicer's SimpleITK is replaced by a stock SimpleITK (that does not have MRMLIDImageIO). However, this mechanism did not work due to a missing import.
The missing import has been added and a test is now added to check that sitkUtils works with and without MRMLIDImageIO.
fixes #7902
> BUG: Fix sitkUtils without MRMLIDImageIO

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorMaskVolumeEffect.py
Output node selector broke when the scene was closed because node selector parameters changed while the scene was closing. It would be better to make the node selector more robust, but this fix is sufficient to address this specific issue.
fixes #7632
> BUG: Fix output volume node selector in Mask Volume effect

- Base/QTGUI/qSlicerApplication.cxx
Reintroduces the logging of unparsed command-line arguments, now restricted to the log file as debug entries. This allows developers to access the information for debugging purposes without cluttering the terminal output.
* https://github.com/Slicer/Slicer/pull/7941
> ENH: Re-introduce logging of unparsed arguments to log file only

- .github/workflows/ci.yml
Skip the "CI (Build)" workflow if changes to `External_*.cmake` files are detected since the last Preview build. Pull request builds likely require an updated Docker image, which provides external dependencies, and building with outdated dependencies could lead to failures. To avoid this, the CI build is skipped when SuperBuild file changes may require an updated image.
Additionally, since the GitHub action `dorny/paths-filter` does not suppor specifying the `base` input for pull request events, we replaced it with the `tj-actions/changed-files` action. This resolves the warning:
> 'base' input parameter is ignored when action is triggered by pull request event"
Follow-up of https://github.com/Slicer/Slicer/pull/7942#issuecomment-2359422820
> BUG: Skip "CI (Build)" workflow if any SuperBuild changes on "nightly-main"

- Modules/Scripted/DICOMLib/DICOMBrowser.py
- Modules/Scripted/DICOMLib/DICOMUtils.py
- Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Make the default behavior of loading DICOM data consistent between using the GUI and using DICOMUtils Python scripting. Previously, loadSeriesByUID and loadByInstanceUID functions used all available DICOM plugins. Now only those DICOM plugins are used by default that are not disable in the application settings.
fixes #7931
I haven't tested it yet, just created this draft pull request to get quick feedback.
> BUG: Skip disabled plugins when loading DICOM by scripting

- Docs/developer_guide/modules/index.md
- Docs/developer_guide/modules/sequences.md
- Libs/MRML/Core/vtkMRMLSequenceNode.cxx
- Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx
- Modules/Loadable/Sequences/Testing/Python/SequencesSelfTest.py
Labelmap volume sequences were saved the same way as scalar volume sequences, therefore when a labelmap volume sequence was loaded from file, the proxy nodes were all scalar volumes. Fixes by adding "intent: label" field in the .seq.nrrd file header (inspired by NIFTI file format's intent tag).
fixes #7124
> BUG: Fixed saving of labelmap volume sequences

- .github/workflows/update-slicer-preview-branch.yml
This commit fixes issues with the workflow intended to update the "nightly-main" branch daily. It incorporates changes that were originally intended in commit 656350456a ("ENH: Add GitHub workflow to update the 'nightly-main' branch daily", 2024-09-20).
While testing the initial version in the `add-update-preview-branch-workflow` branch, the branch was deliberately forced as the `main` branch in the `Slicer/jcfr` fork. This allowed testing the workflow in a near-final integration context. However, the pull request https://github.com/Slicer/Slicer/pull/7953 was mistakenly created from an out-of-date version of the `add-update-preview-branch-workflow` branch, which this follow-up commit addresses.
The confusion arose from the mistaken assumption that the original pull request[^2] had been …
> BUG: Fix GitHub workflow for daily updates to "nightly-main" branch

- Applications/SlicerApp/Testing/Python/SlicerScriptedFileReaderWriterTest.py
- Base/QTGUI/qSlicerSaveDataDialog.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTextStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTextStorageNode.h
Until now, vtkMRMLTextStorageNode could only store files with txt, xml, and json extensions. Even if a filename was set to something else by a file reader/writer plugin, the storage node can override the filename, for example when saving the scene to .mrb format.
This limitation is now lifted, a custom list of file extensions can be specified for both reading and writing.
This will be used for allowing script storage in the scene - see https://github.com/SlicerMorph/SlicerEditor/issues/44
> ENH: Allow vtkMRMLTextStorageNode to store any text files

- Base/Logic/Testing/vtkSlicerVersionConfigureTest1.cxx
- CMake/vtkSlicerVersionConfigureMinimal.h.in
Added `Slicer_VERSION_NUMBER` and `Slicer_VERSION_NUMBER_COMPUTE(major, minor, patch)` macros to simplify implementation of Slicer extensions that are compatible with multiple Slicer versions.
Previously, Slicer version checks were implemented like this:
```cpp
#if ((Slicer_VERSION_MAJOR == 5 && Slicer_VERSION_MINOR >= 9) || (Slicer_VERSION_MAJOR > 5))
```
The new macros make the code more readable and less error-prone:
```cpp
#if Slicer_VERSION_NUMBER >= Slicer_VERSION_NUMBER_COMPUTE(5, 9, 0)
```
---
By introducing these macros, we can distinguish between Slicer versions 5.7 and above. Code that needs to be compatible with Slicer-5.6 and earlier cannot use these macros.
> ENH: Simplify Slicer version check in extensions

- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationShow3DButton.cxx
"Show 3D" button enabled/disabled state was not updated immediately when the button's "locked" state was updated. The problem was that only a member variable was set, but the button update was not triggered.
fixes https://github.com/Project-MONAI/MONAILabel/issues/1624
> BUG: Fix segmentation Show 3D button staying disabled

- .github/workflows/update-slicer-preview-branch.yml
This commit resolves authentication issues in the "Update Preview Branch" GitHub workflow by ensuring proper credentials are used during checkout. Additionally, the following changes were made to the Slicer repository settings:
- Granted "Slicer App" permission to push to the "nightly-main" branch.
- Updated "Slicer App" permissions to allow read/write access to workflow files.
These changes follow guidelines documented at:
https://github.com/orgs/community/discussions/25305#discussioncomment-8256560
This commit builds upon 58a9a8ce41 ("BUG: Fix GitHub workflow for daily updates to 'nightly-main' branch", 2024-09-20) integrated through https://github.com/Slicer/Slicer/pull/7955, ensuring the workflow is associated with the correct credentials to resolve the following error:
```
remote: …
```
> BUG: Fix GitHub workflow authentication for "Update Preview Branch"

- Base/QTGUI/qSlicerWebPythonProxy.cxx
- Base/QTGUI/qSlicerWebPythonProxy.h
- Base/QTGUI/qSlicerWebPythonProxy_p.h
When using SlicerEditor, long messages are often logged in the terminal, these are helpful during debugging but not in release execution. Enable/disable this logging as needed.
https://github.com/SlicerMorph/SlicerEditor/issues/43
> Control the amount of console output of the python web proxy.

- Base/Python/slicer/ScriptedLoadableModule.py
This PR updates the `runTest` method inside of slicer such that now developers should not need to explicitly define each of their tests in a derived class. Additionally, it includes the usage of the setup and tear down methods, so that it functions the same way it would if you were to run them as unittests.
In the case that a develop wants the tests to run in a specific order or exclude certain tests then they can update the `moduleTestNames` variable.
cc: @jamesobutler
> ENH: Add methods for runTest upgrade

- SuperBuild.cmake
Fixes https://github.com/Slicer/Slicer/issues/7194
Module repository was updated but superbuild hash was not.
> BUG: Update LandmarkRegistration in SuperBuild.cmake

- Modules/Loadable/Terminologies/Widgets/Resources/UI/qSlicerTerminologyNavigatorWidget.ui
- Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
- Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.h
- Many users were confused and annoyed by the single-click multi-selection. This changes that style to ExtendedSelection (single-click change selection, Ctrl or Shift modifies selection)
- Add convenience button for selecting all categories again (although Ctrl+A does it as well but it is not obvious)
> ENH: Improve terminology category selection

- Docs/user_guide/modules/segmentations.md
- Docs/user_guide/modules/transforms.md
- Docs/user_guide/modules/volumes.md
- Modules/Loadable/Segmentations/Resources/UI/qSlicerSegmentationsModule.ui
- Modules/Loadable/Transforms/Resources/UI/qSlicerTransformsModuleWidget.ui
- Modules/Loadable/Volumes/Resources/UI/qSlicerVolumesModuleWidget.ui
As discussed at Slicer hangout today.
There can be confusion that changing the selection of a combobox with label that has the prefix "Active" that it will apply changes to the scene in some way. For examplethere can be confusion that "Active Volume" in the Volume module would change which volume is showing in the layout views, however that is not the case. Changing "ActiveVolume" does not update the selection node using SetActiveVolumeID. Instead this label is just for selecting the volume node for manipulating parameters within the Volumes module widget area only.
| `main` | This PR |
|--------|----------|
|![{1FBD831B-10D1-4753-8F13-484BC0BC780C}](https://github.com/user-attachments/assets/cbe72136-188b-4097-b66b-f24cbcf96028)|![{9E4716B9-9B67-4427-AA24-A30448783FB2}](https://github.com …
> ENH: Remove "Active" prefix from some node selection comboboxes

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorDrawEffect.py
If you are in the "Draw" segment editor effect and click to place one point in the given slice offset and then you scroll to another slice offset, you will be unable to place more draw effect points in that offset. It is confusing because that single point does not create an visual UI element, so you are left confused that you actually had started drawing on another slice offset. You currently have to right-click to apply (which does nothing because there is <2 points) and then you can draw on the new slice offset. 
This was leading to confusion by our group's users. I have added code so that if you have placed a single point and then scroll to another slice offset, then the draw effect's points are cleared/reset. 
I still think it is a little confusing when there are >1 points and the …
> ENH: One draw effect point does not prevent use in other slice offset

- Libs/vtkITK/vtkITKArchetypeImageSeriesReader.cxx
Fixes #7937
See original report here about a dataset being scrambled that loaded well in the 5.6.2 release:
https://discourse.slicer.org/t/regression-in-the-dicom-data-base/37913
This corresponds to the change in behavior described here, where spacing from ITK that used to be 1 is now, for example 5 or -1:
https://github.com/InsightSoftwareConsortium/ITK/issues/4794
Which is believed to be due to the changes here, which was added so that for Secondary Capture files the spacing would be respected if present:
https://github.com/InsightSoftwareConsortium/ITK/pull/4521
However adding this code in GDCM meant that if the SpacingBetweenSlices tag is present, even in a CT, it is being used by ITK to calculate spacing, and also ITKToRAS transforms when trying to orthogonalize the transform.
Since …
> BUG: Regression for scans with negative spacing in DICOM

- CMake/SlicerBlockPlatformCheck.cmake
- Docs/developer_guide/build_instructions/windows.md
This should have been included in https://github.com/Slicer/Slicer/commit/acf3dd47940665869765584564b38439f73ff1d5 as ITK 5.4.0 dropped support for MSVC v141 toolset in https://github.com/InsightSoftwareConsortium/ITK/commit/140f3c249fbb20c4f4a1607e563e19ee9a9cbd78.
> COMP: Drop support for MSVC toolset v141 aka Visual Studio 2017

- Modules/Scripted/WebServer/WebServer.py
This PR adds an OPTIONS request handler in the Webserver module.
This handler creates a response to preflight requests when CORS is enabled, which is required when executing cross-origin requests.
The response content was inspired from MSDN documentation at:
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
Relevant forum discussion:
https://discourse.slicer.org/t/using-webserver-dicomweb-interface-with-ohif-cors-enabled/39736/2
---
To test ->
1. Run a separate OHIF instance (not the built-in one) with the following datasource item in appConfig.js
```js
{...
datasource: [
{
friendlyName: 'Slicer 3D',
namespace: '@ohif/extension-default.dataSourcesModule.dicomweb',
sourceName: 'slicer',
configuration: {
name: 'Slicer',
wadoUriRoot: 'http://localhost:2016/dicom',
qidoRoot: …
```
> BUG: add missing OPTIONS request handler when CORS enabled

- Base/QTApp/qSlicerMainWindow.cxx
- Base/QTApp/qSlicerMainWindow_p.h
- Libs/MRML/Core/vtkMRMLScene.cxx
- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx
When closing the scene or exiting the application a confirmation popup is often displayed that warns that the scene content is changed.
Often this popup did not seem justified (e.g., the scene has just been saved) and there was no way of telling why the popup was displayed (what exactly was modified).
This pull request adds a "Show details" option that can display the list of all modified nodes that should be saved in data files or the scene file:
The pull request also contains a few fixes in detection of node modifications to avoid showing confirmation popups unnecessarily.
> Fix too frequent display of scene modification confirmation popup

- Libs/vtkSegmentationCore/vtkSegmentationConverter.cxx
- Libs/vtkSegmentationCore/vtkSegmentationConverter.h
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.h
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologyType.cxx
- Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyItemDelegate.cxx
- Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
This commit makes terminology code finding more robust and removes unnecessary error messages when loading a segmentation.
- If terminology or anatomic context name is not found then we look for the codes in all available contexts.
- If codes are not available anywhere then we do not display an error when the segmentation is loaded. Only when the unavailable code is attempted to be shown in the terminology selector.
- Made behavior of vtkSlicerModuleLogic::DeserializeTerminologyEntry more clear: now it just parses the terminology string. To get metadata of a terminology entry from all loaded terminology contexts, the vtkSlicerModuleLogic::UpdateEntryFromLoadedTerminologies method can be called.
- When segmentation contained unknown segmentation conversion parameters then an error was …
> ENH: Make terminology code finding more robust

- Docs/user_guide/getting_started.md
Screens are wider today than 15 years ago when this requirement was specified, therefore specifying minimum resolution in 4:3 aspect ratio is not relevant anymore.
See discussion in https://discourse.slicer.org/t/full-screen-issue-with-slicer-on-mac-os-15-0-1/39753/18
> DOC: Update recommended screen resolution in documentation

- SuperBuild/External_DCMTK.cmake
Backport security fixes from the following post https://forum.dcmtk.org/viewtopic.php?t=5192 because of the following CVE:
* [CVE-2022-2119](https://www.cvedetails.com/cve/CVE-2022-2119/)
* [CVE-2022-2120](https://www.cvedetails.com/cve/CVE-2022-2120/)
List of DCMTK changes:
```
$ git shortlog 0f9bf4d9e..11972eaa4 --no-merges
Marco Eichelberg (2):
[Backport] Fixed possible NULL pointer dereference.
[Backport] Fixed path traversal vulnerability.
```
Related issues & pull requests:
* https://github.com/commontk/DCMTK/pull/14
* https://github.com/commontk/CTK/pull/1223
> BUG: Update DCMTK to backport fixes for CVE-2022-2119 and CVE-2022-2120

- Base/QTCore/CMakeLists.txt
- Modules/CLI/PETStandardUptakeValueComputation/CMakeLists.txt
- SuperBuild/External_CTK.cmake
- SuperBuild/External_DCMTK.cmake
- SuperBuild/External_ITK.cmake
This commit updates the DCMTK library to version 3.6.8, incorporating numerous enhancements, bug fixes, and compatibility improvements across ITK, CTK, and DCMTK itself. Notable updates include new support for recent DICOM standards (e.g., DICOM 2024b) and compatibility with cross-compiling. The upgrade also addresses several compilation warnings, improves performance, and enhances TLS support and error handling.
Additionally:
* Removed the `DCMTK_WITH_ICU` option, which became obsolete in commit DCMTK/dcmtk@b8e5fd510 ("Removed support for ICU-based charset conversion.", 2024-05-25).
* Removed the `DCMTK_ENABLE_BUILTIN_DICTIONARY` option, obsolete since  commit DCMTK/dcmtk@4ab084d3f ("Harmonize dictionary options.", 2021-09-01), and set `DCMTK_DEFAULT_DICT` instead.
* Fixed building DCMTK …
> ENH: Update DCMTK from 3.6.6 to 3.6.8

- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerROIRepresentation2D.h
Contour triangulation would occasionally fail in some views depending on view orientation.
This was due to a failure in vtkContourTriangulator. Adding vtkCleanPolyData before vtkContourTriangulator in the pipeline fixes the issues.
Fix #7944
> BUG: Fix missing Markups ROI fill in some views

- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyAbstractPlugin.h
- Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.cxx
- Modules/Loadable/Transforms/SubjectHierarchyPlugins/qSlicerSubjectHierarchyTransformsPlugin.h
Transform related functions were originally not included into a specific plugin. Thus some functionalities related to the management of plugins were not available.
Fix https://github.com/Slicer/Slicer/issues/6621
> ENH: Add a transform plugin in subject hierarchy tree view

- Libs/MRML/IDImageIO/itkMRMLIDImageIO.cxx
- Libs/MRML/IDImageIO/itkMRMLIDImageIO.h
This commit removes the unused virtual functions `CanUseOwnBuffer`, `ReadUsingOwnBuffer`, and `GetOwnBuffer` from `MRMLIDImageIO`. These functions were originally introduced in Slicer through commit `bc99a8cfc1` ("ENH: Modify ITK MRML image reader to re-use buffer when possible", 2010-11-15).
The API was initially added to ITK via InsightSoftwareConsortium/ITK@2ffb32de2f ("ENH: Modify ITK image reader to re-use buffer when possible", 2010-11-15) on the `Slicer4UpdatesToITKv3.20` branch, which was later merged into ITK's `release` branch in commit InsightSoftwareConsortium/ITK@d4d43abf60 ("Merge branch 'Slicer4UpdatesToITKv3.20' into release", 2011-10-24).
Despite a subsequent merge of the `release` branch back into the ITK development branch via commit …
> STYLE: Remove unused MRMLIDImageIO API

- SuperBuild/External_ITK.cmake
This update to ITK prevents the logging of hundreds of messages like the following:
> "TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered".
These warnings typically occur when reading a volume from a TIFF file list containing custom tags. Since custom tags are harmless, suppressing these warnings helps prevent console or application log flooding, which can slow own image loading and obscure more important messages.
```
$ git shortlog --no-merges 07eb5d0d6d..5e147295f3
[Backport MR-4909] ENH: Suppress irrelevant TIFF warnings
```
Related issues & pull requests:
* https://github.com/InsightSoftwareConsortium/ITK/pull/4909
* https://github.com/SlicerMorph/SlicerMorph/issues/320
Closes #7994
> PERF: Update ITK to suppress irrelevant TIFF warnings

- Applications/SlicerApp/qSlicerAppMainWindow.cxx
- Applications/SlicerApp/qSlicerAppMainWindow.h
- Modules/Loadable/SlicerWelcome/Resources/UI/qSlicerWelcomeModuleWidget.ui
The 3DSlicerApp account on X.com (formerly Twitter) has not been active since March 2023. LinkedIn continues to be a focused place for researchers to post about their work in an academic/professional setting unlike X.com that covers a wide spectrum of topics. Therefore LinkedIn may be considered more appropriate for connecting researchers to others in more helpful ways.
Previously discussed in https://discourse.slicer.org/t/social-media-presence-moving-away-from-twitter/30433/8.
See joint PR to update the Slicer website with similar change:
https://github.com/Slicer/slicer.org/pull/285
> ENH: Switch highlighted social network to LinkedIn

- Libs/MRML/Core/vtkMRMLTextStorageNode.cxx
When the storage node was unable to open the file for some reason (ex. due to a file name that is too long), the storage node did not report an error, and returned success. Fixed by checking that the file was succesfully opened with std::ofstream::is_open and returning with failure if it isn't open.
> BUG: Fix vtkMRMLTextStorageNode::WriteDataInternal not throwing error

- Modules/Scripted/SegmentStatistics/SegmentStatistics.py
- Modules/Scripted/SegmentStatistics/SegmentStatisticsPlugins/ScalarVolumeSegmentStatisticsPlugin.py
Added option to compute 5th, 10th, 90th, 95th percentile values in Segment Statistics module's Scalar Volume plugin.
Discussion that motivated implementation of this feature: https://discourse.slicer.org/t/why-did-the-segment-created-by-threshold-masking-contain-voxels-beyond-the-threshold/40123
> ENH: Added percentiles computation to Segment Statistics scalar volume plugin

- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsInteractionWidgetRepresentation.cxx
The plane interaction handles and scalar arrays were initialized with an incorrect number of points. Later calls to UpdatePlaneScaleHandles set the number of points correctly, but don't update the scalar arrays to the correct size. This rarely caused a crash when trying to call GetInteractionHandlePositionWorld with an index that was out of range.
Fixed by initializing scale handles with the correct number of points, and by checking to make sure the index is valid in GetInteractionHandlePositionWorld before calling vtkPolyData::GetPoint().
> BUG: Fix incorrect plane interaction scale handles initialization

- Libs/MRML/Core/Testing/vtkMRMLSceneViewNodeTest1.cxx
- Libs/MRML/Core/vtkMRMLCoreTestingMacros.h
This commit is follow-up of 9b8c82356b ("BUG: Revert invalid -Wdeprecated-declarations fix in TEST_SET_GET_STRING", 2023-11-24) and is intended to fix warnings like the following by adding `TEST_SET_GET_STD_STRING` MRML testing macro to explicitly test set/get of `std::string` (instead of relying on the deprecated operator const char*().
Warning fixed:
```
Slicer/Libs/MRML/Core/Testing/vtkMRMLSceneViewNodeTest1.cxx:
In function ‘int vtkMRMLSceneViewNodeTest1(int, char**)’:
Slicer/Libs/MRML/Core/vtkMRMLCoreTestingMacros.h:328:62:
warning: ‘vtkStdString::operator const char*()’ is deprecated: Call `.c_str()` explicitly [-Wdeprecated-declarations]
const char * originalStringPointer = object->Get##variable();
```
* https://github.com/Slicer/Slicer/pull/7401 
* …
> COMP: Resolve deprecated warning in MRML testing macro for std::string

- Libs/MRML/Core/vtkMRMLViewNode.h
- Libs/MRML/Logic/vtkMRMLViewLinkLogic.cxx
- Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLThreeDView.cxx
- Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx
- Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
- Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h
Rename all occurrences of `Visibile` to `Visible` (for example `savedBoxVisibile` -> `savedBoxVisible`)
> STYLE: Fix typo replacing Visibile with Visible

- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsTableView.cxx
Clicking on the eye icon in segment list had no effect. It was due to a typo that got into the code a few days ago.
fixes #8047
> BUG: Fix visibility column in segment list

- Base/QTCore/Testing/Cxx/CMakeLists.txt
- Base/QTCore/Testing/Cxx/qSlicerCoreIOManagerTest1.cxx
- Base/QTCore/qSlicerCoreIOManager.cxx
- Base/QTCore/qSlicerCoreIOManager.h
- Base/QTGUI/qSlicerExportNodeDialog.cxx
- Base/QTGUI/qSlicerSaveDataDialog.cxx
- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.h
When saving nodes with long names on Windows, the file creation and writing would be unsuccessful. Since the error was at the system level, the error message would often be unhelpful for the user.
This PR clamps filename length for nodes with long names using `vtkMRMLScene::ClampFileNameLength`.
The format of the clamped string is:
```
[prefix of first 20 characters of the base name]_[4 character hash code].[extension]
```
The remaining characters after the suffix are used to seed the random number generator used to create the hash code.
Re #7901
> BUG: Fix saving with long node names

- Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx
Fix bug introduced in d6f6b7d.
The backface color for slice nodes in 3D was set from the display node color, causing the slice backface to be colored using the slice color. Fixed by getting the backface color from the frontface actor property instead.
Fix #8055
> BUG: Fix backface color on Slice nodes in 3D views

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorThresholdEffect.py
- Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager2D.cxx
- Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager2D.h
If Slicer is restarted while thresholding preview was active, the segment was no longer visible. This was due to that the segmentation display node was temporarily modified to make the segment transparent (to make threshold preview visible), and this modification was saved into the scene.
Fixed by adding API to the segmentation displayable manager to allow specifying a custom renderer for a segment. This allows temporarily hiding a segment so that it can be displayed by custom rendering. The implementation is cleaner, because:
- no temporary change of MRML nodes are needed (therefore an incorrect state cannot be persistently applied).
- whenever we add/remove a custom actor to the renderer we also add/remove custom rendering for that segment in the displayable manager (previously these …
> BUG: Fix segments not visible after thresholding

- Libs/MRML/Core/vtkMRMLClipNode.cxx
Fixes typo in vtkMRMLClipNode.
> STYLE: Fix typo replacing clipingState with clippingState

- Schemas/slicer-extension-catalog-entry-schema-v1.0.1.json
This is the first step towards introducing tiers for extensions.
see #7474
> ENH: Add "tier" property to extensions catalog schema

- Modules/Loadable/Transforms/MRMLDM/vtkMRMLLinearTransformsDisplayableManager.cxx
After OnMRMLSceneEndBatchProcess was called, UpdateFromMRMLRequested was called, but RequestRender was not. This meant that the widget would not be updated until the user tried to mouse over the widget. This caused a crash in ProcessInteractionEvent, since the activeWidget was deleted during processing as UpdateFromMRML was resolved.
Fixed by:
- Calling RequestRender after SetUpdateFromMRMLRequested(True) in OnMRMLSceneEndClose() and OnMRMLSceneEndBatchProcess().
- Using vtkSmartPointer for activeWidget in ProcessInteractionEvent so that the pointer to the active widget can't be made invalid.
> BUG: Fix crash when hovering over interaction handles after scene load

- Modules/Scripted/DICOMLib/DICOMBrowser.py
This fixes an issue described within this forum post: https://discourse.slicer.org/t/hanging-popup-some-times-after-loading-dicom-files/6057.  There is a dialog progress popup that appears when attempting to load a DICOM file from the DICOM browser that remains on screen after the load as completed. The original post submitter only had issues intermittently. Using Slicer within [Xpra](https://github.com/Xpra-org/xpra) I was experiencing it consistently and this code change resolved the issue.
> BUG: Fix hanging progress popup in DICOM browser

- Modules/Scripted/DICOMLib/DICOMBrowser.py
- Modules/Scripted/DICOMLib/DICOMUtils.py
The loadable warning flag can be used to manage loading failure if not empty
> ENH: Add loadable warning in case of loading failure

- Base/QTGUI/Resources/UI/qSlicerSettingsViewsPanel.ui
- Base/QTGUI/qSlicerSettingsViewsPanel.cxx
- Libs/MRML/Core/vtkMRMLSliceNode.cxx
- Libs/MRML/Core/vtkMRMLSliceNode.h
- Libs/MRML/DisplayableManager/CMakeLists.txt
- Libs/MRML/DisplayableManager/vtkMRMLAbstractThreeDViewDisplayableManager.cxx
- Libs/MRML/DisplayableManager/vtkMRMLAbstractThreeDViewDisplayableManager.h
- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidgetRepresentation.cxx
- Libs/MRML/DisplayableManager/vtkMRMLInteractionWidgetRepresentation.h
- Libs/MRML/DisplayableManager/vtkMRMLSliceEdgeWidgetRepresentation.cxx
- Libs/MRML/DisplayableManager/vtkMRMLSliceEdgeWidgetRepresentation.h
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.cxx
- Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionInteractionRepresentation.h
- Libs/MRML/DisplayableManager/vtkMRMLThreeDSliceEdgeDisplayableManager.cxx
- Libs/MRML/DisplayableManager/vtkMRMLThreeDSliceEdgeDisplayableManager.h
- Libs/MRML/Logic/vtkMRMLSliceLinkLogic.cxx
- Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui
- Libs/MRML/Widgets/Testing/qMRMLThreeDViewTest1.cxx
- Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLSliceControllerWidget.h
- Libs/MRML/Widgets/qMRMLThreeDView.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx
- Modules/Loadable/ViewControllers/qSlicerViewControllersModule.cxx
- Implemented functionality to show slice edges in the 3D view.
- Added user interface controls to control the visibility of slice edges.
- Implemented linking controls to synchronize the visibility of slice edges across different views.
Reference: https://discourse.slicer.org/t/show-slice-edges-in-3d-view/11381
> ENH: Add option to display slice edges in 3D view

- Libs/MRML/Core/vtkMRMLSliceDisplayNode.cxx
IntersectingSlicesLineThicknessMode was written to the xml file as intersectingSlicesIntersectionMode, causing duplicate attributes in the vtkMRMLSliceDisplayNode element.
> BUG: Fix incorrect vtkMRMLSliceDisplayNode XML attribute name

- Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx
- Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.h
Folder opacity/color was broken in d6f6b7dbc2f797f8189b91b583d201dffd76d825.
Fixed by using overriding display node rather than model display node for applicable properties. Fixes failing py_nomainwindow_SubjectHierarchyFoldersTest1 test.
> BUG: Fix folder display override for model nodes

- Modules/CLI/ExecutionModelTour/ExecutionModelTour.xml
- SuperBuild/External_SlicerExecutionModel.cmake
- Utilities/Templates/Modules/CLI/TemplateKey.xml
This should spare someone else from the same issue I encountered [here](https://github.com/Slicer/SlicerExecutionModel/issues/140) by changing the input and output image from positional to flag argument.
> `longflag` is required, `name` is optional in SEM XML

- Extensions/CMake/SlicerBlockBuildPackageAndUploadExtensions.cmake
On Windows, cmake.exe path usually contain space (e.g., "C:/Program Files/CMake/bin/cmake.exe"). If such a string is passed to execute_process as COMMAND directly then the command returns "no such file or directory" error (due to "C:/Program" is not found).
Fixed by converting the semicolon-separated string to a list and using that list as COMMAND.
> BUG: Fix ExtensionsIndex build

- Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui
This closes #8085.
See https://github.com/Slicer/Slicer/issues/8085#issuecomment-2532674962 for more details.
This was accidentally included in https://github.com/Slicer/Slicer/commit/bf0f921a7191415ac18b6e7015039e60b5943f91 and caused issues with the Segmentation layer confusingly not being present until the popup widget was expanded again.
> BUG: Fix slice view more options open by default

- SuperBuild/External_LibArchive.cmake
Fix build errors caused by warnings treated as errors when using
Clang 16. The compiler reports implicit truncation for single-bit
signed bitfields that can only hold values -1 and 0.
Example error:
```
libarchive/archive_write_set_format_7zip.c:1541:13: error: implicit
truncation from 'int' to a one-bit wide bit-field changes value from 1
to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
file->dir = 1;
^ ~ 
```
Affected files include:
- `libarchive/archive_write_set_format_xar.c`
- `libarchive/archive_write_set_format_iso9660.c`
- `libarchive/archive_write_set_format_7zip.c`
Cherry-picked upstream commit libarchive/libarchive@f180dca into the
`Slicer/libarchive` fork on branch `slicer-v3.6.1-2022-04-08-6c3301111`.
The external project now fetches the updated version of libarchive …
> COMP: Fix libarchive build error when using Clang 16

- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
- Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.h
This adds supports for customizing interaction widget event translation specifically for Markups such as the vtkMRMLMarkupsROINode. This is necessary based on the changes made since Slicer 5.6.2 as discussed in https://github.com/Slicer/Slicer/issues/8099.
The below example exhibits the ability to remove the jump slice offset functionality upon single left-clicking on the center translation ROI handle and also on the outer scale ROI handles.
```python
SampleData.SampleDataLogic().downloadMRHead()
roi_node = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsROINode")
roi_node.SetSize(100, 100, 100)
roi_display_node = roi_node.GetDisplayNode()
sliceViewLabel = "Red"
sliceViewWidget = slicer.app.layoutManager().sliceWidget(sliceViewLabel)
displayableManager = …
```
> ENH: Support customizing interaction widget event translation

- Docs/conf.py
Setting the github repository explicitly allows locally generated documentation look the same as that is generated by readthedocs.
> DOC: Set github repository information for documentation generation

- Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
Fix an issue originally introduced in 169df52840 ("ENH: Fix 3943 and other enhancements for slice view annotations", 2015-02-24)
> BUG: Ensure background SeriesTime corner annotation is displayed

- Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
Follow-up on 33131a514d ("ENH: Add Slice Annotations to DataProbe module", 2014-08-22) where the typo was originally introduced.
> STYLE: Fix typo associated with SliceAnnotations property name

- Libs/MRML/DisplayableManager/vtkMRMLModelDisplayableManager.cxx
* Fix vtkMRMLModelDisplayableManager crash if added model display node doesn't derive from vtkMRMLModelDisplayNode
> BUG: Fix Model DM crash when adding display node

- Base/QTCore/qSlicerSceneBundleReader.cxx
- Modules/Scripted/SampleData/SampleData.py
Previously, the scene reader did not report loaded nodes, leading to
incorrect detection of scene loading failures. This commit ensures
that newly loaded nodes are properly tracked and reported.
Additionally:
- Improved the `SampleDataLogic.loadNode` API to return the first loaded node or the scene if no specific node is reported.
- Refactored `SampleDataLogic.loadScene` to reuse `loadNode`, ensuring consistent behavior.
- Improved `SampleDataLogic.downloadFromSource` to not require node name and file name (it can generate it automatically from the URL)
> BUG: Ensure MRB loading correctly reports loaded nodes

- Modules/Scripted/SampleData/SampleData.py
This commit adds "Custom data download" section to the bottom of Sample Data module. It makes it easier to download data sets when following tutorials: the user does not have to use the web browser, find the downloaded file, or drag the file to the application window, just copy-paste the download URL into the inputbox and hit Enter.
@muratmaga you may find this useful for your tutorials
> ENH: Add option to download sample data from custom URL

- Utilities/Doxygen/CMakeLists.txt
- Utilities/Doxygen/Doxyfile.txt.in
Summary:
* Update minimum required Doxygen version from `1.8.4` to `1.10.0` & migrate associated `Doxyfile.txt.in` configuration file running `doxygen -u /path/to/Slicer/Utilities/Doxygen/Doxyfile.txt.in`
* Speed-up doxygen generation enabling parallel build settings `DOT_NUM_THREADS` to `0` to parallelize the build based on the number of available processor and `DOT_MULTI_TARGETS` to `YES` to allow dot to generate multiple output files in one run.
This pull request was created while working on the following issue:
* https://github.com/Slicer/Slicer/issues/7807
> ENH: Speed-up doxygen generation enabling parallel build

- Modules/Scripted/DICOMLib/Logic/vtkSlicerDICOMLoadable.cxx
- Modules/Scripted/DICOMLib/Logic/vtkSlicerDICOMLoadable.h
- Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMLoadable.cxx
- Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMLoadable.h
SlicerRT is unable to load DICOM-RT files successfully without it.
> ENH: Adds loadSuccess flag to loadable Qt and VTK DICOM classes

- .github/workflows/trigger-doxygen-build-and-publish.yml
This commit introduces the `trigger-doxygen-build-and-publish.yml` workflow, which triggers the `doxygen-build-and-publish.yml` workflow maintained in the `Slicer/apidocs.slicer.org` repository. The trigger occurs whenever the `main` branch is updated or a new tag is pushed, resulting in the build and publication of the corresponding Doxygen documentation at https://apidocs.slicer.org.
For security reasons, this workflow is not triggered by the `pull_request` event. This restriction prevents untrusted code from exploiting short-lived tokens with elevated permissions. The workflow internally configures a dummy CMake project that includes the `Utilities/Doxygen` sub-directory, which could otherwise expose sensitive information if executed with arbitrary code.
---
| Use case | …
> ENH: Add GitHub workflow to trigger Doxygen build and publish

- .github/workflows/trigger-doxygen-build-and-publish.yml
Follow-up of commit e6b2ab6265d ("ENH: Add GitHub workflow to trigger Doxygen build and publish", 2025-01-17).
> COMP: Fix manual trigger of Doxygen build and publish through GitHub UI

- SuperBuild.cmake
This commit updates the version of SlicerSurfaceToolbox to include:
* A new Dynamic Modeler Extrude tool.
* A fix for uniform remeshing, addressing installation issues with specific `pyacvd` versions.
Certain versions of `pyacvd` (prior to 0.3.1) required OpenCV, which caused compatibility issues on systems without OpenCV binaries installed. To ensure smooth operation, the updated SurfaceToolbox now installs a compatible `pyacvd` version if (1) The package is missing, or (2) OpenCV dependencies are unavailable. For further details, see https://discourse.slicer.org/t/surface-toolbox-of-3d-slicer-do-not-work-in-windows/40717/4
List of SlicerSurfaceToolbox changes:
```
$ git shortlog 09d5bf6..e8b8f70 --no-merges
Add Extrude tool to dynamic modeler
Mauro I. Dominguez (2): …
```
> ENH: Update SlicerSurfaceToolbox to include dynamic modeler extrude tool

- SuperBuild/External_SlicerExecutionModel.cmake
This update resolves a termination fault that occurs when running the CLI executable built with a newer MSVC runtime on systems with older runtime libraries.
By explicitly including the runtime libraries, compatibility is ensured, avoiding reliance on the system's default runtime version.
List of SlicerExecutionModel changes:
```
$ git shortlog 0e28e41aa..91b921bd5 --no-merges
COMP: Include system runtime libraries
```
> COMP: Include runtime libraries to ensure compatibility in SlicerExecutionModel

- Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.cxx
Anticipating the relocation of Markups nodes into `Libs/MRML/Core`, this commit removes the include of `vtkMRMLMarkupsROIJsonStorageNode.h` from `vtkMRMLMarkupsROINode.cxx`.
This is consistent with how `vtkMRMLMarkupsPlaneNode` and `vtkMRMLMarkupsNode` are implemented.
> COMP: Remove explicit dependency of MarkupsROINode on JSON storage node

- Base/Logic/vtkDataIOManagerLogic.cxx
- Libs/MRML/Core/vtkMRMLColorTableNode.cxx
- Libs/vtkTeem/vtkTeemNRRDReader.cxx
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.h
- SuperBuild/External_OpenSSL.cmake
Fix typos flagged by the `codespell.yml` workflow, which uses the `codespell-project/actions-codespell` GitHub action. This action does not pin the version of `codespell`, and a new release (2.4.0) introduced changes requiring updates to the workflow and typo fixes.
See https://github.com/codespell-project/codespell/releases/tag/v2.4.0
> COMP: Add support for codespell 2.4.0 and fix identified typos

- Libs/MRML/Core/vtkMRMLScene.cxx
> [!IMPORTANT]
> This should be rebased & integrated after the following pull requests are themselves integrated:
> * https://github.com/Slicer/Slicer/pull/8153
Streamline introduction of new node types by standardizing on a defined registration order.
> ENH: Deterministically register nodes in MRML scene constructor

- Base/QTApp/qSlicerApplicationHelper.cxx
Suppresses warnings like the following reported at application startup on macOS:
```
Populating font family aliases took 108 ms. Replace uses of missing font family "Courier" with one that exists to avoid this cost.
```
The root issue, tracked in QTBUG-98369 and QTBUG-99216, has been resolved in newer Qt versions (see qt/qtbase@64dd5a818). This commit conditionally applies a workaround to address the warning for older Qt versions.
> BUG: Suppress "Populating font family aliases" warning on macOS

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Libs/MRML/Logic/vtkMRMLSliceLogic.h
This pull request improves code maintainability by alphabetically sorting includes, removing unused forward declarations and includes, and simplifying dependencies in `vtkMRMLSliceLogic`.
Removed forward declarations:
- `vtkImageData`: Became obsolete after f20a21f ("STYLE: Remove VTKv5 support", 2015-12-01).
- `vtkTransform`: Became obsolete after e339590 ("STYLE: Removed unused variable in vtkMRMLSliceLogic", 2022-03-26) and dc9683a ("STYLE: Removed unused vtkMRMLSliceLogic::ActiveSliceTransform member", 2018-05-09).
Removed unused includes:
- `vtkImageResample.h`: Originally introduced in 01ffcb5 ("ENH 9124. Added new options for displaying slice models in 3D views: [...]") to support `vtkImageResliceMask`. Later removed in 154c6d2 ("ENH: Use the latest vtkImageReslice filter instead …
> Clean up includes and forward declarations in vtkMRMLSliceLogic

- Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx
- Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h
This pull request improves code maintainability by alphabetically sorting includes, removing unused forward declarations and includes, and simplifying dependencies in  `vtkSlicerMarkupsLogic`.
Removed unused includes:
* `vtkMRMLSliceCompositeNode.h`: Became obsolete after bc5d5b45fcb ("ENH: Add interactive slice intersections widget", 2021-07-06)
* `vtkMRMLMarkupsStorageNode.h`: Became obsolete after 936675ac035 ("ENH: Simplify custom markups registration and clean up code", 2021-12-15)
* `vtkMRMLAnnotationSnapshot[Storage]Node.h`: Introduced in f44849b014e ("ENH: Remove Annotations module", 2022-09-10) but never used.
> Clean up includes and forward declarations in vtkSlicerMarkupsLogic

- Modules/Scripted/SampleData/SampleData.py
This pull request modifies the `SampleDataTest` to account for changes introduced in commit 89104423af8 ("BUG: Ensure MRB loading correctly reports loaded nodes", 2025-01-10) through the following pull request:
* https://github.com/Slicer/Slicer/pull/8135
These changes ensure correct behavior verification:
- `test_downloadFromSource_downloadFiles`: Added `loadFiles=False` to disable file loading during download tests.
- `test_downloadFromSource_downloadZipFile`: Set `loadFileType` to "ZipFile" to verify only downloading without attempting to load.
- `test_downloadFromSource_loadMRBFile`: Updated assertions to validate returned node behavior, accounting for fixed MRB loading behavior.
- `test_downloadFromSource_downloadMRBFile`: Set `loadFileType` to "SceneFile" to ensure correct behavior …
> BUG: Fix SampleData tests to align with revised file loading behavior

- Modules/Scripted/SampleData/SampleData.py
This enhancement builds on commit 89104423af8 ("BUG: Ensure MRB loading correctly reports loaded nodes", 2025-01-10), ensuring that if a filename is explicitly specified, it is used to initialize the node name instead of defaulting to the filename derived from the URI.
The `SampleDataLogic.downloadFromSource` method now prioritizes the specified `fileName` when determining the node name, defaulting to deriving the name from the URI only when no `fileName` is provided.
Two new test cases validate that node names are correctly initialized based on explicitly specified filenames or, in their absence, the corresponding file names for single or multiple files.
* https://github.com/Slicer/Slicer/pull/8135
* https://github.com/Slicer/Slicer/pull/8162
> ENH: Use specified filename as node name in SampleDataLogic.downloadFromSource

- Applications/SlicerApp/Testing/Python/DICOMReaders.py
- Applications/SlicerApp/Testing/Python/JRC2013Vis.py
- Applications/SlicerApp/Testing/Python/RSNAQuantTutorial.py
- Applications/SlicerApp/Testing/Python/RSNAVisTutorial.py
- Applications/SlicerApp/Testing/Python/ScenePerformance.py
- Applications/SlicerApp/Testing/Python/SlicerRestoreSceneViewCrashIssue3445.py
- Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyGenericSelfTest.py
This commit updates several self-tests to explicitly define `loadFileTypes` or `loadFiles`, as required following commit 89104423af8 ("BUG: Ensure MRB loading correctly reports loaded nodes", 2025-01-10) introduced the following pull request:
* https://github.com/Slicer/Slicer/pull/8135
Tests updated with `loadFileTypes="ZipFile"` to ensure proper handling of zip files:
- `DICOMReaders`
- `JRC2013Vis`
- `RSNAQuantTutorial`
- `RSNAVisTutorial`
The `SubjectHierarchyGenericSelfTest` was updated with `loadFileTypes="SceneFile"` to handle scene files explicitly.
Tests updated with `loadFiles=False` to disable automatic file loading:
- `ScenePerformance`
- `SlicerRestoreSceneViewCrashIssue3445`
> BUG: Fix self-tests by explicitly setting file loading parameters

- SuperBuild/External_python.cmake
- SuperBuild/python_configure_manylinux_module.cmake
This commit introduces the ability to configure a `_manylinux` module in the Slicer build system to enhance compatibility when installing binary Python wheels.
This update resolves potential issues with installing Python wheels built for newer GLIBC versions or ABIs, which could cause crashes in environments with older configurations.
Specifically, installing `manylinux_2_28_x86_64` ITK wheels compiled with `_GLIBCXX_USE_CXX11_ABI=1` was causing segmentation faults in the _Stable_ Slicer version, which is compiled with `_GLIBCXX_USE_CXX11_ABI=0`. The `_manylinux` module ensures that `manylinux_2_17_x86_64` ITK wheels are always installed, even when Slicer and its associated Python interpreter are executed on newer operating systems.
The `_manylinux.py` module is dynamically generated …
> BUG: Add support for configuring `_manylinux` module

- SuperBuild/External_python.cmake
Summary:
- Add support for building CPython 3.9.17
- Add checksums for Python 2.7.16 to 2.7.18 and 3.7.x, 3.8.x, and 3.9.x
- cmake: Fix various configuration issues and update default version to 3.9.17
- cmake: Rename `USE_SYSTEM_FFI` to `USE_SYSTEM_LibFFI` for consistency
- cmake: Fix name of `USE_SYSTEM_SQLite3` option
- cmake: Prevent rebuilds by ensuring `SRC_DIR` is always an absolute path
```
$ git shortlog bb45aa7a4..48aee12 --no-merges
Brett Jia (2):
cmake: Fix name of USE_SYSTEM_SQLite3 option
cmake: Fix use of system libmpdec (#340)
Erlend E. Aasland (2):
README: Fix broken Ninja link
cmake: Add missing checksums for Python 3.7.x, 3.8.x, and 3.9.x
James Butler (2):
ci: Test latest patch release versions
cmake: Update default version to 3.9.17
Jean-Christophe …
```
> COMP: Update python-cmake-buildsystem anticipating python version update

- Docs/developer_guide/advanced_topics.md
- Docs/developer_guide/modules/transforms.md
- Docs/developer_guide/python_faq.md
- Docs/developer_guide/script_repository/volumes.md
This pull request updates links referencing the outdated `https://www.slicer.org/doc/html` to the current `https://apidocs.slicer.org/main`.
**Next Steps:**
We plan to implement a systematic mechanism to dynamically generate documentation links based on the corresponding ReadTheDocs version, addressing #7119.
> DOC: Fix links to slicer doxygen in the developer guide

- Docs/conf.py
- Docs/developer_guide/advanced_topics.md
- Docs/developer_guide/modules/transforms.md
- Docs/developer_guide/python_faq.md
- Docs/developer_guide/script_repository/volumes.md
This pull request introduces a systematic mechanism to generate Doxygen documentation links dynamically, aligning with the ReadTheDocs version of the project.
- Extracts `<major>.<minor>` version information from the top-level `CMakeLists.txt`.
- Updates `conf.py` to construct Doxygen links dynamically for either the release or main branch based on the minor version parity:
- **Odd minor versions**: Links to the corresponding Preview documentation (`/main` sub-directory).
- **Even minor versions**: Links to the corresponding Stable documentation sub-directory (e.g., `/X.Y`).
- Implements a custom URL scheme `slicerapidocs` to facilitate consistent and version-specific cross-referencing in Markdown files.
Closes #7119
> DOC: Dynamically generate links to slicer doxygen based on ReadTheDocs version

- Docs/developer_guide/extensions.md
- Docs/developer_guide/module_overview.md
- Docs/developer_guide/style_guide.md
Updates to various broken links across the Slicer docs.
There exist other broken links not fixed by this PR, since the resolution for these cases is less clear (like companies/products/tools/papers that no longer exist online).
> BUG: Fix various broken documentation links in developer guide

- SuperBuild/External_VTK.cmake
```
$ git shortlog 57bacae7e9..492821449a --no-merges
Jaswant Panchumarti (1):
[Backport] Fix undefined variable name in octree_node
```
VTK References:
- Issue: https://gitlab.kitware.com/vtk/vtk/-/issues/19358
- Merge Request: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11178 mentioned this came up due to a newer clang.
> COMP: Update VTK backporting fix to support building on Linux with clang

- Base/QTGUI/qSlicerApplication.cxx
https://doc.qt.io/qt-5/qapplication.html#windowIcon-prop
Defining the QApplication window icon sets the default window icon. Slicer currently sets the QMainWindow window icon which is primarily used for windows that are children of the main window. Before this commit the QApplication window icon was undefined so no icon was used for a widget with no parent.
| `main`  | This PR |
|---------|---------|
|![{9738F05D-BFF0-4C2C-A512-300FEE842AE3}](https://github.com/user-attachments/assets/52e20125-2dd3-4fea-a796-645d7f0403f4)|![{68C46A8D-C1AC-43EF-B2EF-A7DBA0E95F39}](https://github.com/user-attachments/assets/0a2a748c-e65c-40f4-b5b3-887504ef3409)|
> ENH: Define a window icon for all windows 

- Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsStorageNodeTest2.cxx
- Modules/Loadable/VolumeRendering/Testing/Cxx/vtkMRMLVolumeRenderingDisplayableManagerTest1.cxx
This commit resolves issues in the following tests caused by a regression introduced in commit d919d2fd693 ("COMP: Move classes from Modules/Loadable/Markups/MRML to Libs/MRML/Core", 2025-01-21):
- `vtkMRMLVolumeRenderingDisplayableManagerTest1`
- `vtkMRMLMarkupsStorageNodeTest2`
The regression resulted from redundant calls to `RegisterNodeClass`. Since these nodes are now part of the core, they are automatically registered in `vtkMRMLScene`. The explicit registrations are no longer necessary and have been removed.
This resolves errors like the following:
```
426: 2025-01-26 18:58:38.183 (   0.260s) [        A9A39980]       vtkMRMLScene.cxx:574   WARN| vtkMRMLScene (0x563228bb7d20): Tag MarkupsROI has already been registered, unregistering previous node class vtkMRMLMarkupsROINode to …
```
> BUG: Fix duplicated registration of Markups node in tests

- CMake/SlicerDashboardDriverScript.cmake
Address the issue mentioned in:
- #7825 
Moved the building of TARGET `packageupload` under the condition that `run_ctest_with_upload` is true.
The condition `run_ctest_with_packages` is already true under the situated code (the outer if condition).
closes #7825
> COMP: Ensure setting `run_ctest_with_upload` to `FALSE` skips package upload

- Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake
Resolves https://github.com/Slicer/Slicer/issues/7721.
The `EXTENSION_CONTRIBUTORS` argument to the function [`slicerFunctionGenerateExtensionDescription()`](https://github.com/Slicer/Slicer/blob/80c243f06764d81b0dbb7d40ef4832baf7296f8f/Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake#L32-L130) now supports both a string input with the contributors names (to be joined by `, `), as well as a CMake list of the contributors, still applying suitable whitespace stripping. The test for this function has been updated to verify both cases.
> ENH: Support specifying extension contributors as CMake list

- SuperBuild.cmake
List of BRAINSTools changes:
```
$ git shortlog d88a4f43..7c37d9e8 --no-merges
Hans J. Johnson (22):
ENH: Update to VTK 9.3 to support builds on newer m3 mac.
COMP: ITKv5.4.0 requires C++17 features.
ENH: Update to newer versions of python packages
ENH: Checks for toml xml yaml
ENH: Add shabang for executable files, remove execute permissions
ENH: Fixed end-of-file inconsistencies.
ENH: Enforce rigors end of line symantics
ENH: Adding python tests naming consistency.
ENH: forbid new submodules
ENH: Initial ruff code fixes for safe code updates.
ENH: Code cleanups for comparison to bool values
ENH: Modernize codebase with pyupgrade to 3.10 syntax recommendations.
ENH: Prepratory shell check comments that will need more work before using.
ENH: Need slightly larger tolerance for m3 native …
```
> ENH: Update BRAINSTools from 2024-05-31 to 2024-11-09

- Base/CLI/itkPluginUtilities.h
- Extensions/Testing/CLIExtensionTemplate/CLIModuleTemplate/CLIModuleTemplate.cxx
- Extensions/Testing/SuperBuildExtensionTemplate/SuperCLIModuleTemplate/SuperCLIModuleTemplate.cxx
- Libs/MRML/IDImageIO/itkMRMLIDImageIO.cxx
- Libs/vtkITK/vtkITKArchetypeImageSeriesReader.cxx
- Libs/vtkITK/vtkITKArchetypeImageSeriesReader.h
- Libs/vtkITK/vtkITKLabelShapeStatistics.cxx
- Modules/CLI/AddScalarVolumes/AddScalarVolumes.cxx
- Modules/CLI/CastScalarVolume/CastScalarVolume.cxx
- Modules/CLI/CheckerBoardFilter/CheckerBoardFilter.cxx
- Modules/CLI/CurvatureAnisotropicDiffusion/CurvatureAnisotropicDiffusion.cxx
- Modules/CLI/DiffusionTensorTest/DiffusionTensorTest.cxx
- Modules/CLI/GaussianBlurImageFilter/GaussianBlurImageFilter.cxx
- Modules/CLI/GradientAnisotropicDiffusion/GradientAnisotropicDiffusion.cxx
- Modules/CLI/GrayscaleFillHoleImageFilter/GrayscaleFillHoleImageFilter.cxx
- Modules/CLI/GrayscaleGrindPeakImageFilter/GrayscaleGrindPeakImageFilter.cxx
- Modules/CLI/HistogramMatching/HistogramMatching.cxx
- Modules/CLI/MaskScalarVolume/MaskScalarVolume.cxx
- Modules/CLI/MedianImageFilter/MedianImageFilter.cxx
- Modules/CLI/MultiplyScalarVolumes/MultiplyScalarVolumes.cxx
- Modules/CLI/N4ITKBiasFieldCorrection/N4ITKBiasFieldCorrection.cxx
- Modules/CLI/OrientScalarVolume/OrientScalarVolume.cxx
- Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx
- Modules/CLI/ResampleDTIVolume/Testing/itkTestMainExtended.h
- Modules/CLI/ResampleScalarVectorDWIVolume/ResampleScalarVectorDWIVolume.cxx
- Modules/CLI/ResampleScalarVolume/ResampleScalarVolume.cxx
- Modules/CLI/SubtractScalarVolumes/SubtractScalarVolumes.cxx
- Modules/CLI/TestGridTransformRegistration/TestGridTransformRegistration.cxx
- Modules/CLI/ThresholdScalarVolume/ThresholdScalarVolume.cxx
- Utilities/Templates/Modules/CLI/TemplateKey.cxx
I encountered the need for this change when trying to make a CLI which can be pointed to Slicer, or to ITK+SlicerExecutionModel for the purpose of configuration. My ITK build has legacy disabled, so copying `GetImageType` function inside the CLI revealed it does not compile.
We should eventually get Slicer building with `ITK_LEGACY_REMOVE` turned on, but this is a step in that direction.
> COMP: Improve compatibility with ITK_LEGACY_REMOVE flag 

- SuperBuild.cmake
The commit fixes the following configuration error introduced following the BRAINSTools update in (244a6c3a788, "ENH: Update BRAINSTools from 2024-05-31 to 2024-11-09", 2025-01-24)
```
CMake Error at /path/to/Slicer-build/BRAINSTools/CMakeLists.txt:34 (message):
FAILURE 13.0 != 11.0
```
```
$ git shortlog 7c37d9e8c..3b3cfd0d4 --no-merges
COMP: Support specifying macOS deployment target ≥ 11.0
```
* https://github.com/Slicer/Slicer/pull/8191
* https://github.com/BRAINSia/BRAINSTools/pull/538
> COMP: Update BRAINSTools to fix macOS build

- Base/QTCLI/vtkSlicerCLIModuleLogic.cxx
- Base/QTGUI/qSlicerApplication.cxx
Explicitly include `Windows.h` in `Base/QTCLI/vtkSlicerCLIModuleLogic.cxx` and 
`Base/QTGUI/qSlicerApplication.cxx` to ensure the availability of Windows-specific 
symbols `MEMORYSTATUSEX` and functions `GetCurrentProcessId()` and `GlobalMemoryStatusEx()`.
----
This fixes a regression introduced in commit 975fa530e49 ("COMP: Remove direct dependency 
on ITK from vtkSlicerApplicationLogic", 2025-01-28), which removed the `itkThreadSupport.h` 
include from `vtkSlicerApplicationLogic.h`. Since `itkThreadSupport.h` indirectly included 
`Windows.h`, its removal caused missing Windows definitions in `qSlicerApplication.cxx` and 
`vtkSlicerCLIModuleLogic.cxx`, leading to the following errors:
- `Base/QTGUI/qSlicerApplication.cxx(1237,3): error C2065: 'MEMORYSTATUSEX': undeclared identifier`
- …
> COMP: Fix Windows build errors by explicitly including `Windows.h`

- Docs/developer_guide/script_repository/markups.md
- Libs/MRML/Core/vtkMRMLMarkupsDisplayNode.cxx
- Libs/MRML/Core/vtkMRMLMarkupsDisplayNode.h
- Libs/MRML/Core/vtkMRMLMarkupsNode.h
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
- Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyGenericSelfTest.py
- Modules/Scripted/Endoscopy/Endoscopy.py
Streamline reuse of attributes `"Markups.MovingInSliceView"` and `"Markups.MovingMarkupIndex"` by declaring `static GetMoving(InSliceView|MarkupIndex)AttributeName()` functions in the `vtkMRMLMarkupsDisplayNode` class as public members. This will allow for consistent use of the attribute strings across C++ and Python scripts.
```cpp
static const char* GetMovingInSliceViewAttributeName() { return "Markups.MovingInSliceView"; }
static const char* GetMovingMarkupIndexAttributeName() { return "Markups.MovingMarkupIndex"; }
```
> [!NOTE]
> The function naming convention of `GetxxxxxxxxAttributeName()` is chosen so that we understand from the function name that it is returning a name of an attribute and not the attribute value itself.
> ENH: Centralize retrieval of Markups Moving attributes in display node

- SuperBuild/External_tbb.cmake
Allow using pre-built Threading Building Blocks (TBB) libraries by specifying:
- `TBB_DIR`: Path to CMake config location
- `TBB_BIN_DIR`: Path to runtime libraries (`.dll` on Windows)
- `TBB_LIB_DIR`: Path to linker libraries (`.lib` on Windows, shared libs on Unix)
On Unix systems, `TBB_BIN_DIR` and `TBB_LIB_DIR` should point to the same directory.
> COMP: Update external project to support externally built TBB libraries

- Libs/MRML/Widgets/qMRMLClipNodeDisplayWidget.cxx
- Modules/Loadable/Segmentations/Resources/UI/qSlicerSegmentationsModule.ui
- Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/DesignerPlugins/qMRMLSubjectHierarchyTreeViewPlugin.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
- Modules/Loadable/Transforms/Resources/UI/qSlicerTransformsModuleWidget.ui
- Modules/Loadable/Transforms/qSlicerTransformsModuleWidget.cxx
- Modules/Loadable/Transforms/qSlicerTransformsModuleWidget.h
- Modules/Loadable/VolumeRendering/CMakeLists.txt
- Modules/Loadable/VolumeRendering/Resources/UI/qSlicerVolumeRenderingModuleWidget.ui
- Modules/Loadable/VolumeRendering/Widgets/CMakeLists.txt
- Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingModuleWidget.cxx
- Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingModuleWidget.h
- Modules/Loadable/Volumes/Resources/UI/qSlicerVolumesModuleWidget.ui
As described in https://github.com/Slicer/Slicer/issues/7533, to make it easier for users to select and show a segmentation (and hide others) the node combobox is now replaced by a subject hierarchy tree. For consistency between all top-level modules, this commit makes the same change for Transforms, Volumes, and Volume Rendering modules.
**Segmentations module:**
**Volumes module:**
**Volume Rendering module:**
**Transforms module:**
New transform and segmentation nodes can be created by right-clicking on the empty area in the tree:
> Use subject hierarchy tree as node selector in Volumes, Volume Rendering, Segmentations, Transforms modules

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/AbstractScriptedSegmentEditorAutoCompleteEffect.py
- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/AbstractScriptedSegmentEditorEffect.py
- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorThresholdEffect.py
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.h
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScriptedEffect.h
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
Closes #7392 
Adds a `cleanup` method to the various editor effects classes that disconnects any signals / slots. This is necessary before calling `delete`, as the connection may keep the object alive otherwise
Here's the output of the patch / code linked in the original issue after applying this fix:
```
Deleting AbstractScriptedSegmentEditorAutoCompleteEffect: <class 'SegmentEditorEffects.SegmentEditorFillBetweenSlicesEffect.SegmentEditorFillBetweenSlicesEffect'>
Deleting AbstractScriptedSegmentEditorEffect: <class 'SegmentEditorEffects.SegmentEditorFillBetweenSlicesEffect.SegmentEditorFillBetweenSlicesEffect'>
Deleting AbstractScriptedSegmentEditorAutoCompleteEffect: <class 'SegmentEditorEffects.SegmentEditorGrowFromSeedsEffect.SegmentEditorGrowFromSeedsEffect'>
Deleting …
```
> BUG: Add cleanup to SegmentEditorEffect

- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.cxx
When saving scene into `.mrb` file, long filenames were generated automatically from long node names, which prevented scene saving on Windows. Added the missing `ClampFileName` call and fixed a bug in `vtkMRMLStorageNode::ClampFileName` to resolve the problem. Now long filenames are automatically shortened.
> BUG: Fix saving into .mrb with long node names

- Applications/SlicerApp/Testing/Python/DICOMReaders.py
When SampleData.downloadFromURL failed then there was an extra error logged about failing to clean up the database directory, because the directory has not even been created. Added a check so that we only remove the directory if it has been created.
> BUG: Avoid additional error message in DICOMReaders.py

- Modules/Loadable/Data/qSlicerSceneReader.cxx
When the user was warned about potential scene loading issues, the message was formatted incorrectly: the scene file name was specified as argument but the argument was not used.
Since the scene file name is added to the message at higher level, we can simply remove the unneeded argument.
> BUG: Fix scene loading warning message

- CMakeLists.txt
This commit fixes Slicer/Slicer#8110 by adding a case for correct detection of `qt_root_dir` for Ubuntu multiarch directory structure.
> COMP: Improve system Qt detection on Debian usr-merge and multiarch systems

- Base/Python/slicer/parameterNodeWrapper/guiConnectors.py
- Base/Python/slicer/parameterNodeWrapper/serializers.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py
This commit introduces:
- A new GuiConnector (`ctkColorPickerButtonToQColorConnector`) that binds `ctkColorPickerButton` to a `QColor` property in the parameter node.
- A new serializer (`QColorSerializer`) enabling QColor to be saved and restored from the parameter node.
- An `ObservedQColor` subclass that automatically updates the parameter node whenever a “set*” method modifies the color value.
part of #7308
> ENH: Add `ctkColorPickerButton` support with `QColor` in `parameterNodeWrapper`

- CMake/SlicerBlockInstallQtTools.cmake
This PR enhances the logic to determine the internal `qt_root_dir` by considering the library architecture through `${CMAKE_LIBRARY_ARCHITECTURE}`.
This is a follow-up PR of Slicer/Slicer#8111
> ENH: Generalize internal `qt_root_dir` path

- Base/Logic/vtkSlicerApplicationLogic.cxx
Fix application logic destruction and two other minor (almost just style) fixes.
---
After threading rework in https://github.com/Slicer/Slicer/commit/47da17d4c90f4b2a0dff3034b5305cc1d864c31f, `vtkSlicerApplicationLogicTest1` test started to fail due to crash in the destructor.
The problem was that the networking threads were deleted before waiting for them to finish.
Fixed by calling `TerminateProcessingThread()` method that joins all created threads (instead of just joining the ProcessingThread as it was implemented in the destructor before).
> BUG: Fix crash in vtkSlicerApplicationLogic destructor

- Applications/SlicerApp/Testing/Python/UtilTest.py
- Base/Python/slicer/util.py
See updated description below: https://github.com/Slicer/Slicer/pull/8180#issuecomment-2649364818
<details><summary>Previous description</summary>
<p>
Allow additional `dtypes` to be handled when converting to `vtk` array. All types supported by `vtk.util.numpy_support.get_vtk_array_type` can be converted.
However, I don't think this still supports `boolean` or `string` arrays.
We need to figure out a way to generate and possibly use the following VTK array types:
`bool` numpy array --> `vtkBitArray`
`string` numpy array --> `vtkStringArray`
</p>
</details> 
Partially addresses:
- https://github.com/Slicer/Slicer/issues/5827
> ENH: Add support for additional NumPy types in `slicer.util.updateTableFromArray`

- Base/Logic/vtkImageFillROI.cxx
- Libs/MRML/Core/vtkMRMLAbstractViewNode.cxx
- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologyEntry.cxx
- Modules/Loadable/VolumeRendering/MRML/vtkMRMLShaderPropertyNode.cxx
- Modules/Loadable/VolumeRendering/MRML/vtkMRMLVolumePropertyNode.cxx
Fix indentation in `vtkMRMLAbstractViewNode::PrintSelf` and add missing newlines in `PrintSelf` .
Follow-up these commits were the newlines were omitted:
* `vtkMRMLSliceLogic`: de98785 ("BUG: fix print methods so tests will pass", 2010-01-15)
* `vtkMRMLShaderPropertyNode`: ea47570 ("ENH: Add new node types to support custom shader code for volume rendering", 2019-06-04)
* `vtkMRMLVolumePropertyNode`: b13f089 ("ENH: fixed visibility in modelHierarchy widget", 2009-01-14)
* `vtkSlicerTerminologyEntry`: fe0e596 ("ENH: Added Terminologies module for handling standard terminologies", 2016-10-14)
* `vtkImageFillROI`: e934e58 ("ENH: poly draw class brought over from slicer2 for use in the editor", 2006-11-15)
Before:
```
[...]
VolumeProperty:     Debug: Off
Modified Time: 533642
Reference Count: …
```
> BUG: Add missing newlines and fix  indentation in `PrintSelf`

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
The comment was originally introduced in 2c46933490 ("ENH: fixed pipeline from mrml scene to composited image data", 2006-03-30) and become obsolete following these commits:
* 95ac4f1fb4 ("ENH: DownCast Foreground and Background layer to MRMLVolumeNode so it can hold different type of volumes like Diffusion Tensor, Diffusion Weighted Volumes and Vector Volumes", 2007-01-03)
* 4189ee6eef ("ENH: Adding layer infrastructure to handle different types of MRMLVolumeNodes. We currently support: Scalars, Vectors, Diffusion Tensors, Diffusion Weighted Volumes", 2007-01-03)
> DOC: Remove obsolete comment from vtkMRMLSliceLogic::UpdatePipeline

- SuperBuild.cmake
```
$ git shortlog 8c43b66ed..b5aa0615a --no-merges
Alexy Pellegrini (2):
ENH: Remove use of vtk_glew.h from vtkOpenGLTextureImage.h
ENH: Includes vtk_glad.h instead of vtk_glew.h when using VTK 9.4 or newer
```
Related issue(s):
* https://github.com/Slicer/Slicer/issues/7488
> ENH: Update vtkAddon anticipating update to VTK >= 9.4

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
This pull request removes redundant `vtkMRMLModelDisplayNode::SetInterpolateTexture` call in
`vtkMRMLSliceLogic::ProcessMRMLLogicsEvents()`, by handled the remaining call in `vtkMRMLSliceLogic::UpdatePipeline()` with a more comprehensive check.
After reviewing the logic, checking only for `GetImageDataConnectionUVW()` would be sufficient because:
- The model slice node (`vtkMRMLModelDisplayNode`) is only associated with 3D views (see use of `SetViewNodeIDs` depicted below).
- `vtkMRMLModelDisplayableManager`, responsible for displaying the slice model node, derives from `vtkMRMLAbstractThreeDViewDisplayableManager`.
- `vtkMRMLModelSliceDisplayableManager` is responsible for displaying model intersections on slice planes and does not handle the model associated with the slice viewer.
This …
> ENH: Consolidate SliceLogic calls to SetInterpolateTexture

- CMakeLists.txt
- Libs/MRML/Core/vtkCacheManager.cxx
- Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx
- Libs/vtkSegmentationCore/vtkBinaryLabelmapToClosedSurfaceConversionRule.cxx
- Libs/vtkSegmentationCore/vtkPolyDataToFractionalLabelmapFilter.cxx
Introduce `Slicer_VTK_MINIMUM_SUPPORTED_VERSION` CMake variable to describe the minimum supported version of VTK.
Anticipate support for building against VTK 9.4 by removing use of APIs originally deprecated in VTK 9.1 or earlier and removed from VTK 9.3.
Update `vtkBinaryLabelmapToClosedSurfaceConversionRule` removing unused `vtkExtractSelectedIds.h` and `vtkExtractSelectedThresholds.h` includes
originally introduced in https://github.com/Slicer/Slicer/commit/fcb40b0738c65ab418731a1a34292f3c85b2133a ("ENH: Add support for shared binary labelmap segmentations", 2019-10-08). These classes have been removed in VTK 9.4 in favor of `vtkExtractSelection`.
> ENH: Remove support for building against VTK <= 9.1

- Modules/Loadable/Volumes/qSlicerVolumesReader.cxx
- Modules/Loadable/Volumes/qSlicerVolumesReader.h
Improve qSlicerSequencesReader heuristics to know that dwmri modality is not typically loaded as a sequence by lowering the confidence for files of this type.
Also fixes code to now read the entire nrrd header so that other keys won't be missed in files with large headers (dwmri files typically have over 1000 characters before the modality tag).
Fixes #8240
> BUG: Do not load DWMRI volumes as sequences

- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsTableView.cxx
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsTableView.h
This PR proposes addition of a context menu item for the segmentations widget to toggle visibility of the selected segments. This feature is very convenient while reviewing segmentations with the large number of segments, when a subset of segments need to be shown/hidden without affecting visibility of other segments.
> ENH: Add segment visibility toggle option

- Applications/SlicerApp/Testing/Python/UtilTest.py
py_UtilTest's test_updateTableFromArray test failed on Windows:
-----
FAIL: test_updateTableFromArray (UtilTest.UtilTestTest) 
---------------------------------------------------------------------- 
File "C:/D/P/S-0-build/Slicer-build/lib/Slicer-5.9/qt-scripted-modules/UtilTest.py", line 285, in test_updateTableFromArray
self.assertEqual(tableNode3.GetColumnType("height"), vtk.VTK_LONG_LONG)
AssertionError: 6 != 16
-----
The root cause is that "int" type is mapped to np.int64 on linux and macOS but on Windows it is mapped to np.int32.
Fixed the test by making the behaviour consistent on all platforms, by using np.int32 as column data type.
> BUG: Fix py_UtilTest on Windows

- Libs/MRML/Core/vtkMRMLScene.cxx
`vtkMRMLScene::GetTemporaryBundleDirectory` could return a string that contained a "\0" character. C string manipulation functions mostly ignore what is after the "\0" character.
Since this string was used as a directory name, it was passed to `kwSys::SystemTools::RemoveADirectory` method, which got into an infinite recursion and crashed with stack overflow, because the appended "/" + filename effectively has not been appended.
This caused several tests to randomly fail, such as `vtkMRMLSequenceStorageNodeTest1`.
The regression was introduced in commit 47c791c77fe4091a18fb894f9f2d19f5c50ad903 (BUG: Fix loading and saving `.mrb` files with trailing space in filename) on 2025-01-11.
@jcfr The fix has to be added to a Slicer-5.8 patch release, preferably soon, as it can cause crash during …
> BUG: Fix crash in SystemTools::RemoveADirectory

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
Fixes an issue introduced in 26fd93d ("BUG: Ensure blend pipeline is updated when setting operation Add or Subtract", 2025-02-17).
`vtkMRMLSliceLogic::UpdateAddSubOperation` may be called with any compositing mode, including unsupported ones, leading to unnecessary error messages. This update ensures the function is only called for supported modes (`Add` or `Subtract`), preventing unintended log errors.
> BUG: Avoid unnecessary error message in UpdateAddSubOperation

- .github/actions/slicer-build/Dockerfile
- .github/workflows/ci.yml
* Update slicer-build GitHub action to use `5.8` docker image
* Update CI GitHub workflow to test `5.8` branch instead of `main`
The `slicer-base` image was manually tagged and published on the `metroplex` factory using the following commands:
```
docker tag slicer/slicer-base:latest slicer/slicer-base:5.8
docker push slicer/slicer-base:5.8
```
Since it is based on the `latest` version, it includes external project specific changes associated with this pull-request:
* https://github.com/Slicer/Slicer/pull/8183
* https://github.com/Slicer/Slicer/pull/8191
* https://github.com/Slicer/Slicer/pull/8197
* https://github.com/Slicer/Slicer/pull/8227
* https://github.com/Slicer/Slicer/pull/8239
* https://github.com/Slicer/Slicer/pull/8165
> [5.8] Update GitHub CI workflow to be release specific

- Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorEffects/SegmentEditorGrowFromSeedsEffect.py
Backport from #8166
---
(cherry picked from commit d09caa4bda46ac5c6231f816bc0a35d974a44765)
> [5.8] BUG: Fix typo in Grow From Seeds help text

- Docs/developer_guide/advanced_topics.md
- Docs/developer_guide/modules/transforms.md
- Docs/developer_guide/python_faq.md
- Docs/developer_guide/script_repository/volumes.md
Backport from #8171
---
This pull request updates links referencing the outdated `https://www.slicer.org/doc/html` to the current `https://apidocs.slicer.org/main`.
(cherry picked from commit d798402abaa8f47ff042f99f073c10f4f5af0f6a)
> [5.8] DOC: Fix links to slicer doxygen in the developer guide

- Docs/developer_guide/extensions.md
- Docs/developer_guide/module_overview.md
- Docs/developer_guide/style_guide.md
Backport from #7179
---
* Fix various broken documentation links
* Update developer guide to link to Qt 5 API docs instead of Qt 4.8
* Use more specific website for links to API docs of dependencies
* Fix formatting of links in Style guide
(cherry picked from commit 0dff9bdbd3567d2cfdc0f7bf270a5e174740786d)
> [5.8] DOC: Fix various broken documentation links in developer guide

- SuperBuild/External_VTK.cmake
Backport from #8183
---
```
$ git shortlog 57bacae7e9..492821449a --no-merges
Jaswant Panchumarti (1):
[Backport] Fix undefined variable name in octree_node
```
VTK References:
- Issue: https://gitlab.kitware.com/vtk/vtk/-/issues/19358
- Merge Request: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11178 mentioned this came up due to a newer clang.
(cherry picked from commit 1fb3d94fc447299b6ebab30804de8ebab943b665)
> [5.8] COMP: Update VTK backporting fix to support building on Linux with clang

- SuperBuild.cmake
Backport from #8227 and #8239
---
ENH: Update vtkAddon 
```
$ git shortlog 3f317421d..8c43b66ed --no-merges
AlexyPellegrini (1):
ENH: Replace WIN32 with _WIN32 to fix build with Ninja (#51)
Ebrahim Ebrahim (1):
BUG: Fix matrix comparisons for exact equality (#54)
```
(cherry picked from commit 0776014)
---
ENH: Update vtkAddon anticipating update to VTK >= 9.4 
```
$ git shortlog 8c43b66ed..b5aa0615a --no-merges
Alexy Pellegrini (2):
ENH: Remove use of vtk_glew.h from vtkOpenGLTextureImage.h
ENH: Includes vtk_glad.h instead of vtk_glew.h when using VTK 9.4 or newer
```
(cherry picked from commit ae95058)
> [5.8] ENH: Update vtkAddon

- SuperBuild.cmake
Backport from #8191 and #8197
--------
ENH: Update BRAINSTools from 2024-05-31 to 2024-11-09 
List of BRAINSTools changes:
```
$ git shortlog d88a4f43..7c37d9e8 --no-merges
Hans J. Johnson (22):
ENH: Update to VTK 9.3 to support builds on newer m3 mac.
COMP: ITKv5.4.0 requires C++17 features.
ENH: Update to newer versions of python packages
ENH: Checks for toml xml yaml
ENH: Add shabang for executable files, remove execute permissions
ENH: Fixed end-of-file inconsistencies.
ENH: Enforce rigors end of line symantics
ENH: Adding python tests naming consistency.
ENH: forbid new submodules
ENH: Initial ruff code fixes for safe code updates.
ENH: Code cleanups for comparison to bool values
ENH: Modernize codebase with pyupgrade to 3.10 syntax recommendations.
ENH: Prepratory shell check …
```
> [5.8] ENH: Update BRAINSTools from 2024-05-31 to 2024-11-09 and include macOS build fix

- Docs/conf.py
- Docs/developer_guide/advanced_topics.md
- Docs/developer_guide/modules/transforms.md
- Docs/developer_guide/python_faq.md
- Docs/developer_guide/script_repository/volumes.md
Backport from #8176
---
This commit introduces a systematic mechanism to generate Doxygen documentation links dynamically, aligning with the ReadTheDocs version of the project.
- Extracts `<major>.<minor>` version information from the top-level `CMakeLists.txt`.
- Updates `conf.py` to construct Doxygen links dynamically for either the release or main branch based on the minor version parity:
- **Odd minor versions**: Links to the corresponding Preview documentation (`/main` sub-directory).
- **Even minor versions**: Links to the corresponding Stable documentation sub-directory (e.g., `/X.Y`).
- Implements a custom URL scheme `slicerapidocs` to facilitate consistent and version-specific cross-referencing in Markdown files.
(cherry picked from commit …
> [5.8] DOC: Dynamically generate links to slicer doxygen based on ReadTheDocs version

- Base/QTCore/Resources/Certs/Slicer.crt
Backport from #8207
---
This commit updates Slicer.crt certificate bundle with [make-ca.sh][1] script using the content of [certdata][2] associated with mozilla/gecko-dev@b2ea4fc37248f6764f197afe3e54676a6299b9ad,
It was auto-generated by the [update-slicer-certificate-bundle][3] GitHub action workflow.
[1]: https://github.com/Slicer/Slicer/blob/71394e2955e040f3b7ffcb36538b1cb751a77f17/Base/QTCore/Resources/Certs/make-ca.sh
[2]: https://github.com/mozilla/gecko-dev/blob/b2ea4fc37248f6764f197afe3e54676a6299b9ad/security/nss/lib/ckfw/builtins/certdata.txt?raw=true
[3]: https://github.com/Slicer/Slicer/blob/71394e2955e040f3b7ffcb36538b1cb751a77f17/.github/workflows/update-slicer-certificate-bundle.yml
(cherry picked from commit 0ceb67e3853f7a72f5bd9a1494aedf26971c1c2b)
> [5.8] ENH: Update Slicer.crt CA bundle

- Modules/Loadable/Volumes/qSlicerVolumesReader.cxx
- Modules/Loadable/Volumes/qSlicerVolumesReader.h
Backport from #8242
---
Improve qSlicerSequencesReader heuristics to know that dwmri modality is not typically loaded as a sequence by lowering the confidence for files of this type.
Also fixes code to now read the entire nrrd header so that other keys won't be missed in files with large headers (dwmri files typically have over 1000 characters before the modality tag).
Fixes #8240
(cherry picked from commit ef756a160661be3152831b6744d0dd51e5785fe6)
> [5.8] BUG: Do not load DWMRI volumes as sequences

- Libs/MRML/Core/vtkMRMLScene.cxx
Backport from #8250
---
vtkMRMLScene::GetTemporaryBundleDirectory could return a string that contained a "\0" character. C string manipulation functions mostly ignore what is after the "\0" character.
Since this string was used as a directory name, it was passed to kwSys::SystemTools::RemoveADirectory method, which got into an infinite recursion and crashed with stack overflow, because the appended "/" + filename effectively has not been appended.
This caused several tests to randomly fail, such as vtkMRMLSequenceStorageNodeTest1.
The regression was introduced in commit 47c791c77fe4091a18fb894f9f2d19f5c50ad903 (BUG: Fix loading and saving .mrb files with trailing space in filename) on 2025-01-11.
(cherry picked from commit f24bada8cc0ee2f707425689545a5273f03b90d9)
> [5.8] BUG: Fix crash in SystemTools::RemoveADirectory

- Modules/Loadable/Data/qSlicerSceneReader.cxx
Backport from #8216
---
When the user was warned about potential scene loading issues, the message was formatted incorrectly: the scene file name was specified as argument but the argument was not used.
Since the scene file name is added to the message at higher level, we can simply remove the unneeded argument.
(cherry picked from commit 19690712673e96bb91d8eb60f735a5e0e2dffe9c)
> [5.8] BUG: Fix scene loading warning message

- Applications/SlicerApp/Testing/Python/DICOMReaders.py
Backport from #8215
---
When SampleData.downloadFromURL failed then there was an extra error logged about failing to clean up the database directory, because the directory has not even been created. Added a check so that we only remove the directory if it has been created.
(cherry picked from commit d94ad217a6375e5ed551edf124ad959f5b6becb8)
> [5.8] BUG: Avoid additional error message in DICOMReaders.py

- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.cxx
Backport from #8214
---
When saving scene into .mrb file, long filenames were generated automatically from long node names, which prevented scene saving on Windows. Added the missing ClampFileName call and fixed a bug in vtkMRMLStorageNode::ClampFileName to resolve the problem. Now long filenames are automatically shortened.
(cherry picked from commit 74eb12951a382b71be7030acc5d7c56704d37e3a)
> [5.8] BUG: Fix saving into .mrb with long node names

- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Libs/MRML/Logic/vtkMRMLSliceLogic.h
- Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx
This PR refactors `vtkMRMLSliceLogic` to introduce support for multiple slice layers using a generalized "Nth Layer" API. Additionally, it provides new methods for checking whether any layers have inputs.
- Replace explicit `BackgroundLayer`, `ForegroundLayer`, and `LabelLayer` members with a dynamic `Layers` list.
- Introduce new methods:
- `GetNthLayer(int layerIndex)`
- `SetNthLayer(int layerIndex, vtkMRMLSliceLayerLogic *layer)`
- `GetNthLayerImageDataConnection(int layerIndex)`
- `GetNthLayerImageDataConnectionUVW(int layerIndex)`
- `GetNthLayerVolumeNode(int layerIndex)`
- `SetNthLayerVolumeNode(int layerIndex, vtkMRMLVolumeNode* volumeNode)`
- Update references to the old layer variables (`BackgroundLayer`, etc.) with their `NthLayer` equivalents.
- Deprecate …
> ENH: Generalize SliceLogic API introducing "Nth Layer" functions

- Libs/MRML/Core/vtkMRMLSliceCompositeNode.cxx
- Libs/MRML/Core/vtkMRMLSliceCompositeNode.h
- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Libs/MRML/Logic/vtkMRMLSliceLogic.h
This PR extends the previous Nth Layer generalization by updating `vtkMRMLSliceCompositeNode` to support multiple layers dynamically, aligning with the recent refactor of `vtkMRMLSliceLogic` introduced in https://github.com/Slicer/Slicer/pull/8277.
- Replace explicit `BackgroundVolumeID`, `ForegroundVolumeID`, and `LabelVolumeID` with a flexible, indexed `Nth Layer` system.
- Introduce new methods:
- `GetNthLayerVolume(int layerIndex)`
- `SetNthLayerVolume(int layerIndex, vtkMRMLVolumeNode* volumeNode)`
- `GetNthLayerVolumeID(int layerIndex)`
- `SetNthLayerVolumeID(int layerIndex, const char* volumeNodeID)`
- Update existing getter/setter methods (`GetBackgroundVolumeID()`, etc.) to internally call `Nth Layer` functions.
- Replace hardcoded `GetBackgroundVolumeID()`, …
> ENH: Generalize CompositeNode API introducing "Nth Layer" functions

- Libs/MRML/Core/vtkMRMLSliceCompositeNode.cxx
- Libs/MRML/Core/vtkMRMLSliceCompositeNode.h
- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
This PR refactors `vtkMRMLSliceCompositeNode` to generalize opacity management using the **Nth Layer API**, replacing hardcoded foreground and label opacity values.
- Add `GetNthLayerOpacity(int layerIndex)` and `SetNthLayerOpacity(int layerIndex, double value)`, replacing individual opacity variables.
- Modify `ForegroundOpacity` and `LabelOpacity` to internally use `Nth Layer` methods.
- Update `vtkMRMLSliceCompositeNode` to store opacity values in a dynamically resizable vector (`LayerOpacities`).
- Replace explicit calls to `GetForegroundOpacity()` and `GetLabelOpacity()` with `GetNthLayerOpacity(layerIndex)`.
> [!NOTE]
> This PR is part of a broader effort to generalize and expand Slicer's multi-layer rendering capabilities.
> Future work includes:
>
> - Modifying UI components to …
> ENH: Generalize CompositeNode "opacity" API introducing "Nth Layer" functions

- Base/QTCore/Testing/Cxx/qSlicerCoreIOManagerTest1.cxx
- Base/QTCore/qSlicerCoreIOManager.cxx
- Base/QTCore/qSlicerCoreIOManager.h
- Base/QTGUI/Resources/UI/qSlicerSettingsGeneralPanel.ui
- Base/QTGUI/qSlicerExportNodeDialog.cxx
- Base/QTGUI/qSlicerSaveDataDialog.cxx
- Base/QTGUI/qSlicerSettingsGeneralPanel.cxx
- Base/QTGUI/qSlicerSettingsGeneralPanel.h
- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.h
Backport from #8245 
---
Make maximum file length configurable, with default set to 50 on Windows and 1000 on other operating systems. Users who do not need compatibility with Windows systems (or use short folder names) can choose to allow longer filenames to keep filenames matching node names.
fixes #8241
(cherry picked from commit a984ec47b50aacbf2f6c732bc87eeec7245714a4)
> [5.8] ENH: Make maximum file length configurable

- Base/QTCore/qSlicerCoreApplication.cxx
- Base/QTCore/qSlicerCoreIOManager.cxx
- Base/QTGUI/qSlicerApplication.cxx
Addresses a regression introduced in a984ec47b50 ("ENH: Make maximum file length configurable", 2025-02-20) through https://github.com/Slicer/Slicer/pull/8245.
- Move the retrieval of `MaximumFileNameLength` from `qSlicerCoreIOManager`'s constructor to `qSlicerCoreApplicationPrivate::initDataIO()`, ensuring proper initialization after the application object is fully set up.
- Remove redundant settings initialization from `qSlicerCoreIOManager`'s constructor.
- Ensure `qSlicerApplication` correctly applies the `MaximumFileNameLength` setting from user preferences when creating the IO Manager.
- Add fallback warning when application settings are inaccessible.
This change ensures consistent settings initialization and avoids potential issues due to premature access in `qSlicerCoreIOManager`. …
> BUG: Fix core IO manager initialization

- Base/QTCore/qSlicerCoreApplication.cxx
- Base/QTCore/qSlicerCoreIOManager.cxx
- Base/QTGUI/qSlicerApplication.cxx
Backport from https://github.com/Slicer/Slicer/pull/8287
---
Addresses a regression introduced in a984ec47b50 ("ENH: Make maximum file length configurable", 2025-02-20)
- Move the retrieval of `MaximumFileNameLength` from `qSlicerCoreIOManager`'s constructor to `qSlicerCoreApplicationPrivate::initDataIO()`, ensuring proper initialization after the application object is fully set up.
- Remove redundant settings initialization from `qSlicerCoreIOManager`'s constructor.
- Ensure `qSlicerApplication` correctly applies the `MaximumFileNameLength` setting from user preferences when creating the IO Manager.
- Add fallback warning when application settings are inaccessible.
This change ensures consistent settings initialization and avoids potential issues due to premature access in …
> [5.8] BUG: Fix core IO manager initialization

- Base/QTCore/qSlicerCoreApplication.cxx
This is a follow-up to https://github.com/Slicer/Slicer/commit/582437a93c7f7a174f6894137001109f686831a9 to fix another location of missing `Windows.h` found when building a Slicer custom application with `Slicer_BUILD_DICOM_SUPPORT` turned `OFF`. It was observed in another Slicer custom application with near identical configuration, but with `Slicer_BUILD_DICOM_SUPPORT` turned `ON` did not run into this build error.
-----------------------
Explicitly include `Windows.h` in `Base/QTCore/qSlicerCoreApplication.cxx` to ensure the availability of Windows-specific function `ExitProcess()`.
This fixes a regression introduced in commit https://github.com/Slicer/Slicer/commit/975fa530e490d60ce5c0164af81872ead78d617c ("COMP: Remove direct dependency on ITK from vtkSlicerApplicationLogic", …
> COMP: Fix Windows build error by explicitly including Windows.h

- Modules/Scripted/DICOMLib/DICOMExportScene.py
It seems that in the new DCMTK version the img2dcm (and probably others) do not have the --no-latin1 flag anymore. This commit removes the use of that flag, which caused an error on MRB DICOM export. I tested it with special characters (Japanese and Hungarian) and export succeeded.
> BUG: Fix DICOM scene export

- Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentsPlugin.cxx
The error occurs many times and the superfluous error messages make the log harder to process.
> ENH: Reduce unnecessary error reporting in segmentation SH

- Docs/user_guide/user_interface.md
Added documentation section that can be reference in Slicer-5.8 release notes.
> DOC: Add ambient shadows section to documentation

- Libs/MRML/Core/vtkArchive.cxx
This is a follow-up to https://github.com/Slicer/Slicer/commit/dfde1cfc68f2d8d6da6678fb0a22fa4dd184288c where this code change should have been included. The VTK minimum supported version is 9.2, so there is no need to handle logic for earlier versions.
> ENH: Remove additional code handling VTK support <= 9.1

- Libs/MRML/Core/vtkMRMLLayoutNode.cxx
- Libs/MRML/Logic/vtkMRMLLayoutLogic.cxx
Defining the singleton tag in the constructor causes issues when trying to record sequences with layout nodes. This commit moves the layout node singleton tag initialization to vtkMRMLLayoutLogic.
> ENH: Move singleton declaration from vtkMRMLLayoutNode constructor

- Libs/MRML/Core/vtkMRMLLayoutNode.cxx
- Libs/MRML/Core/vtkMRMLLayoutNode.h
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.h
This allows both vtkMRMLLayoutNode and vtkMRMLSequenceBrowserNode to be recorded in Sequences.
> ENH: Add CopyContent methods to vtkMRMLLayoutNode and vtkMRMLSequenceBrowserNode

- Base/QTCore/qSlicerCoreApplication_p.h
Per https://doc.qt.io/qt-5/portingguide.html, the Q_WS_WIN preprocessor macros was replaced with Q_OS_WIN.
This commit is a follow-up to https://github.com/Slicer/Slicer/commit/ec58ea1cdf9ed15ffd7ddc19b7a27ffe1a4c589c when `updatePythonOsEnviron` was actually removed.
> STYLE: Remove obsolete Qt4 code

- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx
- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.h
Recently vtkSlicerTerminologiesModuleLogic methods were renamed to make the API more consistent (mostly using "region" instead of somewhat randomly using anatomicalRegion/anatomy/region in their name). This change caused runtime error in QuantitativeReporting extension.
This commit restores the removed methods. They are deprecated methods, which will be removed in the future, but for now they log a warning message and then call the corresponding new method.
fixes #8324
> COMP: Make vtkSlicerTerminologiesModuleLogic API backward compatible

- Modules/Loadable/SceneViews/qSlicerSceneViewsModule.cxx
Prevent CaptureToolBar initialization in qSlicerSceneViewsModule unless main window exists. Fixes error/memory leak in py_nomainwindow_* tests added in fb6fb19ef37f60abc7c021c688560fedd1ccfebe.
> BUG: Fix failing py_nomainwindow_* tests

- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx
SceneViewIndexToSequenceBrowserIndex should only look through SceneViews sequences when trying to determine the index of a specific scene view, however all sequences were being iterated through. This caused the wrong index to be returned when trying to find the index of a scene that contained other sequences.
Fixed by only looking at sequence browser nodes that belong to SceneViews.
> BUG: Fix invalid scene view indexing

- Base/QTGUI/Resources/UI/qSlicerSettingsViewsPanel.ui
- Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.cxx
- Libs/MRML/Widgets/qMRMLThreeDViewControllerWidget.h
Added a menu item to revert ambient shadows options to the default to make it easier to get ambient shadows back to a working state after modifying several parameters.
@muratmaga
> Add reset ambient shading options

- Docs/user_guide/modules/index.md
The wiki is out of date and documentation has been moved to slicer.readthedocs.io
> DOC: Remove link to wiki from list of modules

- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx
Added missing return in vtkSlicerSceneViewsModuleLogic::ConvertSceneViewNodeToSequenceBrowserNode.
> COMP: Fix warning due to missing return path

- Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.cxx
- Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.h
- Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx
- Modules/Loadable/VolumeRendering/Logic/vtkSlicerVolumeRenderingLogic.cxx
- Modules/Loadable/Volumes/Widgets/Resources/UI/qSlicerScalarVolumeDisplayWidget.ui
- Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.cxx
- Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.h
If enabled, the order of colors in the lookup table is reversed. This makes it possible to use the same color tables for images regardless of the objects of interest have higher or lower voxel values than the background.
The reversed colors are also applied to volume rendering, if the user chose to synchronize volume rendering transfer functions with scalar volume display.
@muratmaga
> ENH: Add invert colors option to Volumes module

- Modules/Loadable/Volumes/Widgets/Resources/UI/qSlicerScalarVolumeDisplayWidget.ui
- Modules/Loadable/Volumes/Widgets/qSlicerScalarVolumeDisplayWidget.cxx
Improved histogram in Volumes module:
- Use the currently selected color table, window/level, invert, and threshold settings to color the background of the histogram
- Added minimum, center, maximum values to the horizontal axis of the histogram
- Fixed slow window/level adjustment when the histogram was displayed
@muratmaga
> Improve histogram display in Volumes module

- Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.cxx
- Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.h
This commit adds to vtkMRMLSegmentationDisplayNode:
- Test for equality for segment display parameters
- Call Modified() if they are not equal
> BUG: Call Modified if segment display properties changed during copy

- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx
- Modules/Loadable/Sequences/Logic/vtkSlicerSequencesLogic.cxx
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
- Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.h
This commit adds an additional missing item mode to vtkMRMLSequenceBrowserNode to hide proxy display nodes that are not present in a sequence. This option is used by SceneViews to hide display nodes for scene views that were captured before the display node was present.
> ENH: Add option to hide missing display nodes in sequences

- Libs/MRML/Core/Testing/vtkMRMLColorTableNodeTest1.cxx
- Libs/MRML/Core/vtkMRMLColorTableStorageNode.cxx
Recently color table infrastructure was refactored (65409219f724bf03bd0307e9c2062c06030f3951) and now it is possible to have empty color names. When writing to .ctbl format the empty name confused the parser (it read the R color component as color name).
Fixed the issue by replacing empty color name by "_" when writing to .ctbl file format. Default file save format is .csv now and color name is normally not empty, so the error.
> BUG: Fixing writing empty color names into ctbl format

- Libs/MRML/Core/Testing/vtkMRMLColorTableNodeTest1.cxx
- Libs/MRML/Core/vtkMRMLColorNode.cxx
- Libs/MRML/Core/vtkMRMLColorNode.h
- Libs/MRML/Core/vtkMRMLColorTableNode.cxx
- Libs/MRML/Core/vtkMRMLColorTableNode.h
When a color is set in a color node then its color is automatically set to defined.
However, when colors were set in bulk using SetAndObserveLookupTable, the colors were not set to "defined".
This commit changes the default behavior of SetAndObserveLookupTable so that it sets all the colors in the lookup table to "defined".
This way, the code does that most developers expect it to do.
The pull request also cleans up the ColorTable node a bit to more consistently set number of colors and report errors.
It includes commit from https://github.com/Slicer/Slicer/pull/8348, so it should be merged after that PR is merged.
* https://github.com/Slicer/Slicer/pull/8348
> ENH: Make all colors defined by default when setting a LUT 

- Base/Python/slicer/cli.py
- Base/QTCLI/vtkSlicerCLIModuleLogic.cxx
- Base/QTCLI/vtkSlicerCLIModuleLogic.h
By default, windows associated with CLI executables are hidden on Windows via `itksysProcess_Option_HideWindow = 1`. This behavior makes it impossible for CLIs that create their own windows (e.g., using `vtkWin32HardwareWindow`) to display them.
This commit introduces support for optionally showing CLI windows:
- Adds `SetHideWindow` / `GetHideWindow` methods to `vtkSlicerCLIModuleLogic`, defaulting to `true` to preserve current behavior.
- Updates `ApplyTask` to respect this flag when setting `itksysProcess_Option_HideWindow`.
- Extends the Python API in `slicer.cli.run` and `slicer.cli.runSync` to accept a new `hide_window` parameter (defaulting to `True`).
This enables use cases such as launching interactive viewers as part of CLI workflows on Windows.
> ENH: Add option to show CLI executable windows on Windows

- Modules/Loadable/SceneViews/GUI/qMRMLSceneViewMenu.cxx
`qMRMLSceneViewMenu::resetMenu` was previously called every time a sequence proxy node was modified. The menu shouldn't need to update if the proxy node is modified, so it makes sense to remove this call to improve performance.
> BUG: Fix excessive qMRMLSceneViewMenu::resetMenu calls

- Libs/MRML/Core/vtkMRMLCameraNode.cxx
- Libs/MRML/Core/vtkMRMLModelStorageNode.cxx
- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLSequenceNode.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.cxx
- Libs/MRML/Core/vtkMRMLStorageNode.h
- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx
- Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyFoldersTest1.py
These commits removes logging of false alarm error/warning messages during loading scenes.
This makes it easier to see actual problems during scene loading.
> Reduce warnings during legacy scene load

- Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx
Added missing null-pointer check to avoid crash in case of incomplete terminology.
fixes #8360
> BUG: Fix crash in vtkSlicerTerminologiesModuleLogic

- SuperBuild/External_CTK.cmake
Commit commontk/CTK@88ff72b (introduced through f0138cd0b) changed `ctkDICOMDatabase::fileValue` behavior so that it no longer returns DICOM tag value for files that are not already in the database.
This is an issue because this method has been used universally for any DICOM files (it returned result faster for files that are cached in the DICOM database but it worked for files not in the database, too).
This commit restores the previous, preferred behavior.
```
$ git shortlog 82cae578..7f8e1a67 --no-merges
BUG: Fix ctkDICOMDatabase::fileValue for non-cached files
```
> BUG: Update CTK to fix `ctkDICOMDatabase::fileValue` for non-cached files

- Base/QTGUI/qSlicerApplication.cxx
Follow-up of 3ae750f4714 ("BUG: Avoid logging errors during Python auto-completion with CTK update", 2023-01-19)
* https://github.com/Slicer/Slicer/pull/8238
> BUG: Disable logging of VTK deprecation warnings during Python autocompletion

- SuperBuild/External_CTK.cmake
These changes address failures in the Python completion model caused by unhandled errors when retrieving attributes from VTK classes. VTK 9.4 introduces additional wrapping of property-like accessors requiring to fix improve CTK’s auto-completion infrastructure. See https://www.kitware.com/vtk-9-4-a-step-closer-to-the-ways-of-python/ for more details.
```
$ git shortlog 7f8e1a67d..c68d1c9fa --no-merges
Jean-Christophe Fillion-Robin (5):
STYLE: Remove unneeded line continuation from ctkAbstractPythonManager
COMP: Simplify pythonAttributes by removing unused dict variable
ENH: Make ctkAbstractPythonManager::pythonAttributes available from Python
BUG: Fix python manager error handling in `pythonAttributes` and `dir_object`
BUG: Ensure new reference associated with …
```
> BUG: Update CTK to ensure robust Python auto-completion anticipating VTK 9.4

- CMakeLists.txt
- Docs/developer_guide/build_instructions/linux.md
- Docs/developer_guide/build_instructions/macos.md
- Docs/developer_guide/build_instructions/windows.md
Update documentation and report error if attempting to build Slicer-5.8 with CMake4.
> COMP: Report CMake4 incompatibility in Slicer-5.8

- CMakeLists.txt
Slicer build scripts currently are not compatible with CMake 4. This commit makes the build fail immediately, with a meaningful error message.
> COMP: Make build fail with meaningful error message with CMake 4

- Modules/Loadable/Transforms/qSlicerTransformsModuleWidget.cxx
Slicer crashed when Transforms module was opened when a transform was automatically selected when entering the module and that transform already had a display node. The problem was that in qSlicerTransformsModuleWidget::onNodeSelected() the d->MRMLTransformNode member was updated too late. Some method calls in that method had the side effect of calling qSlicerTransformsModuleWidget::onSubjectHierarchyItemModified, which reset the transform node from d->MRMLTransformNode, which was still nullptr. Fixed the issue by updating d->MRMLTransformNode early, before calling any other methods.
fixes #8386
> BUG: Fix crash when entering into Transforms module

- Base/QTGUI/qSlicerViewersToolBar.cxx
To improve discoverability of the shift+mouse move functionality for slice intersections I have added it to the toggle slice intersection tooltip.
This tooltip is structured like the existing Crosshair visibility action tooltip. This helps indicate that Shift+Mouse move is available for crosshair and slice intersection positioning.
Here for example is the existing Crosshair visibility tooltip:
> ENH: Include slice intersection mouse move info in tooltip

- Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
If select by terminology is used in Colors module, there is no entry found when trying to find the last used terminology, so the first item in the combobox is selected. If instead, we select the first of the preferred terminologies in this case, the user will will get the convenience of being able to use the last context, thus speeding up the workflow.
Re #8394
> ENH: Select first preferred terminology if no entry is found

- Libs/MRML/Core/vtkMRMLAbstractViewNode.cxx
- Libs/MRML/Core/vtkMRMLAbstractViewNode.h
- Libs/MRML/Core/vtkMRMLSliceNode.cxx
- Libs/MRML/Widgets/qMRMLLayoutViewFactory.cxx
This is a small fix introduced in https://github.com/Slicer/Slicer/pull/8141
Kyle asked if it can be integrated in a separate PR:
https://github.com/Slicer/Slicer/pull/8141#discussion_r2038099444
to reproduce:
1) enter in dual monitor layout
2) load example nrrd file
3) Copy and paste in the python console
```
a = slicer.mrmlScene.GetNodeByID("vtkMRMLSliceNodeRed")
b = slicer.mrmlScene.GetNodeByID("vtkMRMLSliceNodeRed+")
a.Copy(b)
```
4) you get
With this fix:
@Sunderlandkyl @lassoan
> BUG: Adjust the FieldOfView to match the aspect ratio of the slice dimensions.

- Libs/MRML/Core/vtkMRMLMarkupsLineNode.cxx
- Libs/MRML/Core/vtkMRMLMarkupsLineNode.h
When start or end point of a markups line was not specified then calling `vtkMRMLMarkupsLineNode::GetLineStartPosition` and `vtkMRMLMarkupsLineNode::GetLineEndPosition` crashed.
fixes #8407
> BUG: Fix vtkMRMLMarkupsLineNode::GetLineStartPosition crash for empty node

- Libs/MRML/Core/vtkImageMathematicsAddon.cxx
- Modules/Loadable/VolumeRendering/MRML/vtkMRMLVolumeRenderingDisplayNode.cxx
- Modules/Loadable/VolumeRendering/MRML/vtkMRMLVolumeRenderingDisplayNode.h
- Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
- Modules/Loadable/VolumeRendering/Resources/UI/qSlicerVolumeRenderingModuleWidget.ui
- Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingModuleWidget.cxx
- Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingModuleWidget.h
When applying clipping to the volume, the clipped regions would be filled with "0", which could result in the region not being clipped if the transfer function had visible voxel values at "0". Fixed by adding adding ClippingBlankVoxelValue and AutoClippingBlankVoxelValue attributes. By default the clipped voxel value will be automatically set from vtkMRMLVolumeNode::GetImageBackgroundScalarComponentAsDouble(). The clipped scalar value can be set to any scalar by setting ClippingBlankVoxelValue when AutoClippingBlankVoxelValue is disabled.
> BUG: Fix volume rendering clipping for volumes with negative scalar

- SuperBuild/External_CTK.cmake
The current component in ctkVTKVolumePropertyWidget can now be changed, allowing transfer functions for components besides the first one to be visualized/changed.
$ git shortlog c68d1c9fa..9c9c1495d --no-merges
COMP: Fix CI removing use of deprecated "ubuntu-20-04" runner
ENH: Add option to set current component in ctkVTKVolumePropertyWidget
> ENH: Update CTK to add components to ctkVTKVolumePropertyWidget

- Modules/Loadable/Colors/Widgets/qMRMLColorPickerWidget.cxx
A color could be drag-and-drop to insert a new copy of the color in the color list view which wouldn't actually update the color table node. See video below:
https://github.com/user-attachments/assets/be74e3b6-50af-46b6-bf08-5a0e33c6f0e5
```python
picker_widget = slicer.qMRMLColorPickerWidget()
picker_widget.setMRMLScene(slicer.mrmlScene)
picker_widget.show()
```
This PR sets the qMRMLColorPickerWidget to set its Color List View to have no DragDrop so that the color table is not attempted to be updated in the color picker widget.
> BUG: Fix editing color list in picker widget

- Modules/Loadable/Colors/qSlicerColorsModule.cxx
With application setting "Subject Hierarchy->Use standard terminology" set to Off, then double-clicking on color in the Markups table produces the following result:
| `main` | This PR |
|--------|----------|
|![image](https://github.com/user-attachments/assets/72744b8e-460e-41d9-8e8f-5991fb7471f3)|![image](https://github.com/user-attachments/assets/08ba3b11-4966-46cc-979c-ae598de7c6b5)|
I have set the tab to remain the first tab which is the basic colors. This is because when not using standard terminology there is not a need for the "Labels" tab to be used where "GenericAnatomyColors" is essentially picking terminologies again. The "Labels" color picker functionality is a little weird in this dialog as do users really care to pick a specific color from a color table node? I would assume …
> ENH: Set color picker to use basic colors tab by default

- Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui
Removing the "Slicer" mention is to support the usage in a Slicer custom application which generally has a different application name.
This string exists in a UI file, so I re-worded it to remove the application name entirely rather than setting the tooltip from the code and utilizing `slicer.app.mainApplicationName`.
> ENH: Remove Slicer mention from Markups save to default display tooltip

- SuperBuild.cmake
Follow-up of kitware/VTK@d2176e7405 ("Remove obsolete PythonInitImpl.cxx file", 2025-01-13)
```
$ git shortlog b5aa0615a..b1fa50340 --no-merges
BUG: Fix wrapping error when using VTK 9.5
DOC: Update History section adding "VTK module Python wrapping"
```
> COMP: Update vtkAddon to fix wrapping error reported when using VTK 9.5

- Modules/Scripted/DICOMLib/DICOMProcesses.py
Sending SEG files to a DICOM server using DIMSE currently fails because the first storescu attempt will raise a UserWarning, so the second attempt with the modified storescu configuration doesn't go through.
This is the easiest and least intrusive solution I could come up with, although switching to dcmsend might be a good idea.
---
Catch `UserWarning` raised on failure of the initial `storescu` send attempt, allowing fallback to a custom configuration to proceed.
This restores functionality originally introduced in 21f8ba46beb ("ENH: Add custom DICOM send configuration", 2021-06-14), which was most likely broken by adb997269ba ("COMP: Refactor DICOMProcess and DICOMCommand", 2023-10-02).
> BUG: Restore fallback DICOM SEG upload with alternative storescu config

- SuperBuild/External_CTK.cmake
This work has been pulled out of https://github.com/Slicer/Slicer/pull/8427 for separate integration.
```
$ git shortlog 9c9c149..26688b1
COMP: Fix build error with VTK 9.5
```
* https://github.com/commontk/CTK/pull/1234
> COMP: Update CTK to fix build when using VTK 9.5

- Docs/user_guide/modules/volumerendering.md
- Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
- Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.h
On macOS graphics hardware, maximum 3D texture size (along any axis) is typically 2048. This commit sets volume partitioning partitioned to not exceed this size by default.
On other systems volume is maximum size is set to 4096 by default, which will not split up the volume in most cases (which was the behavior before this commit).
> ENH: Make it easier to render large volumes on macOS

- Libs/MRML/Widgets/qMRMLNodeComboBox.cxx
As indicated by the comment, enough time has passed for developers to update their code accordingly as part of understanding that vtkMRMLScalarVolumeNode does not have a LabelMap attribute anymore.
This warning was originally added in 2015 through https://github.com/Slicer/Slicer/commit/d071d05cd7c4ef91eeced7a9c1ef003bf9751710.
> ENH: Remove old deprecation warning

- Modules/Loadable/Terminologies/Widgets/Resources/UI/qSlicerTerminologyNavigatorWidget.ui
In the terminology navigator widget, the terminology context selector (to choose between general anatomy list, DICOM list, or custom color tables) was only shown when the category selector section was displayed (the small arrow button on the left was depressed). This made the navigator widget look simpler and nicer, but made it more difficult to switch to a different context.
This pull request makes the context selector always visible.
Old:
New:
@muratmaga
> ENH: Always show context selector in terminology navigator

- Modules/Loadable/Markups/Testing/Cxx/vtkMarkupsAnnotationSceneTest.cxx
As of https://github.com/Slicer/Slicer/commit/a2c948e33eb216d8649ee52007d4ebc9459a1c5b, SetActiveTag deprecation is no longer warned upon reading old scenes.
@Sunderlandkyl The vtkMRMLAnnotationSceneTest is still failing after this fix from me. As seen at https://slicer.cdash.org/tests/29823763?graph=status the test began failing on 2025-03-24 which would correspond to changes you made in https://github.com/Slicer/Slicer/commit/fb6fb19ef37f60abc7c021c688560fedd1ccfebe the day prior.
```
Line 155 - scene->GetNumberOfNodesByClass("vtkMRMLAnnotationPointDisplayNode") != 0 : CheckInt failed
current :10
expected:0
```
> BUG: Fix incorrect expected warnings in vtkMRMLAnnotationSceneTest

- Base/QTCore/Testing/Python/qSlicerModuleGenericTest.py.in
The `unittest.assertRegexpMatches` function was deprecated in Python 3.2 and removed[^1] in Python 3.12.
[^1]: https://docs.python.org/3.12/library/unittest.html#unittest.TestCase.assertRegex
> ENH: Replace deprecated assertRegexpMatches with assertRegex to support Python 3.12+

- Libs/MRML/Core/vtkMRMLSequenceStorageNode.cxx
Follow-up of e09415ba361 ("ENH: Integrate Sequences extension into Slicer core (#4810)", 2020-04-17) in which the includes were originally introduced by not used.
> COMP: Remove unused Qt includes in vtkMRMLSequenceStorageNode.cxx

- Libs/MRML/Core/vtkMRMLLogic.cxx
- Libs/MRML/Core/vtkMRMLLogic.h
- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLScene.h
The utility methods `RemoveUnreferencedStorageNodes` and `RemoveUnreferencedDisplayNodes` were originally introduced in commit https://github.com/Slicer/Slicer/commit/e6ae7b96b162aad2866e488d7ddc8a89392e6e0b (2010-04-17) to support cleanup before scene serialization. They became unused after commit https://github.com/Slicer/Slicer/commit/f8fb837370b5fd1d3b12e78eccad62ab9c67f183 (2012-06-07) but remain useful for debugging or manual scene maintenance.
To improve cohesion, these functions are now part of vtkMRMLScene, where their behavior is more semantically appropriate.
Keeping these methods available helps address issues with orphaned nodes that occasionally appear in scenes, possibly due to misbehaving modules or bugs elsewhere in the pipeline.
---
Related pull request:
* …
> COMP: Move unreferenced node cleanup methods from MRMLLogic to MRMLScene 

- Base/Logic/vtkSlicerApplicationLogic.cxx
- Base/Logic/vtkSlicerApplicationLogicRequests.h
These includes are obsolete since 591c567ace8 ("ENH: Simplified vtkSlicerApplicationLogic", 2015-11-30)
---
Related pull request:
* https://github.com/Slicer/Slicer/pull/8004
> COMP: Remove obsolete includes from vtkSlicerApplicationLogic

- requirements-docs.txt
This PR will help boost the OpenSSF score for Slicer (https://securityscorecards.dev/viewer/?uri=github.com/Slicer/Slicer) which is currently getting docked for vulnerabilities in the Slicer documents requirements file. These issues are being warned in https://github.com/Slicer/Slicer/security/code-scanning/29.
This addresses issues for the following packages:
lxml issues:
https://github.com/advisories/GHSA-55x5-fj6c-h6m8
https://github.com/advisories/GHSA-57qw-cc2g-pv5p
https://github.com/advisories/GHSA-jq4v-f5q6-mjqq
https://github.com/advisories/GHSA-pgww-xf46-h92r
https://github.com/advisories/GHSA-wrxv-2j5q-m38w
https://github.com/advisories/GHSA-xp26-p53h-6h2p
pygments issue:
https://github.com/advisories/GHSA-mrwq-x4v8-fh7p
requests issue: …
> ENH: Bump docs dependencies to resolve vulnerability alerts

- Base/Python/CMakeLists.txt
Prevents the following warning from being reported on startup:
```
No module named 'qSlicerBaseQTCLIPython'
```
Follow-up of 2b3a9c19a11 ("COMP: Fix macOS build removing obsolete VTK wrapping of qSlicerBaseQTCLI", 2025-06-11)
---
* https://github.com/Slicer/Slicer/pull/8475
* https://github.com/Slicer/Slicer/pull/8004
> BUG: Do not attempt to import obsolete qSlicerBaseQTCLIPython module

- .github/workflows/lint.yml
- .readthedocs.yaml
- CMakeLists.txt
- SuperBuild/External_python-dicom-requirements.cmake
- SuperBuild/External_python-extension-manager-ssl-requirements.cmake
- SuperBuild/External_python-numpy.cmake
- SuperBuild/External_python-requests-requirements.cmake
- SuperBuild/External_python-scipy.cmake
- SuperBuild/External_python.cmake
This pull request was created to include the changes originally integrated through this pull requests:
* https://github.com/Slicer/Slicer/pull/8456
For the sake of having a clean history and considering the updated `main` branch has not been referenced externally, `main` was forced push to https://github.com/Slicer/Slicer/commit/4b1666ec317ab1885f1b02354ac2f78708cb29f4
---- 
> [!IMPORTANT]
> This pull request should be rebased & integrated *only* after the pull requests referenced below are themselves reviewed & integrated:
> * https://github.com/Slicer/Slicer/pull/8454
> * https://github.com/Slicer/Slicer/pull/8457
> * https://github.com/Slicer/Slicer/pull/8459
> * https://github.com/Slicer/Slicer/pull/8461
> * https://github.com/Slicer/Slicer/pull/8467
> * …
> ENH: Upgrade from python 3.9.10 to 3.12.10

- .pre-commit-config.yaml
- Base/Python/slicer/parameterNodeWrapper/guiConnectors.py
- Base/Python/slicer/parameterNodeWrapper/wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper.py
- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py
- Base/Python/slicer/tests/test_slicer_parameter_pack.py
- Modules/Scripted/DICOMLib/DICOMProcesses.py
- Modules/Scripted/DICOMLib/DICOMUtils.py
- Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py
- Modules/Scripted/WebServer/WebServer.py
- Modules/Scripted/WebServer/WebServerLib/BaseRequestHandler.py
- Modules/Scripted/WebServer/WebServerLib/DICOMRequestHandler.py
- Modules/Scripted/WebServer/WebServerLib/SlicerRequestHandler.py
- Modules/Scripted/WebServer/WebServerLib/StaticPagesRequestHandler.py
- Utilities/Templates/Modules/Scripted/TemplateKey.py
This follows up Slicer's switch from Python 3.9 to Python 3.12 in https://github.com/Slicer/Slicer/commit/5e952f7c5b031dd32858f245e18719e09099117c.
Changes were automatically applied by running:
`python -m pre_commit run --all-files`
> ENH: Enforce python 3.12 and newer syntax

- SuperBuild/External_CTK.cmake
```
$ git shortlog 26688b15f..ca28a23b9 --no-merges
Hans Johnson (1):
COMP: Support build using CMake 4+ by consistently requiring CMake 3.16.3 (#1236)
Pierre Bour (1):
ENH: Draw ctkAxesWidget axes based on widget state
```
> BUG: Update CTK to improve ctkAxesWidget styling and support CMake 4+

- SuperBuild/External_JsonCpp.cmake
<details><summary>List of JsonCpp changes:</summary>
<p>
```
$ git shortlog 0.10.6..1.9.6 --no-merges
Aaron Jacobs (1):
Remove undefined behavior from a left shift of a negative value.
Abigail Bunyan (1):
Add missing classes to forwards.h
Adam Boseley (1):
By default use <prefix> relative paths when installing
Alex Beregszaszi (2):
Document skipBom in CharReaderBuilder (#1332)
Introduce CharReaderBuilder::ecma404Mode (#1333)
Alexander Gazarov (1):
Replaced the template-based solution for avoiding calls to localeconv() with a macro-based one (fixes #527)
Alexander V. Brezgin (4):
Remove repeated condition
Optimize value range check
Optimize value check
Optimize Value::isIntegral() method
Andrea Pappacoda (1):
build(meson): use find_program('python3') (#1386)
Andrew Childs (1):
json_writer: …
```
> ENH: Update JsonCpp from 0.10.6 to 1.9.6

- Libs/MRML/Core/CMakeLists.txt
- Modules/Loadable/Markups/MRML/CMakeLists.txt
- Modules/Loadable/Terminologies/Logic/CMakeLists.txt
- Modules/Loadable/Volumes/Logic/CMakeLists.txt
- SuperBuild/External_RapidJSON.cmake
This pull request updates the RapidJSON external project to update RapidJSON by integrating Slicer-specific patches and modernize the build process:
* Update RapidJSON external project to download source from Slicer fork
* Update the external project to install RapidJSON, as the generated config file cannot be imported via `find_package(RapidJSON)` when used from a build tree.
* Follow-up on d42156b1224 ("ENH: Use RapidJSON instead of JsonCPP in Terminologies module logic", 2017-01-20) removing the use of `RapidJSON_INCLUDE_DIR` variable and instead use the `RapidJSON` imported target.
The following upstream pull requests have been backported into the [slicer-2024-12-22-24b5e7a8](https://github.com/Slicer/rapidjson/tree/slicer-2024-12-22-24b5e7a8) branch:
* …
> COMP: Update RapidJSON to latest revision

- SuperBuild/External_RapidJSON.cmake
Set the `CMAKE_INSTALL_DIR` variable to ensure CMake configuration files (`RapidJSONConfig.cmake`, `RapidJSONConfigVersion.cmake`, `RapidJSON-targets.cmake`) are installed in a consistent location across platforms.
This fixes regression introduced in 0e905e91b ("COMP: Update RapidJSON to include optimization, compiler and build-system fixes", 2025-06-24) and resolves errors like the following on Windows when calling `find_package(RapidJSON REQUIRED)` in Slicer modules (e.g., Terminologies):
```
CMake Error at C:/path/to/S-0-build/RapidJSON-install/lib/cmake/RapidJSON/RapidJSONConfig.cmake:3 (include):
include could not find requested file:
C:/path/to/S-0-build/RapidJSON-install/lib/cmake/RapidJSON/RapidJSON-targets.cmake …
```
> COMP: Fix configuration on Windows by updating RapidJSON project installation

- SuperBuild/External_OpenSSL.cmake
Newer compilers require explicit inclusion of string.h for memcmp function usage.
> COMP: OpenSSL 1.1.1w is needed to fix missing include

- Docs/developer_guide/script_repository/segmentations.md
Update "Get centroid of a segment in world (RAS) coordinates" entry to follow-up on API change introduced in fcb40b0 ("ENH: Add support for shared binary labelmap segmentations", 2019-10-08).
The signature of `GetBinaryLabelmapRepresentation` changed, and there was a typo in a variable name.
> DOC: Fix entry in "Script repository / Segmentations"

- SuperBuild/External_OpenSSL.cmake
Follow-up to ebdd8127bbf ("COMP: OpenSSL 1.1.1w is needed to fix missing include", 2025-03-08) to resolve build issues on macOS when linking against a zlib library located in a non-system path.
While the upstream fix (openssl/openssl#12238) has been integrated into the OpenSSL 3.x series, this patch applies a backported fix by downloading `openssl-1.1.1w-pr12238.tar.gz`, which includes the necessary modifications for OpenSSL 1.1.1w.
* https://github.com/Slicer/Slicer/pull/8504
> COMP: Fix OpenSSL 1.1.1w build on macOS with non-system zlib

- Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx
- Modules/Loadable/Volumes/Resources/Schema/volumes-display-presets-schema-v1.0.1.json
- Modules/Loadable/Volumes/Resources/VolumeDisplayPresets.json
- Utilities/Scripts/update_translations.py
MONAIAuto3DSeg extension has a model description json file, which contains model title, description, etc., which is displayed on the GUI and therefore have to be translatable to different languages.
A general-purpose mechanism is implemented to detect if a json file is translatable (a filename-schema.json file is present in the same folder) and determine which properties are translatable (those that have their "transatable" custom property set to true).
> ENH: Make JSON files in extensions translatable

- SuperBuild/External_ITK.cmake
- SuperBuild/External_PCRE2.cmake
- SuperBuild/External_SimpleITK.cmake
- SuperBuild/External_Swig.cmake
I had come across this syntax warning when using the SimpleITK version in Slicer which was resolved by https://github.com/SimpleITK/SimpleITK/commit/3899a1314eb32f64af2231061d1e87ba5f75bcf4 as originally included in SimpleITK 2.5.0. This PR updates SimpleITK from a version based on 2.3.1 to a version based on 2.5.2. Other supporting dependencies related to SimpleITK have also been updated to the same versions that SimpleITK uses in its superbuild (such as SWIG 4.3.1).
```
..\Lib\site-packages\SimpleITK\extra.py:476: SyntaxWarning: invalid escape sequence '\s'
\sa itk::simple::DiscreteGaussianImageFilter for the object oriented interface
```
A clean build on Windows was successful as well as packaging.
Follow-up of the following pull request:
* https://github.com/Slicer/Slicer/pull/8339
> COMP: Update SimpleITK to 2.5.2 and corresponding dependencies

- Base/QTCore/qSlicerCoreCommandOptions.h
Update the `Q_PROPERTY` declaration for `extraPythonScriptProcessedArgumentsCount` to use int instead of `QString`.
This corrects the property type to match the actual return type of the associated getter. The mismatch was identified during the transition to Qt6.
Follow-up on 0cf480de872 ("BUG: Fix launching .py files using Slicer with -I argument", 2023-05-12)
> COMP: Fix return type of extraPythonScriptProcessedArgumentsCount property

- Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.cxx
- Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.h
- Libs/MRML/Widgets/qMRMLVolumeInfoWidget.cxx
- Libs/MRML/Widgets/qMRMLVolumeInfoWidget.h
When a volume display node was used as a sequence proxy node, a duplicate window/level preset was added at each node modification.
> BUG: Prevent WindowLevelPreset duplication in volume display node

- Libs/vtkITK/itkConstrainedValueMultiplicationImageFilter.h
- Libs/vtkITK/vtkITKArchetypeImageSeriesReader.cxx
- Introduced `max_closet_representable` constant for IEEE-754 double
representation range.
- Adjusted comparisons in `vtkITKArchetypeImageSeriesReader.cxx` and
`itkConstrainedValueMultiplicationImageFilter.h` to resolve rounding
edge cases for large integer values.
IEEE‑754 double can exactly represent all integers in the range [–2⁵³,
2⁵³], but beyond that, only some integer numbers are representable.
18446744073709551615 (2⁶⁴−1) must be rounded to the nearest representable double: 18446744073709551616
Libs/vtkITK/itkConstrainedValueMultiplicationImageFilter.h:68:32: warning: implicit conversion from 'slicer_itk::NumericTraits<long>::ValueType' (aka 'long') to 'double' changes value from 9223372036854775807 to 9223372036854775808 …
> COMP: Ensure correct handling of maximum representable double values

- Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMExportDialog.cxx
QObject baseclass must be the first in list of multiple inheritance for
automoc to work.
> COMP: QObject must be listed first in multiple inheritance

- Base/QTCore/qSlicerCoreApplication.cxx
- Base/QTCore/qSlicerCorePythonManager.cxx
COMP: Resolve #8460
Update qSlicerCoreApplication.cxx to replace use of PySys_SetArgvEx
with PyConfig.argv as suggested in https://docs.python.org/3/c-api/init.html#c.PySys_SetArgvEx
- **ENH: Update Python initialization for compatibility with isolated mode**
- **ENH: Update Python initialization to use PyConfig API**
> slicer update python initialization 8460

- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx
All math can be performed as integers to avoid implicit type changes.
warning: using floating point absolute value function 'fabs' when
argument is of integer type
> COMP: Replace `fabs` with `std::abs` for consistency in types

- Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.h
Ensure proper method overriding and adherence to C++ best practices.
warning: showViewContextMenuActionsForItem' overrides a member function
but is not marked 'override
> COMP: `showViewContextMenuActionsForItem` as `override`

- Base/QTGUI/qSlicerModuleFinderDialog.cxx
- Modules/Loadable/Colors/Widgets/qMRMLColorPickerWidget.cxx
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentsTableView.cxx
Qt uses type ID check + static_cast for casting QEvent to more specific classes for performance reasons. Using dynamic_cast would be slower due to complexity of RTTI. qobject_cast does not use RTTI, so it is faster, but Qt event objects are not derived from QObject, so it cannot be used here.
See more discussion at https://github.com/Slicer/Slicer/pull/8555
> STYLE: Explain static_cast use in Qt event handling

- Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentsPlugin.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyCloneNodePlugin.cxx
Assume that the last "0.5" argument was supposed to be the
WeightAdjustment instead of weight.
```c++
setActionPosition(QAction* action, int section, int weight /*=0*/, double weightAdjustment /*=0.0*/)
```
Implicit conversion from 'double' to 'int' changes value from 0.5 to 0
> BUG: Incorrect number of arguments given when weightAdjustment was desired.

- SuperBuild/External_CTK.cmake
This is a follow-up to previous Slicer PR #7475. 
The update CTK uses a branch of PythonQt that now includes Qt 5.15 wrappers unlike the older branch. Reviewing https://doc.qt.io/qt-5/newclasses515.html#new-enum-types, this now allows me to use https://doc.qt.io/qt-5/qtabbar.html#setTabVisible which was specifically introduced in Qt 5.15. This usage has currently been unavailable in latest Slicer.
```
CTK:
$ git shortlog 5269887..fcf31fc
Hans Johnson (1):
COMP: Add conditional for VTK version in color assignment
COMP: Update PythonQt to branch based off upstream v3.6.1
```
> COMP: Update CTK with PythonQt wrapping support for Qt 5.15

- Base/Python/slicer/__init__.py
- Add slicer __init__ kit  relative import when using Slicer as a python library
> ENH: Enable relative import of Slicer Python-wrapped libraries

- Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.cxx
- Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.h
- Libs/vtkSegmentationCore/vtkSegmentation.cxx
- Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx
- Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.h
- Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentsPlugin.cxx
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationDisplayNodeWidget.cxx
- Modules/Loadable/Segmentations/qSlicerSegmentationsModule.cxx
- Modules/Loadable/Segmentations/qSlicerSegmentationsModuleWidget.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel.h
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyModel_p.h
- Modules/Loadable/Transforms/Testing/Cxx/qSlicerTransformsModuleWidgetTest.cxx
Subject hierarchy item order are now synchronized between:
- subject hierarchy singleton node in the scene
- subject hierarchy item model of all subject hierarchy Widgets
- segments of each segmentation node
This is implemented by two-way synchronization between: qMRMLSubjectHierarchyModel <-> subject hierarchy node (in qMRMLSubjectHierarchyModel) and subject hierarchy node <-> segmentation nodes (in qSlicerSubjectHierarchySegmentationsPlugin).
fixes #8421
@muratmaga
> BUG: Fix reordering of subject hierarchy nodes

- Base/QTCore/qSlicerCoreCommandOptions.cxx
- Base/QTCore/qSlicerCoreCommandOptions.h
When Slicer is built with `Slicer_USE_PYTHONQT` set to `OFF`, the method `qSlicerCoreCommandOptions::isPythonDisabled()` should still be available and consistently return `true`, indicating that Python support is not enabled.
This change ensures the method is always defined by moving the `#ifdef` inside the function body. It also updates the `Q_PROPERTY` to be unconditionally available.
> COMP: Ensure `isPythonDisabled` is defined regardless of Python support

- Base/QTCore/Testing/Cxx/qSlicerApplicationUpdateManagerTest.cxx
- Base/QTCore/Testing/Cxx/qSlicerExtensionsManagerModelTest.cxx
- Base/QTCore/qSlicerExtensionsManagerModel.cxx
- Base/QTGUI/Testing/Cxx/qSlicerScriptedLoadableModuleTest.cxx
- Base/QTGUI/Testing/Cxx/qSlicerScriptedLoadableModuleWidgetTest.cxx
The regression introduced in commit d36781511c ("COMP: Refactor QDir assignment to use setPath for consistency", 2025-07-03) used `QDir::dirName()` instead of `QDir::path()` in several locations. Since `dirName()` returns only the last component of the directory path (e.g., the leaf), it resulted in incorrect paths being assigned to `QDir` instances.
This caused failures in both extension extraction and temporary directory setup during tests.
This commit restores the correct behavior by replacing `dirName()` with `path()` in the affected locations.
The following tests now pass:
- `qSlicerExtensionsManagerModelTest`
- `qSlicerApplicationUpdateManagerTest`
- `qSlicerScriptedLoadableModuleTest`
- `qSlicerScriptedLoadableModuleWidgetTest`
----
Follow-up if the following pull requests:
* …
> BUG: Fix incorrect QDir assignment introduced during refactoring

- .clang-format
- Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DExtended.h
- Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DExtended.txx
- Modules/CLI/ResampleDTIVolume/itkMatrixExtended.h
- Modules/CLI/ResampleDTIVolume/itkMatrixExtended.txx
- Modules/CLI/RobustStatisticsSegmenter/SFLSRobustStatSegmentor3DLabelMap_single.h
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorEraseEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx
This applies formatting to C++ source files based on `clang-format` settings introduced in the following commit.
The updated settings define `QualifierOrder` to enforce consistent qualifier placement (e.g., `const T` instead of `T const`) across the codebase.
The specific ordering was chosen to **minimize the number of changes** observed when running `clang-format` via `pre-commit`, resulting in minimal disruption.
This improves code readability and simplifies future refactoring.
Running `pre-commit` required updating the `.clang-format` configuration with
the following patch:
```diff
diff --git a/.clang-format b/.clang-format
--- a/.clang-format
+++ b/.clang-format
@@ -37,6 +37,14 @@ ForEachMacros:
- Q_FOREACH
- Q_FOREVER
+QualifierAlignment: Custom
+QualifierOrder:
+  - friend
+  - …
```
> STYLE: Normalize qualifier order

- Modules/Loadable/VolumeRendering/Widgets/qMRMLVolumePropertyNodeWidget.cxx
When selecting RGBA volume rendering the intended behavior was to select the first component, which is used to control the volume opacity. Instead, the first component was selected when "independent" was enabled.
Fixed by using the check state of the RGBColorsRadioButton instead of IndependentRadioButton.
> BUG: Select first component when RGBA volume rendering is selected

- Modules/Loadable/VolumeRendering/Widgets/qMRMLVolumePropertyNodeWidget.cxx
This commit leaves the value of the spinbox when switching between RGBA/independent component modes. The value in the spinbox is only used in independent mode, otherwise the selected component is always 0.
See:
https://github.com/Slicer/Slicer/pull/8587#pullrequestreview-3034451745
> ENH: Avoid changing selected volume rendering component when switching modes

- Base/QTCore/Testing/Cxx/qSlicerExtensionsManagerModelTest.cxx
- Base/QTCore/Testing/Cxx/qSlicerUtilsTest1.cxx
- Base/QTCore/qSlicerCoreApplication.cxx
- Libs/MRML/Widgets/Testing/qMRMLNodeComboBoxTest8.cxx
- Modules/Loadable/SlicerWelcome/qSlicerWelcomeModuleWidget.cxx
This commit fixes regressions introduced in f06fab25fc ("COMP: Prefer C++11 range-for to Qt macros", 2025-07-16), which replaced `Q_FOREACH` with C++11 range-based `for` loops.
A segmentation fault was reported in `qSlicerWelcomeModuleWidgetPrivate::setupUi`, caused by iterating over a temporary `QWidgetList` constructed inline using the `<<` operator. Since range-based `for` loops do not extend the lifetime of temporaries, the container was destroyed after the loop header executed, leading to a **use-after-free** and a crash when dereferencing the iterator.
Similar crashes were observed in tests on Unix systems involving temporary `QStringList` instances. Although `QStringList` (a `QList<QString>`) uses implicit sharing, range-based iteration over a destroyed temporary is still undefined …
> BUG: Fix crashes caused by range-based loops over temporary Qt containers

- Modules/Loadable/VolumeRendering/MRML/vtkMRMLVolumePropertyJsonStorageNode.cxx
Adds a missing return call from vtkMRMLVolumePropertyJsonStorageNode::WriteVolumePropertyNode. Also fixes some style issues, unused variable and return types in vtkMRMLVolumePropertyJsonStorageNode.
> BUG: Add missing return from WriteVolumePropertyNode

- SuperBuild/External_bzip2.cmake
This is work addressing https://github.com/Slicer/Slicer/pull/8575#pullrequestreview-3034557033.
This switches to a newer version of bzip2 located at the official upstream. This is made possible because bzip2 has been CMake-fied since CommonTK began having its own separate fork of the project.
> COMP: Update bzip2 from 1.0.8 to 1.1.0 to resolve CMake deprecation issues

- SuperBuild/External_zlib.cmake
Slicer is currently using zlib version 1.2.3 originally released July 18th, 2005. Slicer has been using a [fork](https://github.com/commontk/zlib) in the CommonTK repo where zlib was CMake'ified since at least 2012. Since then zlib has made it onto GitHub at https://github.com/madler/zlib and also utilizes CMake. The latest release is [1.2.13](https://github.com/madler/zlib/tree/v1.2.13) released on Oct 13th, 2022.
This PR updates zlib used in Slicer to now be the modern forked version known as [zlib-ng](https://github.com/zlib-ng/zlib-ng).  Read the [history](https://github.com/zlib-ng/zlib-ng#history) about zlib-ng. I have configured zlib-ng to be built in zlib-compat mode rather than zlib-ng native mode. This decision matches what ITK has done as they switched to using zlib-ng as part …
> COMP: Switch from zlib 1.2.3 to maintained zlib-ng 2.2.4 fork

- SuperBuild/External_zlib.cmake
Follow-up of cd73e84d93 ("COMP: Switch from zlib 1.2.3 to maintained zlib-ng 2.2.4 fork", 2022-11-28) introduced through the following pull request:
* https://github.com/Slicer/Slicer/pull/6708
> COMP: Fix linux build always installing zlib-ng library is "lib" directory

- Base/Python/slicer/tests/test_slicer_parameter_node_wrapper_guis.py
- Docs/developer_guide/parameter_nodes/gui_connection.md
- Modules/Loadable/SubjectHierarchy/SubjectHierarchyLib/parameterNodeWrapper/guiConnectors.py
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyComboBox.h
- Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h
Parameter node wrapper GUI connector was not implemented for many widgets (#7308), including qMRMLSubjectHierarchyComboBox. This commit adds a connector that can read/write qMRMLSubjectHierarchyComboBox as a MRML node.
fixes #7905
> ENH: Add parameter node GUI connector for qMRMLSubjectHierarchyComboBox

- Libs/MRML/Widgets/Testing/qMRMLNodeAttributeTableViewTest.cxx
This pull requests introduces two related changes:
----
This fixes a regression introduced in 1290285 ("COMP: Remove unnecessary empty string initialization", 2025-07-13) by reverting changes specific to `qMRMLNodeAttributeTableViewTest` in which differentiating an empty an a null `QString` is important.
Related pull request: https://github.com/Slicer/Slicer/pull/8558
----
Add trailing `//` comments to guide clang-format and improve alignment of input and output parameters.
This restores alignment lost due to automatic formatting in b26d778 ("STYLE: Consistent formatting of C++ sources using clang-format", 2025-07-12), which was inadvertently omitted in a prior commit intended to preserve such alignment: 2d10f6b ("STYLE: Add `//` comments to preserve wrapping before clang-format …
> BUG: Fix qMRMLNodeAttributeTableViewTest reintroducing empty QString init

- Libs/MRML/Widgets/Resources/UI/qMRMLScreenShotDialog.ui
- Libs/MRML/Widgets/qMRMLScreenShotDialog.cxx
- Libs/MRML/Widgets/qMRMLScreenShotDialog.h
- Modules/Loadable/SceneViews/GUI/qSlicerSceneViewsModuleDialog.cxx
- Modules/Loadable/SceneViews/GUI/qSlicerSceneViewsModuleDialog.h
- Modules/Loadable/SceneViews/GUI/qSlicerSceneViewsModuleWidget.cxx
- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx
- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.h
Previously users could only select node categories "display", "view" or "existing" (when editing a scene view). With this change, the scene view dialog now contains an "Advanced" section that allows the user to select any nodes in the scene. This node selection section is synchronized with the "display" , "view", and "existing" node check boxes.
> ENH: Add widget to select any node for scene views

- Modules/Loadable/SceneViews/Logic/vtkSlicerSceneViewsModuleLogic.cxx
In vtkSlicerSceneViewsModuleLogic::GetViewNodeClasses(), vtkMRMLSliceLogic should be vtkMRMLSliceCompositeNode.
> BUG: Fix invalid node type in GetViewNodeClasses()

- Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
Fixes the issue reported at https://discourse.slicer.org/t/dashes-silently-removed-from-filename-in-export-to-file-operation/43923
> BUG: Fix removal of dash characters from exported segmentation filename

- Libs/MRML/Core/Testing/vtkMRMLTextStorageNodeTest1.cxx
- Libs/MRML/Widgets/Testing/qMRMLUtf8Test1.cxx
- Modules/Loadable/Units/Logic/vtkSlicerUnitsLogic.cxx
Fixes build failures on C++20 due to invalid conversion from 'const char8_t*' to 'const char*' when using u8"\u00b5m"‑style literals for Micrometer, Square Micrometer, Cubic Micrometer, and Microsecond units. All u8"\u00b5…" suffixes have been changed to "\u00b5…" so that AddUnitNodeToScene(..., const char* suffix, ...) no longer rejects them.
Error log excerpt:
```
/usr/src/RPM/BUILD/slicer-5.8.0/Modules/Loadable/Units/Logic/vtkSlicerUnitsLogic.cxx:227:33: error: invalid conversion from 'const char8_t*' to 'const char*' [-fpermissive]
227 |     "Micrometer", "length", "", u8"\u00b5m", 4, …
|                                 ^~~~~~~~~~~
|                                 |
|                                 const char8_t*
/usr/src/RPM/BUILD/slicer-5.8.0/Modules/Loadable/Units/Logic/vtkSlicerU …
```
> BUG: Replace u8‑prefixed unit suffix literals with narrow strings

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Docs/user_guide/about.md
- GOVERNANCE.md
Key changes include:
- Correcting the BDFL reference in `CODE_OF_CONDUCT.md`
- Simplifying the integration of `GOVERNANCE.md` content in `about.md` using the `heading-offset` option for the `include` directive.
- Adding a dedicated "Code of Conduct" subsection to the About page.
- Updating the `CONTRIBUTING.md` file to reference GitHub Actions for CI testing.
- Reflecting the current review process in `CONTRIBUTING.md`, specifying that at least one review approval is required.
> DOC: Reference "Code of Conduct" in Governance section and Update contribution processes

- Libs/MRML/Widgets/qMRMLWidget.cxx
This closes #8647.
This is a follow-up to https://github.com/Slicer/Slicer/commit/47e89f94da6c8c8faa55de1ddcb50b5608d92a2f which removes the workaround that was setting the OpenGL compatibility profile as default on the Windows platform. The original rendering issues on Intel integrated graphics while use the OpenGL core profile appear to happen less often. Removing the workaround is motivated by rendering issues observed when Nvidia GPUs using the compatibility profile faced rendering issues related to Plot Markers which were not issues upon switching to the core profile.
See https://github.com/Slicer/Slicer/issues/8647#issuecomment-3203747715 for more details.
> ENH: Restore OpenGL core profile usage on Windows platform

- .clang-format
- Base/Logic/vtkImageFillROI.cxx
- Base/Logic/vtkImageFillROI.h
- Base/Logic/vtkImageRectangularSource.cxx
- Base/QTGUI/qSlicerModuleFactoryFilterModel.cxx
- Libs/MRML/Core/Testing/vtkArchiveTest1.cxx
- Libs/MRML/Core/Testing/vtkMRMLVolumeNodeTest1.cxx
- Libs/MRML/Core/vtkEventBroker.h
- Libs/MRML/Core/vtkMRMLColorTableStorageNode.cxx
- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLTransformDisplayNode.cxx
- Libs/MRML/Core/vtkObservation.cxx
- Libs/MRML/DisplayableManager/vtkMRMLOrientationMarkerDisplayableManager.cxx
- Libs/MRML/Logic/vtkImageNeighborhoodFilter.cxx
- Libs/MRML/Widgets/qMRMLNodeComboBoxDelegate.cxx
- Libs/MRML/Widgets/qMRMLTreeView.cxx
- Libs/vtkITK/vtkITKArchetypeImageSeriesReader.h
- Libs/vtkTeem/vtkDiffusionTensorMathematics.cxx
- Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationControlPointsNode.cxx
- Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationLinesNode.cxx
- Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationNode.cxx
- Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
Insert braces after control statements (if, else, for, do, and while) in C++ unless the control statements are inside macro definitions or the braces would enclose preprocessor directives.
See https://releases.llvm.org/20.1.0/tools/clang/docs/ClangFormatStyleOptions.html#insertbraces
> STYLE: Normalize insertion of braces after control statements

- SuperBuild/External_CTK.cmake
On some computers, VTK views were not updating until the mouse was moved on the screen.
This was due to Qt not repainting the view after the VTK rendering was completed, because the widget was not scheduled for repaint.
```
$ git shortlog fcf31fc6d..7ef24ed9a --no-merges
BUG: Fixed VTK views not updating
Davide Punzo (4):
COMP: Exclude VSCode settings files
COMP: Create a dedicated class for ctkDICOMMetadataDialog
ENH: Set ctkDICOMMetadataDialog as non-modal window
COMP: Fix ctkDICOMSchedulerTest1 test
Hans Johnson (1):
COMP: Replace QDir assignment with setPath() (PR-1248)
```
Fixes #7206
> BUG: Update CTK to ensure VTK views are always up-to-date

- Modules/Scripted/LineProfile/LineProfile.py
Change suggested by @jamesobutler 
This change allows for the line plot to be dynamically updated even before the user places the second point, and greatly reduces VTK warnings logged in the python console.
Main:
https://github.com/user-attachments/assets/7de323b3-2362-41e2-a13f-bd9540a35cdd
This PR:
https://github.com/user-attachments/assets/18c98d3a-848b-42a7-9dbe-96df5b48b93a
> BUG: Fix VTK errors drawing line profile plot with undefined points

- Base/Logic/CMakeLists.txt
- Base/Logic/vtkSlicerApplicationLogic.cxx
- Base/Logic/vtkSlicerApplicationLogic.h
- Docs/developer_guide/modules/colors.md
- Docs/developer_guide/script_repository/gui.md
- Docs/developer_guide/script_repository/markups.md
- Docs/developer_guide/script_repository/segmentations.md
- Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
- Libs/MRML/Logic/vtkMRMLSliceLogic.h
- Libs/MRML/Logic/vtkMRMLViewLogic.cxx
- Libs/MRML/Logic/vtkMRMLViewLogic.h
- Libs/MRML/Widgets/qMRMLLayoutManager.cxx
- Libs/MRML/Widgets/qMRMLSliceView.cxx
- Libs/MRML/Widgets/qMRMLSliceView.h
- Libs/MRML/Widgets/qMRMLThreeDView.cxx
- Libs/MRML/Widgets/qMRMLThreeDView.h
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect.cxx
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyViewContextMenuPlugin.cxx
This adds `vtkSlicerApplicationLogic::GetViewDisplayableManagerByClassName` to access a view’s displayable manager by class name without relying on Qt view classes. The layout factories now propagate each view’s `vtkMRMLDisplayableManagerGroup` into the corresponding MRML logic (`vtkMRMLSliceLogic` / `vtkMRMLViewLogic`), which keeps a weak reference.
Motivation: decouple effects and scripts from Qt to support headless and trame-backed frontends.
Key changes:
- Base/Logic links against `MRMLDisplayableManager` and includes headers.
- Add `DisplayableManagerGroup` setters/getters to Slice/View logics with type validation.
- Refactor Segment Editor and Subject Hierarchy code paths to use the new ApplicationLogic API.
- Update developer docs and script repository examples accordingly.
Notes: …
> ENH: Add API to retrieve view displayable managers without Qt widgets

- SuperBuild/External_VTK.cmake
This includes a collection of bug fixes including a fix for ImageSliceMapper with Apple Clang 17.0.0. See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/12347.
On Windows:
Build: ✔️  
Package: ✔️  
Test: ✔️ (no new tests failing compared to current `main`)
```
$ git shortlog 294f4a7..3b61f10 --no-merges
Alexy Pellegrini (4):
[Backport] Reduce build time and binary directory size of vtkCommonCore
[Backport] Add vtk<Type>Array to bulk instantiation
[Backport] Cleanup extern template declarations in data arrays
[Backport] Reduce number of std::shared_ptr instantiations in StructuredPointArray.txx
Ben Boeckel (3):
gitlab-ci: remove submodule support
Filters/CellGrid: fix header list typo
vtkMath: fix copy pasta for `EnableT` docs for `::Dot()`
Bengt Rosenberger (1):
Fix division by zero …
```
> COMP: Update VTK to 9.5.1

- CMake/ExternalProjectDependency.cmake
- Extensions/CMake/SlicerBlockBuildPackageAndUploadExtensions.cmake
- SuperBuild/External_CTK.cmake
This pull request updates the build system to ensure the `BUILD_JOB_SERVER_AWARE` option is set for external projects when using CMake >= 3.28. It addresses the `gmake[N]: *** read jobs  pipe: Bad file descriptor.` issue associated with the build command.
1. Modify `ExternalProjectDependency.cmake` to set `BUILD_JOB_SERVER_AWARE`.
2. Update CTK configuration to ensure `BUILD_JOB_SERVER_AWARE` is set.
3. Ensure this option is also set for extensions external projects
See https://discourse.slicer.org/t/slicer-build-environment-upgraded-to-qt5-almalinux8-gcc14/43802/8?u=jcfr
> COMP: Ensure BUILD_JOB_SERVER_AWARE is set for external projects

- Libs/MRML/Core/vtkMRMLScene.cxx
- Libs/MRML/Core/vtkMRMLScene.h
- Libs/MRML/Core/vtkMRMLSequenceStorageNode.cxx
- Libs/MRML/Core/vtkMRMLSequenceStorageNode.h
Simple non-storable nodes that can save their entire state into the MRML scene (without using additional data files) are now saved as a simple `.mrml` file instead of a `.mrb` file. This improves the reading and writing performance of the sequence nodes, as there is no need to zip/unzip the file.
---
> [!NOTE]
>
> This pull request was created cherry-picking commit from @lassoan that was originally associated with https://github.com/Slicer/Slicer/pull/8693
> PERF: Improve sequence node storage performance for simple nodes

- Libs/vtkSegmentationCore/Testing/vtkSegmentationTest2.cxx
- Libs/vtkSegmentationCore/vtkOrientedImageDataResample.cxx
- Libs/vtkSegmentationCore/vtkOrientedImageDataResample.h
- Libs/vtkSegmentationCore/vtkSegmentation.cxx
- Libs/vtkSegmentationCore/vtkSegmentationModifier.cxx
When calling vtkSegmentation::CollapseBinaryLabelmaps with an empty segment, vtkOrientedImageDataResample::CalculateEffectiveExtent would find a maximum "invalid" extent, rather than the minimal one. Ex for an empty 1x1x1 image:
[1, -1, 1, -1, 1,-1]
Instead of:
[0, -1, 0, -1, 0, -1]
When calling SetExtent on an image, this could cause an error, since the size of the invalid extent could be negative, which would cause a bad_alloc error in vtkGenericDataArray.txx#428.
Fixed by setting invalid extents from vtkOrientedImageDataResample::CalculateEffectiveExtent to the minimal [0, -1, 0, -1, 0, -1]. Added tests with collapsing empty or small segments to vtkSegmentationTest2. Added proper initialization of extents.
> BUG: Fix crash in vtkSegmentation::CollapseBinaryLabelmaps

- Docs/user_guide/getting_started.md
- Add checklist to fix execution issues: verify rights, set +x, run from terminal.
- Document workaround for "Failed to obtain launcher executable name!" by moving binary to user’s home Software folder.
---
_Original description updated by @jcfr_
> DOC: Add Fedora 37+ launch troubleshooting

- Extensions/CMake/SlicerBlockBuildPackageAndUploadExtensions.cmake
Follow-up to 8cb7fc9d5d (“COMP: Ensure BUILD_JOB_SERVER_AWARE option is set for extensions external projects”, 2025-09-03) introduced through https://github.com/Slicer/Slicer/pull/8691.
Fix the `ExternalProject_Add()` argument: use `BUILD_JOB_SERVER_AWARE` (not `JOB_SERVER_AWARE`). The latter applies to custom steps, whereas the former enables GNU Make jobserver propagation for the ExternalProject’s build when a `BUILD_COMMAND` is used.
This prevents intermittent `gmake[*]: *** read jobs pipe: Bad file descriptor.` errors seen on builders using CMake ≥ 3.28 with parallel GNU Make.
> COMP: Set BUILD_JOB_SERVER_AWARE for extension ExternalProject on CMake ≥ 3.28

- Libs/MRML/Core/vtkMRMLFolderDisplayNode.cxx
- Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyFolderPlugin.h
Fix crash if folder node does not have associated displayable node
The fix was proposed in https://github.com/Slicer/Slicer/pull/8058, but that contained other changes that may need more work.
> BUG: Prevent crash on SH reparent without displayable node

- Modules/Scripted/SampleData/SampleData.py
Adapt SampleData test expectations to reflect the recent fix for multi-file volume loading. The test now asserts that only a single node is created (e.g., `.nhdr` + `.raw.gz` pair) instead of treating the sidecar file as a separate node.
Follows up on 2218414aeb ("BUG: Fix loading of multi-file volumes in SampleData module", 2025-09-08) introduced through the following pull request:
* https://github.com/Slicer/Slicer/pull/8710
---
This fixes failure like this one: https://slicer.cdash.org/tests/31072271
> BUG: Update SampleData test for multi-file volume loading behavior

- Docs/user_guide/modules/cropvolume.md
- Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.cxx
- Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.h
- Modules/Loadable/CropVolume/MRML/vtkMRMLCropVolumeParametersNode.cxx
- Modules/Loadable/CropVolume/MRML/vtkMRMLCropVolumeParametersNode.h
- Modules/Loadable/CropVolume/Resources/UI/qSlicerCropVolumeModuleWidget.ui
- Modules/Loadable/CropVolume/qSlicerCropVolumeModuleWidget.cxx
- Modules/Loadable/CropVolume/qSlicerCropVolumeModuleWidget.h
Orientation of the input volume can now be easily fixed in Crop Volume module using the new "Reorient volume" section.
Options are added to tune "Fit to volume" beheavior. It is now possible to align the cropped volume's ROI to the world coordinate system (or keep the current ROI orientation). This is useful if the user wants to align the cropped volume axes to the world coordinate system, for example to make segmentation in anatomical planes easier.
fixes #8415
@muratmaga
> ENH: Add volume reorientation to Crop Volume module

- CMakeLists.txt
- Docs/developer_guide/build_instructions/linux.md
- Docs/developer_guide/build_instructions/macos.md
- Docs/developer_guide/build_instructions/windows.md
This reverts https://github.com/Slicer/Slicer/commit/63cd66526938ccee4627dd8b4fc4235012e2fcd2 and https://github.com/Slicer/Slicer/commit/de382bd89e0641e7273a92d4e169e336ef772675 as a collection of third party dependencies have been updated to be compatible with CMake 4.
I have successfully built latest Slicer `main` with this branch on the Windows platform using CMake 4.1.1 along with Visual Studio 2022 17.12.4.
- Build ✔️ 
- Package ✔️ 
- Test ✔️
> COMP: Enable building with CMake 4

- Modules/Scripted/DICOMLib/DICOMProcesses.py
DICOMCommand inherits from both `DICOMProcess` and `DICOMProcessTLSMixin` but `DICOMProcess.__init__` did not call `super().__init__()`. As a side effect, the MRO stopped before `DICOMProcessTLSMixin.__init__` could set `_tlsSettingsKeyPrefix`.
This regression was introduced by c8d2b625516 ("ENH: Add TLS authentication support to DICOM Sender and Listener", 2024-12-31) and introduced the following error reported when running the test `py_nomainwindow_DCMTKPrivateDictTest`:
```
File "<string>", line 5, in <module>
File "<string>", line 8, in <module>
File "C:\D\P\S-0-build\Slicer-build\lib\Slicer-5.9\qt-scripted-modules\DICOMLib\DICOMProcesses.py", line 279, in start
self.args = self._args + self.tlsArguments()
^^^^^^^^^^^^^^^^^^^
File …
```
> BUG: Make DICOMProcess init cooperative so TLS mixin is initialized

- Applications/SlicerApp/Testing/Python/CMakeLists.txt
- Applications/SlicerApp/Testing/Python/SlicerStartupPreserveSysPathTest.py
- Applications/SlicerApp/Testing/Python/SlicerStartupPreserveSysPathTestHelperModule.py
- Applications/SlicerApp/Testing/Python/SlicerStartupPreserveSysPathTestHelperPackage/__init__.py
- Applications/SlicerApp/Testing/Python/SlicerStartupPreserveSysPathTestHelperScript.py
- Base/QTCore/qSlicerCoreApplication.cxx
_The original pull request description was update by @jcfr to describe the root cause and associated fix._
This PR fixes a regression where updating `argv` via the PyConfig API caused the live interpreter’s `sys.path` to be replaced with `config.module_search_paths`, dropping entries added during Slicer's module discovery. It also adds an application Python test.
In fa915a03fc4 ("BUG: Fix improper Python initialization causing inconsistent interpreter state", 2025-07-17) we switched to updating `argv` using `PyConfig_SetArgv()` and `_PyInterpreterState_SetConfig()`,
While correct for `argv`, the latter **repopulates `sys.path` from the config**, which typically lacks path inserted during Slicer module discovery. Result: imports depending on those entries could fail after startup.
Add …
> BUG: Preserve `sys.path` during Slicer module discovery & add startup test

- Docs/developer_guide/modules/transforms.md
- Libs/MRML/Core/Testing/CMakeLists.txt
- Libs/MRML/Core/Testing/vtkMRMLTransformSequenceStorageNodeTest1.cxx
- Libs/MRML/Core/Testing/vtkMRMLTransformStorageNodeTest2.cxx
- Libs/MRML/Core/vtkMRMLTransformSequenceStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTransformSequenceStorageNode.h
- Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx
- Libs/MRML/Core/vtkMRMLTransformStorageNode.h
- Modules/Loadable/Sequences/Logic/vtkSlicerSequencesLogic.cxx
- Modules/Loadable/Sequences/qSlicerSequencesReader.cxx
- Modules/Loadable/Transforms/qSlicerTransformsReader.cxx
Displacement field transform can be defined using a vector field that transforms from the target coordinate system to the source object (a.k.a. resampling transform, because it can be used to transform images by resampling; "from parent" in Slicer naming convention), or that transforms form the source object coordinate system to the target (a.k.a. modeling transform, because it can be used to transform geometric objects by moving their points; "to parent" in Slicer naming convention).
We use ITK readers/writers for storing of transforms in files, and since ITK is an image-oriented toolkit, it always stores resampling transforms in files. Slicer worked around this limitation by introducing special "inverse" transform classes - which specify that those transforms need to be inverted before …
> ENH: Add support for storing modeling displacement field transforms

- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.h
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect_p.h
- Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractLabelEffect.cxx
- Modules/Loadable/Segmentations/Logic/CMakeLists.txt
- Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentEditorLogic.cxx
- Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentEditorLogic.h
- Modules/Loadable/Segmentations/Testing/Python/SegmentEditorLogicTest.py
- Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
The aim of the PR is to make the new segment editor logic consistent with existing logic classes.
The following commits are included : 
- Rename vtkSegmentEditorLogic to vtkSlicerSegmentEditorLogic
- Make vtkSlicerSegmentEditorLogic inherit from MRMLAbstractLogic and use abstract logic observer mechanism
- Add vtkSlicerSegmentEditorLogic verbosity flag for developer warnings 
This PR is a follow up to #8722 remarks on implementation improvements.
> ENH: Segment Editor: class rename, MRML logic integration, and logging controls

- Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx
When a `.seg.nrrd` file contained all zeros then the segmentation geometry was not initialized correctly (image axes were not set to the directions used in the input file).
fixes #8714
> BUG: Fix geometry initialization from empty segmentation file

- Libs/MRML/Core/Testing/vtkMRMLNonlinearTransformNodeTest1.cxx
- Libs/MRML/Core/vtkMRMLTransformNode.cxx
Order of composite transform components were reversed when deep-copying a transform node. This error has been in the code for several years, but the error was just recently reported probably because composite transforms are not used very frequently.
fixes #8766
> BUG: Fixed cloning of composite transforms

- Libs/vtkITK/vtkITKImageSequenceReader.cxx
- Libs/vtkITK/vtkITKImageSequenceWriter.cxx
Previously vtkITKImageSequenceReader/Writer was not able to handle 2 component image sequences. This commit adds case handling for image sequences with 2 components.
> ENH: Add support for reading/writing 2 component sequence files
